### ISSUE TITLE
[CLI] fastai WandbCallback triggers error when running on multi TPU cores

### ISSUE THREAD

**Issue by butchland** [wandb/wandb#1808]
**Description**
Using the fastai WandbCallback on multiple TPU cores triggers an error:
`AssertionError: can only test a child process`

**Wandb features**
fastai WandbCallback (`fastai.callback.wandb.WandbCallback`)  
The error is in the wandb interface call (`wandb/sdk/interface/interface.py`) which
calls  python's `multiprocessing.process.is_alive` method which triggers the assertion
error.

**How to reproduce**
1. [Link to a reproducible script we can run to see the bug](https://git.io/Jtggo)
2. Describe what we have to do in order to trigger the issue:
      **Run the notebook - it has a run on colab button**
3. Add a zip file with the run folder  - _sorry already deleted the run folder after closing the session_
4. Additional notes: 
       * added a [public wandb project for review](https://wandb.ai/butchland/multicore-tpu-error)
       * running with just a single TPU core is fine (`FLAGS['num_cores'] = 1`) --  [see this run ](https://wandb.ai/butchland/multicore-tpu-error/runs/puwm2xkd)
       * running on multiple cores (`FLAGS['num_cores'] = 8`) didn't even capture the logs -- [see this run](https://wandb.ai/butchland/multicore-tpu-error/runs/t45maezb) and triggered the following stack trace:
 ```
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 330, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 324, in _start_fn
    fn(gindex, *args)
  File "<ipython-input-15-4dbd82bfa7f7>", line 2, in train_fastai_model
    print(f'xla: {rank} start train model')
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/lib/redirect.py", line 100, in new_write
    cb(name, data)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/wandb_run.py", line 726, in _console_callback
    self._backend.interface.publish_output(name, data)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/interface/interface.py", line 153, in publish_output
    self._publish_output(o)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/interface/interface.py", line 158, in _publish_output
    self._publish(rec)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/interface/interface.py", line 458, in _publish
    if self._process and not self._process.is_alive():
  File "/usr/lib/python3.6/multiprocessing/process.py", line 134, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 335, in _mp_start_fn
    file=sys.stderr)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/lib/redirect.py", line 100, in new_write
    cb(name, data)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/wandb_run.py", line 726, in _console_callback
    self._backend.interface.publish_output(name, data)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/interface/interface.py", line 153, in publish_output
    self._publish_output(o)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/interface/interface.py", line 158, in _publish_output
    self._publish(rec)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/interface/interface.py", line 458, in _publish
    if self._process and not self._process.is_alive():
  File "/usr/lib/python3.6/multiprocessing/process.py", line 134, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
```

**Environment**
- OS: [Ubuntu Bionic ]
- Environment: [ Google Colab]
- Python Version: [3.6]

**Initial Analysis (speculation, maybe 100% off )**

Upon review of the source code where the error was triggered, it seems that the wandb interface code was calling python's `multiprocessing.process` `is_alive` method which in turn asserts that the `is_alive` method can only be tested in the parent process -- since running on multiple tpu core is spawning child processes -- my theory is that in these spawned processes the `self._parent_pid` (the main process) is no longer equal to the `os.getpid()` of the child process. 

My *meager understanding* of running on multiple tpu cores is that although multiple processes are spawned, one of them is designated as the master (ie. ordinal = 0) which is the only process where I attached the WandbCallback (all the other spawned processes don't have it attached), hoping to ensure that WandbCallback doesn't write its log multiple times... but then I encountered this error. 

I might review the Pytorch Lightning implementation to see how they did this, as this might also give a clue on how to fix this -- which I don't think is a coding error - it might be more of a design issue -- in which case
feel free to reach out to me to design a fix (maybe in my[ fastai_xla_extensions](https://github.com/butchland/fastai_xla_extensions) library). 

Best regards,
Butch

**Comment by borisdayma** [comment]
Thanks a lot!
Tagging @morganmcg1 who had a similar issue and I believe he tried to use the rank 0 to target only master process.

**Comment by kptkin** [comment]
since there was no activity for a while on this issue, closing it.  feel free to open if the issue persist. Wasn't able to reproduce
