### ISSUE TITLE
[CLI] Running wandb to download dataset (stored as artifact) from W&B failed.

### ISSUE THREAD

**Issue by Yura32000** [wandb/wandb#1849]
Running wandb to download dataset (stored as artifact) from W&B failed.

```bash
wandb artifact get percepto/itasca/Itasca:v6
wandb: Downloading dataset artifact percepto/itasca/Itasca:v6
wandb: Downloading large artifact Itasca:v6, 2925.56MB. 8025 files... Traceback (most recent call last):
  File "/home/user/tf24/bin/wandb", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/user/tf24/lib/python3.8/site-packages/wandb/cli/cli.py", line 94, in wrapper
    return func(*args, **kwargs)
  File "/home/user/tf24/lib/python3.8/site-packages/wandb/cli/cli.py", line 1216, in get
    path = artifact.download(root=root)
  File "/home/user/tf24/lib/python3.8/site-packages/wandb/apis/public.py", line 2830, in download
    pool.map(partial(self._download_file, root=dirpath), manifest.entries)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/user/tf24/lib/python3.8/site-packages/wandb/apis/public.py", line 2868, in _download_file
    return self.get_path(name).download(root)
  File "/home/user/tf24/lib/python3.8/site-packages/wandb/apis/public.py", line 2734, in download
    cache_path = storage_policy.load_reference(
  File "/home/user/tf24/lib/python3.8/site-packages/wandb/sdk/wandb_artifacts.py", line 479, in load_reference
    return self._handler.load_path(self._cache, manifest_entry, local)
  File "/home/user/tf24/lib/python3.8/site-packages/wandb/sdk/wandb_artifacts.py", line 592, in load_path
    return self._handlers[url.scheme].load_path(
  File "/home/user/tf24/lib/python3.8/site-packages/wandb/sdk/wandb_artifacts.py", line 812, in load_path
    etag = self._etag_from_obj(obj)
  File "/home/user/tf24/lib/python3.8/site-packages/wandb/sdk/wandb_artifacts.py", line 928, in _etag_from_obj
    return obj.e_tag[1:-1]  # escape leading and trailing quote
  File "/home/user/tf24/lib/python3.8/site-packages/boto3/resources/factory.py", line 339, in property_loader
    self.load()
  File "/home/user/tf24/lib/python3.8/site-packages/boto3/resources/factory.py", line 505, in do_action
    response = action(self, *args, **kwargs)
  File "/home/user/tf24/lib/python3.8/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/user/tf24/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/user/tf24/lib/python3.8/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found
```
- Environment: Jupyter Lab (Ubuntu 20.04)
- Python Version: [eg. 3.8.7]

**Comment by ariG23498** [comment]
Hey @Yura32000 
Can you get us a code snippet and the artifact that you are downloading. This would let us reproducing the error better.

**Comment by Yura32000** [comment]
wandb artifact get percepto/itasca/Itasca:v6

while it worked before.

**Comment by Yura32000** [comment]
I found the bug. Sincve W&B dataset is just links to aws s3 ral files and when one of them is deleted from s3 then wand artifact get faild with this strange message. Please fix it or at least warn me and continue to download

**Comment by ariG23498** [comment]
Got it!
Thanks for the update! 😄

**Comment by ariG23498** [comment]
Update -- We are working on the error and will push a fix in the next CLI release. Keeping this ticket open until then. 😃

**Comment by anmolmann** [comment]
Hi @Yura32000 , I wanted to follow up on this issue and let you know we had fixed the issue a while ago. Apologies for the dealy in the follow up.
As a workaround, running a script from scratch and having a new clean s3 bucket with versioning from the start would help out sort this issue.
