### ISSUE TITLE
[Windows] Issue with Wandb console

### ISSUE THREAD

**Issue by cr0wley-zz** [wandb/wandb#1882]
**Describe the bug**
I don't have `.netrc` file for my authorization. While initializing wandb in a directory, the console asks for my authorization key from `[the Authorization page](https://wandb.ai/authorize)`. I copy my key but when I try to paste it to the console and press enter, the console throws an error. 

``` bash
Traceback (most recent call last):
  File "c:\users\devjyoti\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\devjyoti\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Devjyoti\aritra_ex\env\Scripts\wandb.exe\__main__.py", line 7, in <module>
  File "c:\users\devjyoti\aritra_ex\env\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\devjyoti\aritra_ex\env\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\devjyoti\aritra_ex\env\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\devjyoti\aritra_ex\env\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\devjyoti\aritra_ex\env\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\devjyoti\aritra_ex\env\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\devjyoti\aritra_ex\env\lib\site-packages\wandb\cli\cli.py", line 94, in wrapper
    return func(*args, **kwargs)
  File "c:\users\devjyoti\aritra_ex\env\lib\site-packages\wandb\cli\cli.py", line 328, in init
    ctx.invoke(login)
  File "c:\users\devjyoti\aritra_ex\env\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\devjyoti\aritra_ex\env\lib\site-packages\wandb\cli\cli.py", line 94, in wrapper
    return func(*args, **kwargs)
  File "c:\users\devjyoti\aritra_ex\env\lib\site-packages\wandb\cli\cli.py", line 247, in login
    wandb.login(relogin=relogin, key=key, anonymous=anon_mode, host=host, force=True)
  File "c:\users\devjyoti\aritra_ex\env\lib\site-packages\wandb\sdk\wandb_login.py", line 44, in login
    configured = _login(**kwargs)
  File "c:\users\devjyoti\aritra_ex\env\lib\site-packages\wandb\sdk\wandb_login.py", line 205, in _login
    wlogin.prompt_api_key()
  File "c:\users\devjyoti\aritra_ex\env\lib\site-packages\wandb\sdk\wandb_login.py", line 140, in prompt_api_key
    key = apikey.prompt_api_key(
  File "c:\users\devjyoti\aritra_ex\env\lib\site-packages\wandb\sdk\lib\apikey.py", line 136, in prompt_api_key
    write_key(settings, key, api=api)
  File "c:\users\devjyoti\aritra_ex\env\lib\site-packages\wandb\sdk\lib\apikey.py", line 221, in write_key
    raise ValueError("API key must be 40 characters long, yours was %s" % len(key))
ValueError: API key must be 40 characters long, yours was 1
```

**To Reproduce**
1. Create a virtual env
2. Activate the environment
3. ` pip install wandb`
4. `wandb init`
5. Copy the authorization key and try pasting it in the console

**Expected behavior**
A .netrc file will be created containing the authorization key in my home folder. 

**Screenshots**
![image](https://user-images.githubusercontent.com/43583140/108813094-5685ea00-75d6-11eb-8632-6adfbe89c60b.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10.0.19041 Build 19041]
 - Browser [chrome Version 88.0.4324.182 (Official Build) (64-bit)]
 - Version [wandb, version 0.10.20]

**Comment by vanpelt** [comment]
Hey @cr0wley-zz you can [set the environment variable](https://superuser.com/questions/79612/setting-and-getting-windows-environment-variables-from-the-command-prompt) `WANDB_API_KEY=XXXX` where XXX is your api key from the authorize page to get past this issue.  

We're unable to reproduce this specific error from calling `wandb login`.  If you paste what you copied from the browser into a an application like Notepad are you seeing the 40 character api key?

**Comment by cr0wley-zz** [comment]
Hello @vanpelt , thank you for looking into this. Yes, if I come out of the console, the key is visible anywhere I try to paste it. Only in the console it gets registered as a 1 digit input.

**Comment by farizrahman4u** [comment]
I was able to reproduce the issue on Windows. A quick work around would be to right click instead of ctrl+v to paste the API key.
