### ISSUE TITLE
[CLI] Wandb error using PyTorch Lightning and Ray Tune

### ISSUE THREAD

**Issue by MohammedAljahdali** [wandb/wandb#1946]
**Description**
I am using ray tune and pytorch lightning, therefore I run multiple wandb runs in a single script. I use wandb.run.finish() at the start of the training function or using wand_mixin from ray tune to end a wandb run and start the new one. But after ending the wandb run and starting the new one I get the following error:

```
Epoch 0:  22%|████████████████████▎                                                                         | 181/840 [00:20<01:15,  8.68it/s, loss=3.39, v_num=4-02, val_loss=3.33, val_accuracy=0.0312, train_loss_step=3.35, train_accuracy_step=0.0625]2021-03-11 02:14:26,056  ERROR function_runner.py:254 -- Runner Thread raised error.
Traceback (most recent call last):
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 561, in train
    self.train_loop.run_training_epoch()
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\pytorch_lightning\trainer\training_loop.py", line 625, in run_training_epoch
    self.trainer.run_evaluation(on_epoch=True)
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 669, in run_evaluation
    self.evaluation_loop.on_evaluation_end()
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\pytorch_lightning\trainer\evaluation_loop.py", line 101, in on_evaluation_end
    self.trainer.call_hook('on_validation_end', *args, **kwargs)
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 926, in call_hook
    trainer_hook(*args, **kwargs)
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\pytorch_lightning\trainer\callback_hook.py", line 177, in on_validation_end
    callback.on_validation_end(self, self.get_model())
  File "C:\Users\Mohammed\AppData\Roaming\Python\Python38\site-packages\ray\tune\integration\pytorch_lightning.py", line 115, in on_validation_end
    self._handle(trainer, pl_module)
  File "C:\Users\Mohammed\AppData\Roaming\Python\Python38\site-packages\ray\tune\integration\pytorch_lightning.py", line 189, in _handle
    tune.report(**report_dict)
  File "C:\Users\Mohammed\AppData\Roaming\Python\Python38\site-packages\ray\tune\session.py", line 92, in report
    return _session(_metric, **kwargs)
  File "C:\Users\Mohammed\AppData\Roaming\Python\Python38\site-packages\ray\tune\function_runner.py", line 187, in __call__
    sys.exit(0)
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\wandb\sdk\wandb_run.py", line 115, in exit
    self._orig_exit(orig_code)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mohammed\AppData\Roaming\Python\Python38\site-packages\ray\tune\function_runner.py", line 248, in run
    self._entrypoint()
  File "C:\Users\Mohammed\AppData\Roaming\Python\Python38\site-packages\ray\tune\function_runner.py", line 315, in entrypoint
    return self._trainable_func(self.config, self._status_reporter,
  File "C:\Users\Mohammed\AppData\Roaming\Python\Python38\site-packages\ray\tune\function_runner.py", line 576, in _trainable_func
    output = fn()
  File "C:\Users\Mohammed\AppData\Roaming\Python\Python38\site-packages\ray\tune\function_runner.py", line 651, in _inner
    inner(config, checkpoint_dir=None)
  File "C:\Users\Mohammed\AppData\Roaming\Python\Python38\site-packages\ray\tune\function_runner.py", line 645, in inner
    fn(config, **fn_kwargs)
  File "train.py", line 131, in train
    trainer.fit(model, datamodule=dm)
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 510, in fit
    results = self.accelerator_backend.train()
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\pytorch_lightning\accelerators\accelerator.py", line 57, in train
    return self.train_or_test()
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\pytorch_lightning\accelerators\accelerator.py", line 74, in train_or_test
    results = self.trainer.train()
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 589, in train
    self.train_loop.on_train_end()
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\pytorch_lightning\trainer\training_loop.py", line 160, in on_train_end
    self.trainer.call_hook("on_train_end")
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 926, in call_hook
    trainer_hook(*args, **kwargs)
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\pytorch_lightning\trainer\callback_hook.py", line 117, in on_train_end
    callback.on_train_end(self, self.get_model())
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\pytorch_lightning\callbacks\progress.py", line 361, in on_train_end
    self.main_progress_bar.close()
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\tqdm\std.py", line 1287, in close
    fp_write('')
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\tqdm\std.py", line 1284, in fp_write
    self.fp.write(_unicode(s))
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\tqdm\utils.py", line 142, in inner
    return func(*args, **kwargs)
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\wandb\sdk\lib\redirect.py", line 100, in new_write
    cb(name, data)
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\wandb\sdk\wandb_run.py", line 796, in _console_callback
    self._backend.interface.publish_output(name, data)
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\wandb\sdk\interface\interface.py", line 187, in publish_output
    self._publish_output(o)
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\wandb\sdk\interface\interface.py", line 192, in _publish_output
    self._publish(rec)
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\wandb\sdk\interface\interface.py", line 518, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 561, in train
    self.train_loop.run_training_epoch()
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\pytorch_lightning\trainer\training_loop.py", line 625, in run_training_epoch
    self.trainer.run_evaluation(on_epoch=True)
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 669, in run_evaluation
    self.evaluation_loop.on_evaluation_end()
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\pytorch_lightning\trainer\evaluation_loop.py", line 101, in on_evaluation_end
    self.trainer.call_hook('on_validation_end', *args, **kwargs)
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 926, in call_hook
    trainer_hook(*args, **kwargs)
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\pytorch_lightning\trainer\callback_hook.py", line 177, in on_validation_end
    callback.on_validation_end(self, self.get_model())
  File "C:\Users\Mohammed\AppData\Roaming\Python\Python38\site-packages\ray\tune\integration\pytorch_lightning.py", line 115, in on_validation_end
    self._handle(trainer, pl_module)
  File "C:\Users\Mohammed\AppData\Roaming\Python\Python38\site-packages\ray\tune\integration\pytorch_lightning.py", line 189, in _handle
    tune.report(**report_dict)
  File "C:\Users\Mohammed\AppData\Roaming\Python\Python38\site-packages\ray\tune\session.py", line 92, in report
    return _session(_metric, **kwargs)
  File "C:\Users\Mohammed\AppData\Roaming\Python\Python38\site-packages\ray\tune\function_runner.py", line 187, in __call__
    sys.exit(0)
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\wandb\sdk\wandb_run.py", line 115, in exit
    self._orig_exit(orig_code)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\Mohammed\AppData\Roaming\Python\Python38\site-packages\ray\tune\function_runner.py", line 267, in run
    raise e
  File "C:\Users\Mohammed\AppData\Roaming\Python\Python38\site-packages\ray\tune\function_runner.py", line 248, in run
    self._entrypoint()
  File "C:\Users\Mohammed\AppData\Roaming\Python\Python38\site-packages\ray\tune\function_runner.py", line 315, in entrypoint
    return self._trainable_func(self.config, self._status_reporter,
  File "C:\Users\Mohammed\AppData\Roaming\Python\Python38\site-packages\ray\tune\function_runner.py", line 576, in _trainable_func
    output = fn()
  File "C:\Users\Mohammed\AppData\Roaming\Python\Python38\site-packages\ray\tune\function_runner.py", line 651, in _inner
    inner(config, checkpoint_dir=None)
  File "C:\Users\Mohammed\AppData\Roaming\Python\Python38\site-packages\ray\tune\function_runner.py", line 645, in inner
    fn(config, **fn_kwargs)
  File "train.py", line 131, in train
    trainer.fit(model, datamodule=dm)
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 510, in fit
    results = self.accelerator_backend.train()
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\pytorch_lightning\accelerators\accelerator.py", line 57, in train
    return self.train_or_test()
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\pytorch_lightning\accelerators\accelerator.py", line 74, in train_or_test
    results = self.trainer.train()
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 589, in train
    self.train_loop.on_train_end()
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\pytorch_lightning\trainer\training_loop.py", line 160, in on_train_end
    self.trainer.call_hook("on_train_end")
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 926, in call_hook
    trainer_hook(*args, **kwargs)
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\pytorch_lightning\trainer\callback_hook.py", line 117, in on_train_end
    callback.on_train_end(self, self.get_model())
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\pytorch_lightning\callbacks\progress.py", line 361, in on_train_end
    self.main_progress_bar.close()
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\tqdm\std.py", line 1287, in close
    fp_write('')
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\tqdm\std.py", line 1284, in fp_write
    self.fp.write(_unicode(s))
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\tqdm\utils.py", line 142, in inner
    return func(*args, **kwargs)
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\wandb\sdk\lib\redirect.py", line 100, in new_write
    cb(name, data)
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\wandb\sdk\wandb_run.py", line 796, in _console_callback
    self._backend.interface.publish_output(name, data)
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\wandb\sdk\interface\interface.py", line 187, in publish_output
    self._publish_output(o)
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\wandb\sdk\interface\interface.py", line 192, in _publish_output
    self._publish(rec)
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\wandb\sdk\interface\interface.py", line 518, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
Epoch 0:  40%|██████████████████████████████████████                                                        | 340/840 [00:37<00:54,  9.12it/s, loss=3.36, v_num=4-02, val_loss=3.33, val_accuracy=0.0312, train_loss_step=3.27, train_accuracy_step=0.0625] 
```
Moreover, wandb run ends successfully and I get the following:
```
wandb: Tracking run with wandb version 0.10.22
wandb: Syncing run model-params-dims=128,model-params-layer_size=4,model-params-num_layers=4,general-batch_size=16_11/03/2021 02:14:02
wandb:  View project at link
wandb:  View run at link
wandb: Run data is saved locally in C:\Users\Mohammed\ray_results\tune_asha\_inner_d827b_00001_1_general-batch_size=16,model-params-dims=128,model-params-layer_size=4,model-params-num_layers=4_2021-03-11_02-13-54\wandb\run-20210311_021402-model-params-dims=128,model-params-layer_size=4,model-params-num_layers=4,general-batch_size=16_11-03-2021_02-14-02
wandb: Run `wandb offline` to turn off syncing.
```

**Wandb features**
This my Wandb related code, at the start of the training function:
```
 try:
       wandb.run.finish()
except:
       print("First Trial")
```
Before creating the PL trainer:
`logger = WandbLogger(**cfg.logger.params)`
 

**Environment**
- OS: Windows 10
- W&B Version:  0.10.22

- Python Version: 3.8.5

**Comment by vanpelt** [comment]
Hey @MohammedAljahdali can you upgrade your installation of wandb to the latest version with `pip install wandb --upgrade` then try setting the environment variable WANDB_START_METHOD=thread and run the script again?

**Comment by MohammedAljahdali** [comment]
Thank you @vanpelt tried what you said, and I still get the same error, however some times only this part of the error:
```
Epoch 0:  90%|████████████████████████████████████████████████████▉      | 1506/1680 [01:50<00:12, 13.68it/s, loss=3.36, v_num=3-35, val_loss=3.35, val_accuracy=0, train_loss_step=3.31, train_accuracy_step=0]Exception ignored in: <function tqdm.__del__ at 0x0000029F427B94C0>██████████████████████████▏                                                                                 | 161/336 [00:02<00:02, 65.11it/s]
Traceback (most recent call last):
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\tqdm\std.py", line 1145, in __del__
    self.close()
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\tqdm\std.py", line 1287, in close
    fp_write('')
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\tqdm\std.py", line 1284, in fp_write
    self.fp.write(_unicode(s))
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\tqdm\utils.py", line 142, in inner
    return func(*args, **kwargs)
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\wandb\sdk\lib\redirect.py", line 100, in new_write
    cb(name, data)
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\wandb\sdk\wandb_run.py", line 796, in _console_callback
    self._backend.interface.publish_output(name, data)
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\wandb\sdk\interface\interface.py", line 187, in publish_output
    self._publish_output(o)
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\wandb\sdk\interface\interface.py", line 192, in _publish_output
    self._publish(rec)
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\wandb\sdk\interface\interface.py", line 518, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
```
