### ISSUE TITLE
[CLI] matplotlib Figure object not JSON serializable

### ISSUE THREAD

**Issue by rubencart** [wandb/wandb#2063]
**Description**
[You documentation](https://docs.wandb.ai/library/log#matplotlib) says "You can pass a matplotlib pyplot or figure object to `wandb.log()`". However, when I do this, at the moment of the commit, I get the following error.

```python
Traceback (most recent call last):
  File "src/main.py", line 236, in <module>
    main(cfg, train_ns_cfg)
  File "src/main.py", line 149, in main
    trainer.fit(model, datamodule=data_module)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 499, in fit
    self.dispatch()
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 546, in dispatch
    self.accelerator.start_training(self)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 73, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 114, in start_training
    self._results = trainer.run_train()
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 637, in run_train
    self.train_loop.run_training_epoch()
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 560, in run_training_epoch
    self.trainer.logger_connector.log_train_epoch_end_metrics(
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py", line 439, in log_train_epoch_end_metrics
    self.log_metrics(epoch_log_metrics, {})
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py", line 236, in log_metrics
    self.trainer.logger.save()
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/pytorch_lightning/loggers/base.py", line 304, in save
    self._finalize_agg_metrics()
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/pytorch_lightning/loggers/base.py", line 145, in _finalize_agg_metrics
    self.log_metrics(metrics=metrics_to_log, step=agg_step)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/pytorch_lightning/utilities/distributed.py", line 42, in wrapped_fn
    return fn(*args, **kwargs)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/pytorch_lightning/loggers/wandb.py", line 192, in log_metrics
    self.experiment.log({**metrics, 'trainer/global_step': step})
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1055, in log
    self.history._row_add(data)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/wandb/sdk/wandb_history.py", line 44, in _row_add
    self._flush()
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/wandb/sdk/wandb_history.py", line 59, in _flush
    self._callback(row=self._data, step=self._step)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 805, in _history_callback
    self._backend.interface.publish_history(
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 226, in publish_history
    item.value_json = json_dumps_safer_history(v)  # type: ignore
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/wandb/util.py", line 655, in json_dumps_safer_history
    return json.dumps(obj, cls=WandBHistoryJSONEncoder, **kwargs)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/wandb/util.py", line 622, in default
    return json.JSONEncoder.default(self, obj)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Figure is not JSON serializable

```

**Wandb features**
I'm calling `self.trainer.logger.experiment.log({'examples': wandb_images}, commit=False)` in a pytorch-lightning module where `wandb_images` is a list of `matplotlib.figure.Figure` instances ([link](https://matplotlib.org/stable/api/figure_api.html#matplotlib.figure.Figure)).

Am I doing something wrong? If so, could you update your docs please?

**How to reproduce**
1. Link to a reproducible script we can run to see the bug
2. Describe what we have to do in order to trigger the issue
3. Add a zip file with the run folder 

The code below reproduces the error.

```python
import matplotlib.pyplot as plt
import seaborn
import torch
from pytorch_lightning.loggers import WandbLogger

from utils import mkdir_p

mkdir_p('./output/tmp')
wandb_logger = WandbLogger(project='MMMAli', save_dir='./output/tmp', offline=True)

fig1: plt.Figure = plt.figure()
ax1 = seaborn.heatmap(torch.randn((10, 10)),
                      square=True,
                      vmin=0.0, vmax=1.0,
                      cbar=False,
                      )
plt.subplots_adjust(bottom=0.2, left=0.2, hspace=0.8)
fig1.add_axes(ax1)

wandb_logger.experiment.log({'examples': [fig1]}, commit=False)
```
Actually, adding the seaborn output is not even necessary to trigger the error.

```python
import matplotlib.pyplot as plt
from pytorch_lightning.loggers import WandbLogger

wandb_logger = WandbLogger(project='MMMAli', save_dir='./output/tmp', offline=True)

fig1: plt.Figure = plt.figure()

wandb_logger.experiment.log({'examples': [fig1]}, commit=False)
```

**Environment**
- OS: Ubuntu 18.04
- Environment: conda
- Python Version: 3.8.8
- Wandb: 0.10.25

**Comment by ariG23498** [comment]
Hey @rubencart 

I have tried reproducing the ticket. This is the [GIST](https://gist.github.com/ariG23498/dd5c0449166beac5e2bb68a11809d1a3) that is a full-fledged repro of your issue. The wandb dashboard corresponding to the GIST can be found [here]()https://wandb.ai/repro/GH-2063.

**My observations**:
1. Sending a `plt.figure` as a list is harmful as the lists are serialised and the `plt.figure` cannot be serialised.
2. Upon sending the `plt.figure` as a solo entity, wandb complained about `ValueError: min() arg is an empty sequence`. This might be related to the fact that the figure is not filled with anything yet.
3. Later when I created a plot and then sent the `plt` object over to be logged, everything was working perfectly.

I would like for you to comment of the steps that I have taken and let us know if this helps you. We might need to change the docs as you have suggested. Thanks for the ticket! 👍

**Comment by rubencart** [comment]
I see, thank you! 

It would be useful to me if I could submit `plt.Figure` instances though and not just the `plt` object, because I'm generating multiple figures at once. Maybe I'm not understanding it correctly, but I think that if you can only submit `plt`, you'd need to generate a figure, log it, close it, generate the next one, log it,... and so on.  Is that correct? So then you wouldn't be able to generate in batch and then log in batch?

Also, when I fill the `plt.Figure` object and log it not as a list but as a single entity, I get the following error: `wandb.errors.Error: plotly is required to log interactive plots, install with: pip install plotly or convert the plot to an image with 'wandb.Image(plt)'`. If `plotly` is required as an extra dependency that you need to install for this yourself, maybe it would also make sense to mention this in the docs?

After installing `plotly`, when logging a single (non-empty) `plt.Figure` like in the snippet below, I get the following error (both at the time of the log and at the end of the script).
```python
import matplotlib.pyplot as plt
import seaborn
import torch
from pytorch_lightning.loggers import WandbLogger

wandb_logger = WandbLogger(project='MMMAli', save_dir='./output/tmp', offline=True)

fig1: plt.Figure = plt.figure()
ax1 = seaborn.heatmap(torch.randn((10, 10)),
                      square=True,
                      vmin=0.0, vmax=1.0,
                      cbar=False,
                      )
plt.subplots_adjust(bottom=0.2, left=0.2, hspace=0.8)
fig1.add_axes(ax1)

wandb_logger.experiment.log({'examples': fig1})
```
```python
Traceback (most recent call last):
  File "src/main.py", line 236, in <module>
    main(cfg, train_ns_cfg)
  File "src/main.py", line 149, in main
    trainer.fit(model, datamodule=data_module)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 499, in fit
    self.dispatch()
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 546, in dispatch
    self.accelerator.start_training(self)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 73, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 114, in start_training
    self._results = trainer.run_train()
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 637, in run_train
    self.train_loop.run_training_epoch()
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 560, in run_training_epoch
    self.trainer.logger_connector.log_train_epoch_end_metrics(
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py", line 439, in log_train_epoch_end_metrics
    self.log_metrics(epoch_log_metrics, {})
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py", line 236, in log_metrics
    self.trainer.logger.save()
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/pytorch_lightning/loggers/base.py", line 304, in save
    self._finalize_agg_metrics()
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/pytorch_lightning/loggers/base.py", line 145, in _finalize_agg_metrics
    self.log_metrics(metrics=metrics_to_log, step=agg_step)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/pytorch_lightning/utilities/distributed.py", line 42, in wrapped_fn
    return fn(*args, **kwargs)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/pytorch_lightning/loggers/wandb.py", line 192, in log_metrics
    self.experiment.log({**metrics, 'trainer/global_step': step})
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1055, in log
    self.history._row_add(data)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/wandb/sdk/wandb_history.py", line 44, in _row_add
    self._flush()
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/wandb/sdk/wandb_history.py", line 59, in _flush
    self._callback(row=self._data, step=self._step)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 805, in _history_callback
    self._backend.interface.publish_history(
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 217, in publish_history
    data = data_types.history_dict_to_json(run, data, step=step)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/wandb/sdk/data_types.py", line 2060, in history_dict_to_json
    payload[key] = val_to_json(run, key, val, namespace=step)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/wandb/sdk/data_types.py", line 2088, in val_to_json
    val = Plotly.make_plot_media(val)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/wandb/sdk/data_types.py", line 2010, in make_plot_media
    val = util.matplotlib_to_plotly(val)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/wandb/util.py", line 414, in matplotlib_to_plotly
    return tools.mpl_to_plotly(obj)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/plotly/tools.py", line 112, in mpl_to_plotly
    matplotlylib.Exporter(renderer).run(fig)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/plotly/matplotlylib/mplexporter/exporter.py", line 51, in run
    self.crawl_fig(fig)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/plotly/matplotlylib/mplexporter/exporter.py", line 118, in crawl_fig
    self.crawl_ax(ax)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/plotly/matplotlylib/mplexporter/exporter.py", line 123, in crawl_ax
    props=utils.get_axes_properties(ax)):
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/plotly/matplotlylib/mplexporter/utils.py", line 272, in get_axes_properties
    'axes': [get_axis_properties(ax.xaxis),
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/plotly/matplotlylib/mplexporter/utils.py", line 236, in get_axis_properties
    props['grid'] = get_grid_style(axis)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/plotly/matplotlylib/mplexporter/utils.py", line 246, in get_grid_style
    if axis._gridOnMajor and len(gridlines) > 0:
AttributeError: 'XAxis' object has no attribute '_gridOnMajor'
```
When I log the `plt` object I get the same `AttributeError` at first, when doing the log, and at the end of the run, when wandb tries to publish the history, I get the `ValueError: min() arg is an empty sequence` error.
```python
import matplotlib.pyplot as plt
import seaborn
import torch
from pytorch_lightning.loggers import WandbLogger

wandb_logger = WandbLogger(project='MMMAli', save_dir='./output/tmp', offline=True)

fig1: plt.Figure = plt.figure()
ax1 = seaborn.heatmap(torch.randn((10, 10)),
                      square=True,
                      vmin=0.0, vmax=1.0,
                      cbar=False,
                      )
plt.subplots_adjust(bottom=0.2, left=0.2, hspace=0.8)
fig1.add_axes(ax1)

wandb_logger.experiment.log({'examples': plt})
```
```python
Traceback (most recent call last):
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1502, in _atexit_cleanup
    self._on_finish()
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1638, in _on_finish
    self.history._flush()
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/wandb/sdk/wandb_history.py", line 59, in _flush
    self._callback(row=self._data, step=self._step)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 805, in _history_callback
    self._backend.interface.publish_history(
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 217, in publish_history
    data = data_types.history_dict_to_json(run, data, step=step)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/wandb/sdk/data_types.py", line 2060, in history_dict_to_json
    payload[key] = val_to_json(run, key, val, namespace=step)   
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/wandb/sdk/data_types.py", line 2088, in val_to_json
    val = Plotly.make_plot_media(val)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/wandb/sdk/data_types.py", line 2010, in make_plot_media
    val = util.matplotlib_to_plotly(val)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/wandb/util.py", line 414, in matplotlib_to_plotly
    return tools.mpl_to_plotly(obj)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/plotly/tools.py", line 112, in mpl_to_plotly
    matplotlylib.Exporter(renderer).run(fig)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/plotly/matplotlylib/mplexporter/exporter.py", line 51, in run
    self.crawl_fig(fig)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/plotly/matplotlylib/mplexporter/exporter.py", line 115, in crawl_fig
    with self.renderer.draw_figure(fig=fig,
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/plotly/matplotlylib/mplexporter/renderers/base.py", line 45, in draw_figure
    self.open_figure(fig=fig, props=props)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/plotly/matplotlylib/renderer.py", line 90, in open_figure
    self.mpl_x_bounds, self.mpl_y_bounds = mpltools.get_axes_bounds(fig)
  File "/cw/liir/NoCsBack/testliir/rubenc/miniconda3/envs/alienv/lib/python3.8/site-packages/plotly/matplotlylib/mpltools.py", line 265, in get_axes_bounds
    x_min, y_min, x_max, y_max = min(x_min), min(y_min), max(x_max), max(y_max)
ValueError: min() arg is an empty sequence
```
So maybe it has something to do with the seaborn heatmap?

The following does work.
```python
import matplotlib.pyplot as plt
import torch
from pytorch_lightning.loggers import WandbLogger

wandb_logger = WandbLogger(project='MMMAli', save_dir='./output/tmp', offline=True)

fig1: plt.Figure = plt.figure()
ax2 = fig1.add_subplot(111)
ax2.imshow(torch.randn((10, 10), dtype=torch.float), cmap='hot', interpolation='nearest')

plt.subplots_adjust(bottom=0.2, left=0.2, hspace=0.8)

wandb_logger.experiment.log({'examples': fig1})
```
But it would be nice to be able to use the seaborn plot.

**Comment by sydholl** [comment]
We are closing this issue due to inactivity. If you feel that it merits additional review, please provide a reproduction and add a comment explaining why. Thank you.
