### ISSUE TITLE
[CLI] The wandb backend process has shutdown

### ISSUE THREAD

**Issue by will-maclean** [wandb/wandb#2381]
**Description**
`The wandb backend process has shutdown`
When starting a simple wandb run, I get the error telling me the wandb backend process has shutdown

**Wandb features**
wandb.init() is where the code fails

**How to reproduce**
```
import wandb

wandb.login(key="my_key")
wandb.init(entity="my_entity_name", project="my_project")
```

**Environment**
MacBook Air (M1, 2020)
- OS: Mac OS Big Sur 11.4
- Environment: conda env on local machine
- Python Version: Python 3.9.5

**Full Error**
```
wandb: Currently logged in as: me (use `wandb login --relogin` to force relogin)
wandb: Appending key for api.wandb.ai to your netrc file: /Users/me/.netrc
wandb: Tracking run with wandb version 0.10.33
wandb: Syncing run amber-rain-15
wandb:  View project at https://wandb.ai/me/project
wandb:  View run at https://wandb.ai/me/project/runs/runs
wandb: Run data is saved locally in <path>
wandb: Run `wandb offline` to turn off syncing.
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/Users/me/miniconda3/envs/project/lib/python3.9/threading.py", line 954, in _bootstrap_inner
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/Users/me/miniconda3/envs/project/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/Users/me/miniconda3/envs/project/lib/python3.9/threading.py", line 892, in run
    self.run()
  File "/Users/me/miniconda3/envs/project/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/me/miniconda3/envs/project/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 183, in check_network_status
    self._target(*self._args, **self._kwargs)
  File "/Users/me/miniconda3/envs/project/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 201, in check_status
    status_response = self._interface.communicate_network_status()
  File "/Users/me/miniconda3/envs/project/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 755, in communicate_network_status
    status_response = self._interface.communicate_stop_status()
  File "/Users/me/miniconda3/envs/project/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 743, in communicate_stop_status
    resp = self._communicate(req, timeout=timeout, local=True)
  File "/Users/me/miniconda3/envs/project/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 545, in _communicate
    resp = self._communicate(req, timeout=timeout, local=True)

  File "/Users/me/miniconda3/envs/project/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 545, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/Users/me/miniconda3/envs/project/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 550, in _communicate_async
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/Users/me/miniconda3/envs/project/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 550, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception:     raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
The wandb backend process has shutdown
```

**Comment by vanpelt** [comment]
Hey @will-maclean can you share the `wandb/debug-internal.log` file found relative to your training script?

**Comment by will-maclean** [comment]
```
2021-07-12 19:12:44,020 INFO    MainThread:62686 [internal.py:wandb_internal():88] W&B internal server running at pid: 62686, started at: 2021-07-12 19:12:44.020452
2021-07-12 19:12:44,022 INFO    WriterThread:62686 [datastore.py:open_for_write():80] open: /Users/me/code/testproject/wandb/run-20210712_191243-4gcdp66z/run-4gcdp66z.wandb
2021-07-12 19:12:44,022 DEBUG   HandlerThread:62686 [handler.py:handle_request():124] handle_request: check_version
2021-07-12 19:12:44,023 DEBUG   SenderThread:62686 [sender.py:send():179] send: header
2021-07-12 19:12:44,023 DEBUG   SenderThread:62686 [sender.py:send_request():193] send_request: check_version
2021-07-12 19:12:44,118 DEBUG   SenderThread:62686 [sender.py:send():179] send: run
2021-07-12 19:12:44,472 INFO    SenderThread:62686 [dir_watcher.py:__init__():168] watching files in: /Users/bill/code/l2rpn/wandb/run-20210712_191243-4gcdp66z/files
2021-07-12 19:12:44,472 INFO    SenderThread:62686 [sender.py:_start_run_threads():716] run started: 4gcdp66z with start time 1626081163
2021-07-12 19:12:44,473 DEBUG   SenderThread:62686 [sender.py:send():179] send: summary
2021-07-12 19:12:44,473 INFO    SenderThread:62686 [sender.py:_save_file():841] saving file wandb-summary.json with policy end
2021-07-12 19:12:44,474 DEBUG   HandlerThread:62686 [handler.py:handle_request():124] handle_request: run_start

```

**Comment by vanpelt** [comment]
Hey @will-maclean this may be due to a corrupt git repositiory or other edge case in our code saving logic.  Can you try running the script with:

```
os.environ["WANDB_DISABLE_CODE"] = "true"
```

If that doesn't work, attempting with:

```
os.environ["WANDB_START_METHOD"] = "thread"
```

May fix the shutdown issue.  If you're still seeing this, the `debug.log` file would also be helpful.

**Comment by will-maclean** [comment]
Thanks for the suggestion. Unfortunately, neither of those fixes worked. 

Here's the debug.log file:

```
2021-07-13 21:29:09,470 INFO    MainThread:68852 [wandb_setup.py:_flush():69] setting env: {'disable_code': 'true', 'start_method': 'thread'}
2021-07-13 21:29:09,470 INFO    MainThread:68852 [wandb_setup.py:_flush():69] setting login settings: {'api_key': 'key'}
2021-07-13 21:29:09,471 INFO    MainThread:68852 [wandb_setup.py:_flush():69] setting login settings: {'api_key': 'key'}
2021-07-13 21:29:09,471 INFO    MainThread:68852 [wandb_setup.py:_flush():69] setting login settings: {}
2021-07-13 21:29:09,471 INFO    MainThread:68852 [wandb_init.py:_log_setup():337] Logging user logs to /path/logs/debug.log
2021-07-13 21:29:09,471 INFO    MainThread:68852 [wandb_init.py:_log_setup():338] Logging internal logs to /path/logs/debug-internal.log
2021-07-13 21:29:09,471 INFO    MainThread:68852 [wandb_init.py:init():370] calling init triggers
2021-07-13 21:29:09,471 INFO    MainThread:68852 [wandb_init.py:init():375] wandb.init called with sweep_config: {}
config: {}
2021-07-13 21:29:09,471 INFO    MainThread:68852 [wandb_init.py:init():419] starting backend
2021-07-13 21:29:09,485 INFO    MainThread:68852 [backend.py:ensure_launched():135] starting backend process...
2021-07-13 21:29:09,485 INFO    MainThread:68852 [backend.py:ensure_launched():139] started backend process with pid: 0
2021-07-13 21:29:09,486 INFO    MainThread:68852 [wandb_init.py:init():424] backend started and connected
2021-07-13 21:29:09,486 INFO    wandb_internal:68852 [internal.py:wandb_internal():88] W&B internal server running at pid: 68852, started at: 2021-07-13 21:29:09.485476
2021-07-13 21:29:09,489 INFO    MainThread:68852 [wandb_init.py:init():472] updated telemetry
2021-07-13 21:29:09,490 INFO    MainThread:68852 [wandb_init.py:init():491] communicating current version
2021-07-13 21:29:09,491 INFO    WriterThread:68852 [datastore.py:open_for_write():80] open: /path/run-1yjy81pt.wandb
2021-07-13 21:29:09,572 INFO    MainThread:68852 [wandb_init.py:init():496] got version response 
2021-07-13 21:29:09,573 INFO    MainThread:68852 [wandb_init.py:init():504] communicating run to backend with 30 second timeout
2021-07-13 21:29:10,104 INFO    SenderThread:68852 [dir_watcher.py:__init__():168] watching files in: /path/files
2021-07-13 21:29:10,106 INFO    MainThread:68852 [wandb_init.py:init():529] starting run threads in backend
2021-07-13 21:29:10,106 INFO    SenderThread:68852 [sender.py:_start_run_threads():716] run started: 1yjy81pt with start time 1626175749
2021-07-13 21:29:10,110 INFO    SenderThread:68852 [sender.py:_save_file():841] saving file wandb-summary.json with policy end
```

**Comment by vanpelt** [comment]
Can you also share the user logs from the `debug.log` file.  My only guess at this point is that your OS is killing the internal process due to memory pressure.  How much free memory do you have?

**Comment by will-maclean** [comment]
That's all there is in the `debug.log` file. I have a 16GB machine and it doesn't get anywhere near full memory for this script

**Comment by vanpelt** [comment]
Hey @will-maclean this is really strange.  Would you be open to jumping onto a screenshare to try to debug what's happening live?  My email is vanpelt@wandb.com we can set something up first thing next week if you're available.

**Comment by KirkHadley** [comment]
Just wanted to throw in that I'm seeing a similar error, but only when wandb has been initialized in a jupyter notebook. I'm also running wandb self hosted, on a docker container.  Also, for me this is very much an intermittent error- appears to primarily happen in jupyter notebooks that have been running for a number of days, and, specifically, ones that have been idle a day or two. 

Restarting the notebook appears to consistently fix the issue, but I'd really rather not have to blow up a notebook session whenever this randomly happens. Any suggestions?

**Comment by vanpelt** [comment]
Good to know, it seems like the long running process is causing the our backend process to get killed likely due to memory constraints.  We're working on a new release next week that should be much more robust to situations like this.
