### ISSUE TITLE
OSError Too many open files: /tmp/tmphv67gzd0wandb-media

### ISSUE THREAD

**Issue by sarmientoj24** [wandb/wandb#2825]
I have been using yolov5's wandb and it is giving me this error

```
File "/opt/conda/lib/python3.8/shutil.py", line 712, in rmtree
OSError: [Errno 24] Too many open files: '/tmp/tmphv67gzd0wandb-media'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/weakref.py", line 642, in _exitfunc
  File "/opt/conda/lib/python3.8/weakref.py", line 566, in __call__
  File "/opt/conda/lib/python3.8/tempfile.py", line 817, in _cleanup
  File "/opt/conda/lib/python3.8/tempfile.py", line 813, in _rmtree
  File "/opt/conda/lib/python3.8/shutil.py", line 714, in rmtree
  File "/opt/conda/lib/python3.8/shutil.py", line 712, in rmtree
OSError: [Errno 24] Too many open files: '/tmp/tmphv67gzd0wandb-media'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/weakref.py", line 642, in _exitfunc
  File "/opt/conda/lib/python3.8/weakref.py", line 566, in __call__
  File "/opt/conda/lib/python3.8/tempfile.py", line 817, in _cleanup
  File "/opt/conda/lib/python3.8/tempfile.py", line 813, in _rmtree
  File "/opt/conda/lib/python3.8/shutil.py", line 714, in rmtree
  File "/opt/conda/lib/python3.8/shutil.py", line 712, in rmtree
OSError: [Errno 24] Too many open files: '/tmp/tmphv67gzd0wandb-media'

```

when doing Genetic Algorithm for hyperparameter evolution. Any idea on why wandb is doing this?

**Comment by maxzw** [comment]
> I got `OSError Too many open files` too. I run wandb in `optuna` subprocess.
> 
> ```python
> def optuna_objective(trial):
>     wandb.init()
>     ...
>     ...
>     wandb.finish()
>     return loss
> ```
> 
> Error Traceback
> 
> ```
> Traceback (most recent call last):
>   File "/anaconda3/envs/tf2.6/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 870, in init
>   File "/anaconda3/envs/tf2.6/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 600, in init
>   File "/anaconda3/envs/tf2.6/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1738, in _on_start
>   File "/anaconda3/envs/tf2.6/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1707, in _console_start
> OSError: [Errno 24] Too many open files: '/workspace/wandb/offline-run-20211026_081159-2i9isn2w/files/output.log'
> ```
> 
> Enviroment
> 
> ```
> macOS Catalina 10.15.7
> Python 3.8.12
> wandb 0.12.5
> ```
> 
> I fixed the problem temporarily set `ulimit -n 2048` every time before python run.

I have the same problem at this moment. I'm running hpo on a SLURM cluster and do not have permission to change these mentioned values. Are there any other options to resolving this issue?

**Comment by MBakirWB** [comment]
@maxzw, thank-you for writing in. This bug is still being addressed. We will update the community here once a fix has been implemented.
Regards

**Comment by AIchberger** [comment]
Any updates on this?

**Comment by da2r-20** [comment]
Any updates?
We are also experiencing it

**Comment by AIchberger** [comment]
So, actually my problem was related to multiprocessing, which could be fixed by setting ```ulimit -n unlimited``` (or any high number) together with
```
torch.multiprocessing.set_sharing_strategy('file_system')
torch.multiprocessing.set_start_method('spawn')
```

**Comment by LucHayward** [comment]
Just to confirm I am still seeing this error, it seems to be related to starting too many jobs (my HPC uses slurm) too rapidly in succession and is generally avoided by allowing some time (say 60s) between jobs.

**Comment by kptkin** [comment]
Hopefully fixed with PR #4617 if it still an issue feel free to re-open.

**Comment by guyfreund** [comment]
experiencing the same - it causes wandb to stop synching my run logs to the app
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/53565845/232227246-edf5c5a5-d63a-49a3-be14-e5bad147dc38.png">

**Comment by abhinav-kashyap-asus** [comment]
I am still epxeriencing this :( This has to be open again

**Comment by kptkin** [comment]
@guyfreund Based on the traceback it looks like an issue that stems from artifacts. Few requests to help us solve this. 
- Could you provide the debug logs (you can find these logs in your run directory under run)? 
- If possible a repro script or explanation about your execution
- Are you using the latest version and did upgrading helped your issue?

@abhinav-kashyap-asus same request regarding additional information to help us debug this issue.

One of my colleague will ticket this issue and tag the relevant engineer.

**Comment by jxmorris12** [comment]
Happened to me too. Killed a long-running training run, huge inconvenience

**Comment by jxmorris12** [comment]
@jonasjuerss This workaround worked for me (so far):
```
import resource
resource.setrlimit(
    resource.RLIMIT_CORE, (resource.RLIM_INFINITY, resource.RLIM_INFINITY)
)
```

**Comment by jonasjuerss** [comment]
@jxmorris12 Unfortunately, that didn't help. Thanks anyway for posting, maybe it works for others.

**Comment by abhinav-kashyap-asus** [comment]
I solved it by not logging the a artefacts. 
This is sad. There should be some way to do this more efficiently. 
I wasted a lot of time where my runs were crashing or the logging entirely stops.

**Comment by Jiuzhouh** [comment]
> I solved it by not logging the a artefacts.
> This is sad. There should be some way to do this more efficiently.
> I wasted a lot of time where my runs were crashing or the logging entirely stops.

How to disable logging the artefacts?

**Comment by mukobi** [comment]
> > I solved it by not logging the a artefacts.
> > This is sad. There should be some way to do this more efficiently.
> > I wasted a lot of time where my runs were crashing or the logging entirely stops.
> 
> How to disable logging the artefacts?

In your code, do not log artifacts if you are (e.g. don't do `wandb.log({... wandb.Table(...)})` or other things that create artifacts.

I hope some wandb people are looking at this. This seems pretty bad and renders wandb quite unusable for researchers using shared compute clusters who need to log many artifacts (especially for NLP or CV).

**Comment by MBakirWB** [comment]
@mukobi , @Jiuzhouh, @jxmorris12, @abhinav-kashyap-asus. Thank you for the continue follow up on this and our apologies that it got buried. We are going to revisit the issue but would appreciate your assistance in understanding the issue and reproducing it. Could you provide the following, either leave here in a comment or email your responses to mohammad.bakir@wandb.com

1. For the run(s) that crash, the complete stacktrace, `debug.log` and `debug-internal.log` files located in the working directory of your projects under  `wandb/<run-folder>/<logs>`
2. A brief description of your experiment setup (single/multiprocessing, Multi-node, use of wandb integrations, ect..)? , the type of environment you are running in, size of artifacts and number of files logged, and wandb version.
3. Code example for a reproduction.

**Comment by shawnlewis** [comment]
We'll get this fixed. If anyone has a script to reproduce that would help.

**Comment by iwishiwasaneagle** [comment]
I had this issue during a sweep. My hacky fix is to restart the sweep agent after every run, and bump `ulimit -n 4096` from 1024. Hopefully, this will work... this is a super annoying bug.

**Comment by mukobi** [comment]
@MBakirWB @shawnlewis Here's some simple code to repro this, run `ulimit -n 64` before to artificially set the file limit low for testing, though I expect this to also happen with 1024 or even 4096 (from experience).

```python
"""Reproduce https://github.com/wandb/wandb/issues/2825"""

import os
import wandb

# Limit the file limit to 64 with ulimit -n 64
os.system("ulimit -n 64")

wandb.init()

for i in range(1000):
    # Log a very simple artifact at each iteration
    data = f"Step {i}"
    wandb.log({"my_table": wandb.Table(columns=["text"], data=[[data]])})
    print(f'Logged "{data}"')
```

Around step 186 do I start to get the `Too many open files:` error, then in the early 200s I start to see weirder tracebacks and errors.

<img width="1667" alt="Screenshot 2023-06-29 175855" src="https://github.com/wandb/wandb/assets/20391679/b745da23-ea03-4e95-8967-4a4bbe593cf2">

Reproed on Ubuntu via Windows Subsystem for Linux with the following `uname -a` (though first encountered on a Linux SLURM cluster for my university).
> Linux DESKTOP-7VO7NFL 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ahalev** [comment]
Also having this issue; following.

**Comment by UmaisZahid** [comment]
I have also hit this issue - lost 12 long-running experiments, brutal!

**Comment by MaxWolf-01** [comment]
I'm also encountering this issue while using wandb.Table to log text predictions. We've already attempted various workarounds to log data less frequently, but the issue remains a massive annoyance for NLP tasks. Due to this bug, our models have crashed multiple times, many hours into training.

I don't know if logging the table only at the end of a long run would fix the issue. However, we can't always guarantee that we'll reach the end of the loop. And with StreamTables (a core feature one would assume) waitig to be implemented over the past years we need to resort to all sorts of ugly workarounds. See: https://github.com/wandb/wandb/issues/2981#issuecomment-1686868189

One workaround we tried (but failed) was just adding the data to the wandb Table and logging a copy of the accumulated table less frequently.

**Comment by mcao516** [comment]
Still experiencing this issue. Following.

**Comment by wrmthorne** [comment]
Also experiencing this issue. The code I have been using is an adaptation of the [PPO multi-adapter from TRL](https://github.com/huggingface/trl/blob/main/examples/scripts/ppo_multi_adapter.py) with logging frequency of every step. Each step sends a table with the query, response and reward. After just under 1000 steps, I saw this error and nothing more was reported. My training still ran to completion and the model checkpoints were saved but I have no data on loss, rewards, etc.

**Comment by spfrommer** [comment]
Also experiencing this issue when logging many tables.

**Comment by mtrazzi** [comment]
this keeps happening to me when running normal training runs on a fork of llama-recipes that uses wandb

**Comment by Kaiyotech** [comment]
This still exists. Somehow. After 2 years.

**Comment by Reza-esfandiarpoor** [comment]
Also facing the same issue!

**Comment by eminb61** [comment]
I still have the same problem

**Comment by eminb61** [comment]
The problem still exists

**Comment by kptkin** [comment]
Hi all, we released a new version of the SDK 0.16.3, that hopefully should mitigate this problem from some of you. [release notes](https://github.com/wandb/wandb/releases/tag/v0.16.3) (PR #6891). We are slowly working a full solution, but hopefully it is a step in the right direction.  Please give it a try and let us know if it helped.

**Comment by pvtien96** [comment]
In my case, this error happens while using the sweeping function. I notice that it usually stops around the 24th sweep in a grid search.
```bash
  File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/git/cmd.py", line 1315, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/git/cmd.py", line 985, in execute
    proc = Popen(
  File "/home/van-tien.pham/anaconda3/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/van-tien.pham/anaconda3/lib/python3.9/subprocess.py", line 1720, in _execute_child
    errpipe_read, errpipe_write = os.pipe()
OSError: [Errno 24] Too many open files
wandb: ERROR Abnormal program exit
Run 2pz72mmg errored: Exception('problem')
wandb: ERROR Run 2pz72mmg errored: Exception('problem')
wandb: Sweep Agent: Waiting for job.
^Cwandb: Ctrl + C detected. Stopping sweep.
```

**Comment by kptkin** [comment]
@pvtien96 do you think you will be able to provide a small repro example? to help us further debug this?

**Comment by anmolmann** [comment]
Hi all, we released a new version of the SDK 0.18.3 with a new backend, which hopefully should mitigate this problem for you. Please give it a try and let us know if it helped. If not, could you please share a small repro - maybe a code snippet, etc. which can help us investigate this issue further?

**Comment by MaxWolf-01** [comment]
The issue still persists 0.18.5

**Comment by zeyuanyin** [comment]
The issue is still there in 0.19.5
