### ISSUE TITLE
[CLI] Wandb sync after running sweeps offline

### ISSUE THREAD

**Issue by DavidSlayback** [wandb/wandb#3002]
**Description**
I've generated runs for a number of agents on a SLURM compute cluster. Using bash, I split these runs among multiple (8) processes that each call wandb sync for that set of runs (since single-threaded wandb sync is too slow). Seemingly at random, these sync scripts will fail

**Wandb features**
wandb sync

**How to reproduce**
1. I have a set of offline run directories generated by a "find" command (attached as "sync.txt")
2. I submit the outer sync script below
```
function divide_by_ceil() {
  divide=$1
  shift
  by=$1
  shift

  echo "($divide + $by - 1) / $by" | bc
}

sync_file="sync.txt"
if [ ! -f "$sync_file" ]; then
  find wandb/ -maxdepth 1 -name 'offline-run-*' > $sync_file # Save direct descendant directories
fi
num_runs=$(wc -l < $sync_file)  # Count number of runs total
num_jobs=8  # Count number of sbatch calls we want
n=$(divide_by_ceil $num_runs $num_jobs)
xargs -s 1000000 -a $sync_file -n $n sbatch --job-name wandb-sync baisero_wandb_sync.sbatch

exit 0
```
and
```
#!/bin/bash

#SBATCH --output sync_wandb.out
#SBATCH --partition short
#SBATCH --time 24:00:00

logfile=$(mktemp wandb_sync.XXX.log)
wandb sync "$@" &> $logfile

exit 0
```
3. Each job at some point runs into an error. An example is below
```
Syncing: https://wandb.ai/davidslayback/cleanoc_12072021/runs/7bgyex5i ...done.
Syncing: https://wandb.ai/davidslayback/cleanoc_12072021/runs/ecrjl74k ...done.
Syncing: https://wandb.ai/davidslayback/cleanoc_12072021/runs/hjnclieh ...done.
Syncing: https://wandb.ai/davidslayback/cleanoc_12072021/runs/hi2qvfeg ...done.
Syncing: https://wandb.ai/davidslayback/cleanoc_12072021/runs/s0bmvetv ...wandb: ERROR Error while calling W&B API: item already claimed or not eligible to be claimed (<Response [409]>)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/slayback.d/.conda/envs/py39/lib/python3.9/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/home/slayback.d/.conda/envs/py39/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 1318, in upsert_run
    response = self.gql(mutation, variable_values=variable_values, **kwargs)
  File "/home/slayback.d/.conda/envs/py39/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/slayback.d/.conda/envs/py39/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 147, in execute
    six.reraise(*sys.exc_info())
  File "/home/slayback.d/.conda/envs/py39/lib/python3.9/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/slayback.d/.conda/envs/py39/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 141, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/slayback.d/.conda/envs/py39/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/slayback.d/.conda/envs/py39/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/slayback.d/.conda/envs/py39/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/home/slayback.d/.conda/envs/py39/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/slayback.d/.conda/envs/py39/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/slayback.d/.conda/envs/py39/lib/python3.9/site-packages/wandb/sync/sync.py", line 267, in run
    sm.send(pb)
  File "/home/slayback.d/.conda/envs/py39/lib/python3.9/site-packages/wandb/sdk/internal/sender.py", line 236, in send
    send_handler(record)
  File "/home/slayback.d/.conda/envs/py39/lib/python3.9/site-packages/wandb/sdk/internal/sender.py", line 687, in send_run
    self._init_run(run, config_value_dict)
  File "/home/slayback.d/.conda/envs/py39/lib/python3.9/site-packages/wandb/sdk/internal/sender.py", line 711, in _init_run
    server_run, inserted = self._api.upsert_run(
  File "/home/slayback.d/.conda/envs/py39/lib/python3.9/site-packages/wandb/apis/normalize.py", line 26, in wrapper
    raise CommError(err.response, err)
wandb.errors.CommError: <Response [409]>
done.
```

**Environment**
- OS: Ubuntu 18.04
- Environment: Slurm Anaconda module
- Python 3.9, latest wandb version

[sync text file](https://gist.github.com/DavidSlayback/dc4e3b1c1ed182e5fd7eda0e9b8a04ad)

**Comment by DavidSlayback** [comment]
Looking further into the issue, it looks like my runs aren't being assigned unique ids by the sweep? I have 95000+ runs but only ~5000 unique ids

**Comment by aidanjdonohue** [comment]
Hi @DavidSlayback, this is not really safe use of `wandb sync`. He have an internal ticket for multithreading the syncing of multiple runs but it looks like you are getting rate limited.

**Comment by Cyberpuncrush** [comment]
> Looking further into the issue, it looks like my runs aren't being assigned unique ids by the sweep? I have 95000+ runs but only ~5000 unique ids

Same issue here, it looks in wandb offline mode, sweep agent will never end even run through all htper-parameter combos, have your problem solved yet?

**Comment by tokaka22** [comment]
> 
Same issue...maybe caused by early-stopping?

**Comment by tokaka22** [comment]
> Same issue here, it looks in wandb offline mode, sweep agent will never end even run through all hyper-parameter combos, have your problem solved yet?

Same issue...maybe caused by early-stopping?

**Comment by realCrush** [comment]
> > Same issue here, it looks in wandb offline mode, sweep agent will never end even run through all hyper-parameter combos, have your problem solved yet?
> 
> Has the problem been solved? @realCrush

I found that wandb sweep is hosted in wandb.ai cloud, and if you create agent locally to grad params from sweep, agents might have strange behaviors, so a possible solution is to set sweep locally, which means you must host whole wandb in your server/local machine.
