### ISSUE TITLE
[CLI]: Sweep is saying that values are filled with "None" yet values are printed out in the stack trace corresponding to values given in Sweep

### ISSUE THREAD

**Issue by P-Sood** [wandb/wandb#3612]
### Describe the bug

```yaml
program: text_nn.py
command:
  - ${env}
  - python3
  - ${program}
  - "--dataset"
  - "/home/prsood/projects/def-whkchun/prsood/multi-modal-emotion/data/emotion_pd"
  - "--model"
  - "LSTM"
  - "--T_max"
  - 5

method: bayes

metric:
  goal: minimize
  name: train/train_loss
parameters:
  epoch: 
    values: [3 , 5 , 7]
  learning_rate:
    distribution: uniform
    min: 0.001
    max: 0.1
  batch_size:
    values: [4 , 16 , 64]
  weight_decay:
    values: [0.000001 , 0.0000001, 0.0000001]  
  seed:
    values: [32, 64, 96]
  patience:
    values: [10]
  clip:
    values: [1]
  #T_max:
  #  values: [5,10]
  output_dim:
    values: [7]
  hidden_layers:
    values: [300]


```

```python 

def arg_parse(description):
    """
    description : str , is the name you want to give to the parser usually the model_modality used
    """
   # pdb.set_trace()
    parser = ArgumentParser(description= f" Run experiments on {description} ")

    # parser.add_argument("--")
    parser.add_argument("--learning_rate" , "-lr" , help="Set the learning rate" , type=float)
    parser.add_argument("--epoch"  , "-e", help="Set the number of epochs" , type = int)
    parser.add_argument("--batch_size", "-b", help="Set the batch_size" , type=int)
    parser.add_argument("--weight_decay", "-w", help="Set the weight_decay", type=float)
    parser.add_argument("--clip", "-c", help="Set the gradient clip", type=float)
    parser.add_argument("--patience", "-p", help="Set the patience", type=float)
    parser.add_argument("--T_max", "-t", help="Set the gradient T_max", type=int)

    # Set the seed
    parser.add_argument("--seed", "-s", help="Set the random seed", type=int)

    # These are values in the yaml that we set
    parser.add_argument("--dataset"  , "-d", help="The dataset we are using currently")
    parser.add_argument("--model"  , "-m", help="The model we are using currently")

    # These are args that we use as input to the model
    parser.add_argument("--input_dim", "-id", help="Set the input dimension", default=2 ,type=int)
    parser.add_argument("--output_dim", "-od", help="Set the output dimension", type=int)
    parser.add_argument("--lstm_layers"  , "-ll", help="set number of LSTM layers" , default=1 , type=int)
    parser.add_argument("--hidden_layers"  , "-hl", help="comma seperated values in order of hidden dimensions" , default="32,64" , type=hidden_layer_count)




    args = parser.parse_args()

    # wandb.init(project="Emotion_" + args.dataset + "_" + args.model, entity="ddi" , config = args)
    wandb.init(project="LSTM_text", entity="ddi" , config = args)
    config = wandb.config
    print(config)
    # Set random seeds
    np.random.seed(config.seed)
    torch.random.manual_seed(config.seed)


    param_dict = {
        'epoch':config.epoch ,
        'patience':config.patience ,
        'lr': config.learning_rate ,
        'clip': config.clip ,
        'batch_size':config.batch_size ,
        'weight_decay':config.weight_decay ,
        'model': config.model,
        'T_max':config.T_max ,
    }

    model_param = {
        'input_dim':config.input_dim ,
        'output_dim':config.output_dim ,
        'lstm_layers':config.lstm_layers ,
        'hidden_layers':config.hidden_layers ,
    }


    df = pd.read_pickle(f"{args.dataset}.pkl")
    print(f"model param = {model_param} \n param_dict = {param_dict}")

    return df , param_dict , model_param


```

```shell

2022-05-03 14:35:21,087 - wandb.wandb_agent - INFO - Running runs: []
2022-05-03 14:35:21,497 - wandb.wandb_agent - INFO - Agent received command: run
2022-05-03 14:35:21,497 - wandb.wandb_agent - INFO - Agent starting run with config:
	batch_size: 4
	clip: 1
	epoch: 5
	hidden_layers: 300
	learning_rate: 0.09535137259022426
	output_dim: 7
	patience: 10
	seed: 96
	weight_decay: 1e-06
2022-05-03 14:35:21,512 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env python3 text_nn.py --dataset /home/prsood/projects/def-whkchun/prsood/multi-modal-emotion/data/emotion_pd --model LSTM --T_max 5
2022-05-03 14:35:26,530 - wandb.wandb_agent - INFO - Running runs: ['pcn72t01']
Exception ignored in: <_io.FileIO name='/project/6051551/prsood/multi-modal-emotion/src/wandb/sweep-czj8ofdk/config-pcn72t01.yaml' mode='rb' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/project/6051551/prsood/multi-modal-emotion/src/wandb/sweep-czj8ofdk/config-pcn72t01.yaml' mode='r' encoding='UTF-8'>
wandb: Currently logged in as: prsood (ddi). Use `wandb login --relogin` to force relogin
wandb: WARNING Ignored wandb.init() arg project when running a sweep.
wandb: WARNING Ignored wandb.init() arg entity when running a sweep.
wandb: Tracking run with wandb version 0.12.16
wandb: Run data is saved locally in /project/6051551/prsood/multi-modal-emotion/src/wandb/run-20220503_143527-pcn72t01
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run twilight-sweep-8
wandb: ⭐️ View project at https://wandb.ai/ddi/LSTM_text
wandb: 🧹 View sweep at https://wandb.ai/ddi/LSTM_text/sweeps/czj8ofdk
wandb: 🚀 View run at https://wandb.ai/ddi/LSTM_text/runs/pcn72t01
{'learning_rate': 0.09535137259022426, 'epoch': 5, 'batch_size': 4, 'weight_decay': 1e-06, 'clip': 1, 'patience': 10, 'T_max': 5, 'seed': 96, 'dataset': '/home/prsood/projects/def-whkchun/prsood/multi-modal-emotion/data/emotion_pd', 'model': 'LSTM', 'input_dim': 2, 'output_dim': 7, 'lstm_layers': 1, 'hidden_layers': 300}
model param = {'input_dim': 2, 'output_dim': 7, 'lstm_layers': 1, 'hidden_layers': 300} 
 param_dict = {'epoch': 5, 'patience': 10, 'lr': 0.09535137259022426, 'clip': 1, 'batch_size': 4, 'weight_decay': 1e-06, 'model': 'LSTM', 'T_max': 5}
2022-05-03 14:35:57,190 - wandb.wandb_agent - INFO - Cleaning up finished run: pcn72t01
wandb: ERROR Error while calling W&B API: None is not a permitted value of the categorical hyperparameter batch_size in the current sweep. (<Response [400]>)
wandb: Terminating and syncing runs. Press ctrl-c to kill.
Traceback (most recent call last):
  File "/project/6051551/prsood/sarcasm_venv/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 1761, in agent_heartbeat
    timeout=60,
  File "/project/6051551/prsood/sarcasm_venv/lib/python3.7/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/project/6051551/prsood/sarcasm_venv/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 140, in execute
    return self.client.execute(*args, **kwargs)
  File "/project/6051551/prsood/sarcasm_venv/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/project/6051551/prsood/sarcasm_venv/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/project/6051551/prsood/sarcasm_venv/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/project/6051551/prsood/sarcasm_venv/lib/python3.7/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/6051551/prsood/sarcasm_venv/bin/wandb", line 8, in <module>
    sys.exit(cli())
  File "/project/6051551/prsood/sarcasm_venv/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/project/6051551/prsood/sarcasm_venv/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/project/6051551/prsood/sarcasm_venv/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/project/6051551/prsood/sarcasm_venv/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/project/6051551/prsood/sarcasm_venv/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/project/6051551/prsood/sarcasm_venv/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/project/6051551/prsood/sarcasm_venv/lib/python3.7/site-packages/wandb/cli/cli.py", line 95, in wrapper
    return func(*args, **kwargs)
  File "/project/6051551/prsood/sarcasm_venv/lib/python3.7/site-packages/wandb/cli/cli.py", line 1205, in agent
    wandb_agent.agent(sweep_id, entity=entity, project=project, count=count)
  File "/project/6051551/prsood/sarcasm_venv/lib/python3.7/site-packages/wandb/wandb_agent.py", line 612, in agent
    count=count,
  File "/project/6051551/prsood/sarcasm_venv/lib/python3.7/site-packages/wandb/wandb_agent.py", line 548, in run_agent
    agent.run()
  File "/project/6051551/prsood/sarcasm_venv/lib/python3.7/site-packages/wandb/wandb_agent.py", line 252, in run
    commands = self._api.agent_heartbeat(agent_id, {}, run_status)
  File "/project/6051551/prsood/sarcasm_venv/lib/python3.7/site-packages/wandb/apis/internal.py", line 126, in agent_heartbeat
    return self.api.agent_heartbeat(*args, **kwargs)
  File "/project/6051551/prsood/sarcasm_venv/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 1765, in agent_heartbeat
    message = ast.literal_eval(e.args[0])["message"]
  File "/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python3.7/ast.py", line 46, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python3.7/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    400 Client Error: Bad Request for url: https://api.wandb.ai/graphql
             ^
SyntaxError: invalid syntax


```

### Environment

WandB version: 0.12.16

OS: CentOS Linux 7

Python version: 3.7.7

Versions of relevant libraries: 

### Additional Context

As you can see in the YAML file I moved the T_max above, but that was the errored out one previously.

As well, the more times I ran the wandb agent command , the faster the above error appeared

**Comment by P-Sood** [comment]
My file structure is like 
MME
   -data
   -README.md
   -req.txt
   -run_text_only_NN.sh
   -setup.cfg
   -src
        - hyper_parameter_config
             - lstm.yaml
        - models
        - notebooks
        - run_scripts
        - text_nn.py (file that holds the main function)
        - train_model
        - utils
             - global_functions.py (python script that holds the arg parse and wandb config)
        - wandb
   -wandb


Now i run the commands inside **src** directory
wandb sweep --project LSTM_text -e ddi --name hyper_param_tuning_lstm hyper_parameter_config/lstm.yaml

Get the sweep ID and then run
 wandb agent ddi/LSTM_text/{sweep_id}

I mention all of this because I don't know if there is a pathing issue somewhere that is interfering with things

**Comment by ramit-wandb** [comment]
Hi @P-Sood,

Looking at your code, one likely possibility why this is occurring is that you are calling `wandb.init` inside a function and trying to use the generated object outside that context. My reasoning here is that the `wandb.run` object is getting destroyed at the function exit to `arg_parse`. Could you try calling `wandb.init` outside `arg_parse`?

I see that `wandb.config` behaves as expected inside `arg_parse`, but not outside `arg_parse`, leading to this. Please let me know if this does not work for you and we will work on this together to get your code working for you.

Thanks!
Ramit

**Comment by P-Sood** [comment]
> Hi @P-Sood,
> 
> Looking at your code, one likely possibility why this is occurring is that you are calling `wandb.init` inside a function and trying to use the generated object outside that context. My reasoning here is that the `wandb.run` object is getting destroyed at the function exit to `arg_parse`. Could you try calling `wandb.init` outside `arg_parse`?
> 
> I see that `wandb.config` behaves as expected inside `arg_parse`, but not outside `arg_parse`, leading to this. Please let me know if this does not work for you and we will work on this together to get your code working for you.
> 
> Thanks! Ramit

Hi @ramit-wandb, thank you for your reply. I have moved wandb.init inside of the main function. However the same error appears.

*new  main() function in text_nn.py *

```python
def main():
    project_name = "LSTM_text"
    args =  arg_parse(project_name)
    # wandb.init(project="Emotion_" + args.dataset + "_" + args.model, entity="ddi" , config = args)
    wandb.init(project=project_name, entity="ddi" , config = args)
    config = wandb.config
    # print(config)
    # Set random seeds
    np.random.seed(config.seed)
    torch.random.manual_seed(config.seed)

    
    param_dict = {
        'epoch':config.epoch ,
        'patience':config.patience ,
        'lr': config.learning_rate ,
        'clip': config.clip ,
        'batch_size':config.batch_size ,
        'weight_decay':config.weight_decay ,
        'model': config.model,
        'T_max':config.T_max ,
    }

    model_param = {
        'input_dim':config.input_dim ,
        'output_dim':config.output_dim ,
        'lstm_layers':config.lstm_layers ,
        'hidden_layers':config.hidden_layers ,
    }

    
    df = pd.read_pickle(f"{args.dataset}.pkl")
    
    print(param_dict , '\n' , model_param)
    runModel(df, param_dict , model_param)
```

*new  arg_parse() in global_function.py *

```python
def arg_parse(description):
    """
    description : str , is the name you want to give to the parser usually the model_modality used
    """
   # pdb.set_trace()
    parser = ArgumentParser(description= f" Run experiments on {description} ")

    # parser.add_argument("--")
    parser.add_argument("--learning_rate" , "-lr" , help="Set the learning rate" , type=float)
    parser.add_argument("--epoch"  , "-e", help="Set the number of epochs" , type = int)
    parser.add_argument("--batch_size", "-b", help="Set the batch_size" , type=int)
    parser.add_argument("--weight_decay", "-w", help="Set the weight_decay", type=float)
    parser.add_argument("--clip", "-c", help="Set the gradient clip", type=float)
    parser.add_argument("--patience", "-p", help="Set the patience", type=float)
    parser.add_argument("--T_max", "-t", help="Set the gradient T_max", type=int)

    # Set the seed
    parser.add_argument("--seed", "-s", help="Set the random seed", type=int)
    
    # These are values in the yaml that we set
    parser.add_argument("--dataset"  , "-d", help="The dataset we are using currently") 
    parser.add_argument("--model"  , "-m", help="The model we are using currently") 

    # These are args that we use as input to the model
    parser.add_argument("--input_dim", "-id", help="Set the input dimension", default=2 ,type=int)
    parser.add_argument("--output_dim", "-od", help="Set the output dimension", type=int)
    parser.add_argument("--lstm_layers"  , "-ll", help="set number of LSTM layers" , default=1 , type=int) 
    parser.add_argument("--hidden_layers"  , "-hl", help="comma seperated values in order of hidden dimensions" , default="32,64" , type=hidden_layer_count) 




    return parser.parse_args()
```

```stack
Exception ignored in: <_io.FileIO name='/project/6051551/prsood/multi-modal-emotion/src/wandb/sweep-xhqfjm32/config-ouovic2m.yaml' mode='rb' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/project/6051551/prsood/multi-modal-emotion/src/wandb/sweep-xhqfjm32/config-ouovic2m.yaml' mode='r' encoding='UTF-8'>
wandb: Currently logged in as: prsood (ddi). Use `wandb login --relogin` to force relogin
wandb: WARNING Ignored wandb.init() arg project when running a sweep.
wandb: WARNING Ignored wandb.init() arg entity when running a sweep.
wandb: Tracking run with wandb version 0.12.16
wandb: Run data is saved locally in /project/6051551/prsood/multi-modal-emotion/src/wandb/run-20220504_184945-ouovic2m
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run twilight-sweep-1
wandb: ⭐️ View project at https://wandb.ai/ddi/LSTM_text
wandb: 🧹 View sweep at https://wandb.ai/ddi/LSTM_text/sweeps/xhqfjm32
wandb: 🚀 View run at https://wandb.ai/ddi/LSTM_text/runs/ouovic2m
2022-05-04 18:50:22,877 - wandb.wandb_agent - INFO - Cleaning up finished run: ouovic2m
wandb: ERROR Error while calling W&B API: None is not a permitted value of the categorical hyperparameter T_max in the current sweep. (<Response [400]>)
wandb: Terminating and syncing runs. Press ctrl-c to kill.
Traceback (most recent call last):
  File "/project/6051551/prsood/sarcasm_venv/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 1761, in agent_heartbeat
    timeout=60,
  File "/project/6051551/prsood/sarcasm_venv/lib/python3.7/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/project/6051551/prsood/sarcasm_venv/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 140, in execute
    return self.client.execute(*args, **kwargs)
  File "/project/6051551/prsood/sarcasm_venv/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/project/6051551/prsood/sarcasm_venv/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/project/6051551/prsood/sarcasm_venv/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/project/6051551/prsood/sarcasm_venv/lib/python3.7/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/6051551/prsood/sarcasm_venv/bin/wandb", line 8, in <module>
    sys.exit(cli())
  File "/project/6051551/prsood/sarcasm_venv/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/project/6051551/prsood/sarcasm_venv/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/project/6051551/prsood/sarcasm_venv/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/project/6051551/prsood/sarcasm_venv/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/project/6051551/prsood/sarcasm_venv/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/project/6051551/prsood/sarcasm_venv/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/project/6051551/prsood/sarcasm_venv/lib/python3.7/site-packages/wandb/cli/cli.py", line 95, in wrapper
    return func(*args, **kwargs)
  File "/project/6051551/prsood/sarcasm_venv/lib/python3.7/site-packages/wandb/cli/cli.py", line 1205, in agent
    wandb_agent.agent(sweep_id, entity=entity, project=project, count=count)
  File "/project/6051551/prsood/sarcasm_venv/lib/python3.7/site-packages/wandb/wandb_agent.py", line 612, in agent
    count=count,
  File "/project/6051551/prsood/sarcasm_venv/lib/python3.7/site-packages/wandb/wandb_agent.py", line 548, in run_agent
    agent.run()
  File "/project/6051551/prsood/sarcasm_venv/lib/python3.7/site-packages/wandb/wandb_agent.py", line 252, in run
    commands = self._api.agent_heartbeat(agent_id, {}, run_status)
  File "/project/6051551/prsood/sarcasm_venv/lib/python3.7/site-packages/wandb/apis/internal.py", line 126, in agent_heartbeat
    return self.api.agent_heartbeat(*args, **kwargs)
  File "/project/6051551/prsood/sarcasm_venv/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 1765, in agent_heartbeat
    message = ast.literal_eval(e.args[0])["message"]
  File "/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python3.7/ast.py", line 46, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python3.7/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    400 Client Error: Bad Request for url: https://api.wandb.ai/graphql
             ^
SyntaxError: invalid syntax
(sarcasm_venv) [prsood@cedar1 src]$ /cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 6 leaked semaphores to clean up at shutdown
  len(cache))

```


*old main() function in text_nn.py corresponding to arg_parse in original comment *

```python
def main():
    df , param_dict , model_param = arg_parse("LSTM_text")
    runModel(df, param_dict , model_param)
    print(param_dict , '\n' , model_param)
```

I have changed nothing else.

**Comment by P-Sood** [comment]
[ramit-wandb](https://github.com/ramit-wandb)
@ramit-wandb 
Was wondering if you were still able to help me on this. As it's a more time-sensitive issue for me, any reply would be helpful.

**Comment by ramit-wandb** [comment]
Hey @P-Sood,

Apologies for the delay here. I looked through the error messages and noticed the following line:

```
wandb: ERROR Error while calling W&B API: None is not a permitted value of the categorical hyperparameter T_max in the current sweep. (<Response [400]>)
```

Could you share your sweep config YAML file so that I can investigate this further?

Thanks,
Ramit

**Comment by P-Sood** [comment]
Hi @ramit-wandb 
the YAML file is at the top. It is the first file in the original post.

Hope that helps!

**Comment by ramit-wandb** [comment]
Ah, thanks. It seems like you have 2 ways to pass in arguments : `parser.add_argument` or the `wandb.config` and they seem to be conflicting with one another. I would recommend ensuring that your parameters have only one point of entry for your parameters.

I would also suggest adding default values to the `parser.add_argument` parameters to ensure no `None` values get passed into the program.

Thanks,
Ramit
