### ISSUE TITLE
[CLI]: HTTPError: 409 Client Error

### ISSUE THREAD

**Issue by ManiadisG** [wandb/wandb#3638]
### Describe the bug

Occasionally, when I initiate a run, I get the following error:

```
Thread SenderThread:
Traceback (most recent call last):
  File "/anaconda3/envs/env/lib/python3.8/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/anaconda3/envs/env/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1298, in upsert_run
    response = self.gql(mutation, variable_values=variable_values, **kwargs)
  File "/anaconda3/envs/env/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/anaconda3/envs/env/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 147, in execute
    six.reraise(*sys.exc_info())
  File "/anaconda3/envs/env/lib/python3.8/site-packages/six.py", line 719, in reraise
    raise value
  File "/anaconda3/envs/env/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 141, in execute
    return self.client.execute(*args, **kwargs)
  File "/anaconda3/envs/env/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/anaconda3/envs/env/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/anaconda3/envs/env/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/anaconda3/envs/env/lib/python3.8/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/envs/env/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 52, in run
    self._run()
  File "/anaconda3/envs/env/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 102, in _run
    self._process(record)
  File "/anaconda3/envs/env/lib/python3.8/site-packages/wandb/sdk/internal/internal.py", line 291, in _process
    self._sm.send(record)
  File "/anaconda3/envs/env/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 236, in send
    send_handler(record)
  File "/anaconda3/envs/env/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 687, in send_run
    self._init_run(run, config_value_dict)
  File "/anaconda3/envs/env/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 711, in _init_run
    server_run, inserted = self._api.upsert_run(
  File "/anaconda3/envs/env/lib/python3.8/site-packages/wandb/apis/normalize.py", line 26, in wrapper
    raise CommError(err.response, err)
wandb.errors.CommError: <Response [409]>
Problem at: /utils/wandb_logger.py 64 __init__
Traceback (most recent call last):
  File "/anaconda3/envs/env/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 931, in init
    run = wi.init()
  File "/anaconda3/envs/env/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 596, in init
    backend.cleanup()
  File "/anaconda3/envs/env/lib/python3.8/site-packages/wandb/sdk/backend/backend.py", line 245, in cleanup
    self.interface.join()
  File "/anaconda3/envs/env/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 458, in join
    super().join()
  File "/anaconda3/envs/env/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 599, in join
    _ = self._communicate_shutdown()
  File "/anaconda3/envs/env/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 455, in _communicate_shutdown
    _ = self._communicate(record)
  File "/anaconda3/envs/env/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/anaconda3/envs/env/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
Traceback (most recent call last):
  File "/snap/pycharm-professional/280/plugins/python/helpers/pydev/pydevd.py", line 1491, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-professional/280/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/run.py", line 38, in <module>
    main()
  File "/run.py", line 35, in main
    mp.spawn(main_worker, nprocs=len(args.gpus), args=(args,))
  File "/anaconda3/envs/env/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/anaconda3/envs/env/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/anaconda3/envs/env/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/anaconda3/envs/env/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 931, in init
    run = wi.init()
  File "/anaconda3/envs/env/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 596, in init
    backend.cleanup()
  File "/anaconda3/envs/env/lib/python3.8/site-packages/wandb/sdk/backend/backend.py", line 245, in cleanup
    self.interface.join()
  File "/anaconda3/envs/env/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 458, in join
    super().join()
  File "/anaconda3/envs/env/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 599, in join
    _ = self._communicate_shutdown()
  File "/anaconda3/envs/env/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 455, in _communicate_shutdown
    _ = self._communicate(record)
  File "/anaconda3/envs/env/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/anaconda3/envs/env/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/anaconda3/envs/env/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/run.py", line 27, in main_worker
    trainer.run_training(data_module.train_dataloader(), data_module.val_dataloader())
  File "/model.py", line 88, in run_training
    self.ProgBarAndLogger = ProgBarAndLogger(self.args.experiment_dir, self.args.project_name, self.args.run_id,
  File "/utils/wandb_logger.py", line 64, in __init__
    wandb.init(project=project_name, entity=entity, config=configs, group=group, tags=tags,
  File "/anaconda3/envs/env/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 969, in init
    six.raise_from(Exception("problem"), error_seen)
  File "<string>", line 3, in raise_from
Exception: problem
```

It appears to be happening after I have begun and stopped multiple runs in a short amount of time. Sometimes it stops after some time passes, but for one of my projects it is permanent, preventing me from adding any new runs.

What is it related to and is there a way to overcome this?

[UPDATE]: It appears to be related to the fact that I specify the run_id for each experiment. I have a numbering convention where I provide a string, existing experiments are read, and the run is automaticaly numbered. For instance, for a given string "test_string" and assuming 10 runs with the same initial "test_string" exist, the new run is assigned id "test_string_11". When I change the string the error dissapears.

### Environment

WandB version: 0.12.9

OS: Ubuntu 20.04.3 LTS

Python version: 3.8.12

Versions of relevant libraries:

**Comment by nate-wandb** [comment]
Hi @ManiadisG, is there a reason you would like to specify the `run_id` in this case? 

All `run_id`'s within a project must be unique so is there any chance that you are stepping on a previously used `run_id`?

**Comment by ManiadisG** [comment]
Thank you for your response.

I am specifying `run_id`s to make it easier to identify specific runs, both in the web API of wandb and in my local directories. I am aware this could be done by specifying the `name` argument as well, but I personaly found the former way to be cleaner.

I can confirm that the problem is not that the `run_id` has been used, I have checked for this.

If it helps, I suspect it might have something to do with initializing/stopping/deleting runs in a short amount of time, but I don't know why only a specific `run_id` keyword would be affected.

**Comment by nate-wandb** [comment]
@ManiadisG Yes, I think this is the issue. Are you deleting a run and then quickly starting a new run with a same `run_id`? When you delete a run you actually have a few days to recover the run so it still exists on our database. This would cause this error if you tried to run to the same `run_id` again. 

I understand if you have incorporated setting the `run_id` as a part of your workflow but this will be an unfortunate drawback of this approach.

**Comment by ManiadisG** [comment]
Hi @nate-wandb, thank you for checking.

No, I believe this is not the source of the problem, as it happened again this week (fortunately for our discussion) in a project that had not been active for over a month. Also, I am quite certain that I had increased the index past those of previous runs, so that exact run_id could not have been used previously.

From my experience with the issue, it looks as though the non-numerical part of the keyword was locked, regardless of the numerical indexing that followed it. Also, it looks like this is case-insensitive, as changing the capitalization did not seem to work.

**Comment by nate-wandb** [comment]
Hi @ManiadisG, could you show an example of what one of your `run_id`'s looks like so I can try to replicate the issue? 

You are saying that if a `run_id` has the same non-numerical prefix then that prefix cannot be used again? For example if you used "testrun1" then you could not use "testrun2"? 

Thank you,
Nate

**Comment by ManiadisG** [comment]
Hi @nate-wandb.

I just tested this on a project that has been inactive for about a month, with a prefix that started throwing this error around March.

The prefix of the `run_id` is _neg_cont_. The full `run_id` is then _neg_cont_XXXX_, where _XXXX_ is a number that increases with each run. I just tried _neg_cont_0125_ to _neg_cont_0130_, none of which existed previously and all threw the same error. However, even slightly changing the prefix overcomes the problem. For example, _negcont_XXXX_ works normally.

This is why I assume it is related to the prefix, though I get it sounds strage. Unfortunately I couldn't get a better idea from the error message.

**Comment by nate-wandb** [comment]
@ManiadisG, is there any chance that those `run_id`'s existed at any point in that project? I just tested both of the `run_id`'s you sent and didn't have any issue running to those id's which leads me to believe that the issue is specific to using those id's with your project. 

These `run_id`'s may persist for longer than 7 days. That was just my hypothesis based on the fact that you can recover runs for up to 7 days. I can check with our backend team to see if it's possible that these `run_id`'s still exist in the backend for longer preventing you from using them again.

**Comment by ManiadisG** [comment]
@nate-wandb I tried an arbitrarily large suffix and it worked.

In my code the XXXX suffix increases incrementaly by reading existing runs locally or in the cloud. It finds the biggest suffix XXXX and adds 1. Somehow, after each failed run, the increment also fails. So, for instance, after I try _neg_cont_0130_ and it throws an error, it primes _neg_cont_0131_ to also fail, despite 0131 never having been used. After a large XXXX worked, I tried skipping only a single number after a failed run's id (basically jumping from _neg_cont_0131_ to _neg_cont_0133_) and that also worked. I still don't quite understand why this happens though.

**Comment by vanpelt** [comment]
@ManiadisG there's nothing fancy going on in our backend that could explain this behavior.  You'll receive a 409 conflict if an id is already in our DB, or if two process simultaneously try to update the same id.  Is it possible you have multiple threads or parallel processes that are doing this increment at the same time?

**Comment by ManiadisG** [comment]
I will close this issue as I  think the cause of the problem has been found. Many thanks for your help!
