### ISSUE TITLE
[CLI]: model working only if not logging with WANDB

### ISSUE THREAD

**Issue by pilviosol** [wandb/wandb#3646]
### Describe the bug

I'm trying to log losses and images on wandb. After I upgraded the version of wandb to 0.12.16, I encounter a message that I don't see if running the exact same code without logging things in wandb

    def train(self, x_train, y_train, x_val, y_val, batch_size, num_epochs):
        callback_list.append(WandbCallback())

        def plot_and_save_while_training(epoch, logs):

            if epoch % 5 == 0:
                a = self.model.predict(x_val)

                for i in range(len(x_val[0])):
                    element = a[i]
                    element = np.squeeze(element)

                    if i % 5 == 0:
                        fig = plt.figure()
                        img = plt.imshow(element, cmap=plt.cm.viridis, origin='lower', extent=[0, 256, 0, 512],
                                         aspect='auto')
                        title = str(epoch) + '_' + str(i)
                        plt.title(title)
                        plt.colorbar()
                        plt.tight_layout()
                        plt.savefig('/nas/home/spol/Thesis/saved_model/images/' + dt_string + '/' + title)

                        plt.close()
                        wandb.log({"Validation set plots": [wandb.Image(fig, caption=title)]})

        callback_list.append(LambdaCallback(on_epoch_end=plot_and_save_while_training))
        callback_list.append(callback)
        self.model.fit(x_train,
                       y_train,
                       batch_size=batch_size,
                       epochs=num_epochs,
                       shuffle=False,
                       callbacks=callback_list,
                       validation_data=(x_val, y_val))

Traceback (most recent call last):
  File "/nas/home/spol/Thesis/CVAE_train.py", line 147, in <module>
    autoencoder = train(x_train, y_train, x_val, y_val, LEARNING_RATE, BATCH_SIZE, EPOCHS)
  File "/nas/home/spol/Thesis/CVAE_train.py", line 108, in train
    autoencoder.train(x_train, y_train, x_val, y_val, batch_size, epochs)
  File "/nas/home/spol/Thesis/VV_autoencoder.py", line 145, in train
    self.model.fit(x_train,
  File "/nas/home/spol/miniconda3/envs/keras_env/lib/python3.8/site-packages/tensorflow/python/keras/engine/training_v1.py", line 790, in fit
    return func.fit(
  File "/nas/home/spol/miniconda3/envs/keras_env/lib/python3.8/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 649, in fit
    return fit_loop(
  File "/nas/home/spol/miniconda3/envs/keras_env/lib/python3.8/site-packages/wandb/integration/keras/keras.py", line 147, in new_arrays
    return old_arrays(*args, **kwargs)
  File "/nas/home/spol/miniconda3/envs/keras_env/lib/python3.8/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 441, in model_iteration
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/nas/home/spol/miniconda3/envs/keras_env/lib/python3.8/site-packages/tensorflow/python/keras/callbacks.py", line 416, in on_epoch_end
    callback.on_epoch_end(epoch, numpy_logs)
  File "/nas/home/spol/miniconda3/envs/keras_env/lib/python3.8/site-packages/wandb/integration/keras/keras.py", line 598, in on_epoch_end
    self._save_model_as_artifact(epoch)
  File "/nas/home/spol/miniconda3/envs/keras_env/lib/python3.8/site-packages/wandb/integration/keras/keras.py", line 991, in _save_model_as_artifact
    self.model.save(self.filepath[:-3], overwrite=True, save_format="tf")
  File "/nas/home/spol/miniconda3/envs/keras_env/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1978, in save
    save.save_model(self, filepath, overwrite, include_optimizer, save_format,
  File "/nas/home/spol/miniconda3/envs/keras_env/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py", line 133, in save_model
    saved_model_save.save(model, filepath, overwrite, include_optimizer,
  File "/nas/home/spol/miniconda3/envs/keras_env/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/save.py", line 80, in save
    save_lib.save(model, filepath, signatures, options)
  File "/nas/home/spol/miniconda3/envs/keras_env/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py", line 975, in save
    _, exported_graph, object_saver, asset_info = _build_meta_graph(
  File "/nas/home/spol/miniconda3/envs/keras_env/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py", line 1064, in _build_meta_graph
    asset_info, exported_graph = _fill_meta_graph_def(meta_graph_def,
  File "/nas/home/spol/miniconda3/envs/keras_env/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py", line 653, in _fill_meta_graph_def
    signatures = _generate_signatures(signature_functions, resource_map)
  File "/nas/home/spol/miniconda3/envs/keras_env/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py", line 518, in _generate_signatures
    outputs = _call_function_with_mapped_captures(
  File "/nas/home/spol/miniconda3/envs/keras_env/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py", line 470, in _call_function_with_mapped_captures
    export_captures = _map_captures_to_created_tensors(function.graph.captures,
  File "/nas/home/spol/miniconda3/envs/keras_env/lib/python3.8/site-packages/tensorflow/python/saved_model/save.py", line 389, in _map_captures_to_created_tensors
    raise AssertionError(
AssertionError: Tried to export a function which references untracked object Tensor("mu/BiasAdd:0", shape=(None, 64), dtype=float32).TensorFlow objects (e.g. tf.Variable) captured by functions must be tracked by assigning them to an attribute of a tracked object or assigned to an attribute of the main object directly.
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: Network error (ReadTimeout), entering retry loop.

### Environment

WandB version: 0.12.16

OS: Mac Catalina 10.15.6 (19G2021)

Python version: 3.8.12

Versions of relevant libraries: Tensorflow 2.3.1, Keras 2.8.0

**Comment by ayulockin** [comment]
Hey @pilviosol we are working on this issue. I will update soon.

**Comment by nate-wandb** [comment]
Hi @pilviosol, 
We were not able to replicate the issue. Could you possibly share a complete minimal replication for the issue? Perhaps in a Colab? Also, just to clarify, you are talking about the `AssertionError` correct? Not the `wandb` error?

Thank you,
Nate

**Comment by pilviosol** [comment]
Hi,
I cannot retrive the logs and the error since the day after the error
disappeared and then I deleted the “runs” to clear space. Anyway now
everything is working fine.

Thank you, bye
Il giorno ven 27 mag 2022 alle 17:24 nate-wandb ***@***.***>
ha scritto:

**Comment by ayulockin** [comment]
Thanks for the update @pilviosol. If you find any issue please reopen this issue.
