### ISSUE TITLE
[CLI]: Launch - Missing Kubernetes Dependency

### ISSUE THREAD

**Issue by alexeyfsk** [wandb/wandb#3663]
### Describe the bug

The package is missing the Kubernetes dependency imported by `wandb/sdk/launch/builder/kaniko.py`.

Separately running `pip install kubernetes` resolves the issue.

```shell
(v) alexey@mac v % wandb launch
Traceback (most recent call last):
  File "/Users/alexey/.local/share/virtualenvs/v-w4Hf3KuV/bin/wandb", line 8, in <module>
    sys.exit(cli())
  File "/Users/alexey/.local/share/virtualenvs/v-w4Hf3KuV/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/alexey/.local/share/virtualenvs/v-w4Hf3KuV/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/alexey/.local/share/virtualenvs/v-w4Hf3KuV/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/alexey/.local/share/virtualenvs/v-w4Hf3KuV/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/alexey/.local/share/virtualenvs/v-w4Hf3KuV/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/alexey/.local/share/virtualenvs/v-w4Hf3KuV/lib/python3.10/site-packages/wandb/cli/cli.py", line 95, in wrapper
    return func(*args, **kwargs)
  File "/Users/alexey/.local/share/virtualenvs/v-w4Hf3KuV/lib/python3.10/site-packages/wandb/cli/cli.py", line 1044, in launch
    from wandb.sdk.launch import launch as wandb_launch
  File "/Users/alexey/.local/share/virtualenvs/v-w4Hf3KuV/lib/python3.10/site-packages/wandb/sdk/launch/launch.py", line 10, in <module>
    from .agent import LaunchAgent
  File "/Users/alexey/.local/share/virtualenvs/v-w4Hf3KuV/lib/python3.10/site-packages/wandb/sdk/launch/agent/__init__.py", line 1, in <module>
    from .agent import LaunchAgent
  File "//Users/alexey/.local/share/virtualenvs/v-w4Hf3KuV/lib/python3.10/site-packages/wandb/sdk/launch/agent/agent.py", line 16, in <module>
    from ..builder.loader import load_builder
  File "/Users/alexey/.local/share/virtualenvs/v-w4Hf3KuV/lib/python3.10/site-packages/wandb/sdk/launch/builder/loader.py", line 8, in <module>
    from .kaniko import KanikoBuilder
  File "/Users/alexey/.local/share/virtualenvs/v-w4Hf3KuV/lib/python3.10/site-packages/wandb/sdk/launch/builder/kaniko.py", line 10, in <module>
    import kubernetes  # type: ignore
ModuleNotFoundError: No module named 'kubernetes'
```

### Environment

WandB version: `0.12.16`

OS: `MacOS 12.3.1`

Python version: `3.10. 3`

Versions of relevant libraries: `N/A`

**Comment by ramit-wandb** [comment]
Hi @alexeyfsk,

Additional dependencies associated to launch can be installed using `pip install wandb[launch]`. We have improved the error messages associated to these, but we are not packaging all the dependencies for Launch into `wandb` if they are not required.
