### ISSUE TITLE
wandb.config is empty when I use hyperparameter sweeps[Q]

### ISSUE THREAD

**Issue by yc-cui** [wandb/wandb#3665]
I'm a beginner with wandb. It's a convenient tool and I like it. However, when I try the hyperparameter sweeps, I encouter a problem. I have no idea why the config is empty. The simple version of my code is as follows. As you can see, it's quite readable:
```
class Trainer:
    def __init__(self):
        sweep_id = wandb.sweep(sweep_config, project=PROJECT_NAME)
        wandb.init()
        wandb.agent(sweep_id, self.run, count=1)

    def run(self):
        with wandb.init():
            config = wandb.config
            opt = self.build_optim(config.optimizer, config.lr)

    def build_optim(self, optim, lr):

        optimizer = None

        if optim == "sgd":
            optimizer = nn.SGD(self.net.trainable_params(), lr)
        elif optim == "adam":
            optimizer = nn.Adam(self.net.trainable_params(), lr)
        elif optim == "adagrad":
            optimizer = nn.Adagrad(self.net.trainable_params(), lr)
        elif optim == "momentum":
            optimizer = nn.Momentum(self.net.trainable_params(), lr)

        return optimizer 

```
The sweep config is like:
```
        "sweep_config": {
            "method": "grid",
            "metric": {
                "name": "accuracy",
                "goal": "maximize"
            },
            "parameters": {
                "optimizer": {
                    "values": ["adam", "sgd", "adagrad", "momentum"]
                },
                "lr": {
                    "values": [0.01, 0.001, 0.0001]
                }
            }
        }
```
However, I got this problem:
```
wandb: Agent Starting Run: hm2y06z8 with config:
wandb: 	lr: 0.01
wandb: 	optimizer: adam
wandb: ERROR Problem finishing run
Traceback (most recent call last):
  File "/root/autodl-tmp/PycharmProjects/code/trainer.py", line 58, in run_sweep
    opt = self.build_optim(config.optimizer, config.lr)
  File "/root/autodl-tmp/miniconda3/envs/ms/lib/python3.7/site-packages/wandb/sdk/wandb_config.py", line 160, in __getattr__
    return self.__getitem__(key)
  File "/root/autodl-tmp/miniconda3/envs/ms/lib/python3.7/site-packages/wandb/sdk/wandb_config.py", line 128, in __getitem__
    return self._items[key]
KeyError: 'optimizer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/autodl-tmp/miniconda3/envs/ms/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1876, in _atexit_cleanup
    self._on_finish()
  File "/root/autodl-tmp/miniconda3/envs/ms/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1977, in _on_finish
    self._console_stop()  # TODO: there's a race here with jupyter console logging
  File "/root/autodl-tmp/miniconda3/envs/ms/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1916, in _console_stop
    self._restore()
  File "/root/autodl-tmp/miniconda3/envs/ms/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1845, in _restore
    self._err_redir.uninstall()
  File "/root/autodl-tmp/miniconda3/envs/ms/lib/python3.7/site-packages/wandb/sdk/lib/redirect.py", line 747, in uninstall
    _WSCH.remove_fd(self._pipe_read_fd)
  File "/root/autodl-tmp/miniconda3/envs/ms/lib/python3.7/site-packages/wandb/sdk/lib/redirect.py", line 660, in remove_fd
    self._unregister()
  File "/root/autodl-tmp/miniconda3/envs/ms/lib/python3.7/site-packages/wandb/sdk/lib/redirect.py", line 648, in _unregister
    signal.signal(signal.SIGWINCH, self._old_handler)
  File "/root/autodl-tmp/miniconda3/envs/ms/lib/python3.7/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
```
I tried printing the wandb.config, but I got `{}`. 
following [2854#issuecomment-955045336](https://github.com/wandb/client/issues/2854#issuecomment-955045336), I tried :
```
import os
os.environ["WANDB_CONSOLE"] = "off"
```
 However, it still doesn't help.

**Comment by ramit-wandb** [comment]
Hi @cuiyc2000,

I'm sorry this is happening to you. Could you share the `debug.log` and `debug-internal.log` files associated with one of the runs where this is happening? It will give us some more visibility into your issue and will allow me to provide you better assistance.

Thanks,
Ramit

**Comment by cuiyc2000** [comment]
> Hi @cuiyc2000,
> 
> I'm sorry this is happening to you. Could you share the `debug.log` and `debug-internal.log` files associated with one of the runs where this is happening? It will give us some more visibility into your issue and will allow me to provide you better assistance.
> 
> Thanks, Ramit

```
(base) root@container-bc4e118dac-0ee45f86:~/autodl-tmp/PycharmProjects/code/wandb# cat debug.log
2022-05-15 17:43:56,332 INFO    Thread-12 :4144487 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2022-05-15 17:43:56,332 INFO    Thread-12 :4144487 [wandb_setup.py:_flush():76] Loading settings from wandb/settings
2022-05-15 17:43:56,332 INFO    Thread-12 :4144487 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'DLFIN', 'entity': 'cugcuiyc', 'root_dir': '/root/autodl-tmp/PycharmProjects/code', 'sweep_id': 'p037ledq', 'run_id': 'hm2y06z8', 'sweep_param_path': '/root/autodl-tmp/PycharmProjects/code/wandb/sweep-p037ledq/config-hm2y06z8.yaml'}
2022-05-15 17:43:56,332 INFO    Thread-12 :4144487 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program': '/root/autodl-tmp/PycharmProjects/code/main.py'}
2022-05-15 17:43:56,332 INFO    Thread-12 :4144487 [wandb_init.py:_log_setup():428] Logging user logs to /root/autodl-tmp/PycharmProjects/code/wandb/run-20220515_174356-hm2y06z8/logs/debug.log
2022-05-15 17:43:56,333 INFO    Thread-12 :4144487 [wandb_init.py:_log_setup():429] Logging internal logs to /root/autodl-tmp/PycharmProjects/code/wandb/run-20220515_174356-hm2y06z8/logs/debug-internal.log
2022-05-15 17:43:56,333 INFO    Thread-12 :4144487 [wandb_init.py:init():462] calling init triggers
2022-05-15 17:43:56,333 INFO    Thread-12 :4144487 [wandb_init.py:init():466] wandb.init called with sweep_config: {'lr': 0.01, 'optimizer': 'adam'}
config: {}
2022-05-15 17:43:56,333 INFO    Thread-12 :4144487 [wandb_init.py:init():510] wandb.init() called when a run is still active
2022-05-15 17:43:56,338 INFO    Thread-12 :4144487 [wandb_run.py:_finish():1685] finishing run cugcuiyc/DLFIN/enq7k2lp
2022-05-15 17:43:56,339 INFO    Thread-12 :4144487 [wandb_run.py:_atexit_cleanup():1867] got exitcode: 1
2022-05-15 17:43:56,342 INFO    Thread-12 :4144487 [wandb_run.py:_restore():1839] restore
2022-05-15 17:43:58,616 INFO    Thread-12 :4144487 [wandb_run.py:_restore():1839] restore
2022-05-15 17:44:04,578 ERROR   Thread-12 :4144487 [wandb_run.py:_atexit_cleanup():1888] Problem finishing run
Traceback (most recent call last):
  File "/root/autodl-tmp/PycharmProjects/code/trainer.py", line 58, in run_sweep
    opt = self.build_optim(config.optimizer, config.lr)
  File "/root/autodl-tmp/miniconda3/envs/ms/lib/python3.7/site-packages/wandb/sdk/wandb_config.py", line 160, in __getattr__
    return self.__getitem__(key)
  File "/root/autodl-tmp/miniconda3/envs/ms/lib/python3.7/site-packages/wandb/sdk/wandb_config.py", line 128, in __getitem__
    return self._items[key]
KeyError: 'optimizer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/autodl-tmp/miniconda3/envs/ms/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1876, in _atexit_cleanup
    self._on_finish()
  File "/root/autodl-tmp/miniconda3/envs/ms/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1977, in _on_finish
    self._console_stop()  # TODO: there's a race here with jupyter console logging
  File "/root/autodl-tmp/miniconda3/envs/ms/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1916, in _console_stop
    self._restore()
  File "/root/autodl-tmp/miniconda3/envs/ms/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1845, in _restore
    self._err_redir.uninstall()
  File "/root/autodl-tmp/miniconda3/envs/ms/lib/python3.7/site-packages/wandb/sdk/lib/redirect.py", line 747, in uninstall
    _WSCH.remove_fd(self._pipe_read_fd)
  File "/root/autodl-tmp/miniconda3/envs/ms/lib/python3.7/site-packages/wandb/sdk/lib/redirect.py", line 660, in remove_fd
    self._unregister()
  File "/root/autodl-tmp/miniconda3/envs/ms/lib/python3.7/site-packages/wandb/sdk/lib/redirect.py", line 648, in _unregister
    signal.signal(signal.SIGWINCH, self._old_handler)
  File "/root/autodl-tmp/miniconda3/envs/ms/lib/python3.7/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread

(base) root@container-bc4e118dac-0ee45f86:~/autodl-tmp/PycharmProjects/code/wandb# cat debug-internal.log
cat: debug-internal.log: No such file or directory
```

Not good, no debug-internal.log in my computer.

**Comment by cuiyc2000** [comment]
solved, shouldn't use `wandb.init()` in `__init__`

**Comment by fight-think** [comment]
Hello, I put "wandb.init()" into the trainer or self.run() rather than __init__ and still get the empty dict. The wandb version I use is 0.12.21. If I change the version to 0.13.11, I will get the consistent error of "BrokenPipeError: [Errno 32] Broken pipe". Did anyone meet this error?

**Comment by fight-think** [comment]
Update: It has been solved by setting "wandb.run=None" before "run=wandb.init()" in the training function or self.run in this example with version 0.12.21.

**Comment by aroyphillips** [comment]
Can you provide the full code (or the full simple version) for your corrected code? Running into the same issue
