### ISSUE TITLE
[Q] Problem with Proxy Scheme

### ISSUE THREAD

**Issue by pasassi** [wandb/wandb#3685]
Hi, I would like to use wandb in my office computer at the university. Here we are behind a Proxy and when I try to login from the terminal I get the following error:

```
Traceback (most recent call last):
  File "/home/user/.local/bin/wandb", line 5, in <module>
    from wandb.cli.cli import cli
  File "/home/user/.local/lib/python3.8/site-packages/wandb/__init__.py", line 26, in <module>
    from wandb import sdk as wandb_sdk
  File "/home/user/.local/lib/python3.8/site-packages/wandb/sdk/__init__.py", line 5, in <module>
    from . import wandb_helper as helper  # noqa: F401
  File "/home/user/.local/lib/python3.8/site-packages/wandb/sdk/wandb_helper.py", line 6, in <module>
    from .lib import config_util
  File "/home/user/.local/lib/python3.8/site-packages/wandb/sdk/lib/config_util.py", line 7, in <module>
    from wandb.util import load_yaml
  File "/home/user/.local/lib/python3.8/site-packages/wandb/util.py", line 108, in <module>
    sentry_sdk.init(
  File "/home/user/.local/lib/python3.8/site-packages/sentry_sdk/hub.py", line 105, in _init
    client = Client(*args, **kwargs)  # type: ignore
  File "/home/user/.local/lib/python3.8/site-packages/sentry_sdk/client.py", line 89, in __init__
    self._init_impl()
  File "/home/user/.local/lib/python3.8/site-packages/sentry_sdk/client.py", line 111, in _init_impl
    self.transport = make_transport(self.options)
  File "/home/user/.local/lib/python3.8/site-packages/sentry_sdk/transport.py", line 529, in make_transport
    return transport_cls(options)
  File "/home/user/.local/lib/python3.8/site-packages/sentry_sdk/transport.py", line 154, in __init__
    self._pool = self._make_pool(
  File "/home/user/.local/lib/python3.8/site-packages/sentry_sdk/transport.py", line 439, in _make_pool
    return urllib3.ProxyManager(proxy, **opts)
  File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 420, in __init__
    raise ProxySchemeUnknown(proxy.scheme)
urllib3.exceptions.ProxySchemeUnknown: Not supported proxy scheme None
```
Thanks for your help!

**Comment by MBakirWB** [comment]
Hi Pasassi, 

Our python library uses the python requests library for accessing our API. That library respects the standard proxy configuration environment variables, `HTTPS_PROXY` and `HTTP_PROXY`. Our script will use the proxy specified in these variables if they're set in the environment.

**Comment by pasassi** [comment]
I have both variables set to the corresponding proxy. It was needed to run `pip` for example.

**Comment by vanpelt** [comment]
They must have a "scheme", I.e. http:// or https://

**Comment by pasassi** [comment]
Thanks, I was having the following problem, my variables were set like this:

```
export http_proxy=<proxy_name>:<port_number>
export https_proxy=<proxy_name>:<port_number>
```

I included the "scheme" at the beginning and the problem was fixed:

```
export http_proxy=http://<proxy_name>:<port_number>
export https_proxy=https://<proxy_name>:<port_number>
```

**Comment by MBakirWB** [comment]
Hi @pasassi ,

I'm glad you were able to get this addressed. I will be closing this out but please do reach out again if you require additional support.
