### ISSUE TITLE
[CLI]: RecursionError when printing vars on run object

### ISSUE THREAD

**Issue by HallerPatrick** [wandb/wandb#3705]
### Describe the bug

When accessing a run object through the API and calling the built-in `vars` function on it, and printing the result, it causes some infinite recursion logic.

Snippet comparabale to [docs](https://docs.wandb.ai/guides/track/log/logging-faqs#how-can-i-access-the-data-logged-to-my-runs-directly-and-programmatically):
```python 
import wandb

api = wandb.Api()
run = api.run("<some_run>")
print(vars(run))
```

```shell
Traceback (most recent call last):
  File "/Users/patrickhaller/Projects/GERPT/test.py", line 6, in <module>
    print(vars(run))
  File "/Users/patrickhaller/Projects/GERPT/venv/lib/python3.9/site-packages/wandb/apis/public.py", line 998, in __repr__
    return f"<User {self.email}>"
  File "/Users/patrickhaller/Projects/GERPT/venv/lib/python3.9/site-packages/wandb/apis/public.py", line 818, in __getattr__
    raise AttributeError(f"'{repr(self)}' object has no attribute '{name}'")
  File "/Users/patrickhaller/Projects/GERPT/venv/lib/python3.9/site-packages/wandb/apis/public.py", line 998, in __repr__
    return f"<User {self.email}>"
  File "/Users/patrickhaller/Projects/GERPT/venv/lib/python3.9/site-packages/wandb/apis/public.py", line 818, in __getattr__
    raise AttributeError(f"'{repr(self)}' object has no attribute '{name}'")
  File "/Users/patrickhaller/Projects/GERPT/venv/lib/python3.9/site-packages/wandb/apis/public.py", line 998, in __repr__
    return f"<User {self.email}>"
    ...
  File "/Users/patrickhaller/Projects/GERPT/venv/lib/python3.9/site-packages/wandb/apis/public.py", line 818, in __getattr__
    raise AttributeError(f"'{repr(self)}' object has no attribute '{name}'")
  File "/Users/patrickhaller/Projects/GERPT/venv/lib/python3.9/site-packages/wandb/apis/public.py", line 998, in __repr__
    return f"<User {self.email}>"
  File "/Users/patrickhaller/Projects/GERPT/venv/lib/python3.9/site-packages/wandb/apis/public.py", line 810, in __getattr__
    key = self.snake_to_camel(name)
  File "/Users/patrickhaller/Projects/GERPT/venv/lib/python3.9/site-packages/wandb/apis/public.py", line 790, in snake_to_camel
    camel = "".join([i.title() for i in string.split("_")])
  File "/Users/patrickhaller/Projects/GERPT/venv/lib/python3.9/site-packages/wandb/apis/public.py", line 790, in <listcomp>
    camel = "".join([i.title() for i in string.split("_")])
RecursionError: maximum recursion depth exceeded while calling a Python object
```

### Environment

WandB version: 0.12.16

OS: macOS Monetary

Python version: 3.9.10

Versions of relevant libraries:

### Additional Context

* Requires an existing run. 
* I removed part of the stack trace due to length constraints, which was repeating

**Comment by MBakirWB** [comment]
Hi @HallerPatrick ,

I'll be glad to look into this for you. I am able to replicate the error on my end and will need time to review it. Are you attempting to print a specific attribute(s) of `run? In the mean time you could also utilize `print(dir(run))`.

**Comment by HallerPatrick** [comment]
Hey @MBakirWB,

I tried to look into the API through the python console to look at the dict of a `run` object. Out of habit am using `vars` instead of `dir`. This is probably not a urgent bug, I just wanted to let you know :)

**Comment by MBakirWB** [comment]
Hi @HallerPatrick ,

We have identified the bug that causes this recursion. Thanks again for bringing it to our attention. I will be submitting a ticket to our engineering team to address and will update you when a fix is in place. 

Regards,

Mohammad
