### ISSUE TITLE
[CLI]: 

### ISSUE THREAD

**Issue by anil-gurbuz** [wandb/wandb#3743]
### Describe the bug

Last 3 lines of dict_from_config_file(filename, must_exist=False): function expects ["value"] as second level key in config.yml files. I believe that's a bug as removing ["value"] part in the code got it working. 

```python 
os.environ["WANDB_API_KEY"] = "XXXXXXXXXXXXXXXX"
os.environ["WANDB_MODE"] = "offline"

wandb.init(project="GAN", entity="anil-gurbuz", config="./config.yml")

```

```shell
Traceback (most recent call last):
  File "C:\Users\gurbuza\Anaconda3\envs\DL\lib\site-packages\wandb\sdk\wandb_init.py", line 996, in init
    wi.setup(kwargs)
  File "C:\Users\gurbuza\Anaconda3\envs\DL\lib\site-packages\wandb\sdk\wandb_init.py", line 186, in setup
    init_config = parse_config(
  File "C:\Users\gurbuza\Anaconda3\envs\DL\lib\site-packages\wandb\sdk\wandb_helper.py", line 13, in parse_config
    params = config_util.dict_from_config_file(params, must_exist=True)
  File "C:\Users\gurbuza\Anaconda3\envs\DL\lib\site-packages\wandb\sdk\lib\config_util.py", line 120, in dict_from_config_file
    data[k] = v["value"]
KeyError: 'value'
wandb: ERROR Abnormal program exit
Traceback (most recent call last):
  File "C:\Users\gurbuza\Anaconda3\envs\DL\lib\site-packages\wandb\sdk\wandb_init.py", line 996, in init
    wi.setup(kwargs)
  File "C:\Users\gurbuza\Anaconda3\envs\DL\lib\site-packages\wandb\sdk\wandb_init.py", line 186, in setup
    init_config = parse_config(
  File "C:\Users\gurbuza\Anaconda3\envs\DL\lib\site-packages\wandb\sdk\wandb_helper.py", line 13, in parse_config
    params = config_util.dict_from_config_file(params, must_exist=True)
  File "C:\Users\gurbuza\Anaconda3\envs\DL\lib\site-packages\wandb\sdk\lib\config_util.py", line 120, in dict_from_config_file
    data[k] = v["value"]
KeyError: 'value'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\gurbuza\Anaconda3\envs\DL\lib\site-packages\wandb\sdk\wandb_init.py", line 1037, in init
    raise Exception("problem") from error_seen
Exception: problem
```

### Additional Files

config.yml file below

[config.zip](https://github.com/wandb/client/files/8836957/config.zip)

### Environment

WandB version: 0.12.17

OS: Windows 10

Python version: 3.9.12

Versions of relevant libraries:

**Comment by nate-wandb** [comment]
HI @anil-gurbuz thank you for reporting. I believe this is because we expect the `config.yml` to be in the following single-nested format with `value` as a key in the second level:
```
epochs:
  desc: Number of epochs to train over
  value: 100
batch_size:
  desc: Size of each mini-batch
  value: 32
```
Are you able to correctly access all of your config values with your edit to the codebase? For example, does `wandb.config.global.data.real_batch_size` return 128? I would imagine you cannot access these deeper nested parameters this way but I may be wrong. 

Thank you,
Nate

**Comment by anil-gurbuz** [comment]
Hi Nate, 

Thanks for the response. I see what you mean.

I can access up to final level with "." notation -- i.e wandb.config.test_unit --  though final key value pair is only accessiable as a dictionary i.e -- wandb.config.test_unit["model"] --  

Also, it logs those configs correctly to project page as well.

**Comment by nate-wandb** [comment]
Hi @anil-gurbuz,
You're welcome! I wanted to follow up on this and ask if you found that reformatting your sweep.yaml solved the issue for you or if you still feel that we should address this as a bug?

Thank you,
Nate

**Comment by kptkin** [comment]
duplicates #1913
