### ISSUE TITLE
[CLI]: support network architectures with multiple inputs

### ISSUE THREAD

**Issue by AlexanderMelde** [wandb/wandb#3797]
### Describe the bug

Some Network architectures have multiple input layers of various shapes. Keras supports this, but the WandbCallback function throws a ValueError whenever data for such a network is passed to the parameters `training_data` or `validation_data`.

```
ValueError: all input arrays must have the same shape
```

I have created a minimal failing example using the [vgg8_arcface](https://github.com/4uiiurz1/keras-arcface/blob/master/archs.py#L43) network architecture.

```python 
def vgg8_arcface(input_shape, num_classes):
    input = Input(shape=input_shape)
    y = Input(shape=(num_classes,))

    x = vgg_block(input, 16, 2)
    x = MaxPooling2D(pool_size=(2, 2))(x)
    ...


# This is where it fails:
additional_wandb_params = (
    dict(
        log_gradients=True,
        log_evaluation=True,
        training_data=((train_x, train_y), train_y),
        validation_data=((test_x, test_y), test_y),
    )
    if REPRODUCE_ERROR
    else dict()
)

history = model.fit(
    (train_x, train_y),
    train_y,
    epochs=1,
    batch_size=64,
    steps_per_epoch=ds_info.splits["train"].num_examples // 64,
    validation_data=((test_x, test_y), test_y),
    callbacks=[
        wandb.keras.WandbCallback(
            input_type="image",
            save_model=False,
            **additional_wandb_params,
        ),
    ],
)
```
The full code can be seen in this [Gist](https://gist.github.com/AlexanderMelde/004ea3574b12f934bd01305a3fa333d8).
Setting `REPRODUCE_ERROR = False` will disable the wandb logging and no error will be thrown.

The error is the following:

```shell
wandb: WARNING Error initializing ValidationDataLogger in WandbCallback. Skipping logging validation data. Error: 
937/937 [==============================] - ETA: 0s - loss: 4.9142 - accuracy: 0.5350Traceback (most recent call last):
  File "min_fail_2inp.py", line 176, in <module>
    history = model.fit(
  File "\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "\lib\site-packages\wandb\integration\keras\keras.py", line 572, in on_epoch_end
    {"examples": self._log_images(num_images=self.predictions)},
  File "\lib\site-packages\wandb\integration\keras\keras.py", line 784, in _log_images
    np.stack(test_data), batch_size=self._prediction_batch_size
  File "<__array_function__ internals>", line 180, in stack
  File "\lib\site-packages\numpy\core\shape_base.py", line 426, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape
```
Full error log can be seen in this [Git](https://gist.github.com/AlexanderMelde/8c10e5c700f2cf8698ab2afd18c1ac89).

A visualization of the model architecture is attached to the additional files section.

### Additional Files

![model_vgg8_arcface](https://user-images.githubusercontent.com/2115644/173583355-abcc57de-bc71-4ebf-82e7-b18a7b141a33.png)

### Environment

**WandB version:**

- client 0.12.18
- server W&B Local 0.11.0

**OS:** Microsoft Windows 11 Home, Version 10.0.22000 Build 22000

**Python version:** Python 3.10.4

**Versions of relevant libraries:**

- numpy 1.22.4
- tensorflow 2.9.1
- tensorflow-datasets 4.6.0

### Additional Context

Using this network is important for my current research as the mentioned loss is great at clustering the models latent space.

**Comment by AlexanderMelde** [comment]
Looking at the wandb source code, i think the error comes from trying to log the data as images.
The input is assumed to be just an image, and not two inputs, with one being an image and the other being a label (one hot encoded).  

When logging the image,
https://github.com/wandb/client/blob/a339333b3ee93864daf416f04c1501186dffac5c/wandb/integration/keras/keras.py#L748
`test_data` is simply set to the input
https://github.com/wandb/client/blob/a339333b3ee93864daf416f04c1501186dffac5c/wandb/integration/keras/keras.py#L760-L765
and later it is directly passed to input_image_data, even though it is not an image.
https://github.com/wandb/client/blob/a339333b3ee93864daf416f04c1501186dffac5c/wandb/integration/keras/keras.py#L802-L814

So specifying `input_type="image"` in the callback parameters might be my mistake, but i don't see any other way to specify and log this kind of input.

Omitting `input_type="image"` the ValueError is no longer present, but the following warning persists:
```
wandb: WARNING Error initializing ValidationDataLogger in WandbCallback. Skipping logging validation data. Error: 
```

A possible solution would be a list of types in the callback parameters , e.g.  `input_type=["image", "label"]`.

**Comment by sydholl** [comment]
We are closing this issue due to inactivity. If you feel this bug merits additional review, please provide a reproduction and add a comment explaining why. Thank you.
