### ISSUE TITLE
[CLI]: subprocess.CalledProcessError: Command returned non-zero exit status 1.

### ISSUE THREAD

**Issue by GrahamboJangles** [wandb/wandb#3803]
### Describe the bug

I'm trying to run `wandb server start` in Windows 10 through the CMD and I get this error:

```
Command '['docker', 'inspect', 'wandb/local', '--format', '{{json .RepoDigests}}']' returned non-zero exit status 1.
error during connect: In the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json?filters=%7B%22name%22%3A%7B%22wandb-local%22%3Atrue%7D%7D": open //./pipe/docker_engine: The system cannot find the file specified.
Traceback (most recent call last):
  File "E:\Coding_and_Scripting\Pyhon3.10.4\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\Coding_and_Scripting\Pyhon3.10.4\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\Coding_and_Scripting\Pyhon3.10.4\Scripts\wandb.exe\__main__.py", line 7, in <module>
  File "E:\Coding_and_Scripting\Pyhon3.10.4\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "E:\Coding_and_Scripting\Pyhon3.10.4\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "E:\Coding_and_Scripting\Pyhon3.10.4\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "E:\Coding_and_Scripting\Pyhon3.10.4\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "E:\Coding_and_Scripting\Pyhon3.10.4\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "E:\Coding_and_Scripting\Pyhon3.10.4\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "E:\Coding_and_Scripting\Pyhon3.10.4\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "E:\Coding_and_Scripting\Pyhon3.10.4\lib\site-packages\wandb\cli\cli.py", line 96, in wrapper
    return func(*args, **kwargs)
  File "E:\Coding_and_Scripting\Pyhon3.10.4\lib\site-packages\wandb\cli\cli.py", line 1476, in start
    running = subprocess.check_output(
  File "E:\Coding_and_Scripting\Pyhon3.10.4\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "E:\Coding_and_Scripting\Pyhon3.10.4\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker', 'ps', '--filter', 'name=wandb-local', '--format', '{{.ID}}']' returned non-zero exit status 1.
```
I've tried running with and without admin.

### Environment

WandB version: v4.9.0 in the GUI

OS: Windows 10

Python version: 3.10.4

Versions of relevant libraries: I don't know which libraries are relevant

**Comment by vanpelt** [comment]
Hey @GrahamboJangles the error looks like a permission error.  Can you try running the following from an admin console and share any errors returned?

```shell
docker inspect wandb/local --format '{{json .RepoDigests}}'
```

**Comment by GrahamboJangles** [comment]
@vanpelt `Template parsing error: template: :1: unclosed action`

**Comment by vanpelt** [comment]
@GrahamboJangles I would try with double quotes instead of single quotes.  Also, what version of docker are you running?  You may need to upgrade your version of docker.

```
docker version
docker inspect wandb/local --format "{{json .RepoDigests}}"
```

**Comment by GrahamboJangles** [comment]
@vanpelt `docker version` returns
```
error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/version": open //./pipe/docker_engine: The system cannot find the file specified.
Client:
 Cloud integration: v1.0.25
 Version:           20.10.16
 API version:       1.41
 Go version:        go1.17.10
 Git commit:        aa7e414
 Built:             Thu May 12 09:17:07 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true
```
`docker inspect wandb/local --format "{{json .RepoDigests}}"` returns
```
error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/wandb/local/json": open //./pipe/docker_engine: The system cannot find the file specified.
```

**Comment by MBakirWB** [comment]
@GrahamboJangles ,

Have you downloaded the Linux Kernel Update package per the WSL 2 error window? If yes, are you still experiencing errors with launching your Docker container?

**Comment by MBakirWB** [comment]
Hi @GrahamboJangles , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by GrahamboJangles** [comment]
@MBakirWB Hi, sorry for the long response-time. I have installed the Linux Kernal Update per the error window using `wsl_update_x64.msi`, and I had to run it as administrator after doing so to get it to work.

**Comment by grvrjt** [comment]
how to handle the error  subprocess.CalledProcessError: Command '['ifconfig', 'wlan0']' returned non-zero exit status 1.
So that  i can show in the terminal a user friendly message .
