### ISSUE TITLE
[CLI]: Can't find a run using only `run_id`

### ISSUE THREAD

**Issue by martinabeleda** [wandb/wandb#3830]
### Describe the bug

Based on the documentation for `wandb.api.public.Api` I expect that I could find a run given only the `run_id` if the entity and project are set in `api.settings`:

> path to run in the form entity/project/run_id. If api.entity is set, this can be in the form project/run_id and if api.project is set this can just be the run_id.

When I try do to exactly that, I get an error:

```python 
import os
import wandb

# Create a project under a team
run = wandb.init(entity="my-entity", project="my-project")
run_id = run.id

# We can fetch the run if we know the entity and the project
wandb.Api().run(f"my-entity/my-project/{run_id}")

# We should be able to fetch the run using the Api if entity and project are set
os.environ["WANDB_ENTITY"] = "my-entity"
os.environ["WANDB_PROJECT"] = "my-project"
wandb.Api().run(run_id)
```

From the logs, we can see that the path is resolved incorrectly, with the `run_id` in place of the project name.

```shell
Traceback (most recent call last):
  File "/Users/martinabeleda/Development/martinabeleda/client/wandb/apis/normalize.py", line 22, in wrapper
    return func(*args, **kwargs)
  File "/Users/martinabeleda/Development/martinabeleda/client/wandb/apis/public.py", line 733, in run
    self._runs[path] = Run(self.client, entity, project, run)
  File "/Users/martinabeleda/Development/martinabeleda/client/wandb/apis/public.py", line 1582, in __init__
    self.load(force=not _attrs)
  File "/Users/martinabeleda/Development/martinabeleda/client/wandb/apis/public.py", line 1686, in load
    raise ValueError("Could not find run %s" % self)
ValueError: Could not find run <Run my-entity/yx0pjmex/yx0pjmex (not found)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martinabeleda/Development/martinabeleda/client/test.py", line 15, in <module>
    wandb.Api().run(run_id)
  File "/Users/martinabeleda/Development/martinabeleda/client/wandb/apis/normalize.py", line 58, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "/Users/martinabeleda/Development/martinabeleda/client/wandb/apis/normalize.py", line 22, in wrapper
    return func(*args, **kwargs)
  File "/Users/martinabeleda/Development/martinabeleda/client/wandb/apis/public.py", line 733, in run
    self._runs[path] = Run(self.client, entity, project, run)
  File "/Users/martinabeleda/Development/martinabeleda/client/wandb/apis/public.py", line 1582, in __init__
    self.load(force=not _attrs)
  File "/Users/martinabeleda/Development/martinabeleda/client/wandb/apis/public.py", line 1686, in load
    raise ValueError("Could not find run %s" % self)
wandb.errors.CommError: Could not find run <Run my-entity/yx0pjmex/yx0pjmex (not found)>
```

We can confirm this behaviour by calling `api._parse_path()` directly:

```python
>>> wandb.Api()._parse_path("my-entity/my-project/yx0pjmex")
('my-entity', 'my-project', 'yx0pjmex')
>>> wandb.Api()._parse_path("yx0pjmex")
('my-entity', 'yx0pjmex', 'yx0pjmex')
```

### Environment

WandB version: `0.13.0rc4.dev1

OS: `macOS Monterrey 12.3.1`

Python version: `3.10.4`

Versions of relevant libraries: None, I believe this error is internal to `wandb`

**Comment by armanhar** [comment]
Hey Martin, thanks for flagging this. I'll reproduce the issue on my end and file a ticket.

**Comment by martinabeleda** [comment]
@armanhar I was working on a fix for this but a little unsure about what the expected behaviour should be if parse path is called without project set. I've added some tests in https://github.com/wandb/client/pull/3832 to try to clarify the expected behaviour. Let me know if that is correct and I can go ahead with implementation

**Comment by armanhar** [comment]
Hey @martinabeleda, apologies about the delay on this. I'll double-check with the team on the expected behavior and let you know.

**Comment by ramit-wandb** [comment]
Hi @martinabeleda,

Could you share where you read this in our docs? I don't believe this is something we support, other than defaulting to the logged in entity in case of the entity not being passed in to the run path. 

Thanks,
Ramit

**Comment by martinabeleda** [comment]
@ramit-wandb It's under the docs for [`wandb.public.Api.run()`](https://docs.wandb.ai/ref/python/public-api/api#run).

**Comment by ramit-wandb** [comment]
Thanks @martinabeleda,

I have filed a bug report for this for our engineering team and let them know of the PR you have created. I'll keep you updated on the status of this issue.

**Comment by jacobromero** [comment]
This appears to have been fixed in v0.16.3. I have also tested in the latest version of the SDK which also works.
Feel free to re-open if this issue still present for you.
