### ISSUE TITLE
[CLI]: Crash on init when starting with guild

### ISSUE THREAD

**Issue by samedii** [wandb/wandb#3859]
### Describe the bug

```python 
    wandb.init(project="my-project")
```

```shell
➜ guild run train -y
Refreshing flags...                                                                                                                                                                                        
Resolving splits dependency                   
Resolving config dependency
wandb: Currently logged in as: samedii. Use `wandb login --relogin` to force relogin
Problem at: /home/richard/Documents/trafikverket-wire-damage-generation/.venv/.guild/runs/65ce589556a04fccbd8fe997ea9c04db/.guild/sourcecode/operations/train.py 30 train
Traceback (most recent call last):
  File "/home/richard/Documents/trafikverket-wire-damage-generation/.venv/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 999, in init
    run = wi.init()
  File "/home/richard/Documents/trafikverket-wire-damage-generation/.venv/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 523, in init
    backend.ensure_launched()
  File "/home/richard/Documents/trafikverket-wire-damage-generation/.venv/lib/python3.8/site-packages/wandb/sdk/backend/backend.py", line 215, in ensure_launched
    self._module_main_install()
  File "/home/richard/Documents/trafikverket-wire-damage-generation/.venv/lib/python3.8/site-packages/wandb/sdk/backend/backend.py", line 116, in _module_main_install
    main_module.__spec__ = main_mod_spec
AttributeError: 'dict' object has no attribute '__spec__'
```

### Environment

WandB version: 0.12.19

OS: Ubuntu 20.04.4 LTS

Python version: 3.8.8

Versions of relevant libraries: guild 0.8.1

**Comment by samedii** [comment]
Added PR for dockerpycreds https://github.com/shin-/dockerpy-creds/pull/15 but should be unrelated to the main issue of the pdb hack stopping running via guild.

**Comment by kptkin** [comment]
This issue is resolve with wandb>=0.13.0. If you still seeing a problem, feel free to re-open this issue.
