### ISSUE TITLE
wandb.sklearn.plot_confusion_matrix cannot find confusion_matrix_0_xxxxxxxx.table.json

### ISSUE THREAD

**Issue by stephano41** [wandb/wandb#3912]
### Describe the bug

I am using  pytorch lightning with the wandb logger from pytorch lightning. In my lightning module at test_epoch_end I have:

```
def test_epoch_end(self, output):
  ...
  wandb.log({"Confusion Matrix": wandb.sklearn.plot_confusion_matrix(target, preds)})
```
where target is a list containing:
```[0 1 0 1 1 1 0 0 0 1 0 0 0 1 1 1 1 0 0 1 0 1 0 0 0 1 1 0 1 1 1 1 1 0 0 0 0
 1 0 0 0 1 0 0 1 0 1 0 0 1 1 0 1 1 1 0 1 1 1 1 0 1 1 1 1 1 0 0 1 0 0 0 1 0
 1 0 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 0 0 1 1 1 0 0 1 1 0 1 1 1]
```
 
and preds is:
```[1. 0. 1. 1. 0. 1. 1. 1. 0. 1. 0. 0. 0. 1. 1. 1. 1. 0. 0. 1. 0. 1. 1. 0.
 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 1. 0. 1. 0. 1. 1. 1. 1. 0. 1. 0.
 0. 0. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1. 0. 0. 0.
 1. 0. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1.
 1. 1. 1. 0. 1. 0. 0. 1. 1. 1.]
```
However, when I run trainer.test() (which calls test_epoch_end) 
i get the error:
```
[Errno 2] No such file or directory: 'C:\\Users\\Steven\\OneDrive - University of Adelaide\\Python Scripts\\GRF_hip_outcomes\\outputs\\debug-cnn_lstm_v1\\2022-07-07-21-33-52\\test-test_test2022-07-08-19-26-10\\wandb\\run-20220708_192613-26lg8yiq\\files\\media\\table\\confusion_matrix_0_e4fddc643e696677764d.table.json'
```
where `C:\\Users\\Steven\\OneDrive - University of Adelaide\\Python Scripts\\GRF_hip_outcomes\\outputs\\debug-cnn_lstm_v1\\2022-07-07-21-33-52\\test-test_test2022-07-08-19-26-10\` is the save directory root

the full stack is:
```
Traceback (most recent call last):
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\shutil.py", line 791, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\Steven\\AppData\\Local\\Temp\\tmpikgg_xxgwandb-media\\3gylmzlq.table.json' -> 'C:\\Users\\Steven\\OneDrive - University of Adelaide\\Python Scripts\\GRF_hip_outcomes\\outputs\\debug-cnn_lstm_v1\\2022-07-07-21-33-52\\test-test_test2022-07-08-19-26-10\\wandb\\run-20220708_192613-26lg8yiq\\files\\media\\table\\confusion_matrix_0_e4fddc643e696677764d.table.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "evaluate.py", line 140, in <module>
    main()
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\hydra\main.py", line 90, in decorated_main
    _run_hydra(
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\hydra\_internal\utils.py", line 389, in _run_hydra
    _run_app(
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\hydra\_internal\utils.py", line 452, in _run_app
    run_and_report(
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\hydra\_internal\utils.py", line 216, in run_and_report
    raise ex
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\hydra\_internal\utils.py", line 213, in run_and_report
    return func()
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\hydra\_internal\utils.py", line 453, in <lambda>
    lambda: hydra.run(
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\hydra\_internal\hydra.py", line 132, in run
    _ = ret.return_value
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\hydra\core\utils.py", line 260, in return_value
    raise self._return_value
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\hydra\core\utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "evaluate.py", line 71, in main
    out = trainer.test(model=model, dataloaders=datamodule, ckpt_path=checkpoint_file)
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 938, in test
    return self._call_and_handle_interrupt(self._test_impl, model, dataloaders, ckpt_path, verbose, datamodule)
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 723, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 985, in _test_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1236, in _run
    results = self._run_stage()
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1320, in _run_stage
    return self._run_evaluate()
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1365, in _run_evaluate
    eval_loop_results = self._evaluation_loop.run()
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\pytorch_lightning\loops\base.py", line 211, in run
    output = self.on_run_end()
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\pytorch_lightning\loops\dataloader\evaluation_loop.py", line 188, in on_run_end
    self._evaluation_epoch_end(self._outputs)
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\pytorch_lightning\loops\dataloader\evaluation_loop.py", line 313, in _evaluation_epoch_end
    self.trainer._call_lightning_module_hook("test_epoch_end", output_or_outputs)
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1595, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "C:\Users\Steven\OneDrive - University of Adelaide\Python Scripts\GRF_hip_outcomes\srcs\models\grf_module.py", line 75, in test_epoch_end
    "Confusion Matrix": wandb.sklearn.plot_confusion_matrix(target, preds)
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\wandb\sklearn\plot\classifier.py", line 179, in confusion_matrix
    wandb.log({"confusion_matrix": confusion_matrix_chart})
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\wandb\sdk\wandb_run.py", line 256, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\wandb\sdk\wandb_run.py", line 222, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\wandb\sdk\wandb_run.py", line 1543, in log
    self._log(data=data, step=step, commit=commit)
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\wandb\sdk\wandb_run.py", line 1334, in _log
    self._partial_history_callback(data, step, commit)
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\wandb\sdk\wandb_run.py", line 1223, in _partial_history_callback
    self._backend.interface.publish_partial_history(
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\wandb\sdk\interface\interface.py", line 541, in publish_partial_history
    data = history_dict_to_json(run, data, step=user_step, ignore_copy_err=True)
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\wandb\sdk\data_types\utils.py", line 54, in history_dict_to_json
    payload[key] = val_to_json(
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\wandb\sdk\data_types\utils.py", line 162, in val_to_json
    val.bind_to_run(run, key, namespace)
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\wandb\data_types.py", line 529, in bind_to_run
    super().bind_to_run(*args, **kwargs)
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\wandb\sdk\data_types\base_types\media.py", line 132, in bind_to_run
    shutil.move(self._path, new_path)
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\shutil.py", line 811, in move
    copy_function(src, real_dst)
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Steven\\OneDrive - University of Adelaide\\Python Scripts\\GRF_hip_outcomes\\outputs\\debug-cnn_lstm_v1\\2022-07-07-21-33-52\\test-test_test2022-07-08-19-26-10\\wandb\\run-20220708_192613-26lg8yiq\\files\\media\\table\\confusion_matrix_0_e4fddc643e696677764d.table.json'
Traceback (most recent call last):
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\shutil.py", line 791, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\Steven\\AppData\\Local\\Temp\\tmpikgg_xxgwandb-media\\3gylmzlq.table.json' -> 'C:\\Users\\Steven\\OneDrive - University of Adelaide\\Python Scripts\\GRF_hip_outcomes\\outputs\\debug-cnn_lstm_v1\\2022-07-07-21-33-52\\test-test_test2022-07-08-19-26-10\\wandb\\run-20220708_192613-26lg8yiq\\files\\media\\table\\confusion_matrix_0_e4fddc643e696677764d.table.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "evaluate.py", line 140, in <module>
    main()
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\hydra\main.py", line 90, in decorated_main
    _run_hydra(
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\hydra\_internal\utils.py", line 389, in _run_hydra
    _run_app(
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\hydra\_internal\utils.py", line 452, in _run_app
    run_and_report(
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\hydra\_internal\utils.py", line 216, in run_and_report
    raise ex
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\hydra\_internal\utils.py", line 213, in run_and_report
    return func()
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\hydra\_internal\utils.py", line 453, in <lambda>
    lambda: hydra.run(
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\hydra\_internal\hydra.py", line 132, in run
    _ = ret.return_value
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\hydra\core\utils.py", line 260, in return_value
    raise self._return_value
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\hydra\core\utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "evaluate.py", line 71, in main
    out = trainer.test(model=model, dataloaders=datamodule, ckpt_path=checkpoint_file)
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 938, in test
    return self._call_and_handle_interrupt(self._test_impl, model, dataloaders, ckpt_path, verbose, datamodule)
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 723, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 985, in _test_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1236, in _run
    results = self._run_stage()
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1320, in _run_stage
    return self._run_evaluate()
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1365, in _run_evaluate
    eval_loop_results = self._evaluation_loop.run()
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\pytorch_lightning\loops\base.py", line 211, in run
    output = self.on_run_end()
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\pytorch_lightning\loops\dataloader\evaluation_loop.py", line 188, in on_run_end
    self._evaluation_epoch_end(self._outputs)
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\pytorch_lightning\loops\dataloader\evaluation_loop.py", line 313, in _evaluation_epoch_end
    self.trainer._call_lightning_module_hook("test_epoch_end", output_or_outputs)
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1595, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "C:\Users\Steven\OneDrive - University of Adelaide\Python Scripts\GRF_hip_outcomes\srcs\models\grf_module.py", line 75, in test_epoch_end
    "Confusion Matrix": wandb.sklearn.plot_confusion_matrix(target, preds)
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\wandb\sklearn\plot\classifier.py", line 179, in confusion_matrix
    wandb.log({"confusion_matrix": confusion_matrix_chart})
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\wandb\sdk\wandb_run.py", line 256, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\wandb\sdk\wandb_run.py", line 222, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\wandb\sdk\wandb_run.py", line 1543, in log
    self._log(data=data, step=step, commit=commit)
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\wandb\sdk\wandb_run.py", line 1334, in _log
    self._partial_history_callback(data, step, commit)
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\wandb\sdk\wandb_run.py", line 1223, in _partial_history_callback
    self._backend.interface.publish_partial_history(
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\wandb\sdk\interface\interface.py", line 541, in publish_partial_history
    data = history_dict_to_json(run, data, step=user_step, ignore_copy_err=True)
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\wandb\sdk\data_types\utils.py", line 54, in history_dict_to_json
    payload[key] = val_to_json(
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\wandb\sdk\data_types\utils.py", line 162, in val_to_json
    val.bind_to_run(run, key, namespace)
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\wandb\data_types.py", line 529, in bind_to_run
    super().bind_to_run(*args, **kwargs)
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\site-packages\wandb\sdk\data_types\base_types\media.py", line 132, in bind_to_run
    shutil.move(self._path, new_path)
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\shutil.py", line 811, in move
    copy_function(src, real_dst)
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\Steven\anaconda3\envs\GRF_hip_outcomes\lib\shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Steven\\OneDrive - University of Adelaide\\Python Scripts\\GRF_hip_outcomes\\outputs\\debug-cnn_lstm_v1\\2022-07-07-21-33-52\\test-test_test2022-07-08-19-26-10\\wandb\\run-20220708_192613-26lg8yiq\\files\\media\\table\\confusion_matrix_0_e4fddc643e696677764d.table.json'
wandb:         
```

### Environment

WandB version: 0.12.21

OS: Windows

Python version: 3.9

Versions of relevant libraries: pytorch lightning 1.6

**Comment by nate-wandb** [comment]
Hi @stephano41, it looks like you are setting your root directory as a network drive correct? This often causes these sort of errors as these can become temporarily unaccessible. Would it work for you to set the root dir to a local drive and then transfer runs over to your network drive upon completion of the run?

Thank you,
Nate

**Comment by stephano41** [comment]
Hi @nate-wandb thank you for your response, I tried a few things and eventually disabling the path length limit on my windows machine made it work
