### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'box_keys'

### ISSUE THREAD

**Issue by SioGilroy** [wandb/wandb#3922]
I followed the tutorial in the video https://www.youtube.com/watch?v=5h5UtLau3Vc, however, I am getting this error. I am using Google Collab

Traceback (most recent call last):
  File "train.py", line 667, in <module>
    main(opt)
  File "train.py", line 562, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 91, in train
    loggers = Loggers(save_dir, weights, opt, hyp, LOGGER)  # loggers instance
  File "/content/yolov5/utils/loggers/__init__.py", line 82, in __init__
    self.wandb = WandbLogger(self.opt, run_id)
  File "/content/yolov5/utils/loggers/wandb/wandb_utils.py", line 185, in __init__
    self.setup_training(opt)
  File "/content/yolov5/utils/loggers/wandb/wandb_utils.py", line 248, in setup_training
    self.val_table = self.val_artifact.get("val")
  File "/usr/local/lib/python3.7/dist-packages/wandb/apis/public.py", line 3740, in get
    result = wb_class.from_json(json_obj, self)
  File "/usr/local/lib/python3.7/dist-packages/wandb/data_types.py", line 497, in from_json
    json_obj["column_types"], source_artifact
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/_dtypes.py", line 78, in type_from_dict
    return _type.from_json(json_dict, artifact)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/_dtypes.py", line 251, in from_json
    return cls(**_json_obj_to_params_obj(json_dict.get("params", {}), artifact))
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/_dtypes.py", line 153, in _json_obj_to_params_obj
    for key in json_obj
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/_dtypes.py", line 153, in <dictcomp>
    for key in json_obj
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/_dtypes.py", line 153, in _json_obj_to_params_obj
    for key in json_obj
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/_dtypes.py", line 153, in <dictcomp>
    for key in json_obj
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/_dtypes.py", line 149, in _json_obj_to_params_obj
    return TypeRegistry.type_from_dict(json_obj, artifact)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/_dtypes.py", line 78, in type_from_dict
    return _type.from_json(json_dict, artifact)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/_dtypes.py", line 251, in from_json
    return cls(**_json_obj_to_params_obj(json_dict.get("params", {}), artifact))
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/_dtypes.py", line 153, in _json_obj_to_params_obj
    for key in json_obj
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/_dtypes.py", line 153, in <dictcomp>
    for key in json_obj
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/_dtypes.py", line 156, in _json_obj_to_params_obj
    return [_json_obj_to_params_obj(item, artifact) for item in json_obj]
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/_dtypes.py", line 156, in <listcomp>
    return [_json_obj_to_params_obj(item, artifact) for item in json_obj]
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/_dtypes.py", line 149, in _json_obj_to_params_obj
    return TypeRegistry.type_from_dict(json_obj, artifact)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/_dtypes.py", line 78, in type_from_dict
    return _type.from_json(json_dict, artifact)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/_dtypes.py", line 251, in from_json
    return cls(**_json_obj_to_params_obj(json_dict.get("params", {}), artifact))
TypeError: __init__() got an unexpected keyword argument 'box_keys'

**Comment by lesliewandb** [comment]
Hi @SioGilroy, can you send me a code snippet of how you implemented wandb.init please? Also, can you let me know which version of wandb you are using? If you are not using our latest version (0.12.21) can you upgrade to it and see if that is able to fix this?

**Comment by 1208zuyi** [comment]
HI @SioGilroy Have you solve the problem? Because I got that error too.

**Comment by 1208zuyi** [comment]
HI @SioGilroy, have you solve the problem? Because I also got that error. Just wanted to ask if there is a solution.

**Comment by lilsnow0001** [comment]
Hi @SioGilroy Have you solve the error? Because I also got that problem. Just wanted to ask if there is a solution.

**Comment by SioGilroy** [comment]
I ran the code on my terminal instead of Google Collab and it works now, but it still does not work on Google Collab

**Comment by lesliewandb** [comment]
Thank you for the update. Can you give me the debug logs for when you tried it in Colab please?
