### ISSUE TITLE
[CLI]: wandb artifact download error within docker

### ISSUE THREAD

**Issue by alib022** [wandb/wandb#4051]
### Describe the bug

Hi,
I have a simple code to download the artifact from the aws through wandb. The code works, however, as soon as I run the code within docker I am getting Bad Request error from the boto.3. Is there any solution for this?

```python

run = wandb.init(project=const.WANDB_PROJECT, job_type='inference', entity=const.WANDB_ENTITY)
artifact = run.use_artifact(const.WANDB_MODEL_NAME + ':latest')
modelPath = artifact.download()

```

```shell
wandb: Downloading large artifact cloud:latest, 102.72MB. 2 files... Found credentials in environment variables.
Found credentials in environment variables.
Traceback (most recent call last):
  
  File "/opt/conda/lib/python3.8/site-packages/wandb/apis/public.py", line 4381, in download
    pool.map(partial(self._download_file, root=dirpath), manifest.entries)
  File "/opt/conda/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/opt/conda/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/opt/conda/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/opt/conda/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/opt/conda/lib/python3.8/site-packages/wandb/apis/public.py", line 4475, in _download_file
    return self.get_path(name).download(root)
  File "/opt/conda/lib/python3.8/site-packages/wandb/apis/public.py", line 3840, in download
    cache_path = manifest.storage_policy.load_reference(
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_artifacts.py", line 935, in load_reference
    return self._handler.load_path(artifact, manifest_entry, local)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_artifacts.py", line 1091, in load_path
    return self._handlers[str(url.scheme)].load_path(
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_artifacts.py", line 1374, in load_path
    etag = self._etag_from_obj(obj)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_artifacts.py", line 1541, in _etag_from_obj
    etag = obj.e_tag[1:-1]  # escape leading and trailing quote
  File "/opt/conda/lib/python3.8/site-packages/boto3/resources/factory.py", line 339, in property_loader
    self.load()
  File "/opt/conda/lib/python3.8/site-packages/boto3/resources/factory.py", line 505, in do_action
    response = action(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/opt/conda/lib/python3.8/site-packages/botocore/client.py", line 388, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/conda/lib/python3.8/site-packages/botocore/client.py", line 708, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (400) when calling the HeadObject operation: Bad Request


```

### Environment

WandB version:

OS: Ubuntu 20.04

Python version: 3.8

Versions of relevant libraries:

**Comment by MBakirWB** [comment]
Hi @alib022 , can you please provide you debug logs for the crashed run and we will take a closer look. The debug.log and debug-internal.log files are within your local wandb run folder. They may help indicate what the issue is.

**Comment by MBakirWB** [comment]
Hi @alib022 , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
