### ISSUE TITLE
How to run wandb sweeps with ray rllib?

### ISSUE THREAD

**Issue by dejangrubisic** [wandb/wandb#4062]
I am trying to use wandb with ray, but I cannot make it work. I am 

```
def train():
  wandb_run_id = datetime.now().strftime("%Y%m%d_%H%M%S")
    with wandb.init(
        project="my_project", 
        entity="my_entity",
        id=wandb_run_id,
        # resume="must", # Tried this
        # reinit=True  # Tried this
    ):
    analysis = tune.run(
        PPOTrainer,
        checkpoint_at_end=True,
        config=wandb.config, 
        stop=stop_criteria,    
        callbacks=[ WandbLoggerCallback(
                        project="my_project",
                        api_key_file="/wandb_key.txt",
                        log_config=False,
                        id=wandb_run_id)
                            ])


sweep_id = wandb.sweep(sweep_config, project="my_project")
wandb.agent(sweep_id=sweep_id, function=train, count=sweep_count)
```

I am constantly getting this error:
```
Traceback (most recent call last):
  File "/private/home/dejang/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1040, in init
    wi.setup(kwargs)
  File "/private/home/dejang/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 186, in setup
    tel.feature.set_init_tags = True
  File "/private/home/dejang/.local/lib/python3.8/site-packages/wandb/sdk/lib/telemetry.py", line 41, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/private/home/dejang/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 572, in _telemetry_callback
    self._telemetry_flush()
  File "/private/home/dejang/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 583, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/private/home/dejang/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 74, in _publish_telemetry
    self._publish(rec)
  File "/private/home/dejang/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface_queue.py", line 48, in _publish
    if self._process_check and self._process and not self._process.is_alive():
  File "/private/home/dejang/.conda/envs/compiler_gym/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
```
After this it continues and terminates with extra errors.

```
Number of trials: 1/1 (1 TERMINATED)
+-------------------------------------+------------+----------------------+--------+------------------+------+----------+----------------------+----------------------+--------------------+
| Trial name                          | status     | loc                  |   iter |   total time (s) |   ts |   reward |   episode_reward_max |   episode_reward_min |   episode_len_mean |
|-------------------------------------+------------+----------------------+--------+------------------+------+----------+----------------------+----------------------+--------------------|
| PPOTrainer_compiler_gym_e8bc4_00000 | TERMINATED | 100.97.72.14:2557862 |      1 |          16.1025 | 6000 | 0.883231 |              20.3819 |             -13.4179 |                 10 |
+-------------------------------------+------------+----------------------+--------+------------------+------+----------+----------------------+----------------------+--------------------+


2022-08-05 14:10:19,953 INFO tune.py:747 -- Total run time: 44.26 seconds (42.39 seconds for the tuning loop).
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb:                                                                                
wandb: Synced devout-sweep-1: https://wandb.ai/dejang/loop_tool_agent/runs/3vj4onkk
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20220805_140920-3vj4onkk/logs
Run 3vj4onkk errored: NotADirectoryError(20, 'Not a directory')
wandb: ERROR Run 3vj4onkk errored: NotADirectoryError(20, 'Not a directory')
```

What would be the right way to do this?

**Comment by MBakirWB** [comment]
Hi @dejangrubisic , thank-you for writing in. I will review and provide a response this week.

**Comment by MBakirWB** [comment]
Hi @dejangrubisic can you use `wandb.require("service")` before calling `ray.init()`. Wandb [service](https://docs.wandb.ai/guides/track/advanced/distributed-training#wandb-service) addresses some common issues with distributed training.

**Comment by MBakirWB** [comment]
Hi @dejangrubisic , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
