### ISSUE TITLE
[CLI]: Specifying probabilities in a sweep configuration doesn't work with method = "bayes"

### ISSUE THREAD

**Issue by LeoGrin** [wandb/wandb#4125]
### Describe the bug

# Issue

Specifying values and probabilities for hyperparameter distribution doesn't work with `method="bayes"`

# Minimal example
```python
    sweep_config = {
        "program": "run_experiment.py",
        "name": "BO",
        "project": project,
        "method": "bayes",
        "metric": {
            "name": "mean_test_score",
            "goal": "minimize"  # RMSE
        },
        "parameters": {"learning_rate": {"values": [0.1, 0.2], "probabilities": [0.8, 0.2]}}
    }

    sweep_id = wandb.sweep(sweep_config, project=project)
```

# Full traceback

```shell
400 response executing GraphQL.
{"errors":[{"message":"Invalid sweep config: arrays used as indices must be of integer (or boolean) type","path":["upsertSweep"]}],"data":{"upsertSweep":null}}
wandb: ERROR Error while calling W&B API: Invalid sweep config: arrays used as indices must be of integer (or boolean) type (<Response [400]>)
wandb: ERROR Invalid sweep config: arrays used as indices must be of integer (or boolean) type
Traceback (most recent call last):
  File "/Users/leo/opt/anaconda3/envs/stage/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 113, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/leo/opt/anaconda3/envs/stage/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 204, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/Users/leo/opt/anaconda3/envs/stage/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/leo/opt/anaconda3/envs/stage/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/leo/opt/anaconda3/envs/stage/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/Users/leo/opt/anaconda3/envs/stage/lib/python3.8/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/leo/opt/anaconda3/envs/stage/lib/python3.8/site-packages/wandb/apis/normalize.py", line 25, in wrapper
    return func(*args, **kwargs)
  File "/Users/leo/opt/anaconda3/envs/stage/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2181, in upsert_sweep
    raise e
  File "/Users/leo/opt/anaconda3/envs/stage/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2166, in upsert_sweep
    response = self.gql(
  File "/Users/leo/opt/anaconda3/envs/stage/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 129, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/Users/leo/opt/anaconda3/envs/stage/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2156, in no_retry_4xx
    raise UsageError(body["errors"][0]["message"])
wandb.errors.UsageError: Invalid sweep config: arrays used as indices must be of integer (or boolean) type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "launch_config/launch_bo_test.py", line 68, in <module>
    sweep_id = create_sweep_bo(data_transform_config,
  File "launch_config/launch_bo_test.py", line 54, in create_sweep_bo
    sweep_id = wandb.sweep(sweep_config, project=project)
  File "/Users/leo/opt/anaconda3/envs/stage/lib/python3.8/site-packages/wandb/sdk/wandb_sweep.py", line 112, in sweep
    sweep_id, warnings = api.upsert_sweep(sweep)
  File "/Users/leo/opt/anaconda3/envs/stage/lib/python3.8/site-packages/wandb/apis/internal.py", line 102, in upsert_sweep
    return self.api.upsert_sweep(*args, **kwargs)
  File "/Users/leo/opt/anaconda3/envs/stage/lib/python3.8/site-packages/wandb/apis/normalize.py", line 61, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "/Users/leo/opt/anaconda3/envs/stage/lib/python3.8/site-packages/wandb/apis/normalize.py", line 25, in wrapper
    return func(*args, **kwargs)
  File "/Users/leo/opt/anaconda3/envs/stage/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2181, in upsert_sweep
    raise e
  File "/Users/leo/opt/anaconda3/envs/stage/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2166, in upsert_sweep
    response = self.gql(
  File "/Users/leo/opt/anaconda3/envs/stage/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 129, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/Users/leo/opt/anaconda3/envs/stage/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2156, in no_retry_4xx
    raise UsageError(body["errors"][0]["message"])
wandb.errors.CommError: Invalid sweep config: arrays used as indices must be of integer (or boolean) type

```

### Environment

WandB version: 0.13.1

OS: MacOS Monterey 12.0.1

Python version: 3.8.8

Versions of relevant libraries:

**Comment by MBakirWB** [comment]
Hi @LeoGrin , thank-you for writing in. We will have to look into this further but yes the "Bayes" method doesn't accept a nested dictionary, example from your code `"parameters": {"learning_rate": {"values": [0.1, 0.2], "probabilities": [0.8, 0.2]}}`. Is there a reason this is you approach vs defining a learning_rate [distribution](https://docs.wandb.ai/guides/sweeps/configuration#parameters) to run Bayes over? Or perhaps defining the values of learning rate as `[0.1] * 8 + [0.2] * 2`?

**Comment by LeoGrin** [comment]
Thank for your answer @MBakirWB. I used "learning_rate" as a simple example, but I wanted to use this for discrete parameters. Your second solution `[0.1] * 8 + [0.2] * 2` should work!

**Comment by MBakirWB** [comment]
Hi @LeoGrin, thank-you for clarifying and also letting me the example might work. Please do feel free to write in again with any follow ups, I will mark this closed for now.

**Comment by ellisbrown** [comment]
> but I wanted to use this for discrete parameters

I'm currently trying to do precisely this and am having trouble. The [example from the docs](https://docs.wandb.ai/guides/sweeps/configuration#examples-1) even fails
```
parameter_name:
    values: [1, 2, 3, 4, 5]
    probabilities: [0.1, 0.2, 0.1, 0.25, 0.35]
```

<img width="389" alt="image" src="https://user-images.githubusercontent.com/5157986/186776980-0f0f1f78-2723-4cb8-81cf-976b3e3e56e6.png">

Error message on hover is `Property probabilities is not allowed.`

**Comment by MBakirWB** [comment]
Hi @ellisbrown , [probabilities ](https://docs.wandb.ai/guides/sweeps/configuration#:~:text=values%20when%20using-,random,-.)can only be used with `method: random`. Modify your method and you should no longer see the error.
