### ISSUE TITLE
[CLI]: Connection issues with local (Docker) setup and Optuna multi-threading

### ISSUE THREAD

**Issue by mimxrt** [wandb/wandb#4134]
### Describe the bug

Trying to combine Optuna and a Docker wandb instance, I get connection issues when using multi-threading. Removing the `n_jobs=2` parameter from `optuna.create_study()` makes the issue go away. (Remoing the wandb-related code will also get rid of the errors, even with `n_jobs` enabled). I hope there is a way to use wandb and still run a parallelized study with Optuna.

Note that both wandb server and the client run on the same machine, just in different Docker containers. Thus, _real_ network issues should not be the issue.

```python
import wandb
import optuna
import numpy as np


def objective(trial: optuna.Trial) -> float:
    config = dict(trial.params)
    config["trial.number"] = trial.number

    wandb.init(
        project="my_project",
        group="wandb_mwe",
        config=config,
        reinit=True,
        # settings=wandb.Settings(start_method="fork"),  # does not make a difference
        # settings=wandb.Settings(start_method="thread"),  # does not make a difference
    )

    score = np.random.random(1)

    wandb.run.summary["final score"] = score
    wandb.run.summary["state"] = "completed"
    wandb.finish(quiet=True)

    return score


wandb.login(
    key="",
    host="http://my.local.net:8000",
    # host="http://wandb-docker-container:8000",  # not a valid url
    relogin=True,
)

study = optuna.create_study(study_name="my_study", direction="maximize")
study.optimize(objective, n_trials=5, n_jobs=2)

```

```shell
$ /opt/conda/bin/python /workspaces/my_project/src/wandb_errors_mwe.py
wandb: Appending key for my.local.net to your netrc file: /home/vscode/.netrc
[I 2022-08-18 11:27:58,400] A new study created in memory with name: my_study
/opt/conda/lib/python3.9/site-packages/optuna/study/study.py:393: FutureWarning: `n_jobs` argument has been deprecated in v2.7.0. This feature will be removed in v4.0.0. See https://github.com/optuna/optuna/releases/tag/v2.7.0.
  warnings.warn(
wandb: Currently logged in as: username. Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.13.1
wandb: Run data is saved locally in /workspaces/my_project/src/wandb/run-20220818_112758-r6nbia7o
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run spring-cloud-23
wandb: ⭐️ View project at http://my.local.net:8080/username/my_project
wandb: 🚀 View run at http://my.local.net:8080/username/my_project/runs/r6nbia7o
wandb: Waiting for W&B process to finish... (success).
wandb:                                                                                
wandb: Synced spring-cloud-23: http://my.local.net:8080/username/my_project/runs/r6nbia7o
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 1 other file(s)
[I 2022-08-18 11:28:10,043] Trial 0 finished with value: 0.07086374553871444 and parameters: {}. Best is trial 0 with value: 0.07086374553871444.
wandb: Tracking run with wandb version 0.13.1
wandb: Run data is saved locally in /workspaces/my_project/src/wandb/run-20220818_112810-132mjr0f
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run kind-microwave-24
wandb: ⭐️ View project at http://my.local.net:8080/username/my_project
wandb: 🚀 View run at http://my.local.net:8080/username/my_project/runs/132mjr0f
wandb: Waiting for W&B process to finish... (success).
wandb:                                                                                
wandb: Synced kind-microwave-24: http://my.local.net:8080/username/my_project/runs/132mjr0f
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 1 other file(s)
[I 2022-08-18 11:28:23,610] Trial 2 finished with value: 0.42732459058893624 and parameters: {}. Best is trial 2 with value: 0.42732459058893624.
Problem at: /workspaces/my_project/src/wandb_errors_mwe.py 10 objective
wandb: ERROR Error communicating with wandb process
wandb: ERROR For more info see: https://docs.wandb.ai/library/init#init-start-error
[W 2022-08-18 11:28:28,455] Trial 1 failed because of the following error: UsageError('Error communicating with wandb process\nFor more info see: https://docs.wandb.ai/library/init#init-start-error')
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/optuna/study/_optimize.py", line 213, in _run_trial
    value_or_values = func(trial)
  File "/workspaces/my_project/src/wandb_errors_mwe.py", line 10, in objective
    wandb.init(
  File "/opt/conda/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1043, in init
    run = wi.init()
  File "/opt/conda/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 691, in init
    raise UsageError(error_message)
wandb.errors.UsageError: Error communicating with wandb process
For more info see: https://docs.wandb.ai/library/init#init-start-error
wandb: Tracking run with wandb version 0.13.1
wandb: Run data is saved locally in /workspaces/my_project/src/wandb/run-20220818_112823-2h3zkj2i
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run serene-frost-25
wandb: ⭐️ View project at http://my.local.net:8080/username/my_project
wandb: 🚀 View run at http://my.local.net:8080/username/my_project/runs/2h3zkj2i
wandb: Waiting for W&B process to finish... (success).
wandb:                                                                                
wandb: Synced serene-frost-25: http://my.local.net:8080/username/my_project/runs/2h3zkj2i
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 1 other file(s)
[I 2022-08-18 11:28:36,211] Trial 3 finished with value: 0.5581329015664727 and parameters: {}. Best is trial 3 with value: 0.5581329015664727.
Traceback (most recent call last):
  File "/workspaces/my_project/src/wandb_errors_mwe.py", line 38, in <module>
    study.optimize(objective, n_trials=5, n_jobs=2)
  File "/opt/conda/lib/python3.9/site-packages/optuna/study/study.py", line 400, in optimize
    _optimize(
  File "/opt/conda/lib/python3.9/site-packages/optuna/study/_optimize.py", line 106, in _optimize
    f.result()
  File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/opt/conda/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/lib/python3.9/site-packages/optuna/study/_optimize.py", line 163, in _optimize_sequential
    trial = _run_trial(study, func, catch)
  File "/opt/conda/lib/python3.9/site-packages/optuna/study/_optimize.py", line 264, in _run_trial
    raise func_err
  File "/opt/conda/lib/python3.9/site-packages/optuna/study/_optimize.py", line 213, in _run_trial
    value_or_values = func(trial)
  File "/workspaces/my_project/src/wandb_errors_mwe.py", line 10, in objective
    wandb.init(
  File "/opt/conda/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1043, in init
    run = wi.init()
  File "/opt/conda/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 691, in init
    raise UsageError(error_message)
wandb.errors.UsageError: Error communicating with wandb process
For more info see: https://docs.wandb.ai/library/init#init-start-error
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb:                                                                                
wandb: Synced 2 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20220818_112758-2b67cjb2/logs
```

### Additional Files

[wandb.zip](https://github.com/wandb/wandb/files/9373074/wandb.zip)

### Environment

WandB version: 0.13.1

OS: Linux (running in VSCode dev container)

Python version: 3.9.6

Versions of relevant libraries: optuna: 2.10.1

### Additional Context

I have based my MWE on this post: https://medium.com/optuna/optuna-meets-weights-and-biases-58fc6bab893

**Comment by thanos-wandb** [comment]
Hi @mimxrt thank you for reporting this. Can you please try again with the following `wandb.init` call?
wandb.init(
        project="my_project",
        group="wandb_mwe",
        config=config,
        # reinit=True,
        settings=wandb.Settings(start_method="fork")
    )

**Comment by mimxrt** [comment]
Hi @thanos-wandb , thanks for your reply. Unfortunately, the error is still happening:

```shell
$ /opt/conda/bin/python /workspaces/my_project/src/wandb_errors_mwe.py
wandb: Appending key for my.local.net to your netrc file: /home/vscode/.netrc
[I 2022-08-23 06:16:18,272] A new study created in memory with name: my_study
/opt/conda/lib/python3.9/site-packages/optuna/study/study.py:393: FutureWarning: `n_jobs` argument has been deprecated in v2.7.0. This feature will be removed in v4.0.0. See https://github.com/optuna/optuna/releases/tag/v2.7.0.
  warnings.warn(
wandb: Currently logged in as: username. Use `wandb login --relogin` to force relogin
wandb: wandb version 0.13.2 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.13.1
wandb: Run data is saved locally in /workspaces/my_project/wandb/run-20220823_061618-1zi936fl
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run misty-sun-12
wandb: ⭐️ View project at http://my.local.net:8080/username/my_project
wandb: 🚀 View run at http://my.local.net:8080/username/my_project/runs/1zi936fl
wandb: Waiting for W&B process to finish... (success).
wandb:                                                                                
wandb: Synced misty-sun-12: http://my.local.net:8080/username/my_project/runs/1zi936fl
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 1 other file(s)
[I 2022-08-23 06:16:28,200] Trial 1 finished with value: 0.6672494185254773 and parameters: {}. Best is trial 1 with value: 0.6672494185254773.
wandb: wandb version 0.13.2 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.13.1
wandb: Run data is saved locally in /workspaces/my_project/wandb/run-20220823_061628-34mzwxp6
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run stilted-forest-14
wandb: ⭐️ View project at http://my.local.net:8080/username/my_project
wandb: 🚀 View run at http://my.local.net:8080/username/my_project/runs/34mzwxp6
wandb: Waiting for W&B process to finish... (success).
wandb:                                                                                
wandb: Synced stilted-forest-14: http://my.local.net:8080/username/my_project/runs/34mzwxp6
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 1 other file(s)
[I 2022-08-23 06:16:38,965] Trial 2 finished with value: 0.4047631218167227 and parameters: {}. Best is trial 1 with value: 0.6672494185254773.
wandb: wandb version 0.13.2 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.13.1
wandb: Run data is saved locally in /workspaces/my_project/wandb/run-20220823_061638-3fn59zcf
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run dashing-silence-15
wandb: ⭐️ View project at http://my.local.net:8080/username/my_project
wandb: 🚀 View run at http://my.local.net:8080/username/my_project/runs/3fn59zcf
wandb: Waiting for W&B process to finish... (success).
Problem at: /workspaces/my_project/src/wandb_errors_mwe.py 10 objective
wandb: ERROR Error communicating with wandb process
[W 2022-08-23 06:16:48,381] Trial 0 failed because of the following error: UsageError('Error communicating with wandb process')
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/optuna/study/_optimize.py", line 213, in _run_trial
    value_or_values = func(trial)
  File "/workspaces/my_project/src/wandb_errors_mwe.py", line 10, in objective
    wandb.init(
  File "/opt/conda/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1043, in init
    run = wi.init()
  File "/opt/conda/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 691, in init
    raise UsageError(error_message)
wandb.errors.UsageError: Error communicating with wandb process
wandb:                                                                                
wandb: Synced dashing-silence-15: http://my.local.net:8080/username/my_project/runs/3fn59zcf
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 1 other file(s)
[I 2022-08-23 06:16:49,623] Trial 3 finished with value: 0.15721237756900364 and parameters: {}. Best is trial 1 with value: 0.6672494185254773.
Traceback (most recent call last):
  File "/workspaces/my_project/src/wandb_errors_mwe.py", line 38, in <module>
    study.optimize(objective, n_trials=5, n_jobs=2)
  File "/opt/conda/lib/python3.9/site-packages/optuna/study/study.py", line 400, in optimize
    _optimize(
  File "/opt/conda/lib/python3.9/site-packages/optuna/study/_optimize.py", line 106, in _optimize
    f.result()
  File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/opt/conda/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/lib/python3.9/site-packages/optuna/study/_optimize.py", line 163, in _optimize_sequential
    trial = _run_trial(study, func, catch)
  File "/opt/conda/lib/python3.9/site-packages/optuna/study/_optimize.py", line 264, in _run_trial
    raise func_err
  File "/opt/conda/lib/python3.9/site-packages/optuna/study/_optimize.py", line 213, in _run_trial
    value_or_values = func(trial)
  File "/workspaces/my_project/src/wandb_errors_mwe.py", line 10, in objective
    wandb.init(
  File "/opt/conda/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1043, in init
    run = wi.init()
  File "/opt/conda/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 691, in init
    raise UsageError(error_message)
wandb.errors.UsageError: Error communicating with wandb process
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb:                                                                                
wandb: Synced 2 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20220823_061618-1a6d89ly/logs
```

wandb folder: [wandb2.zip](https://github.com/wandb/wandb/files/9399857/wandb2.zip)

**Comment by thanos-wandb** [comment]
Hi @mimxrt thank you for attaching the wandb folder, we will try to reproduce this error and get back to you soon with more information.

**Comment by MBakirWB** [comment]
Hi @mimxrt, I was unable to pinpoint the specific cause of this issue. From the debug logs, although you encountered `error: Error communicating with wandb process`, the trials that ran to competition were synced successfully. From the trace back 2 of the 4 trials succeeded (Trials 1 and 2). Have you attempted to setup your work via [process-level parallelization](https://optuna.readthedocs.io/en/stable/tutorial/10_key_features/004_distributed.html#sphx-glr-tutorial-10-key-features-004-distributed-py) to see if this results in a different outcome?

**Comment by mimxrt** [comment]
Thanks for following up on this @MBakirWB!

I will try and see how it goes but still: Based on the MWE posted above, the trials *should* not fail at all, right? The objective function just takes a random value and returns it as score - nothing that could cause the trial to fail. Also, when not running in parallel, the trials work 100% of the time (setting `n_jobs = None`). My guess would be that wandb is somehow confused by the parallel sync from different trials?

When running wandb in a Docker container, does this work for you?

My Compose file:
```yml
services:
  wandb:
    image: wandb/local:0.17.0
    restart: unless-stopped
    runtime: nvidia
    shm_size: "2gb"
    ports:
      - "8080:8080"
    environment:
      - HOST=http://my.local.net:8080
      - LICENSE=<replace-with-license>
    volumes:
      - wandb:/vol

volumes:
  wandb:

```

**Comment by mimxrt** [comment]
I think that Optuna is aware of this: 

> To ensure correct trial order in Weights & Biases, this callback should only be used with study.optimize(n_jobs=1).
> -- [Source](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.integration.WeightsAndBiasesCallback.html)

So I have been using it wrong. Unfortunately this makes Optuna a lot less useful...

**Comment by MBakirWB** [comment]
Thank you for the update @mimxrt.
