### ISSUE TITLE
[CLI]: Error in local controller demo

### ISSUE THREAD

**Issue by geyao1995** [wandb/wandb#4149]
### Describe the bug

I follow the official demo [Run a local controller inside Python](https://docs.wandb.ai/guides/sweeps/advanced-sweeps/local-controller#run-a-local-controller-inside-python) with two steps:
1.  create the sweep:

```shell
(pytorch) geyao@geyaodeMacBook-Air wandb_test % wandb sweep sweep_config.yaml
wandb: Creating sweep from: sweep_config.yaml
wandb: Created sweep with ID: yybw4spr
wandb: View sweep at: https://wandb.ai/geyao/my-mnist-test-project/sweeps/yybw4spr
wandb: Run sweep agent with: wandb agent geyao/my-mnist-test-project/yybw4spr
```
2. run the python code:
```python
import wandb
import time

sweep = wandb.controller('yybw4spr')
while not sweep.done():
    sweep.print_status()
    sweep.step()
    time.sleep(5)
```
I set the `sweep_id` to `yybw4spr` and `geyao/my-mnist-test-project/yybw4spr`. However, both fails and the error is:
```shell
400 response executing GraphQL.
{"errors":[{"message":"name required for project query","path":["project"]}],"data":{"project":null}}
wandb: ERROR Error while calling W&B API: name required for project query (<Response [400]>)
Traceback (most recent call last):
  File "/Users/geyao/miniconda3/envs/pytorch/lib/python3.10/site-packages/wandb/apis/normalize.py", line 25, in wrapper
    return func(*args, **kwargs)
  File "/Users/geyao/miniconda3/envs/pytorch/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 688, in sweep
    response = self.gql(
  File "/Users/geyao/miniconda3/envs/pytorch/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 113, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/geyao/miniconda3/envs/pytorch/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 204, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/Users/geyao/miniconda3/envs/pytorch/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/geyao/miniconda3/envs/pytorch/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/geyao/miniconda3/envs/pytorch/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/Users/geyao/miniconda3/envs/pytorch/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/geyao/PycharmProjects/wandb_demo/sweep_controller.py", line 4, in <module>
    sweep = wandb.controller(r'yybw4spr')
  File "/Users/geyao/miniconda3/envs/pytorch/lib/python3.10/site-packages/wandb/sdk/wandb_sweep.py", line 141, in controller
    c = _WandbController(
  File "/Users/geyao/miniconda3/envs/pytorch/lib/python3.10/site-packages/wandb/wandb_controller.py", line 217, in __init__
    sweep_obj = self._sweep_object_read_from_backend()
  File "/Users/geyao/miniconda3/envs/pytorch/lib/python3.10/site-packages/wandb/wandb_controller.py", line 438, in _sweep_object_read_from_backend
    sweep_obj = self._api.sweep(self._sweep_id, specs)
  File "/Users/geyao/miniconda3/envs/pytorch/lib/python3.10/site-packages/wandb/apis/internal.py", line 99, in sweep
    return self.api.sweep(*args, **kwargs)
  File "/Users/geyao/miniconda3/envs/pytorch/lib/python3.10/site-packages/wandb/apis/normalize.py", line 27, in wrapper
    raise CommError(err.response, err)
wandb.errors.CommError: <Response [400]>
```

My `sweep_config.yaml` is:
```yaml
program: train_mnist.py
method: grid
parameters:
  lr_schedule:
    values: [ step, cyclic ]
  epoch_total:
    values: [ 2, 4 ]
metric:
  goal: maximize
  name: test-result/accuracy
project: my-mnist-test-project
name: MNIST-Sweep-Test
description: test sweep demo
```

### Environment

WandB version: 0.13.1 

OS: MacOS 12.5

Python version: 3.10

Versions of relevant libraries:

**Comment by MBakirWB** [comment]
Hi @geyao1995 , thank-you for writing in. We will attempt to reproduce and get back to you soon.

**Comment by MBakirWB** [comment]
Hi @geyao1995 , in your python script define your `entity` and `project` in `wandb.controller`, `wandb.controller(entity="<entity>", project="<project>", sweep_id_or_config="<sweep-id>")

**Comment by geyao1995** [comment]
Thanks! Sorry for missing these two parameters.
