### ISSUE TITLE
[CLI]: Wandb causes training to error - Dropped streaming file chunk

### ISSUE THREAD

**Issue by samholt** [wandb/wandb#4163]
### Describe the bug

After training for several hours, capturing allot of data points wandb errors

```python

import wandb
wandb.init(project="continous de rl", entity="samholt")
wandb.config.update({'learning_rate': 1e-3})

total_epochs = 10000000000

# Create model
model = get_model()

wandb.config.update({"model_dyn_parameters": scalar_count_of_model_parameters})

# Training loop
for epoch_i in range(total_epochs):
  wandb.log({"loss": track_loss, "epoch": epoch_i})
  wandb.watch(model)

```

The above model has about 18,000 - 250,000 parameters depending on the experiment. All experiments face the following issue of wandb erroring after training for a few hours (3 or so).

```shell
07:50:48,303 root INFO [epoch=0402|iter=0501] train_loss=0.04047        | s/it=0.11040
wandb: ERROR Dropped streaming file chunk (see wandb/debug-internal.log)
Traceback (most recent call last):
  File "/home/sam/code/continous_control/continousderl/worldmodel_nl.py", line 223, in <module>
    logger.info(get_NL_worldmodel(retrain=True))
  File "/home/sam/code/continous_control/continousderl/worldmodel_nl.py", line 166, in get_NL_worldmodel
    loss_dyn_.backward()
  File "/home/sam/anaconda3/envs/cderl/lib/python3.9/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/sam/anaconda3/envs/cderl/lib/python3.9/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/sam/anaconda3/envs/cderl/lib/python3.9/site-packages/wandb/wandb_torch.py", line 264, in <lambda>
    handle = var.register_hook(lambda grad: _callback(grad, log_track))
  File "/home/sam/anaconda3/envs/cderl/lib/python3.9/site-packages/wandb/wandb_torch.py", line 262, in _callback
    self.log_tensor_stats(grad.data, name)
  File "/home/sam/anaconda3/envs/cderl/lib/python3.9/site-packages/wandb/wandb_torch.py", line 238, in log_tensor_stats
    wandb.run._log(
  File "/home/sam/anaconda3/envs/cderl/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1375, in _log
    self._partial_history_callback(data, step, commit)
  File "/home/sam/anaconda3/envs/cderl/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1259, in _partial_history_callback
    self._backend.interface.publish_partial_history(
  File "/home/sam/anaconda3/envs/cderl/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 553, in publish_partial_history
    self._publish_partial_history(partial_history)
  File "/home/sam/anaconda3/envs/cderl/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 67, in _publish_partial_history
    self._publish(rec)
  File "/home/sam/anaconda3/envs/cderl/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/sam/anaconda3/envs/cderl/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_record_publish
    self.send_server_request(server_req)
  File "/home/sam/anaconda3/envs/cderl/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 84, in send_server_request
    self._send_message(msg)
  File "/home/sam/anaconda3/envs/cderl/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 81, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/sam/anaconda3/envs/cderl/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 61, in _sendall_with_error_handle 
    sent = self._sock.send(data[total_sent:])
ConnectionResetError: [Errno 104] Connection reset by peer
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/sam/anaconda3/envs/cderl/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 81, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/sam/anaconda3/envs/cderl/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 61, in _sendall_with_error_handle 
    sent = self._sock.send(data[total_sent:])
BrokenPipeError: [Errno 32] Broken pipe
```

### Additional Files

debug-internal.log shows

```
2022-08-23 07:50:51,832 DEBUG   HandlerThread:462244 [handler.py:handle_request():141] handle_request: partial_history
2022-08-23 07:50:51,833 DEBUG   HandlerThread:462244 [handler.py:handle_request():141] handle_request: partial_history
2022-08-23 07:50:51,834 DEBUG   HandlerThread:462244 [handler.py:handle_request():141] handle_request: partial_history
2022-08-23 07:50:52,180 DEBUG   SenderThread:462244 [sender.py:send():302] send: history
2022-08-23 07:50:53,904 INFO    Thread-12 :462244 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/sam/code/continous_control/continousderl/wandb/run-20220823_040512-26dgjkcf/files/output.log
2022-08-23 07:50:55,665 DEBUG   SenderThread:462244 [sender.py:send():302] send: summary
2022-08-23 07:50:55,804 DEBUG   HandlerThread:462244 [handler.py:handle_request():141] handle_request: partial_history
2022-08-23 07:50:55,923 DEBUG   HandlerThread:462244 [handler.py:handle_request():141] handle_request: partial_history
```

### Environment

WandB version: '0.13.1'

OS: Distributor ID: Linuxmint
Description:    Linux Mint 20.3
Release:        20.3
Codename:       una

Python version: Python 3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0] :: Anaconda, Inc. on linux

Versions of relevant libraries: 

### Additional Context

Please do let me know how I can solve this problem, as if wandb causes training runs to crash, then this makes it unusable.

Thank you so much for helping and your time.

Best,
Sam

**Comment by ramit-wandb** [comment]
Hi @samholt!

That does not seem to be the whole `debug-internal.log`, would it be possible for you to share the complete log for me to have a look through once? Also wanted to know if you are doing something special / unique with multiprocessing. 

I'll help investigate this and get a solution going for you.

Thanks,
Ramit

**Comment by samholt** [comment]
> I'll help investigate this and get a solution going for you.

I tried to upload it, however it was too large to be supported by github - let me share a google drive link with it

**Comment by samholt** [comment]
Here is the link to it https://drive.google.com/file/d/1TGcPuJnJ6wGjop0VCvh7gANH9NzDtDvF/view?usp=sharing

Please do let me know how I can prevent erroring.

I am not doing anything special, only training the model and using it as the original guidelines,

Thank you so much,

Best,
Sam

**Comment by samholt** [comment]
I wonder whether wandb collects too much training losses, and then errors ?

**Comment by samholt** [comment]
Sadly I am still getting this error, looking at the original error, I presume wandb creates a seperate process or thread to process model gradient tensor stats. It seems after a while this thread for whatever reason stops running, and is killed, therefore when pytorch goes to do a backward pass, and send the gradient tensor stats to across to the other process it receives a broken pipe error, causing an error stopping all training.

Is there any way to handle this error to overcome it ? It seems to be tied into the model, I will continue hunting for a solution ASAP, as this is stopping production workflows,

Thank you so much for your time,

Keen to hear your response and any possible workarounds or fixes, @ramit-wandb !

Best,
Sam

**Comment by ramit-wandb** [comment]
Hi @samholt!

Apologies about the delay here - I talked to some folks and looks like this is coming due to an unstable internet connection. You can try one of the following things:
- [Resuming a Run](https://docs.wandb.ai/guides/track/advanced/resuming)
- [Setting the run mode to offline and sync them later](https://docs.wandb.ai/guides/technical-faq/troubleshooting#what-happens-if-internet-connection-is-lost-while-im-training-a-model)

Please let me know if these help resolve this issue!
Thanks,
Ramit

**Comment by samholt** [comment]
Dear @ramit-wandb,

I fixed it by not logging so much data all the time, by removing the line `wandb.watch(model)`.

Thank you so much for the help as well,

I love weights and biases and consistently using it for all my work !

Keep up the great work,

Best,
Sam
