### ISSUE TITLE
[Better Error] In `_launch_server` and `_inform_used_ports` when `_wait_for_ports` timeout

### ISSUE THREAD

**Issue by YouJiacheng** [wandb/wandb#4224]
My Python is slow when import packages(e.g. via network), it can easily exceed the 30 seconds timeout in `_wait_for_ports` since the server setup is slow.
Then I got following errors:
```
Traceback (most recent call last):
  File "/home/youjiacheng/miniconda3/envs/nvml/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1040, in init
    wi.setup(kwargs)
  File "/home/youjiacheng/miniconda3/envs/nvml/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 151, in setup
    self._wl = wandb_setup.setup()
  File "/home/youjiacheng/miniconda3/envs/nvml/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 320, in setup
    ret = _setup(settings=settings)
  File "/home/youjiacheng/miniconda3/envs/nvml/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 315, in _setup
    wl = _WandbSetup(settings=settings)
  File "/home/youjiacheng/miniconda3/envs/nvml/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 301, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/home/youjiacheng/miniconda3/envs/nvml/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 114, in __init__
    self._setup()
  File "/home/youjiacheng/miniconda3/envs/nvml/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 242, in _setup
    self._setup_manager()
  File "/home/youjiacheng/miniconda3/envs/nvml/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 273, in _setup_manager
    self._manager = wandb_manager._Manager(
  File "/home/youjiacheng/miniconda3/envs/nvml/lib/python3.10/site-packages/wandb/sdk/wandb_manager.py", line 106, in __init__
    self._service.start()
  File "/home/youjiacheng/miniconda3/envs/nvml/lib/python3.10/site-packages/wandb/sdk/service/service.py", line 106, in start
    self._launch_server()
  File "/home/youjiacheng/miniconda3/envs/nvml/lib/python3.10/site-packages/wandb/sdk/service/service.py", line 102, in _launch_server
    assert ports_found
AssertionError
wandb: ERROR Abnormal program exit
Traceback (most recent call last):
  File "/home/youjiacheng/miniconda3/envs/nvml/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1040, in init
    wi.setup(kwargs)
  File "/home/youjiacheng/miniconda3/envs/nvml/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 151, in setup
    self._wl = wandb_setup.setup()
  File "/home/youjiacheng/miniconda3/envs/nvml/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 320, in setup
    ret = _setup(settings=settings)
  File "/home/youjiacheng/miniconda3/envs/nvml/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 315, in _setup
    wl = _WandbSetup(settings=settings)
  File "/home/youjiacheng/miniconda3/envs/nvml/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 301, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/home/youjiacheng/miniconda3/envs/nvml/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 114, in __init__
    self._setup()
  File "/home/youjiacheng/miniconda3/envs/nvml/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 242, in _setup
    self._setup_manager()
  File "/home/youjiacheng/miniconda3/envs/nvml/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 273, in _setup_manager
    self._manager = wandb_manager._Manager(
  File "/home/youjiacheng/miniconda3/envs/nvml/lib/python3.10/site-packages/wandb/sdk/wandb_manager.py", line 106, in __init__
    self._service.start()
  File "/home/youjiacheng/miniconda3/envs/nvml/lib/python3.10/site-packages/wandb/sdk/service/service.py", line 106, in start
    self._launch_server()
  File "/home/youjiacheng/miniconda3/envs/nvml/lib/python3.10/site-packages/wandb/sdk/service/service.py", line 102, in _launch_server
    assert ports_found
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/youjiacheng/***/main.py", line 9, in <module>
    wandb.init(
  File "/home/youjiacheng/miniconda3/envs/nvml/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1081, in init
    raise Exception("problem") from error_seen
Exception: problem
(nvml) [youjiacheng@node** ***]$ Traceback (most recent call last):
  File "/home/youjiacheng/miniconda3/envs/nvml/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/youjiacheng/miniconda3/envs/nvml/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/youjiacheng/miniconda3/envs/nvml/lib/python3.10/site-packages/wandb/__main__.py", line 3, in <module>
    cli.cli(prog_name="python -m wandb")
  File "/home/youjiacheng/miniconda3/envs/nvml/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/youjiacheng/miniconda3/envs/nvml/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/youjiacheng/miniconda3/envs/nvml/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/youjiacheng/miniconda3/envs/nvml/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/youjiacheng/miniconda3/envs/nvml/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/youjiacheng/miniconda3/envs/nvml/lib/python3.10/site-packages/wandb/cli/cli.py", line 97, in wrapper
    return func(*args, **kwargs)
  File "/home/youjiacheng/miniconda3/envs/nvml/lib/python3.10/site-packages/wandb/cli/cli.py", line 286, in service
    server.serve()
  File "/home/youjiacheng/miniconda3/envs/nvml/lib/python3.10/site-packages/wandb/sdk/service/server.py", line 128, in serve
    self._inform_used_ports(grpc_port=grpc_port, sock_port=sock_port)
  File "/home/youjiacheng/miniconda3/envs/nvml/lib/python3.10/site-packages/wandb/sdk/service/server.py", line 65, in _inform_used_ports
    pf.write(self._port_fname)
  File "/home/youjiacheng/miniconda3/envs/nvml/lib/python3.10/site-packages/wandb/sdk/service/port_file.py", line 25, in write
    f = tempfile.NamedTemporaryFile(prefix=bname, dir=dname, mode="w", delete=False)
  File "/home/youjiacheng/miniconda3/envs/nvml/lib/python3.10/tempfile.py", line 553, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/home/youjiacheng/miniconda3/envs/nvml/lib/python3.10/tempfile.py", line 256, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpiwslzrk2/port-184742.txt5v2falw3'
```
These error messages made me think that it is tempfile creation problem, and causes `ports_found=False`.
However, ultimately, it turns out that the timeout in `_wait_for_ports` is the root cause:
https://github.com/wandb/wandb/blob/a00561721429dbff3092c5f99fa4f559d9b24049/wandb/sdk/service/service.py#L81-L109
The true procedure is:
1. `tmpdir` created, context entered
2. server launched
3. slow server setup causes timeout, `_wait_for_ports` return False
4. `assert ports_found` fails
5. context exited, tmpdir removed
6. server attempt to create a NamedTemporaryFile in removed `tmpdir`, raise FileNotFoundError

I hope there could be some improvements with error messages, it would be better if the setup can be more robust: Actually we can use `close_fds=False` to create tmpfile at client side and share it with subprocess server via fd. And we can just raise a warning and retry when timeout, instead of that raise assertion error and exit.
BTW, the server process doesn't exit when error.

**Comment by kptkin** [comment]
Hi @YouJiacheng, thanks for the detailed description. We are looking into improving the robustness of this feature. Fixes are planned for the next release. I will update this issue as soon as fixes are available!

**Comment by LucHayward** [comment]
I too am having this problem on the HPC at my university.

The issue seems solvable by only initiating one wandb process at a time (ie wait for one process to finish initiating before starting the next).

**Comment by YouJiacheng** [comment]
Alternatively, you can modify the source code of wandb to make the timeout longer.

**Comment by kptkin** [comment]
Hi all!

Thanks for reporting this issue. We are actively working on resolving it and would like to ask for your help.

If you could upgrade to the e latest version of wandb (as writing this message it would be 0.13.9) that would really helpful.
Also we introduce new environment variable (WANDB__SERVICE_WAIT) this will allow you increase the startup time from the command line instead of reaching and modifying the installed code. To use it just do the following:
```WANDB__SERVICE_WAIT=300 python your_script.py``
Another thing we added a debug flag that will print the timing information during startup to the tdout (if you have a way to collect stdout and share with us that would further help us narrow down the issue). You can do that as follows:
_WANDB_STARTUP_DEBUG=true python your_script.py
Sorry that you are experiencing issue and hopefully we could resolve them soon.

**Comment by Anri-Lombard** [comment]
> I too am having this problem on the HPC at my university.
> 
> The issue seems solvable by only initiating one wandb process at a time (ie wait for one process to finish initiating before starting the next).

Funny seeing you here; I'm having the problem with our HPC as well 😂
