### ISSUE TITLE
[Q] Remote jobs don't resume after network error

### ISSUE THREAD

**Issue by jameschapman19** [wandb/wandb#4242]
All my remote jobs have an error like:
`wandb: Network error resolved after 0:01:31.558040, resuming normal operation.`
And then they don't actually resume :( any idea what I can do?

**Comment by jameschapman19** [comment]
1.7.3

**Comment by jameschapman19** [comment]
Looks similar to #4143

**Comment by jameschapman19** [comment]
From debug-internal
`Traceback (most recent call last):
  File "/share/apps/python-3.9.5-shared/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/share/apps/python-3.9.5-shared/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/share/apps/python-3.9.5-shared/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/share/apps/python-3.9.5-shared/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/share/apps/python-3.9.5-shared/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/share/apps/python-3.9.5-shared/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/share/apps/python-3.9.5-shared/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/share/apps/python-3.9.5-shared/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/share/apps/python-3.9.5-shared/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/share/apps/python-3.9.5-shared/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/share/apps/python-3.9.5-shared/lib/python3.9/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/share/apps/python-3.9.5-shared/lib/python3.9/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/share/apps/python-3.9.5-shared/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/share/apps/python-3.9.5-shared/lib/python3.9/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/share/apps/python-3.9.5-shared/lib/python3.9/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/share/apps/python-3.9.5-shared/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/share/apps/python-3.9.5-shared/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 127, in execute
    return self.client.execute(*args, **kwargs)
  File "/share/apps/python-3.9.5-shared/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/share/apps/python-3.9.5-shared/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/share/apps/python-3.9.5-shared/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/share/apps/python-3.9.5-shared/lib/python3.9/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/share/apps/python-3.9.5-shared/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/share/apps/python-3.9.5-shared/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/share/apps/python-3.9.5-shared/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/share/apps/python-3.9.5-shared/lib/python3.9/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)`

**Comment by jameschapman19** [comment]
Hi - I've worked this out and will close but explain for anyone who stumbles on a similar error using a compute cluster. Basically the tqdm printouts themselves were filling my allowed storage so the initial network error and the apparent non resumption were really storage errors. The fix is to set progressbar=False when using machines which aren't able to use the normal tqdm printout trick and instead print every. single. line. XD

**Comment by jameschapman19** [comment]
(perhaps there might be a way to catch this kind of error from the wandb end though)
