### ISSUE TITLE
[CLI]: Error thrown trying to create wandb.Image with bounding boxes

### ISSUE THREAD

**Issue by grantdelozier** [wandb/wandb#4265]
### Describe the bug

I want to save an image to my experiment log that has bounding boxes with captions, but I'm getting a key/value error internal to the library. On reading the source, it seems like there are different conflicting data structures defining how bounding boxes need to be defined.

I am attempting to follow the comments left in BoundingBoxes2D class https://github.com/wandb/wandb/blob/7ed1dcdb92e6991842a975beff06e1bfc9e0a1ce/wandb/sdk/data_types/helper_types/bounding_boxes_2d.py#L17

as well as the data structure outlined in this article: https://docs.wandb.ai/ref/python/data-types/boundingboxes2d#log-bounding-boxes-for-a-single-image

```python
import wandb
import numpy as np

class_labels = {1: 'actual', 2: 'mask'}

boxes = {
    'predictions': {
        'box_data': [
            {'position': {'minX': 0.252, 'maxX': 0.33, 'minY': 0.016, 'maxY': 0.028}, 'class_id': 1, 'box_caption': 'C'}, 
            {'position': {'minX': 0.34, 'maxX': 0.39, 'minY': 0.018, 'maxY': 0.028}, 'class_id': 1, 'box_caption': 'L'}, 
            {'position': {'minX': 0.398, 'maxX': 0.506, 'minY': 0.016, 'maxY': 0.03}, 'class_id': 1, 'box_caption': 'S'}, 
            {'position': {'minX': 0.398, 'maxX': 0.506, 'minY': 0.016, 'maxY': 0.03}, 'class_id': 1, 'box_caption': ']'}, 
            {'position': {'minX': 0.398, 'maxX': 0.506, 'minY': 0.016, 'maxY': 0.03}, 'class_id': 1, 'box_caption': ' '}, 
            {'position': {'minX': 0.516, 'maxX': 0.548, 'minY': 0.018, 'maxY': 0.028}, 'class_id': 1, 'box_caption': 'd'}, 
            {'position': {'minX': 0.556, 'maxX': 0.634, 'minY': 0.016, 'maxY': 0.028}, 'class_id': 1, 'box_caption': 'o'}, 
            {'position': {'minX': 0.642, 'maxX': 0.76, 'minY': 0.016, 'maxY': 0.03}, 'class_id': 1, 'box_caption': 'c'}, 
            {'position': {'minX': 0.642, 'maxX': 0.76, 'minY': 0.016, 'maxY': 0.03}, 'class_id': 1, 'box_caption': 'u'}, 
            {'position': {'minX': 0.642, 'maxX': 0.76, 'minY': 0.016, 'maxY': 0.03}, 'class_id': 1, 'box_caption': 'm'}, 
            {'position': {'minX': 0.642, 'maxX': 0.76, 'minY': 0.016, 'maxY': 0.03}, 'class_id': 1, 'box_caption': 'e'}, 
            {'position': {'minX': 0.642, 'maxX': 0.76, 'minY': 0.016, 'maxY': 0.03}, 'class_id': 1, 'box_caption': 'n'}, 
            {'position': {'minX': 0.642, 'maxX': 0.76, 'minY': 0.016, 'maxY': 0.03}, 'class_id': 1, 'box_caption': 't'}, 
            {'position': {'minX': 0.642, 'maxX': 0.76, 'minY': 0.016, 'maxY': 0.03}, 'class_id': 1, 'box_caption': ' '}, 
            {'position': {'minX': 0.642, 'maxX': 0.76, 'minY': 0.016, 'maxY': 0.03}, 'class_id': 1, 'box_caption': 'l'}, 
            {'position': {'minX': 0.114, 'maxX': 0.154, 'minY': 0.044, 'maxY': 0.058}, 'class_id': 1, 'box_caption': 'e'}, 
            {'position': {'minX': 0.114, 'maxX': 0.154, 'minY': 0.044, 'maxY': 0.058}, 'class_id': 1, 'box_caption': 'v'}, 
            {'position': {'minX': 0.162, 'maxX': 0.192, 'minY': 0.044, 'maxY': 0.056}, 'class_id': 1, 'box_caption': 'e'}, 
            {'position': {'minX': 0.162, 'maxX': 0.192, 'minY': 0.044, 'maxY': 0.056}, 'class_id': 1, 'box_caption': 'l'}, 
            {'position': {'minX': 0.202, 'maxX': 0.252, 'minY': 0.044, 'maxY': 0.056}, 'class_id': 1, 'box_caption': ' '}, 
            {'position': {'minX': 0.202, 'maxX': 0.252, 'minY': 0.044, 'maxY': 0.056}, 'class_id': 1, 'box_caption': 'a'}, 
            {'position': {'minX': 0.202, 'maxX': 0.252, 'minY': 0.044, 'maxY': 0.056}, 'class_id': 1, 'box_caption': 'n'}, 
            {'position': {'minX': 0.202, 'maxX': 0.252, 'minY': 0.044, 'maxY': 0.056}, 'class_id': 1, 'box_caption': 'n'}, 
            {'position': {'minX': 0.262, 'maxX': 0.31, 'minY': 0.044, 'maxY': 0.056}, 'class_id': 1, 'box_caption': 'o'}, 
            {'position': {'minX': 0.262, 'maxX': 0.31, 'minY': 0.044, 'maxY': 0.056}, 'class_id': 1, 'box_caption': 't'}, 
            {'position': {'minX': 0.262, 'maxX': 0.31, 'minY': 0.044, 'maxY': 0.056}, 'class_id': 1, 'box_caption': 'a'}, 
            {'position': {'minX': 0.262, 'maxX': 0.31, 'minY': 0.044, 'maxY': 0.056}, 'class_id': 1, 'box_caption': 't'}, 
            {'position': {'minX': 0.32, 'maxX': 0.34, 'minY': 0.046, 'maxY': 0.056}, 'class_id': 1, 'box_caption': 'i'}, 
            {'position': {'minX': 0.348, 'maxX': 0.38, 'minY': 0.044, 'maxY': 0.056}, 'class_id': 1, 'box_caption': 'o'}, 
            {'position': {'minX': 0.348, 'maxX': 0.38, 'minY': 0.044, 'maxY': 0.056}, 'class_id': 1, 'box_caption': 'n'}
        ]
    },
    "class_labels": class_labels
}


image_tensor = np.random.randint(low=0, high=256, size=(512, 512, 1))

wandb.Image(image_tensor, boxes=boxes, mode='L')
```

```shell
Traceback (most recent call last):
  File "test_wandb_image.py", line 47, in <module>
    wandb.Image(image_tensor, boxes=boxes, mode='L')#, classes=class_labels)
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/data_types/image.py", line 155, in __init__
    self._set_initialization_meta(grouping, caption, classes, boxes, masks)
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/data_types/image.py", line 183, in _set_initialization_meta
    boxes_final[key] = BoundingBoxes2D(box_item, key)
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/data_types/helper_types/bounding_boxes_2d.py", line 214, in __init__
    super().__init__(val)
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/data_types/base_types/json_metadata.py", line 30, in __init__
    self.validate(val)
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/data_types/helper_types/bounding_boxes_2d.py", line 262, in validate
    boxes = val["box_data"]
KeyError: 'box_data'

```

### Environment

WandB version: '0.13.3'

OS: Ubuntu 20.04.5 LTS 

Python version:  3.7.13

Versions of relevant libraries:

**Comment by thanos-wandb** [comment]
Hi @grantdelozier thank you for reporting this. Could you please replace the last 4 lines of your boxes dictionary with the following ones and let me know if that would work for you?

```
        ],
    "class_labels": class_labels
    }
}
```

**Comment by grantdelozier** [comment]
Thanks! that worked. I guess I misread the format of that dictionary
