### ISSUE TITLE
[CLI]: JSON serialization error in wandb logging

### ISSUE THREAD

**Issue by nahidalam** [wandb/wandb#4287]
### Describe the bug

When I try to log using wandb I get error

```
Traceback (most recent call last):
  File "main.py", line 121, in <module>
    main()
  File "main.py", line 117, in main
    wandb.log({'train_loss': json.dumps(train_loss), 'validation_loss': json.dumps(valid_loss)})
  File "/home/ec2-user/anaconda3/envs/clip_env/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/home/ec2-user/anaconda3/envs/clip_env/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/ec2-user/anaconda3/envs/clip_env/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/ec2-user/anaconda3/envs/clip_env/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type AvgMeter is not JSON serializable
```

```
for epoch in range(CFG.epochs):
        print(f"Epoch: {epoch + 1}")
        model.train()
        train_loss = train_epoch(model, train_loader, optimizer, lr_scheduler, step)
        model.eval()
        with torch.no_grad():
            valid_loss = valid_epoch(model, valid_loader)
        
        if valid_loss.avg < best_loss:
            best_loss = valid_loss.avg
            torch.save(model.state_dict(), "best_mvit.pt")
            print("Saved Best Model!")
        wandb.log({'train_loss': train_loss, 'validation_loss': valid_loss})
```

### Environment

WandB version: 0.13.2

OS: Amazon linux which is centos rhel fedora

Python version: 3.8

Versions of relevant libraries:

**Comment by nahidalam** [comment]
resolved

**Comment by mariosconsta** [comment]
> Resolved

How?

**Comment by mantralbs** [comment]
I want to know how you resoveled this problem?
