### ISSUE TITLE
[CLI]: Opaque "The wandb backend process has shutdown" after several hours

### ISSUE THREAD

**Issue by vedantroy** [wandb/wandb#4306]
### Describe the bug

I can't provide a reproduction because it happens intermittently after several hours of training.

Here's the stack-trace:

```
contrastive_train-contrastive_train-1  |                           Exception in thread NetStatThr:
contrastive_train-contrastive_train-1  | Traceback (most recent call last):
contrastive_train-contrastive_train-1  |   File "/root/micromamba/envs/video-rec/lib/python3.8/threading.py", line 932, in _bootstrap_inner
contrastive_train-contrastive_train-1  |     self.run()
contrastive_train-contrastive_train-1  |   File "/root/micromamba/envs/video-rec/lib/python3.8/threading.py", line 870, in run
contrastive_train-contrastive_train-1  |     self._target(*self._args, **self._kwargs)
contrastive_train-contrastive_train-1  |   File "/root/micromamba/envs/video-rec/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 152, in check_network_status
contrastive_train-contrastive_train-1  |     status_response = self._interface.communicate_network_status()
contrastive_train-contrastive_train-1  |   File "/root/micromamba/envs/video-rec/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 138, in communicate_network_status
contrastive_train-contrastive_train-1  |     resp = self._communicate_network_status(status)
contrastive_train-contrastive_train-1  |   File "/root/micromamba/envs/video-rec/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 405, in _communicate_network_status
contrastive_train-contrastive_train-1  |     resp = self._communicate(req, local=True)
contrastive_train-contrastive_train-1  |   File "/root/micromamba/envs/video-rec/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 226, in _communicate
contrastive_train-contrastive_train-1  |     return self._communicate_async(rec, local=local).get(timeout=timeout)
contrastive_train-contrastive_train-1  |   File "/root/micromamba/envs/video-rec/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 231, in _communicate_async
contrastive_train-contrastive_train-1  |     raise Exception("The wandb backend process has shutdown")
contrastive_train-contrastive_train-1  | Exception: The wandb backend process has shutdown
contrastive_train-contrastive_train-1  | Exception in thread ChkStopThr:
contrastive_train-contrastive_train-1  | Traceback (most recent call last):
contrastive_train-contrastive_train-1  |   File "/root/micromamba/envs/video-rec/lib/python3.8/threading.py", line 932, in _bootstrap_inner
contrastive_train-contrastive_train-1  |     self.run()
contrastive_train-contrastive_train-1  |   File "/root/micromamba/envs/video-rec/lib/python3.8/threading.py", line 870, in run
contrastive_train-contrastive_train-1  |     self._target(*self._args, **self._kwargs)
contrastive_train-contrastive_train-1  |   File "/root/micromamba/envs/video-rec/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 170, in check_status
contrastive_train-contrastive_train-1  |     status_response = self._interface.communicate_stop_status()
contrastive_train-contrastive_train-1  |   File "/root/micromamba/envs/video-rec/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 127, in communicate_stop_status
contrastive_train-contrastive_train-1  |     resp = self._communicate_stop_status(status)
contrastive_train-contrastive_train-1  |   File "/root/micromamba/envs/video-rec/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 395, in _communicate_stop_status
contrastive_train-contrastive_train-1  |     resp = self._communicate(req, local=True)
contrastive_train-contrastive_train-1  |   File "/root/micromamba/envs/video-rec/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 226, in _communicate
contrastive_train-contrastive_train-1  |     return self._communicate_async(rec, local=local).get(timeout=timeout)
contrastive_train-contrastive_train-1  |   File "/root/micromamba/envs/video-rec/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 231, in _communicate_async
contrastive_train-contrastive_train-1  |     raise Exception("The wandb backend process has shutdown")
contrastive_train-contrastive_train-1  | Exception: The wandb backend process has shutdown
```

### Environment

```
Collecting environment information...
PyTorch version: 1.12.0+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A
OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31
Python version: 3.8.13 (default, Mar 28 2022, 11:38:47)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-4.15.0-193-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.6.124
GPU models and configuration: 
GPU 0: NVIDIA A100-PCIE-40GB
GPU 1: NVIDIA A100-PCIE-40GB

Nvidia driver version: 515.65.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True
Versions of relevant libraries:
[pip3] numpy==1.22.4
[pip3] pytorch-ranger==0.1.1
[pip3] torch==1.12.0+cu116
[pip3] torch-optimizer==0.1.0
[pip3] torchdata==0.4.0
[pip3] torchmetrics==0.7.3
[pip3] torchvision==0.13.1a0+bddbd7e
[conda] Could not collect
Pillow/Pillow-SIMD version: 7.0.0.post3
Postfix means using pillow-simd
```

My requirements.txt:

```
attrs==22.1.0
av==9.2.0
pyarrow==9.0.0
boto3==1.24.60
botocore==1.27.60
certifi==2022.5.18.1
charset-normalizer==2.1.0
click==8.1.3
coolname==1.1.0
docker-pycreds==0.4.0
docstring-parser==0.14.1
einops==0.4.1
einops-exts==0.0.3
fsspec==2022.7.1
gitdb==4.0.9
GitPython==3.1.27
idna==3.3
importlib-metadata==4.12.0
importlib-resources==5.9.0
jmespath==1.0.1
jsonschema==4.7.2
lmdb==1.3.0
mosaicml==0.9.0
numpy==1.22.4
packaging==21.3
pathtools==0.1.2
# We will install pillow-simd instead
# Pillow==9.2.0
portalocker==2.5.1
promise==2.3
protobuf==3.20.1
psutil==5.9.1
py-cpuinfo==8.0.0
pyDeprecate==0.3.2
pyparsing==3.0.9
pyrsistent==0.18.1
python-dateutil==2.8.2
pytimeparse==1.1.8
pytorch-ranger==0.1.1
PyYAML==6.0
repackage==0.7.3
requests==2.28.1
remote_pdb==2.1.0
ruamel.yaml==0.17.21
ruamel.yaml.clib==0.2.6
# crashes too much
# scalene==1.5.11
s3transfer==0.6.0
sentry-sdk==1.9.5
setproctitle==1.3.2
shortuuid==1.0.9
six==1.16.0
smmap==5.0.0
tabulate==0.8.9
transformers==4.21.2
timm==0.6.7
torch==1.12.0+cu116
torch-optimizer==0.1.0
torchdata==0.4.0
torchmetrics==0.7.3
# Need to install this manually
# torchvision==0.13.1a0+bddbd7e
tqdm==4.64.0
typer==0.6.1
typing_extensions==4.3.0
urllib3==1.26.11
wandb==0.12.21
yahp==0.1.3
zipp==3.8.1

pytest==7.1.3
```

**Comment by nate-wandb** [comment]
Hi @vedantroy, could you try requiring the latest wandb version which is `0.13.3`? In versions > `0.13.0` we introduced a new method of handling the backend processes which increases the reliability and may solve this for you.

Thank you,
Nate

**Comment by vedantroy** [comment]
> Hi @vedantroy, could you try requiring the latest wandb version which is `0.13.3`? In versions > `0.13.0` we introduced a new method of handling the backend processes which increases the reliability and may solve this for you.
> 
> Thank you, Nate

Will try, and let you know the results.
