### ISSUE TITLE
[Feature]: Overwrite nested default config in sweep

### ISSUE THREAD

**Issue by dschaub95** [wandb/wandb#4345]
### Description

I would love a better handling of nested configs during sweeping. Specifically, I would like to be able to provide a default config in `wandb.init(config=defaults)` whose parameters are only update by the sweep config.
This is an example sweep configuration (in Jupyter):
`sweep_configuration = {
    'method': 'bayes',
    'metric': {
        'goal': 'minimize', 
        'name': 'valid/best_loss'
    },
    'parameters': {
        'model': {
            'parameters': {
                'cgnn': {
                    'parameters': {
                        'train': {
                            'parameters': {
                                'batch_s': {'values': [4, 8, 16]},
                                'lr': {'max': 0.1, 'min': 0.0001}
                            }
                        },
                        'model': {
                            'parameters': {
                                'num_layers': {'values': [2, 4, 6]},
                                'head_num': {'values': [4, 8, 16]},
                                'embed_dim': {'values': [64, 128]},
                                'ff_hidden_dim': {'values': [256, 512]},
                                'softmax': {'values': [True, False]},
                                'extra_out': {'values': [True, False]},
                            }
                        }
                    }
                }
            }
        }
    }
}`
If there is a better way to define a nested sweep config let me know. A solution could massively reduce overhead when setting up a sweep config.

### Suggested Solution

When providing a nested default config in `wandb.init(config=defaults)` the config provided by the sweep should preserve the original nested structure of the default config when adding/overwriting values. 
For the above sweep configuration, this would mean the `wandb.config` would also contain additional training parameters like weight decay etc.
I think a solution should just do a recursive config merge.

**Comment by MBakirWB** [comment]
Thank you for writing in @dschaub95.  We have recent and in progress updates into how nested sweep configs are handled. I will review your input and provide feedback soon.

**Comment by maartenbuyl** [comment]
Any updates on this? It unfortunately makes nested sweep configs impractical to use.

**Comment by rapharomero** [comment]
Here is a minimal reproducible example: 
```
import wandb
print(wandb.__version__)
def main():
    default_config = {'model': {'dim': 2, 'lr': 0.1}}
    wandb.init(config=default_config, mode='disabled')
    print(wandb.config)
    wandb.finish()

print('Wandb context')
main()

print('Sweep Context')
sweep_config = {
    'method': 'grid',
    'parameters': {
        'model.dim': {
            'values': [8, 16]
        }
    }
}
sweep_id = wandb.sweep(sweep_config)
wandb.agent(sweep_id, function=main, count=1)
```
outputs: 

```
0.14.0
Wandb context
{'model': {'dim': 2, 'lr': 0.1}}
Sweep Context
Create sweep with ID: 2pt4a8no
Sweep URL: https://wandb.ai/rapharomero/uncategorized/sweeps/2pt4a8no
wandb: Agent Starting Run: n9il6acn with config:
wandb:  model.dim: 8
{'model.dim': 8, 'model': {'dim': 2, 'lr': 0.1}}
```

Instead we would expect the sweep output to be ``` {'model': {'dim': 8, 'lr': 0.1}}} ``` i.e. the model.dim should get updated during the sweep.

**Comment by rapharomero** [comment]
A second MRE: Using the nested sweep config configuration, with wandb in `disabled` mode

```
import wandb

print(wandb.__version__)
default_config = {'model': {'dim': 2, 'lr': 0.1}}


def main():
    wandb.init(config=default_config, mode='disabled')
    print(wandb.config)
    wandb.finish()

print('Wandb context')
main()

print('Sweep Context')

sweep_config = {
    'method': 'grid',
    'parameters': {
        'model': {
            'parameters': {
                'dim': {
                    'values': [2, 8, 16]
                }
            }
        }
    }
}

sweep_id = wandb.sweep(sweep_config)
wandb.agent(sweep_id, function=main, count=1)
```

outputs the following error 

```
0.14.0
Wandb context
{'model': {'dim': 2, 'lr': 0.1}}
Sweep Context
Create sweep with ID: fexck74s
Sweep URL: https://wandb.ai/rapharomero/uncategorized/sweeps/fexck74s
wandb: Agent Starting Run: zdg3kzf2 with config:
wandb:  model: {'dim': 2}
Traceback (most recent call last):
  File "/home/raphael/anaconda3/envs/pylab/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1144, in init
    run = wi.init()
  File "/home/raphael/anaconda3/envs/pylab/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 556, in init
    return self._make_run_disabled()
  File "/home/raphael/anaconda3/envs/pylab/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 513, in _make_run_disabled
    drun.config.update(self.config)
  File "/home/raphael/anaconda3/envs/pylab/lib/python3.8/site-packages/wandb/sdk/wandb_config.py", line 185, in update
    sanitized = self._update(d, allow_val_change)
  File "/home/raphael/anaconda3/envs/pylab/lib/python3.8/site-packages/wandb/sdk/wandb_config.py", line 178, in _update
    sanitized = self._sanitize_dict(
  File "/home/raphael/anaconda3/envs/pylab/lib/python3.8/site-packages/wandb/sdk/wandb_config.py", line 238, in _sanitize_dict
    k, v = self._sanitize(k, v, allow_val_change)
  File "/home/raphael/anaconda3/envs/pylab/lib/python3.8/site-packages/wandb/sdk/wandb_config.py", line 262, in _sanitize
    raise config_util.ConfigError(
wandb.sdk.lib.config_util.ConfigError: Attempted to change value of key "model" from {'dim': 2} to {'dim': 2, 'lr': 0.1}
If you really want to do this, pass allow_val_change=True to config.update()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/raphael/anaconda3/envs/pylab/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1152, in init
    getcaller()
  File "/home/raphael/anaconda3/envs/pylab/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 838, in getcaller
    src, line, func, stack = logger.findCaller(stack_info=True)
AttributeError: '_EarlyLogger' object has no attribute 'findCaller'
wandb: ERROR Abnormal program exit
Run zdg3kzf2 errored: Exception('problem')
wandb: ERROR Run zdg3kzf2 errored: Exception('problem')
```

**Comment by rapharomero** [comment]
However, if I run the same code as before with wandb mode = 'offline',i.e. 

```
import wandb

print(wandb.__version__)
default_config = {'model': {'dim': 2, 'lr': 0.1}}


def main():
    wandb.init(config=default_config, mode='offline')
    print(wandb.config)
    wandb.finish()

print('Wandb context')
main()

print('Sweep Context')

sweep_config = {
    'method': 'grid',
    'parameters': {
        'model': {
            'parameters': {
                'dim': {
                    'values': [8, 16]
                }
            }
        }
    }
}
sweep_id = wandb.sweep(sweep_config)
wandb.agent(sweep_id, function=main, count=1)
```

I get

```
0.14.0
Wandb context
wandb: Tracking run with wandb version 0.14.0
wandb: W&B syncing is set to `offline` in this directory.  
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
{'model': {'dim': 2, 'lr': 0.1}}
wandb: Waiting for W&B process to finish... (success).
wandb: You can sync this run to the cloud by running:
wandb: wandb sync /home/raphael/Work/aida_ugent/latent_trajectory-private/code/wandb/offline-run-20230403_163408-tv1q7fyx
wandb: Find logs at: ./wandb/offline-run-20230403_163408-tv1q7fyx/logs
Sweep Context
Create sweep with ID: lvqiwynh
Sweep URL: https://wandb.ai/rapharomero/uncategorized/sweeps/lvqiwynh
wandb: Agent Starting Run: iir10yjz with config:
wandb:  model: {'dim': 8}
wandb: Tracking run with wandb version 0.14.0
wandb: W&B syncing is set to `offline` in this directory.  
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
{'model': {'dim': 2}}
wandb: Waiting for W&B process to finish... (success).
wandb: You can sync this run to the cloud by running:
wandb: wandb sync /home/raphael/Work/aida_ugent/latent_trajectory-private/code/wandb/offline-run-20230403_163419-iir10yjz
wandb: Find logs at: ./wandb/offline-run-20230403_163419-iir10yjz/logs
```
However we would expect the printed  output during the sweep to be {'model': {'dim': 8, 'lr': 0.1}}
Instead it seems that during the sweep run, the default configs get erased and replaced by the configs specified in the sweep config.

**Comment by rapharomero** [comment]
To summarize, it would be nice if both the 'dot-trick' syntax and the 'nested parameter' sweep config version would replace the relevant default config by their values specified by the sweep.

**Comment by pecey** [comment]
Just ran into the same issue where the default configs for nested parameter got erased and were replaced by the ones defined in the sweep config. Having the ability to just overwrite the specified keys would be immensely helpful (as well as intuitive). If not, it would be great if this is mentioned in the docs so users know what to expect.
