### ISSUE TITLE
[CLI]: IndexError: list index out of range when using MMDetWandbHook

### ISSUE THREAD

**Issue by Kittywyk** [wandb/wandb#4358]
### Describe the bug

I'm training a detector based on mmdetection, and I called MMDetWandbHook in config file following [this](https://wandb.ai/ayush-thakur/mmdetection/reports/How-to-Use-Weights-Biases-with-MMDetection--VmlldzoyMTM0MDE2) tutorial. 
When I run the train script through command:
```
python tools/train.py configs/retinanet/retinanet_r34_fpn_1x_coco.py
```
an error occurs:

```
IndexError: list index out of range
```

The full traceback show belows:
```
Traceback (most recent call last):
  File "tools/train.py", line 245, in <module>
    main()
  File "tools/train.py", line 234, in main
    train_detector(
  File "/NAS/HUST_WHU/Wangyuankun/Code/mmdetection/mmdet/apis/train.py", line 244, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/NAS/HUST_WHU/condav100/env/openmmlab/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 117, in run
    self.call_hook('before_run')
  File "/NAS/HUST_WHU/condav100/env/openmmlab/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 317, in call_hook
    getattr(hook, fn_name)(self)
  File "/NAS/HUST_WHU/condav100/env/openmmlab/lib/python3.8/site-packages/mmcv/runner/dist_utils.py", line 135, in wrapper
    return func(*args, **kwargs)
  File "/NAS/HUST_WHU/Wangyuankun/Code/mmdetection/mmdet/core/hook/wandblogger_hook.py", line 201, in before_run
    self._add_ground_truth(runner)
  File "/NAS/HUST_WHU/Wangyuankun/Code/mmdetection/mmdet/core/hook/wandblogger_hook.py", line 380, in _add_ground_truth
    wandb_masks = self._get_wandb_masks(
  File "/NAS/HUST_WHU/Wangyuankun/Code/mmdetection/mmdet/core/hook/wandblogger_hook.py", line 536, in _get_wandb_masks
    mask = polygon_to_bitmap(mask, height, width)
  File "/NAS/HUST_WHU/Wangyuankun/Code/mmdetection/mmdet/core/mask/structures.py", line 1069, in polygon_to_bitmap
    rles = maskUtils.frPyObjects(polygons, height, width)
  File "pycocotools/_mask.pyx", line 293, in pycocotools._mask.frPyObjects
IndexError: list index out of range
```

### Environment

WandB version: 0.13.4

OS: Linux

Python version: 3.8.13

Versions of relevant libraries:  
TorchVision: 0.9.1+cu101
OpenCV: 4.6.0
MMCV: 1.6.1
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: 11.3
MMDetection: 2.25.2+9d3e162

**Comment by ramit-wandb** [comment]
Hi @Kittywyk,

The root cause of this error does not seem to be coming from Weights and Biases, but `pycocotools._mask.frPyObjects`. I would recommend reaching out to the PyCOCOTools team to report this.

Thanks,
Ramit

**Comment by Kittywyk** [comment]
I see. Thank you!



Send from Kitty’s iPhone


------------------ Original ------------------
From: Ramit Goolry ***@***.***&gt;
Date: Fri,Oct 7,2022 1:48 AM
To: wandb/wandb ***@***.***&gt;
Cc: Kittywyk ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [wandb/wandb] [CLI]: IndexError: list index out of range whenusing MMDetWandbHook (Issue #4358)





 
Hi @Kittywyk,
 
The root cause of this error does not seem to be coming from Weights and Biases, but pycocotools._mask.frPyObjects. I would recommend reaching out to the PyCOCOTools team to report this.
 
Thanks,
 Ramit
