### ISSUE TITLE
[App]: 'You must call wandb.init() before wandb.log()' at the end of the training

### ISSUE THREAD

**Issue by ma-batita** [wandb/wandb#4364]
### Current Behavior

Hello, I am running on a strange behavior with wandb.
I have the massage "You must call wandb.init() before wandb.log()" but at the end of my training!
I am running my code on vertex Al (using a docker file) and I dont get any error or warning but at the end of the training (after the run summary of wandb) I got this : 

```
wandb: Synced test_CB_wandb: https://wandb.ai/bodyguard/huggingface/runs/m19hgjkq
2022-10-07 16:58:31.503 CEST

workerpool0-0
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
2022-10-07 16:58:31.503 CEST

workerpool0-0
wandb: Find logs at: ./wandb/run-20221007_145819-m19hgjkq/logs
2022-10-07 16:58:31.719 CEST

workerpool0-0
wandb: ERROR You must call wandb.init() before wandb.log()
2022-10-07 16:58:31.721 CEST

workerpool0-0
Traceback (most recent call last):
2022-10-07 16:58:31.721 CEST

workerpool0-0
 File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
2022-10-07 16:58:31.721 CEST

workerpool0-0
 "__main__", mod_spec)
2022-10-07 16:58:31.721 CEST

workerpool0-0
 File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
2022-10-07 16:58:31.721 CEST

workerpool0-0
 exec(code, run_globals)
2022-10-07 16:58:31.721 CEST

workerpool0-0
 File "/app/my_trainer/task.py", line 100, in <module>
2022-10-07 16:58:31.721 CEST

workerpool0-0
 main()
2022-10-07 16:58:31.721 CEST

workerpool0-0
 File "/app/my_trainer/task.py", line 96, in main
2022-10-07 16:58:31.721 CEST

workerpool0-0
 experiment.run(args)
2022-10-07 16:58:31.721 CEST

workerpool0-0
 File "/app/my_trainer/experiment.py", line 154, in run
2022-10-07 16:58:31.721 CEST

workerpool0-0
 metrics = trainer.evaluate(eval_dataset=val_dataset)
2022-10-07 16:58:31.721 CEST

workerpool0-0
 File "/opt/conda/lib/python3.7/site-packages/transformers/trainer.py", line 2807, in evaluate
2022-10-07 16:58:31.721 CEST

workerpool0-0
 self.log(output.metrics)
2022-10-07 16:58:31.721 CEST

workerpool0-0
 File "/opt/conda/lib/python3.7/site-packages/transformers/trainer.py", line 2401, in log
2022-10-07 16:58:31.721 CEST

workerpool0-0
 self.control = self.callback_handler.on_log(self.args, self.state, self.control, logs)
2022-10-07 16:58:31.721 CEST

workerpool0-0
 File "/opt/conda/lib/python3.7/site-packages/transformers/trainer_callback.py", line 390, in on_log
2022-10-07 16:58:31.721 CEST

workerpool0-0
 return self.call_event("on_log", args, state, control, logs=logs)
2022-10-07 16:58:31.721 CEST

workerpool0-0
 File "/opt/conda/lib/python3.7/site-packages/transformers/trainer_callback.py", line 407, in call_event
2022-10-07 16:58:31.721 CEST

workerpool0-0
 **kwargs,
2022-10-07 16:58:31.721 CEST

workerpool0-0
 File "/opt/conda/lib/python3.7/site-packages/transformers/integrations.py", line 731, in on_log
2022-10-07 16:58:31.721 CEST

workerpool0-0
 self._wandb.log({**logs, "train/global_step": state.global_step})
2022-10-07 16:58:31.721 CEST

workerpool0-0
 File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/lib/preinit.py", line 36, in preinit_wrapper
2022-10-07 16:58:31.721 CEST

workerpool0-0
 raise wandb.Error(f"You must call wandb.init() before {name}()")
2022-10-07 16:58:31.721 CEST

workerpool0-0
wandb.errors.Error: You must call wandb.init() before wandb.log()
2022-10-07 16:58:31.722 CEST

workerpool0-0
ERROR:root:Traceback (most recent call last):
2022-10-07 16:58:31.722 CEST

workerpool0-0
 File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
2022-10-07 16:58:31.722 CEST

workerpool0-0
 "__main__", mod_spec)
2022-10-07 16:58:31.722 CEST

workerpool0-0
 File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
2022-10-07 16:58:31.722 CEST

workerpool0-0
 exec(code, run_globals)
2022-10-07 16:58:31.722 CEST

workerpool0-0
 File "/app/my_trainer/task.py", line 100, in <module>
2022-10-07 16:58:31.722 CEST

workerpool0-0
 main()
2022-10-07 16:58:31.722 CEST

workerpool0-0
 File "/app/my_trainer/task.py", line 96, in main
2022-10-07 16:58:31.722 CEST

workerpool0-0
 experiment.run(args)
2022-10-07 16:58:31.722 CEST

workerpool0-0
 File "/app/my_trainer/experiment.py", line 154, in run
2022-10-07 16:58:31.722 CEST

workerpool0-0
 metrics = trainer.evaluate(eval_dataset=val_dataset)
2022-10-07 16:58:31.722 CEST

workerpool0-0
 File "/opt/conda/lib/python3.7/site-packages/transformers/trainer.py", line 2807, in evaluate
2022-10-07 16:58:31.722 CEST

workerpool0-0
 self.log(output.metrics)
2022-10-07 16:58:31.722 CEST

workerpool0-0
 File "/opt/conda/lib/python3.7/site-packages/transformers/trainer.py", line 2401, in log
2022-10-07 16:58:31.722 CEST

workerpool0-0
 self.control = self.callback_handler.on_log(self.args, self.state, self.control, logs)
2022-10-07 16:58:31.722 CEST

workerpool0-0
 File "/opt/conda/lib/python3.7/site-packages/transformers/trainer_callback.py", line 390, in on_log
2022-10-07 16:58:31.722 CEST

workerpool0-0
 return self.call_event("on_log", args, state, control, logs=logs)
2022-10-07 16:58:31.722 CEST

workerpool0-0
 File "/opt/conda/lib/python3.7/site-packages/transformers/trainer_callback.py", line 407, in call_event
2022-10-07 16:58:31.722 CEST

workerpool0-0
 **kwargs,
2022-10-07 16:58:31.722 CEST

workerpool0-0
 File "/opt/conda/lib/python3.7/site-packages/transformers/integrations.py", line 731, in on_log
2022-10-07 16:58:31.722 CEST

workerpool0-0
 self._wandb.log({**logs, "train/global_step": state.global_step})
2022-10-07 16:58:31.722 CEST

workerpool0-0
 File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/lib/preinit.py", line 36, in preinit_wrapper
2022-10-07 16:58:31.722 CEST

workerpool0-0
 raise wandb.Error(f"You must call wandb.init() before {name}()")
2022-10-07 16:58:31.722 CEST

workerpool0-0
wandb.errors.Error: You must call wandb.init() before wandb.log()
2022-10-07 16:58:31.722 CEST

workerpool0-0
NoneType: None
```

Knowing that on my training code I have the init, log and finish at the right places;
```
wandb.init(project="my_project")
wandb.login(key=my_key)

#...
trainer.train()
wandb.finish()

```

### Expected Behavior

The error message should be at the beginning of my  training or I shouldn't get it at all.

### Environment

OS:

Browsers:

Version:

**Comment by thanos-wandb** [comment]
Hi @ma-batita thank you for reporting this. May I please ask if you instantiate a run object when you're calling `wandb.init()`? because in that case you will need to use `run.log(...)` instead.

Also, can you please try the `wandb.login(key=my_key)` command first, and to specify your `entity` in the `wandb.init(entity='my_entity', project="my_project")` call. Is this a distributed training job on Vertex AI?

**Comment by ma-batita** [comment]
Hello @thanos-wandb,
thank you for your respond.

> May I please ask if you instantiate a run object when you're calling `wandb.init()`? because in that case you will need to use `run.log(...)` instead.

No, I did not instantiate any run. I just imported wandb, called wandb.init(),  and wandb.log().

>can you please try the `wandb.login(key=my_key)` command first, and to specify your entity in the `wandb.init(entity='my_entity', project="my_project")` call.

I also tried `wandb.login()` without the init but nothing changed. I even called wandb in the docker file ; 
```
# Run wandb
RUN wandb init -p "my_project" 
RUN wandb login 9c1************44c

# Copies the trainer code to the docker image.
# .....

RUN wandb finish
```

> Is this a distributed training job on Vertex AI?

Yes it is :)

**Comment by thanos-wandb** [comment]
Thank you @ma-batita for the additional information. Do you initiate and log experiments from a [single process or multiple](https://docs.wandb.ai/guides/track/advanced/distributed-training)? Can you please also try by creating a run object instead? You may also find useful [this Report](https://wandb.ai/wandb-smle/vertex-super-resolution/reports/Using-Vertex-AI-and-Weights-Biases-to-Enhance-Image-Resolution--VmlldzoyMzE5MjUw) about using Vertex AI and W&B.

**Comment by ma-batita** [comment]
Hello again and thank you for you help :) 

> Do you initiate and log experiments from a [single process or multiple](https://docs.wandb.ai/guides/track/advanced/distributed-training)?

Now I am testing just a sigle process (`replica_count=1` in the `job. run` of vertex) and I got the error. But the main goal is to run on multiple process / GPU.

> Can you please also try by creating a run object instead?

Do you mean encapsulate my training process in a with statemt `with wandb.init() as run`

> You may also find useful [this Report](https://wandb.ai/wandb-smle/vertex-super-resolution/reports/Using-Vertex-AI-and-Weights-Biases-to-Enhance-Image-Resolution--VmlldzoyMzE5MjUw) about using Vertex AI and W&B.

Thank you for the report. I already took a look at it and got some inspiration from it but it is running on PyTorch Lightning and I am working with pure PyTorch.

**Comment by thanos-wandb** [comment]
Hi @ma-batita glad to hear you enjoyed the report, we don't have any content yet for Vertex AI & PyTorch, but you can check some PyTorch in general reports [here](https://wandb.ai/fully-connected/blog/pytorch).

It would be recommended that we first solve this issue for a single process and we check thereafter if it works on multiple. Exactly, you can do this in one of the following two ways:

```
with wandb.init(entity='my_entity', project="my_project") as run:
    run.log(...)
```
    
```
run = wandb.init(entity='my_entity', project="my_project")
run.log(...)    
```

Please let me know if that still throws an error, and if so would it be possible to attach the `debug.log` and `debug-internal.log` files to debug further?

**Comment by ma-batita** [comment]
Hi @thanos-wandb,
Thank you for your big help.

>It would be recommended that we first solve this issue for a single process and we check thereafter if it works on multiple. Exactly, you can do this in one of the following two ways:
> ```
>with wandb.init(entity='my_entity', project="my_project") as run:
>      run.log(...)
>  ```
>  ```
>  run = wandb.init(entity='my_entity', project="my_project")
>  run.log(...)   
>  ``` 

I will do this change but I managed finally to fix the error `You must call wandb.init() before wandb.log()` by changing the `wandb.finish()` placement. It was just after the training process bit know it it at the end of the the code (after saving the model and check metrics.) I hoe this help who comes seeking for helm :) 

The problem now is vertex considering wandb logs as an errors. No matter what I do to change the log level, it is always considered as errors. This is [the log file](https://drive.google.com/file/d/1FgREna0TTjbnusnr22nM7_faj8AfDePZ/view?usp=sharing) from vertex. 
Thanks for your help :)

**Comment by thanos-wandb** [comment]
Hi @ma-batita sorry for the late response here. I am glad you fixed the previous issue, and thanks for posting the solution for future reference! 

Regarding the logs being considered as errors from Vertex AI, may I please ask if that cause your experiments to crash or do they log normally? Have you tried setting `os.environ["WANDB_SILENT"] = "true"` from your Python script or exporting this environment variable `WANDB_SILENT=true` to suppress all logs? Would this work for you?

**Comment by ma-batita** [comment]
Hello @thanos-wandb, 
No, it does not affect anything in the training process. everything logged normally. it is juste considered as error!
<img width="1042" alt="Screenshot 2022-10-28 at 4 40 14 PM" src="https://user-images.githubusercontent.com/90634663/198652712-ac8a998e-b19f-46a2-8a27-7b7e5f004da0.png">


The problem is that when I do `os.environ["WANDB_SILENT"] = "true"` it does not log anything!

**Comment by thanos-wandb** [comment]
Hi @ma-batita thanks a lot for confirming that everything works fine. It seems that W&B console logs are treated as `stderr` instead of `stdout` therefore they are flagged as errors by Vertex AI logger. Could you please try instead to set this `os.environ["WANDB_CONSOLE"] = "off"` environment variable?

**Comment by ma-batita** [comment]
Hello again @thanos-wandb,
I just tested my code with `os.environ["WANDB_CONSOLE"] = "off"` but nothing has changed!

**Comment by thanos-wandb** [comment]
Hi @ma-batita could you please confirm that everything works fine in terms of executing your code and logging to W&B? The remaining issue with the logs being treated as `errors` seems related to your [training logs](https://cloud.google.com/ai-platform/training/docs/troubleshooting#training_logs) in Google Cloud. Could you try to use `logging` python package to capture any logging events? Then you can set the desired log level doing something as `Logger.info(msg, *args, **kwargs)`, `Logger.warning(msg, *args, **kwargs)`,` Logger.critical(msg, *args, **kwargs)`. Would this work for you?

**Comment by thanos-wandb** [comment]
Hi @ma-batita I wanted to follow up on this request, did you try to use the `logging` package, and does the issue still occur for you?

**Comment by ma-batita** [comment]
HI @thanos-wandb,

> could you please confirm that everything works fine in terms of executing your code and logging to W&B?

Yes, everything works just fine without GCP (training and logging).

> Could you try to use logging python package to capture any logging events? Then you can set the desired log level doing something as `Logger.info(msg, *args, **kwargs)`, `Logger.warning(msg, *args, **kwargs)`, `Logger.critical(msg, *args, **kwargs)`.

Here is what I am using as a logger in my code :

```
import logging

def set_global_logging_level(level=logging.ERROR, prefices=[""]):
    prefix_re = re.compile(rf'^(?:{ "|".join(prefices) })')
    for name in logging.root.manager.loggerDict:
        if re.match(prefix_re, name):
            logging.getLogger(name).setLevel(level)

#....

if __name__ == "__main__":
    logging.disable(logging.INFO)
    set_global_logging_level(
        logging.ERROR, prefices=["transformers", "torch", "wandb", "tqdm"]
    )
    main()

```

> did you try to use the logging package, and does the issue still occur for you?

Yes :(

**Comment by thanos-wandb** [comment]
Hi @ma-batita thank you for sharing this, it seems that you're specifying `wandb` logs to be treated as errors messages. What would happen if you adjust your code to the following?

```
if __name__ == "__main__":
    logging.disable(logging.INFO)
    set_global_logging_level(
        logging.ERROR, prefices=["transformers", "torch", "tqdm"]
    )
    set_global_logging_level(
        logging.INFO, prefices=["wandb"]
    )
    main()
```

**Comment by ma-batita** [comment]
Hello @thanos-wandb, unfortunately this does not change anything :(

**Comment by thanos-wandb** [comment]
Hi @ma-batita sorry this is still happening, can you also try the following:
```
if __name__ == "__main__":
    set_global_logging_level(
        logging.INFO, prefices=["transformers", "wandb", "torch", "tqdm"]
    )
    main()
```
In case this doesn't solve it, would it be possible to share a minimal code example to reproduce this in Vertex AI on our side? thanks a lot.

**Comment by ma-batita** [comment]
hi @thanos-wandb, with `logging.INFO` everything is considered as error now!

**Comment by thanos-wandb** [comment]
Hi @ma-batita thank you for the script. For security reasons, can you please go to `https://wandb.ai/settings` and delete the current API key and generate a new one? I have downloaded the code, so you could also remove the attached file if you would like. I will get back to you once I review and reproduce this error.

**Comment by ma-batita** [comment]
Hi @thanos-wandb,

>can you please go to https://wandb.ai/settings and delete the current API key and generate a new one?

Done

>you could also remove the attached file

Done

>I will get back to you once I review and reproduce this error.

Thank you so much. I really appreciate your help!

**Comment by thanos-wandb** [comment]
Hi @ma-batita thanks for taking care of the above. Last thing to ask for now would be a small or demo version of your `test_data.csv`? I will then give it a go on Vertex AI, and try to reproduce the same issue and see what causes that. Thank you!

**Comment by ma-batita** [comment]
hi @thanos-wandb, here is a [shared file](https://drive.google.com/file/d/1Iaih7_u-fME8Ywf1MVGD91Y2-5cYbimD/view?usp=sharing) of the same test data that I used in my code.

**Comment by thanos-wandb** [comment]
Hi @ma-batita just an update on this, the code works fine with Google Colab, and also on Vertex AI with a user-managed notebook without throwing any errors. Therefore this logging issue seems related with the docker image that you're using to run on Vertex. Would it be possible to share the Dockerfile excluding any privacy data, so that I could also reproduce the same issue?

**Comment by ma-batita** [comment]
Hi @thanos-wandb, This is how my docker file looks like. I really appreciate your efforts. Thank you!

```
FROM us-docker.pkg.dev/vertex-ai/training/pytorch-gpu.1-11:latest

WORKDIR /app

RUN pip install google-cloud-storage transformers sentencepiece wandb accelerate toma deepspeed

COPY ./my_accelerate/__init__.py /app/my_accelerate/__init__.py
COPY ./my_accelerate/config_file.yaml /app/my_accelerate/config_file.yaml
COPY ./my_accelerate/script.py /app/my_accelerate/script.py


ENTRYPOINT ["python", "-m", "my_accelerate.script"]
```

**Comment by thanos-wandb** [comment]
Hi @ma-batita just checking in here to see if this issue is still ongoing for you, and if you're having your image in Artifacts Registry or Container Registry in GCP? Thank you!

**Comment by TaosLezz** [comment]
You can try:
import wandb
wandb.init(mode='disabled')
