### ISSUE TITLE
[CLI]: yolov5 artifacts uploading issue

### ISSUE THREAD

**Issue by hank9938** [wandb/wandb#4402]
### Describe the bug

I followed up the youtube tutorial https://www.youtube.com/watch?v=a9Bre0YJ8L8&t=878s,
and I was going to upload my own labeled dataset.
When I proceeded to the step of running the upload dataset command, it came up with an error below.
If there is any way I can deal with it?   

```cmd
E:\個人資料\Hank9938\專題yolo訓練資料\yolov5-master>python utils/loggers/wandb/log_dataset.py --project custom_yolov5 --data data/custom_dataset.yaml
```

```
Traceback (most recent call last):
  File "E:\個人資料\Hank9938\專題yolo訓練資料\yolov5-master\utils\loggers\wandb\log_dataset.py", line 27, in <module>
    create_dataset_artifact(opt)
  File "E:\個人資料\Hank9938\專題yolo訓練資料\yolov5-master\utils\loggers\wandb\log_dataset.py", line 11, in create_dataset_artifact
    logger = WandbLogger(opt, None, job_type='Dataset Creation')  # TODO: return value unused
  File "E:\個人資料\Hank9938\專題yolo訓練資料\yolov5-master\utils\loggers\wandb\wandb_utils.py", line 136, in __init__
    if opt.upload_dataset:
AttributeError: 'Namespace' object has no attribute 'upload_dataset'
```

### Additional Files

![image](https://user-images.githubusercontent.com/116379939/197261109-9046f4e8-f456-4f01-b668-6a9a16297603.png)

### Environment

WandB version:0.13.4

OS:windows

Python version:3.9

Versions of relevant libraries: pytorch1.12.1

**Comment by MBakirWB** [comment]
Hi @hank9938 , thank you for writing in with your question. I was able to replicate the issue on my end. It appears the `upload_dataset` flag was recently disabled, see [here](https://github.com/ultralytics/yolov5/commit/0860e58557f26a0136dd8afbc82f408f31d15ecd). I will need to dig into this further to determine why the change was made.

**Comment by hank9938** [comment]
Hello! I am wondering if the problem has been solved yet? 
Thank you for being patient with me.

**Comment by soumik12345** [comment]
Hi @hank9938 , we have temporarily disabled the `upload_dataset` flag due to it leading to a serialization error for the evaluation table to be stored as a Weights & BIases Artifact. We will re-enable the flag once we fix the bug.

**Comment by hank9938** [comment]
Thanks for your quick response. But is there any other way I can upload my dataset not by cmd and still get a yaml for tarining? Metting the deadline of my small project, I have to decide whether to switch to another training platform and give up wandb.

**Comment by parambharat** [comment]
Hi @hank9938, Thank you for your patience. We will look into this issue in the coming week and you can expect a fix in about 2 weeks time.
