### ISSUE TITLE
[CLI]: HTTP Error when trying to download artifact 

### ISSUE THREAD

**Issue by jlin99** [wandb/wandb#4431]
### Describe the bug

When attempting to load the model, HTTP 404 Not Found error is thrown. Double checked that API key is correct. It only fails when attempting to load the model.

```python
MODEL_ARTIFACT_NAME = "contenda/v2b_segment_regeneration/segment_regeneration_svr:v0"
api = wandb.Api(api_key=wandb_service_api)
artifact = api.artifact(MODEL_ARTIFACT_NAME)
path = artifact.get_path("model.pkl")
with open(path.download(), 'rb') as f:
    SVR_REGENERATION_CLASSIFIER = pickle.load(f)
```

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/egghead/man-o-repo/src/contenda/processing/regeneration/regeneration_classifier.py", line 20, in get_svr_regeneration_classifier_model
    with open(path.download(), 'rb') as f:
  File "/Users/egghead/opt/miniconda3/envs/contenda_core/lib/python3.9/site-packages/wandb/apis/public.py", line 3847, in download
    cache_path = manifest.storage_policy.load_file(
  File "/Users/egghead/opt/miniconda3/envs/contenda_core/lib/python3.9/site-packages/wandb/sdk/wandb_artifacts.py", line 909, in load_file
    response.raise_for_status()
  File "/Users/egghead/opt/miniconda3/envs/contenda_core/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/artifactsV2/default/contenda/QXJ0aWZhY3Q6MjU3Njg3MjQ4/4e9a882913a3e663b76fae5617af84fb
```

### Environment

WandB version: 0.13.2, 0.13.4

OS: mac

Python version: 3.9

Versions of relevant libraries:

**Comment by MBakirWB** [comment]
Hi @jlin99, I was able to successfully run your code and load the model. Could you try Set the `WANDB_API_KEY` environment variable to the API key and re-run your code.

**Comment by MBakirWB** [comment]
Thank you for the feedback @kjhenner, I will review our docs for any changes that need to happen.
