### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'message_types_by_name'[Q]

### ISSUE THREAD

**Issue by KnifeDing** [wandb/wandb#4442]
when I import wandb, get

AttributeError: 'NoneType' object has no attribute 'message_types_by_name'

how to solve it?

**Comment by verazuo** [comment]
I met the same error.
Not quite sure how this happened. But you can decrease the wandb package version to reuse it.
```
pip install wandb==0.13.3 --upgrade
```

**Comment by timvandam** [comment]
I have the same issue with 0.13.6 and 0.13.7. Running wandb locally works just fine, but when I try to run it on a slurm cluster I am met with this issue the moment I import wandb. As per @verazuo 0.13.3 indeed works

**Comment by DManowitz** [comment]
I am getting this error with wandb 0.13.5 running locally.  Here is the relevant stack trace:

    import wandb
  File "...\lib\site-packages\wandb\__init__.py", line 26, in <module>
    from wandb import sdk as wandb_sdk
  File "...\lib\site-packages\wandb\sdk\__init__.py", line 9, in <module>
    from .wandb_init import _attach, init  # noqa: F401
  File "...\lib\site-packages\wandb\sdk\wandb_init.py", line 30, in <module>
    from . import wandb_login, wandb_setup
  File "...\lib\site-packages\wandb\sdk\wandb_login.py", line 25, in <module>
    from .wandb_settings import Settings, Source
  File "...\lib\site-packages\wandb\sdk\wandb_settings.py", line 39, in <module>
    from wandb.sdk.wandb_setup import _EarlyLogger
  File "...\lib\site-packages\wandb\sdk\wandb_setup.py", line 22, in <module>
    from . import wandb_manager, wandb_settings
  File "...\lib\site-packages\wandb\sdk\wandb_manager.py", line 14, in <module>
    from wandb.sdk.lib.proto_util import settings_dict_from_pbmap
  File "...\lib\site-packages\wandb\sdk\lib\proto_util.py", line 6, in <module>
    from wandb.proto import wandb_internal_pb2 as pb
  File "...\lib\site-packages\wandb\proto\wandb_internal_pb2.py", line 6, in <module>
    from wandb.proto.v3.wandb_internal_pb2 import *
  File "...\lib\site-packages\wandb\proto\v3\wandb_internal_pb2.py", line 16, in <module>
    from wandb.proto import wandb_base_pb2 as wandb_dot_proto_dot_wandb__base__pb2
  File "...\lib\site-packages\wandb\proto\wandb_base_pb2.py", line 6, in <module>
    from wandb.proto.v3.wandb_base_pb2 import *
  File "...\lib\site-packages\wandb\proto\v3\wandb_base_pb2.py", line 21, in <module>
    __RECORDINFO = DESCRIPTOR.message_types_by_name['_RecordInfo']
AttributeError: 'NoneType' object has no attribute 'message_types_by_name'

**Comment by mariuaas** [comment]
I have the same issue

**Comment by DManowitz** [comment]
I have other packages which constrain protobuf to be < 3.20.

**Comment by kptkin** [comment]
@DManowitz a few points:
- Did you try using the latest version of wandb and if so, did the issue persist?
- I wasn't able to reproduce it locally, so if you could provide a reproduction script + details about your environment (os, python version etc) and list of python packages, it might help us debug this issue.

**Comment by JianhuanZhuo** [comment]
Any progress? The same issue

**Comment by raubitsj** [comment]
@JianhuanZhuo 
Can you let us know what version of protobuf you are using?
```
pip list | grep protobuf
```

**Comment by theTrueRiccardo** [comment]
Same problem. If I try to do:
`wandb login`
i get an error. Here the trace:
```
File "c:\users\riccardo\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\riccardo\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Riccardo\AppData\Local\Programs\Python\Python39\Scripts\wandb.exe\__main__.py", line 4, in <module>
  File "c:\users\riccardo\appdata\local\programs\python\python39\lib\site-packages\wandb\__init__.py", line 26, in <module>
    from wandb import sdk as wandb_sdk
  File "c:\users\riccardo\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\__init__.py", line 9, in <module>
    from .wandb_init import _attach, init  # noqa: F401
  File "c:\users\riccardo\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\wandb_init.py", line 30, in <module>
    from . import wandb_login, wandb_setup
  File "c:\users\riccardo\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\wandb_login.py", line 25, in <module>
    from .wandb_settings import Settings, Source
  File "c:\users\riccardo\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\wandb_settings.py", line 39, in <module>
    from wandb.sdk.wandb_setup import _EarlyLogger
  File "c:\users\riccardo\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\wandb_setup.py", line 22, in <module>
    from . import wandb_manager, wandb_settings
  File "c:\users\riccardo\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\wandb_manager.py", line 14, in <module>
    from wandb.sdk.lib.proto_util import settings_dict_from_pbmap
  File "c:\users\riccardo\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\lib\proto_util.py", line 6, in <module>
    from wandb.proto import wandb_internal_pb2 as pb
  File "c:\users\riccardo\appdata\local\programs\python\python39\lib\site-packages\wandb\proto\wandb_internal_pb2.py", line 6, in <module>
    from wandb.proto.v3.wandb_internal_pb2 import *
  File "c:\users\riccardo\appdata\local\programs\python\python39\lib\site-packages\wandb\proto\v3\wandb_internal_pb2.py", line 16, in <module>
    from wandb.proto import wandb_base_pb2 as wandb_dot_proto_dot_wandb__base__pb2
  File "c:\users\riccardo\appdata\local\programs\python\python39\lib\site-packages\wandb\proto\wandb_base_pb2.py", line 6, in <module>
    from wandb.proto.v3.wandb_base_pb2 import *
  File "c:\users\riccardo\appdata\local\programs\python\python39\lib\site-packages\wandb\proto\v3\wandb_base_pb2.py", line 21, in <module>
    __RECORDINFO = DESCRIPTOR.message_types_by_name['_RecordInfo']
AttributeError: 'NoneType' object has no attribute 'message_types_by_nam
```

I'm trying to login from windows, inside venv virtual environment. The problem persists also by changing protobuf version. I've tried 3.20, 3.21, latest, 3.19, 4.21.9

**Comment by Kartik-Neralwar** [comment]
> Could you check your protobuf version? it seems to work for version `3.20.1` or latest version of protobuf `4.21.9`

Using protobuf/3.20.1 gives an error with wandb.keras:

```
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

```

The packages (modules) that I use currently:

anaconda/3/2021.11
cuda/11.4
cudnn/8.2.4
tensorflow/gpu-cuda-11.4/2.8.0
keras/2.6.0
keras-preprocessing/1.1.2
protobuf/3.20.1
wandb /0.13.4 / 0.13.9/ 0.14.1 /0.14.2

Kartik

**Comment by V0XNIHILI** [comment]
Similar issue here:

```
Traceback (most recent call last):
  File "/space/env/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/space/envlib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/space/env/lib/python3.10/site-packages/wandb/sdk/internal/system/system_monitor.py", line 118, in _start
    asset.start()
  File "/space/env/lib/python3.10/site-packages/wandb/sdk/internal/system/assets/cpu.py", line 166, in start
    self.metrics_monitor.start()
  File "/space/env/lib/python3.10/site-packages/wandb/sdk/internal/system/assets/interfaces.py", line 168, in start
    logger.info(f"Started {self._process.name}")
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by sydholl** [comment]
WandB Internal User commented: 
verazuo commented: 
I met the same error.
Not quite sure how this happened. But you can decrease the wandb package version to reuse it.
```
pip install wandb==0.13.3 --upgrade
```

**Comment by sydholl** [comment]
WandB Internal User commented: 
timvandam commented: 
I have the same issue with 0.13.6 and 0.13.7. Running wandb locally works just fine, but when I try to run it on a slurm cluster I am met with this issue the moment I import wandb. As per @verazuo 0.13.3 indeed works

**Comment by sydholl** [comment]
WandB Internal User commented: 
DManowitz commented: 
I am getting this error with wandb 0.13.5 running locally.  Here is the relevant stack trace:

```
    import wandb
  File "...\lib\site-packages\wandb\__init__.py", line 26, in <module>
    from wandb import sdk as wandb_sdk
  File "...\lib\site-packages\wandb\sdk\__init__.py", line 9, in <module>
    from .wandb_init import _attach, init  # noqa: F401
  File "...\lib\site-packages\wandb\sdk\wandb_init.py", line 30, in <module>
    from . import wandb_login, wandb_setup
  File "...\lib\site-packages\wandb\sdk\wandb_login.py", line 25, in <module>
    from .wandb_settings import Settings, Source
  File "...\lib\site-packages\wandb\sdk\wandb_settings.py", line 39, in <module>
    from wandb.sdk.wandb_setup import _EarlyLogger
  File "...\lib\site-packages\wandb\sdk\wandb_setup.py", line 22, in <module>
    from . import wandb_manager, wandb_settings
  File "...\lib\site-packages\wandb\sdk\wandb_manager.py", line 14, in <module>
    from wandb.sdk.lib.proto_util import settings_dict_from_pbmap
  File "...\lib\site-packages\wandb\sdk\lib\proto_util.py", line 6, in <module>
    from wandb.proto import wandb_internal_pb2 as pb
  File "...\lib\site-packages\wandb\proto\wandb_internal_pb2.py", line 6, in <module>
    from wandb.proto.v3.wandb_internal_pb2 import *
  File "...\lib\site-packages\wandb\proto\v3\wandb_internal_pb2.py", line 16, in <module>
    from wandb.proto import wandb_base_pb2 as wandb_dot_proto_dot_wandb__base__pb2
  File "...\lib\site-packages\wandb\proto\wandb_base_pb2.py", line 6, in <module>
    from wandb.proto.v3.wandb_base_pb2 import *
  File "...\lib\site-packages\wandb\proto\v3\wandb_base_pb2.py", line 21, in <module>
    __RECORDINFO = DESCRIPTOR.message_types_by_name['_RecordInfo']
AttributeError: 'NoneType' object has no attribute 'message_types_by_name'
```

**Comment by sydholl** [comment]
WandB Internal User commented: 
mariuaas commented: 
I have the same issue

**Comment by sydholl** [comment]
WandB Internal User commented: 
kptkin commented: 
Could you check your protobuf version? it seems to work for version `3.20.1` or latest version of protobuf `4.21.9`

**Comment by sydholl** [comment]
WandB Internal User commented: 
DManowitz commented: 
I have other packages which constrain protobuf to be < 3.20.

**Comment by sydholl** [comment]
WandB Internal User commented: 
kptkin commented: 
@DManowitz a few points:
- Did you try using the latest version of wandb and if so, did the issue persist?
- I wasn't able to reproduce it locally, so if you could provide a reproduction script + details about your environment (os, python version etc) and list of python packages, it might help us debug this issue.

**Comment by sydholl** [comment]
WandB Internal User commented: 
JianhuanZhuo commented: 
Any progress? The same issue

**Comment by sydholl** [comment]
WandB Internal User commented: 
raubitsj commented: 
@JianhuanZhuo 
Can you let us know what version of protobuf you are using?
```
pip list | grep protobuf
```

**Comment by sydholl** [comment]
WandB Internal User commented: 
Kartik-Neralwar commented: 
> Could you check your protobuf version? it seems to work for version `3.20.1` or latest version of protobuf `4.21.9`

Using protobuf/3.20.1 gives an error with wandb.keras:

```
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

```

The packages (modules) that I use currently:

anaconda/3/2021.11
cuda/11.4
cudnn/8.2.4
tensorflow/gpu-cuda-11.4/2.8.0
keras/2.6.0
keras-preprocessing/1.1.2
protobuf/3.20.1
wandb /0.13.4 / 0.13.9/ 0.14.1 /0.14.2

Kartik

**Comment by sydholl** [comment]
WandB Internal User commented: 
theTrueRiccardo commented: 
Same problem. If I try to do:
`wandb login`
i get an error. Here the trace:
```
File "c:\users\riccardo\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\riccardo\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Riccardo\AppData\Local\Programs\Python\Python39\Scripts\wandb.exe\__main__.py", line 4, in <module>
  File "c:\users\riccardo\appdata\local\programs\python\python39\lib\site-packages\wandb\__init__.py", line 26, in <module>
    from wandb import sdk as wandb_sdk
  File "c:\users\riccardo\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\__init__.py", line 9, in <module>
    from .wandb_init import _attach, init  # noqa: F401
  File "c:\users\riccardo\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\wandb_init.py", line 30, in <module>
    from . import wandb_login, wandb_setup
  File "c:\users\riccardo\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\wandb_login.py", line 25, in <module>
    from .wandb_settings import Settings, Source
  File "c:\users\riccardo\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\wandb_settings.py", line 39, in <module>
    from wandb.sdk.wandb_setup import _EarlyLogger
  File "c:\users\riccardo\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\wandb_setup.py", line 22, in <module>
    from . import wandb_manager, wandb_settings
  File "c:\users\riccardo\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\wandb_manager.py", line 14, in <module>
    from wandb.sdk.lib.proto_util import settings_dict_from_pbmap
  File "c:\users\riccardo\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\lib\proto_util.py", line 6, in <module>
    from wandb.proto import wandb_internal_pb2 as pb
  File "c:\users\riccardo\appdata\local\programs\python\python39\lib\site-packages\wandb\proto\wandb_internal_pb2.py", line 6, in <module>
    from wandb.proto.v3.wandb_internal_pb2 import *
  File "c:\users\riccardo\appdata\local\programs\python\python39\lib\site-packages\wandb\proto\v3\wandb_internal_pb2.py", line 16, in <module>
    from wandb.proto import wandb_base_pb2 as wandb_dot_proto_dot_wandb__base__pb2
  File "c:\users\riccardo\appdata\local\programs\python\python39\lib\site-packages\wandb\proto\wandb_base_pb2.py", line 6, in <module>
    from wandb.proto.v3.wandb_base_pb2 import *
  File "c:\users\riccardo\appdata\local\programs\python\python39\lib\site-packages\wandb\proto\v3\wandb_base_pb2.py", line 21, in <module>
    __RECORDINFO = DESCRIPTOR.message_types_by_name['_RecordInfo']
AttributeError: 'NoneType' object has no attribute 'message_types_by_nam
```

I'm trying to login from windows, inside venv virtual environment. The problem persists also by changing protobuf version. I've tried 3.20, 3.21, latest, 3.19, 4.21.9

**Comment by sydholl** [comment]
WandB Internal User commented: 
V0XNIHILI commented: 
Similar issue here:

```
Traceback (most recent call last):
  File "/space/env/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/space/envlib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/space/env/lib/python3.10/site-packages/wandb/sdk/internal/system/system_monitor.py", line 118, in _start
    asset.start()
  File "/space/env/lib/python3.10/site-packages/wandb/sdk/internal/system/assets/cpu.py", line 166, in start
    self.metrics_monitor.start()
  File "/space/env/lib/python3.10/site-packages/wandb/sdk/internal/system/assets/interfaces.py", line 168, in start
    logger.info(f"Started {self._process.name}")
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by sydholl** [comment]
WandB Internal User commented: 
DManowitz commented: 
I am getting this error with wandb 0.13.5 running locally.  Here is the relevant stack trace:

```
    import wandb
  File "...\lib\site-packages\wandb\__init__.py", line 26, in <module>
    from wandb import sdk as wandb_sdk
  File "...\lib\site-packages\wandb\sdk\__init__.py", line 9, in <module>
    from .wandb_init import _attach, init  # noqa: F401
  File "...\lib\site-packages\wandb\sdk\wandb_init.py", line 30, in <module>
    from . import wandb_login, wandb_setup
  File "...\lib\site-packages\wandb\sdk\wandb_login.py", line 25, in <module>
    from .wandb_settings import Settings, Source
  File "...\lib\site-packages\wandb\sdk\wandb_settings.py", line 39, in <module>
    from wandb.sdk.wandb_setup import _EarlyLogger
  File "...\lib\site-packages\wandb\sdk\wandb_setup.py", line 22, in <module>
    from . import wandb_manager, wandb_settings
  File "...\lib\site-packages\wandb\sdk\wandb_manager.py", line 14, in <module>
    from wandb.sdk.lib.proto_util import settings_dict_from_pbmap
  File "...\lib\site-packages\wandb\sdk\lib\proto_util.py", line 6, in <module>
    from wandb.proto import wandb_internal_pb2 as pb
  File "...\lib\site-packages\wandb\proto\wandb_internal_pb2.py", line 6, in <module>
    from wandb.proto.v3.wandb_internal_pb2 import *
  File "...\lib\site-packages\wandb\proto\v3\wandb_internal_pb2.py", line 16, in <module>
    from wandb.proto import wandb_base_pb2 as wandb_dot_proto_dot_wandb__base__pb2
  File "...\lib\site-packages\wandb\proto\wandb_base_pb2.py", line 6, in <module>
    from wandb.proto.v3.wandb_base_pb2 import *
  File "...\lib\site-packages\wandb\proto\v3\wandb_base_pb2.py", line 21, in <module>
    __RECORDINFO = DESCRIPTOR.message_types_by_name['_RecordInfo']
AttributeError: 'NoneType' object has no attribute 'message_types_by_name'
```

**Comment by sydholl** [comment]
WandB Internal User commented: 
mariuaas commented: 
I have the same issue

**Comment by sydholl** [comment]
WandB Internal User commented: 
kptkin commented: 
Could you check your protobuf version? it seems to work for version `3.20.1` or latest version of protobuf `4.21.9`

**Comment by sydholl** [comment]
WandB Internal User commented: 
JianhuanZhuo commented: 
Any progress? The same issue

**Comment by sydholl** [comment]
WandB Internal User commented: 
raubitsj commented: 
@JianhuanZhuo 
Can you let us know what version of protobuf you are using?
```
pip list | grep protobuf
```

**Comment by sydholl** [comment]
WandB Internal User commented: 
theTrueRiccardo commented: 
Same problem. If I try to do:
`wandb login`
i get an error. Here the trace:
```
File "c:\users\riccardo\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\riccardo\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Riccardo\AppData\Local\Programs\Python\Python39\Scripts\wandb.exe\__main__.py", line 4, in <module>
  File "c:\users\riccardo\appdata\local\programs\python\python39\lib\site-packages\wandb\__init__.py", line 26, in <module>
    from wandb import sdk as wandb_sdk
  File "c:\users\riccardo\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\__init__.py", line 9, in <module>
    from .wandb_init import _attach, init  # noqa: F401
  File "c:\users\riccardo\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\wandb_init.py", line 30, in <module>
    from . import wandb_login, wandb_setup
  File "c:\users\riccardo\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\wandb_login.py", line 25, in <module>
    from .wandb_settings import Settings, Source
  File "c:\users\riccardo\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\wandb_settings.py", line 39, in <module>
    from wandb.sdk.wandb_setup import _EarlyLogger
  File "c:\users\riccardo\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\wandb_setup.py", line 22, in <module>
    from . import wandb_manager, wandb_settings
  File "c:\users\riccardo\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\wandb_manager.py", line 14, in <module>
    from wandb.sdk.lib.proto_util import settings_dict_from_pbmap
  File "c:\users\riccardo\appdata\local\programs\python\python39\lib\site-packages\wandb\sdk\lib\proto_util.py", line 6, in <module>
    from wandb.proto import wandb_internal_pb2 as pb
  File "c:\users\riccardo\appdata\local\programs\python\python39\lib\site-packages\wandb\proto\wandb_internal_pb2.py", line 6, in <module>
    from wandb.proto.v3.wandb_internal_pb2 import *
  File "c:\users\riccardo\appdata\local\programs\python\python39\lib\site-packages\wandb\proto\v3\wandb_internal_pb2.py", line 16, in <module>
    from wandb.proto import wandb_base_pb2 as wandb_dot_proto_dot_wandb__base__pb2
  File "c:\users\riccardo\appdata\local\programs\python\python39\lib\site-packages\wandb\proto\wandb_base_pb2.py", line 6, in <module>
    from wandb.proto.v3.wandb_base_pb2 import *
  File "c:\users\riccardo\appdata\local\programs\python\python39\lib\site-packages\wandb\proto\v3\wandb_base_pb2.py", line 21, in <module>
    __RECORDINFO = DESCRIPTOR.message_types_by_name['_RecordInfo']
AttributeError: 'NoneType' object has no attribute 'message_types_by_nam
```

I'm trying to login from windows, inside venv virtual environment. The problem persists also by changing protobuf version. I've tried 3.20, 3.21, latest, 3.19, 4.21.9

**Comment by sydholl** [comment]
WandB Internal User commented: 
Kartik-Neralwar commented: 
> Could you check your protobuf version? it seems to work for version `3.20.1` or latest version of protobuf `4.21.9`

Using protobuf/3.20.1 gives an error with wandb.keras:

```
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

```

The packages (modules) that I use currently:

anaconda/3/2021.11
cuda/11.4
cudnn/8.2.4
tensorflow/gpu-cuda-11.4/2.8.0
keras/2.6.0
keras-preprocessing/1.1.2
protobuf/3.20.1
wandb /0.13.4 / 0.13.9/ 0.14.1 /0.14.2

Kartik
