### ISSUE TITLE
[CLI]: wandb login directs me to localhost, cannot login/init

### ISSUE THREAD

**Issue by naveace** [wandb/wandb#4460]
### Describe the bug

When I run wandb login it directs me to localhost to get my api key (if I go the address given, it refuses to connect). If I put in the api key from https://wandb.ai/authorize it accepts it, but then if I try wandb.init it cannot connect to your server

```python

In [2]: import wandb

In [3]: wandb.init()
Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
wandb: You can find your API key in your browser here: http://localhost:8080/authorize
wandb: Paste an API key from your profile and hit enter, or press ctrl+c to quit:
wandb: Appending key for localhost to your netrc file: /Users/evanvogelbaum/.netrc
Retry attempt failed:
Traceback (most recent call last):
  File "/Users/evanvogelbaum/opt/anaconda3/envs/PersonalCoding/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/Users/evanvogelbaum/opt/anaconda3/envs/PersonalCoding/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/Users/evanvogelbaum/opt/anaconda3/envs/PersonalCoding/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/evanvogelbaum/opt/anaconda3/envs/PersonalCoding/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/evanvogelbaum/opt/anaconda3/envs/PersonalCoding/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/evanvogelbaum/opt/anaconda3/envs/PersonalCoding/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/Users/evanvogelbaum/opt/anaconda3/envs/PersonalCoding/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/evanvogelbaum/opt/anaconda3/envs/PersonalCoding/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/evanvogelbaum/opt/anaconda3/envs/PersonalCoding/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/evanvogelbaum/opt/anaconda3/envs/PersonalCoding/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/Users/evanvogelbaum/opt/anaconda3/envs/PersonalCoding/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/Users/evanvogelbaum/opt/anaconda3/envs/PersonalCoding/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/Users/evanvogelbaum/opt/anaconda3/envs/PersonalCoding/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7ff6080ad3a0>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/evanvogelbaum/opt/anaconda3/envs/PersonalCoding/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/Users/evanvogelbaum/opt/anaconda3/envs/PersonalCoding/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Users/evanvogelbaum/opt/anaconda3/envs/PersonalCoding/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff6080ad3a0>: Failed to establish a new connection: [Errno 61] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/evanvogelbaum/opt/anaconda3/envs/PersonalCoding/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 113, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/evanvogelbaum/opt/anaconda3/envs/PersonalCoding/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 210, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/Users/evanvogelbaum/opt/anaconda3/envs/PersonalCoding/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/evanvogelbaum/opt/anaconda3/envs/PersonalCoding/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/evanvogelbaum/opt/anaconda3/envs/PersonalCoding/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/Users/evanvogelbaum/opt/anaconda3/envs/PersonalCoding/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/evanvogelbaum/opt/anaconda3/envs/PersonalCoding/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/evanvogelbaum/opt/anaconda3/envs/PersonalCoding/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/evanvogelbaum/opt/anaconda3/envs/PersonalCoding/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/Users/evanvogelbaum/opt/anaconda3/envs/PersonalCoding/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff6080ad3a0>: Failed to establish a new connection: [Errno 61] Connection refused'))
wandb: Network error (ConnectionError), entering retry loop.
wandb: Network error (ConnectionError), entering retry loop.
wandb: | Waiting for wandb.init()...

```

```shell

```

### Additional Files

[debug-internal.log](https://github.com/wandb/wandb/files/9957060/debug-internal.log)
[debug.log](https://github.com/wandb/wandb/files/9957063/debug.log)
[debug-cli.evanvogelbaum.log](https://github.com/wandb/wandb/files/9957064/debug-cli.evanvogelbaum.log)

### Environment

WandB version: wandb, version 0.13.5

OS: macOS Monterey v12.6

Python version: Python 3.9.12

Versions of relevant libraries:

**Comment by ramit-wandb** [comment]
Hi @naveace,

Please run the following command to log in to `wandb.ai`:

```bash
wandb login --cloud --relogin
```

and pass your api key to this.

**Comment by naveace** [comment]
Thank you so much; that solved it!

**Comment by worldveil** [comment]
@ramit-wandb I am seeing this issue still:

```
In [5]: wandb.__version__
Out[5]: '0.13.10'

In [6]: !wandb login --cloud --relogin
Traceback (most recent call last):
  File "/opt/miniconda3/envs/huggingface/bin/wandb", line 8, in <module>
    sys.exit(cli())
  File "/opt/miniconda3/envs/huggingface/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/miniconda3/envs/huggingface/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/miniconda3/envs/huggingface/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/miniconda3/envs/huggingface/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/miniconda3/envs/huggingface/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/miniconda3/envs/huggingface/lib/python3.10/site-packages/wandb/cli/cli.py", line 102, in wrapper
    return func(*args, **kwargs)
  File "/opt/miniconda3/envs/huggingface/lib/python3.10/site-packages/wandb/cli/cli.py", line 226, in login
    wandb_sdk.wandb_login._handle_host_wandb_setting(host, cloud)
  File "/opt/miniconda3/envs/huggingface/lib/python3.10/site-packages/wandb/sdk/wandb_login.py", line 34, in _handle_host_wandb_setting
    _api.clear_setting("base_url", globally=True, persist=True)
  File "/opt/miniconda3/envs/huggingface/lib/python3.10/site-packages/wandb/apis/internal.py", line 78, in clear_setting
    return self.api.clear_setting(*args, **kwargs)
  File "/opt/miniconda3/envs/huggingface/lib/python3.10/site-packages/wandb/apis/internal.py", line 19, in api
    self._api = InternalApi(*self._api_args, **self._api_kwargs)
  File "/opt/miniconda3/envs/huggingface/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 161, in __init__
    self._settings = Settings(
  File "/opt/miniconda3/envs/huggingface/lib/python3.10/site-packages/wandb/old/settings.py", line 25, in __init__
    self._global_settings.read([Settings._global_path()])
  File "/opt/miniconda3/envs/huggingface/lib/python3.10/site-packages/wandb/old/settings.py", line 112, in _global_path
    filesystem.mkdir_exists_ok(config_dir)
  File "/opt/miniconda3/envs/huggingface/lib/python3.10/site-packages/wandb/sdk/lib/filesystem.py", line 16, in mkdir_exists_ok
    os.makedirs(dir_name, exist_ok=True)
  File "/opt/miniconda3/envs/huggingface/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/Users/xxx/.config/wandb'
```

How can I get around this?
