### ISSUE TITLE
[CLI]:  Bug or possible method removed in Api.artifact_type() 

### ISSUE THREAD

**Issue by ShuAiii** [wandb/wandb#4532]
### Describe the bug

Trying to retrieve all "dataset" type Artifact from a WandB project is not working for me.

```python
import wandb

os.environ["WANDB_API_KEY"] = "API -KEY"
api = wandb.Api()
project_name = 'PROJECT-NAME'

collections = [coll for coll in api.artifact_type(type_name="dataset", project=project_name).collections()]
```

```shell
Traceback (most recent call last):
  File ".\boto.py", line 8, in <module>
    collections = [coll for coll in api.artifact_type(type_name="dataset", project=project_name).collections()]
  File "C:\Users\kzhang\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\wandb\apis\normalize.py", line 62, in wrapper
    six.reraise(CommError, CommError(message, err), sys.exc_info()[2])
  File "C:\Users\kzhang\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\kzhang\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\wandb\apis\normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\kzhang\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\wandb\apis\public.py", line 735, in artifact_type
    return ArtifactType(self.client, entity, project, type_name)
  File "C:\Users\kzhang\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\wandb\apis\public.py", line 3102, in __init__
    self.load()
  File "C:\Users\kzhang\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\wandb\apis\public.py", line 3136, in load
    raise ValueError("Could not find artifact type %s" % self.type)
wandb.errors.CommError: Could not find artifact type dataset
```

### Environment

WandB version: '0.12.11'

**Comment by ShuAiii** [comment]
Solved. If you belong to a team, `api.artifact_type(type_name=..., project=project_name)` only yields the artifacts either from your team account or your personal account, depending on your default choice.
