### ISSUE TITLE
[CLI]: wandb: ERROR Abnormal program exit & No Space left on the device

### ISSUE THREAD

**Issue by kaansancak** [wandb/wandb#4541]
### Describe the bug

I am trying to start a sweep job but I am getting the following error even though I have enough space on my server.
This started to happen very recently, I tried clearing out the cache/output files generated by wandb.
I have also tried setting up `WANDB_CACHE_DIR` and `WANDB_DIR` but still getting the same errors.

```python
CUDA_VISIBLE_DEVICES=0 wandb agent kaansancak/arxiv-res/b3b3oiv4
```

```shell
Traceback (most recent call last):
  File "/opt/conda/envs/auto/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1075, in init
    wi.setup(kwargs)
  File "/opt/conda/envs/auto/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 165, in setup
    self._wl = wandb_setup.setup()
  File "/opt/conda/envs/auto/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 312, in setup
    ret = _setup(settings=settings)
  File "/opt/conda/envs/auto/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 307, in _setup
    wl = _WandbSetup(settings=settings)
  File "/opt/conda/envs/auto/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 293, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/opt/conda/envs/auto/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 100, in __init__
    self._settings = self._settings_setup(settings, self._early_logger)
  File "/opt/conda/envs/auto/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 130, in _settings_setup
    s._infer_run_settings_from_environment(_logger=early_logger)
  File "/opt/conda/envs/auto/lib/python3.9/site-packages/wandb/sdk/wandb_settings.py", line 1430, in _infer_run_settings_from_environment
    program_relpath = self.program_relpath or _get_program_relpath_from_gitrepo(
  File "/opt/conda/envs/auto/lib/python3.9/site-packages/wandb/sdk/wandb_settings.py", line 139, in _get_program_relpath_from_gitrepo
    root = repo.root
  File "/opt/conda/envs/auto/lib/python3.9/site-packages/wandb/sdk/lib/git.py", line 65, in root
    return self.repo.git.rev_parse("--show-toplevel")
  File "/opt/conda/envs/auto/lib/python3.9/site-packages/git/cmd.py", line 696, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/opt/conda/envs/auto/lib/python3.9/site-packages/git/cmd.py", line 1270, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/opt/conda/envs/auto/lib/python3.9/site-packages/git/cmd.py", line 1064, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(-7)
  cmdline: git rev-parse --show-toplevel
wandb: ERROR Abnormal program exit
Traceback (most recent call last):
  File "/opt/conda/envs/auto/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1075, in init
    wi.setup(kwargs)
  File "/opt/conda/envs/auto/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 165, in setup
    self._wl = wandb_setup.setup()
  File "/opt/conda/envs/auto/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 312, in setup
    ret = _setup(settings=settings)
  File "/opt/conda/envs/auto/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 307, in _setup
    wl = _WandbSetup(settings=settings)
  File "/opt/conda/envs/auto/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 293, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/opt/conda/envs/auto/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 100, in __init__
    self._settings = self._settings_setup(settings, self._early_logger)
  File "/opt/conda/envs/auto/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 130, in _settings_setup
    s._infer_run_settings_from_environment(_logger=early_logger)
  File "/opt/conda/envs/auto/lib/python3.9/site-packages/wandb/sdk/wandb_settings.py", line 1430, in _infer_run_settings_from_environment
    program_relpath = self.program_relpath or _get_program_relpath_from_gitrepo(
  File "/opt/conda/envs/auto/lib/python3.9/site-packages/wandb/sdk/wandb_settings.py", line 139, in _get_program_relpath_from_gitrepo
    root = repo.root
  File "/opt/conda/envs/auto/lib/python3.9/site-packages/wandb/sdk/lib/git.py", line 65, in root
    return self.repo.git.rev_parse("--show-toplevel")
  File "/opt/conda/envs/auto/lib/python3.9/site-packages/git/cmd.py", line 696, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/opt/conda/envs/auto/lib/python3.9/site-packages/git/cmd.py", line 1270, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/opt/conda/envs/auto/lib/python3.9/site-packages/git/cmd.py", line 1064, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(-7)
  cmdline: git rev-parse --show-toplevel

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/localscratch/AutoGNN/tuner.py", line 104, in <module>
    main()
  File "/localscratch/AutoGNN/tuner.py", line 44, in main
    run = wandb.init(settings=wandb.Settings(disable_code=True, save_code=False))
  File "/opt/conda/envs/auto/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1116, in init
    raise Exception("problem") from error_seen
Exception: problem
2022-11-28 19:47:52,641 - wandb.wandb_agent - INFO - Running runs: ['6xe5qi52']
2022-11-28 19:47:52,642 - wandb.wandb_agent - INFO - Cleaning up finished run: 6xe5qi52
2022-11-28 19:47:53,137 - wandb.wandb_agent - INFO - Agent received command: run
2022-11-28 19:47:53,142 - wandb.wandb_agent - ERROR - Exception while processing command: {'run_id': 'vp2fee3r', 'program': 'tuner.py', 'type': 'run', 'args': {'att': {'value': 'cat'}, 'baseline': {'value': 0}, 'dataset': {'value': 'ogbn-arxiv'}, 'dense': {'value': 0}, 'dropout': {'value': 0.3398706821913155}, 'epochs': {'value': 5000}, 'fused': {'value': 0}, 'gcn_norm': {'value': 0}, 'hidden_channels': {'value': 355}, 'lr': {'value': 0.08327753206290885}, 'n_layers': {'value': 8}, 'no_bn': {'value': 0}, 'use_linear': {'value': 0}}, 'runqueue_item_id': 'UnVuUXVldWVJdGVtOjE5NzU4NzI0Mg==', 'logs': ['expected_improvement: 3.133893e-05', 'predicted_value: 0.000000e+00', 'predicted_value_std_dev: 7.855504e-11', 'success_probability: 5.000000e-01', 'warnings: \n Some dimmensions of kernel are close to their bounds (bad fit), the next sample will be a random sample within parameter space'], 'run_storage_id': 'UnVuOnYxOnZwMmZlZTNyOmFyeGl2LXJlczprYWFuc2FuY2Fr'}
Traceback (most recent call last):
  File "/opt/conda/envs/auto/lib/python3.9/site-packages/wandb/wandb_agent.py", line 322, in _process_command
    result = self._command_run(command)
  File "/opt/conda/envs/auto/lib/python3.9/site-packages/wandb/wandb_agent.py", line 478, in _command_run
    proc = AgentProcess(command=command_list, env=env)
  File "/opt/conda/envs/auto/lib/python3.9/site-packages/wandb/wandb_agent.py", line 38, in __init__
    self._finished_q = multiprocessing.Queue()
  File "/opt/conda/envs/auto/lib/python3.9/multiprocessing/context.py", line 103, in Queue
    return Queue(maxsize, ctx=self.get_context())
  File "/opt/conda/envs/auto/lib/python3.9/multiprocessing/queues.py", line 48, in __init__
    self._wlock = ctx.Lock()
  File "/opt/conda/envs/auto/lib/python3.9/multiprocessing/context.py", line 68, in Lock
    return Lock(ctx=self.get_context())
  File "/opt/conda/envs/auto/lib/python3.9/multiprocessing/synchronize.py", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/opt/conda/envs/auto/lib/python3.9/multiprocessing/synchronize.py", line 57, in __init__
    sl = self._semlock = _multiprocessing.SemLock(
OSError: [Errno 28] No space left on device
```

### Environment

WandB version: wandb==0.13.5

OS: Ubuntu 20.04.5 LTS

Python version: Python 3.9.13

**Comment by MBakirWB** [comment]
Hi @kaansancak , happy to help. Are you running your experiments through a docker container or EC2 instance? If you are, you will need to need to increase the size of your docker container.

**Comment by kaansancak** [comment]
> Hi @kaansancak , happy to help. Are you running your experiments through a docker container or EC2 instance? If you are, you will need to need to increase the size of your docker container.

Can you clarify which size you are referring to?

**Comment by MBakirWB** [comment]
Hi @kaansancak, apologies for delay in clarification. The `WANDB_DIR` env variable sets where the wandb files land during experiment execution. To modify where the files land, they can either use env variable `os.environ["WANDB_DIR"]` or do it with an `init(dir=...)` call (or they can have global settings file in the system). When users are uploading artifacts we save them and write through the `~/.cache/wandb`, which can be changed by setting  `WANDB_CACHE_DIR` env variable. 

Sometime when users are running experiments through a docker container, they haven't allocated enough storage size to the container to accommodate their experiments runs. This could be what is happening here. I recommend to first increase the storage allocation size of your docker container.

**Comment by kaansancak** [comment]
Hi @MBakirWB, I believe I have more than enough storage in my docker, correct me if I am wrong.
```
Filesystem                                          Size  Used Avail Use% Mounted on
overlay                                             1.1T  252G  704G  27% /
tmpfs                                                68M     0   68M   0% /dev
tmpfs                                               542G     0  542G   0% /sys/fs/cgroup
shm                                                  68M     0   68M   0% /dev/shm
/dev/md1                                             31T  1.5T   28T   5% /localscratch
/hcsefiles1/ksancak3                       54G  5.1G   49G  10% /home/host
/dev/nvme2n1p2                                      1.1T  252G  704G  27% /etc/hosts
tmpfs                                               109G   63M  109G   1% /run/nvidia-persistenced/socket
udev                                                541G     0  541G   0% /dev/nvidia0
tmpfs                                               542G     0  542G   0% /proc/acpi
tmpfs                                               542G     0  542G   0% /proc/scsi
tmpfs                                               542G     0  542G   0% /sys/firmware
```
I have tried setting `WANDB_DIR` AND `WANDB_CACHE_DIR`, however it didn't resolve the issue. Currently, I haven't set up `WANDB_CACHE_DIR`, so it should point to default `~/.cache/wandb` however, there isn't such directory in my system.

**Comment by MBakirWB** [comment]
Hi @kaansancak , With Artifacts, we copy to `tempfile.TemporaryDirectory()` from the python stdlib, and we recommend for users today to have` 2x` the space to upload the artifact as we write through the cache.

- How large are the artifacts you are uploading? 
- Our application also writes to the `/var/log` directory and the `/vol/env` directory, check these as well.
- Try setting `WANDB_CACHE_DIR=/tmp`. 
-  Did you build a private local instance? If yes, are you using our minio storage inside the container? As you log anything the container starts to grow in size and eventually run out of disk space.

**Comment by MBakirWB** [comment]
Hi @kaansancak  since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by alexanderswerdlow** [comment]
Bumping this issue. My training hangs because of the out of space issue. Despite `WANDB_CACHE_DIR` being unset, the writes are going to `/tmp`. Despite this, I see that `~/.cache/wandb` has recent writes.

At the very least, it's critical that training continues when this error occurs, instead of hanging.

**Comment by shrinandj** [comment]
The stack trace:

```
  File "/opt/conda/envs/auto/lib/python3.9/multiprocessing/synchronize.py", line 57, in __init__
    sl = self._semlock = _multiprocessing.SemLock(
OSError: [Errno 28] No space left on device
```

suggests that the problem was when creating a semaphore. NOT about disk capacity.

You could try to increase the number of semaphores allowed in the system by running something like: `sysctl -w kernel.sem="250 32000 32 192"`

https://www.thegeekdiary.com/how-to-change-kernel-semaphore-limits-in-centos-rhel

**Comment by asarigun** [comment]
`WANDB_CACHE_DIR` is an environment variable that you can use to set the location of the Weights & Biases cache directory. Here's how you can use it with Weights & Biases (`wandb`):

1. Set the environment variable before running your Python script or Jupyter notebook:

```bash
export WANDB_CACHE_DIR=/path/to/cache/directory
```

2. Initialize `wandb` by calling `wandb.init()` in your Python script or Jupyter notebook. `wandb` will automatically use the cache directory specified by the `WANDB_CACHE_DIR` environment variable.

Here's an example:

```bash
import os
import wandb

# Set the WANDB_CACHE_DIR environment variable
os.environ['WANDB_CACHE_DIR'] = '/path/to/cache/directory'

# Initialize wandb
wandb.init(project='my-project', entity='my-entity')

# Train your model and log results to wandb
...
```

By setting the `WANDB_CACHE_DIR` environment variable, `wandb` will use the specified directory for caching data and artifacts. This can be useful if you have limited space on your default cache directory, or if you want to store the cache on a different disk.
