### ISSUE TITLE
[CLI]: AttributeError: partially initialized module 'wandb' has no attribute 'login' 

### ISSUE THREAD

**Issue by pauliusrauba** [wandb/wandb#4560]
### Describe the bug

I'm trying to login to wandb as per the quickstart tutorial by entering ```wandb login``` in the terminal. I get the following error:

```
Traceback (most recent call last):
  File "/Users/pauliusrauba/opt/miniconda3/envs/torch-gpu/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/pauliusrauba/opt/miniconda3/envs/torch-gpu/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/pauliusrauba/Library/CloudStorage/OneDrive-Personal/University of Cambridge/2022/VSCode/wandb.py", line 1, in <module>
    import wandb
  File "/Users/pauliusrauba/Library/CloudStorage/OneDrive-Personal/University of Cambridge/2022/VSCode/wandb.py", line 2, in <module>
    wandb.login()
AttributeError: partially initialized module 'wandb' has no attribute 'login' (most likely due to a circular import)
proc exited with 1
Traceback (most recent call last):
  File "/Users/pauliusrauba/opt/miniconda3/envs/torch-gpu/bin/wandb", line 8, in <module>
    sys.exit(cli())
  File "/Users/pauliusrauba/opt/miniconda3/envs/torch-gpu/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/pauliusrauba/opt/miniconda3/envs/torch-gpu/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/pauliusrauba/opt/miniconda3/envs/torch-gpu/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/pauliusrauba/opt/miniconda3/envs/torch-gpu/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/pauliusrauba/opt/miniconda3/envs/torch-gpu/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/pauliusrauba/opt/miniconda3/envs/torch-gpu/lib/python3.10/site-packages/wandb/cli/cli.py", line 97, in wrapper
    return func(*args, **kwargs)
  File "/Users/pauliusrauba/opt/miniconda3/envs/torch-gpu/lib/python3.10/site-packages/wandb/cli/cli.py", line 236, in login
    wandb.setup(settings=login_settings)
  File "/Users/pauliusrauba/opt/miniconda3/envs/torch-gpu/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 312, in setup
    ret = _setup(settings=settings)
  File "/Users/pauliusrauba/opt/miniconda3/envs/torch-gpu/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 307, in _setup
    wl = _WandbSetup(settings=settings)
  File "/Users/pauliusrauba/opt/miniconda3/envs/torch-gpu/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 293, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/Users/pauliusrauba/opt/miniconda3/envs/torch-gpu/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 106, in __init__
    self._setup()
  File "/Users/pauliusrauba/opt/miniconda3/envs/torch-gpu/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 234, in _setup
    self._setup_manager()
  File "/Users/pauliusrauba/opt/miniconda3/envs/torch-gpu/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 265, in _setup_manager
    self._manager = wandb_manager._Manager(
  File "/Users/pauliusrauba/opt/miniconda3/envs/torch-gpu/lib/python3.10/site-packages/wandb/sdk/wandb_manager.py", line 108, in __init__
    self._service.start()
  File "/Users/pauliusrauba/opt/miniconda3/envs/torch-gpu/lib/python3.10/site-packages/wandb/sdk/service/service.py", line 112, in start
    self._launch_server()
  File "/Users/pauliusrauba/opt/miniconda3/envs/torch-gpu/lib/python3.10/site-packages/wandb/sdk/service/service.py", line 108, in _launch_server
    assert ports_found
AssertionError
```

Anything I need to do from my end? 

```python

```

```shell

```

### Environment

WandB version: 0.13.5

OS: Ventura 13.0.1, Apple M1 Pro

Python version: 3.10.8

Versions of relevant libraries:

### Additional Context

Launching from VSCode, using an interpreter that is from a miniconda environment.

**Comment by MBakirWB** [comment]
Hi @pauliusrauba , could you try `wandb login --relogin --host=https://api.wandb.ai`

**Comment by pauliusrauba** [comment]
Solved it. Had a python file ```wandb.py``` in the same folder. Renaming the file helped. No need to use ```--relogin``` or ```--host```.
