### ISSUE TITLE
[Q] How to use wandb/sweep on a computer without internet connection？

### ISSUE THREAD

**Issue by CaiCandong** [wandb/wandb#4586]
I've tried using offline mode, but it doesn't work：
```
(torch) wandb offline
W&B offline. Running your script from this directory will only write metadata locally. Use wandb disabled to completely turn off W&B.
(torch) wandb sweep --controller ./config.yaml 
wandb: Creating sweep from: ./config.yaml
wandb: Network error (ConnectionError), entering retry loop.
```
```
controller:
  type: local
method: bayes
metric:
  goal: minimize
  name: val_loss_avg
parameters:
  batch_size:
    distribution: int_uniform
    max: 20
    min: 4
  learning_rate:
    distribution: uniform
    max: 0.01
    min: 0.0001
  lr_patience:
    distribution: int_uniform
    max: 10
    min: 3
program: train.py
```
```
2022-12-07 23:10:03 ERROR Retry attempt failed:
Traceback (most recent call last):
  File "/dssg/home/caicandong/anaconda3/envs/torch/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/dssg/home/caicandong/anaconda3/envs/torch/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/dssg/home/caicandong/anaconda3/envs/torch/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dssg/home/caicandong/anaconda3/envs/torch/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/dssg/home/caicandong/anaconda3/envs/torch/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/dssg/home/caicandong/anaconda3/envs/torch/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/dssg/home/caicandong/anaconda3/envs/torch/lib/python3.8/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/dssg/home/caicandong/anaconda3/envs/torch/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fcc03fa59d0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dssg/home/caicandong/anaconda3/envs/torch/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/dssg/home/caicandong/anaconda3/envs/torch/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/dssg/home/caicandong/anaconda3/envs/torch/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcc03fa59d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dssg/home/caicandong/anaconda3/envs/torch/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 113, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/dssg/home/caicandong/anaconda3/envs/torch/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 210, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/dssg/home/caicandong/anaconda3/envs/torch/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/dssg/home/caicandong/anaconda3/envs/torch/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/dssg/home/caicandong/anaconda3/envs/torch/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/dssg/home/caicandong/anaconda3/envs/torch/lib/python3.8/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/dssg/home/caicandong/anaconda3/envs/torch/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/dssg/home/caicandong/anaconda3/envs/torch/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/dssg/home/caicandong/anaconda3/envs/torch/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/dssg/home/caicandong/anaconda3/envs/torch/lib/python3.8/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcc03fa59d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

```

**Comment by thanos-wandb** [comment]
Hi @CaiCandong thank you for writing in! You can only run experiments in offline mode, which means that it will write in your local disk and you will then be able to `sync` anytime you want with W&B UI. However, for sweeps this isn't possible as you can see more detailed from the diagram below, as you will need to communicate with sweep server to create the sweep_id and then the agents will need to know which hyperparameter set to use.

![1_Sweeps_High_Level_Overview](https://user-images.githubusercontent.com/108423944/206537835-0124e96e-dee0-4748-8a71-d69b1cd7e059.svg)


May I please ask what's the use case for this, and why you would like to run the sweep experiments offline? a workaround would be if you were [self-hosting](https://docs.wandb.ai/guides/self-hosted) the W&B instance, let me know if you would need further assistance with this option.

**Comment by CaiCandong** [comment]
Thanks for your answer, our lab has a deep learning cluster running in an intranet environment, so I want to use `sweep` offline.

**Comment by nepfaff** [comment]
@thanos-wandb is your example supposed to work on a computer without internet access?
