### ISSUE TITLE
[CLI]: problem creating a table

### ISSUE THREAD

**Issue by fabioboh** [wandb/wandb#4592]
### Describe the bug

I am not able to create a table from a pandas dataframe such that the column elements are a list of list of list (versions: 0.13.5 and 0.13.6). This did not produce an error in version 0.10.8. 

```python
import pandas as pd
import numpy as np
import os
import wandb
os.environ['WANDB_MODE'] = 'dryrun'
a = np.array([1,2,3])
b = np.array([5,6,7])
data = [[[a,b,b]],[[b,b,a]]]
df = pd.DataFrame(data, columns=['boh'])
wandb.init(project='BOH', name="dummy-name", group='ncv', dir='.')
wandb.Table(dataframe=df)
```

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/wandb/data_types.py", line 271, in __init__
    self._init_from_dataframe(dataframe, columns, optional, dtype)
  File "/usr/local/lib/python3.8/dist-packages/wandb/data_types.py", line 328, in _init_from_dataframe
    self.add_data(*tuple(dataframe[col].values[row] for col in self.columns))
  File "/usr/local/lib/python3.8/dist-packages/wandb/data_types.py", line 470, in add_data
    result_type = self._get_updated_result_type(data)
  File "/usr/local/lib/python3.8/dist-packages/wandb/data_types.py", line 489, in _get_updated_result_type
    result_type = current_type.assign(incoming_row_dict)
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/data_types/_dtypes.py", line 842, in assign
    type_map[key] = self.params["type_map"][key].assign(
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/data_types/_dtypes.py", line 549, in assign
    resolved_types = _union_assigner(
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/data_types/_dtypes.py", line 496, in _union_assigner
    assigned_type = allowed_type.assign(obj_or_type)
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/data_types/_dtypes.py", line 216, in assign
    return self.assign_type(TypeRegistry.type_of(py_obj))
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/data_types/_dtypes.py", line 73, in type_of
    _type = class_handler.from_obj(py_obj)
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/data_types/_dtypes.py", line 623, in from_obj
    UnknownType() if None not in py_list else OptionalType(UnknownType())
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/wandb/data_types.py", line 271, in __init__
    self._init_from_dataframe(dataframe, columns, optional, dtype)
  File "/usr/local/lib/python3.8/dist-packages/wandb/data_types.py", line 328, in _init_from_dataframe
    self.add_data(*tuple(dataframe[col].values[row] for col in self.columns))
  File "/usr/local/lib/python3.8/dist-packages/wandb/data_types.py", line 470, in add_data
    result_type = self._get_updated_result_type(data)
  File "/usr/local/lib/python3.8/dist-packages/wandb/data_types.py", line 489, in _get_updated_result_type
    result_type = current_type.assign(incoming_row_dict)
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/data_types/_dtypes.py", line 842, in assign
    type_map[key] = self.params["type_map"][key].assign(
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/data_types/_dtypes.py", line 549, in assign
    resolved_types = _union_assigner(
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/data_types/_dtypes.py", line 496, in _union_assigner
    assigned_type = allowed_type.assign(obj_or_type)
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/data_types/_dtypes.py", line 216, in assign
    return self.assign_type(TypeRegistry.type_of(py_obj))
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/data_types/_dtypes.py", line 73, in type_of
    _type = class_handler.from_obj(py_obj)
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/data_types/_dtypes.py", line 623, in from_obj
    UnknownType() if None not in py_list else OptionalType(UnknownType())
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

```

### Environment

WandB version: 0.13.6

OS: NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

Python version:
3.8.10
Versions of relevant libraries:
pandas = '1.1.5'
numpy = '1.19.5'

**Comment by thanos-wandb** [comment]
Hi @fabioboh thank you for reporting this. May I please ask what array type and shape you would like to log as Table? If you wanted to log a 2D array, you could adjust your code as follows:
```
data = [[a,b,b],[b,b,a]]
df = pd.DataFrame(data, columns=['boh1', 'boh2', 'boh3'])
```
Would this work for you?

**Comment by fabioboh** [comment]
Hi @thanos-wandb , thanks for your quick reply. I use the table to store the results of repeated nested cross validation.  In some column I need to store the classifier predictions across folds and repetitions. I can of course rewrite my code to use a structure as you suggest (but there would be a variable number of columns), but I again of course would prefer to stick with the code I have (which was working with version 0.10.8). Is there a reason why you

**Comment by fabioboh** [comment]
dear @thanos-wandb , could you please tell me if you plan to solve this problem or whether I should plan a different solution? thanks a lot

**Comment by fabioboh** [comment]
@thanos-wandb I do not understand this automatic answer...

**Comment by thanos-wandb** [comment]
Hi @fabioboh sorry for the automated reply received from our ticketing system, and the late response here. This data structure indeed seems to work up to `0.10.12` version. I have reported the issue in the engineering team, and I will keep you posted on any updates.

In the meantime, please let us know if you would need any help to adjust your code/data, and we can further look into a workaround. It would be recommended that you upgrade to our most recent version (currently `0.13.7`) as it includes many bug fixes and features since then.
