### ISSUE TITLE
wandb error when running yolov7

### ISSUE THREAD

**Issue by ChiraagPV** [wandb/wandb#4608]
wandb: W&B API key is configured. Use wandb login --relogin to force relogin
wandb: Network error (JSONDecodeError), entering retry loop.
wandb: Network error (JSONDecodeError), entering retry loop.

wandb: ERROR Error communicating with wandb process
wandb: ERROR For more info see: https://docs.wandb.ai/library/init#init-start-error

wandb.errors.UsageError: Error communicating with wandb process
For more info see: https://docs.wandb.ai/library/init#init-start-error

I am unable to run codes and getting an interruption here, Can you help me out with this issue?

**Comment by ChiraagPV** [comment]
wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin
wandb: Network error (JSONDecodeError), entering retry loop.
wandb: Network error (JSONDecodeError), entering retry loop.

wandb: ERROR Error communicating with wandb process
wandb: ERROR For more info see: https://docs.wandb.ai/library/init#init-start-error

wandb.errors.UsageError: Error communicating with wandb process
For more info see: https://docs.wandb.ai/library/init#init-start-error

I am unable to run codes and getting an interruption here, Can you help me out with this issue?

**Comment by ChiraagPV** [comment]
Latest Error :

C:\WINDOWS\system32>python
Python 3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import wandb
>>> wandb.init(settings=wandb.Settings(start_method="fork"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\chira\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\wandb_settings.py", line 1079, in __init__
    self.update({k: v}, source=source)
  File "C:\Users\chira\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\wandb_settings.py", line 1208, in update
    self.__dict__[key].update(value, source)
  File "C:\Users\chira\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\wandb_settings.py", line 334, in update
    self._value = self._validate(self._preprocess(value))
  File "C:\Users\chira\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\wandb_settings.py", line 295, in _validate
    if not v(value):
  File "C:\Users\chira\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\wandb_settings.py", line 755, in _validate_start_method
    raise UsageError(
wandb.errors.UsageError: Settings field `start_method`: 'fork' not in ['thread', 'spawn']
>>> wandb.init(settings=wandb.Settings(start_method="thread"))
wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin
wandb: Network error (JSONDecodeError), entering retry loop.
wandb: Network error (JSONDecodeError), entering retry loop.
Problem at: <stdin> 1 <module>t()...
wandb: ERROR Error communicating with wandb process
wandb: ERROR For more info see: https://docs.wandb.ai/library/init#init-start-error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\chira\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\wandb_init.py", line 1078, in init
    run = wi.init()
  File "C:\Users\chira\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\wandb_init.py", line 719, in init
    raise UsageError(error_message)
wandb.errors.UsageError: Error communicating with wandb process
For more info see: https://docs.wandb.ai/library/init#init-start-error
>>>

**Comment by anmolmann** [comment]
Hi @ChiraagPV, the `JSONDecodeError` means the server is returning an error. Are you able to access the site in the browser? 
-Also, the debug log from the client library itself would be helpful. You can find it in `wandb/debug-internal.log` relative to your script. If you could please share it with us that would be really helpful.
- Also, could you please let us know which wandb version you are on? (`wandb --version`)

**Comment by anmolmann** [comment]
Hi @ChiraagPV, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
