### ISSUE TITLE
[App]: Offline resuming issue

### ISSUE THREAD

**Issue by GabPrato** [wandb/wandb#4624]
### Current Behavior

If I run a job in offline mode and stop the job, then resume, I get two different results depending on when I stop the job, shouldn't happen and is very easy to reproduce.
If I log more steps in the first part than in the second, I only see the first part being plotted on wandb. The logs contain everything but the second part is first in the logs and the first part is after.
If I log more steps in the second part, I see all the steps in the plot on wandb. The logs only contain the second part though.

### Expected Behavior

All steps logged should be visible and the logs should contain all logs and in order.

### Steps To Reproduce

Here's how to reproduce:

Python code, make sure to set a value for project and entity in `wandb.init()`:
```python
import argparse
import numpy as np
import wandb
import time

parser = argparse.ArgumentParser()
parser.add_argument("--wandb_experiment_name", type=str)
parser.add_argument("--wandb_experiment_id", type=str)
parser.add_argument("--step_to_start_at", type=int, default=0)
args = parser.parse_args()


wandb.init(project='undefined', entity='undefined', name=args.wandb_experiment_name, config=args,
    id=args.wandb_experiment_id, resume="allow")


for i in range(args.step_to_start_at, 100):
    print(f'{i}/100')
    time.sleep(1)
    wandb.log({'Train Loss': np.random.rand(1).item()}, step=i)
```

Then in your console run the following commands:
```bash
WANDB_EXPERIMENT_NAME="debug-wandb23" # non unique name
WANDB_EXPERIMENT_ID="2022-12-13_18-45-00" # unique wandb id, max 64 characters

wandb offline
export WANDB_DIR="./wandb/$WANDB_EXPERIMENT_ID"
mkdir -p $WANDB_DIR

python -u debug_wandb.py \
    --wandb_experiment_name=$WANDB_EXPERIMENT_NAME \
    --wandb_experiment_id=$WANDB_EXPERIMENT_ID \
    --step_to_start_at=0 
```
And kill the job at around 50 steps. Then restart the job:
```bash
python -u debug_wandb.py \
    --wandb_experiment_name=$WANDB_EXPERIMENT_NAME \
    --wandb_experiment_id=$WANDB_EXPERIMENT_ID \
    --step_to_start_at=51

```
And kill it once it gets to step 70. Then sync:
```bash
wandb sync wandb/$WANDB_EXPERIMENT_ID/wandb/off*
```
I get the following plot:
![Screenshot from 2022-12-13 18-53-09](https://user-images.githubusercontent.com/25964820/207471618-2352accf-6ad3-4d40-9288-2b1d977d3ce4.png)

​As you can see, it logs up to about where we killed the job. If I look at the logs on wandb, they are in the wrong order:
> 50/100
> 51/100
> 52/100
> 53/100
> 54/100
> 55/100
> 56/100
> 57/100
> 58/100
> 59/100
> 60/100
> 61/100
> 62/100
> 63/100
> 64/100
> 65/100
> 66/100
> 67/100
> 68/100
> 69/100
> Traceback (most recent call last):
>   File "/home/pratogab/Projects/efficient_video_transformer/debug_wandb.py", line 21, in <module>
>     time.sleep(1)
> KeyboardInterrupt
> 24/100
> 25/100
> 26/100
> 27/100
> 28/100
> 29/100
> 30/100
> 31/100
> 32/100
> 33/100
> 34/100
> 35/100
> 36/100
> 37/100
> 38/100
> 39/100
> 40/100
> 41/100
> 42/100
> 43/100
> 44/100
> 45/100
> 46/100
> 47/100
> 48/100
> 49/100
> Traceback (most recent call last):
>   File "/home/pratogab/Projects/efficient_video_transformer/debug_wandb.py", line 21, in <module>
>     time.sleep(1)
> KeyboardInterrupt

If instead I kill the job at step around 20 and then run the second one for longer, I see all the logs:
```bash
WANDB_EXPERIMENT_NAME="debug-wandb24" # non unique name
WANDB_EXPERIMENT_ID="2022-12-13_18-46-00" # unique wandb id, max 64 characters

wandb offline
export WANDB_DIR="./wandb/$WANDB_EXPERIMENT_ID"
mkdir -p $WANDB_DIR

python -u debug_wandb.py \
    --wandb_experiment_name=$WANDB_EXPERIMENT_NAME \
    --wandb_experiment_id=$WANDB_EXPERIMENT_ID \
    --step_to_start_at=0 
```
(I kill the job at around 20 steps. Then restart the job:)
```bash
python -u debug_wandb.py \
    --wandb_experiment_name=$WANDB_EXPERIMENT_NAME \
    --wandb_experiment_id=$WANDB_EXPERIMENT_ID \
    --step_to_start_at=21
```
(And kill it once it gets to step 90. Then sync:)
```bash
wandb sync wandb/$WANDB_EXPERIMENT_ID/wandb/off*
```
I get this:
![Screenshot from 2022-12-13 18-56-32](https://user-images.githubusercontent.com/25964820/207471722-7e87feea-cd85-43e6-add3-67e6adeebef3.png)

If I look at the logs, they are missing the first part:
> 37/100
> 38/100
> 39/100
> 40/100
> 41/100
> 42/100
> 43/100
> 44/100
> 45/100
> 46/100
> 47/100
> 48/100
> 49/100
> 50/100
> 51/100
> 52/100
> 53/100
> 54/100
> 55/100
> 56/100
> 57/100
> 58/100
> 59/100
> 60/100
> 61/100
> 62/100
> 63/100
> 64/100
> 65/100
> 66/100
> 67/100
> 68/100
> 69/100
> 70/100
> 71/100
> 72/100
> 73/100
> 74/100
> 75/100
> 76/100
> 77/100
> 78/100
> 79/100
> 80/100
> 81/100
> 82/100
> 83/100
> 84/100
> 85/100
> 86/100
> 87/100
> 88/100
> 89/100
> 90/100
> Traceback (most recent call last):
>   File "/home/pratogab/Projects/efficient_video_transformer/debug_wandb.py", line 21, in <module>
>     time.sleep(1)
> KeyboardInterrupt

### Screenshots

![Screenshot from 2022-12-13 18-53-09](https://user-images.githubusercontent.com/25964820/207472361-79732dad-b392-4b73-800e-ab80704d5bff.png)
![Screenshot from 2022-12-13 18-56-32](https://user-images.githubusercontent.com/25964820/207472362-e0b6c249-e2f5-43d7-89af-5b3a15ed5a4d.png)

### Environment

OS: Linux, ubuntu 20

Browsers: Chrome

Version: wandb 0.12.14 & 0.13.6

**Comment by thanos-wandb** [comment]
Hi @pratogab thanks so much for reporting this, and all the detailed information to reproduce this error. Does the issue pop up only when you kill the process? Have you tried for instance running this to a certain step and properly terminate the job with `wandb.finish()` and then continue from there with `resume='must'`?

**Comment by pratogab** [comment]
@thanos-wandb I tried what you asked, but same result.
```python
import argparse
import numpy as np
import wandb
import time

parser = argparse.ArgumentParser()
parser.add_argument("--wandb_experiment_name", type=str)
parser.add_argument("--wandb_experiment_id", type=str)
parser.add_argument("--wandb_resume", action='store_true')
parser.add_argument("--step_to_start_at", type=int, default=0)
parser.add_argument("--step_to_end_at", type=int, default=100)
args = parser.parse_args()


if args.wandb_resume:
    wandb.init(project='undefined', entity='undefined', name=args.wandb_experiment_name, config=args, 
        id=args.wandb_experiment_id, resume="must")
else:
    wandb.init(project='undefined', entity='undefined', name=args.wandb_experiment_name, config=args, 
        id=args.wandb_experiment_id)


for i in range(args.step_to_start_at, args.step_to_end_at + 1):
    print(f'{i}/{args.step_to_end_at}')
    time.sleep(1)
    wandb.log({'Train Loss': np.random.rand(1).item()}, step=i)

wandb.finish()
```

```bash
WANDB_EXPERIMENT_NAME="debug-wandb25" # non unique name
WANDB_EXPERIMENT_ID="2022-12-17_10-29-00" # unique wandb id, max 64 characters

wandb offline
export WANDB_DIR="./wandb/$WANDB_EXPERIMENT_ID"
mkdir -p $WANDB_DIR

python -u debug_wandb.py \
    --wandb_experiment_name=$WANDB_EXPERIMENT_NAME \
    --wandb_experiment_id=$WANDB_EXPERIMENT_ID \
    --step_to_start_at=0 \
    --step_to_end_at=50

python -u debug_wandb.py \
    --wandb_experiment_name=$WANDB_EXPERIMENT_NAME \
    --wandb_experiment_id=$WANDB_EXPERIMENT_ID \
    --wandb_resume \
    --step_to_start_at=50 \
    --step_to_end_at=71

wandb sync wandb/$WANDB_EXPERIMENT_ID/wandb/off*
```

Here's the output of both runs (truncated the print(i) calls):

> wandb: Tracking run with wandb version 0.12.14
> wandb: W&B syncing is set to `offline` in this directory.  
> wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
> 0/50
> 1/50
> .
> .
> .
> 49/50
> 
> wandb: Waiting for W&B process to finish... (success).
> wandb:                                                                                
> wandb: 
> wandb: Run history:
> wandb: Train Loss ▂▇▇▃▃▄▂▇▅▂▁▇▃▆▇▁▅▅▇▂▆▃▃▂▂▆▇▂▆▇▅▇▅▃▆▂█▃▅▃
> wandb: 
> wandb: Run summary:
> wandb: Train Loss 0.29312
> wandb: 
> wandb: You can sync this run to the cloud by running:
> wandb: wandb sync ./wandb/2022-12-17_10-29-00/wandb/offline-run-20221217_103128-2022-12-17_10-29-00
> wandb: Find logs at: ./wandb/2022-12-17_10-29-00/wandb/offline-run-20221217_103128-2022-12-17_10-29-00/logs

> wandb: WARNING `resume` will be ignored since W&B syncing is set to `offline`. Starting a new run with run id 2022-12-17_10-29-00.
> wandb: Tracking run with wandb version 0.12.14
> wandb: W&B syncing is set to `offline` in this directory.  
> wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
> 51/71
> 52/71
.
.
.
> 70/71
> 
> wandb: Waiting for W&B process to finish... (success).
> wandb:                                                                                
> wandb: 
> wandb: Run history:
> wandb: Train Loss ▄▂▆▃▁▆▆▅▂▆█▃▃▄▃▅▅█▆▄
> wandb: 
> wandb: Run summary:
> wandb: Train Loss 0.53598
> wandb: 
> wandb: You can sync this run to the cloud by running:
> wandb: wandb sync ./wandb/2022-12-17_10-29-00/wandb/offline-run-20221217_103231-2022-12-17_10-29-00
> wandb: Find logs at: ./wandb/2022-12-17_10-29-00/wandb/offline-run-20221217_103231-2022-12-17_10-29-00/logs

And I only get the first steps again:
![Screenshot from 2022-12-17 10-36-20](https://user-images.githubusercontent.com/25964820/208249733-fee467d0-0e45-4103-936e-c89111d6c3c0.png)

**Comment by thanos-wandb** [comment]
Hi @pratogab just an update here, I've checked your code and reproduce it on my end and it appears the `offline` runs won't resume. There's also a warning message displayed in the stack trace above `wandb: WARNING resume will be ignored since W&B syncing is set to offline`. 

Therefore, you will need to either run them `online` or create a new run-id for the offline runs. We have already a feature request, and I will now increase the requests to our engineering team to allow resuming offline runs. I will close this ticket for now, and we will reach out to you here once there are any updated regarding this feature. 

Thanks so much again for all the information provided, all the best for the new year!

**Comment by MoH-assan** [comment]
Hi any updates on this feature. wandb is still ignoring 'resume' when offline  
`>>> wandb_run = wandb.init(id="dewtee3c",project='SM_H_S',entity='uoft' ,resume="must")
wandb: WARNING `resume` will be ignored since W&B syncing is set to `offline`. Starting a new run with run id dewtee3c.`

**Comment by klieret** [comment]
@thanos-wandb Any updates on this?

**Comment by thanos-wandb** [comment]
@MoH-assan @klieret sorry this slipped through the cracks. There's possibly a way to append the offline run if the following are true:

- You still have the local run folder for the newer run you would like to append to the end of the previous run

- The two runs recorded different steps. So if run_a recorded steps 0-100 and run_b recorded steps 101-200 this would work.

Here is the command you could use to do this: wandb sync --id <first-run's-run-id> --append <path/to/second/run/folder>

Would this option work for your use case?

**Comment by esl-lewis** [comment]
I would like to +1 @klieret , this feature is key to me as my HPC cluster does not allow online wandb runs

**Comment by streethagore** [comment]
I would like to know what is the state of this issue.
I crucially need to resume offline runs on my cluster since it is not connected to internet.

**Comment by jaded0** [comment]
It's still unclear whether this has actually been resolved. Is the run forking, or rewinding, supposed to imitate a resume?

**Comment by skpig** [comment]
Any progress on this feature?

**Comment by bernardo-torres** [comment]
Any updates on this issue?
