### ISSUE TITLE
[Q] Wandb login crashed

### ISSUE THREAD

**Issue by mathbr10** [wandb/wandb#4643]
Hello

For some reason when I try to call wandb login or wandb init I receive the message below:

```
wandb: ERROR Find detailed error logs at: /tmp/debug-cli.matheus.log
Error: Invalid URL: <my-team>
```
The logs are:

```
2022-12-15 07:00:23 ERROR Traceback (most recent call last):
  File "<local-project-path>/venv/lib/python3.8/site-packages/wandb/cli/cli.py", line 97, in wrapper
    return func(*args, **kwargs)
  File "<local-project-path>/venv/lib/python3.8/site-packages/wandb/cli/cli.py", line 236, in login
    wandb.setup(settings=login_settings)
  File "<local-project-path>/venv/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 312, in setup
    ret = _setup(settings=settings)
  File "<local-project-path>/venv/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 307, in _setup
    wl = _WandbSetup(settings=settings)
  File "<local-project-path>/venv/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 293, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "<local-project-path>/venv/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 100, in __init__
    self._settings = self._settings_setup(settings, self._early_logger)
  File "<local-project-path>/venv/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 119, in _settings_setup
    s._apply_config_files(_logger=early_logger)
  File "<local-project-path>/venv/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 1289, in _apply_config_files
    self.update(
  File "<local-project-path>/venv/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 1207, in update
    self.__dict__[key].update(value, source)
  File "<local-project-path>/venv/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 334, in update
    self._value = self._validate(self._preprocess(value))
  File "<local-project-path>/venv/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 295, in _validate
    if not v(value):
  File "<local-project-path>/venv/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 895, in _validate_base_url
    raise UsageError(f"Invalid URL: {value}")
wandb.errors.UsageError: Invalid URL: bb_ai-team

2022-12-15 07:01:29 ERROR Traceback (most recent call last):
  File "<local-project-path>/venv/lib/python3.8/site-packages/wandb/cli/cli.py", line 97, in wrapper
    return func(*args, **kwargs)
  File "<local-project-path>/venv/lib/python3.8/site-packages/wandb/cli/cli.py", line 236, in login
    wandb.setup(settings=login_settings)
  File "<local-project-path>/venv/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 312, in setup
    ret = _setup(settings=settings)
  File "<local-project-path>/venv/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 307, in _setup
    wl = _WandbSetup(settings=settings)
  File "<local-project-path>/venv/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 293, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "<local-project-path>/venv/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 100, in __init__
    self._settings = self._settings_setup(settings, self._early_logger)
  File "<local-project-path>/venv/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 119, in _settings_setup
    s._apply_config_files(_logger=early_logger)
  File "<local-project-path>/venv/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 1289, in _apply_config_files
    self.update(
  File "<local-project-path>/venv/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 1207, in update
    self.__dict__[key].update(value, source)
  File "<local-project-path>/venv/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 334, in update
    self._value = self._validate(self._preprocess(value))
  File "<local-project-path>/venv/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 295, in _validate
    if not v(value):
  File "<local-project-path>/venv/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 895, in _validate_base_url
    raise UsageError(f"Invalid URL: {value}")
wandb.errors.UsageError: Invalid URL: <my-wandb-team>

```
I tryied to uninstall wandb and install it again but the same error persists. Also I created a new vm but got same behavior. What should I do to solve it?

Thanks in advance.

**Comment by lesliewandb** [comment]
Hi @mathbr10, thank you for writing in! Can you send me the code snippet you are using when trying to log in? Also, can you try to completely delete your .netrc and use `wandb login --relogin` and see if that is able to help?

**Comment by mathbr10** [comment]
Hello @lesliewandb I just found the solution. I only need to delete `~/.config/wandb/settings` and call `wandb login` again

**Comment by lesliewandb** [comment]
That's great! I'll close this ticket out then, but I hope you have a beautiful rest of the year :)
