### ISSUE TITLE
[CLI]: `Exception: problem` with `wandb==0.13.6` when launching several jobs on a cluster

### ISSUE THREAD

**Issue by SaulLu** [wandb/wandb#4644]
### Describe the bug

I work on a cluster and very frequently I launch jobs that run in parallel and that use wandb.

With the `wandb==0.13.6` version of wandb and despite the `export WANDB_MODE=offline` flag in my slurm script, I got the following error:
```
Traceback (most recent call last):
  File "/gpfswork/rech/six/commun/conda/envs/m4-user/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1075, in init
    wi.setup(kwargs)
  File "/gpfswork/rech/six/commun/conda/envs/m4-user/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 165, in setup
    self._wl = wandb_setup.setup()
  File "/gpfswork/rech/six/commun/conda/envs/m4-user/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 312, in setup
    ret = _setup(settings=settings)
  File "/gpfswork/rech/six/commun/conda/envs/m4-user/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 307, in _setup
    wl = _WandbSetup(settings=settings)
  File "/gpfswork/rech/six/commun/conda/envs/m4-user/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 293, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/gpfswork/rech/six/commun/conda/envs/m4-user/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 106, in __init__
    self._setup()
  File "/gpfswork/rech/six/commun/conda/envs/m4-user/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 234, in _setup
    self._setup_manager()
  File "/gpfswork/rech/six/commun/conda/envs/m4-user/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 265, in _setup_manager
    self._manager = wandb_manager._Manager(
  File "/gpfswork/rech/six/commun/conda/envs/m4-user/lib/python3.8/site-packages/wandb/sdk/wandb_manager.py", line 111, in __init__
    self._service.start()
  File "/gpfswork/rech/six/commun/conda/envs/m4-user/lib/python3.8/site-packages/wandb/sdk/service/service.py", line 119, in start
    self._launch_server()
  File "/gpfswork/rech/six/commun/conda/envs/m4-user/lib/python3.8/site-packages/wandb/sdk/service/service.py", line 115, in _launch_server
    assert ports_found
AssertionError
wandb: ERROR Abnormal program exit
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /gpfswork/rech/six/commun/conda/envs/m4-user/lib/python3.8/site-packages/wan │
│ db/sdk/wandb_init.py:1075 in init                                            │
│                                                                              │
│   1072 │   except_exit = None                                                │
│   1073 │   try:                                                              │
│   1074 │   │   wi = _WandbInit()                                             │
│ ❱ 1075 │   │   wi.setup(kwargs)                                              │
│   1076 │   │   except_exit = wi.settings._except_exit                        │
│   1077 │   │   try:                                                          │
│   1078 │   │   │   run = wi.init()                                           │
│                                                                              │
│ /gpfswork/rech/six/commun/conda/envs/m4-user/lib/python3.8/site-packages/wan │
│ db/sdk/wandb_init.py:165 in setup                                            │
│                                                                              │
│    162 │   │   │   │   )                                                     │
│    163 │   │   │   │   self.printer.display(line, level="warn")              │
│    164 │   │                                                                 │
│ ❱  165 │   │   self._wl = wandb_setup.setup()                                │
│    166 │   │   # Make sure we have a logger setup (might be an early logger) │
│    167 │   │   _set_logger(self._wl._get_logger())                           │
│    168                                                                       │
│                                                                              │
│ /gpfswork/rech/six/commun/conda/envs/m4-user/lib/python3.8/site-packages/wan │
│ db/sdk/wandb_setup.py:312 in setup                                           │
│                                                                              │
│   309                                                                        │
│   310                                                                        │
│   311 def setup(settings=None) -> Optional["_WandbSetup"]:                   │
│ ❱ 312 │   ret = _setup(settings=settings)                                    │
│   313 │   return ret                                                         │
│   314                                                                        │
│   315                                                                        │
│                                                                              │
│ /gpfswork/rech/six/commun/conda/envs/m4-user/lib/python3.8/site-packages/wan │
│ db/sdk/wandb_setup.py:307 in _setup                                          │
│                                                                              │
│   304 │   │   │   setup_instance._teardown()                                 │
│   305 │   │   _WandbSetup._instance = None                                   │
│   306 │   │   return                                                         │
│ ❱ 307 │   wl = _WandbSetup(settings=settings)                                │
│   308 │   return wl                                                          │
│   309                                                                        │
│   310                                                                        │
│                                                                              │
│ /gpfswork/rech/six/commun/conda/envs/m4-user/lib/python3.8/site-packages/wan │
│ db/sdk/wandb_setup.py:293 in __init__                                        │
│                                                                              │
│   290 │   │   if _WandbSetup._instance and _WandbSetup._instance._pid == pid │
│   291 │   │   │   _WandbSetup._instance._update(settings=settings)           │
│   292 │   │   │   return                                                     │
│ ❱ 293 │   │   _WandbSetup._instance = _WandbSetup__WandbSetup(settings=setti │
│   294 │                                                                      │
│   295 │   def __getattr__(self, name):                                       │
│   296 │   │   return getattr(self._instance, name)                           │
│                                                                              │
│ /gpfswork/rech/six/commun/conda/envs/m4-user/lib/python3.8/site-packages/wan │
│ db/sdk/wandb_setup.py:106 in __init__                                        │
│                                                                              │
│   103 │   │   wandb.termsetup(self._settings, logger)                        │
│   104 │   │                                                                  │
│   105 │   │   self._check()                                                  │
│ ❱ 106 │   │   self._setup()                                                  │
│   107 │   │                                                                  │
│   108 │   │   tracelog_mode = self._settings._tracelog                       │
│   109 │   │   if tracelog_mode:                                              │
│                                                                              │
│ /gpfswork/rech/six/commun/conda/envs/m4-user/lib/python3.8/site-packages/wan │
│ db/sdk/wandb_setup.py:234 in _setup                                          │
│                                                                              │
│   231 │   │   │   print("frozen, could be trouble")                          │
│   232 │                                                                      │
│   233 │   def _setup(self):                                                  │
│ ❱ 234 │   │   self._setup_manager()                                          │
│   235 │   │                                                                  │
│   236 │   │   sweep_path = self._settings.sweep_param_path                   │
│   237 │   │   if sweep_path:                                                 │
│                                                                              │
│ /gpfswork/rech/six/commun/conda/envs/m4-user/lib/python3.8/site-packages/wan │
│ db/sdk/wandb_setup.py:265 in _setup_manager                                  │
│                                                                              │
│   262 │   │   # Temporary setting to allow use of grpc so that we can keep   │
│   263 │   │   # that code from rotting during the transition                 │
│   264 │   │   use_grpc = self._settings._service_transport == "grpc"         │
│ ❱ 265 │   │   self._manager = wandb_manager._Manager(                        │
│   266 │   │   │   _use_grpc=use_grpc, settings=self._settings                │
│   267 │   │   )                                                              │
│   268                                                                        │
│                                                                              │
│ /gpfswork/rech/six/commun/conda/envs/m4-user/lib/python3.8/site-packages/wan │
│ db/sdk/wandb_manager.py:111 in __init__                                      │
│                                                                              │
│   108 │   │                                                                  │
│   109 │   │   token = _ManagerToken.from_environment()                       │
│   110 │   │   if not token:                                                  │
│ ❱ 111 │   │   │   self._service.start()                                      │
│   112 │   │   │   host = "localhost"                                         │
│   113 │   │   │   if _use_grpc:                                              │
│   114 │   │   │   │   transport = "grpc"                                     │
│                                                                              │
│ /gpfswork/rech/six/commun/conda/envs/m4-user/lib/python3.8/site-packages/wan │
│ db/sdk/service/service.py:119 in start                                       │
│                                                                              │
│   116 │   │   │   self._internal_proc = internal_proc                        │
│   117 │                                                                      │
│   118 │   def start(self) -> None:                                           │
│ ❱ 119 │   │   self._launch_server()                                          │
│   120 │                                                                      │
│   121 │   @property                                                          │
│   122 │   def grpc_port(self) -> Optional[int]:                              │
│                                                                              │
│ /gpfswork/rech/six/commun/conda/envs/m4-user/lib/python3.8/site-packages/wan │
│ db/sdk/service/service.py:115 in _launch_server                              │
│                                                                              │
│   112 │   │   │   │   **kwargs,                                              │
│   113 │   │   │   )                                                          │
│   114 │   │   │   ports_found = self._wait_for_ports(fname, proc=internal_pr │
│ ❱ 115 │   │   │   assert ports_found                                         │
│   116 │   │   │   self._internal_proc = internal_proc                        │
│   117 │                                                                      │
│   118 │   def start(self) -> None:                                           │
╰──────────────────────────────────────────────────────────────────────────────╯
AssertionError

The above exception was the direct cause of the following exception:

╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /home/opc/multimodal_exp/repos/m4/m4/training/main.py:146 in <module>        │
│                                                                              │
│   143 │   │   vl_model = model_class.from_pretrained(                        │
│   144 │   │   │   config.resume_param.model_file, config=config.resume_param │
│   145 │   │   )                                                              │
│ ❱ 146 │   trainer = Trainer(                                                 │
│   147 │   │   accelerator=accelerator,                                       │
│   148 │   │   vl_model=vl_model,                                             │
│   149 │   │   tokenizer=tokenizer,                                           │
│                                                                              │
│ /home/opc/multimodal_exp/repos/m4/m4/training/trainer.py:83 in __init__      │
│                                                                              │
│    80 │   │   self._set_model_tflops_per_batch()                             │
│    81 │   │                                                                  │
│    82 │   │   # Init trackers                                                │
│ ❱  83 │   │   self._init_trackers()                                          │
│    84 │   │                                                                  │
│    85 │   │   # Handle jz timing and memory                                  │
│    86 │   │   self.jz_training_time_over = [False]                           │
│                                                                              │
│ /home/opc/multimodal_exp/repos/m4/m4/training/trainer.py:215 in              │
│ _init_trackers                                                               │
│                                                                              │
│   212 │   │   │   │   │   continue                                           │
│   213 │   │   │   │   for key, value in vars(v).items():                     │
│   214 │   │   │   │   │   wdb_config[f"{k}-{key}"] = value                   │
│ ❱ 215 │   │   │   wandb_logger = wandb.init(                                 │
│   216 │   │   │   │   config=wdb_config,                                     │
│   217 │   │   │   │   id=self.hparams.wandb_run_id,                          │
│   218 │   │   │   │   resume="allow",                                        │
│                                                                              │
│ /gpfswork/rech/six/commun/conda/envs/m4-user/lib/python3.8/site-packages/wan │
│ db/sdk/wandb_init.py:1115 in init                                            │
│                                                                              │
│   1112 │   │   │   wandb.termerror("Abnormal program exit")                  │
│   1113 │   │   │   if except_exit:                                           │
│   1114 │   │   │   │   os._exit(-1)                                          │
│ ❱ 1115 │   │   │   raise Exception("problem") from error_seen                │
│   1116 │   return run                                                        │
│   1117                                                                       │
╰──────────────────────────────────────────────────────────────────────────────╯
Exception: problem
```

When going back to a previous version of wandb (`wandb==0.12.21`) the error is gone. 

### Environment

WandB version: 0.13.6

OS: linux

Python version: 3.8

Versions of relevant libraries:

**Comment by lesliewandb** [comment]
Hi @SaulLu, can you tell me what kind of jobs you are running and the environment you are doing these jobs in? Also, can you send over your debug logs found in your wandb run directory please?

**Comment by SaulLu** [comment]
Hi @lesliewandb ,

> can you tell me what kind of jobs you are running and the environment you are doing these jobs in?

Could you tell me what kind of information you would need?  It's DL model training jobs.

>  Also, can you send over your debug logs found in your wandb run directory please?

I'll see if I can track it down.

**Comment by SaulLu** [comment]
> Also, can you send over your debug logs found in your wandb run directory please?

My `debug.log` only contains recent entries in it (added in the last hour and a half), so I don't think it reflects the issue unfortunately.

**Comment by ArtsiomWB** [comment]
Hi @SaulLu!
Sorry for the late response, by what environment you are running this on, Leslie meant are you running this on local or on public cloud?

**Comment by SaulLu** [comment]
Hi @ArtsiomWB,

These jobs were executed on a cluster provided by a cloud provider. The cluster had several compute nodes and the jobs were launched thanks to a job scheduler (SLURM) on the requested resources according to the availability. 

What I think is important to underline is that with such a setup, I could have 2 trainings running on two different nodes but saving their wandb logs on the same disk space.

**Comment by SaulLu** [comment]
Thanks for monitoring this issue.

Unfortunately I haven't had a chance to reproduce the error - I no longer have access to the cluster where I observed this problem and having allocations on another cluster I use is not obvious and I concentrate on performing experiments when I have them. At the moment the only solution I have found is not to upgrade the version of wandb, which is not ideal.

**Comment by kptkin** [comment]
Hi @SaulLu,

Thanks for reporting the issue. We tried to reproduce the issue and our current running hypothesis is that there is something in the start time in certain environments that causes our startup scripts to fail. 
In case you get a chance to run scripts on a clusters to reproduce the issue. Could you help us debug further the issue by doing the following:
- Upgrade to the latest version of wandb (as writing this message it would be 0.13.9)
- You can try increasing the startup time by changing this environment variable (Note this is in seconds) and seeing if this solves your issue. You can do that as follows:
```WANDB__SERVICE_WAIT=300 python your_script.py```
- If you enable this flag it will print  timing information during startup to the stdout (if you have a way to collect stdout and share with us that would further help us narrow down the issue). You can do that as follows:
```_WANDB_STARTUP_DEBUG=true python your_script.py```

Sorry that you are experiencing issue and hopefully we could resolve them soon.
