### ISSUE TITLE
accelerator.end_tracking() generates exception when wandb is used as a tracker

### ISSUE THREAD

**Issue by DuttaSamarpan** [wandb/wandb#4693]
```
Exception in thread SockSrvRdThr:
Traceback (most recent call last):
  File "/Users/samarpandutta/miniforge3/envs/banjo-accelerate-demo/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/Users/samarpandutta/miniforge3/envs/banjo-accelerate-demo/lib/python3.9/site-packages/wandb/sdk/service/server_sock.py", line 112, in run
    shandler(sreq)
  File "/Users/samarpandutta/miniforge3/envs/banjo-accelerate-demo/lib/python3.9/site-packages/wandb/sdk/service/server_sock.py", line 173, in server_record_publish
    iface = self._mux.get_stream(stream_id).interface
  File "/Users/samarpandutta/miniforge3/envs/banjo-accelerate-demo/lib/python3.9/site-packages/wandb/sdk/service/streams.py", line 199, in get_stream
    stream = self._streams[stream_id]
KeyError: '3lxi4eq2'

```

where the key `3lxi4eq2` is actually the wandb run_id

I am initiating the run in this way 
<img width="947" alt="Screenshot 2022-12-24 at 11 45 43 PM" src="https://user-images.githubusercontent.com/104805069/209457252-0097892e-c226-4ac7-9806-9b5e983aae28.png">

and finishing the run in this way
<img width="953" alt="Screenshot 2022-12-24 at 11 47 53 PM" src="https://user-images.githubusercontent.com/104805069/209457292-b2a01611-9ff5-4d83-a26e-a6adf46e0c00.png">

**Comment by DuttaSamarpan** [comment]
I think its an issue with accelerator hence closing it

**Comment by hmartiro** [comment]
I am also experiencing the same error. I think it's worth elaborating on here as the exception code is within wandb. @DuttaSamarpan did you come up with a workaround or fix?

**Comment by hmartiro** [comment]
Tracking here https://github.com/huggingface/accelerate/issues/944
