### ISSUE TITLE
[Q] how to start  a  wandb service on M2

### ISSUE THREAD

**Issue by sheljoy** [wandb/wandb#4742]
run
```bash
wandb server start
```
on MacBook Pro with Apple silicon M2, then get the error message:
```plaintext
Command '['docker', 'inspect', 'wandb/local', '--format', '{{json .RepoDigests}}']' returned non-zero exit status 1.
Unable to find image 'wandb/local:latest' locally
d4c36d7e6810: Download complete
43b41203f3d9: Download complete
4f4fb700ef54: Download complete
e9003da0c56f: Download complete
f4e8bbf61315: Download complete
686284ff2b32: Download complete
907a3ad4d170: Download complete
ef339ad8c941: Download complete
8e058277d049: Download complete
77cd2f2836c7: Download complete
be76333c6717: Download complete
c97818eec16d: Download complete
5993d1583f07: Download complete
b73976ac9f59: Download complete
1f9f9bf2fbd8: Download complete
e5d4882fdf06: Download complete
2b55860d4c66: Download complete
a44ddb3520f9: Download complete
5744e8cffbdc: Download complete
cac814e1eefd: Download complete
0f03750132fd: Download complete
af1787f9dddb: Download complete
aba4be42eb74: Download complete
92b233a93996: Download complete
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
docker: Error response from daemon: platform linux/arm64/v8 not supported.
wandb: ERROR Failed to launch the W&B server container, see the above error.
```

**Comment by lesliewandb** [comment]
Hi @sheljoy, can you try running your code in a [rosetta terminal](https://osxdaily.com/2020/12/04/how-install-rosetta-2-apple-silicon-mac/) and to emulate an older mac? This will help us determine if this bug is due to the processor. Can you tell us more on why you're using the local version of wandb?

**Comment by sheljoy** [comment]
run `wandb server start` in rosetta terminal.
```plaintext
Command '['docker', 'inspect', 'wandb/local', '--format', '{{json .RepoDigests}}']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/opt/envs/base/lib/python3.11/site-packages/wandb/docker/__init__.py", line 209, in image_id
    raise ValueError()
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/envs/base/bin/wandb", line 10, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/envs/base/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/envs/base/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/envs/base/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/envs/base/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/envs/base/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/envs/base/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/envs/base/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/envs/base/lib/python3.11/site-packages/wandb/cli/cli.py", line 97, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/envs/base/lib/python3.11/site-packages/wandb/cli/cli.py", line 1621, in start
    local_image_sha = wandb.docker.image_id("wandb/local").split("wandb/local")[-1]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/envs/base/lib/python3.11/site-packages/wandb/docker/__init__.py", line 213, in image_id
    return image_id_from_registry(image_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/envs/base/lib/python3.11/site-packages/wandb/docker/__init__.py", line 182, in image_id_from_registry
    token = auth_token(registry, repository).get("token")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/envs/base/lib/python3.11/site-packages/wandb/docker/__init__.py", line 140, in auth_token
    auth_info = auth_config.resolve_authconfig(registry)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/envs/base/lib/python3.11/site-packages/wandb/docker/auth.py", line 288, in resolve_authconfig
    cfg = self._resolve_authconfig_credstore(registry, store_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/envs/base/lib/python3.11/site-packages/wandb/docker/auth.py", line 317, in _resolve_authconfig_credstore
    store = self._get_store_instance(credstore_name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/envs/base/lib/python3.11/site-packages/wandb/docker/auth.py", line 336, in _get_store_instance
    self._stores[name] = dockerpycreds.Store(
                         ^^^^^^^^^^^^^^^^^^^^
  File "/opt/envs/base/lib/python3.11/site-packages/dockerpycreds/store.py", line 23, in __init__
    raise errors.InitializationError(
dockerpycreds.errors.InitializationError: docker-credential-desktop not installed or not available in PATH
```

**Comment by lesliewandb** [comment]
Thank you for this! Can you try to either:
1. try installing a compatible (with their configuration) docker version on their machine and try starting the server again? Or,
2. try out this for docker (without compose): docker run --platform linux/x86_64 mysql --rm -d -v wandb:/vol -p 8080:8080 --name wandb-local wandb/local or try adding platform to their services in the yaml file for ex:
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    
You might have a docker incompatible version. If so, this should be able to help

**Comment by sheljoy** [comment]
wandb 0.13.9 is nice.
```plaintext
docker pull wandb/local
Using default tag: latest
8e058277d049: Already exists
4f4fb700ef54: Already exists
cac814e1eefd: Already exists
84ff7d0716c8: Already exists
c1b169f4b545: Already exists
2b55860d4c66: Already exists
7a42fa02e081: Already exists
b918b7452c70: Already exists
ba763db94302: Already exists
b1abe44486e2: Already exists
c624f5d13b82: Already exists
384777338554: Already exists
9fcb48974b96: Already exists
30942af76f2f: Download complete
d0622fd30719: Download complete
636d8004bed3: Download complete
7a873044f57b: Download complete
facc65aa382e: Download complete
ba63e22587a5: Download complete
65094b1fba18: Download complete
05f4743a7169: Download complete
a8a8af81a834: Download complete
897aeb82c93e: Download complete
docker.io/wandb/local:latest
```


```bash
wandb server start
```
```plaintext
wandb: W&B server started at http://localhost:8080 🚀
wandb: You can stop the server by running `wandb server stop`
wandb: You can find your API key in your browser here: http://localhost:8080/authorize
wandb: Paste an API key from your profile and hit enter, or press ctrl+c to quit:
zsh: suspended  wandb server star
```
