### ISSUE TITLE
[Q] Free up temporary space

### ISSUE THREAD

**Issue by 2er0** [wandb/wandb#4805]
Is there a way to delete/clean temporary folders created by W&B to upload images to the W&B server?

I ran a couple of times into an out-of-space exception (OSError) on a shared machine.

Example for an experiment run with multiple executions:
```python
for _ in range(X):
    wandb.init(…, reinit=True)
    …
    # do training and logging
    wandb.log({"image": fig})
    …
    wandb.finish()
```

**Comment by 2er0** [comment]
OK, maybe some things needed to be clarified.

The code is a simplified example of running an experiment with the same or different configurations multiple times. 
The problem is that the folder containing the logs and images of an experiment run (one step in the loop) is stored in a distributed filesystem in my setup and has no space limits. But, during the sync of the log and the images, a temporary folder in the filesystem gets created to upload the images to the W&B server. This is locally on a machine in the cluster and outside my control. 

Could it be that temporary content for the upload to the W&B server is not directly cleaned after upload?

This is an example of the error that I get:
```
Traceback (most recent call last):
  File "/…/lib/python3.9/logging/__init__.py", line 1087, in emit
    self.flush()
  File "/…/lib/python3.9/logging/__init__.py", line 1067, in flush
    self.stream.flush()
OSError: [Errno 28] No space left on device
Call stack:
  File "/…/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
  File "/…/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/…/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 67, in run
    success = self.push()
  File "/…/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 143, in push
    logger.info("Uploaded file %s", self.save_path)
Message: 'Uploaded file %s'
Arguments: ('/tmp/tmp80tjxis3wandb/nr1dladx-media/images/after_training_251_de80e82534744aa63f7b.png',)
--- Logging error ---
Traceback (most recent call last):
  File "/…/lib/python3.9/logging/__init__.py", line 1087, in emit
    self.flush()
  File "/…/lib/python3.9/logging/__init__.py", line 1067, in flush
    self.stream.flush()
OSError: [Errno 28] No space left on device
Call stack:
  File "/…/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
  File "/…/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/…/lib/python3.9/site-packages/wandb/vendor/watchdog_0_9_0/wandb_watchdog/observers/api.py", line 199, in run
    self.dispatch_events(self.event_queue, self.timeout)
  File "/…/lib/python3.9/site-packages/wandb/vendor/watchdog_0_9_0/wandb_watchdog/observers/api.py", line 368, in dispatch_events
    handler.dispatch(event)
  File "/…/lib/python3.9/site-packages/wandb/vendor/watc%
```

**Comment by 2er0** [comment]
Ok, since the `requests` package is used to upload images to the wandb servers, there is not much in addition I can do. I already clean up the local log storage in my code.
