### ISSUE TITLE
[Q] Internal process shutdown.

### ISSUE THREAD

**Issue by LiriFang** [wandb/wandb#4842]
Hi,

I keep getting the shutdown as follows. I ran the same scripts in Linux without error. However, I keep getting the internal process exited when running the scripts in Windows.

I would appreciate any help!

2023-01-25 07:24:08,865 INFO    MainThread:1112 [internal.py:wandb_internal():90] W&B internal server running at pid: 1112, started at: 2023-01-25 07:24:08.864165
2023-01-25 07:24:08,867 INFO    WriterThread:1112 [datastore.py:open_for_write():75] open: C:\Users\..\wandb\offline-run-20230125_072407-1yif3f7e\run-1yif3f7e.wandb
2023-01-25 07:24:08,868 DEBUG   HandlerThread:1112 [handler.py:handle_request():141] handle_request: run_start
2023-01-25 07:24:08,897 DEBUG   HandlerThread:1112 [meta.py:__init__():35] meta init
2023-01-25 07:24:08,897 DEBUG   HandlerThread:1112 [meta.py:__init__():49] meta init done
2023-01-25 07:24:08,897 DEBUG   HandlerThread:1112 [meta.py:probe():209] probe
2023-01-25 07:24:08,906 DEBUG   HandlerThread:1112 [meta.py:_setup_git():199] setup git
2023-01-25 07:24:09,083 DEBUG   HandlerThread:1112 [meta.py:_setup_git():206] setup git done
2023-01-25 07:24:09,083 DEBUG   HandlerThread:1112 [meta.py:_save_pip():53] save pip
2023-01-25 07:24:09,083 DEBUG   HandlerThread:1112 [meta.py:_save_pip():67] save pip done
2023-01-25 07:24:09,083 DEBUG   HandlerThread:1112 [meta.py:_save_conda():74] save conda
2023-01-25 07:24:14,128 DEBUG   HandlerThread:1112 [meta.py:_save_conda():84] save conda done
2023-01-25 07:24:14,128 DEBUG   HandlerThread:1112 [meta.py:probe():247] probe done
2023-01-25 07:24:17,948 WARNING MainThread:1112 [internal.py:is_dead():387] Internal process exiting, parent pid 12504 disappeared
2023-01-25 07:24:17,948 ERROR   MainThread:1112 [internal.py:wandb_internal():149] Internal process shutdown.
2023-01-25 07:24:18,286 INFO    WriterThread:1112 [datastore.py:close():279] close: C:\Users\..\wandb\offline-run-20230125_072407-1yif3f7e\run-1yif3f7e.wandb
2023-01-25 07:24:18,286 INFO    HandlerThread:1112 [handler.py:finish():806] shutting down handler
2023-01-25 07:24:18,961 INFO    SenderThread:1112 [sender.py:finish():1106] shutting down sender
2023-01-25 07:24:18,961 INFO    MainThread:1112 [internal.py:handle_exit():80] Internal process exited

**Comment by LiriFang** [comment]
It seems to be related to the subprocess.

2023-01-25 07:38:52,670 INFO    MainThread:6724 [internal.py:wandb_internal():90] W&B internal server running at pid: 6724, started at: 2023-01-25 07:38:52.669981
2023-01-25 07:38:52,671 INFO    WriterThread:6724 [datastore.py:open_for_write():75] open: C:\Users\..\wandb\offline-run-20230125_073851-1m0kporq\run-1m0kporq.wandb
2023-01-25 07:38:52,672 DEBUG   HandlerThread:6724 [handler.py:handle_request():141] handle_request: run_start
2023-01-25 07:38:52,698 DEBUG   HandlerThread:6724 [meta.py:__init__():35] meta init
2023-01-25 07:38:52,698 DEBUG   HandlerThread:6724 [meta.py:__init__():49] meta init done
2023-01-25 07:38:52,699 DEBUG   HandlerThread:6724 [meta.py:probe():209] probe
2023-01-25 07:38:52,713 DEBUG   HandlerThread:6724 [meta.py:_setup_git():199] setup git
2023-01-25 07:38:52,891 DEBUG   HandlerThread:6724 [meta.py:_setup_git():206] setup git done
2023-01-25 07:38:52,891 DEBUG   HandlerThread:6724 [meta.py:_save_pip():53] save pip
2023-01-25 07:38:52,893 DEBUG   HandlerThread:6724 [meta.py:_save_pip():67] save pip done
2023-01-25 07:38:52,893 DEBUG   HandlerThread:6724 [meta.py:_save_conda():74] save conda
2023-01-25 07:38:52,896 ERROR   HandlerThread:6724 [meta.py:_save_conda():83] Error saving conda packages
Traceback (most recent call last):
  File "C:\Users\..\Anaconda3\envs\cv\lib\site-packages\wandb\sdk\internal\meta.py", line 79, in _save_conda
    subprocess.call(
  File "C:\Users\..\Anaconda3\envs\cv\lib\subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\..\Anaconda3\envs\cv\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\..\Anaconda3\envs\cv\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
2023-01-25 07:38:52,896 DEBUG   HandlerThread:6724 [meta.py:_save_conda():84] save conda done
2023-01-25 07:38:52,896 DEBUG   HandlerThread:6724 [meta.py:probe():247] probe done
2023-01-25 07:39:01,733 WARNING MainThread:6724 [internal.py:is_dead():387] Internal process exiting, parent pid 8008 disappeared
2023-01-25 07:39:01,733 ERROR   MainThread:6724 [internal.py:wandb_internal():149] Internal process shutdown.
2023-01-25 07:39:02,098 INFO    WriterThread:6724 [datastore.py:close():279] close: C:\Users\..\wandb\offline-run-20230125_073851-1m0kporq\run-1m0kporq.wandb
2023-01-25 07:39:02,098 INFO    HandlerThread:6724 [handler.py:finish():806] shutting down handler
2023-01-25 07:39:02,751 INFO    SenderThread:6724 [sender.py:finish():1106] shutting down sender
2023-01-25 07:39:02,751 INFO    MainThread:6724 [internal.py:handle_exit():80] Internal process exited
