### ISSUE TITLE
[CLI]: Sync raises KeyError: 'step'

### ISSUE THREAD

**Issue by mertozlutiras** [wandb/wandb#4857]
### Describe the bug

```python

# one line command
WandbLogger.sync()

# passing optional parameters
WandbLogger.sync(
    id=None,
    n_fine_tunes=None,
    project="gpt-3",
    **kwargs_wandb_init
)


```

```shell

KeyError                                  Traceback (most recent call last)
Input In [283], in <cell line: 4>()
      1 # THIS IS TO SYNC ALL THE PAST TO WANDB 
      2 
      3 # one line command
----> 4 WandbLogger.sync()
      6 # passing optional parameters
      7 WandbLogger.sync(
      8     id=None,
      9     n_fine_tunes=None,
     10     project="gpt-3",
     11     **kwargs_wandb_init
     12 )

File ~/opt/anaconda3/lib/python3.9/site-packages/openai/wandb_logger.py:73, in WandbLogger.sync(cls, id, n_fine_tunes, project, entity, force, **kwargs_wandb_init)
     69 # log starting from oldest fine_tune
     70 show_individual_warnings = (
     71     False if id is None and n_fine_tunes is None else True
     72 )
---> 73 fine_tune_logged = [
     74     cls._log_fine_tune(
     75         fine_tune,
     76         project,
     77         entity,
     78         force,
     79         show_individual_warnings,
     80         **kwargs_wandb_init,
     81     )
     82     for fine_tune in fine_tunes
     83 ]
     85 if not show_individual_warnings and not any(fine_tune_logged):
     86     print("No new successful fine-tunes were found")

File ~/opt/anaconda3/lib/python3.9/site-packages/openai/wandb_logger.py:74, in <listcomp>(.0)
     69 # log starting from oldest fine_tune
     70 show_individual_warnings = (
     71     False if id is None and n_fine_tunes is None else True
     72 )
     73 fine_tune_logged = [
---> 74     cls._log_fine_tune(
     75         fine_tune,
     76         project,
     77         entity,
     78         force,
     79         show_individual_warnings,
     80         **kwargs_wandb_init,
     81     )
     82     for fine_tune in fine_tunes
     83 ]
     85 if not show_individual_warnings and not any(fine_tune_logged):
     86     print("No new successful fine-tunes were found")

File ~/opt/anaconda3/lib/python3.9/site-packages/openai/wandb_logger.py:162, in WandbLogger._log_fine_tune(cls, fine_tune, project, entity, force, show_individual_warnings, **kwargs_wandb_init)
    160 for _, row in df_results.iterrows():
    161     metrics = {k: v for k, v in row.items() if not np.isnan(v)}
--> 162     step = metrics.pop("step")
    163     if step is not None:
    164         step = int(step)

KeyError: 'step'

```

### Environment

WandB version:  0.13.9

OS: MacOS

Python version: 3.10

Versions of relevant libraries:

openai                        0.26.3

**Comment by luisbergua** [comment]
Hi @mertozlutiras, thanks a lot for reporting this! I can see you're integrating `wandb` with `openai`. Could you please share with me a code snippet of what are you running before this error raises?

**Comment by mkleijn** [comment]
I have a similar issue running Windows 11 with Python 3.11:

openai wandb sync -i  ft-_redacted_

```
wandb: Currently logged in as: m<redacted> (<redacted>). Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.13.9
wandb: Run data is saved locally in C:\Users\M<redacted>\wandb\run-20230130_135720-ft-<redacted>
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run ft-<redacted>
wandb:  View project at https://wandb.ai/<redacted>/GPT-3
wandb:  View run at https://wandb.ai/<redacted>/GPT-3/runs/ft-<redacted>
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\<redacted>\AppData\Local\Programs\Python\Python311\Scripts\openai.exe\__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\Users\<redacted>\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\_openai_scripts.py", line 63, in main
    args.func(args)
  File "C:\Users\<redacted>\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\cli.py", line 527, in sync
    resp = openai.wandb_logger.WandbLogger.sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<redacted>\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\wandb_logger.py", line 73, in sync
    fine_tune_logged = [
                       ^
  File "C:\Users\<redacted>\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\wandb_logger.py", line 74, in <listcomp>
    cls._log_fine_tune(
  File "C:\Users\<redacted>\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\wandb_logger.py", line 162, in _log_fine_tune
    step = metrics.pop("step")
           ^^^^^^^^^^^^^^^^^^^
KeyError: 'step'
wandb: Waiting for W&B process to finish... (failed 1). Press Ctrl-C to abort syncing.
wandb:  View run ft-<redacted> at: https://wandb.ai/<redacted>/GPT-3/runs/ft-<redacted>
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: .\wandb\run-20230130_135720-ft-<redacted>\logs

```

**Comment by luisbergua** [comment]
Hi @mertozlutiras @mkleijn! Could you please share a full code example and so I can try to reproduce this? I'm not getting the same error as you do when running this. Also, did you notice this issue appearing in any concrete version?

**Comment by mertozlutiras-hyrd** [comment]
I'm finetuning some openai models and then run the WandbLogger.sync() as previously shared. What can I share as a full code example? What do you mean by concrete version?

**Comment by luisbergua** [comment]
Hi @mertozlutiras, thanks for explaining this! And sorry for not being clear, with concrete version I mean the version of the `wandb` package, could you please share with me what version are you using and if you noticed this issue appearing after upgrading to any version or have you been experiencing this for a long time? Thanks!

**Comment by mkleijn** [comment]
@mertozlutiras @luisbergua i was able to remedy it just now by running "pip install openai --upgrade" to upgrade from openai-0.26.1 to openai-0.26.4

Maybe some dependency got updated that fixed it, not sure. But my sync to WandB now completed succesfully.

**Comment by luisbergua** [comment]
Hi @mkleijn, thanks for sharing this! @mertozlutiras could you please try upgrading `openai` and see if it works?

**Comment by kptkin** [comment]
@mkleijn since we haven't heard from you we are closing this issue. If you still experience this issue, feel free to re-open this issue.
