### ISSUE TITLE
[CLI]: 

### ISSUE THREAD

**Issue by bwassim** [wandb/wandb#4918]
### Describe the bug
I am having the error below when I try to run wandb locally

```
wandb server start

```

```shell
(C:\ProgramData\MiniforgeEnvs\tf) C:\WINDOWS\system32>wandb server start
Traceback (most recent call last):
  File "C:\ProgramData\MiniforgeEnvs\tf\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\MiniforgeEnvs\tf\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\MiniforgeEnvs\tf\Scripts\wandb.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\MiniforgeEnvs\tf\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\ProgramData\MiniforgeEnvs\tf\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\ProgramData\MiniforgeEnvs\tf\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\ProgramData\MiniforgeEnvs\tf\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\ProgramData\MiniforgeEnvs\tf\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\ProgramData\MiniforgeEnvs\tf\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\ProgramData\MiniforgeEnvs\tf\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\ProgramData\MiniforgeEnvs\tf\lib\site-packages\wandb\cli\cli.py", line 102, in wrapper
    return func(*args, **kwargs)
  File "C:\ProgramData\MiniforgeEnvs\tf\lib\site-packages\wandb\cli\cli.py", line 1651, in start
    registry_image_sha = wandb.docker.image_id_from_registry("wandb/local").split(
AttributeError: 'NoneType' object has no attribute 'split'
```

### Environment

WandB version: 0.13.9

OS: Windows 10 Ent.

Python version: 3.9.15

Versions of relevant libraries:

**Comment by MBakirWB** [comment]
Hi @bwassim, happy to help. This error indicates that wandb was unable to resolve the docker id of our image from the [docker repo](https://hub.docker.com/u/wandb) when we pull our image to your local machine. This may be a network related issue. Are you connected to the internet? Do you have any firewall/proxy settings configured that prevent http requests?

**Comment by bwassim** [comment]
There is a good chance this is the case since I am using my work laptop.

**Comment by MBakirWB** [comment]
Hi @bwassim , wanted to follow up with your on this issue you were facing. Are you still encountering difficulty with launching wandb locally?

**Comment by bwassim** [comment]
Hello @MBakirWB, thanks for asking. Actually I stopped trying since I couldn't figure this out.

**Comment by MBakirWB** [comment]
Hi @bwassim , thank you for the update. You could try the following docker commands:

```
docker pull wandb/local:latest
docker run --rm -d -v wandb:/vol -p 8080:8080 --name wandb-local wandb/local:latest
```
Which if successful in pulling the image will make it accessible through `http://localhost:8080/`

**Comment by MBakirWB** [comment]
Hi @bwassim  since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by agranadosb** [comment]
Hi @MBakirWB, I had the same issue. After executing `docker pull wandb/local:latest` the error was gone.
