### ISSUE TITLE
[Q] Change staging dir

### ISSUE THREAD

**Issue by shenoynikhil** [wandb/wandb#5055]
Currently when the run ends I am getting this error trace. I think it's because I do not have write access to where the staging directory is selected by default. How do I change that?

```python
Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
Thread SenderThread:
Traceback (most recent call last):
  File "/arc/project/st-jiaruid-1/miniconda3/envs/mrl-2/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 49, in run
    self._run()
  File "/arc/project/st-jiaruid-1/miniconda3/envs/mrl-2/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 100, in _run
    self._process(record)
  File "/arc/project/st-jiaruid-1/miniconda3/envs/mrl-2/lib/python3.8/site-packages/wandb/sdk/internal/internal.py", line 329, in _process
    self._sm.send(record)
  File "/arc/project/st-jiaruid-1/miniconda3/envs/mrl-2/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 343, in send
    send_handler(record)
  File "/arc/project/st-jiaruid-1/miniconda3/envs/mrl-2/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 365, in send_request
    send_handler(record)
  File "/arc/project/st-jiaruid-1/miniconda3/envs/mrl-2/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 615, in send_request_defer
    self._flush_job()
  File "/arc/project/st-jiaruid-1/miniconda3/envs/mrl-2/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 1567, in _flush_job
    artifact = self._job_builder.build()
  File "/arc/project/st-jiaruid-1/miniconda3/envs/mrl-2/lib/python3.8/site-packages/wandb/sdk/internal/job_builder.py", line 214, in build
    f.write(json.dumps(source_info, indent=4))
  File "/arc/project/st-jiaruid-1/miniconda3/envs/mrl-2/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/arc/project/st-jiaruid-1/miniconda3/envs/mrl-2/lib/python3.8/site-packages/wandb/sdk/wandb_artifacts.py", line 412, in new_file
    self.add_file(path, name=name)
  File "/arc/project/st-jiaruid-1/miniconda3/envs/mrl-2/lib/python3.8/site-packages/wandb/sdk/wandb_artifacts.py", line 433, in add_file
    return self._add_local_file(name, local_path, digest=digest)
  File "/arc/project/st-jiaruid-1/miniconda3/envs/mrl-2/lib/python3.8/site-packages/wandb/sdk/wandb_artifacts.py", line 749, in _add_local_file
    with get_new_staging_file() as f:
  File "/arc/project/st-jiaruid-1/miniconda3/envs/mrl-2/lib/python3.8/site-packages/wandb/sdk/interface/artifacts.py", line 999, in get_new_staging_file
    return tempfile.NamedTemporaryFile(dir=get_staging_dir(), delete=False)
  File "/arc/project/st-jiaruid-1/miniconda3/envs/mrl-2/lib/python3.8/site-packages/wandb/sdk/interface/artifacts.py", line 994, in get_staging_dir
    filesystem.mkdir_exists_ok(path)
  File "/arc/project/st-jiaruid-1/miniconda3/envs/mrl-2/lib/python3.8/site-packages/wandb/sdk/lib/filesystem.py", line 18, in mkdir_exists_ok
    raise PermissionError(f"{dir_name!s} is not writable")
PermissionError: /home/shenoy/.local/share/wandb/artifacts/staging is not writable
wandb: ERROR Internal wandb error: file data was not synced
```

**Comment by shenoynikhil** [comment]
I think I found the issue, I need to change the `env` variable `WANDB_DATA_DIR`.

**Comment by billmdevs** [comment]
Thank you @shenoynikhil for letting us know the solution to your issue. I will be closing it now. If you have any other issue in the future please feel free to contact us!

**Comment by moredatarequired** [comment]
@shenoynikhil thanks for reporting! @billmdevs it seems like we can do a little better reporting on this error message; I'm submitting https://github.com/wandb/wandb/pull/5067 to prevent this from being confusing in the future.

**Comment by off99555** [comment]
Hey I also I have error No enough space with OS error, can you also add

> @shenoynikhil thanks for reporting! @billmdevs it seems like we can do a little better reporting on this error message; I'm submitting #5067 to prevent this from being confusing in the future.

Hi, I also I have **OS Error: No enough space error** on a cloud machine, can you also add instructive message to tell users how to change the folder for wandb cache folder?

**Comment by moredatarequired** [comment]
Hi @billmdevs , the free space issue is in JIRA as https://wandb.atlassian.net/browse/WB-12643; I don't know the timeline for getting to it, unfortunately.
