### ISSUE TITLE
[Q] wandb version compatibility with protobuf

### ISSUE THREAD

**Issue by Yoonho-Na** [wandb/wandb#5069]
Hi I need to install wandb that is compatible with protobuf==3.9.2

How can I find the correct version?

**Comment by luisbergua** [comment]
Hi @Yoonho-Na, thanks for writing in! May I ask about your use case here? This is a really old version so many new features and fixes won't work on that version so I'd try to find a workaround if possible. In case this isn't possible, you can have a look at the [history](https://github.com/wandb/wandb/commits/main/requirements.txt) of `requirements.txt `. For your concrete case, `protobuf>=3.12.0` was added [here](https://github.com/wandb/wandb/blob/9e054de251d7a8c56cf95466d523425fb112af69/requirements.txt) so you need to use the [previous version](https://github.com/wandb/wandb/releases/tag/v0.9.3) (in this case `0.9.3`). Please let me know if this helps!

**Comment by dp-0809** [comment]
Hi，
I installed the wandb 0.12.21 and protobuf 3.20.1，but the error reported like: from wandb.proto import wandb_internal_pb2 as pb

**Comment by michelgokan** [comment]
I have a similar problem:

```
$ wandb login 

Traceback (most recent call last):
  File "/opt/homebrew/bin/wandb", line 5, in <module>
    from wandb.cli.cli import cli
  File "/opt/homebrew/lib/python3.9/site-packages/wandb/__init__.py", line 26, in <module>
    from wandb import sdk as wandb_sdk
  File "/opt/homebrew/lib/python3.9/site-packages/wandb/sdk/__init__.py", line 9, in <module>
    from .wandb_init import _attach, init  # noqa: F401
  File "/opt/homebrew/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 27, in <module>
    from . import wandb_login, wandb_setup
  File "/opt/homebrew/lib/python3.9/site-packages/wandb/sdk/wandb_login.py", line 23, in <module>
    from .wandb_settings import Settings, Source
  File "/opt/homebrew/lib/python3.9/site-packages/wandb/sdk/wandb_settings.py", line 38, in <module>
    from wandb.sdk.wandb_setup import _EarlyLogger
  File "/opt/homebrew/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 28, in <module>
    from . import wandb_manager
  File "/opt/homebrew/lib/python3.9/site-packages/wandb/sdk/wandb_manager.py", line 12, in <module>
    from wandb.sdk.lib.proto_util import settings_dict_from_pbmap
  File "/opt/homebrew/lib/python3.9/site-packages/wandb/sdk/lib/proto_util.py", line 7, in <module>
    from wandb.proto import wandb_internal_pb2 as pb
  File "/opt/homebrew/lib/python3.9/site-packages/wandb/proto/wandb_internal_pb2.py", line 15, in <module>
    from wandb.proto import wandb_base_pb2 as wandb_dot_proto_dot_wandb__base__pb2
  File "/opt/homebrew/lib/python3.9/site-packages/wandb/proto/wandb_base_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/opt/homebrew/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

**Comment by pvtien96** [comment]
I have a similar problem:
```bash
(base) [van-tien.pham@X SVP]$ wandb login
Traceback (most recent call last):
  File "/home/van-tien.pham/anaconda3/bin/wandb", line 5, in <module>
    from wandb.cli.cli import cli
  File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/wandb/__init__.py", line 27, in <module>
    from wandb import sdk as wandb_sdk
  File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/wandb/sdk/__init__.py", line 25, in <module>
    from .artifacts.artifact import Artifact
  File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/wandb/sdk/artifacts/artifact.py", line 46, in <module>
    from wandb.apis.normalize import normalize_exceptions
  File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/wandb/apis/__init__.py", line 43, in <module>
    from .internal import Api as InternalApi  # noqa
  File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/wandb/apis/internal.py", line 3, in <module>
    from wandb.sdk.internal.internal_api import Api as InternalApi
  File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 48, in <module>
    from ..lib import retry
  File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 17, in <module>
    from .mailbox import ContextCancelledError
  File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 10, in <module>
    from wandb.proto import wandb_internal_pb2 as pb
  File "/home/van-tien.pham/anaconda3/lib/python3.9/site-packages/wandb/proto/wandb_internal_pb2.py", line 3, in <module>
    protobuf_version = google.protobuf.__version__[0]
AttributeError: module 'google.protobuf' has no attribute '__version__'
```
