### ISSUE TITLE
[CLI]: Bug in WandbCallbackHandler in `langchain` 

### ISSUE THREAD

**Issue by arkinyaara** [wandb/wandb#5212]
### Describe the bug

in `WandbCallbackHandler.on_chain_start` (row 533 in wandb_callback.py), the name of the input key is hardcoded set to "input" and the name of the output key is hard-coded "output", so if the chain uses any other name for the input key, this results in `KyeError`.

```python

```

```shell
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1448, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "use_wandb.py", line 21, in <module>
    res = intenter.get_intent(IntenterInput(query="hi there"))
  File "intenter.py", line 183, in get_intent
    result = self.full_chain(inputs.dict())
  File ".venv/lib/python3.9/site-packages/langchain/chains/base.py", line 107, in __call__
    self.callback_manager.on_chain_start(
  File "venv/lib/python3.9/site-packages/langchain/callbacks/base.py", line 184, in on_chain_start
    handler.on_chain_start(serialized, inputs, **kwargs)
  File ".venv/lib/python3.9/site-packages/langchain/callbacks/wandb_callback.py", line 533, in on_chain_start
    chain_input = inputs["input"]
KeyError: 'input'
python-BaseException
```

### Environment

WandB version: wandb==0.14.0

OS: macOS big sur

Python version: 3.9.9

Versions of relevant libraries: langchain==0.0.118

**Comment by arkinyaara** [comment]
Hi, this issue is a duplicate of [this](https://github.com/hwchase17/langchain/issues/1884), I'll close the issue.
Thanks for the quick response.
