### ISSUE TITLE
Error: Timed out waiting for wandb service to start after 30.0 seconds. Try increasing the timeout with the `_service_wait` setting.

### ISSUE THREAD

**Issue by FONSECV** [wandb/wandb#5214]
I cannot login to the library. The first time I tried to log in it worked and then I tried to use sweeps and this error appeared. I've reinstalled the library, delete the wandb line in .netrc file to logout, and unset the WANDB_API_KEY. Then, I tried to log in again but the error persists.

2023-03-22 16:08:49 ERROR Traceback (most recent call last):
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/cli/cli.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/cli/cli.py", line 243, in login
    wandb.setup(settings=login_settings)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 327, in setup
    ret = _setup(settings=settings)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 320, in _setup
    wl = _WandbSetup(settings=settings)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 303, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 114, in __init__
    self._setup()
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 250, in _setup
    self._setup_manager()
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 277, in _setup_manager
    self._manager = wandb_manager._Manager(settings=self._settings)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_manager.py", line 146, in __init__
    self._service.start()
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/service/service.py", line 199, in start
    self._launch_server()
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/service/service.py", line 193, in _launch_server
    sentry_reraise(e, delay=True)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/util.py", line 214, in sentry_reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/service/service.py", line 191, in _launch_server
    self._wait_for_ports(fname, proc=internal_proc)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/service/service.py", line 141, in _wait_for_ports
    raise ServiceStartTimeoutError(
wandb.sdk.service.service.ServiceStartTimeoutError: Timed out waiting for wandb service to start after 30.0 seconds. Try increasing the timeout with the `_service_wait` setting.

2023-03-22 16:32:06 ERROR Traceback (most recent call last):
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/cli/cli.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/cli/cli.py", line 243, in login
    wandb.setup(settings=login_settings)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 327, in setup
    ret = _setup(settings=settings)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 320, in _setup
    wl = _WandbSetup(settings=settings)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 303, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 114, in __init__
    self._setup()
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 250, in _setup
    self._setup_manager()
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 277, in _setup_manager
    self._manager = wandb_manager._Manager(settings=self._settings)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_manager.py", line 146, in __init__
    self._service.start()
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/service/service.py", line 199, in start
    self._launch_server()
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/service/service.py", line 193, in _launch_server
    sentry_reraise(e, delay=True)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/util.py", line 214, in sentry_reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/service/service.py", line 191, in _launch_server
    self._wait_for_ports(fname, proc=internal_proc)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/service/service.py", line 141, in _wait_for_ports
    raise ServiceStartTimeoutError(
wandb.sdk.service.service.ServiceStartTimeoutError: Timed out waiting for wandb service to start after 30.0 seconds. Try increasing the timeout with the `_service_wait` setting.

2023-03-22 17:08:50 ERROR Traceback (most recent call last):
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/cli/cli.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/cli/cli.py", line 243, in login
    wandb.setup(settings=login_settings)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 327, in setup
    ret = _setup(settings=settings)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 320, in _setup
    wl = _WandbSetup(settings=settings)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 303, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 114, in __init__
    self._setup()
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 250, in _setup
    self._setup_manager()
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 277, in _setup_manager
    self._manager = wandb_manager._Manager(settings=self._settings)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_manager.py", line 146, in __init__
    self._service.start()
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/service/service.py", line 199, in start
    self._launch_server()
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/service/service.py", line 193, in _launch_server
    sentry_reraise(e, delay=True)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/util.py", line 214, in sentry_reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/service/service.py", line 191, in _launch_server
    self._wait_for_ports(fname, proc=internal_proc)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/service/service.py", line 141, in _wait_for_ports
    raise ServiceStartTimeoutError(
wandb.sdk.service.service.ServiceStartTimeoutError: Timed out waiting for wandb service to start after 30.0 seconds. Try increasing the timeout with the `_service_wait` setting.

2023-03-22 17:14:50 ERROR Traceback (most recent call last):
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/cli/cli.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/cli/cli.py", line 243, in login
    wandb.setup(settings=login_settings)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 327, in setup
    ret = _setup(settings=settings)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 320, in _setup
    wl = _WandbSetup(settings=settings)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 303, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 114, in __init__
    self._setup()
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 250, in _setup
    self._setup_manager()
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 277, in _setup_manager
    self._manager = wandb_manager._Manager(settings=self._settings)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_manager.py", line 146, in __init__
    self._service.start()
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/service/service.py", line 199, in start
    self._launch_server()
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/service/service.py", line 193, in _launch_server
    sentry_reraise(e, delay=True)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/util.py", line 214, in sentry_reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/service/service.py", line 191, in _launch_server
    self._wait_for_ports(fname, proc=internal_proc)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/service/service.py", line 141, in _wait_for_ports
    raise ServiceStartTimeoutError(
wandb.sdk.service.service.ServiceStartTimeoutError: Timed out waiting for wandb service to start after 30.0 seconds. Try increasing the timeout with the `_service_wait` setting.

2023-03-22 17:20:40 ERROR Traceback (most recent call last):
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/cli/cli.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/cli/cli.py", line 243, in login
    wandb.setup(settings=login_settings)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 327, in setup
    ret = _setup(settings=settings)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 320, in _setup
    wl = _WandbSetup(settings=settings)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 303, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 114, in __init__
    self._setup()
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 250, in _setup
    self._setup_manager()
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 277, in _setup_manager
    self._manager = wandb_manager._Manager(settings=self._settings)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_manager.py", line 146, in __init__
    self._service.start()
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/service/service.py", line 199, in start
    self._launch_server()
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/service/service.py", line 193, in _launch_server
    sentry_reraise(e, delay=True)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/util.py", line 214, in sentry_reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/service/service.py", line 191, in _launch_server
    self._wait_for_ports(fname, proc=internal_proc)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/service/service.py", line 141, in _wait_for_ports
    raise ServiceStartTimeoutError(
wandb.sdk.service.service.ServiceStartTimeoutError: Timed out waiting for wandb service to start after 30.0 seconds. Try increasing the timeout with the `_service_wait` setting.

2023-03-22 17:30:45 ERROR Traceback (most recent call last):
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/cli/cli.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/cli/cli.py", line 243, in login
    wandb.setup(settings=login_settings)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 327, in setup
    ret = _setup(settings=settings)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 320, in _setup
    wl = _WandbSetup(settings=settings)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 303, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 114, in __init__
    self._setup()
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 250, in _setup
    self._setup_manager()
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 277, in _setup_manager
    self._manager = wandb_manager._Manager(settings=self._settings)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_manager.py", line 146, in __init__
    self._service.start()
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/service/service.py", line 199, in start
    self._launch_server()
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/service/service.py", line 193, in _launch_server
    sentry_reraise(e, delay=True)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/util.py", line 214, in sentry_reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/service/service.py", line 191, in _launch_server
    self._wait_for_ports(fname, proc=internal_proc)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/service/service.py", line 141, in _wait_for_ports
    raise ServiceStartTimeoutError(
wandb.sdk.service.service.ServiceStartTimeoutError: Timed out waiting for wandb service to start after 30.0 seconds. Try increasing the timeout with the `_service_wait` setting.

2023-03-22 18:02:35 ERROR Traceback (most recent call last):
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/cli/cli.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/cli/cli.py", line 243, in login
    wandb.setup(settings=login_settings)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 327, in setup
    ret = _setup(settings=settings)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 320, in _setup
    wl = _WandbSetup(settings=settings)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 303, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 114, in __init__
    self._setup()
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 250, in _setup
    self._setup_manager()
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 277, in _setup_manager
    self._manager = wandb_manager._Manager(settings=self._settings)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/wandb_manager.py", line 146, in __init__
    self._service.start()
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/service/service.py", line 199, in start
    self._launch_server()
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/service/service.py", line 193, in _launch_server
    sentry_reraise(e, delay=True)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/util.py", line 214, in sentry_reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/service/service.py", line 191, in _launch_server
    self._wait_for_ports(fname, proc=internal_proc)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/MyDefault/lib/python3.9/site-packages/wandb/sdk/service/service.py", line 141, in _wait_for_ports
    raise ServiceStartTimeoutError(
wandb.sdk.service.service.ServiceStartTimeoutError: Timed out waiting for wandb service to start after 30.0 seconds. Try increasing the timeout with the `_service_wait` setting.

2023-03-22 18:53:46 ERROR Traceback (most recent call last):
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/cs323/lib/python3.9/site-packages/wandb/cli/cli.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/cs323/lib/python3.9/site-packages/wandb/cli/cli.py", line 243, in login
    wandb.setup(settings=login_settings)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/cs323/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 327, in setup
    ret = _setup(settings=settings)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/cs323/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 320, in _setup
    wl = _WandbSetup(settings=settings)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/cs323/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 303, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/cs323/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 114, in __init__
    self._setup()
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/cs323/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 250, in _setup
    self._setup_manager()
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/cs323/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 277, in _setup_manager
    self._manager = wandb_manager._Manager(settings=self._settings)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/cs323/lib/python3.9/site-packages/wandb/sdk/wandb_manager.py", line 146, in __init__
    self._service.start()
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/cs323/lib/python3.9/site-packages/wandb/sdk/service/service.py", line 199, in start
    self._launch_server()
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/cs323/lib/python3.9/site-packages/wandb/sdk/service/service.py", line 193, in _launch_server
    sentry_reraise(e, delay=True)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/cs323/lib/python3.9/site-packages/wandb/util.py", line 214, in sentry_reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/cs323/lib/python3.9/site-packages/wandb/sdk/service/service.py", line 191, in _launch_server
    self._wait_for_ports(fname, proc=internal_proc)
  File "/ibex/scratch/fonsecv/Machine_Learning_Course/env/cs323/lib/python3.9/site-packages/wandb/sdk/service/service.py", line 141, in _wait_for_ports
    raise ServiceStartTimeoutError(
wandb.sdk.service.service.ServiceStartTimeoutError: Timed out waiting for wandb service to start after 30.0 seconds. Try increasing the timeout with the `_service_wait` setting.

**Comment by MBakirWB** [comment]
Hi @FONSECV, happy to help. Could you please provide me the following:
- Brief description of your environment and experiment setup
- The `debug.log` and `debug-internal.log` files for two of the crashing runs. These files are located in the project working directory under `wandb/<run-folder>/files`

The `_service_wait` setting appearing in your error message was recently added to allow you to customize startup time. 

To use a longer service start up time you can use:
`WANDB__SERVICE_WAIT=300 python train.py`

Please increase the start up time and update me with the results. Thanks.

**Comment by gattia** [comment]
I just got this same issue for the first time using a script I've used many many times before. I just ran the script 3 times, and got this error on 2/3 runs. 

Just chiming in as this indicates it might not be a user issue? Is wandb particularly slow at the moment?

**Comment by FONSECV** [comment]
Hi @MBakirWB I am new user, I haven't been able to run my experiment yet. I was trying first with the sample code on wandb website 

import wandb
import random

# start a new wandb run to track this script
wandb.init(
    # set the wandb project where this run will be logged
    project="my-awesome-project",
    
    # track hyperparameters and run metadata
    config={
    "learning_rate": 0.02,
    "architecture": "CNN",
    "dataset": "CIFAR-100",
    "epochs": 10,
    }
)

# simulate training
epochs = 10
offset = random.random() / 5
for epoch in range(2, epochs):
    acc = 1 - 2 ** -epoch - random.random() / epoch - offset
    loss = 2 ** -epoch + random.random() / epoch + offset
    
    # log metrics to wandb
    wandb.log({"acc": acc, "loss": loss})
    
# [optional] finish the wandb run, necessary in notebooks
wandb.finish()

My problem is basically to login to the library, the error appears at that point. and doesn't allow me to paste my key. the first time I installed the library it asked me for the key, so I proceeded to run my own experiment and the error appeared, I thought it was a problem with wandb so I reinstalled it. Now I cannot login again because the error appears after using wandb login, not allowing me to paste the key

**Comment by FONSECV** [comment]
Thank you @gattia this solved it for me too.

**Comment by ThomasRochefortB** [comment]
For those of you wanting to implement the `_service_wait` parameter in your Python script here is how I did it:

```
import wandb

run = wandb.init(settings=wandb.Settings(_service_wait=300))

# REST OF YOUR CODE

run.finish()
```

**Comment by moghis** [comment]
> _service_wait

This Solved my problem: [https://github.com/wandb/wandb/issues/3911#issuecomment-1409769887](wandb Github)

**Comment by moghis** [comment]
> For those of you wanting to implement the `_service_wait` parameter in your Python script here is how I did it:
> 
> ```
> import wandb
> 
> run = wandb.init(settings=wandb.Settings(_service_wait=300))
> 
> # REST OF YOUR CODE
> 
> run.finish()
> ```
> 
> ** Edit : Nevermind it does not work. With the above setting I still get the default service_wait of 30 seconds. Anybody got a clue?

This Solved my problem: 

```
import os
import wandb

os.environ["WANDB__SERVICE_WAIT"] = "300"
```

**Comment by mojorisin99** [comment]
> > For those of you wanting to implement the `_service_wait` parameter in your Python script here is how I did it:
> > ```
> > import wandb
> > 
> > run = wandb.init(settings=wandb.Settings(_service_wait=300))
> > 
> > # REST OF YOUR CODE
> > 
> > run.finish()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ** Edit : Nevermind it does not work. With the above setting I still get the default service_wait of 30 seconds. Anybody got a clue?
> 
> This Solved my problem:
> 
> ```
> import os
> import wandb
> 
> os.environ["WANDB__SERVICE_WAIT"] = "300"
> ```

That worked for me thank you very much

**Comment by szemyd** [comment]
This didn't work for me, but this did:
```
wandb.init(
                    settings=wandb.Settings(
                        init_timeout=300,
                    ),
                )
```

OR it might have been this that I also added:

```
os.environ["WANDB_INIT_TIMEOUT"] = "300"
```

I'm still testing, because the error is hard to reproduce (only happens on CI and only in some instances).

**Comment by Mjvolk3** [comment]
Hi @szemyd I am having the same issues. I'm wondering if you ever found the solution? I've been trying a scatter shot approach including all the different env variables that are mentioned, but still not having much success.

**Comment by macio232** [comment]
@Mjvolk3 `WANDB__SERVICE_WAIT` did the job for me in `0.16.0`

**Comment by marcheivanovski** [comment]
Had the same issue on a previously working code, and increasing `os.environ["WANDB__SERVICE_WAIT"] = "300"` solved it for me.

**Comment by richardrl** [comment]
This happened when I tried training with  a relatively large model (ResNet50) on SLURM. The os.environ trick above worked

**Comment by LoneXHuB** [comment]
My solution: was to simply restart the google colab runtime by going to Runtime/restart session. Hope it helps.
