### ISSUE TITLE
[CLI]: OSError: [Errno 28] No space left on device

### ISSUE THREAD

**Issue by pugantsov** [wandb/wandb#5217]
### Describe the bug

I get this error randomly when running my script for a while and I can't seem to find out why it's happening. It seems to happen upon calling `wandb.init` like so:

```python
wandb.init(
    project=project,
    entity=entity,
    name=model_name,
    tags=wandb_tags,
    config=wandb_args,
    id=wandb.util.generate_id(),
)
```

Restarting the script lets it run absolutely fine for another 20-30 minutes before the script crashes again with the same error.

```shell
Problem at: /tmp/ipykernel_95624/3953319749.py 71 <cell line: 1>

Traceback (most recent call last):
  File "/yes/envs/titan/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 999, in init
    run = wi.init()
  File "/yes/envs/titan/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 523, in init
    backend.ensure_launched()
  File "/yes/envs/titan/lib/python3.9/site-packages/wandb/sdk/backend/backend.py", line 187, in ensure_launched
    self.result_q = self._multiprocessing.Queue()
  File "/yes/envs/titan/lib/python3.9/multiprocessing/context.py", line 103, in Queue
    return Queue(maxsize, ctx=self.get_context())
  File "/yes/envs/titan/lib/python3.9/multiprocessing/queues.py", line 43, in __init__
    self._rlock = ctx.Lock()
  File "/yes/envs/titan/lib/python3.9/multiprocessing/context.py", line 68, in Lock
    return Lock(ctx=self.get_context())
  File "/yes/envs/titan/lib/python3.9/multiprocessing/synchronize.py", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/yes/envs/titan/lib/python3.9/multiprocessing/synchronize.py", line 57, in __init__
    sl = self._semlock = _multiprocessing.SemLock(
OSError: [Errno 28] No space left on device
wandb: ERROR Abnormal program exit

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
File /yes/envs/titan/lib/python3.9/site-packages/wandb/sdk/wandb_init.py:999, in init(job_type, dir, config, project, entity, reinit, tags, group, name, notes, magic, config_exclude_keys, config_include_keys, anonymous, mode, allow_val_change, resume, force, tensorboard, sync_tensorboard, monitor_gym, save_code, id, settings)
    998 try:
--> 999     run = wi.init()
   1000     except_exit = wi.settings._except_exit

File /yes/envs/titan/lib/python3.9/site-packages/wandb/sdk/wandb_init.py:523, in _WandbInit.init(self)
    522 backend = Backend(settings=self.settings, manager=manager)
--> 523 backend.ensure_launched()
    524 backend.server_connect()

File /yes/envs/titan/lib/python3.9/site-packages/wandb/sdk/backend/backend.py:187, in Backend.ensure_launched(self)
    186 self.record_q = self._multiprocessing.Queue()
--> 187 self.result_q = self._multiprocessing.Queue()
    188 user_pid = os.getpid()

File /yes/envs/titan/lib/python3.9/multiprocessing/context.py:103, in BaseContext.Queue(self, maxsize)
    102 from .queues import Queue
--> 103 return Queue(maxsize, ctx=self.get_context())

File /yes/envs/titan/lib/python3.9/multiprocessing/queues.py:43, in Queue.__init__(self, maxsize, ctx)
     42 self._reader, self._writer = connection.Pipe(duplex=False)
---> 43 self._rlock = ctx.Lock()
     44 self._opid = os.getpid()

File /yes/envs/titan/lib/python3.9/multiprocessing/context.py:68, in BaseContext.Lock(self)
     67 from .synchronize import Lock
---> 68 return Lock(ctx=self.get_context())

File /yes/envs/titan/lib/python3.9/multiprocessing/synchronize.py:162, in Lock.__init__(self, ctx)
    161 def __init__(self, *, ctx):
--> 162     SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)

File /yes/envs/titan/lib/python3.9/multiprocessing/synchronize.py:57, in SemLock.__init__(self, kind, value, maxvalue, ctx)
     56 try:
---> 57     sl = self._semlock = _multiprocessing.SemLock(
     58         kind, value, maxvalue, self._make_name(),
     59         unlink_now)
     60 except FileExistsError:

OSError: [Errno 28] No space left on device

The above exception was the direct cause of the following exception:

Exception                                 Traceback (most recent call last)
Input In [7], in <cell line: 1>()
     68     wandb_args.update({"stage": EXPERIMENT_MODE, "agent_id": AGENT_ID})
     70     # Initialize WandB
---> 71     wandb.init(
     72         project=project,
     73         entity=entity,
     74         name=model_name,
     75         tags=wandb_tags,
     76         config=wandb_args,
     77         id=wandb.util.generate_id(),
     78     )
     80 # ➡ Run training and validation loop
     81 trainer = Trainer(
     82     model_id=model_args["model_name"],
     83     model=model,
   (...)
     89     save=not DEBUG_MODE,
     90 )

File /yes/envs/titan/lib/python3.9/site-packages/wandb/sdk/wandb_init.py:1037, in init(job_type, dir, config, project, entity, reinit, tags, group, name, notes, magic, config_exclude_keys, config_include_keys, anonymous, mode, allow_val_change, resume, force, tensorboard, sync_tensorboard, monitor_gym, save_code, id, settings)
   1035         if except_exit:
   1036             os._exit(-1)
-> 1037         raise Exception("problem") from error_seen
   1038 return run

Exception: problem
```

### Environment

WandB version: 0.12.16

OS: Linux-3.10.0-1062.12.1.el7.x86_64-x86_64-with-glibc2.27

Python version: 3.9.12

**Comment by kptkin** [comment]
@pugantsov Could you try upgrading to the latest version of wandb and let us know if you still experience this issue.

**Comment by luisbergua** [comment]
Hi @pugantsov, following up here! did you have the chance to upgrade to the latest version and was the issue still raising?
