### ISSUE TITLE
[CLI]: 400 Bad Request on upsertSweep mutation

### ISSUE THREAD

**Issue by jqhoogland** [wandb/wandb#5221]
### Describe the bug

I'm trying to run a sweep, but when I run the python file that initializes and starts the sweep, I get a 400 Bad Request error.  

In particular, the response seems to be:
```json
{
  "errors": [
    { 
      "message": "400 Bad Request: The browser (or proxy) sent a request that this server could not understand.", 
      "path": ["upsertSweep"]
    }
  ], 
  "data": {"upsertSweep":null}
}
```

Here's the code (I can't imagine anything contributing accept for the `wandb.sweep` line

```python
sweep_config = {
    'method': 'grid',
    'name': 'sweep',
    'parameters': {
        'r_mnist_to_cifar': {'values': list(np.linspace(0.3, 3.0, 10))},
        'p_both': {'value': 0.3},
        'p_mnist_error': {'value': 0},
        "p_cifar_error": {'value': 0},
        "seed": {'values': list(range(10))},
        'batch_size': {'value': 64},
        'learning_rate': {'value': 0.001},
        'epochs': {'value': 5}
    }
}

sweep_id = wandb.sweep(sweep_config, project="dominoes")
# wandb.agent(sweep_id, function=train, count=10 * 10)
```

```shell
wandb: ERROR Error while calling W&B API: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand. (<Response [400]>)
wandb: ERROR 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/Users/Jesse/Projects/unifying-grok-dd/.venv/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/Jesse/Projects/unifying-grok-dd/.venv/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 243, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/Users/Jesse/Projects/unifying-grok-dd/.venv/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/Jesse/Projects/unifying-grok-dd/.venv/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/Jesse/Projects/unifying-grok-dd/.venv/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/Users/Jesse/Projects/unifying-grok-dd/.venv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Jesse/Projects/unifying-grok-dd/.venv/lib/python3.10/site-packages/wandb/apis/normalize.py", line 25, in wrapper
    return func(*args, **kwargs)
  File "/Users/Jesse/Projects/unifying-grok-dd/.venv/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2367, in upsert_sweep
    raise e
  File "/Users/Jesse/Projects/unifying-grok-dd/.venv/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2352, in upsert_sweep
    response = self.gql(
  File "/Users/Jesse/Projects/unifying-grok-dd/.venv/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 215, in gql
    ret = self._retry_gql(
  File "/Users/Jesse/Projects/unifying-grok-dd/.venv/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/Users/Jesse/Projects/unifying-grok-dd/.venv/lib/python3.10/site-packages/wandb/util.py", line 1007, in no_retry_4xx
    raise UsageError(body["errors"][0]["message"])
wandb.errors.UsageError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Jesse/Projects/unifying-grok-dd/dominoes/sweep.py", line 81, in <module>
    sweep_id = wandb.sweep(sweep_config, project="dominoes")
  File "/Users/Jesse/Projects/unifying-grok-dd/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_sweep.py", line 110, in sweep
    sweep_id, warnings = api.upsert_sweep(sweep)
  File "/Users/Jesse/Projects/unifying-grok-dd/.venv/lib/python3.10/site-packages/wandb/apis/internal.py", line 120, in upsert_sweep
    return self.api.upsert_sweep(*args, **kwargs)
  File "/Users/Jesse/Projects/unifying-grok-dd/.venv/lib/python3.10/site-packages/wandb/apis/normalize.py", line 65, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "/Users/Jesse/Projects/unifying-grok-dd/.venv/lib/python3.10/site-packages/wandb/apis/normalize.py", line 25, in wrapper
    return func(*args, **kwargs)
  File "/Users/Jesse/Projects/unifying-grok-dd/.venv/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2367, in upsert_sweep
    raise e
  File "/Users/Jesse/Projects/unifying-grok-dd/.venv/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2352, in upsert_sweep
    response = self.gql(
  File "/Users/Jesse/Projects/unifying-grok-dd/.venv/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 215, in gql
    ret = self._retry_gql(
  File "/Users/Jesse/Projects/unifying-grok-dd/.venv/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/Users/Jesse/Projects/unifying-grok-dd/.venv/lib/python3.10/site-packages/wandb/util.py", line 1007, in no_retry_4xx
    raise UsageError(body["errors"][0]["message"])
wandb.errors.CommError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
```

### Environment

WandB version: 0.14.0

OS: MacOS Big Sur 11.6.8 

Python version: python3.10

Versions of relevant libraries: I don't think anything else is relevant here.

**Comment by ArtsiomWB** [comment]
Hi @jqhoogland ! Could you also attach the debug logs for the run thats causing this issue?

**Comment by jqhoogland** [comment]
There is no run! (It's erroring when I attempt to create the sweep_id, before I start any run). There's also no information in any of the other logs (debug-cli, debug-internal, debug).
