### ISSUE TITLE
[CLI]: wandb 0.14.0 crashes upon startup with IPython 8.11.0 and python 3.9.9

### ISSUE THREAD

**Issue by rowanz** [wandb/wandb#5250]
### Describe the bug

When I open a new ipython terminal and try to import wandb, it crashes. (I tried it with a few different versions and seem to get the same behavior.

Open up `ipython` and then run

```python
import wandb
```

```shell
In [1]: import wandb

Traceback (most recent call last):
  File "/Users/rowan/.pyenv/versions/3.9.9/lib/python3.9/asyncio/selector_events.py", line 261, in _add_reader
    key = self._selector.get_key(fd)
  File "/Users/rowan/.pyenv/versions/3.9.9/lib/python3.9/selectors.py", line 193, in get_key
    raise KeyError("{!r} is not registered".format(fileobj)) from None
KeyError: '0 is not registered'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rowan/.virtualenvs/rowanenv/bin/ipython", line 8, in <module>
    sys.exit(start_ipython())
  File "/Users/rowan/.virtualenvs/rowanenv/lib/python3.9/site-packages/IPython/__init__.py", line 124, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/rowan/.virtualenvs/rowanenv/lib/python3.9/site-packages/traitlets/config/application.py", line 1043, in launch_instance
    app.start()
  File "/Users/rowan/.virtualenvs/rowanenv/lib/python3.9/site-packages/IPython/terminal/ipapp.py", line 318, in start
    self.shell.mainloop()
  File "/Users/rowan/.virtualenvs/rowanenv/lib/python3.9/site-packages/IPython/terminal/interactiveshell.py", line 887, in mainloop
    self.interact()
  File "/Users/rowan/.virtualenvs/rowanenv/lib/python3.9/site-packages/IPython/terminal/interactiveshell.py", line 872, in interact
    code = self.prompt_for_code()
  File "/Users/rowan/.virtualenvs/rowanenv/lib/python3.9/site-packages/IPython/terminal/interactiveshell.py", line 811, in prompt_for_code
    text = self.pt_app.prompt(
  File "/Users/rowan/.virtualenvs/rowanenv/lib/python3.9/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1035, in prompt
    return self.app.run(
  File "/Users/rowan/.virtualenvs/rowanenv/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 961, in run
    return loop.run_until_complete(coro)
  File "/Users/rowan/.pyenv/versions/3.9.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/rowan/.virtualenvs/rowanenv/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 875, in run_async
    return await _run_async(f)
  File "/Users/rowan/.virtualenvs/rowanenv/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 728, in _run_async
    with self.input.raw_mode(), self.input.attach(
  File "/Users/rowan/.pyenv/versions/3.9.9/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/Users/rowan/.virtualenvs/rowanenv/lib/python3.9/site-packages/prompt_toolkit/input/vt100.py", line 176, in _attached_input
    loop.add_reader(fd, callback_wrapper)
  File "/Users/rowan/.pyenv/versions/3.9.9/lib/python3.9/asyncio/selector_events.py", line 336, in add_reader
    self._add_reader(fd, callback, *args)
  File "/Users/rowan/.pyenv/versions/3.9.9/lib/python3.9/asyncio/selector_events.py", line 263, in _add_reader
    self._selector.register(fd, selectors.EVENT_READ,
  File "/Users/rowan/.pyenv/versions/3.9.9/lib/python3.9/selectors.py", line 523, in register
    self._selector.control([kev], 0, 0)
TypeError: changelist must be an iterable of select.kevent objects

If you suspect this is an IPython 8.11.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

### Environment

WandB version: 0.14.0

OS: OSX Ventura 13.2.1

Python version: 3.9.9

Versions of relevant libraries:

**Comment by thanos-wandb** [comment]
Hi @rowanz thanks for reporting this issue. I was able to import `wandb` with same versions (`python`, `ipython`, `wandb`) as yours (please see screenshot). There might be another dependency that's causing this conflict. Could you please try in a new virtual environment and see if the error still persists there? Also, would it be possible that you `pip freeze > requirements.txt` and share with us the generated file?

**Comment by thanos-wandb** [comment]
<img width="642" alt="Screenshot 2023-04-02 at 11 56 27" src="https://user-images.githubusercontent.com/108423944/229348741-e4ce7bbf-2c5d-4424-ba97-eef5ad997f01.png">

**Comment by thanos-wandb** [comment]
Hi @rowanz  just wanted to check in and see if you had a chance to review my last message. Have you tried in a new virtual environment, and are you still unable to `import wandb`?

**Comment by thanos-wandb** [comment]
Hi @rowanz since we haven't heard back from you, we will close this ticket for now. If you're still experiencing any issues, please let us know and we will be happy to keep investigating.
