### ISSUE TITLE
[CLI]: `PermissionError` when trying to read k8s token inside container.

### ISSUE THREAD

**Issue by johnhenning** [wandb/wandb#5252]
### Describe the bug

When using the CLI or library, a `PermissionError` is raised if the k8s token secret is mounted with root permissions and the user for the container is not root. 

```bash
wandb login
```

```shell
Traceback (most recent call last):
  File "/home/skunk/.pyenv/versions/3.10.9/bin/wandb", line 8, in <module>
    sys.exit(cli())
  File "/home/skunk/.pyenv/versions/3.10.9/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/skunk/.pyenv/versions/3.10.9/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/skunk/.pyenv/versions/3.10.9/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/skunk/.pyenv/versions/3.10.9/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/skunk/.pyenv/versions/3.10.9/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/skunk/.pyenv/versions/3.10.9/lib/python3.10/site-packages/wandb/cli/cli.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/home/skunk/.pyenv/versions/3.10.9/lib/python3.10/site-packages/wandb/cli/cli.py", line 243, in login
    wandb.setup(settings=login_settings)
  File "/home/skunk/.pyenv/versions/3.10.9/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 327, in setup
    ret = _setup(settings=settings)
  File "/home/skunk/.pyenv/versions/3.10.9/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 320, in _setup
    wl = _WandbSetup(settings=settings)
  File "/home/skunk/.pyenv/versions/3.10.9/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 303, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/home/skunk/.pyenv/versions/3.10.9/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 108, in __init__
    self._settings = self._settings_setup(settings, self._early_logger)
  File "/home/skunk/.pyenv/versions/3.10.9/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 136, in _settings_setup
    s._infer_settings_from_environment()
  File "/home/skunk/.pyenv/versions/3.10.9/lib/python3.10/site-packages/wandb/sdk/wandb_settings.py", line 1525, in _infer_settings_from_environment
    settings["docker"] = wandb.env.get_docker(wandb.util.image_id_from_k8s())
  File "/home/skunk/.pyenv/versions/3.10.9/lib/python3.10/site-packages/wandb/util.py", line 1250, in image_id_from_k8s
    headers={"Authorization": f"Bearer {open(token_path).read()}"},
PermissionError: [Errno 13] Permission denied: '/var/run/secrets/kubernetes.io/serviceaccount/token'
```

### Environment

WandB version:
0.14.0
OS:
Ubuntu 20.04
Python version:
3.10.9
Versions of relevant libraries:

### Additional Context

I think this just needs another exception handler handling the `PermissionError` as well as the `RequestException`
https://github.com/wandb/wandb/blob/e5e6fac5a449911ab4795f9e4367a6871ddcdb9c/wandb/util.py#L1244-L1253

This is related to #5134

**Comment by thanos-wandb** [comment]
Hi @jlhbaseball15 thanks so much for reporting this issue, and for the suggestion to handle this error more gently. I can proceed with a feature request to include `PermissionError` as well in the `except` block. 

Would it be please possible to provide some more details of the use case, eg is this something that happens often in your workflow to mount the k8s secrets token with root permissions, and any code snippet how you generated that token would be really helpful details to add to the internal ticket.

**Comment by thanos-wandb** [comment]
Hi @jlhbaseball15 just an update on this, I have reported it to our SDK team to handle this case better. I have linked the internal ticket with this thread so as to keep you posted on any updates. Thanks once again for reporting this issue.

**Comment by jlhbaseball15** [comment]
Hi @thanos-wandb, Thanks a lot! As for when this happens, we have on demand dev containers running where the end user is not root, but the token is mounted with root only permissions by default. We got around it by setting the token permissions to `0644` instead of `0600` but there may be use cases where that's not ideal.

**Comment by thanos-wandb** [comment]
Hi @jlhbaseball15 thanks for the update, glad to hear you worked around the issue for now by changing token's permissions. I will keep you posted here on any further updates!
