### ISSUE TITLE
[Q] wandb.init() report `ReadTimeout`, and cannot run the program

### ISSUE THREAD

**Issue by Porthoos** [wandb/wandb#5286]
Hello, I've started using W&B recently, and I found the wandb cannot work. the output of the program is `wandb: Network error (ReadTimeout), entering retry loop.`, is this a problem about my computer or the server?

I'm using W&B 0.14.0
python 3.8.13
OS windows 10

the full output of program is

> wandb: W&B API key is configured. Use wandb login --relogin to force relogin
wandb: Network error (ReadTimeout), entering retry loop.
wandb: Network error (ReadTimeout), entering retry loop.
Traceback (most recent call last):
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\wandb\sdk\wandb_init.py", line 1144, in init
    run = wi.init()
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\wandb\sdk\wandb_init.py", line 773, in init
    raise error
wandb.errors.CommError: Error communicating with wandb process, exiting...
For more info see: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Problem at: D:\PycharmProjects\PPOimplementation\PPOmain.py 108 main
wandb: ERROR Abnormal program exit

the file debug-internal.log is

> 2023-04-03 10:28:53,689 INFO    StreamThr :7284 [internal.py:wandb_internal():87] W&B internal server running at pid: 7284, started at: 2023-04-03 10:28:53.688300
2023-04-03 10:28:53,692 DEBUG   HandlerThread:7284 [handler.py:handle_request():144] handle_request: status
2023-04-03 10:28:53,748 INFO    WriterThread:7284 [datastore.py:open_for_write():85] open: D:\PycharmProjects\PPOimplementation\wandb\run-20230403_102853-emaoap72\run-emaoap72.wandb
2023-04-03 10:28:53,754 DEBUG   SenderThread:7284 [sender.py:send():336] send: header
2023-04-03 10:28:53,921 DEBUG   SenderThread:7284 [sender.py:send():336] send: run
2023-04-03 10:28:58,964 DEBUG   HandlerThread:7284 [handler.py:handle_request():144] handle_request: keepalive
2023-04-03 10:29:04,013 DEBUG   HandlerThread:7284 [handler.py:handle_request():144] handle_request: keepalive
2023-04-03 10:29:09,064 DEBUG   HandlerThread:7284 [handler.py:handle_request():144] handle_request: keepalive
2023-04-03 10:29:14,126 DEBUG   HandlerThread:7284 [handler.py:handle_request():144] handle_request: keepalive
2023-04-03 10:29:19,187 DEBUG   HandlerThread:7284 [handler.py:handle_request():144] handle_request: keepalive
2023-04-03 10:29:24,234 DEBUG   HandlerThread:7284 [handler.py:handle_request():144] handle_request: keepalive
2023-04-03 10:29:29,301 DEBUG   HandlerThread:7284 [handler.py:handle_request():144] handle_request: keepalive
2023-04-03 10:29:34,084 INFO    SenderThread:7284 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\http\client.py", line 1348, in getresponse
    response.begin()
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\http\client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\http\client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\urllib3\packages\six.py", line 770, in reraise
    raise value
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\urllib3\connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\urllib3\connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=10)

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\wandb\sdk\internal\internal_api.py", line 243, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\transport\requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\requests\adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=10)
2023-04-03 10:29:34,365 DEBUG   HandlerThread:7284 [handler.py:handle_request():144] handle_request: keepalive
2023-04-03 10:29:39,584 DEBUG   HandlerThread:7284 [handler.py:handle_request():144] handle_request: keepalive
2023-04-03 10:29:44,606 DEBUG   HandlerThread:7284 [handler.py:handle_request():144] handle_request: keepalive
2023-04-03 10:29:49,634 DEBUG   HandlerThread:7284 [handler.py:handle_request():144] handle_request: keepalive
2023-04-03 10:29:54,674 DEBUG   HandlerThread:7284 [handler.py:handle_request():144] handle_request: cancel
2023-04-03 10:29:54,675 DEBUG   SenderThread:7284 [sender.py:send():345] Record cancelled: run
2023-04-03 10:29:54,675 DEBUG   HandlerThread:7284 [handler.py:handle_request():144] handle_request: cancel
2023-04-03 10:29:54,676 DEBUG   HandlerThread:7284 [handler.py:handle_request():144] handle_request: status_report
2023-04-03 10:29:59,514 INFO    MainThread:7284 [internal.py:handle_exit():77] Internal process exited

**Comment by ArtsiomWB** [comment]
Hi @Porthoos! Could you send your debug logs of the run that has crashed fro you and produced this error?

**Comment by Porthoos** [comment]
do you mean the debug.log?

> 2023-04-03 14:50:33,666 INFO    MainThread:1888 [wandb_setup.py:_flush():76] Configure stats pid to 1888
2023-04-03 14:50:33,666 INFO    MainThread:1888 [wandb_setup.py:_flush():76] Loading settings from C:\Users\JinLab\.config\wandb\settings
2023-04-03 14:50:33,667 INFO    MainThread:1888 [wandb_setup.py:_flush():76] Loading settings from D:\PycharmProjects\PPOimplementation\wandb\settings
2023-04-03 14:50:33,667 INFO    MainThread:1888 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-04-03 14:50:33,667 INFO    MainThread:1888 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-04-03 14:50:33,667 INFO    MainThread:1888 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'PPOmain.py', 'program': 'PPOmain.py'}
2023-04-03 14:50:33,667 INFO    MainThread:1888 [wandb_init.py:_log_setup():506] Logging user logs to D:\PycharmProjects\PPOimplementation\wandb\run-20230403_145033-sivtwm98\logs\debug.log
2023-04-03 14:50:33,667 INFO    MainThread:1888 [wandb_init.py:_log_setup():507] Logging internal logs to D:\PycharmProjects\PPOimplementation\wandb\run-20230403_145033-sivtwm98\logs\debug-internal.log
2023-04-03 14:50:33,668 INFO    MainThread:1888 [wandb_init.py:init():546] calling init triggers
2023-04-03 14:50:33,668 INFO    MainThread:1888 [wandb_init.py:init():552] wandb.init called with sweep_config: {}
config: {'exp_name': 'PPOmain', 'seed': 1, 'torch_deterministic': True, 'track': True, 'wandb_project_name': 'PPO_implementation', 'wandb_entity': 'Aramiis', 'policy_dist': 'Beta', 'env_id': 'gym_STAR/My_Env-v1', 'max_train_steps': 3000000.0, 'evaluate_freq': 5000.0, 'lr_a': 0.0003, 'lr_c': 0.0003, 'batch_size': 2048, 'minibatch_size': 64, 'update_epochs': 10, 'gamma': 0.99, 'lamda': 0.95, 'epsilon': 0.2, 'entropy_coef': 0.01, 'valuef_coef': 0.5, 'batch_adv_norm': True, 'mbatch_adv_norm': False, 'vloss_clip': True, 'hidden_width': 64, 'state_dim': 554, 'action_dim': 126, 'max_action': 1.0}
2023-04-03 14:50:33,669 INFO    MainThread:1888 [wandb_init.py:init():602] starting backend
2023-04-03 14:50:33,669 INFO    MainThread:1888 [wandb_init.py:init():606] setting up manager
2023-04-03 14:50:33,690 INFO    MainThread:1888 [wandb_init.py:init():613] backend started and connected
2023-04-03 14:50:33,713 INFO    MainThread:1888 [wandb_init.py:init():701] updated telemetry
2023-04-03 14:50:33,765 INFO    MainThread:1888 [wandb_init.py:init():741] communicating run to backend with 60.0 second timeout
2023-04-03 14:51:02,648 INFO    Thread-7  :1888 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\http\client.py", line 1348, in getresponse
    response.begin()
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\http\client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\http\client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\urllib3\packages\six.py", line 770, in reraise
    raise value
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\urllib3\connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\urllib3\connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=10)

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\wandb\sdk\internal\internal_api.py", line 243, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\transport\requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\requests\adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=10)
2023-04-03 14:51:34,346 ERROR   MainThread:1888 [wandb_init.py:init():755] backend process timed out, exiting...
encountered error: Error communicating with wandb process, exiting...
For more info see: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-04-03 14:51:34,354 ERROR   MainThread:1888 [wandb_init.py:init():1171] error
Traceback (most recent call last):
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\wandb\sdk\wandb_init.py", line 1144, in init
    run = wi.init()
  File "D:\anaconda3\envs\STAR_DEPLOY\lib\site-packages\wandb\sdk\wandb_init.py", line 773, in init
    raise error
wandb.errors.CommError: Error communicating with wandb process, exiting...
For more info see: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-

**Comment by ArtsiomWB** [comment]
Yep, that's perfect! Apologies should have worded it better.

**Comment by ArtsiomWB** [comment]
Could you also send a script you are running when you are running into this issue?

**Comment by ArtsiomWB** [comment]
We wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by Porthoos** [comment]
Sorry for late response, I have started using offline wandb, and sync it after it finish. Thanks for your help, I will close this issue.
