### ISSUE TITLE
Wandb init fails when on inferring environment from Git

### ISSUE THREAD

**Issue by pugantsov** [wandb/wandb#5291]
I am trying to run jobs via a Kubernetes cluster and my job fails whenever it reaches `wandb.init` with the following error:

```
wandb: ERROR Abnormal program exit
Traceback (most recent call last):
  File "/yes/envs/titan/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 996, in init
    wi.setup(kwargs)
  File "/yes/envs/titan/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 133, in setup
    self._wl = wandb_setup.setup()
  File "/yes/envs/titan/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 318, in setup
    ret = _setup(settings=settings)
  File "/yes/envs/titan/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 313, in _setup
    wl = _WandbSetup(settings=settings)
  File "/yes/envs/titan/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 299, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/yes/envs/titan/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 107, in __init__
    self._settings = self._settings_setup(settings, self._early_logger)
  File "/yes/envs/titan/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 136, in _settings_setup
    s._infer_run_settings_from_environment(_logger=early_logger)
  File "/yes/envs/titan/lib/python3.9/site-packages/wandb/sdk/wandb_settings.py", line 1392, in _infer_run_settings_from_environment
    program_relpath = self.program_relpath or _get_program_relpath_from_gitrepo(
  File "/yes/envs/titan/lib/python3.9/site-packages/wandb/sdk/wandb_settings.py", line 138, in _get_program_relpath_from_gitrepo
    root = repo.root
  File "/yes/envs/titan/lib/python3.9/site-packages/wandb/sdk/lib/git.py", line 46, in root
    return self.repo.git.rev_parse("--show-toplevel")
  File "/yes/envs/titan/lib/python3.9/site-packages/git/cmd.py", line 639, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/yes/envs/titan/lib/python3.9/site-packages/git/cmd.py", line 1184, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/yes/envs/titan/lib/python3.9/site-packages/git/cmd.py", line 984, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git rev-parse --show-toplevel
  stderr: 'fatal: detected dubious ownership in repository at '/nfs'
To add an exception for this directory, call:

	git config --global --add safe.directory /nfs'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nfs/repr_comparison/scripts/source_training/train.py", line 136, in <module>
    run(args)
  File "/nfs/repr_comparison/scripts/source_training/train.py", line 84, in run
    wandb.init(
  File "/yes/envs/titan/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1037, in init
    raise Exception("problem") from error_seen
Exception: problem
```

/nfs/ here is a cluster-level name pointing to my specific Kubernetes volume claim.

I have tried passing in `wandb.Settings(program_relpath=os.path.join(os.getenv("SCRIPT_DIR"), "train.py"), disable_git=True, save_code=False)` (as per https://github.com/wandb/wandb/issues/1565) but it still seems to check for git when I run it.

Since I launch these in Docker containers, it's not as simple as me just running the suggested line of  `git config --global --add safe.directory /nfs`

**Comment by kptkin** [comment]
Hi @pugantsov 

Thanks a lot for reporting this issue. It is indeed seems like a bug. In the meantime. I would suggest using an environment variable to setup  `program_relpath` path. Hence when it reaches the problematic part of the code it will only evaluate the first part and avoid raising the exception. 
You could do something like this:

```
import os
import wandb

os.environ["WANDB_PROGRAM_RELPATH"] =  ...
run = wandb.init(settings=wandb.Settings(disable_git=True, save_code=False))
``` 

We will be working on fixing this issue and hopefully it will be included in one of the upcoming releases.

**Comment by neel04** [comment]
But this disabled saving the code, which is quite handy for me (and most people I assume)?

Is there some other workaround? and what exactly is `WANDB_PROGRAM_RELPATH`?

**Comment by kptkin** [comment]
> But this disabled saving the code, which is quite handy for me (and most people I assume)?
> 
> Is there some other workaround? and what exactly is `WANDB_PROGRAM_RELPATH`?

@neel04 you could try removing the `save_code=False` (i just followed the pattern provided by @pugantsov).
We do catch the above git exception (`exc.GitCommandError`) in the case of code saving setup, so if that is the error you are seeing `save_code` should work for you.

`WANDB_PROGRAM_RELPATH` would be the relative path to your program from the current working directory (the directory where we by default initialize all the wandb files).

**Comment by kptkin** [comment]
@neel04 and @pugantsov I looked at the code again and i see that we have error handling for the case you are reporting. Which version of wandb are you using?

Could you update to the latest and see if you still experiencing this issue?

**Comment by kptkin** [comment]
Hi @pugantsov @neel04 

Would you be interested to test out this [branch](#5437 ) to verify that we actually fixed your issue?

you could install it like this:
```
pip install git+https://github.com/wandb/wandb.git@WB-13236 
```

I tested it locally with a malformed git folder and it seems to fix all instances of the git invocation
