### ISSUE TITLE
[Q]please help me

### ISSUE THREAD

**Issue by Merak2** [wandb/wandb#5323]
when I run my code, I meet this problem, I have't effective method.
![image](https://user-images.githubusercontent.com/49240354/231399148-dcc8a76c-35da-4f39-9b5a-6a12136b99d8.png)
debug.log
`2023-04-12 16:26:15,974 INFO    MainThread:8900 [wandb_setup.py:_flush():76] Configure stats pid to 8900
2023-04-12 16:26:15,974 INFO    MainThread:8900 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Admin\.config\wandb\settings
2023-04-12 16:26:15,974 INFO    MainThread:8900 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Admin\Desktop\PerFedMask\wandb\settings
2023-04-12 16:26:15,974 INFO    MainThread:8900 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-04-12 16:26:15,974 INFO    MainThread:8900 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-04-12 16:26:15,974 INFO    MainThread:8900 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'fed_perfedmask.py', 'program': 'C:\\Users\\Admin\\Desktop\\PerFedMask\\fed_perfedmask.py'}
2023-04-12 16:26:15,975 INFO    MainThread:8900 [wandb_init.py:_log_setup():507] Logging user logs to C:\Users\Admin\Desktop\PerFedMask\wandb\run-20230412_162615-lyo9cqjr\logs\debug.log
2023-04-12 16:26:15,975 INFO    MainThread:8900 [wandb_init.py:_log_setup():508] Logging internal logs to C:\Users\Admin\Desktop\PerFedMask\wandb\run-20230412_162615-lyo9cqjr\logs\debug-internal.log
2023-04-12 16:26:15,977 INFO    MainThread:8900 [wandb_init.py:init():547] calling init triggers
2023-04-12 16:26:15,977 INFO    MainThread:8900 [wandb_init.py:init():555] wandb.init called with sweep_config: {}
config: {'seed': 1, 'data': 'Cifar10', 'model': 'preresnet18', 'algorithm': 'perFedMask', 'width_scale': 1.0, 'no_track_stat': False, 'no_mask_loss': False, 'no_log': False, 'test': False, 'resume': False, 'verbose': 0, 'percent': 1.0, 'val_ratio': 0.1, 'batch': 50, 'test_batch': 128, 'pd_nuser': 100, 'pr_nuser': 10, 'pu_nclass': 3, 'domain_order': 0, 'partition_mode': 'uni', 'con_test_cls': True, 'slim_ratios': '8-1', 'val_ens_only': True, 'lr': 0.1, 'lr_sch': 'multi_step', 'opt': 'sgd', 'iters': 80, 'wk_iters': 4, 'save_path': './checkpoint\\Alg_perFedMask_C10_Cifar10', 'save_file': './checkpoint\\Alg_perFedMask_C10_Cifar10\\preresnet18__pd_nuser_100__pct_1.0__pu_nclass_3__pr_nuser_10__ctc__8-1__lrs_multi_step__batch_50__wk_iters_4'}
2023-04-12 16:26:15,978 INFO    MainThread:8900 [wandb_init.py:init():595] starting backend
2023-04-12 16:26:15,978 INFO    MainThread:8900 [wandb_init.py:init():599] setting up manager
2023-04-12 16:26:15,981 INFO    MainThread:8900 [backend.py:_multiprocessing_setup():108] multiprocessing start_methods=spawn, using: spawn
2023-04-12 16:26:15,984 INFO    MainThread:8900 [wandb_init.py:init():605] backend started and connected
2023-04-12 16:26:15,997 INFO    MainThread:8900 [wandb_init.py:init():695] updated telemetry
2023-04-12 16:26:15,997 INFO    MainThread:8900 [wandb_init.py:init():732] communicating run to backend with 60.0 second timeout
2023-04-12 16:26:17,045 WARNING MsgRouterThr:8900 [router.py:message_loop():77] message_loop has been closed
2023-04-12 16:26:21,065 ERROR   MainThread:8900 [wandb_init.py:init():1163] transport failed
Traceback (most recent call last):
  File "C:\Users\Admin\.conda\envs\PerFedMask\lib\site-packages\wandb\sdk\wandb_init.py", line 1145, in init
    run = wi.init()
  File "C:\Users\Admin\.conda\envs\PerFedMask\lib\site-packages\wandb\sdk\wandb_init.py", line 738, in init
    cancel=True,
  File "C:\Users\Admin\.conda\envs\PerFedMask\lib\site-packages\wandb\sdk\lib\mailbox.py", line 281, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed
`
debug-internal.log
`2023-04-12 16:26:15,984 INFO    StreamThr :9120 [internal.py:wandb_internal():89] W&B internal server running at pid: 9120, started at: 2023-04-12 16:26:15.983258
2023-04-12 16:26:15,985 DEBUG   HandlerThread:9120 [handler.py:handle_request():144] handle_request: status
2023-04-12 16:26:15,997 INFO    HandlerThread:9120 [handler.py:finish():845] shutting down handler
2023-04-12 16:26:15,998 INFO    WriterThread:9120 [datastore.py:open_for_write():85] open: C:\Users\Admin\Desktop\PerFedMask\wandb\run-20230412_162615-lyo9cqjr\run-lyo9cqjr.wandb
2023-04-12 16:26:15,998 INFO    WriterThread:9120 [datastore.py:close():298] close: C:\Users\Admin\Desktop\PerFedMask\wandb\run-20230412_162615-lyo9cqjr\run-lyo9cqjr.wandb
2023-04-12 16:26:16,993 ERROR   StreamThr :9120 [internal.py:wandb_internal():174] Thread SenderThread:
Traceback (most recent call last):
  File "C:\Users\Admin\.conda\envs\PerFedMask\lib\site-packages\wandb\sdk\internal\internal_util.py", line 49, in run
    self._run()
  File "C:\Users\Admin\.conda\envs\PerFedMask\lib\site-packages\wandb\sdk\internal\internal_util.py", line 89, in _run
    self._setup()
  File "C:\Users\Admin\.conda\envs\PerFedMask\lib\site-packages\wandb\sdk\internal\internal.py", line 324, in _setup
    context_keeper=self._context_keeper,
  File "C:\Users\Admin\.conda\envs\PerFedMask\lib\site-packages\wandb\sdk\internal\sender.py", line 283, in __init__
    default_settings=settings, retry_callback=self.retry_callback
  File "C:\Users\Admin\.conda\envs\PerFedMask\lib\site-packages\wandb\sdk\internal\internal_api.py", line 221, in __init__
    url=f"{self.settings('base_url')}/graphql",
  File "C:\Users\Admin\.conda\envs\PerFedMask\lib\site-packages\wandb\sdk\lib\gql_request.py", line 34, in __init__
    self.session = requests.Session()
  File "C:\Users\Admin\.conda\envs\PerFedMask\lib\site-packages\requests\sessions.py", line 448, in __init__
    self.mount("https://", HTTPAdapter())
  File "C:\Users\Admin\.conda\envs\PerFedMask\lib\site-packages\requests\adapters.py", line 156, in __init__
    self.init_poolmanager(pool_connections, pool_maxsize, block=pool_block)
  File "C:\Users\Admin\.conda\envs\PerFedMask\lib\site-packages\pip_system_certs\wrapt_requests.py", line 27, in init_poolmanager
    import ssl
  File "C:\Users\Admin\.conda\envs\PerFedMask\lib\ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: DLL load failed: �Ҳ���ָ����ģ�顣
`

**Comment by thanos-wandb** [comment]
Hi @Merak2 thanks for reporting this issue. Does it fail in `wandb.init()` call? Are you logging to a Local W&B instance, if so could you please verify you are writing to the correct host url? Try re-logging in as follows from your CLI:
`wandb login --relogin --host=<your=host>` and input the API key from authorization page. Would this work for you?

**Comment by thanos-wandb** [comment]
Hi @Merak2 thanks for the additional information, the `start_method` is a deprecated option in our most recent version, so you won't need this defined in `settings`. Other than that, I also see that you get an `ImportError: DLL load failed` which is what might be causing the issue for you. Could you please provide us with some context, was this error always happening for you, or did it appear recently after you changed for instance wandb version, or training environment/machine?

**Comment by thanos-wandb** [comment]
Thanks for the link to this repo, it uses an old wandb version (`v0.12.19`). Could you please upgrade (`pip install --upgrade wandb`) to our most recent version (`v0.15.0`) and try again? Would it be possible to provide some more information on your training environment, Are you using WSL, or anaconda prompt?

**Comment by thanos-wandb** [comment]
Hi @Merak2 this shouldn't happen it seems you're getting a `ConnectTimeout` error even from the `wandb init` CLI command. Are you using a proxy, or are behind any firewall? What's your permissions in this folder? and could you please try to open the anaconda prompt in admin mode?

**Comment by thanos-wandb** [comment]
Hi @Merak2 could you please first try to force relogin as follows: `wandb login --cloud --relogin` ? Would this work for you?

**Comment by thanos-wandb** [comment]
Hi @Merak2 just checking in here to see if you're still encountering this issue? It would worth upgrading to our most recent version (`v0.15.4`) and try again. Even though this seems likely related to your Windows environment. Could you please also check if you're running into same issues from a Jupyter or a Colab notebook? thank you!

**Comment by thanos-wandb** [comment]
Hi @Merak2 re-opening this as it seems to be an ongoing issue for you. Could you please check the previous message and provide more information? Thank you!

**Comment by thanos-wandb** [comment]
Hi @Merak2 thanks a lot for the screenshot, that's really helpful. You will need to change the value '"your-entity"` to be the same as your username (or team name if you're a member of an Org) in `wandb.ai`. Could you please try again, and see if that worked for you? It seems you're able to successfully login so this should work for you.

**Comment by thanos-wandb** [comment]
Hi @Merak2 just following up here if you changed the entity value from your code above and if that now works for you? Thanks!
