### ISSUE TITLE
[CLI]: wandb sync --clean --clean-old-hours X removes active runs

### ISSUE THREAD

**Issue by pkuderov** [wandb/wandb#5324]
### Describe the bug

Running a very long lasting sweep, I decided to clean up disk space occupied by the wandb logs and removed the logs for already finished runs with the following command:
```shell
wandb sync --clean --clean-old-hours 4
```

To my surprise, I immediately got current runs failing with the following exception (sorry for providing a screenshot instead of the text):

```shell
During handling of the above exception, another exception occurred:                                    
  File "/home/pkuderov/mambaforge/envs/hima/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", 
line 51, in _publish                                                                          
Traceback (most recent call last):                                                                     
  File "/home/pkuderov/mambaforge/envs/hima/lib/python3.9/site-packages/wandb/agents/pyagent.py", line 298, in 
_run_job                                                                                       
    self._sock_client.send_record_publish(record)                                                      
  File "/home/pkuderov/mambaforge/envs/hima/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", 
line 221, in send_record_publish                                                                       
    self._function()                                                                                   
  File "/home/pkuderov/dev/hima/hima/common/run/sweep.py", line 114, in _wandb_agent_entry_point       
    self.send_server_request(server_req)                                                               
  File "/home/pkuderov/mambaforge/envs/hima/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", 
line 155, in send_server_request                                                                       
    wandb.finish(1)                                                                                    
  File "/home/pkuderov/mambaforge/envs/hima/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 3
716, in finish                                                                                         
    self._send_message(msg)                                                                            
  File "/home/pkuderov/mambaforge/envs/hima/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", 
line 152, in _send_message                                                                             
    self._sendall_with_error_handle(header + data)                                                     
  File "/home/pkuderov/mambaforge/envs/hima/lib/python3.9/site-package
```

I am not sure if it is a bug instead of expected behaviour. However, I see several problems here:

1. The documentation for `wandb sync` is not sufficient, which forces users to act on their own risk. Terminology for `online/offline/synced` needs better explanation.
2. No safe checks neither implemented, nor mentioned in the documentation, while the `clean` operation is obviously dangerous (e.g. I ruined 20 hours of computations, could be much worse).
3. Documentation does not provide a clear way to clean up all finished (i.e. successful, stopped or failed) synced runs' logs.

P.S. Thank you guys for such an awesome tool you are developed! Love it 🖤 

### Environment

WandB version: 0.14.2

OS: Linux

Python version: 3.9.16

Versions of relevant libraries: N/A

**Comment by nate-wandb** [comment]
Hi @pkuderov, working on a reproduction of this now but I agree that a dialogue should indicate what could happen if you run this command while runs are running. I'll follow up shortly with what I find.

Thank you for reporting!

**Comment by nate-wandb** [comment]
Hi @pkuderov, I was able to replicate the behavior you are seeing. I'll report this to the engineering team and follow up once they have a chance to look into it.

**Comment by RyanNavillus** [comment]
Just to add to this, I'm working on a slurm cluster with limited disk space per person. I should have moved the log directory to my scratch disk, but it would be nice if `wandb sync --clean` could sync and delete local files without crashing runs. That way I could periodically free up disk space for long-running experiments without crashing them. I'm sure that would take much more effort than adding a warning though.

**Comment by nate-wandb** [comment]
@RyanNavillus, how large are the run folders? I'm curious if maybe the cache is getting large since we use this for storing Artifacts and we do have a [function](https://docs.wandb.ai/ref/cli/wandb-artifact/wandb-artifact-cache/wandb-artifact-cache-cleanup) to safely clean this.

**Comment by RyanNavillus** [comment]
> @RyanNavillus, how large are the run folders? I'm curious if maybe the cache is getting large since we use this for storing Artifacts and we do have a [function](https://docs.wandb.ai/ref/cli/wandb-artifact/wandb-artifact-cache/wandb-artifact-cache-cleanup) to safely clean this.

Thanks, I'll look into this! The folders got very big very quickly because I was running 16 experiments at once and I was syncing from tensorboard, so I'm there was a "runs" folder and "wandb" folder that were duplicating info. It was increasing maybe 1-2GB per hour, so I had to periodically clean out runs that were finished, which was a hassle to figure out. It works fine for lots of short runs, but if I had one very long experiment that required more log space than I have on disk, there would be no way to run it afaik.

**Comment by nate-wandb** [comment]
Sounds good! I'll follow back up once the team has had a chance to look into providing a more clear warning/protecting the run folders of active runs.
