### ISSUE TITLE
[CLI]: Importing from MLFlow into WandB breaks because of permissions

### ISSUE THREAD

**Issue by angadkalra** [wandb/wandb#5339]
### Describe the bug

I'm trying to transition from MLFlow to WandB. I have 8 projects in MLFlow with 10 runs each, and I'm trying to use the code that is recommended here: https://docs.wandb.ai/guides/track/public-api-guide#advanced

but I keep getting this error:

```python
from wandb.apis.importers import MlflowImporter

overrides = {"entity": "imvaria", "project": "TESTING"}
importer = MlflowImporter(mlflow_tracking_uri="https://mlflow.imvaria.com/")

all_runs = list(importer.download_all_runs())
testing_runs = [run for run in all_runs if run.run.info.experiment_id == '41']

[importer.import_one(run, overrides=overrides) for run in screendx_runs]
```

```shell
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden) 
```

I definitely do have permission for MLFlow because I'm able to hit the server using the python API and view experiments and runs. I can't find anything related to permissions in WandB web app.

Thanks!

### Environment

WandB version: 0.14.0

OS: Ubuntu 20.04

Python version: 3.9.15

Versions of relevant libraries:

**Comment by andrewtruong** [comment]
Hey @angadkalra thanks for filing this!

This error suggests that you might not have permissions for that specific W&B entity and project.  Maybe you're logged into a different instance?

The easiest way to check permissions is probably to create a run with this snippet:
```py
with wandb.init(entity="imvaria", project="TESTING"):
  run.log({'example': 1})
```

**Comment by angadkalra** [comment]
Just tried that snippet and it worked fine.

**Comment by angadkalra** [comment]
Looks like theres a new error now:

```
>>> importer.import_one(testing_runs[0], overrides=overrides)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/wandb/apis/importers/mlflow.py", line 108, in import_one
    super().import_one(run, overrides)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/wandb/apis/importers/base.py", line 301, in import_one
    self._import_one(run)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/wandb/apis/importers/base.py", line 306, in _import_one
    sm.send(run._make_summary_record())
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/wandb/apis/importers/base.py", line 164, in _make_summary_record
    "_runtime": self.runtime(),  # quirk of runtime -- it has to be here!
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/wandb/apis/importers/mlflow.py", line 78, in runtime
    return self.run.info.end_time // 1_000 - self.start_time()
TypeError: unsupported operand type(s) for //: 'NoneType' and 'int'
```

**Comment by andrewtruong** [comment]
Hmm, that's strange.  Can you check using the mlflow API to see if this run has a start time?

Can you also share the mlflow server and client versions?

**Comment by angadkalra** [comment]
mlflow server and client is version 2.2.2

using mlflow python cli

```
>>> run.info
<RunInfo: artifact_uri='gs://mlflow/artifacts/41/cb5526e714af436c9f2daff47e218dcb/artifacts', end_time=None, experiment_id='41', lifecycle_stage='active', run_id='cb5526e714af436c9f2daff47e218dcb', run_name=('TESTING'), run_uuid='cb5526e714af436c9f2daff47e218dcb', start_time=1676577355963, status='RUNNING', user_id='ubuntu'>
```

**Comment by andrewtruong** [comment]
It looks like this run is still running -- is that correct?
```
status='RUNNING'
```

Are you trying to import a running run, or is the run already finished and maybe there's some logging issue on the MLFlow side?

I think in either case, we can guard for this.

For completeness, can you try importing a run that has an end_time?  I think your code would look something like this:
```py
testing_runs = [run for run in all_runs if run.run.info.end_time is not None]
```

**Comment by angadkalra** [comment]
So here's what's happening. All my MLFlow project runs are status='FINISHED', but when I'm trying to import into WandB, it doesn't like the run name because it contains stuff like ':' or '/', so when I rename the MLFlow run in MLFlow, it changes the status to RUNNING, and then importing it becomes impossible.

**Comment by andrewtruong** [comment]
Oh interesting, that sounds like a different issue.

So for your case, I think we can make two patches:
1. We'll add handling for incompatible strings (maybe replace `:` and `/` with `__`)
2. We'll add a dummy value for `end_time` so you can still import runs with status `RUNNING`

**Comment by angadkalra** [comment]
Yup I think that should be fine! I can post here if I run into any more issues. When do you think that patch will be available for download?

**Comment by angadkalra** [comment]
I keep getting this...can you tell me whats wrong with my run name?

>  ValueError: Artifact name may only contain alphanumeric characters, dashes, underscores, and dots. Invalid name: 
"Train-Val split version 3 ResNet-50 - rmv confusing neg labels - Train Lung Harvard NLST NY-SBU - Lung 3 sites val - SSA 3.1.6"

**Comment by angadkalra** [comment]
@andrewtruong Hey man, any help with previous comment?

**Comment by andrewtruong** [comment]
Hey @angadkalra, thanks for your patience!

I think your run name is fine, but our handling for Artifacts doesn't like that it has spaces -- looking into this now.

**Comment by andrewtruong** [comment]
@angadkalra can you try this branch to see if it works for you?
https://github.com/wandb/wandb/tree/andrew/mlflow-importer-fixes

**Comment by angadkalra** [comment]
> @angadkalra can you try this branch to see if it works for you? https://github.com/wandb/wandb/tree/andrew/mlflow-importer-fixes

Thanks for helping! Do you have instructions to install wandb package for a specific branch manually? 

I'm guessing:

1. uninstall current pip package for wandb
2. checkout wandb repo, switch to your branch, install that branch (instructions for this needed)
3. run python code to login to wandb and try importing mlflow runs

**Comment by andrewtruong** [comment]
The easiest way is to [pip install the branch directly](https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch).

Try this:
```
pip install git+https://github.com/wandb/wandb.git@andrew/mlflow-importer-fixes
```

**Comment by angadkalra** [comment]
So I installed the branch and confirmed it was able to log a simple metric to a test project. Then I tried importing one mlflow run into the same test project, and it gave me this:

```
(Pdb) importer.import_one(testing_runs[1], overrides=overrides)                                                                                                                                 
409 response executing GraphQL.                                                                                                                                                                 
{"errors":[{"message":"run imvaria/TESTING/cb5526e714af436c9f2daff47e218dcb was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}     
wandb: ERROR Error while calling W&B API: run imvaria/TESTING/cb5526e714af436c9f2daff47e218dcb was previously created and deleted; try a new run name (<Response [409]>)                        
409 response executing GraphQL.
```

So I changed the project name in overrides and it gave me this:

```
importer.import_one(testing_runs[1], overrides=overrides)
*** ValueError: Path is not a file: /tmp/tmpmr7kxnpd/ckpts
```

**Comment by nate-wandb** [comment]
Hi @angadkalra, does `/tmp/tmpmr7kxnpd/ckpts` exist on your machine? It looks like it may be expecting a file and not a dir. 

CC: @andrewtruong

**Comment by andrewtruong** [comment]
Hey @angadkalra, it seems like you're generating some data to test this out.  If that's the case, can you please share:

1. The script you're using to add data to MLFlow
2. The script you're using to import data from MLFlow into W&B?

That will make debugging a lot easier.  Thanks!

**Comment by angadkalra** [comment]
@andrewtruong I'm not generating any extra data to test this out. I have 10 experiments with a few runs each already in our MLFlow server from past projects, and I'm just trying to port some of the important ones over. 

This is the exact code I'm using to import mlflow runs into wandb:

```python
from wandb.apis.importers import MlflowImporter

overrides = {"entity": "imvaria", "project": "TESTING"}
importer = MlflowImporter(mlflow_tracking_uri="https://mlflow.imvaria.com/")

all_runs = list(importer.download_all_runs())
testing_runs = [run for run in all_runs if run.run.info.experiment_id == '41']

[importer.import_one(run, overrides=overrides) for run in testing_runs]
```

**Comment by angadkalra** [comment]
> Hi @angadkalra, does `/tmp/tmpmr7kxnpd/ckpts` exist on your machine? It looks like it may be expecting a file and not a dir.
> 
> CC: @andrewtruong

This path exists on my machine but I never created it explicitly and it seems to contain the artifacts for a single experiment run in MLFlow...I have no idea why or how it got created...and I'm not referencing it in my code at all

**Comment by angadkalra** [comment]
So the artifacts contained in the dir /tmp/tmpmr7kxnpd/ are the exact artifacts that failed to get imported over when I tried importing a single run from MLFlow into WandB. It's the first run in my experiment in MLFlow with ID == '41'. So maybe the wandb script is creating this directory while it's importing?

**Comment by nate-wandb** [comment]
Hi @angadkalra, for a little background we don't typically write to `/tmp` unless the `WANDB_DIR` either doesn't exist or is unwritable. Could you try setting the env variable `WANDB_DIR` to a directory that exists and run again as a quick check?

**Comment by nate-wandb** [comment]
Hi @angadkalra, I just wanted to follow up and see if setting `WANDB_DIR` helped here?

**Comment by angadkalra** [comment]
This is the code I tried to execute:
```
from wandb.apis.importers import MlflowImporter

overrides = {"entity": "imvaria", "project": "TESTING"}
importer = MlflowImporter(mlflow_tracking_uri="https://mlflow.imvaria.com/")

all_runs = list(importer.download_all_runs())
testing_runs = [run for run in all_runs if run.run.info.experiment_id == '41']
importer.import_one(testing_runs[1])
```

This is the current error I get:

```
403 response executing GraphQL.                                                                                                                                                                                                                                                                                               
{"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}                                                                                                                                                                                    
wandb: ERROR Error while calling W&B API: permission denied (<Response [403]>)                                                                                                                                                                                                                                                
It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)                                                                
Traceback (most recent call last):                                                                                                                                                                                                                                                                                            
  File "/home/angad_imvaria_com/.conda/envs/model-training/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__                                                                                                                                                                                         
    result = self._call_fn(*args, **kwargs)                                                                                                                                                                                                                                                                                   
  File "/home/angad_imvaria_com/.conda/envs/model-training/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 285, in execute                                                                                                                                                                              
    return self.client.execute(*args, **kwargs)  # type: ignore                                                                                                                                                                                                                                                               
  File "/home/angad_imvaria_com/.conda/envs/model-training/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute                                                                                                                                                                       
    result = self._get_result(document, *args, **kwargs)                                                                                                                                                                                                                                                                      
  File "/home/angad_imvaria_com/.conda/envs/model-training/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result                                                                                                                                                                   
    return self.transport.execute(document, *args, **kwargs)                                                                                                                                                                                                                                                                  
  File "/home/angad_imvaria_com/.conda/envs/model-training/lib/python3.9/site-packages/wandb/sdk/lib/gql_request.py", line 56, in execute                                                                                                                                                                                     
    request.raise_for_status()                                                                                                                                                                                                                                                                                                
  File "/home/angad_imvaria_com/.conda/envs/model-training/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status                                                                                                                                                                                    
    raise HTTPError(http_error_msg, response=self)                                                                                                                                                                                                                                                                            
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.wandb.ai/graphql                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                              
During handling of the above exception, another exception occurred:                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                              
Traceback (most recent call last):                                                                                                                                                                                                                                                                                            
  File "/home/angad_imvaria_com/.conda/envs/model-training/lib/python3.9/site-packages/wandb/sdk/internal/sender.py", line 977, in send_run
self._init_run(run, config_value_dict)
  File "/home/angad_imvaria_com/.conda/envs/model-training/lib/python3.9/site-packages/wandb/sdk/internal/sender.py", line 1015, in _init_run
    server_run, inserted, server_messages = self._api.upsert_run(
  File "/home/angad_imvaria_com/.conda/envs/model-training/lib/python3.9/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/home/angad_imvaria_com/.conda/envs/model-training/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/angad_imvaria_com/.conda/envs/model-training/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 1690, in upsert_run
    response = self.gql(
  File "/home/angad_imvaria_com/.conda/envs/model-training/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 257, in gql
    ret = self._retry_gql(
  File "/home/angad_imvaria_com/.conda/envs/model-training/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/home/angad_imvaria_com/.conda/envs/model-training/lib/python3.9/site-packages/wandb/util.py", line 907, in check_retry_fn
    return fallback_retry_fn(e)
  File "/home/angad_imvaria_com/.conda/envs/model-training/lib/python3.9/site-packages/wandb/util.py", line 849, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
Traceback (most recent call last):
  File "/imvaria/data/import_mlflow_into_wandb.py", line 8, in <module>
    importer.import_one(testing_runs[1])
  File "/home/angad_imvaria_com/.conda/envs/model-training/lib/python3.9/site-packages/wandb/apis/importers/mlflow.py", line 108, in import_one
    super().import_one(run, overrides)
  File "/home/angad_imvaria_com/.conda/envs/model-training/lib/python3.9/site-packages/wandb/apis/importers/base.py", line 301, in import_one
    self._import_one(run)
  File "/home/angad_imvaria_com/.conda/envs/model-training/lib/python3.9/site-packages/wandb/apis/importers/base.py", line 311, in _import_one
    sm.send(run._make_artifact_record())
  File "/home/angad_imvaria_com/.conda/envs/model-training/lib/python3.9/site-packages/wandb/apis/importers/base.py", line 196, in _make_artifact_record
    art = wandb.Artifact(self.display_name(), "imported-artifacts")
File "/home/angad_imvaria_com/.conda/envs/model-training/lib/python3.9/site-packages/wandb/sdk/wandb_artifacts.py", line 169, in __init__
    raise ValueError(
ValueError: Artifact name may only contain alphanumeric characters, dashes, underscores, and dots. Invalid name: "Train-Val split version 3 ResNet-50 with Lung vs Rest - confusing labels - Train data - 3 sites val - SSA 3.1.6"
```

**Comment by nate-wandb** [comment]
@angadkalra, could you try setting your API key in the Env variable `WANDB_API_KEY`? 

Also, it may be worth trying to log this to your personal entity instead of the team. I see, that you should have access to the team but this could be a bug.

**Comment by angadkalra** [comment]
@nate-wandb My API key is set already. I'm able to train models and log all metrics, parameters, and ckpts to my wandb server.

**Comment by andrewtruong** [comment]
Hey @angadkalra, the error you're getting looks like this line here:
```
ValueError: Artifact name may only contain alphanumeric characters, dashes, underscores, and dots. Invalid name: "Train-Val split version 3 ResNet-50 with Lung vs Rest - confusing labels - Train data - 3 sites val - SSA 3.1.6"
```

This contains invalid characters which previously should have failed, but we added a [fix a few weeks ago](https://github.com/wandb/wandb/pull/5416/files#diff-5cb72252e743f18ba3ec3fc2a96f4e21d4b777bdcac183494a4bc745eba6f9bbR266-R270) that should have addressed this.

Can you please confirm you're using that branch?  I think one way to identify this in your code is to check if the helper function exists and changes the name as we expect.
```python
run = testing_runs[0]
name = "Train-Val split version 3 ResNet-50 with Lung vs Rest - confusing labels - Train data - 3 sites val - SSA 3.1.6"
result = run._handle_incompatible_strings(name)

result
```

Alternatively, the next release is Tuesday, June 6th.  After that time you can pip install wandb directly

**Comment by angadkalra** [comment]
@andrewtruong Thanks for the reply! 

I didn't realize the branch named changed from "fixes" to "118", so I had installed latest version of wandb instead...I'll re-install the merged branch and try my code again.

**Comment by andrewtruong** [comment]
Can you try this in your own personal entity?  I think that should work.

If it does, try making yourself an admin of the Imvaria entity and then importing to that.

![image](https://github.com/wandb/wandb/assets/15385696/9ce20192-6046-4d95-a217-ca40d811c920)

**Comment by angadkalra** [comment]
@andrewtruong I'm the only member and I'm an admin:

![Screenshot 2023-06-02 at 9 38 23 AM](https://github.com/wandb/wandb/assets/8902328/5d97570d-ea98-44a1-b17c-85c5fb734249)

**Comment by angadkalra** [comment]
@andrewtruong So I tried on personal entity:

Tried this first:
![Screenshot 2023-06-05 at 11 23 27 AM](https://github.com/wandb/wandb/assets/8902328/e56cc9ad-bcc4-406b-9123-c0b4f64fe245)

Then tried importing a single mlflow run:
```
403 response executing GraphQL.                                                                                                                                                                                                                                                                                               
{"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}                                                                                                                                                                                    
wandb: ERROR Error while calling W&B API: permission denied (<Response [403]>)                                                                                                                                                                                                                                                
It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)                                                                
Traceback (most recent call last):                                                                                                                                                                                                                                                                                            
  File "/home/angad_imvaria_com/.local/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__                                                                                                                                                                                                             
    result = self._call_fn(*args, **kwargs)                                                                                                                                                                                                                                                                                   
  File "/home/angad_imvaria_com/.local/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 320, in execute                                                                                                                                                                                                  
    return self.client.execute(*args, **kwargs)  # type: ignore                                                                                                                                                                                                                                                               
  File "/home/angad_imvaria_com/.local/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute                                                                                                                                                                                           
    result = self._get_result(document, *args, **kwargs)                                                                                                                                                                                                                                                                      
  File "/home/angad_imvaria_com/.local/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result                                                                                                                                                                                       
    return self.transport.execute(document, *args, **kwargs)                                                                                                                                                                                                                                                                  
  File "/home/angad_imvaria_com/.local/lib/python3.9/site-packages/wandb/sdk/lib/gql_request.py", line 56, in execute
    request.raise_for_status()
  File "/home/angad_imvaria_com/.conda/envs/model-training/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/angad_imvaria_com/.local/lib/python3.9/site-packages/wandb/sdk/internal/sender.py", line 953, in send_run
    self._init_run(run, config_value_dict)
  File "/home/angad_imvaria_com/.local/lib/python3.9/site-packages/wandb/sdk/internal/sender.py", line 991, in _init_run
    server_run, inserted, server_messages = self._api.upsert_run(
  File "/home/angad_imvaria_com/.local/lib/python3.9/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/home/angad_imvaria_com/.local/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/angad_imvaria_com/.local/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 1727, in upsert_run
    response = self.gql(
  File "/home/angad_imvaria_com/.local/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 292, in gql
    ret = self._retry_gql(
  File "/home/angad_imvaria_com/.local/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/home/angad_imvaria_com/.local/lib/python3.9/site-packages/wandb/util.py", line 908, in check_retry_fn
    return fallback_retry_fn(e)
  File "/home/angad_imvaria_com/.local/lib/python3.9/site-packages/wandb/util.py", line 850, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
```

**Comment by angadkalra** [comment]
My WANDB_DIR is set but it keeps trying to write to /tmp:

```
Traceback (most recent call last):
  File "/imvaria/data/import_mlflow_into_wandb.py", line 8, in <module>
    importer.import_one(testing_runs[1])
  File "/home/angad_imvaria_com/.local/lib/python3.9/site-packages/wandb/apis/importers/mlflow.py", line 123, in import_one
    super().import_one(run, overrides)
  File "/home/angad_imvaria_com/.local/lib/python3.9/site-packages/wandb/apis/importers/base.py", line 316, in import_one
    self._import_one(run)
  File "/home/angad_imvaria_com/.local/lib/python3.9/site-packages/wandb/apis/importers/base.py", line 326, in _import_one
    sm.send(run._make_artifact_record())
  File "/home/angad_imvaria_com/.local/lib/python3.9/site-packages/wandb/apis/importers/base.py", line 202, in _make_artifact_record
    art.add_file(path, name)
  File "/home/angad_imvaria_com/.local/lib/python3.9/site-packages/wandb/sdk/artifacts/local_artifact.py", line 377, in add_file
    raise ValueError("Path is not a file: %s" % local_path)
ValueError: Path is not a file: /tmp/tmpvfy3g_my/ckpts
```

**Comment by angadkalra** [comment]
@andrewtruong any idea?

**Comment by nate-wandb** [comment]
@angadkalra, when you ran this to your personal entity did you set entity in the overrides argument? If so, could you try not setting this? I can move the project for you if we find that this works. I just want to see if this is related to using the entity argument.

**Comment by angadkalra** [comment]
> Hi @angadkalra, I wanted to see if you still wanted to investigate this and if you had a chance to try the above?

Yes I will try ASAP, sorry for the delay!

**Comment by angadkalra** [comment]
@nate-wandb So I tried not setting the entity argument and same error happens. I think this is what the problem is:
```
File "/home/angad/.local/lib/python3.9/site-packages/wandb/apis/importers/base.py", line 202, in _make_artifact_record                         
  art.add_file(path, name)
```

So path is /tmp/tmpw3188232/ckpts, and that dir has all the ckpts from the MLFlow run I'm trying to import, but it contains 5 files and art.add_file(...) isn't working because it thinks path is a file and not a dir. I think you need to loop through all files in path dir.

**Comment by angadkalra** [comment]
> Hi @angadkalra, this makes sense. We have a function art.add_dir() as well that it looks like we need to apply if the path is a directory rather than pointing to a single file. I've submitted a ticket to the engineering team and can follow up once we have a fix on this.
> 
> Thank you, Nate

Thanks so much! Please let me know when fixed.

**Comment by tristan-spaulding2** [comment]
Hi @angadkalra , just wanted to confirm if this issue was resolved with the release around June 6th, or if you're still encountering issues.  Thanks.

**Comment by angadkalra** [comment]
@tristan-spaulding2 hey! I will update to the latest and rerun my code. Feel free to close this issue because I probably won't be able to test for a while! I can always reopen if this problem persists.

Thanks for your work!
