### ISSUE TITLE
[Q] wandb ValueError

### ISSUE THREAD

**Issue by JainRohan** [wandb/wandb#5364]
I'm working with a codebase: https://github.com/samuela/git-re-basin.

Trying to reproduce the plots for `cifar10_mlp_weight_matching.py` using Weights & Biases with compiling script: `python src/cifar10_mlp_weight_matching.py --model-a mlp_0 --model-b mlp_1 --load-epoch 10`. However, resulting in a wandb ValueError that the project doesn't contain artifact. Shown below:

`wandb: ERROR Project <entity>/<project> does not contain artifact: "cifar10-mlp-weights:mlp_0"`

**Comment by ArtsiomWB** [comment]
Hi @JainRohan! Could you send over the full error logs in here?

**Comment by JainRohan** [comment]
> 

Hi @ArtsiomWB, here is the full error log

```
user@8f2d9c0b99f0:~/git-re-basin$ python src/cifar10_mlp_weight_matching.py --model-a mlp_0 --model-b mlp_1 --load-epoch 10
/home/user/.local/lib/python3.8/site-packages/flax/core/frozen_dict.py:169: FutureWarning: jax.tree_util.register_keypaths is deprecated, and will be removed in a future release. Please use `register_pytree_with_keys()` instead.
  jax.tree_util.register_keypaths(
WARNING:tensorflow:Deprecation warnings have been disabled. Set TF_ENABLE_DEPRECATION_WARNINGS=1 to re-enable them.
2023-04-19 00:08:43.788635: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:268] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
wandb: Currently logged in as: rohan-jain1. Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.14.2
wandb: Run data is saved locally in /home/user/git-re-basin/wandb/run-20230419_000846-boa0m8mj
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run pleasant-microwave-20
wandb: ⭐️ View project at https://wandb.ai/rohan-jain1/sparse-git-rebasin
wandb: 🚀 View run at https://wandb.ai/rohan-jain1/sparse-git-rebasin/runs/boa0m8mj
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: 🚀 View run pleasant-microwave-20 at: https://wandb.ai/rohan-jain1/sparse-git-rebasin/runs/boa0m8mj
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 2 other file(s)
wandb: Find logs at: ./wandb/run-20230419_000846-boa0m8mj/logs
wandb: ERROR Project rohan-jain1/sparse-git-rebasin does not contain artifact: "cifar10-mlp-weights:mlp_0"
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/wandb/apis/public.py", line 957, in artifact
    artifact = Artifact(self.client, entity, project, artifact_name)
  File "/home/user/.local/lib/python3.8/site-packages/wandb/apis/public.py", line 4355, in __init__
    self._load()
  File "/home/user/.local/lib/python3.8/site-packages/wandb/apis/public.py", line 5082, in _load
    raise ValueError(
ValueError: Project rohan-jain1/sparse-git-rebasin does not contain artifact: "cifar10-mlp-weights:mlp_0"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/cifar10_mlp_weight_matching.py", line 237, in <module>
    main()
  File "src/cifar10_mlp_weight_matching.py", line 135, in main
    wandb_run.use_artifact(f"cifar10-mlp-weights:{config.model_a}").get_path(
  File "/home/user/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 344, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 334, in wrapper
    return func(self, *args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2675, in use_artifact
    artifact = public_api.artifact(type=type, name=name)
  File "/home/user/.local/lib/python3.8/site-packages/wandb/apis/normalize.py", line 87, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "/home/user/.local/lib/python3.8/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/wandb/apis/public.py", line 957, in artifact
    artifact = Artifact(self.client, entity, project, artifact_name)
  File "/home/user/.local/lib/python3.8/site-packages/wandb/apis/public.py", line 4355, in __init__
    self._load()
  File "/home/user/.local/lib/python3.8/site-packages/wandb/apis/public.py", line 5082, in _load
    raise ValueError(
wandb.errors.CommError: Project rohan-jain1/sparse-git-rebasin does not contain artifact: "cifar10-mlp-weights:mlp_0"
```

**Comment by JainRohan** [comment]
I fixed it!
