### ISSUE TITLE
[CLI]: Crashes keras in python 3.7

### ISSUE THREAD

**Issue by nathanieltagg** [wandb/wandb#5398]
### Describe the bug

I tried the quickstart for Keras in a training of EfficientPose by adding the WandbMetricsLogger to the callbacks.

```python
    callbacks.append( WandbMetricsLogger() )


```

```shell
Traceback (most recent call last):
  File "train.py", line 379, in <module>
    main()
  File "train.py", line 205, in main
    validation_data = validation_generator
  File "/home/ntagg/miniconda3/envs/eff/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 1296, in fit_generator
    steps_name='steps_per_epoch')
  File "/home/ntagg/miniconda3/envs/eff/lib/python3.7/site-packages/wandb/integration/keras/keras.py", line 166, in new_generator
    return old_generator(*args, **kwargs)
  File "/home/ntagg/miniconda3/envs/eff/lib/python3.7/site-packages/wandb/integration/keras/keras.py", line 166, in new_generator
    return old_generator(*args, **kwargs)
  File "/home/ntagg/miniconda3/envs/eff/lib/python3.7/site-packages/wandb/integration/keras/keras.py", line 166, in new_generator
    return old_generator(*args, **kwargs)
  File "/home/ntagg/miniconda3/envs/eff/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_generator.py", line 332, in model_iteration
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/ntagg/miniconda3/envs/eff/lib/python3.7/site-packages/tensorflow_core/python/keras/callbacks.py", line 299, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/ntagg/miniconda3/envs/eff/lib/python3.7/site-packages/wandb/integration/keras/callbacks/metrics_logger.py", line 105, in on_epoch_end
    lr = self._get_lr()
  File "/home/ntagg/miniconda3/envs/eff/lib/python3.7/site-packages/wandb/integration/keras/callbacks/metrics_logger.py", line 90, in _get_lr
    return float(self.model.optimizer.learning_rate.numpy().item())
  File "/home/ntagg/miniconda3/envs/eff/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py", line 579, in numpy
    "numpy() is only available when eager execution is enabled.")
NotImplementedError: numpy() is only available when eager execution is enabled.
w
```

### Environment

WandB version: 0.15

OS: Ubuntu 20.04

Python version: 3.7

Versions of relevant libraries:
Tensoflow 1.15

**Comment by kptkin** [comment]
@nathanieltagg Thanks for reporting this issue, it seems to fail since the code assume eager execution and you are using tf1.
Is it a strong requirement for you to use tf1? 
- If not could you update to tf2, i think there are documentation on the tf site with the migration process.
- If it is could you enable eager execution and see if this solve your issue: `tf.compat.v1.enable_eager_execution()` you can achieve this by adding to the top of your script see [here ](https://www.tensorflow.org/api_docs/python/tf/compat/v1/enable_eager_execution).

We will also try to investigate if there is an easy way to support tf1 with the above code.

Please let me know if any of the above helped

**Comment by MBakirWB** [comment]
Hi @nathanieltagg , following up on this issue. Did @kptkin's suggestion to upgrade to tf2 address this issue?

**Comment by MBakirWB** [comment]
Hi @nathanieltagg, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
