### ISSUE TITLE
[App]: tox -e 'mypy-report' failed about wandb@0.15.2 on centos8_aarch64

### ISSUE THREAD

**Issue by Tom-python0121** [wandb/wandb#5532]
### Current Behavior

tox -e 'mypy-report' failed about wandb@0.15.2 on centos8_aarch64.
### Steps to reproduce the issue

```console
[root@localhost spack-src]#tox -e 'mypy-report'
mypy-report: commands[0]> pycobertura show --format text mypy-results/cobertura.xml
Traceback (most recent call last):
  File "/home/stage/root/spack-stage-py-wandb-0.15.1-liy367rhoqf463pejuhgltxgp5hdbs6f/spack-src/.tox/mypy-report/bin/pycobertura", line 8, in <module>
    sys.exit(pycobertura())
  File "/home/stage/root/spack-stage-py-wandb-0.15.1-liy367rhoqf463pejuhgltxgp5hdbs6f/spack-src/.tox/mypy-report/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/stage/root/spack-stage-py-wandb-0.15.1-liy367rhoqf463pejuhgltxgp5hdbs6f/spack-src/.tox/mypy-report/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/stage/root/spack-stage-py-wandb-0.15.1-liy367rhoqf463pejuhgltxgp5hdbs6f/spack-src/.tox/mypy-report/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/stage/root/spack-stage-py-wandb-0.15.1-liy367rhoqf463pejuhgltxgp5hdbs6f/spack-src/.tox/mypy-report/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/stage/root/spack-stage-py-wandb-0.15.1-liy367rhoqf463pejuhgltxgp5hdbs6f/spack-src/.tox/mypy-report/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/stage/root/spack-stage-py-wandb-0.15.1-liy367rhoqf463pejuhgltxgp5hdbs6f/spack-src/.tox/mypy-report/lib/python3.8/site-packages/pycobertura/cli.py", line 135, in show
    cobertura = Cobertura(
  File "/home/stage/root/spack-stage-py-wandb-0.15.1-liy367rhoqf463pejuhgltxgp5hdbs6f/spack-src/.tox/mypy-report/lib/python3.8/site-packages/pycobertura/cobertura.py", line 67, in __init__
    raise self.InvalidCoverageReport("Invalid coverage file: {}".format(report))
pycobertura.cobertura.InvalidCoverageReport: Invalid coverage file: mypy-results/cobertura.xml
mypy-report: exit 1 (0.24 seconds) /home/stage/root/spack-stage-py-wandb-0.15.1-liy367rhoqf463pejuhgltxgp5hdbs6f/spack-src> pycobertura show --format text mypy-results/cobertura.xml pid=3204836
  mypy-report: FAIL code 1 (0.33=setup[0.09]+cmd[0.24] seconds)
  evaluation failed :( (0.98 seconds)
```

### Expected Behavior

the test can passed.

### Steps To Reproduce

spack install --keep-stage -v py-wandb@0.15.2 py-pip
spack load py-wandb@0.15.2 py-pip
spack cd py-wandb@0.15.2
pip install tox
tox -e 'mypy-report'

### Environment

OS:linux-centos8-aarch64

Browsers:google

Version:0.15.2

**Comment by fdsig** [comment]
Hi @Tom-python0121 , 

Thanks for messaging in with this. I can see from your stack trace that this failed on 0.15.1 and wonder if you would be able to confirm if tests successfully ran on versions previous to this such as 0.15.0? 

For Clarity, while we do run extensive testing, we don't normally test in the way you have described and therefore would want to understand if this is something that is new on your side and has occurred after having been able to run successfully in the past.

**Comment by Tom-python0121** [comment]
@fdsig I tested the previous versions 0.15.0 and 0.13.10 and found that the test case reported the same error.

**Comment by fdsig** [comment]
Hi @Tom-python0121 , Thanks for updating this I have spoken with the eng team who maintain our SDK, and looks like we don't currently support testing in the way that you describe. 

We outline how to test as an open-source contribution in the [testing section](https://github.com/wandb/wandb/blob/main/CONTRIBUTING.md#testing)  of our [CONTRIBUTING.md](https://github.com/wandb/wandb/blob/main/CONTRIBUTING.md) which uses tox.

I can submit a feature request for you here but would be grateful if you would be able to outline what type of tests you are running and give some context on your use case -- eg why you are installing with a 'spack' install and then testing with tox and if your 'spack' install of wandb working for you but just failing a test?

Look forward to hearing back!

**Comment by thanos-wandb** [comment]
Hi @Tom-python0121 since we haven't heard back from you, we're going to temporarily close this ticket for now. Please feel free to reopen this and provide us with any additional information so that we could proceed with a feature request.
