### ISSUE TITLE
[CLI]: assert magic == ord("W")

### ISSUE THREAD

**Issue by koaning** [wandb/wandb#5536]
### Describe the bug

I'm running wandb in Github codespaces and after launching the deamon via `wandb init` ... it starts giving me errors in the background. It's this one: 

```
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/codespace/.local/lib/python3.10/site-packages/wandb/sdk/service/server_sock.py", line 100, in run
    sreq = self._sock_client.read_server_request()
  File "/home/codespace/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 274, in read_server_request
    data = self._read_packet_bytes()
  File "/home/codespace/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 248, in _read_packet_bytes
    rec = self._extract_packet_bytes()
  File "/home/codespace/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 230, in _extract_packet_bytes
    assert magic == ord("W")
AssertionError
```

Every few seconds it pops up. No idea what's causing it. I can still use the terminal, but this is printed every few seconds. 

### Environment

WandB version:

wandb, version 0.15.2

OS:

linux 

Python version:

3.10.4

**Comment by nate-wandb** [comment]
Hi @koaning, sorry you are running into this. Could you possibly share the `debug-internal.log` and `debug.log` files from a run where you are seeing this? These are found in the local run folder in the logs directory. 

Also, have you seen this in any other environments or only in Codespaces?

**Comment by nate-wandb** [comment]
Hi @koaning, I just wanted to follow up and see if you were able to look into the above?

**Comment by koaning** [comment]
Sorry for the late reply. I've been swamped with other work and have not been able to get back to this one. We can also close this one for now and should I see it again I'll gladly come back with more info.

**Comment by woshiyyya** [comment]
Any update on this issue?

**Comment by woshiyyya** [comment]
I got the same error. I've attached my logs files below:

[debug.log](https://github.com/wandb/wandb/files/13993600/debug.log)
[debug-internal.log](https://github.com/wandb/wandb/files/13993601/debug-internal.log)
