### ISSUE TITLE
[CLI]: wandb: Network error (ConnectTimeout), entering retry loop

### ISSUE THREAD

**Issue by cs-mshah** [wandb/wandb#5550]
### Describe the bug

I get frequent connection issues about Network timeouts from my wandb cli on my DGX server. I don't have issues elsewhere.

```shell
wandb: Network error (ConnectTimeout), entering retry loop.
```

### Environment

WandB version:0.15.0

OS: NVIDIA DGX Server Version 5.3.1 (GNU/Linux 5.4.0-113-generic x86_64)

Python version: Python 3.9.16

Versions of relevant libraries:
PyTorch

### Additional Context

I have even tried the following: 
https://docs.wandb.ai/guides/technical-faq/troubleshooting#how-do-i-deal-with-network-issues
`wandb.init(settings=wandb.Settings(start_method="fork"))`

**Comment by rsanandres-wandb** [comment]
Hello @cs-mshah !

When we see `Network error (ConnectTimeout)` Errors, it is normally due to something blocking the connection specifically to `wandb` such as a VPN, Proxy, or a load balancer. However, I can look into the logs and make sure that the error isn't due to something else.

Could you get the debug logs? The `debug.log` and `debug-internal.log` files can be found in the wandb folder, which is located in the same directory where the script was executed. Inside the wandb folder, you'll find subfolders with names in the format "run-DATETIME-ID," each associated with a single run. Could you gather the debug logs for one of the failed runs and send it to me?

**Comment by cs-mshah** [comment]
here is the debug.log:
```
2023-05-12 10:17:03,593 INFO    MainThread:3208098 [wandb_setup.py:_flush():76] Configure stats pid to 3208098
2023-05-12 10:17:03,593 INFO    MainThread:3208098 [wandb_setup.py:_flush():76] Loading settings from /home/dgxadmin/.config/wandb/settings
2023-05-12 10:17:03,593 INFO    MainThread:3208098 [wandb_setup.py:_flush():76] Loading settings from /home/dgxadmin/Manan/CrossDomainGCD/OpenLDN/wandb/settings
2023-05-12 10:17:03,593 INFO    MainThread:3208098 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'api_key': '***REDACTED***', 'mode': 'offline'}
2023-05-12 10:17:03,593 INFO    MainThread:3208098 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-05-12 10:17:03,593 INFO    MainThread:3208098 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'train.py', 'program': '/home/dgxadmin/Manan/CrossDomainGCD/OpenLDN/train.py'}
2023-05-12 10:17:03,593 INFO    MainThread:3208098 [wandb_init.py:_log_setup():507] Logging user logs to /home/dgxadmin/Manan/CrossDomainGCD/OpenLDN/wandb/offline-run-20230512_101703-wzzbma81/logs/debug.log
2023-05-12 10:17:03,593 INFO    MainThread:3208098 [wandb_init.py:_log_setup():508] Logging internal logs to /home/dgxadmin/Manan/CrossDomainGCD/OpenLDN/wandb/offline-run-20230512_101703-wzzbma81/logs/debug-internal.log
2023-05-12 10:17:03,593 INFO    MainThread:3208098 [wandb_init.py:init():547] calling init triggers
2023-05-12 10:17:03,593 INFO    MainThread:3208098 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {'description': 'dann', 'data_root': 'data/pacs', 'run_started': '12-05-23_1017', 'out': 'outputs/dataset_pacs_arch_resnet50_no_novel_3_dann_12-05-23_1017', 'no_progress': False, 'dataset': 'pacs', 'no_class': 7, 'lbl_percent': 100, 'no_novel': 3, 'create_splits': False, 'train_domain': 'photo', 'test_domain': 'art_painting', 'train_split': 0.0, 'arch': 'resnet50', 'pretrained': 'swav_800ep_pretrain.pth.tar', 'epochs': 20, 'batch_size': 32, 'img_size': 224, 'num_workers': 64, 'resume': '', 'seed': 0, 'iteration': 1000, 'optimizer': 'adam', 'lr': 0.01, 'momentum': 0.9, 'weight_decay': 0.001, 'scheduler': 'lambda', 'lr_gamma': 0.001, 'lr_decay': 0.75, 'method': 'dann', 'bottleneck_dim': 256, 'temp': 0.07, 'disk_dataset_path': '/home/dgxadmin/datasets', 'tsne': False, 'tsne_freq': 10, 'no_known': 4, 'exp_name': 'dataset_pacs_arch_resnet50_no_novel_3_dann_12-05-23_1017', 'n_gpu': 1}
2023-05-12 10:17:03,593 INFO    MainThread:3208098 [wandb_init.py:init():595] starting backend
2023-05-12 10:17:03,593 INFO    MainThread:3208098 [wandb_init.py:init():599] setting up manager
2023-05-12 10:17:03,598 INFO    MainThread:3208098 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: fork
2023-05-12 10:17:03,601 INFO    MainThread:3208098 [wandb_init.py:init():605] backend started and connected
2023-05-12 10:17:03,609 INFO    MainThread:3208098 [wandb_init.py:init():695] updated telemetry
2023-05-12 10:17:03,699 INFO    MainThread:3208098 [wandb_init.py:init():782] starting run threads in backend
2023-05-12 10:17:08,555 INFO    MainThread:3208098 [wandb_run.py:_console_start():2157] atexit reg
2023-05-12 10:17:08,555 INFO    MainThread:3208098 [wandb_run.py:_redirect():2012] redirect: SettingsConsole.WRAP_RAW
2023-05-12 10:17:08,555 INFO    MainThread:3208098 [wandb_run.py:_redirect():2077] Wrapping output streams.
2023-05-12 10:17:08,555 INFO    MainThread:3208098 [wandb_run.py:_redirect():2102] Redirects installed.
2023-05-12 10:17:08,556 INFO    MainThread:3208098 [wandb_init.py:init():824] run started, returning control to user process
2023-05-12 12:08:28,875 WARNING MsgRouterThr:3208098 [router.py:message_loop():77] message_loop has been closed
```

here is the [`debug-internal.log`](https://pastebin.com/TBX00v3z)

**Comment by cs-mshah** [comment]
I had to shift the wandb folder to another machine and sync from there using `wandb sync --sync-all`. There were Network errors there too, but it eventually got uploaded after a long wait. Before it used to happen almost immediately.

**Comment by Yoega** [comment]
I met the same "Network error (ConnectTimeout), entering retry loop" problem. I have set the mode to offline. When I tried to synchronize my finished run to the cloud, I even got the Network error problem!!! How can I deal with it?

**Comment by rsanandres-wandb** [comment]
Networks tend to be vague unless we trace the logs of the run. As mentioned before, the most common culprits are VPN, Proxy, or a load balance which are blocking or slowing dow the connection between the client and `wandb`. The `debug.log` and `debug-internal.log` are good places to start for debugging why the Network error may be happening. The `debug.log` and `debug-internal.log` files can be found in the wandb folder within the same directory where the script was executed. Within the wandb folder, there are multiple folders named `run-DATETIME-ID`, each corresponding to a specific run.

**Comment by Lily-Le** [comment]
How to solve such problems? The connection becomes terrible suddenly. With and without a VPN result in the same 'connection timeout' error in wandb.init

**Comment by kptkin** [comment]
@Lily-Le you could increase the init timeout using the following settings: `wandb.init(settings=dict(init_timeout=120))`
or whatever value you need, based on the networks issues, note the new default is 90 sec.

**Comment by leileilin** [comment]
@kptkin 
This error also occurs when I use deepspeed multi-machine training.
Here is the debug.log:
2025-05-12 14:41:52,861 INFO    MainThread:31138 [wandb_setup.py:_flush():69] setting env: {}
2025-05-12 14:41:52,861 INFO    MainThread:31138 [wandb_setup.py:_flush():69] setting login settings: {}
2025-05-12 14:41:52,861 INFO    MainThread:31138 [wandb_init.py:_log_setup():337] Logging user logs to /nlp_group/linlei/llm_train_code/ms-swift/wandb/run-20250512_144152-h91h8p0c/logs/debug.log
2025-05-12 14:41:52,861 INFO    MainThread:31138 [wandb_init.py:_log_setup():338] Logging internal logs to /nlp_group/linlei/llm_train_code/ms-swift/wandb/run-20250512_144152-h91h8p0c/logs/debug-internal.log
2025-05-12 14:41:52,861 INFO    MainThread:31138 [wandb_init.py:init():370] calling init triggers
2025-05-12 14:41:52,861 INFO    MainThread:31138 [wandb_init.py:init():375] wandb.init called with sweep_config: {}
config: {}
2025-05-12 14:41:52,861 INFO    MainThread:31138 [wandb_init.py:init():419] starting backend
2025-05-12 14:41:52,861 INFO    MainThread:31138 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-05-12 14:41:52,874 INFO    MainThread:31138 [backend.py:ensure_launched():135] starting backend process...
2025-05-12 14:41:52,879 INFO    MainThread:31138 [backend.py:ensure_launched():139] started backend process with pid: 33356
2025-05-12 14:41:52,880 INFO    MainThread:31138 [wandb_init.py:init():424] backend started and connected
2025-05-12 14:41:52,881 INFO    MainThread:31138 [wandb_init.py:init():472] updated telemetry
2025-05-12 14:41:52,882 INFO    MainThread:31138 [wandb_init.py:init():491] communicating current version
2025-05-12 14:41:57,882 INFO    MainThread:31138 [wandb_init.py:init():504] communicating run to backend with 30 second timeout
2025-05-12 14:42:20,940 ERROR   Thread-5 (wrapped_target):31138 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "/share/miniconda3/envs/llm_train_swift/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/share/miniconda3/envs/llm_train_swift/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/share/miniconda3/envs/llm_train_swift/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/share/miniconda3/envs/llm_train_swift/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/share/miniconda3/envs/llm_train_swift/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/share/miniconda3/envs/llm_train_swift/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/share/miniconda3/envs/llm_train_swift/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/share/miniconda3/envs/llm_train_swift/lib/python3.10/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f8b9de062c0>, 'Connection to api.wandb.ai timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/share/miniconda3/envs/llm_train_swift/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/share/miniconda3/envs/llm_train_swift/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/share/miniconda3/envs/llm_train_swift/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f8b9de062c0>, 'Connection to api.wandb.ai timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/share/miniconda3/envs/llm_train_swift/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/share/miniconda3/envs/llm_train_swift/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 130, in execute
    return self.client.execute(*args, **kwargs)
  File "/share/miniconda3/envs/llm_train_swift/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/share/miniconda3/envs/llm_train_swift/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/share/miniconda3/envs/llm_train_swift/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/share/miniconda3/envs/llm_train_swift/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/share/miniconda3/envs/llm_train_swift/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/share/miniconda3/envs/llm_train_swift/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/share/miniconda3/envs/llm_train_swift/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/share/miniconda3/envs/llm_train_swift/lib/python3.10/site-packages/requests/adapters.py", line 688, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f8b9de062c0>, 'Connection to api.wandb.ai timed out. (connect timeout=10)'))
2025-05-12 14:42:27,883 INFO    MainThread:31138 [interface.py:_communicate_run():656] couldn't get run from backend
2025-05-12 14:42:27,883 ERROR   MainThread:31138 [wandb_init.py:init():508] backend process timed out
2025-05-12 14:42:27,883 ERROR   MainThread:31138 [wandb_init.py:init():517] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
Here is the debug-internal.log:
2025-05-12 14:41:53,958 INFO    MainThread:33356 [internal.py:wandb_internal():88] W&B internal server running at pid: 33356, started at: 2025-05-12 14:41:53.957512
2025-05-12 14:41:53,960 DEBUG   HandlerThread:33356 [handler.py:handle_request():124] handle_request: check_version
2025-05-12 14:41:53,960 INFO    WriterThread:33356 [datastore.py:open_for_write():80] open: /nlp_group/linlei/llm_train_code/ms-swift/wandb/run-20250512_144152-h91h8p0c/run-h91h8p0c.wandb
2025-05-12 14:41:53,962 DEBUG   SenderThread:33356 [sender.py:send():179] send: header
2025-05-12 14:41:53,962 DEBUG   SenderThread:33356 [sender.py:send_request():193] send_request: check_version
2025-05-12 14:41:58,963 DEBUG   SenderThread:33356 [sender.py:send():179] send: run
2025-05-12 14:42:27,883 DEBUG   HandlerThread:33356 [handler.py:handle_request():124] handle_request: shutdown
2025-05-12 14:42:27,884 INFO    HandlerThread:33356 [handler.py:finish():658] shutting down handler
2025-05-12 14:42:27,886 INFO    WriterThread:33356 [datastore.py:close():288] close: /nlp_group/linlei/llm_train_code/ms-swift/wandb/run-20250512_144152-h91h8p0c/run-h91h8p0c.wandb
2025-05-12 14:42:32,287 ERROR   SenderThread:33356 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "/share/miniconda3/envs/llm_train_swift/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/share/miniconda3/envs/llm_train_swift/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/share/miniconda3/envs/llm_train_swift/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/share/miniconda3/envs/llm_train_swift/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/share/miniconda3/envs/llm_train_swift/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/share/miniconda3/envs/llm_train_swift/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/share/miniconda3/envs/llm_train_swift/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/share/miniconda3/envs/llm_train_swift/lib/python3.10/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f8b7c4a8fd0>, 'Connection to api.wandb.ai timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/share/miniconda3/envs/llm_train_swift/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/share/miniconda3/envs/llm_train_swift/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/share/miniconda3/envs/llm_train_swift/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f8b7c4a8fd0>, 'Connection to api.wandb.ai timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/share/miniconda3/envs/llm_train_swift/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/share/miniconda3/envs/llm_train_swift/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 130, in execute
    return self.client.execute(*args, **kwargs)
  File "/share/miniconda3/envs/llm_train_swift/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/share/miniconda3/envs/llm_train_swift/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/share/miniconda3/envs/llm_train_swift/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/share/miniconda3/envs/llm_train_swift/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/share/miniconda3/envs/llm_train_swift/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/share/miniconda3/envs/llm_train_swift/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/share/miniconda3/envs/llm_train_swift/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/share/miniconda3/envs/llm_train_swift/lib/python3.10/site-packages/requests/adapters.py", line 688, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f8b7c4a8fd0>, 'Connection to api.wandb.ai timed out. (connect timeout=10)'))
