### ISSUE TITLE
[CLI]: wandb login fails if typer is not installed

### ISSUE THREAD

**Issue by slitvinov** [wandb/wandb#5559]
If [Typer](https://typer.tiangolo.com) is not installed, running `wanb login `results in a vague error message.

```shell
$ wandb login
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/lisergey/.local/lib/python3.8/site-packages/wandb/__main__.py", line 1, in <module>
    from wandb.cli import cli
  File "/home/lisergey/.local/lib/python3.8/site-packages/wandb/cli/cli.py", line 933, in <module>
    def launch_sweep(
  File "/usr/lib/python3/dist-packages/click/core.py", line 1234, in decorator
    cmd = command(*args, **kwargs)(f)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 115, in decorator
    cmd = _make_command(f, name, attrs, cls)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 88, in _make_command
    return cls(name=name or f.__name__.lower().replace('_', '-'),
TypeError: __init__() got an unexpected keyword argument 'no_args_is_help'
```

It works after I install Typer.

```shell
$ python -m pip install typer
Collecting typer
  Using cached typer-0.9.0-py3-none-any.whl (45 kB)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/lisergey/.local/lib/python3.8/site-packages (from typer) (4.5.0)
Collecting click<9.0.0,>=7.1.1
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Installing collected packages: click, typer
Successfully installed click-8.1.3 typer-0.9.0
$ wandb login
wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize
wandb: Paste an API key from your profile and hit enter, or press ctrl+c to quit: 
```

### Environment

```shell
$ wandb --version
wandb, version 0.15.2
```

```shell
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

```shell
$ python -m pip freeze
appdirs==1.4.4
apturl==0.5.2
attrs==19.3.0
Automat==0.8.0
backcall==0.1.0
blinker==1.4
Brlapi==0.7.0
certifi==2019.11.28
cffi==1.15.1
chardet==3.0.4
chrome-gnome-shell==0.0.0
click==8.1.3
colorama==0.4.3
command-not-found==0.3
constantly==15.1.0
cryptography==38.0.1
cupshelpers==1.0
cycler==0.10.0
dbus-python==1.2.16
decorator==4.4.2
defer==1.0.6
deluge==2.0.3
distro==1.4.0
distro-info===0.23ubuntu1
docker-pycreds==0.4.0
entrypoints==0.3
fenics-basix==0.4.2
fenics-ffcx==0.4.2
fenics-ufl==2022.1.0
GeoIP==1.3.2
gitdb==4.0.10
GitPython==3.1.31
gpg===1.13.1-unknown
httplib2==0.14.0
hyperlink==19.0.0
idna==2.8
incremental==16.10.1
ipython==7.13.0
ipython-genutils==0.2.0
jedi==0.15.2
keyring==18.0.1
kiwisolver==1.0.1
language-selector==0.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.2
lazr.uri==1.0.3
llvmlite==0.31.0
louis==3.12.0
macaroonbakery==1.3.1
Mako==1.1.0
Markdown==3.1.1
MarkupSafe==1.1.0
matplotlib==3.1.2
meson==0.53.2
mpi4py==3.1.3
mpmath==1.1.0
netifaces==0.10.4
numba==0.48.0
numpy==1.17.4
oauthlib==3.1.0
olefile==0.46
packaging==20.3
parso==0.5.2
pathtools==0.1.2
petsc4py==3.12.0
petsc4py-complex==3.12.0
petsc4py-real==3.12.0
pexpect==4.6.0
pickleshare==0.7.5
Pillow==7.0.0
ply==3.11
prompt-toolkit==2.0.10
protobuf==4.23.0
psutil==5.9.5
pyasn1==0.4.2
pyasn1-modules==0.2.1
pybind11==2.9.2
pycairo==1.16.2
pycparser==2.21
pycrypto==2.6.1
pycups==1.9.73
Pygments==2.3.1
PyGObject==3.36.0
PyHamcrest==1.9.0
PyJWT==1.7.1
pymacaroons==0.13.0
PyNaCl==1.3.0
pyOpenSSL==22.1.0
pyparsing==2.4.6
PyQt5==5.14.1
pyRFC3339==1.1
python-apt==2.0.1
python-dateutil==2.7.3
python-debian===0.1.36ubuntu1
python-libtorrent==1.1.13
pytz==2019.3
pyxattr==0.6.1
pyxdg==0.26
PyYAML==5.3.1
rencode==1.0.6
reportlab==3.5.34
requests==2.22.0
requests-unixsocket==0.2.0
scipy==1.3.3
SecretStorage==2.3.1
sentry-sdk==1.23.0
service-identity==18.1.0
setproctitle==1.1.10
simplejson==3.16.0
sip==4.19.21
six==1.14.0
slepc4py==3.12.0
slepc4py-complex==3.12.0
slepc4py-real==3.12.0
smmap==5.0.0
sympy==1.5.1
systemd-python==234
traitlets==4.3.3
Twisted==18.9.0
typer==0.9.0
typing-extensions==4.5.0
ubuntu-advantage-tools==8001
ubuntu-drivers-common==0.0.0
ufw==0.36
unattended-upgrades==0.1
urllib3==2.0.2
wadllib==1.3.3
wandb==0.15.2
wcwidth==0.1.8
xkit==0.0.0
youtube-dl==2020.3.24
zope.interface==4.7.1```

### Additional Context

_No response_

**Comment by ArtsiomWB** [comment]
Hi @slitvinov, thank you for reporting this. Is this a blocker for you?

**Comment by slitvinov** [comment]
I would classify it as a minor inconvenience.

**Comment by ArtsiomWB** [comment]
Gotcha! Thank you for bringing this up. I have checked and Typer is not one of our required packages. I do know that clicker is though and I do see that it got installed/updated after you installed Typer. 

I think potentially what could have happened was you had an older version that was incompatible with wandb and then it got updated to the one you needed.

**Comment by ArtsiomWB** [comment]
Would you like me to close this issue for you?

**Comment by slitvinov** [comment]
@ArtsiomWB you are right. I can reproduce it!
```$ python -m venv e
$ . ./e/bin/activate
(e) $ python -m pip -q install click==7 
(e) $ python -m pip -q install wandb
(e) $ python -m wandb login
*** output flushed ***
TypeError: __init__() got an unexpected keyword argument 'no_args_is_help'
(e) $ python -m pip -q install click==8.1
(e) $ python -m wandb login
wandb: Currently logged in as: slitvinov. Use `wandb login --relogin` to force relogin
```
It is possible that `wandb` requires a comparable version of `click` during the installation?

**Comment by rsanandres-wandb** [comment]
Hello @slitvinov !

Yes, `wandb` [requires a version](https://github.com/wandb/wandb/blob/537f5a460c7a3ddb5706ea611b99725faf7b3af4/requirements.txt#LL1C1-L1C44) of `click` but there is also a note that indicates that `# click 8.0.0 is broken`. Perhaps `click==8.0.0` was installed when initially run which caused the error. 

For ease of access, here is the particular requirements for `click`:
```Click>=7.0,!=8.0.0  # click 8.0.0 is broken```
