### ISSUE TITLE
[CLI]: 

### ISSUE THREAD

**Issue by firezym** [wandb/wandb#5571]
### Describe the bug

In WSL Ubuntu 22.04.1 LTS, I use the following proxy setting so that I can get to OpenAI and pips behind the proxy.
If I add any `http` or `https` schema like `export HTTPS_PROXY="http://192.168.10.166:11111/"`, the OpenAI API and pip installs will not work. 
Is there anyway to compromise the proxy settings, eg. adding compatibles in the codes?

```shell
export http_proxy="192.168.10.166:11111"
export https_proxy="192.168.10.166:11111"
export ALL_PROXY="192.168.10.166:11111"
export no_proxy="localhost,127.0.0.1,::1,192.168.*.*,10.0.*.*"
```

When I run this code I get error of `ProxySchemeUnknown`.

```python
from langchain.callbacks import WandbCallbackHandler, StdOutCallbackHandler
from datetime import datetime

session_group = datetime.now().strftime("%m.%d.%Y_%H.%M.%S")
wandb_callback = WandbCallbackHandler(
    job_type="inference",
    project="langchain_callback_demo",
    group=f"minimal_{session_group}",
    name="llm",
    tags=["test"],
)
callbacks = [StdOutCallbackHandler(), wandb_callback]
```

```shell
File [~/miniconda3/envs/lang/lib/python3.11/site-packages/urllib3/poolmanager.py:481](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/ocean/projects/behavior/~/miniconda3/envs/lang/lib/python3.11/site-packages/urllib3/poolmanager.py:481), in ProxyManager.__init__(self, proxy_url, num_pools, headers, proxy_headers, proxy_ssl_context, use_forwarding_for_https, **connection_pool_kw)
    478 proxy = parse_url(proxy_url)
    480 if proxy.scheme not in ("http", "https"):
--> 481     raise ProxySchemeUnknown(proxy.scheme)
    483 if not proxy.port:
    484     port = port_by_scheme.get(proxy.scheme, 80)
ProxySchemeUnknown: Proxy URL had no scheme, should start with http:// or https://
```
In cmd line interface, when I type wandb, I also get following error:
```
Traceback (most recent call last):
  File "/home/ocean/miniconda3/envs/lang/bin/wandb", line 5, in <module>
    from wandb.cli.cli import cli
  File "/home/ocean/miniconda3/envs/lang/lib/python3.11/site-packages/wandb/__init__.py", line 200, in <module>
    _sentry.setup()
  File "/home/ocean/miniconda3/envs/lang/lib/python3.11/site-packages/wandb/analytics/sentry.py", line 40, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ocean/miniconda3/envs/lang/lib/python3.11/site-packages/wandb/analytics/sentry.py", line 76, in setup
    client = sentry_sdk.Client(
             ^^^^^^^^^^^^^^^^^^
  File "/home/ocean/miniconda3/envs/lang/lib/python3.11/site-packages/sentry_sdk/client.py", line 143, in __init__
    self._init_impl()
  File "/home/ocean/miniconda3/envs/lang/lib/python3.11/site-packages/sentry_sdk/client.py", line 211, in _init_impl
    self.transport = make_transport(self.options)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ocean/miniconda3/envs/lang/lib/python3.11/site-packages/sentry_sdk/transport.py", line 534, in make_transport
    return transport_cls(options)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ocean/miniconda3/envs/lang/lib/python3.11/site-packages/sentry_sdk/transport.py", line 154, in __init__
    self._pool = self._make_pool(
                 ^^^^^^^^^^^^^^^^
  File "/home/ocean/miniconda3/envs/lang/lib/python3.11/site-packages/sentry_sdk/transport.py", line 444, in _make_pool
    return urllib3.ProxyManager(proxy, **opts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ocean/miniconda3/envs/lang/lib/python3.11/site-packages/urllib3/poolmanager.py", line 481, in __init__
    raise ProxySchemeUnknown(proxy.scheme)
urllib3.exceptions.ProxySchemeUnknown: Proxy URL had no scheme, should start with http:// or https://
Exception ignored in atexit callback: <bound method Sentry.end_session of <wandb.analytics.sentry.Sentry object at 0x7ff642be4a10>>
Traceback (most recent call last):
  File "/home/ocean/miniconda3/envs/lang/lib/python3.11/site-packages/wandb/analytics/sentry.py", line 40, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ocean/miniconda3/envs/lang/lib/python3.11/site-packages/wandb/analytics/sentry.py", line 163, in end_session
    assert self.hub is not None
AssertionError:
```

### Environment

WandB version:

OS:

Python version:

Versions of relevant libraries:

**Comment by firezym** [comment]
I temporarily changed the urllib3's poolmanager code to deprecate the error. But not sure if any other nasty things will happen. In my env, /home/username/miniconda3/envs/lang/lib/python3.11/site-packages/urllib3/poolmanager.py,
at the start of the code I added
```
...
from .util.retry import Retry
from .util.url import parse_url

### Manually Chaged for WandB ###
from .util.url import Url
### Manually Chaged for WandB ###

__all__ = ["PoolManager", "ProxyManager", "proxy_from_url"]
...

```

Around line 480 I changed code as following:
```
...
        if isinstance(proxy_url, HTTPConnectionPool):
            proxy_url = "%s://%s:%i" % (
                proxy_url.scheme,
                proxy_url.host,
                proxy_url.port,
            )
        proxy = parse_url(proxy_url)

        if proxy.scheme not in ("http", "https"):
            ### Manually Chaged for WandB ###
            proxy = Url(scheme="https", host=proxy.host, port=proxy.port, path=proxy.path)
            # raise ProxySchemeUnknown(proxy.scheme)
            ### Manually Chaged for WandB ###

        if not proxy.port:
            port = port_by_scheme.get(proxy.scheme, 80)
            proxy = proxy._replace(port=port)

...

```

**Comment by nate-wandb** [comment]
Hi @firezym, I see, so we need to append the "https" of "http" (depending on which env variable it comes from) before passing it to urllib3 here correct? That way you could use `export http_proxy="192.168.10.166:11111` and `
export https_proxy="192.168.10.166:11111"` which would be compatible with the other libraries. 

I'm not sure what the standard is here but it sounds like other libraries are doing this. If this seems like the solution, I can pass this onto the engineering team.

**Comment by firezym** [comment]
@nate-wandb That is correct. But I am not sure if wandb lib can go that deep into the urllib3 proxy level. I think you can pass this problem to the team to see if they can look into the basic library compatibility issue about proxy setting alignment with OpenAI and Pips.

**Comment by nate-wandb** [comment]
Hi @firezym, sorry for the delay. I've passed this onto the eng team to investigate. I believe `wandb` pulls the env variable and passes it to `urllib3` so there may be an opportunity to append the schema prior to passing it there but I'll have to have the team look into it. I'll follow up here once we have an update on this.

**Comment by firezym** [comment]
@nate-wandb Thanks a lot. Looking forward to it :)

**Comment by nate-wandb** [comment]
Hi @firezym, I haven't been able to reproduce this and it seems like PIP expects the http/https prefix. I haven't tested Open AI yet.

**Comment by firezym** [comment]
@nate-wandb pip actually is not that important during running. OpenAI and wandb will run in the same proxy env at the same time, which matters. Please try OpenAI :)

**Comment by nate-wandb** [comment]
Hi @firezym, I was able to reproduce this. I'll pass this onto our engineering team to look into and can follow up once they have a chance to look into the option of being able to handle both variations of the url. This would probably be the more robust way to handle this to ensure compatibility with other libraries similar to the change that you made to `urllib3`

**Comment by nate-wandb** [comment]
@firezym can you try `export WANDB_ERROR_REPORTING=False`? I believe this may only be an issue with the way we handle this with our Sentry integration and the above env variable will disable Sentry.

**Comment by firezym** [comment]
@nate-wandb Thanks a lot. I will try this when I have chance recently :)

**Comment by sydholl** [comment]
WandB Internal User commented: 
firezym commented: 
I temporarily changed the urllib3's poolmanager code to deprecate the error. But not sure if any other nasty things will happen. In my env, /home/username/miniconda3/envs/lang/lib/python3.11/site-packages/urllib3/poolmanager.py,
at the start of the code I added
```
...
from .util.retry import Retry
from .util.url import parse_url

### Manually Chaged for WandB ###
from .util.url import Url
### Manually Chaged for WandB ###

__all__ = ["PoolManager", "ProxyManager", "proxy_from_url"]
...

```

Around line 480 I changed code as following:
```
...
        if isinstance(proxy_url, HTTPConnectionPool):
            proxy_url = "%s://%s:%i" % (
                proxy_url.scheme,
                proxy_url.host,
                proxy_url.port,
            )
        proxy = parse_url(proxy_url)

        if proxy.scheme not in ("http", "https"):
            ### Manually Chaged for WandB ###
            proxy = Url(scheme="https", host=proxy.host, port=proxy.port, path=proxy.path)
            # raise ProxySchemeUnknown(proxy.scheme)
            ### Manually Chaged for WandB ###

        if not proxy.port:
            port = port_by_scheme.get(proxy.scheme, 80)
            proxy = proxy._replace(port=port)

...

```

**Comment by sydholl** [comment]
WandB Internal User commented: 
firezym commented: 
@nate-wandb Thanks a lot. Looking forward to it :)

**Comment by sydholl** [comment]
WandB Internal User commented: 
firezym commented: 
@nate-wandb pip actually is not that important during running. OpenAI and wandb will run in the same proxy env at the same time, which matters. Please try OpenAI :)

**Comment by sydholl** [comment]
WandB Internal User commented: 
nate-wandb commented: 
@firezym can you try `export WANDB_ERROR_REPORTING=False`? I believe this may only be an issue with the way we handle this with our Sentry integration and the above env variable will disable Sentry.

**Comment by anmolmann** [comment]
Hi @firezym , I wanted to follow up on my @nate-wandb 's suggestion above. Please let us know if we can be of further assistance or if your issue has been resolved.
