### ISSUE TITLE
[CLI]: Can't pickle local object 'TorchHistory.add_log_hooks_to_pytorch_module.<locals>.<lambda>'

### ISSUE THREAD

**Issue by vyskocj** [wandb/wandb#5573]
### Describe the bug

The `wandb.watch()` causes the exception below when we want to save the model using `torch.save()`. There exists workaround (passing to `torch.save()` an argument: pickle_module=dill) but when `log_graph=True` is used in the `wandb.watch()`, there is another unsolvable error. You can see also [ultralytics bug report](https://github.com/ultralytics/ultralytics/issues/2668#issue-1713230405).

What does the `wandb.watch` store directly in the model and why? Would be possible to save such information in another memory (e.g. on a disk)?

I found that this is let's say old problem:
- [https://github.com/wandb/wandb/issues/961#issue-598509912](https://github.com/wandb/wandb/issues/961#issue-598509912)

```python
from ultralytics import YOLO
import wandb

def watch_model(trainer):
    wandb.watch(trainer.model, log="all", log_freq=100, log_graph=True)

# Load a model
model = YOLO("yolov8n.pt")  # load a pretrained model (recommended for training)
model.add_callback("on_train_start", watch_model)

# Use the model
model.train(data=f"datasets/custom.yaml", cache=True, epochs=1)  # train the model
```

```shell
AttributeError                            Traceback (most recent call last)
/var/tmp/pbs.15486198.meta-pbs.metacentrum.cz/ipykernel_195945/3018824876.py in 
2
3 # Use the model
----> 4 model.train(data=f"datasets/custom.yaml", cache=True, epochs=1)  # train the model


~/.local-carnivore_id_v1.2.sif/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py in train(self, **kwargs)
369             self.model = self.trainer.model
370         self.trainer.hub_session = self.session  # attach optional HUB session
--> 371         self.trainer.train()
372         # Update model and cfg after training
373         if RANK in (-1, 0):


~/.local-carnivore_id_v1.2.sif/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py in train(self)
191                 ddp_cleanup(self, str(file))
192         else:
--> 193             self._do_train(world_size)
194
195     def _setup_ddp(self, world_size):


~/.local-carnivore_id_v1.2.sif/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py in _do_train(self, world_size)
370                 # Save model
371                 if self.args.save or (epoch + 1 == self.epochs):
--> 372                     self.save_model()
373                     self.run_callbacks('on_model_save')
374


~/.local-carnivore_id_v1.2.sif/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py in save_model(self)
413
414         # Save last, best and delete
--> 415         torch.save(ckpt, self.last)
416         if self.best_fitness == self.fitness:
417             torch.save(ckpt, self.best)


/opt/conda/lib/python3.8/site-packages/torch/serialization.py in save(obj, f, pickle_module, pickle_protocol, _use_new_zipfile_serialization)
378         if _use_new_zipfile_serialization:
379             with _open_zipfile_writer(opened_file) as opened_zipfile:
--> 380                 _save(obj, opened_zipfile, pickle_module, pickle_protocol)
381                 return
382         _legacy_save(obj, opened_file, pickle_module, pickle_protocol)


/opt/conda/lib/python3.8/site-packages/torch/serialization.py in _save(obj, zip_file, pickle_module, pickle_protocol)
546     pickler = pickle_module.Pickler(data_buf, protocol=pickle_protocol)
547     pickler.persistent_id = persistent_id
--> 548     pickler.dump(obj)
549     data_value = data_buf.getvalue()
550     zip_file.write_record('data.pkl', data_value, len(data_value))


AttributeError: Can't pickle local object 'TorchHistory.add_log_hooks_to_pytorch_module..'
```

### Environment

WandB version:
0.15.3

OS:
linux

Python version:
3.8

Versions of relevant libraries:
ultralytics==8.0.105
dill==0.3.6

**Comment by nate-wandb** [comment]
Hi @vyskocj, I'll take this to our engineering team to investigate. In the meantime could you try `wandb.unwatch()` before you save the model if that works for your workflow?

**Comment by vyskocj** [comment]
Thank you for your fast response. @nate-wandb Yes, this is working, but if a user (like me) is using some Python package for training the models, it requires intervention into the installed scripts or some wrappers.

In my opinion, it would be better (if the reported issue of `wandb.watch()` could not really be solved in another way) to have a function designed for hooks - i.e. the user would have to periodically call a function that would send the data/model to wandb (as it is done for logging), instead of doing everything itself (as it is done now). I hope that you will be able to find a great solution.

**Comment by nate-wandb** [comment]
Hi @vyskocj, sorry for the delay. For your above suggestion, are you looking for something similar to our `WandbLogger` [class](https://lightning.ai/docs/pytorch/stable/extensions/generated/lightning.pytorch.loggers.WandbLogger.html) for PyTorch Lightning?

**Comment by vyskocj** [comment]
It is ok, meanwhile, I have created a pull request to Ultralytics, in which this problem occurred, to save the model via dill (instead of the original pickle). So from my side, the problem is solved by a walkaround.

And according to your question, I would say yes if the `WandbLogger` and its `watch` method allow `torch.save` without problems (using the standard pickle library). It is true that there is a workaround, however, new users will go through the same walk that I had. However, it will be unpleasant for them if their program falls on this after days of training.

If there is no possibility to guarantee this (saving model using `torch.save` without exception), I highly recommend adding a warning or at least any information into your documentation to [wandb.watch](https://docs.wandb.ai/ref/python/watch) that it may cause issues with saving model using pickle -> 'wandb.unwatch' has to be called before saving the model to avoid an error. Because I did not know about this method until you told me about it.

**Comment by nate-wandb** [comment]
Ok, glad you have a workaround in the meantime. I'll submit this request to the engineering team and see if we can solve this from our side. I'll follow back up once I have an update.

**Comment by jveitchmichaelis** [comment]
@nate-wandb I also get this with a project that uses Pytorch Lightning. 

```
ERROR:__name__:Can't pickle local object 'TorchHistory.add_log_parameters_hook.<locals>.<lambda>'
Traceback (most recent call last):
  File "/home/josh/ -- .py", line 898, in train
    trainer.fit(model=self.model, datamodule=data_module)
  File "/opt/conda/envs/tcd/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/opt/conda/envs/tcd/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 36, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/opt/conda/envs/tcd/lib/python3.10/site-packages/lightning/pytorch/strategies/launchers/multiprocessing.py", line 113, in launch
    mp.start_processes(
  File "/opt/conda/envs/tcd/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 189, in start_processes
    process.start()
  File "/opt/conda/envs/tcd/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/opt/conda/envs/tcd/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/opt/conda/envs/tcd/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/conda/envs/tcd/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/conda/envs/tcd/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/opt/conda/envs/tcd/lib/python3.10/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'TorchHistory.add_log_parameters_hook.<locals>.<lambda>'
```

The model is a semantic segmentation model from Torchgeo, but I underneath it's from [here](https://github.com/qubvel/segmentation_models.pytorch). This wasn't an issue in the past, but seems to be related to upgrading Lightning.

**Comment by nate-wandb** [comment]
@jveitchmichaelis thank you for raising this as well. Interesting that in PTL this only fails for multiple GPU's. Are you saving the model or is this happening without a model save? I think PTL might be pickling to disk to pass the model between processes but I'll have to look into this know for sure.

**Comment by duarteocarmo** [comment]
@nate-wandb  - `wandb.unwatch` - worked well for me and allowed me to save the whole model!

**Comment by ArmiNouri** [comment]
@nate-wandb `wandb.unwatch` works if I need to save the model once at the end of the process, but I'm saving the best performing model after each epoch. Any trick on how to make this work? `unwatch`ing, saving, and then re`watch`ing throws this error:

``` 
File "<path>/wandb/wandb_torch.py", line 114, in add_log_parameters_hook
    self._hook_handles["parameters/" + prefix] = hook
TypeError: list indices must be integers or slices, not str
```

**Comment by alexnguyen0512** [comment]
@nate-wandb I'm also getting the same erorr as jveitchmichaelis above. In this case, I'm training a VAE model with PTL and also using Hydra to manage runs. I'm training the models on supercomputing nodes with 4 GPUs each and want to utilize multiprocessing to speed up training, but I am crashing out with the following error 

```
12 Traceback (most recent call last):
13   File "/global/u2/d/dknguyen/gen_ai/cdvae/cdvae/run.py", line 166, in main
14     run(cfg)
15   File "/global/u2/d/dknguyen/gen_ai/cdvae/cdvae/run.py", line 154, in run
16     trainer.fit(model=model, datamodule=datamodule)
17   File "/global/common/software/nersc/pm-2022q4/sw/pytorch/2.0.1/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in fit
18     self._call_and_handle_interrupt(
19   File "/global/common/software/nersc/pm-2022q4/sw/pytorch/2.0.1/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 721, in _call_and_handle_interrupt
20     return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
21   File "/global/common/software/nersc/pm-2022q4/sw/pytorch/2.0.1/lib/python3.9/site-packages/pytorch_lightning/strategies/launchers/spawn.py", line 78, in launch
22     mp.spawn(
23   File "/global/common/software/nersc/pm-2022q4/sw/pytorch/2.0.1/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 239, in spawn
24     return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
25   File "/global/common/software/nersc/pm-2022q4/sw/pytorch/2.0.1/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
26     process.start()
27   File "/global/common/software/nersc/pm-2022q4/sw/pytorch/2.0.1/lib/python3.9/multiprocessing/process.py", line 121, in start
28     self._popen = self._Popen(self)
29   File "/global/common/software/nersc/pm-2022q4/sw/pytorch/2.0.1/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
30     return Popen(process_obj)
31   File "/global/common/software/nersc/pm-2022q4/sw/pytorch/2.0.1/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
32     super().__init__(process_obj)
33   File "/global/common/software/nersc/pm-2022q4/sw/pytorch/2.0.1/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
34     self._launch(process_obj)
35   File "/global/common/software/nersc/pm-2022q4/sw/pytorch/2.0.1/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 47, in _launch
36     reduction.dump(process_obj, fp)
37   File "/global/common/software/nersc/pm-2022q4/sw/pytorch/2.0.1/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
38     ForkingPickler(file, protocol).dump(obj)
39 AttributeError: Can't pickle local object 'TorchHistory.add_log_parameters_hook.<locals>.<lambda>'
40 Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```
