### ISSUE TITLE
[CLI]: ConnectionAbortedError common during sweep

### ISSUE THREAD

**Issue by jlperla** [wandb/wandb#5574]
### Describe the bug

Cannot reproduce minimally - though can show you how to reproduce with public repo.

But basically: on Windows with the latest wandb app the sweep agent (logged with pytorch lighting if that mattrers at all) is often throwing an error about `ConnectionAbortedError` , sometimes on the first run within the sweep.  You can see an example of a more complete error message below which I took as a snapshot:

```
wandb: Run summary:
wandb:     convergence_description Success
wandb: early_stopping_check_failed False
wandb:      early_stopping_monitor train_loss
wandb:    early_stopping_threshold 1e-05
wandb:                       epoch 268
wandb:               hpo_objective 0.00042
wandb:                     lr-Adam 0.005
wandb:                     retcode 0
wandb:              test_abs_error 0.01124
wandb:                   test_loss 0.00042
wandb:      test_loss_check_failed nan
wandb:              test_rel_error 0.00905
wandb:                  train_loss 1e-05
wandb:                  train_time 8.35106
wandb:        trainable_parameters 50049
wandb:         trainer/global_step 268
wandb:               val_abs_error 0.01986
wandb:                    val_loss 0.00111
wandb:               val_rel_error 0.01936
wandb:
wandb:  View run misty-sweep-7 at: https://wandb.ai/highdimensionaleconlab/symmetry_dynamic_programming/runs/sxd0pq6w
wandb: Synced 6 W&B file(s), 1 media file(s), 1 artifact file(s) and 0 other file(s)
wandb: Find logs at: .\wandb\run-20230518_140904-sxd0pq6w\logs
Exception in thread ChkStopThr:
Traceback (most recent call last):
  File "C:\Users\jesse\anaconda3\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\jesse\anaconda3\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\jesse\anaconda3\lib\site-packages\wandb\sdk\wandb_run.py", line 278, in check_stop_status
    self._loop_check_status(
  File "C:\Users\jesse\anaconda3\lib\site-packages\wandb\sdk\wandb_run.py", line 216, in _loop_check_status
    local_handle = request()
  File "C:\Users\jesse\anaconda3\lib\site-packages\wandb\sdk\interface\interface.py", line 787, in deliver_stop_status
    return self._deliver_stop_status(status)
  File "C:\Users\jesse\anaconda3\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 585, in _deliver_stop_status
    return self._deliver_record(record)
  File "C:\Users\jesse\anaconda3\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 560, in _deliver_record
    handle = mailbox._deliver_record(record, interface=self)
  File "C:\Users\jesse\anaconda3\lib\site-packages\wandb\sdk\lib\mailbox.py", line 455, in _deliver_record
    interface._publish(record)
  File "C:\Users\jesse\anaconda3\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 51, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\jesse\anaconda3\lib\site-packages\wandb\sdk\lib\sock_client.py", line 221, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\jesse\anaconda3\lib\site-packages\wandb\sdk\lib\sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "C:\Users\jesse\anaconda3\lib\site-packages\wandb\sdk\lib\sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\jesse\anaconda3\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2023-05-18 14:09:37,766 - wandb.wandb_agent - INFO - Cleaning up finished run: sxd0pq6w
2023-05-18 14:09:38,049 - wandb.wandb_agent - INFO - Agent received command: run
```
This has been happening since I started using W&B.

I am unsure, though, what this means as it seems like the assets are pushed to the server?  

### Environment

WandB version: 0.15.3

OS: Windows

Python version: 3.9

Versions of relevant libraries:  Pytorch lightning 2 but not sure that really matters.

**Comment by umakrishnaswamy** [comment]
Hey @jlperla,
 
Thanks for reaching out. This ConnectionAbortedError is caused by something in your computer that is dropping the connections between your machine and wandb. There could be a few reasons why this is happening:

- Windows firewall could be blocking the ports
- If you have any anti-virus software installed, that could be blocking the connection as well

I would recommend trying to find out if you currently have any software blocking this connection, and then changing your firewall & anti-virus software settings to allow this type of connection.

Best,

Uma

**Comment by jlperla** [comment]
Thanks Uma.  I will see if the default firewall stuff is blocking things.  Is it possible that even with the failure it is still uploading all of the results?  It is hard to tell but it seems like it?

**Comment by umakrishnaswamy** [comment]
Hey @jlperla, 

It could be possible that some of your results would be uploaded and that the connection drops after a number of epochs. Wandb tries (many times) to establish a reconnection, which is why you may see your script continuing to run and/or a delay in logging. Which runs are you referring to that are giving you the error yet still logging your data? And how did changing your firewall/anti-virus software settings affect your logging?
 
Additionally, if you run your script without wandb, does your training loop run as expected?
 
Best,
 
Uma

**Comment by umakrishnaswamy** [comment]
Hi @jlperla ,

We wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if your issue has been resolved.

Best,
Uma

**Comment by jlperla** [comment]
Thanks for followingup.   Not sure if there is anything I can do about it.  I just have the baseline out-of-the-box windows firewall settings, nothning else on my network.  No extra firewall or anti-virus stuff installed at all, but maybe they randomly flag things.

This happens intermittantly with scripts and sweeps that otherwise run fine so it is hard to replicate the issue at will.

Why don't we close the issue and if I am able to make it reproducible I will post separately.
