### ISSUE TITLE
[CLI]: @wandb_log failed integration with metaflow - wandb.errors.AuthenticationError

### ISSUE THREAD

**Issue by erichhhhho** [wandb/wandb#5580]
### Current Behavior

When creating metaflow flow, following https://docs.wandb.ai/guides/integrations/metaflow:
```
export WANDB_API_KEY=<YOUR KEY>
```

```python
from metaflow import FlowSpec, Parameter, step, batch, environment
from wandb.integration.metaflow import wandb_log
import wandb

@wandb_log(datasets=True, models=True, settings=wandb.Settings(api_key=os.getenv("WANDB_API_KEY"))
class WandbExampleFlow(FlowSpec):
  @step
  def start(self):
    self.raw_df = pd.read_csv(...).    # pd.DataFrame -> upload as dataset
    self.model_file = torch.load(...)  # nn.Module    -> upload as model
    self.next(self.mid)

  @environment(
        vars={
            "WANDB_API_KEY": os.getenv("WANDB_API_KEY"),
        }
    )
  @batch(gpu=1)
  @retry(times=2)
  @step
  def mid(self):
    self.raw_df = pd.read_csv(...).    # pd.DataFrame -> upload as dataset
    self.model_file = torch.load(...)  # nn.Module    -> upload as model
    self.next(self.end)

  @step
  def end(self):
    self.raw_df = pd.read_csv(...).    
    self.model_file = torch.load(...)
```

Met the following error when it is running the step with @batch:
```bash
wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin
wandb: ERROR Error while calling W&B API: user is not logged in (<Response [401]>)
<flow XXX step train> failed:
    Internal error
Traceback (most recent call last):
  File "/home/code/metaflow/metaflow/cli.py", line 1171, in main
    start(auto_envvar_prefix="METAFLOW", obj=state)
  File "/home/code/metaflow/metaflow/_vendor/click/core.py", line 829, in __call__
    return self.main(args, kwargs)
  File "/home/code/metaflow/metaflow/_vendor/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/code/metaflow/metaflow/_vendor/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/code/metaflow/metaflow/_vendor/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, ctx.params)
  File "/home/code/metaflow/metaflow/_vendor/click/core.py", line 610, in invoke
    return callback(args, kwargs)
  File "/home/code/metaflow/metaflow/_vendor/click/decorators.py", line 21, in new_func
    return f(get_current_context(), args, kwargs)
  File "/home/code/metaflow/metaflow/cli.py", line 580, in step
    task.run_step(
  File "/home/code/metaflow/metaflow/task.py", line 587, in run_step
    self._exec_step_function(step_func)
  File "/home/code/metaflow/metaflow/task.py", line 61, in _exec_step_function
    step_function()
  File "/usr/local/lib/python3.9/site-packages/wandb/integration/metaflow/metaflow.py", line 307, in wrapper
    with wandb.init(settings=settings) as run:
  File "/usr/local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1169, in init
    raise e
  File "/usr/local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1150, in init
    run = wi.init()
  File "/usr/local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 769, in init
    raise error
wandb.errors.AuthenticationError: The API key you provided is either invalid or missing.  If the `WANDB_API_KEY` environment variable is set, make sure it is correct. Otherwise, to resolve this issue, you may try running the 'wandb login --relogin' command. If you are using a local server, make sure that you're using the correct hostname. If you're not sure, you can try logging in again using the 'wandb login --relogin --host [hostname]' command.(Error 401: Unauthorized)

    AWS Batch error:
    Essential container in task exited This could be a transient error. Use @retry to retry.

Task failed.
```

### Expected Behavior

@wandb_log should be able to integrate metaflow step with @batch and pass in the api key

### Steps To Reproduce

1. Create Flow mentioned above
2. Run the flow

### Environment

OS:
Ubuntu 22.04.1 LTS

Version:
metaflow-2.7.14
wandb-0.15.2

### Additional Context

Related issue: 
#2864 
#2962 
https://github.com/Netflix/metaflow/issues/814
@andrewtruong

**Comment by luisbergua** [comment]
Hi @erichhhhho, thanks for reporting this! I have tested with the [code from the docs](https://docs.wandb.ai/guides/integrations/metaflow#decorate-your-flows-and-steps) and it works properly for me. Could you try setting your api key in the script as `os.environ["WANDB_API_KEY"] = <your_key>` and see if you get the same error?

**Comment by luisbergua** [comment]
Hi @erichhhhho , I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by erichhhhho** [comment]
> Hi @erichhhhho, thanks for reporting this! I have tested with the [code from the docs](https://docs.wandb.ai/guides/integrations/metaflow#decorate-your-flows-and-steps) and it works properly for me. Could you try setting your api key in the script as `os.environ["WANDB_API_KEY"] = <your_key>` and see if you get the same error?

Yes, I got the same error. Adding WANDB_API_KEY in local environment variable will not be able to resolve this issue. Basically, it might need @wandb_log to pass the local WANDB_API_KEY into the metaflow step with @batch. Could you try adding step with @batch?

**Comment by erichhhhho** [comment]
Hi @luisbergua , just to follow up, any update on this issue?

**Comment by luisbergua** [comment]
Hi @erichhhhho, apologies for the delay on this! As you said, the `@batch`step is running  in a different container so that's why you need to explicitly set `WANDB_API_KEY ` again. I'll create a feature request to have this automated, thanks for reporting this!
