### ISSUE TITLE
[CLI]: Importing `wandb` inside a script fails

### ISSUE THREAD

**Issue by rsomani95** [wandb/wandb#5627]
### Describe the bug

`import wandb` fails from inside my training script with the following error:

```python
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    import wandb
  File "/usr/local/lib/python3.8/dist-packages/wandb/__init__.py", line 191, in <module>
    if wandb_sdk.lib.ipython.in_notebook():
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/lib/ipython.py", line 62, in in_notebook
    return _get_python_type() != "python"
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/lib/ipython.py", line 32, in _get_python_type
    from IPython import get_ipython  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/IPython/__init__.py", line 53, in <module>
    from .terminal.embed import embed
  File "/usr/local/lib/python3.8/dist-packages/IPython/terminal/embed.py", line 17, in <module>
    from IPython.terminal.ipapp import load_default_config
  File "/usr/local/lib/python3.8/dist-packages/IPython/terminal/ipapp.py", line 29, in <module>
    from IPython.core.magics import (
  File "/usr/local/lib/python3.8/dist-packages/IPython/core/magics/__init__.py", line 21, in <module>
    from .execution import ExecutionMagics
  File "/usr/local/lib/python3.8/dist-packages/IPython/core/magics/execution.py", line 11, in <module>
    import cProfile as profile
  File "/usr/lib/python3.8/cProfile.py", line 22, in <module>
    run.__doc__ = _pyprofile.run.__doc__
AttributeError: module 'profile' has no attribute 'run'
```

However, if I try opening an IPython terminal, `import wandb` doesn't fail whereas opening a regular python terminal and running `import wandb` throws the same error as above.

### Environment

WandB version: `0.15.3`

OS: `Ubuntu 20.04.6 LTS`

Python version: `3.8.10`

Versions of relevant libraries: `ipython==8.12.2`

**Comment by rsomani95** [comment]
Runnin `pip uninstall ipython -y` does the trick but I'd prefer not to have to do that.

**Comment by MBakirWB** [comment]
Hi @rsomani95 , the stacktrace is suggesting, _pyprofile is somehow replacing the global namespace. Do you happen to have a script called `profile.py` in your dirs?

**Comment by MBakirWB** [comment]
Hi @rsomani95 , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by rsomani95** [comment]
Hey @MBakirWB thank you for your response. You were right, there was a `profile.py` in the directory I was running from that caused the issue. Removing it solved the issue, thank you!
