### ISSUE TITLE
[CLI]: Cannot load wandb configs from file

### ISSUE THREAD

**Issue by smorad** [wandb/wandb#5648]
### Describe the bug

It doesn't seem like file-based configs are working. I am following https://docs.wandb.ai/guides/track/config#file-based-configs.

```python
# test.py
import wandb
wandb.init()
print(wandb.config)
print(wandb.config['bork'])
```

```yaml
# bork.yaml
bork: 
  spork: "bork"
```

```bash
python test.py --configs bork.yaml
```

```bash
wandb: Currently logged in as: *** (***). Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.15.3
wandb: Run data is saved locally in /Users/***/code/pql/wandb/run-20230601_130523-oil93bwm
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run jumping-glade-64
wandb: ⭐️ View project at https://wandb.ai/***/torchrl-ddpg
wandb: 🚀 View run at https://wandb.ai/***/torchrl-ddpg/runs/oil93bwm
{}
Traceback (most recent call last):
  File "/Users/***/code/pql/test.py", line 4, in <module>
    print(wandb.config['bork'])
  File "/Users/***/miniforge3/envs/torch_rl/lib/python3.9/site-packages/wandb/sdk/wandb_config.py", line 130, in __getitem__
    return self._items[key]
KeyError: 'bork'
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: 🚀 View run jumping-glade-64 at: https://wandb.ai/***/torchrl-ddpg/runs/oil93bwm
wandb: Synced 7 W&B file(s), 0 media file(s), 0 artifact file(s) and 1 other file(s)
wandb: Find logs at: ./wandb/run-20230601_130523-oil93bwm/logs
```

### Environment

WandB version: 0.15.3
OS: MacOS
Python version: 3.9.16

Versions of relevant libraries:

**Comment by luisbergua** [comment]
Hi @smorad, thanks for your patience! After discussing this internally, `--configs` arg  is a relic from older versions of SDK and needs to be removed from our docs. The way to achieve ethis is `wandb.init(config="bork.yaml")`
