### ISSUE TITLE
[Feature]: Add force flag for wandb sync

### ISSUE THREAD

**Issue by pochtar** [wandb/wandb#5674]
### Description

https://docs.wandb.ai/ref/cli/wandb-sync
It would be great to have a flag to force sync some runs that unexpectedly crashed or had client/server issues.
There are many use cases when it can be helpful, but one notable example is run `dkgndibo` that made the entire sweep stuck after the run's completion because of this:
```
2023-06-05 21:17:43,264 INFO    Thread-261 (_run_job):4972 [wandb_init.py:init():596] starting backend
2023-06-05 21:17:43,264 INFO    Thread-261 (_run_job):4972 [wandb_init.py:init():600] setting up manager
2023-06-05 21:17:43,266 INFO    Thread-261 (_run_job):4972 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-06-05 21:17:43,268 INFO    Thread-261 (_run_job):4972 [wandb_init.py:init():606] backend started and connected
2023-06-05 21:17:43,270 INFO    Thread-261 (_run_job):4972 [wandb_run.py:_config_callback():1286] config_cb None None {'dropout': ..., 'num_layers': ..., 'num_units': ...}
2023-06-05 21:17:43,271 INFO    Thread-261 (_run_job):4972 [wandb_init.py:init():700] updated telemetry
2023-06-05 21:17:43,273 INFO    Thread-261 (_run_job):4972 [wandb_init.py:init():737] communicating run to backend with 60.0 second timeout
2023-06-05 21:17:43,592 INFO    Thread-261 (_run_job):4972 [wandb_run.py:_on_init():2177] communicating current version
2023-06-05 21:17:43,696 INFO    Thread-261 (_run_job):4972 [wandb_run.py:_on_init():2186] got version response 
2023-06-05 21:17:43,696 INFO    Thread-261 (_run_job):4972 [wandb_init.py:init():787] starting run threads in backend
2023-06-05 21:17:46,660 INFO    Thread-261 (_run_job):4972 [wandb_run.py:_console_start():2158] atexit reg
2023-06-05 21:17:46,660 INFO    Thread-261 (_run_job):4972 [wandb_run.py:_redirect():2013] redirect: SettingsConsole.WRAP_RAW
2023-06-05 21:17:46,660 INFO    Thread-261 (_run_job):4972 [wandb_run.py:_redirect():2078] Wrapping output streams.
2023-06-05 21:17:46,660 INFO    Thread-261 (_run_job):4972 [wandb_run.py:_redirect():2103] Redirects installed.
2023-06-05 21:17:46,660 INFO    Thread-261 (_run_job):4972 [wandb_init.py:init():829] run started, returning control to user process
2023-06-05 21:40:51,650 INFO    Thread-1 (_heartbeat):4972 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/home/max/miniconda3/envs/project/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/home/max/miniconda3/envs/project/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/home/max/miniconda3/envs/project/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/max/miniconda3/envs/project/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/home/max/miniconda3/envs/project/lib/python3.10/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/home/max/miniconda3/envs/project/lib/python3.10/ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/requests/adapters.py", line 487, in send
    resp = conn.urlopen(
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 285, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 55, in execute
    request = self.session.post(self.url, **post_args)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/requests/adapters.py", line 533, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=60)
2023-06-05 21:41:43,420 INFO    Thread-261 (_run_job):4972 [wandb_run.py:_finish():1893] finishing run xmax/mlp_may23/dkgndibo
2023-06-05 21:41:43,420 INFO    Thread-261 (_run_job):4972 [wandb_run.py:_atexit_cleanup():2127] got exitcode: 0
2023-06-05 21:41:43,427 INFO    Thread-261 (_run_job):4972 [wandb_run.py:_restore():2110] restore
2023-06-05 21:41:43,427 INFO    Thread-261 (_run_job):4972 [wandb_run.py:_restore():2116] restore done
2023-06-05 21:49:32,066 INFO    Thread-1 (_heartbeat):4972 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/home/max/miniconda3/envs/project/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/home/max/miniconda3/envs/project/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/home/max/miniconda3/envs/project/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/max/miniconda3/envs/project/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/home/max/miniconda3/envs/project/lib/python3.10/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/home/max/miniconda3/envs/project/lib/python3.10/ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/requests/adapters.py", line 487, in send
    resp = conn.urlopen(
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 285, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 55, in execute
    request = self.session.post(self.url, **post_args)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/requests/adapters.py", line 533, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=60)
2023-06-05 21:53:51,455 INFO    Thread-1 (_heartbeat):4972 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/home/max/miniconda3/envs/project/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/home/max/miniconda3/envs/project/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/home/max/miniconda3/envs/project/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/max/miniconda3/envs/project/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/home/max/miniconda3/envs/project/lib/python3.10/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/home/max/miniconda3/envs/project/lib/python3.10/ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/requests/adapters.py", line 487, in send
    resp = conn.urlopen(
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 285, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 55, in execute
    request = self.session.post(self.url, **post_args)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/requests/adapters.py", line 533, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=60)
2023-06-05 21:58:00,089 INFO    Thread-1 (_heartbeat):4972 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/home/max/miniconda3/envs/project/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/home/max/miniconda3/envs/project/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/home/max/miniconda3/envs/project/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/max/miniconda3/envs/project/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/home/max/miniconda3/envs/project/lib/python3.10/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/home/max/miniconda3/envs/project/lib/python3.10/ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/requests/adapters.py", line 487, in send
    resp = conn.urlopen(
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 285, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 55, in execute
    request = self.session.post(self.url, **post_args)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/requests/adapters.py", line 533, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=60)
2023-06-05 23:15:38,678 INFO    Thread-1 (_heartbeat):4972 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/home/max/miniconda3/envs/project/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f659c4bfa30>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/requests/adapters.py", line 487, in send
    resp = conn.urlopen(
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f659c4bfa30>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 285, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 55, in execute
    request = self.session.post(self.url, **post_args)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/max/miniconda3/envs/project/lib/python3.10/site-packages/requests/adapters.py", line 520, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f659c4bfa30>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
```

As a result, after a few hours of waiting, I had to cancel the run, even though it was already finished and was just waiting for wandb to sync data.

If you take a look at `dkgndibo` run on the dashboard, you'll see that both transient data and the summary are not updated with the most recent version I have locally. However, if you try `wandb sync --id dkgndibo`, you get `wandb: No runs to be synced.` despite the fact that the local run's files contain newer data.

Therefore, for the cases like this when the server doesn't reflect what is stored on the client, it would be great to be able to manually resync some runs from local files like so: `wandb sync --id dkgndibo --force`.
Thanks.

### Suggested Solution

Introduce the `--force` flag to be able to manually resync runs.

**Comment by umakrishnaswamy** [comment]
Hey @pochtar,

I made a feature request for this and will let you know once progress is made! Thank you!

Best,

Uma
