### ISSUE TITLE
[CLI]: Resume stopped sweep

### ISSUE THREAD

**Issue by pochtar** [wandb/wandb#5845]
### Describe the bug

When I stop a sweep via either UI or `subprocess.run(["wandb", "sweep", "--stop", sweep_id])`, I can resume the stopped sweep via UI. However, if I try to resume via API `subprocess.run(["wandb", "sweep", "--resume", sweep_id])`, the following error appears:
```
Traceback (most recent call last):
  File "/home/max/miniconda3/envs/env/bin/wandb", line 8, in <module>
    sys.exit(cli())
  File "/home/max/miniconda3/envs/env/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/max/miniconda3/envs/env/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/max/miniconda3/envs/env/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/max/miniconda3/envs/env/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/max/miniconda3/envs/env/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/max/miniconda3/envs/env/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/max/miniconda3/envs/env/lib/python3.10/site-packages/wandb/cli/cli.py", line 106, in wrapper
    return func(*args, **kwargs)
  File "/home/max/miniconda3/envs/env/lib/python3.10/site-packages/wandb/cli/cli.py", line 747, in sweep
    getattr(api, "%s_sweep" % state)(sweep_id, entity=entity, project=project)
  File "/home/max/miniconda3/envs/env/lib/python3.10/site-packages/wandb/apis/internal.py", line 147, in resume_sweep
    return self.api.resume_sweep(*args, **kwargs)
  File "/home/max/miniconda3/envs/env/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 3552, in resume_sweep
    self.set_sweep_state(
  File "/home/max/miniconda3/envs/env/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 3475, in set_sweep_state
    raise Exception("Cannot resume %s sweep." % curr_state.lower())
Exception: Cannot resume finished sweep.
```

How can I resume the stopped sweep? If currently not possible, please fix this as it is already possible via the UI, so this should also be possible via API.

Just for the context on the use case why I need it: sometimes I need to pause a long sweep for a short period of time (automatically) and then automatically resume it. Since TF takes up all the free GPU memory and is unable to free it without program exit (singleton), I tried to pause the sweep from within after a run's end (for which I didn't find API too hence subprocess, which works fine for the case), and then do `exit()`.

This doesn't play nice with wandb because of multithreading/multiprocessing, so what I tried next instead is to pause and then `os._exit()` at the end of a run. This finishes the program but still doesn't play nice with wandb because the last run keeps showing as "running" for some time on UI and then fails.

The most graceful solution is to invoke `stop` instead of `pause` at the end of the run, and then resume (programmatically) when the GPU memory is available back again. This brings us to the issue of this ticket, since resuming a stopped sweep via API currently doesn't work.
Thanks.

### Environment

WandB version: latest

OS: ubuntu

Python version: 3.10

**Comment by MBakirWB** [comment]
Hi @pochtar , thanks for reporting and I recognize how there are conflicting workflows. I've asked our sweeps team to review and will provide an update when I have one.

**Comment by MBakirWB** [comment]
Hi @pochtar , the team will be picking up this as a feature request. It's a reasonable request to have workflow from sweeps/UI to align. I will keep you updated on the progress and when the feature will be released.

**Comment by MBakirWB** [comment]
Hi @pochtar, resuming finished sweeps from the command line is now supported and will be reflected in our next SDK release within next 1-2 weeks. Please do test it out and let me know if you run into any issues.
