### ISSUE TITLE
[CLI]: wandb login cli failure

### ISSUE THREAD

**Issue by nicholscrawford** [wandb/wandb#5847]
### Describe the bug

In a conda environment, installed wandb. Then attempted to log in. Just get an error. Python version 3.8.13

```shell
(ll4ma) nicholscrawfordtaylor@haku:~$ pip install wandb
Collecting wandb
  Downloading wandb-0.15.5-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 12.0 MB/s eta 0:00:00
Requirement already satisfied: PyYAML in ./anaconda3/envs/ll4ma/lib/python3.8/site-packages (from wandb) (6.0)
Requirement already satisfied: protobuf!=4.21.0,<5,>=3.12.0 in ./anaconda3/envs/ll4ma/lib/python3.8/site-packages (from wandb) (4.23.3)
Collecting GitPython!=3.1.29,>=1.0.0
  Downloading GitPython-3.1.31-py3-none-any.whl (184 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 184.3/184.3 kB 3.3 MB/s eta 0:00:00
Collecting setproctitle
  Downloading setproctitle-1.3.2-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (31 kB)
Collecting appdirs>=1.4.3
  Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Requirement already satisfied: typing-extensions in ./anaconda3/envs/ll4ma/lib/python3.8/site-packages (from wandb) (4.3.0)
Collecting sentry-sdk>=1.0.0
  Downloading sentry_sdk-1.27.1-py2.py3-none-any.whl (211 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.7/211.7 kB 3.4 MB/s eta 0:00:00
Collecting docker-pycreds>=0.4.0
  Downloading docker_pycreds-0.4.0-py2.py3-none-any.whl (9.0 kB)
Requirement already satisfied: psutil>=5.0.0 in ./anaconda3/envs/ll4ma/lib/python3.8/site-packages (from wandb) (5.9.0)
Collecting pathtools
  Downloading pathtools-0.1.2.tar.gz (11 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: setuptools in ./anaconda3/envs/ll4ma/lib/python3.8/site-packages (from wandb) (63.4.1)
Requirement already satisfied: requests<3,>=2.0.0 in ./anaconda3/envs/ll4ma/lib/python3.8/site-packages (from wandb) (2.28.1)
Requirement already satisfied: Click!=8.0.0,>=7.1 in ./.local/lib/python3.8/site-packages (from wandb) (8.1.3)
Requirement already satisfied: six>=1.4.0 in ./anaconda3/envs/ll4ma/lib/python3.8/site-packages (from docker-pycreds>=0.4.0->wandb) (1.16.0)
Collecting gitdb<5,>=4.0.1
  Downloading gitdb-4.0.10-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 877.1 kB/s eta 0:00:00
Requirement already satisfied: certifi>=2017.4.17 in ./anaconda3/envs/ll4ma/lib/python3.8/site-packages (from requests<3,>=2.0.0->wandb) (2023.5.7)
Requirement already satisfied: charset-normalizer<3,>=2 in ./anaconda3/envs/ll4ma/lib/python3.8/site-packages (from requests<3,>=2.0.0->wandb) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in ./anaconda3/envs/ll4ma/lib/python3.8/site-packages (from requests<3,>=2.0.0->wandb) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./anaconda3/envs/ll4ma/lib/python3.8/site-packages (from requests<3,>=2.0.0->wandb) (1.26.11)
Collecting smmap<6,>=3.0.1
  Using cached smmap-5.0.0-py3-none-any.whl (24 kB)
Building wheels for collected packages: pathtools
  Building wheel for pathtools (setup.py) ... done
  Created wheel for pathtools: filename=pathtools-0.1.2-py3-none-any.whl size=8792 sha256=f2d557616064aba560b7659afcfbc9ade3f89061062d8067264b8b0e086a5789
  Stored in directory: /home/nicholscrawfordtaylor/.cache/pip/wheels/4c/8e/7e/72fbc243e1aeecae64a96875432e70d4e92f3d2d18123be004
Successfully built pathtools
Installing collected packages: pathtools, appdirs, smmap, setproctitle, sentry-sdk, docker-pycreds, gitdb, GitPython, wandb
Successfully installed GitPython-3.1.31 appdirs-1.4.4 docker-pycreds-0.4.0 gitdb-4.0.10 pathtools-0.1.2 sentry-sdk-1.27.1 setproctitle-1.3.2 smmap-5.0.0 wandb-0.15.5

(ll4ma) nicholscrawfordtaylor@haku:~$ wandb login

```

```shell
(ll4ma) nicholscrawfordtaylor@haku:~$ wandb login
Traceback (most recent call last):
  File "/home/nicholscrawfordtaylor/anaconda3/envs/ll4ma/bin/wandb", line 5, in <module>
    from wandb.cli.cli import cli
  File "/home/nicholscrawfordtaylor/anaconda3/envs/ll4ma/lib/python3.8/site-packages/wandb/__init__.py", line 26, in <module>
    from wandb import sdk as wandb_sdk
  File "/home/nicholscrawfordtaylor/anaconda3/envs/ll4ma/lib/python3.8/site-packages/wandb/sdk/__init__.py", line 4, in <module>
    from .artifacts.artifact import Artifact  # noqa: F401
  File "/home/nicholscrawfordtaylor/anaconda3/envs/ll4ma/lib/python3.8/site-packages/wandb/sdk/artifacts/artifact.py", line 37, in <module>
    from wandb.apis.normalize import normalize_exceptions
  File "/home/nicholscrawfordtaylor/anaconda3/envs/ll4ma/lib/python3.8/site-packages/wandb/apis/__init__.py", line 42, in <module>
    from .internal import Api as InternalApi  # noqa
  File "/home/nicholscrawfordtaylor/anaconda3/envs/ll4ma/lib/python3.8/site-packages/wandb/apis/internal.py", line 3, in <module>
    from wandb.sdk.internal.internal_api import Api as InternalApi
  File "/home/nicholscrawfordtaylor/anaconda3/envs/ll4ma/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 46, in <module>
    from ..lib import retry
  File "/home/nicholscrawfordtaylor/anaconda3/envs/ll4ma/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 17, in <module>
    from .mailbox import ContextCancelledError
  File "/home/nicholscrawfordtaylor/anaconda3/envs/ll4ma/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 10, in <module>
    from wandb.proto import wandb_internal_pb2 as pb
  File "/home/nicholscrawfordtaylor/anaconda3/envs/ll4ma/lib/python3.8/site-packages/wandb/proto/wandb_internal_pb2.py", line 8, in <module>
    from wandb.proto.v4.wandb_internal_pb2 import *
  File "/home/nicholscrawfordtaylor/anaconda3/envs/ll4ma/lib/python3.8/site-packages/wandb/proto/v4/wandb_internal_pb2.py", line 5, in <module>
    from google.protobuf.internal import builder as _builder
  File "/home/nicholscrawfordtaylor/anaconda3/envs/ll4ma/lib/python3.8/site-packages/google/protobuf/internal/builder.py", line 42, in <module>
    from google.protobuf import reflection as _reflection
  File "/home/nicholscrawfordtaylor/anaconda3/envs/ll4ma/lib/python3.8/site-packages/google/protobuf/reflection.py", line 51, in <module>
    from google.protobuf import message_factory
  File "/home/nicholscrawfordtaylor/anaconda3/envs/ll4ma/lib/python3.8/site-packages/google/protobuf/message_factory.py", line 44, in <module>
    from google.protobuf.internal import api_implementation
  File "/home/nicholscrawfordtaylor/anaconda3/envs/ll4ma/lib/python3.8/site-packages/google/protobuf/internal/api_implementation.py", line 104, in <module>
    from google.protobuf.pyext import _message
TypeError: bases must be types
```

### Environment

WandB version: 0.15.5

OS: Ubuntu 20.04

Python version: 3.8.13

Versions of relevant libraries:

**Comment by ArtsiomWB** [comment]
Hi @nicholscrawford! apologies you are running into this concern. 

Do you happen to know what version of protobuf you currently have installed?

**Comment by nicholscrawford** [comment]
Version: 4.23.2

**Comment by ArtsiomWB** [comment]
Hi there, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by ArtsiomWB** [comment]
Hi, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by nicholscrawford** [comment]
Apologies for the delay, was just getting back from vacation. 
```
(ll4ma) nicholscrawfordtaylor@haku:~/code/pointconvformer_wrapper$ pip install protobuf==3.15.0
Collecting protobuf==3.15.0
  Downloading protobuf-3.15.0-cp38-cp38-manylinux1_x86_64.whl (1.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 8.0 MB/s eta 0:00:00
Requirement already satisfied: six>=1.9 in /home/nicholscrawfordtaylor/anaconda3/envs/ll4ma/lib/python3.8/site-packages (from protobuf==3.15.0) (1.16.0)
Installing collected packages: protobuf
  Attempting uninstall: protobuf
    Found existing installation: protobuf 4.23.3
    Uninstalling protobuf-4.23.3:
      Successfully uninstalled protobuf-4.23.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorboardx 2.6.1 requires protobuf>=4.22.3, but you have protobuf 3.15.0 which is incompatible.
Successfully installed protobuf-3.15.0
```
This gives a warning/error, the failure no longer occurs.

**Comment by nicholscrawford** [comment]
This downgrade also breaks much of my other code, making it a pretty bad solution.
