### ISSUE TITLE
[CLI]: Importing wandb breaks asyncio loop

### ISSUE THREAD

**Issue by lillekemiker** [wandb/wandb#5862]
### Describe the bug

Importing `wandb` causes `asyncio.new_event_loop()` to not work as expected.

```python
import asyncio
loop = asyncio.new_event_loop()  # No error
import wandb
loop = asyncio.new_event_loop()  # raises TypeError

```

Please note the `TypeError: changelist must be an iterable of select.kevent objects` is the error of interest below.

```shell
Traceback (most recent call last):
  File "/Users/mkristiansen/.pyenv/versions/3.9.10/lib/python3.9/asyncio/selector_events.py", line 323, in _add_reader
    key = self._selector.get_key(fd)
  File "/Users/mkristiansen/.pyenv/versions/3.9.10/lib/python3.9/selectors.py", line 193, in get_key
    raise KeyError("{!r} is not registered".format(fileobj)) from None
KeyError: '7 is not registered'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mkristiansen/git/InvokeAI/../diffusers/test2.py", line 4, in <module>
    loop = asyncio.new_event_loop()
  File "/Users/mkristiansen/.pyenv/versions/3.9.10/lib/python3.9/asyncio/events.py", line 761, in new_event_loop
    return get_event_loop_policy().new_event_loop()
  File "/Users/mkristiansen/.pyenv/versions/3.9.10/lib/python3.9/asyncio/events.py", line 659, in new_event_loop
    return self._loop_factory()
  File "/Users/mkristiansen/.pyenv/versions/3.9.10/lib/python3.9/asyncio/unix_events.py", line 54, in __init__
    super().__init__(selector)
  File "/Users/mkristiansen/.pyenv/versions/3.9.10/lib/python3.9/asyncio/selector_events.py", line 62, in __init__
    self._make_self_pipe()
  File "/Users/mkristiansen/.pyenv/versions/3.9.10/lib/python3.9/asyncio/selector_events.py", line 127, in _make_self_pipe
    self._add_reader(self._ssock.fileno(), self._read_from_self)
  File "/Users/mkristiansen/.pyenv/versions/3.9.10/lib/python3.9/asyncio/selector_events.py", line 325, in _add_reader
    self._selector.register(fd, selectors.EVENT_READ, (handle, None))
  File "/Users/mkristiansen/.pyenv/versions/3.9.10/lib/python3.9/selectors.py", line 523, in register
    self._selector.control([kev], 0, 0)
TypeError: changelist must be an iterable of select.kevent objects
Exception ignored in: <function BaseEventLoop.__del__ at 0x10b063550>
Traceback (most recent call last):
  File "/Users/mkristiansen/.pyenv/versions/3.9.10/lib/python3.9/asyncio/base_events.py", line 683, in __del__
    self.close()
  File "/Users/mkristiansen/.pyenv/versions/3.9.10/lib/python3.9/asyncio/unix_events.py", line 63, in close
    if self._signal_handlers:
AttributeError: '_UnixSelectorEventLoop' object has no attribute '_signal_handlers'

```

### Environment

WandB version: 0.15.5

OS: macOS 13.0.1 (22A400)

Python version: 3.9.10

Versions of relevant libraries: N/A

### Additional Context

I encountered this bug when attempting to install and run the `InvokeAI` package (https://github.com/invoke-ai/InvokeAI).
The package includes a FastAPI frontend which is why the `asyncio.new_event_loop()` call happens.

The reason the `wandb` package is even imported is because InvokeAI imports the `k-diffusion` package, which in turn imports `wandb` when it's available. It seems `k-diffusion` installs `wandb` as a requirement, which is the only reason it's available. I think I can probably just uninstall `wandb` but have some other things to change before I can test that theory.
Regardless, this bug is unrelated and seems pretty serious.

**Comment by ArtsiomWB** [comment]
Hi, @lillekemiker! Thank you for writing in! What version of asyncio are you currently using? 

Trying to reproduce this on my side and it seems to be working as expected.

**Comment by lillekemiker** [comment]
Hi @ArtsiomWB,
Thanks for looking into it so quickly. That is odd that you can't reproduce.
My `asyncio` is the one that comes with python 3.9.10 installed through `pyenv` on my macOS system.
Is that what you are using?

**Comment by lillekemiker** [comment]
@ArtsiomWB - I retried with a clean environment with only wandb installed and I can't reproduce either. It must be contingent on some other dependency. I'll investigate a bit further

**Comment by ArtsiomWB** [comment]
Sounds great! We appreciate your time and effort :)

**Comment by lillekemiker** [comment]
@ArtsiomWB - it looks like `eventlets` has to be installed as well for the error to occur. I checked the dependencies for `eventlets` and they don't cause the error.

My steps to reproduce:

```sh
pyenv virtualenv 3.9.10 temp
pip install -U pip wheel
pip install wandb eventlet
python test.py
```

Where `test.py` contains my example code

**Comment by ArtsiomWB** [comment]
Hi @lillekemiker! Thank you for the follow-up once again. Strangely enough running it on venv 3.9.10, with all of the commands and the code provided above still runs on my machine. I'll check internally and see if anyone else is seeing this behavior on their side!

**Comment by lillekemiker** [comment]
Definitely very odd. I don't see the error after upgrading python to `3.10.9`. My guess is that it is some compiled bug somewhere. Maybe in my python installation. Which would make it even harder to track down since it's pretty specific to my system, having been compiled on it.
Still odd. But thanks for looking into it.

**Comment by ArtsiomWB** [comment]
No problem at all! I can close this ticket for now if you'd like, but you can always write in and reopen it if something like this pops up for you again.

**Comment by lillekemiker** [comment]
Thanks again for your help. Feel free to close it for now.

**Comment by conacts** [comment]
Thank you @lillekemiker and @ArtsiomWB for resolving the issue, but do not forget to close it.
