### ISSUE TITLE
[CLI]: AttributeError: module 'wandb' has no attribute 'sdk' when running training with HuggingFace trainer on sagemaker 

### ISSUE THREAD

**Issue by jordanlgraves** [wandb/wandb#6013]
### Describe the bug

Getting an Attribute error importing wandb with HuggingFace trainer on Sagemaker.

```python

import sagemaker
from sagemaker.huggingface import HuggingFace

sagemaker_session = sagemaker.Session()
role = "arn:aws:iam::095075634539:role/service-role/AmazonSageMaker-ExecutionRole-20230608T161802"

hyperparameters = {
      "output_dir": "/opt/ml/checkpoints",
      "num_train_epochs": 1,
      "per_device_train_batch_size": 256,
      "per_device_eval_batch_size": 256,
      "gradient_accumulation_steps": 10,
      "warmup_steps": 100,
      "weight_decay": 0.01,
      "logging_steps": 10,
      "eval_steps": 1000,
      "metric_for_best_model":"loss",
      "greater_is_better": True,
      "gradient_checkpointing": True,
      "save_steps": 10,
}

huggingface_estimator = HuggingFace(
      checkpoint_s3_uri="...",
      entry_point='train.py',
      source_dir='.', 
      transformers_version='4.4.2',
      pytorch_version='1.6.0',
      py_version='py36',
      role=role,
      hyperparameters = hyperparameters,
      dependencies=['requirements.txt'],    
      instance_type='ml.p3.16xlarge',
      instance_count=1,
)

huggingface_estimator.fit()



# requirements.txt

nlpaug
transformers[torch]
datasets
torchmetrics
accelerate
deepspeed
s3fs
boto3
scikit-learn
Pillow
torchvision
wandb==0.14.2

```

```shell

Traceback (most recent call last):
  File "train.py", line 24, in <module>
    import wandb
  File "/opt/conda/lib/python3.6/site-packages/wandb/__init__.py", line 26, in <module>
    from wandb import sdk as wandb_sdk
  File "/opt/conda/lib/python3.6/site-packages/wandb/sdk/__init__.py", line 7, in <module>
    from .wandb_init import _attach, init  # noqa: F401
  File "/opt/conda/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 32, in <module>
    from .backend.backend import Backend
  File "/opt/conda/lib/python3.6/site-packages/wandb/sdk/backend/backend.py", line 17, in <module>
    from wandb.sdk.interface.interface import InterfaceBase
  File "/opt/conda/lib/python3.6/site-packages/wandb/sdk/interface/interface.py", line 19, in <module>
    import wandb.sdk.lib.json_util as json

AttributeError: module 'wandb' has no attribute 'sdk'
```

### Environment

WandB version: 0.15.8

OS: training image: 763104351884.dkr.ecr.us-east-1.amazonaws.com/huggingface-pytorch-training:1.6.0-transformers4.4.2-gpu-py36-cu110-ubuntu18.04

Python version: py36

Versions of relevant libraries:

**Comment by luisbergua** [comment]
Hi @jordanlgraves, thanks for reporting this! I was able to reproduce this using `python 3.6` (same as you, right?). As you can see [here](https://github.com/wandb/wandb/blob/cf20648b1665ea1bb6295515e166a5ea62fe92d8/pyproject.toml#L14C26-L14C26), we do not officially support `python<3.7` sot this is why you're seeing this error, using `python >=3.7` works properly for me.

**Comment by luisbergua** [comment]
Hi @jordanlgraves , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
