### ISSUE TITLE
[CLI]: Unable to sync offline record to server.

### ISSUE THREAD

**Issue by hh-xiaohu** [wandb/wandb#6045]
### Describe the bug

Due to network issues, I trained the neural network in offline mode. My network training was unexpectedly interrupted, and I want to synchronize the locally stored WandB records to the cloud. However, I encountered the following error.

```python
wandb sync ./wandb/offline-run-20230807_123301-2vmc9ygs
```

```shell
Syncing: https://wandb.ai/xxx/xxx/runs/2vmc9ygs ...Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/site-packages/wandb/sync/sync.py", line 265, in run
    sm.send(pb)
  File "/usr/local/lib/python3.6/site-packages/wandb/sdk/internal/sender.py", line 227, in send
    assert record_type
AssertionError
```
According to issue #5239 , I run:
```python
python -c "import wandb; print(wandb.util.generate_id())"
```
But nothing helps.

### Environment

WandB version: 0.15.5

OS:

Python version: 3.6

Versions of relevant libraries: pytorch-lightning 1.4.9

**Comment by rsanandres-wandb** [comment]
Hello!

**Comment by rsanandres-wandb** [comment]
Hello @hh-xiaohu !

After you created a new id, did you run `wandb sync [PATH] -p <PROJECT_NAME> -e --id new_run_id` which should sync your run to a new id.

**Comment by hh-xiaohu** [comment]
Got an error:

```python
wandb sync offline-run-20230814_120702-bcgvdzy5 -p aegnn-ncaltech101-recognition -e --id=3l66kjbz
```
```shell
wandb: ERROR Error while calling W&B API: entity --id=3l66kjbz not found during upsertBucket (<Response [404]>)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/hanh/anaconda3/envs/aegnn/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/hanh/anaconda3/envs/aegnn/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 140, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/hanh/anaconda3/envs/aegnn/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/hanh/anaconda3/envs/aegnn/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/hanh/anaconda3/envs/aegnn/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/home/hanh/anaconda3/envs/aegnn/lib/python3.8/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
**requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hanh/anaconda3/envs/aegnn/lib/python3.8/site-packages/wandb/apis/normalize.py", line 22, in wrapper
    return func(*args, **kwargs)
  File "/home/hanh/anaconda3/envs/aegnn/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1318, in upsert_run
    response = self.gql(mutation, variable_values=variable_values, **kwargs)
  File "/home/hanh/anaconda3/envs/aegnn/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 118, in __call__
    if not check_retry_fn(e):
  File "/home/hanh/anaconda3/envs/aegnn/lib/python3.8/site-packages/wandb/util.py", line 879, in no_retry_auth
    raise CommError("Permission denied, ask the project owner to grant you access")
**wandb.errors.CommError: Permission denied, ask the project owner to grant you access**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hanh/anaconda3/envs/aegnn/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/hanh/anaconda3/envs/aegnn/lib/python3.8/site-packages/wandb/sync/sync.py", line 265, in run
    sm.send(pb)
  File "/home/hanh/anaconda3/envs/aegnn/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 234, in send
    send_handler(record)
  File "/home/hanh/anaconda3/envs/aegnn/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 692, in send_run
    self._init_run(run, config_value_dict)
  File "/home/hanh/anaconda3/envs/aegnn/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 716, in _init_run
    server_run, inserted = self._api.upsert_run(
  File "/home/hanh/anaconda3/envs/aegnn/lib/python3.8/site-packages/wandb/apis/normalize.py", line 58, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "/home/hanh/anaconda3/envs/aegnn/lib/python3.8/site-packages/wandb/apis/normalize.py", line 22, in wrapper
    return func(*args, **kwargs)
  File "/home/hanh/anaconda3/envs/aegnn/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1318, in upsert_run
    response = self.gql(mutation, variable_values=variable_values, **kwargs)
  File "/home/hanh/anaconda3/envs/aegnn/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 118, in __call__
    if not check_retry_fn(e):
  File "/home/hanh/anaconda3/envs/aegnn/lib/python3.8/site-packages/wandb/util.py", line 879, in no_retry_auth
    raise CommError("Permission denied, ask the project owner to grant you access")
**wandb.errors.CommError: Permission denied, ask the project owner to grant you access**

```
It reminds me that I didn't get permission, but I've already logged into my WandB account.

```shell
wandb login
```

```shell
wandb: Currently logged in as: xxxx (use `wandb login --relogin` to force relogin)
```

**Comment by rsanandres-wandb** [comment]
Apolgies, the query is `wandb sync [PATH] -p <PROJECT_NAME> -e <ENTITY> --id new_run_id`. You will have to enter in the entity as well.

**Comment by umakrishnaswamy** [comment]
Hi @hh-xiaohu,

I'm a member of Wandb's support team alongside Raphael. We wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if the query worked well for you!

**Comment by sydholl** [comment]
WandB Internal User commented: 
rsanandres-wandb commented: 
Hello @hh-xiaohu !

After you created a new id, did you run `wandb sync [PATH] -p <PROJECT_NAME> -e --id new_run_id` which should sync your run to a new id.

**Comment by sydholl** [comment]
WandB Internal User commented: 
hh-xiaohu commented: 
Got an error:

```python
wandb sync offline-run-20230814_120702-bcgvdzy5 -p aegnn-ncaltech101-recognition -e --id=3l66kjbz
```
```shell
wandb: ERROR Error while calling W&B API: entity --id=3l66kjbz not found during upsertBucket (<Response [404]>)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/hanh/anaconda3/envs/aegnn/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/hanh/anaconda3/envs/aegnn/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 140, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/hanh/anaconda3/envs/aegnn/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/hanh/anaconda3/envs/aegnn/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/hanh/anaconda3/envs/aegnn/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/home/hanh/anaconda3/envs/aegnn/lib/python3.8/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
**requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hanh/anaconda3/envs/aegnn/lib/python3.8/site-packages/wandb/apis/normalize.py", line 22, in wrapper
    return func(*args, **kwargs)
  File "/home/hanh/anaconda3/envs/aegnn/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1318, in upsert_run
    response = self.gql(mutation, variable_values=variable_values, **kwargs)
  File "/home/hanh/anaconda3/envs/aegnn/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 118, in __call__
    if not check_retry_fn(e):
  File "/home/hanh/anaconda3/envs/aegnn/lib/python3.8/site-packages/wandb/util.py", line 879, in no_retry_auth
    raise CommError("Permission denied, ask the project owner to grant you access")
**wandb.errors.CommError: Permission denied, ask the project owner to grant you access**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hanh/anaconda3/envs/aegnn/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/hanh/anaconda3/envs/aegnn/lib/python3.8/site-packages/wandb/sync/sync.py", line 265, in run
    sm.send(pb)
  File "/home/hanh/anaconda3/envs/aegnn/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 234, in send
    send_handler(record)
  File "/home/hanh/anaconda3/envs/aegnn/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 692, in send_run
    self._init_run(run, config_value_dict)
  File "/home/hanh/anaconda3/envs/aegnn/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 716, in _init_run
    server_run, inserted = self._api.upsert_run(
  File "/home/hanh/anaconda3/envs/aegnn/lib/python3.8/site-packages/wandb/apis/normalize.py", line 58, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "/home/hanh/anaconda3/envs/aegnn/lib/python3.8/site-packages/wandb/apis/normalize.py", line 22, in wrapper
    return func(*args, **kwargs)
  File "/home/hanh/anaconda3/envs/aegnn/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1318, in upsert_run
    response = self.gql(mutation, variable_values=variable_values, **kwargs)
  File "/home/hanh/anaconda3/envs/aegnn/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 118, in __call__
    if not check_retry_fn(e):
  File "/home/hanh/anaconda3/envs/aegnn/lib/python3.8/site-packages/wandb/util.py", line 879, in no_retry_auth
    raise CommError("Permission denied, ask the project owner to grant you access")
**wandb.errors.CommError: Permission denied, ask the project owner to grant you access**

```
It reminds me that I didn't get permission, but I've already logged into my WandB account.

```shell
wandb login
```

```shell
wandb: Currently logged in as: xxxx (use `wandb login --relogin` to force relogin)
```

**Comment by spacegoing** [comment]
I had this error, it turns out to be I'm running stale wandb version on my local, a `pip install --upgrade wandb` solves it

**Comment by Apple-Zhang** [comment]
> I had this error, it turns out to be I'm running stale wandb version on my local, a `pip install --upgrade wandb` solves it

This almost solves my problem! I met the exception thrown by Pydantic after I updated wandb. I solved the problem by “pip install --upgrade pydantic”.

**Comment by jakeweatherhead** [comment]
> I had this error, it turns out to be I'm running stale wandb version on my local, a `pip install --upgrade wandb` solves it

@spacegoing's solution worked for me. I was getting the `record_type` AssertionError when attempting to sync my offline WandB runs. Turns out my WandB installation was running the outdated `v0.20.1`.

After running `pip install --upgrade wandb` my installation was upgraded to the current latest version (`v0.21.0`) and I was able to sync my runs.
