### ISSUE TITLE
[CLI]: wandb.Api.sweep fails when the path only contains the sweep ID

### ISSUE THREAD

**Issue by alegonz** [wandb/wandb#6168]
### Describe the bug

The docstring for `wandb.Api.sweep` states:

```
    path: (str, optional) path to sweep in the form entity/project/sweep_id.  If `api.entity`
                is set, this can be in the form project/sweep_id and if `api.project` is set
                this can just be the sweep_id.
```
however, passing only the sweep ID fails as shown below.

I presume that by "If `api.entity` is set, ... if `api.project` is set" means to pass `overrides={"entity": "gon", "project": "test2"}` at instantiation because the class does not have an `entity` attribute and the `project` attribute actually points to a method.

```python
>>> import wandb
>>> api = wandb.Api(overrides={"entity": "gon", "project": "test2"})
>>> api.sweep("bj0a1t6i")
```

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/wandb/apis/public.py", line 998, in sweep
    self._sweeps[path] = Sweep(self.client, entity, project, sweep_id)
  File "/usr/local/lib/python3.8/dist-packages/wandb/apis/public.py", line 2867, in __init__
    self.load(force=not attrs)
  File "/usr/local/lib/python3.8/dist-packages/wandb/apis/public.py", line 2886, in load
    raise ValueError("Could not find sweep %s" % self)
ValueError: Could not find sweep <Sweep gon/bj0a1t6i/bj0a1t6i (Unknown State)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/wandb/apis/normalize.py", line 87, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "/usr/local/lib/python3.8/dist-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/wandb/apis/public.py", line 998, in sweep
    self._sweeps[path] = Sweep(self.client, entity, project, sweep_id)
  File "/usr/local/lib/python3.8/dist-packages/wandb/apis/public.py", line 2867, in __init__
    self.load(force=not attrs)
  File "/usr/local/lib/python3.8/dist-packages/wandb/apis/public.py", line 2886, in load
    raise ValueError("Could not find sweep %s" % self)
wandb.errors.CommError: Could not find sweep <Sweep gon/bj0a1t6i/bj0a1t6i (Unknown State)>
```
The entity, project and sweep indeed exist as calling the function with a path of the form `entity/project/sweep_id` does work:
```python
>>> api.sweep("gon/test2/bj0a1t6i")
<Sweep gon/test2/bj0a1t6i (FINISHED)>
```

### Environment

WandB version: 0.15.8

OS: Ubuntu 20.04

Python version: 3.8.10

Versions of relevant libraries:

**Comment by umakrishnaswamy** [comment]
Hey @alegonz, I was able to reproduce this issue. Thank you for raising this, and I will escalate this to our engineering team and let you know when any progress on this arises.
