### ISSUE TITLE
[Q] Continuously got the error -  OSError: [Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by AustinApple** [wandb/wandb#6176]
Hello,
I continuously got the following error recently. 
```
Traceback (most recent call last):
  File "/data/mwu11/anaconda3/envs/diffdock/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 1075, in init
    wi.setup(kwargs)
  File "/data/mwu11/anaconda3/envs/diffdock/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 165, in setup
    self._wl = wandb_setup.setup()
  File "/data/mwu11/anaconda3/envs/diffdock/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 312, in setup
    ret = _setup(settings=settings)
  File "/data/mwu11/anaconda3/envs/diffdock/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 307, in _setup
    wl = _WandbSetup(settings=settings)
  File "/data/mwu11/anaconda3/envs/diffdock/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 293, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/data/mwu11/anaconda3/envs/diffdock/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 100, in __init__
    self._settings = self._settings_setup(settings, self._early_logger)
  File "/data/mwu11/anaconda3/envs/diffdock/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 130, in _settings_setup
    s._infer_run_settings_from_environment(_logger=early_logger)
  File "/data/mwu11/anaconda3/envs/diffdock/lib/python3.7/site-packages/wandb/sdk/wandb_settings.py", line 1429, in _infer_run_settings_from_environment
    program, _logger=_logger
  File "/data/mwu11/anaconda3/envs/diffdock/lib/python3.7/site-packages/wandb/sdk/wandb_settings.py", line 139, in _get_program_relpath_from_gitrepo
    root = repo.root
  File "/data/mwu11/anaconda3/envs/diffdock/lib/python3.7/site-packages/wandb/sdk/lib/git.py", line 65, in root
    return self.repo.git.rev_parse("--show-toplevel")
  File "/data/mwu11/anaconda3/envs/diffdock/lib/python3.7/site-packages/git/cmd.py", line 696, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/data/mwu11/anaconda3/envs/diffdock/lib/python3.7/site-packages/git/cmd.py", line 1270, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/data/mwu11/anaconda3/envs/diffdock/lib/python3.7/site-packages/git/cmd.py", line 952, in execute
    **subprocess_kwargs,
  File "/data/mwu11/anaconda3/envs/diffdock/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/data/mwu11/anaconda3/envs/diffdock/lib/python3.7/subprocess.py", line 1482, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 12] Cannot allocate memory
wandb: ERROR Abnormal program exit
Traceback (most recent call last):
  File "/data/mwu11/anaconda3/envs/diffdock/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 1075, in init
    wi.setup(kwargs)
  File "/data/mwu11/anaconda3/envs/diffdock/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 165, in setup
    self._wl = wandb_setup.setup()
  File "/data/mwu11/anaconda3/envs/diffdock/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 312, in setup
    ret = _setup(settings=settings)
  File "/data/mwu11/anaconda3/envs/diffdock/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 307, in _setup
    wl = _WandbSetup(settings=settings)
  File "/data/mwu11/anaconda3/envs/diffdock/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 293, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/data/mwu11/anaconda3/envs/diffdock/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 100, in __init__
    self._settings = self._settings_setup(settings, self._early_logger)
  File "/data/mwu11/anaconda3/envs/diffdock/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 130, in _settings_setup
    s._infer_run_settings_from_environment(_logger=early_logger)
  File "/data/mwu11/anaconda3/envs/diffdock/lib/python3.7/site-packages/wandb/sdk/wandb_settings.py", line 1429, in _infer_run_settings_from_environment
    program, _logger=_logger
  File "/data/mwu11/anaconda3/envs/diffdock/lib/python3.7/site-packages/wandb/sdk/wandb_settings.py", line 139, in _get_program_relpath_from_gitrepo
    root = repo.root
  File "/data/mwu11/anaconda3/envs/diffdock/lib/python3.7/site-packages/wandb/sdk/lib/git.py", line 65, in root
    return self.repo.git.rev_parse("--show-toplevel")
  File "/data/mwu11/anaconda3/envs/diffdock/lib/python3.7/site-packages/git/cmd.py", line 696, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/data/mwu11/anaconda3/envs/diffdock/lib/python3.7/site-packages/git/cmd.py", line 1270, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/data/mwu11/anaconda3/envs/diffdock/lib/python3.7/site-packages/git/cmd.py", line 952, in execute
    **subprocess_kwargs,
  File "/data/mwu11/anaconda3/envs/diffdock/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/data/mwu11/anaconda3/envs/diffdock/lib/python3.7/subprocess.py", line 1482, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 12] Cannot allocate memory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/mwu11/anaconda3/envs/diffdock/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data/mwu11/anaconda3/envs/diffdock/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/mwu11/DiffDock/affinity/affinity_train_davis_graphdta_embedding.py", line 380, in <module>
    config=args
  File "/data/mwu11/anaconda3/envs/diffdock/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 1116, in init
    raise Exception("problem") from error_seen
Exception: problem
```
Does it mean I run out of memory? But when checking the memory usage during code running, 
```
               total       used        free	 shared  buff/cache   available
Mem:           1.0T        875G        2.7G         11G        129G        118G
Swap:            9G          9G          0B
```
It seems that I still have memory.

**Comment by luisbergua** [comment]
Hi @AustinApple, thank you for reporting this and soryr that you're running into issues! To figure out what's going on here, would you mind sharing the following?

- `debug.log` and `debug-internal.log `for the affected run? These files are under your local folder `wandb/run-<date>_<time>-<run-id>/logs` in the same directory where you’re running your code.
- A code snippet so I can see calls to wandb and also try to repro this on my end
- A link to the affected run
- Any more details about the environment this happens in

I'll revise those to provide you a clearer answer

**Comment by luisbergua** [comment]
Hi @AustinApple, following up here! Did you have the chance to look at my previous message and would you mind sharing the requested information? That would really help identify the issue here!

**Comment by sydholl** [comment]
Sydney Hollingsworth commented: 
This ticket has gone stale, please follow up or close.

**Comment by sydholl** [comment]
Luis Bergua commented: 
Already followed up

**Comment by amorehead** [comment]
I believe I am having the same issue with `wandb` version `0.15.9`.

**Comment by luisbergua** [comment]
Hi @amorehead, I'm sorry that this is also affecting. Would you mind sharing:

> * `debug.log` and `debug-internal.log` for the affected run? These files are under your local folder `wandb/run-<date>_<time>-<run-id>/logs` in the same directory where you’re running your code.
> * A code snippet so I can see calls to wandb and also try to repro this on my end
> * A link to the affected run
> * Any more details about the environment this happens in

**Comment by luisbergua** [comment]
Thank you so much for confirming this @amorehead and great to see this was resolved!

**Comment by sydholl** [comment]
WandB Internal User commented: 
luisbergua commented: 
Hi @amorehead, I'm sorry that this is also affecting. Would you mind sharing:

> * `debug.log` and `debug-internal.log` for the affected run? These files are under your local folder `wandb/run-<date>_<time>-<run-id>/logs` in the same directory where you’re running your code.
> * A code snippet so I can see calls to wandb and also try to repro this on my end
> * A link to the affected run
> * Any more details about the environment this happens in

**Comment by sydholl** [comment]
WandB Internal User commented: 
luisbergua commented: 
Thank you so much for confirming this @amorehead and great to see this was resolved!
