### ISSUE TITLE
[CLI]: Cannot use with `debugpy.connect`, something wrong with `sys.executable`

### ISSUE THREAD

**Issue by DavidZhang73** [wandb/wandb#6290]
### Describe the bug

I'm using `PyTorch Lightning` with `wandb` and want to remote debug my code, hence use `debugpy` and vscode. If vscode is in debug mode which means it is waiting for debug connection, everything works fine, but if not, wandb says something wrong with `sys.executable` configuration.

```python
import debugpy
import wandb

try:
    debugpy.connect(5678)
except Exception as e:
    print(e)

wandb.init(project="test")
```

`launch.json` for vscode:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Remote Debug",
            "type": "python",
            "request": "attach",
            "listen": {
                "host": "0.0.0.0",
                "port": 5678
            },
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}",
                    "remoteRoot": "."
                }
            ],
            "justMyCode": false
        }
    ]
}
```

```shell
0.18s - Could not connect to 127.0.0.1: 5678
Traceback (most recent call last):
  File "/home/users/u6921098/miniconda3/envs/TemporalDiagramGroundingInVideos/lib/python3.10/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 493, in start_client
    s.connect((host, port))
ConnectionRefusedError: [Errno 111] Connection refused
[Errno 111] Connection refused
0.03s - Could not connect to 127.0.0.1: 5678
Traceback (most recent call last):
  File "/home/users/u6921098/miniconda3/envs/TemporalDiagramGroundingInVideos/lib/python3.10/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 493, in start_client
    s.connect((host, port))
ConnectionRefusedError: [Errno 111] Connection refused
Could not connect to 127.0.0.1: 5678
Traceback (most recent call last):
  File "/home/users/u6921098/miniconda3/envs/TemporalDiagramGroundingInVideos/lib/python3.10/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 3476, in main
    debugger.connect(host, port)
  File "/home/users/u6921098/miniconda3/envs/TemporalDiagramGroundingInVideos/lib/python3.10/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 1421, in connect
    s = start_client(host, port)
  File "/home/users/u6921098/miniconda3/envs/TemporalDiagramGroundingInVideos/lib/python3.10/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 493, in start_client
    s.connect((host, port))
ConnectionRefusedError: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/users/u6921098/project/TemporalDiagramGroundingInVideos/demo.py", line 16, in <module>
    wandb.init(project="TemporalDiagramGroundingInVideos")
  File "/home/users/u6921098/miniconda3/envs/TemporalDiagramGroundingInVideos/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1184, in init
    raise e
  File "/home/users/u6921098/miniconda3/envs/TemporalDiagramGroundingInVideos/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1161, in init
    wi.setup(kwargs)
  File "/home/users/u6921098/miniconda3/envs/TemporalDiagramGroundingInVideos/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 189, in setup
    self._wl = wandb_setup.setup(settings=setup_settings)
  File "/home/users/u6921098/miniconda3/envs/TemporalDiagramGroundingInVideos/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 327, in setup
    ret = _setup(settings=settings)
  File "/home/users/u6921098/miniconda3/envs/TemporalDiagramGroundingInVideos/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 320, in _setup
    wl = _WandbSetup(settings=settings)
  File "/home/users/u6921098/miniconda3/envs/TemporalDiagramGroundingInVideos/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 303, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/home/users/u6921098/miniconda3/envs/TemporalDiagramGroundingInVideos/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 114, in __init__
    self._setup()
  File "/home/users/u6921098/miniconda3/envs/TemporalDiagramGroundingInVideos/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 250, in _setup
    self._setup_manager()
  File "/home/users/u6921098/miniconda3/envs/TemporalDiagramGroundingInVideos/lib/python3.10/site-packages/wandb/sdk/wandb_setup.py", line 277, in _setup_manager
    self._manager = wandb_manager._Manager(settings=self._settings)
  File "/home/users/u6921098/miniconda3/envs/TemporalDiagramGroundingInVideos/lib/python3.10/site-packages/wandb/sdk/wandb_manager.py", line 138, in __init__
    self._service.start()
  File "/home/users/u6921098/miniconda3/envs/TemporalDiagramGroundingInVideos/lib/python3.10/site-packages/wandb/sdk/service/service.py", line 245, in start
    self._launch_server()
  File "/home/users/u6921098/miniconda3/envs/TemporalDiagramGroundingInVideos/lib/python3.10/site-packages/wandb/sdk/service/service.py", line 239, in _launch_server
    _sentry.reraise(e)
  File "/home/users/u6921098/miniconda3/envs/TemporalDiagramGroundingInVideos/lib/python3.10/site-packages/wandb/analytics/sentry.py", line 154, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/users/u6921098/miniconda3/envs/TemporalDiagramGroundingInVideos/lib/python3.10/site-packages/wandb/sdk/service/service.py", line 237, in _launch_server
    self._wait_for_ports(fname, proc=internal_proc)
  File "/home/users/u6921098/miniconda3/envs/TemporalDiagramGroundingInVideos/lib/python3.10/site-packages/wandb/sdk/service/service.py", line 106, in _wait_for_ports
    raise ServiceStartProcessError(
wandb.sdk.service.service.ServiceStartProcessError: The wandb service process exited with 1. Ensure that `sys.executable` is a valid python interpreter. You can override it with the `_executable` setting or with the `WANDB__EXECUTABLE` environment variable.
```

### Environment

WandB version: 0.15.10

OS: Linux millbrae 5.15.0-56-generic #62~20.04.1-Ubuntu SMP Tue Nov 22 21:24:20 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Python version: Python 3.10.10

Versions of relevant libraries: debugpy==1.8.0

**Comment by DavidZhang73** [comment]
Hi @MBakirWB, result with the env:

```bash
0.12s - Could not connect to 127.0.0.1: 5678
Traceback (most recent call last):
  File "/home/users/u6921098/miniconda3/envs/TemporalDiagramGroundingInVideos/lib/python3.10/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 493, in start_client
    s.connect((host, port))
ConnectionRefusedError: [Errno 111] Connection refused
[Errno 111] Connection refused
wandb: Currently logged in as: davidz. Use `wandb login --relogin` to force relogin
0.03s - Could not connect to 127.0.0.1: 5678
Traceback (most recent call last):
  File "/home/users/u6921098/miniconda3/envs/TemporalDiagramGroundingInVideos/lib/python3.10/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 493, in start_client
    s.connect((host, port))
ConnectionRefusedError: [Errno 111] Connection refused
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/users/u6921098/miniconda3/envs/TemporalDiagramGroundingInVideos/lib/python3.10/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 2821, in settrace
    _locked_settrace(
  File "/home/users/u6921098/miniconda3/envs/TemporalDiagramGroundingInVideos/lib/python3.10/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 2902, in _locked_settrace
    py_db.connect(host, port)  # Note: connect can raise error.
  File "/home/users/u6921098/miniconda3/envs/TemporalDiagramGroundingInVideos/lib/python3.10/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 1421, in connect
    s = start_client(host, port)
  File "/home/users/u6921098/miniconda3/envs/TemporalDiagramGroundingInVideos/lib/python3.10/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 493, in start_client
    s.connect((host, port))
ConnectionRefusedError: [Errno 111] Connection refused
0.03s - Could not connect to 127.0.0.1: 5678
Traceback (most recent call last):
  File "/home/users/u6921098/miniconda3/envs/TemporalDiagramGroundingInVideos/lib/python3.10/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 493, in start_client
    s.connect((host, port))
ConnectionRefusedError: [Errno 111] Connection refused
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/users/u6921098/miniconda3/envs/TemporalDiagramGroundingInVideos/lib/python3.10/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 2821, in settrace
    _locked_settrace(
  File "/home/users/u6921098/miniconda3/envs/TemporalDiagramGroundingInVideos/lib/python3.10/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 2902, in _locked_settrace
    py_db.connect(host, port)  # Note: connect can raise error.
  File "/home/users/u6921098/miniconda3/envs/TemporalDiagramGroundingInVideos/lib/python3.10/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 1421, in connect
    s = start_client(host, port)
  File "/home/users/u6921098/miniconda3/envs/TemporalDiagramGroundingInVideos/lib/python3.10/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 493, in start_client
    s.connect((host, port))
ConnectionRefusedError: [Errno 111] Connection refused
Problem at: /home/users/u6921098/project/TemporalDiagramGroundingInVideos/demo.py 9 <module>
Traceback (most recent call last):
  File "/home/users/u6921098/project/TemporalDiagramGroundingInVideos/demo.py", line 9, in <module>
    wandb.init(project="test")
  File "/home/users/u6921098/miniconda3/envs/TemporalDiagramGroundingInVideos/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1184, in init
    raise e
  File "/home/users/u6921098/miniconda3/envs/TemporalDiagramGroundingInVideos/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1165, in init
    run = wi.init()
  File "/home/users/u6921098/miniconda3/envs/TemporalDiagramGroundingInVideos/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 751, in init
    result = run_init_handle.wait(
  File "/home/users/u6921098/miniconda3/envs/TemporalDiagramGroundingInVideos/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 281, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed
/home/users/u6921098/miniconda3/envs/TemporalDiagramGroundingInVideos/lib/python3.10/multiprocessing/resource_tracker.py:104: UserWarning: resource_tracker: process died unexpectedly, relaunching.  Some resources might leak.
  warnings.warn('resource_tracker: process died unexpectedly, '
0.03s - Could not connect to 127.0.0.1: 5678
Traceback (most recent call last):
  File "/home/users/u6921098/miniconda3/envs/TemporalDiagramGroundingInVideos/lib/python3.10/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 493, in start_client
    s.connect((host, port))
ConnectionRefusedError: [Errno 111] Connection refused
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/users/u6921098/miniconda3/envs/TemporalDiagramGroundingInVideos/lib/python3.10/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 2821, in settrace
    _locked_settrace(
  File "/home/users/u6921098/miniconda3/envs/TemporalDiagramGroundingInVideos/lib/python3.10/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 2902, in _locked_settrace
    py_db.connect(host, port)  # Note: connect can raise error.
  File "/home/users/u6921098/miniconda3/envs/TemporalDiagramGroundingInVideos/lib/python3.10/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 1421, in connect
    s = start_client(host, port)
  File "/home/users/u6921098/miniconda3/envs/TemporalDiagramGroundingInVideos/lib/python3.10/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 493, in start_client
    s.connect((host, port))
ConnectionRefusedError: [Errno 111] Connection refused
```
