### ISSUE TITLE
[CLI]: Wandb throws "Connection to wandb service failed: [Errno 111] Connection refused." even though wandb is disabled

### ISSUE THREAD

**Issue by Saydemr** [wandb/wandb#6307]
### Describe the bug

Wandb is disabled with `wandb disabled` command. In the middle of a run, wandb exits with the following error even though it is disabled.

```shell
Error executing job with overrides: ['model.dropout=0.5', 'model.dprate=0.3', 'model.hidden_dim=128', 'task.prop_lr=0.01876712569139643', 'task.lr=0.052119386113837755', 'task.weight_decay=0.0009362746022136746', 'task.prop_wd=0.00040287573177016635']
Traceback (most recent call last):
  File "/nfs/homedirs/saya/miniconda3/envs/p3/lib/python3.8/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/nfs/homedirs/saya/miniconda3/envs/p3/lib/python3.8/site-packages/hydra/_internal/utils.py", line 466, in <lambda>
    lambda: hydra.multirun(
  File "/nfs/homedirs/saya/miniconda3/envs/p3/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 162, in multirun
    ret = sweeper.sweep(arguments=task_overrides)
  File "/nfs/homedirs/saya/miniconda3/envs/p3/lib/python3.8/site-packages/hydra_plugins/hydra_optuna_sweeper/optuna_sweeper.py", line 52, in sweep
    return self.sweeper.sweep(arguments)
  File "/nfs/homedirs/saya/miniconda3/envs/p3/lib/python3.8/site-packages/hydra_plugins/hydra_optuna_sweeper/_impl.py", line 391, in sweep
    raise e
  File "/nfs/homedirs/saya/miniconda3/envs/p3/lib/python3.8/site-packages/hydra_plugins/hydra_optuna_sweeper/_impl.py", line 357, in sweep
    values = [float(ret.return_value)]
  File "/nfs/homedirs/saya/miniconda3/envs/p3/lib/python3.8/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
wandb.sdk.wandb_manager.ManagerConnectionRefusedError: Connection to wandb service failed: [Errno 111] Connection refused.
```

### Environment

WandB version: 0.15.2

OS: Ubuntu 5.4.0-131-generic

Python version: 3.8.10

Versions of relevant libraries:
[environment file](https://github.com/wandb/wandb/files/12643191/environment.txt) (used from conda)

**Comment by thanos-wandb** [comment]
Hi @Saydemr thank you for reporting this issue. May I please ask for some more context, were there any other runs with mode online prior to this one? it seems that some background wandb processes hadn't terminated. Is this issue reproducible on your end, or just occurred once? Could you please provide us with the debug.log and debug-internal.log files from the failed run? These files are under your local folder wandb/run-<date>_<time>-<run-id>/logs in the same directory where you’re running your code.

**Comment by thanos-wandb** [comment]
Hi @Saydemr I wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by Saydemr** [comment]
Hello, I just deleted every file related to wandb, removed wandb, reset the server, reinstalled wandb and run it again. Therefore, I do not have the log file.

Sorry for the inconvenience...

**Comment by thanos-wandb** [comment]
Thanks for the update @Saydemr we will close the ticket on our end, but please feel free to reopen this if the same issue ever pops up again and we will be happy to keep investigating.
