### ISSUE TITLE
[CLI]: Google Cloud Storage Module Import

### ISSUE THREAD

**Issue by peterdavidfagan** [wandb/wandb#6320]
### Describe the bug

I receive an error message related to storage.Client not being found when downloading artifacts. If I manually run `from google.storage import Client` the error goes away.

To replicate try to download any artifact from GCP bucket storage without importing the storage client manually in your script.

```shell
wandb: Downloading large artifact concept_learner_v2:latest, 481.07MB. 221 files... 
Error executing job with overrides: ['+move_puzzle=single_gpu_executor_default']
Traceback (most recent call last):
  File "/home/peter/Code/research_projects/visual_concept_planner/visual_concept_planner/evaluate_concept_learner.py", line 293, in evaluate_model
    model_path = wandb.use_artifact("ipab-rad/model-registry/concept_learner_v2:latest").download()
  File "/home/peter/.cache/pypoetry/virtualenvs/visual_concept_planner-cmy0OQ_m-py3.10/lib/python3.10/site-packages/wandb/sdk/artifacts/public_artifact.py", line 668, in download
    pool.map(
  File "/home/peter/.pyenv/versions/3.10.6/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/peter/.pyenv/versions/3.10.6/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/home/peter/.pyenv/versions/3.10.6/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/peter/.pyenv/versions/3.10.6/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/peter/.cache/pypoetry/virtualenvs/visual_concept_planner-cmy0OQ_m-py3.10/lib/python3.10/site-packages/wandb/sdk/artifacts/public_artifact.py", line 665, in _download_file_with_thread_local_api_settings
    return self._download_file(name, root, download_logger)
  File "/home/peter/.cache/pypoetry/virtualenvs/visual_concept_planner-cmy0OQ_m-py3.10/lib/python3.10/site-packages/wandb/sdk/artifacts/public_artifact.py", line 769, in _download_file
    downloaded_path = self.get_path(name).download(root)
  File "/home/peter/.cache/pypoetry/virtualenvs/visual_concept_planner-cmy0OQ_m-py3.10/lib/python3.10/site-packages/wandb/sdk/artifacts/artifact_manifest_entry.py", line 87, in download
    cache_path = self._parent_artifact.manifest.storage_policy.load_reference(
  File "/home/peter/.cache/pypoetry/virtualenvs/visual_concept_planner-cmy0OQ_m-py3.10/lib/python3.10/site-packages/wandb/sdk/artifacts/storage_policies/wandb_storage_policy.py", line 152, in load_reference
    return self._handler.load_path(manifest_entry, local)
  File "/home/peter/.cache/pypoetry/virtualenvs/visual_concept_planner-cmy0OQ_m-py3.10/lib/python3.10/site-packages/wandb/sdk/artifacts/storage_handlers/multi_handler.py", line 40, in load_path
    return handler.load_path(manifest_entry, local=local)
  File "/home/peter/.cache/pypoetry/virtualenvs/visual_concept_planner-cmy0OQ_m-py3.10/lib/python3.10/site-packages/wandb/sdk/artifacts/storage_handlers/gcs_handler.py", line 78, in load_path
    self.init_gcs()
  File "/home/peter/.cache/pypoetry/virtualenvs/visual_concept_planner-cmy0OQ_m-py3.10/lib/python3.10/site-packages/wandb/sdk/artifacts/storage_handlers/gcs_handler.py", line 52, in init_gcs
    self._client = storage.Client()
AttributeError: module 'google.cloud.storage' has no attribute 'Client'
```

### Environment

WandB version: 0.15.4

OS: Ubuntu 22.04

Python version: 3.10.6

Versions of relevant libraries:

**Comment by umakrishnaswamy** [comment]
Hey @peterdavidfagan - thank you for flagging this. I was able to reproduce this and will update this thread once progress is made on the bug

**Comment by umakrishnaswamy** [comment]
Hey @peterdavidfagan - few questions to help me dig into this further:

- How many files are there in the artifact and what’s the amount of data? Or does this error occur with artifacts of various sizes?
- Is this error being raised when downloading the artifact both from a run and from the API? Or one or the other?
```
run = wandb.init()
artifact = run.use_artifact()
artifact_dir = artifact.download()
-----------------------------------
api = wandb.Api()
artifact = api.artifact()
artifact_dir = artifact.download()
```

**Comment by peterdavidfagan** [comment]
> Hey @peterdavidfagan - few questions to help me dig into this further:

Hi @umakrishnaswamy, please find answers to your questions below:

> How many files are there in the artifact and what’s the amount of data? Or does this error occur with artifacts of various sizes?

A folder that contains, 110 subfolders (each with about 2 files) + 1 file so around 221 files in total. I am looking to download a Flax checkpoint, I can provide access to the raw model files in my GCP bucket if necessary.

<img width="1147" alt="Screenshot 2023-09-20 at 08 32 49" src="https://github.com/wandb/wandb/assets/42982057/e44fbc1a-c24f-46b7-8e8b-3b26f27bf29f">


> Is this error being raised when downloading the artifact both from a run and from the API? Or one or the other?

I am encountering this error only when downloading it via the Python API. I haven't tried with the CLI as I want to automatically pull the latest model version based on a config file I pass to my run. 

Happy to provide any additional details that are required.

**Comment by umakrishnaswamy** [comment]
@peterdavidfagan - I have tried reproducing this issue via the core wandb SDK and wandb API on version 0.15.4 and our most up to date version, but have been unable to reproduce the issue thus far. Do you reach this same issue on our most up to date wandb version? Additionally, I recommend checking the compatibility between your wandb version and the Google Cloud storage library. 

In general, explicitly importing the Client class ensures that the correct class is used, regardless of any potential naming conflicts or differences in library versions, so this might be why you're seeing this behavior.

**Comment by umakrishnaswamy** [comment]
@peterdavidfagan Hi there, I wanted to follow up on this request. Please let us know if we can be of further assistance
