### ISSUE TITLE
[CLI] Error -  Cannot specify both target_size and target_fraction

### ISSUE THREAD

**Issue by ciaranby** [wandb/wandb#6326]
### Describe the bug

When running: wandb artifact cache cleanup 1GB
as per the documentation we get the following error:
ValueError: Cannot specify both target_size and target_fraction

Seems to be due to the following line:
https://github.com/wandb/wandb/blob/main/wandb/cli/cli.py#L2208

remove_temp should be set as a keyword argument. 

As we can see here remove_temp should not be set using a positional argument:
https://github.com/wandb/wandb/blob/main/wandb/sdk/artifacts/artifacts_cache.py#L67

```python
N/A
```

```shell
(automation-aiss-py3.11) ciaran@Ciarans-MacBook-Pro data_pipeline % wandb artifact cache cleanup
Usage: wandb artifact cache cleanup [OPTIONS] TARGET_SIZE
Try 'wandb artifact cache cleanup --help' for help.

Error: Missing argument 'TARGET_SIZE'.
(automation-aiss-py3.11) ciaran@Ciarans-MacBook-Pro data_pipeline % wandb artifact cache cleanup 0GB
Traceback (most recent call last):
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/bin/wandb", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/wandb/cli/cli.py", line 102, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/wandb/cli/cli.py", line 2203, in cleanup
    reclaimed_bytes = cache.cleanup(target_size, remove_temp)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/wandb/sdk/artifacts/artifacts_cache.py", line 95, in cleanup
    raise ValueError("Cannot specify both target_size and target_fraction")
ValueError: Cannot specify both target_size and target_fraction
(automation-aiss-py3.11) ciaran@Ciarans-MacBook-Pro data_pipeline % wandb artifact cache cleanup 0Gb
Traceback (most recent call last):
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/bin/wandb", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/wandb/cli/cli.py", line 102, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/wandb/cli/cli.py", line 2203, in cleanup
    reclaimed_bytes = cache.cleanup(target_size, remove_temp)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/wandb/sdk/artifacts/artifacts_cache.py", line 95, in cleanup
    raise ValueError("Cannot specify both target_size and target_fraction")
ValueError: Cannot specify both target_size and target_fraction
(automation-aiss-py3.11) ciaran@Ciarans-MacBook-Pro data_pipeline % wandb artifact cache cleanup 1Gb
Traceback (most recent call last):
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/bin/wandb", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/wandb/cli/cli.py", line 102, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/wandb/cli/cli.py", line 2203, in cleanup
    reclaimed_bytes = cache.cleanup(target_size, remove_temp)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/wandb/sdk/artifacts/artifacts_cache.py", line 95, in cleanup
    raise ValueError("Cannot specify both target_size and target_fraction")
ValueError: Cannot specify both target_size and target_fraction
(automation-aiss-py3.11) ciaran@Ciarans-MacBook-Pro data_pipeline % wandb artifact cache cleanup 1GB
Traceback (most recent call last):
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/bin/wandb", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/wandb/cli/cli.py", line 102, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/wandb/cli/cli.py", line 2203, in cleanup
    reclaimed_bytes = cache.cleanup(target_size, remove_temp)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/wandb/sdk/artifacts/artifacts_cache.py", line 95, in cleanup
    raise ValueError("Cannot specify both target_size and target_fraction")

```

### Environment

WandB version:
wandb, version 0.15.10

OS:
Mac OS ventura

Python version:
3.11.1

Versions of relevant libraries:
N/A

**Comment by sydholl** [comment]
Internal GitHub User commented: 
### Describe the bug


When running: wandb artifact cache cleanup 1GB
as per the documentation we get the following error:
ValueError: Cannot specify both target_size and target_fraction


Seems to be due to the following line:
https://github.com/wandb/wandb/blob/main/wandb/cli/cli.py#L2208

remove_temp should be set as a keyword argument. 

As we can see here remove_temp should not be set using a positional argument:
https://github.com/wandb/wandb/blob/main/wandb/sdk/artifacts/artifacts_cache.py#L67


```python
N/A
```


```shell
(automation-aiss-py3.11) ciaran@Ciarans-MacBook-Pro data_pipeline % wandb artifact cache cleanup
Usage: wandb artifact cache cleanup [OPTIONS] TARGET_SIZE
Try 'wandb artifact cache cleanup --help' for help.

Error: Missing argument 'TARGET_SIZE'.
(automation-aiss-py3.11) ciaran@Ciarans-MacBook-Pro data_pipeline % wandb artifact cache cleanup 0GB
Traceback (most recent call last):
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/bin/wandb", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/wandb/cli/cli.py", line 102, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/wandb/cli/cli.py", line 2203, in cleanup
    reclaimed_bytes = cache.cleanup(target_size, remove_temp)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/wandb/sdk/artifacts/artifacts_cache.py", line 95, in cleanup
    raise ValueError("Cannot specify both target_size and target_fraction")
ValueError: Cannot specify both target_size and target_fraction
(automation-aiss-py3.11) ciaran@Ciarans-MacBook-Pro data_pipeline % wandb artifact cache cleanup 0Gb
Traceback (most recent call last):
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/bin/wandb", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/wandb/cli/cli.py", line 102, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/wandb/cli/cli.py", line 2203, in cleanup
    reclaimed_bytes = cache.cleanup(target_size, remove_temp)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/wandb/sdk/artifacts/artifacts_cache.py", line 95, in cleanup
    raise ValueError("Cannot specify both target_size and target_fraction")
ValueError: Cannot specify both target_size and target_fraction
(automation-aiss-py3.11) ciaran@Ciarans-MacBook-Pro data_pipeline % wandb artifact cache cleanup 1Gb
Traceback (most recent call last):
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/bin/wandb", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/wandb/cli/cli.py", line 102, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/wandb/cli/cli.py", line 2203, in cleanup
    reclaimed_bytes = cache.cleanup(target_size, remove_temp)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/wandb/sdk/artifacts/artifacts_cache.py", line 95, in cleanup
    raise ValueError("Cannot specify both target_size and target_fraction")
ValueError: Cannot specify both target_size and target_fraction
(automation-aiss-py3.11) ciaran@Ciarans-MacBook-Pro data_pipeline % wandb artifact cache cleanup 1GB
Traceback (most recent call last):
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/bin/wandb", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/wandb/cli/cli.py", line 102, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/wandb/cli/cli.py", line 2203, in cleanup
    reclaimed_bytes = cache.cleanup(target_size, remove_temp)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ciaran/Library/Caches/pypoetry/virtualenvs/automation-aiss-tput_O6o-py3.11/lib/python3.11/site-packages/wandb/sdk/artifacts/artifacts_cache.py", line 95, in cleanup
    raise ValueError("Cannot specify both target_size and target_fraction")

```


### Additional Files

_No response_

### Environment

WandB version:
wandb, version 0.15.10

OS:
Mac OS ventura

Python version:
3.11.1

Versions of relevant libraries:
N/A

### Additional Context

_No response_

**Comment by ArtsiomWB** [comment]
Hi @ciaranby! Thank you for writing in! To double check, you are trying to run the `wandb artifact cache cleanup` command in your CLI in order to clean up some artifact cache. When you do run the command, you see an error on your side. Once you go inside of the codebase (thank you for looking into it), you see that `target_size: Optional[int] = None` is already automatically set to None and is  optional, but even with it being optional, it still asks you to specify it?

**Comment by ciaranby** [comment]
I see the erros hown above error when I run the command as follows:

`wandb artifact cache cleanup 1GB`

**Comment by ciaranby** [comment]
The issue is because [this line of code]( https://github.com/wandb/wandb/blob/main/wandb/cli/cli.py#L2208) is wrong:
```
reclaimed_bytes = cache.cleanup(target_size, remove_temp)

```

it should be:

```
    reclaimed_bytes = cache.cleanup(target_size, remove_temp=remove_temp)
```

or it could be:

```
    reclaimed_bytes = cache.cleanup(target_size, None, remove_temp)

```

**Comment by MBakirWB** [comment]
#6152

**Comment by yubin-ai** [comment]
I can confirm this error on wandb 0.16.5 and in wandb 0.16.6 it is gone.
