### ISSUE TITLE
[CLI]: Breaking changes when upgrading from 0.15.7 to 0.15.11

### ISSUE THREAD

**Issue by SimiPixel** [wandb/wandb#6380]
### Describe the bug

I have a run-file that executes just fine with 0.15.7 but gives the following error after having upgraded to 0.15.11

I upgraded using `pip install --upgrade wandb`

```shell
Traceback (most recent call last):
  File "/home/woody/iwb0/iwb0003h/.conda/envs/jax_bleeding_v2/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1143, in init
    config = {"lr": 3e-4, "batch_size": 32}
        ^^^^^^^^^^^^^^^^
  File "/home/woody/iwb0/iwb0003h/.conda/envs/jax_bleeding_v2/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 172, in setup
    if set(singleton_env.keys()) != set(os_env.keys()) or set(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/woody/iwb0/iwb0003h/.conda/envs/jax_bleeding_v2/lib/python3.11/site-packages/wandb/sdk/wandb_setup.py", line 327, in setup
    ret = _setup(settings=settings)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/woody/iwb0/iwb0003h/.conda/envs/jax_bleeding_v2/lib/python3.11/site-packages/wandb/sdk/wandb_setup.py", line 320, in _setup
    wl = _WandbSetup(settings=settings)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/woody/iwb0/iwb0003h/.conda/envs/jax_bleeding_v2/lib/python3.11/site-packages/wandb/sdk/wandb_setup.py", line 303, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/woody/iwb0/iwb0003h/.conda/envs/jax_bleeding_v2/lib/python3.11/site-packages/wandb/sdk/wandb_setup.py", line 114, in __init__
    self._setup()
  File "/home/woody/iwb0/iwb0003h/.conda/envs/jax_bleeding_v2/lib/python3.11/site-packages/wandb/sdk/wandb_setup.py", line 250, in _setup
    self._setup_manager()
  File "/home/woody/iwb0/iwb0003h/.conda/envs/jax_bleeding_v2/lib/python3.11/site-packages/wandb/sdk/wandb_setup.py", line 277, in _setup_manager
    self._manager = wandb_manager._Manager(settings=self._settings)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/woody/iwb0/iwb0003h/.conda/envs/jax_bleeding_v2/lib/python3.11/site-packages/wandb/sdk/wandb_manager.py", line 130, in __init__

  File "/home/woody/iwb0/iwb0003h/.conda/envs/jax_bleeding_v2/lib/python3.11/site-packages/wandb/sdk/service/service.py", line 16, in <module>
    from wandb import _minimum_nexus_version, _sentry, termlog
ImportError: cannot import name '_minimum_nexus_version' from 'wandb' (/home/woody/iwb0/iwb0003h/.conda/envs/jax_bleeding_v2/lib/python3.11/site-packages/wandb/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hpc/iwb0/iwb0003h/projects/argparse_S06_4Seg_3seg_correct.py", line 382, in <module>
    main()
  File "/home/hpc/iwb0/iwb0003h/projects/argparse_S06_4Seg_3seg_correct.py", line 347, in main
    wandb.init(project=args.project, name=args.name, config=config, tags=[args.tag])
  File "/home/woody/iwb0/iwb0003h/.conda/envs/jax_bleeding_v2/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1185, in init
    run = None
    ^^^^^^^^^^^
wandb.errors.Error: An unexpected error occurred
srun: error: a0125: task 0: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=849371.0
```

### Environment

WandB version: 0.15.11

OS: Almalinux 8.8

Python version: 3.11.4

Versions of relevant libraries:

**Comment by thanos-wandb** [comment]
Hi @SimiPixel thank you for reporting this issue. Could you please share with us the `debug.log` and `debug-internal.log` of the affected run (in `0.15.11`). These files are under your local folder `wandb/run-<date>_<time>-<run-id>/logs` in the same directory where you’re running your code. 

Additionally, could you please provide some more context, in what environment are you executing these runs? and does in fail in 0.15.11 for a simple code as follows:
```
run = wandb.init(project='test')
run.log({'metric': 1})
run.finish()
```

**Comment by thanos-wandb** [comment]
@SimiPixel we wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by thanos-wandb** [comment]
Hi @SimiPixel since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
