### ISSUE TITLE
[CLI]: bug using `load_report` with wandb API

### ISSUE THREAD

**Issue by minoring** [wandb/wandb#6388]
### Describe the bug

Hello, I ran into an error using load_report with the wandb API.
Putting an issue here cause I couldn't find anything related.

```python
import wandb

api = wandb.Api()
entity = "<my_entity>"
projecty = "<my_project>"
report_id = "<my_project_id>"

report = api.load_report(f"{entity}/{project}/reports/{report_id}")
```

```shell
Traceback (most recent call last):
  File "/home/<user>/Error_Recovery/error_recovery/error_recovery/scripts/wandb_to_csv.py", line 35, in <module>
    main()
  File "/home/<user>/Error_Recovery/error_recovery/error_recovery/scripts/wandb_to_csv.py", line 16, in main
    report = api.load_report(f"{entity}/{project}/reports/{report_id}")
  File "/home/<user>/miniconda3/envs/error/lib/python3.8/site-packages/wandb/apis/public.py", line 545, in load_report
    return wandb.apis.reports.Report.from_url(path)
AttributeError: module 'wandb.apis' has no attribute 'reports'
```

### Environment

WandB version: 0.15.11

OS: Ubuntu 20.04

Python version: 3.8

Versions of relevant libraries:

**Comment by nate-wandb** [comment]
Hi @minoring, I wanted to follow up and see if you had a chance to checkout the above Colab and if this worked as a solution?
