### ISSUE TITLE
[Q] Weird error code when syncing offline runs

### ISSUE THREAD

**Issue by tristanengst** [wandb/wandb#6402]
I'm trying to sync an offline run and getting the following error code:
```
wandb: ERROR Error while calling W&B API: invalid parameters: 64 limit exceeded for JobType (<Response [400]>)
```
What does it mean and how can I fix it so offline syncing works properly? Currently the run doesn't display on the WandB website, so I can't view results and it's a big issue.

Thanks!

Some more information—when I do `cat /tmp/debug-cli.tristanengst.log`, I get:
```
2023-09-27 18:38:31 INFO Running runs: []
2023-09-27 18:38:31 INFO Agent received command: run
2023-09-27 18:38:31 INFO Agent starting run with config:
        arch: conv
        bs: 64
        code_bs: 1000
        conv_embed_dim: 256
        data_tr: cifar10
        data_val: cifar10
        debug_one_wd: 1
        epochs: 32
        eval_iter: 4
        gpus: 0
        ipe: 20
        lrs: 0 5e-5
        noise_std: 0.2
        suffix: Sept27-ConvTuning-Old
        wandb: online
        wd: 1e-05
2023-09-27 18:38:31 INFO About to run command: /usr/bin/env python TrainSSL.py --arch=conv --bs=64 --code_bs=1000 --conv_embed_dim=256 --data_tr=cifar10 --data_val=cifar10 --debug_one_wd=1 --epochs=32 --eval_iter=4 --gpus=0 --ipe=20 "--lrs=0 5e-5" --noise_std=0.2 --suffix=Sept27-ConvTuning-Old --wandb=online --wd=1e-05
2023-10-02 18:22:43 INFO open for scan: /home/tristanengst/Development/IMLE-SSL/wandb/offline-run-20231002_181204-i3zlwjfk/run-i3zlwjfk.wandb
2023-10-02 18:22:43 ERROR 400 response executing GraphQL.
2023-10-02 18:22:43 ERROR {"errors":[{"message":"invalid parameters: 64 limit exceeded for JobType","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-10-02 18:22:43 ERROR invalid parameters: 64 limit exceeded for JobType (Error 400: Bad Request)
Traceback (most recent call last):
  File "/home/tristanengst/miniconda3/envs/py311IMLESSL/lib/python3.11/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tristanengst/miniconda3/envs/py311IMLESSL/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 1999, in upsert_run
    response = self.gql(
               ^^^^^^^^^
  File "/home/tristanengst/miniconda3/envs/py311IMLESSL/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 330, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "/home/tristanengst/miniconda3/envs/py311IMLESSL/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tristanengst/miniconda3/envs/py311IMLESSL/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 358, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tristanengst/miniconda3/envs/py311IMLESSL/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tristanengst/miniconda3/envs/py311IMLESSL/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tristanengst/miniconda3/envs/py311IMLESSL/lib/python3.11/site-packages/wandb/sdk/lib/gql_request.py", line 56, in execute
    request.raise_for_status()
  File "/home/tristanengst/miniconda3/envs/py311IMLESSL/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tristanengst/miniconda3/envs/py311IMLESSL/lib/python3.11/site-packages/wandb/sdk/internal/sender.py", line 974, in send_run
    self._init_run(run, config_value_dict)
  File "/home/tristanengst/miniconda3/envs/py311IMLESSL/lib/python3.11/site-packages/wandb/sdk/internal/sender.py", line 1012, in _init_run
    server_run, inserted, server_messages = self._api.upsert_run(
                                            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tristanengst/miniconda3/envs/py311IMLESSL/lib/python3.11/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: invalid parameters: 64 limit exceeded for JobType (Error 400: Bad Request)
2023-10-02 18:22:43 INFO saving file wandb-metadata.json with policy now
2023-10-02 18:22:43 INFO saving file code/* with policy now
2023-10-02 18:22:43 INFO saving file media/images/images/val_0_20f5f75632f77e06d4a7.png with policy now
2023-10-02 18:22:43 INFO saving file media/images/images/tr_0_a137e38691aab7cb4a67.png with policy now
2023-10-02 18:22:43 INFO saving file media/images/images/tr_new_masks_0_c8d25f60c572fa6f2255.png with policy now
2023-10-02 18:22:43 INFO saving file media/images/images/val_150_4a3ed90deed76030f8b1.png with policy now
2023-10-02 18:22:43 INFO saving file media/images/images/tr_150_6209b97279066c8ba952.png with policy now
2023-10-02 18:22:43 INFO saving file media/images/images/tr_new_masks_150_db44275faff9405555a4.png with policy now
2023-10-02 18:22:43 INFO saving file wandb-summary.json with policy end
2023-10-02 18:22:43 INFO handling exit code: 255
2023-10-02 18:22:43 INFO handling runtime: 451
2023-10-02 18:22:43 INFO saving file wandb-summary.json with policy end
2023-10-02 18:22:43 INFO send defer
2023-10-02 18:22:43 INFO handle sender defer: 0
2023-10-02 18:22:43 INFO send defer: 1
2023-10-02 18:22:43 INFO handle sender defer: 1
2023-10-02 18:22:43 INFO send defer: 2
2023-10-02 18:22:43 INFO handle sender defer: 2
2023-10-02 18:22:43 INFO send defer: 3
2023-10-02 18:22:43 INFO handle sender defer: 3
2023-10-02 18:22:43 INFO send defer: 4
2023-10-02 18:22:43 INFO handle sender defer: 4
2023-10-02 18:22:43 INFO send defer: 5
2023-10-02 18:22:43 INFO handle sender defer: 5
2023-10-02 18:22:43 INFO send defer: 6
2023-10-02 18:22:43 INFO handle sender defer: 6
2023-10-02 18:22:43 INFO send defer: 7
2023-10-02 18:22:43 INFO handle sender defer: 7
2023-10-02 18:22:43 INFO send defer: 8
2023-10-02 18:22:43 INFO handle sender defer: 8
2023-10-02 18:22:43 INFO Attempting to build job artifact
2023-10-02 18:22:43 INFO is repo sourced job
2023-10-02 18:22:43 INFO adding wandb-job metadata file
2023-10-02 18:22:43 INFO send defer: 9
2023-10-02 18:22:43 INFO handle sender defer: 9
2023-10-02 18:22:43 INFO send defer: 10
2023-10-02 18:22:43 INFO handle sender defer: 10
2023-10-02 18:22:43 INFO send defer: 11
2023-10-02 18:22:43 INFO handle sender defer: 11
2023-10-02 18:22:43 INFO send defer: 12
2023-10-02 18:22:43 INFO handle sender defer: 12
2023-10-02 18:22:43 INFO send defer: 13
2023-10-02 18:22:43 INFO handle sender defer: 13
2023-10-02 18:22:43 INFO send defer: 14
2023-10-02 18:22:43 INFO handle sender defer: 14
2023-10-02 18:22:43 INFO shutting down sender
2023-10-03 05:37:36 INFO open for scan: /home/tristanengst/Development/IMLE-SSL/wandb/offline-run-20231003_053428-sva44zb8/run-sva44zb8.wandb
2023-10-03 05:37:36 ERROR 400 response executing GraphQL.
2023-10-03 05:37:36 ERROR {"errors":[{"message":"invalid parameters: 64 limit exceeded for JobType","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-10-03 05:37:36 ERROR invalid parameters: 64 limit exceeded for JobType (Error 400: Bad Request)
Traceback (most recent call last):
  File "/home/tristanengst/miniconda3/envs/py311IMLESSL/lib/python3.11/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tristanengst/miniconda3/envs/py311IMLESSL/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 1999, in upsert_run
    response = self.gql(
               ^^^^^^^^^
  File "/home/tristanengst/miniconda3/envs/py311IMLESSL/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 330, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "/home/tristanengst/miniconda3/envs/py311IMLESSL/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tristanengst/miniconda3/envs/py311IMLESSL/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 358, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tristanengst/miniconda3/envs/py311IMLESSL/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tristanengst/miniconda3/envs/py311IMLESSL/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tristanengst/miniconda3/envs/py311IMLESSL/lib/python3.11/site-packages/wandb/sdk/lib/gql_request.py", line 56, in execute
    request.raise_for_status()
  File "/home/tristanengst/miniconda3/envs/py311IMLESSL/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tristanengst/miniconda3/envs/py311IMLESSL/lib/python3.11/site-packages/wandb/sdk/internal/sender.py", line 974, in send_run
    self._init_run(run, config_value_dict)
  File "/home/tristanengst/miniconda3/envs/py311IMLESSL/lib/python3.11/site-packages/wandb/sdk/internal/sender.py", line 1012, in _init_run
    server_run, inserted, server_messages = self._api.upsert_run(
                                            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tristanengst/miniconda3/envs/py311IMLESSL/lib/python3.11/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: invalid parameters: 64 limit exceeded for JobType (Error 400: Bad Request)
2023-10-03 05:37:36 INFO saving file wandb-metadata.json with policy now
2023-10-03 05:37:36 INFO saving file code/* with policy now
2023-10-03 05:37:36 INFO saving file media/images/images/val_0_20f5f75632f77e06d4a7.png with policy now
2023-10-03 05:37:36 INFO saving file media/images/images/tr_0_a137e38691aab7cb4a67.png with policy now
2023-10-03 05:37:36 INFO saving file media/images/images/tr_new_masks_0_c8d25f60c572fa6f2255.png with policy now
2023-10-03 05:37:36 INFO saving file wandb-summary.json with policy end
2023-10-03 05:37:36 INFO handling exit code: 255
2023-10-03 05:37:36 INFO handling runtime: 176
2023-10-03 05:37:36 INFO saving file wandb-summary.json with policy end
2023-10-03 05:37:36 INFO send defer
2023-10-03 05:37:36 INFO handle sender defer: 0
2023-10-03 05:37:36 INFO send defer: 1
2023-10-03 05:37:36 INFO handle sender defer: 1
2023-10-03 05:37:36 INFO send defer: 2
2023-10-03 05:37:36 INFO handle sender defer: 2
2023-10-03 05:37:36 INFO send defer: 3
2023-10-03 05:37:36 INFO handle sender defer: 3
2023-10-03 05:37:36 INFO send defer: 4
2023-10-03 05:37:36 INFO handle sender defer: 4
2023-10-03 05:37:36 INFO send defer: 5
2023-10-03 05:37:36 INFO handle sender defer: 5
2023-10-03 05:37:36 INFO send defer: 6
2023-10-03 05:37:36 INFO handle sender defer: 6
2023-10-03 05:37:36 INFO send defer: 7
2023-10-03 05:37:36 INFO handle sender defer: 7
2023-10-03 05:37:36 INFO send defer: 8
2023-10-03 05:37:36 INFO handle sender defer: 8
2023-10-03 05:37:36 INFO Attempting to build job artifact
2023-10-03 05:37:36 INFO is repo sourced job
2023-10-03 05:37:36 INFO adding wandb-job metadata file
2023-10-03 05:37:36 INFO send defer: 9
2023-10-03 05:37:36 INFO handle sender defer: 9
2023-10-03 05:37:36 INFO send defer: 10
2023-10-03 05:37:36 INFO handle sender defer: 10
2023-10-03 05:37:36 INFO send defer: 11
2023-10-03 05:37:36 INFO handle sender defer: 11
2023-10-03 05:37:36 INFO send defer: 12
2023-10-03 05:37:36 INFO handle sender defer: 12
2023-10-03 05:37:36 INFO send defer: 13
2023-10-03 05:37:36 INFO handle sender defer: 13
2023-10-03 05:37:36 INFO send defer: 14
2023-10-03 05:37:36 INFO handle sender defer: 14
2023-10-03 05:37:36 INFO shutting down sender
```

**Comment by umakrishnaswamy** [comment]
Hey @tristanengst - thank you for surfacing this. We have a hard 64 character restriction on run job_type strings which is why you are running into this error; however, this doesn't seem to be enforced in offline mode - I will definitely make a bug report about this and update you with progress that arises. 

As for syncing your current runs - I'm looking to see if there's a way we can do that and will update you if I find a workaround. Otherwise, I recommend re-running your script with a job_type string less than 64 characters - so sorry for this inconvenience!

**Comment by tristanengst** [comment]
What does `job_string` actually refer to? Is it the name of the run (the `name` keyword argument to `wandb.init()`)—it's the only thing that could've been especially long, although I'd had no trouble with roughly similar lengths in both online and offline mode before.

**Comment by umakrishnaswamy** [comment]
@tristanengst - Would it be possible to provide an example code snippet of your `wandb.init()` call and the arguments inside it? Or if you have a value set for the [environment variable](https://docs.wandb.ai/guides/track/environment-variables#optional-environment-variables) `WANDB_JOB_TYPE` ?

**Comment by tristanengst** [comment]
Apologies, there was a bug in my init function—`job_type` should have been `None`, but was accidentally set to the long string I mentioned earlier as the `name` keyword argument. I confirmed that with online mode, calling `wandb.init()` with the issue fails immediately, so it is good enforce this in offline mode too to avoid confusion. There's no need to figure out how to sync to the affected runs as the problem can be easily circumvented going forward by not having the bug.

**Comment by umakrishnaswamy** [comment]
@tristanengst I'll update this thread once progress is made on the fix. Glad to hear you were able to find the bug in your init function!

**Comment by umakrishnaswamy** [comment]
hey @tristanengst - just merged a fix for being able to override the job type you may have set in your script, since we don't enforce the 64 character limit in offline runs. this will be available in our next SDK release, and thanks again for flagging!
