### ISSUE TITLE
[CLI]: Specifying `wandb.init(config=FILE)` whilst having `config-defaults.yaml` in the same directory raises exception

### ISSUE THREAD

**Issue by iwishiwasaneagle** [wandb/wandb#6496]
### Describe the bug

Running `wandb.init(config=FILE)` whilst having `config-defaults.yaml` in the same directory throws `wandb.sdk.lib.config_util.ConfigError: Attempted to change value of key`

```python
iimport wandb

print(f"{wandb.__version__=}")

with open("dev-defaults.yaml", "w") as f:
    f.writelines(
        """
number_of_waypoints:
  desc:
  value: 16
        """
    )

with open("config-defaults.yaml", "w") as f:
    f.writelines(
        """
number_of_waypoints:
  desc:
  value: 64
        """
    )

run = wandb.init(config="dev-defaults.yaml", mode="offline")


```

```shell
wandb.__version__='0.15.12'
Problem at: /tmp/test.py 23 <module>
wandb: ERROR Attempted to change value of key "number_of_waypoints" from 64 to 16
wandb: ERROR If you really want to do this, pass allow_val_change=True to config.update()
Traceback (most recent call last):
  File "/tmp/test.py", line 23, in <module>
    run = wandb.init(
  File "/home/jhewers/.conda/envs/jpathgen/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1189, in init
    raise e
  File "/home/jhewers/.conda/envs/jpathgen/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/home/jhewers/.conda/envs/jpathgen/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 633, in init
    run = Run(
  File "/home/jhewers/.conda/envs/jpathgen/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 565, in __init__
    self._init(
  File "/home/jhewers/.conda/envs/jpathgen/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 683, in _init
    self._config._update(config, ignore_locked=True)
  File "/home/jhewers/.conda/envs/jpathgen/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 177, in _update
    sanitized = self._sanitize_dict(
  File "/home/jhewers/.conda/envs/jpathgen/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 237, in _sanitize_dict
    k, v = self._sanitize(k, v, allow_val_change)
  File "/home/jhewers/.conda/envs/jpathgen/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 258, in _sanitize
    raise config_util.ConfigError(
wandb.sdk.lib.config_util.ConfigError: Attempted to change value of key "number_of_waypoints" from 64 to 16
If you really want to do this, pass allow_val_change=True to config.update()
```

### Environment

WandB version: 0.15.12

OS: Linux HOSTNAME 5.15.131-1-MANJARO #1 SMP PREEMPT Thu Sep 7 11:05:18 UTC 2023 x86_64 GNU/Linux

Python version: 3.10.12

Versions of relevant libraries:

**Comment by ArtsiomWB** [comment]
Hi @iwishiwasaneagle! Thank you for reporting this concern to us. I've looked around and it does look like it is intentional. Wandb runs automatically pick up `config-defaults.yaml` for their config runs if it is located in the same directory as the script you are currently running. We do have this documented in [docs](https://docs.wandb.ai/guides/track/config#file-based-configs) but it definitely isn't the cleanest, and is a bit confusing.

**Comment by iwishiwasaneagle** [comment]
Hmmm I don't agree that this is documented behaviour. From the wording it makes it sound like default-configs.yaml doesn't need to be specified if it exists.

Nonetheless, this is unintuitive behaviour in my opinion. Having the config Param option for wandh.init should supersede the detaults, not the other way around.

-------- Original Message --------

**Comment by ArtsiomWB** [comment]
Thank you for the feedback! I will let our docs team know and we can fix it up and make it more clear!

**Comment by sydholl** [comment]
Artsiom Skarakhod commented: 
Hi @iwishiwasaneagle! Thank you for reporting this concern to us. I've looked around and it does look like it is intentional. Wandb runs automatically pick up `config-defaults.yaml` for their config runs if it is located in the same directory as the script you are currently running. We do have this documented in docs but it definitely isn't the cleanest, and is a bit confusing.

**Comment by sydholl** [comment]
WandB Internal User commented: 
ArtsiomWB commented: 
Thank you for the feedback! I will let our docs team know and we can fix it up and make it more clear!

**Comment by iwishiwasaneagle** [comment]
@sydholl I don't doubt that it's intentional, I just don't think it's great UX. If I explicitly specify a config file, I think I'd want it to take precedence over anything else in the repo. With the current behavior, if `config-defaults.yaml` has keys `A, B` and  `my-amazing-config.yaml` has keys `B, C`, I'd have to update `wandb.config` to include the `B` that I've specified. 

Essentially, it currently is

```
my-amazing-config.yaml -> config-defaults.yaml
```

when it should be (in my opinion)

```
config-defaults.yaml -> my-amazing-config.yaml
```

**Comment by sydholl** [comment]
WandB Internal User commented: 
iwishiwasaneagle commented: 
@sydholl I don't doubt that it's intentional, I just don't think it's great UX. If I explicitly specify a config file, I think I'd want it to take precedence over anything else in the repo. With the current behavior, if `config-defaults.yaml` has keys `A, B` and  `my-amazing-config.yaml` has keys `B, C`, I'd have to update `wandb.config` to include the `B` that I've specified. 

Essentially, it currently is

```
my-amazing-config.yaml -> config-defaults.yaml
```

when it should be (in my opinion)

```
config-defaults.yaml -> my-amazing-config.yaml
```

**Comment by sydholl** [comment]
WandB Internal User commented: 
sydholl commented: 
WandB Internal User commented: 
iwishiwasaneagle commented: 
@sydholl I don't doubt that it's intentional, I just don't think it's great UX. If I explicitly specify a config file, I think I'd want it to take precedence over anything else in the repo. With the current behavior, if `config-defaults.yaml` has keys `A, B` and  `my-amazing-config.yaml` has keys `B, C`, I'd have to update `wandb.config` to include the `B` that I've specified. 

Essentially, it currently is

```
my-amazing-config.yaml -> config-defaults.yaml
```

when it should be (in my opinion)

```
config-defaults.yaml -> my-amazing-config.yaml
```

**Comment by sydholl** [comment]
WandB Internal User commented: 
sydholl commented: 
WandB Internal User commented: 
iwishiwasaneagle commented: 
@sydholl I don't doubt that it's intentional, I just don't think it's great UX. If I explicitly specify a config file, I think I'd want it to take precedence over anything else in the repo. With the current behavior, if `config-defaults.yaml` has keys `A, B` and  `my-amazing-config.yaml` has keys `B, C`, I'd have to update `wandb.config` to include the `B` that I've specified. 

Essentially, it currently is

```
my-amazing-config.yaml -> config-defaults.yaml
```

when it should be (in my opinion)

```
config-defaults.yaml -> my-amazing-config.yaml
```

**Comment by sydholl** [comment]
WandB Internal User commented: 
sydholl commented: 
WandB Internal User commented: 
iwishiwasaneagle commented: 
@sydholl I don't doubt that it's intentional, I just don't think it's great UX. If I explicitly specify a config file, I think I'd want it to take precedence over anything else in the repo. With the current behavior, if `config-defaults.yaml` has keys `A, B` and  `my-amazing-config.yaml` has keys `B, C`, I'd have to update `wandb.config` to include the `B` that I've specified. 

Essentially, it currently is

```
my-amazing-config.yaml -> config-defaults.yaml
```

when it should be (in my opinion)

```
config-defaults.yaml -> my-amazing-config.yaml
```

**Comment by ArtsiomWB** [comment]
I have submitted this feedback to our engineering team as well! Thank you for your time and patience!

**Comment by sydholl** [comment]
WandB Internal User commented: 
ArtsiomWB commented: 
I have submitted this feedback to our engineering team as well! Thank you for your time and patience!
