### ISSUE TITLE
[CLI]: Cannot log data with W&B in PyTorch & Kubernetes; UID not found

### ISSUE THREAD

**Issue by phrasenmaeher** [wandb/wandb#6520]
### Describe the bug

I am running code by Nvidia (https://github.com/NVlabs/FourCastNet/blob/93360c1720a9f97aabf970689f21c9fad8737788/train.py#L594) 
on my compute infrastructure. I am using Kubernetes to run the code on a Nvidia DGX pod.

When trying to track my experiments with `wandb`, it fails with the following error:

```shell
wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin
Problem at: [removed]/fourcastnet/train.py 88 __init__
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 623, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_manager.py", line 197, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/service/service_sock.py", line 34, in _svc_inform_init
    inform_init.settings.CopyFrom(settings.to_proto())
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 1538, in to_proto
    v = getattr(self, k)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 1433, in __getattribute__
    return item.value
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 520, in value
    _value = h(_value)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 848, in <lambda>
    project_url={"hook": lambda _: self._project_url(), "auto_hook": True},
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 1264, in _project_url
    query = self._get_url_query_string()
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 1245, in _get_url_query_string
    if Api().settings().get("anonymous") != "true":
  File "/opt/conda/lib/python3.8/site-packages/wandb/apis/internal.py", line 98, in settings
    return self.api.settings(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/wandb/apis/internal.py", line 39, in api
    self._api = InternalApi(*self._api_args, **self._api_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 245, in __init__
    self._settings = Settings(
  File "/opt/conda/lib/python3.8/site-packages/wandb/old/settings.py", line 27, in __init__
    self._global_settings.read([Settings._global_path()])
  File "/opt/conda/lib/python3.8/site-packages/wandb/old/settings.py", line 130, in _global_path
    username = getpass.getuser()
  File "/opt/conda/lib/python3.8/getpass.py", line 169, in getuser
    return pwd.getpwuid(os.getuid())[0]
KeyError: 'getpwuid(): uid not found: 1356'
wandb: ERROR An unexpected error occurred
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 623, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_manager.py", line 197, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/service/service_sock.py", line 34, in _svc_inform_init
    inform_init.settings.CopyFrom(settings.to_proto())
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 1538, in to_proto
    v = getattr(self, k)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 1433, in __getattribute__
    return item.value
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 520, in value
    _value = h(_value)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 848, in <lambda>
    project_url={"hook": lambda _: self._project_url(), "auto_hook": True},
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 1264, in _project_url
    query = self._get_url_query_string()
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 1245, in _get_url_query_string
    if Api().settings().get("anonymous") != "true":
  File "/opt/conda/lib/python3.8/site-packages/wandb/apis/internal.py", line 98, in settings
    return self.api.settings(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/wandb/apis/internal.py", line 39, in api
    self._api = InternalApi(*self._api_args, **self._api_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 245, in __init__
    self._settings = Settings(
  File "/opt/conda/lib/python3.8/site-packages/wandb/old/settings.py", line 27, in __init__
    self._global_settings.read([Settings._global_path()])
  File "/opt/conda/lib/python3.8/site-packages/wandb/old/settings.py", line 130, in _global_path
    username = getpass.getuser()
  File "/opt/conda/lib/python3.8/getpass.py", line 169, in getuser
    return pwd.getpwuid(os.getuid())[0]
KeyError: 'getpwuid(): uid not found: 1356'
```

The uid that is being searched for is the UID I have on my computing system.
This is the snippet I use for running the code:

```yaml
          command: 
            #- "torchrun"
            #- "--standalone"
            #- "--nproc_per_node=4" # 4 GPUs per node, adapt if neccessary
            - "python"
            - "-u"
            - "[removed]/train.py"
          args:
```
regardless of whether I am using torchrun or not, logging with w&b fails with the error above.
Any ideas on injecting my UID here?

### Environment

WandB version: most recent

OS: MacOS X, Kubernete

Python version: 3.8

Versions of relevant libraries: pytorch 1.11

**Comment by rsanandres-wandb** [comment]
Hello!

The root cause seems to be Python struggling to match the UID as seen here:
```
  File "/opt/conda/lib/python3.8/getpass.py", line 169, in getuser
    return pwd.getpwuid(os.getuid())[0]
```

Could you check your UID of the machine to see if it matches up to 1356 just to make sure?

**Comment by sydholl** [comment]
Raphael San Andres commented: 
Hello!

The root cause seems to be Python struggling to match the UID as seen here:


    File "/opt/conda/lib/python3.8/getpass.py", line 169, in getuser return pwd.getpwuid(os.getuid())[0]


Could you check your UID of the machine to see if it matches up to 1356 just to make sure?

**Comment by phrasenmaeher** [comment]
Hi, I was able to fix the problem by pointing `w&b` to a memory-disk.
I added the following to my job definition:

```
          volumeMounts:
            - mountPath: "/.config/wandb"
              name: wandb
     [...]
      volumes:
        - name: wandb
          emptyDir: { }
```
With this fix, I was able to solve the problem. Strange though that earlier I was able to point `w&b` to a host's directory without problem (by setting `WANDB_CONFIG_DIR` and `WANDB_DIR` )
