### ISSUE TITLE
Wandb error on importing callback function from ultralytics integration 

### ISSUE THREAD

**Issue by lowisluo** [wandb/wandb#6566]
Hi,
Encountered Error on importing Ultralytics integration callback

### Version:
- Wandb: 0.15.12
- Ultralytics: 8.0.203

### Code:
  ```python
  from wandb.integration.ultralytics import add_wandb_callback
  ```

### Error:
```bash
Traceback (most recent call last):
  File "/media/ssd1/anaconda3/envs/py39_rbbox/lib/python3.9/site-packages/wandb/integration/ultralytics/callback.py", line 45, in <module>
    from ultralytics.yolo.utils import RANK, __version__
ModuleNotFoundError: No module named 'ultralytics.yolo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/media/ssd1/anaconda3/envs/py39_rbbox/lib/python3.9/site-packages/wandb/integration/ultralytics/__init__.py", line 7, in <module>
    from wandb.integration.ultralytics.callback import add_wandb_callback
  File "/media/ssd1/anaconda3/envs/py39_rbbox/lib/python3.9/site-packages/wandb/integration/ultralytics/callback.py", line 64, in <module>
    wandb.error(e)
AttributeError: module 'wandb' has no attribute 'error'
```

### Quick Fix
Found out Ultralytics have re-structured the utils, and removed `yolo`,
quick fixes by updating following line:
https://github.com/wandb/wandb/blob/c6b7a82a152e8efee84cb7f0887532c482ccd6c1/wandb/integration/ultralytics/callback.py#L45
to
```python
from ultralytics.utils import RANK, __version__ 
```

**Comment by umakrishnaswamy** [comment]
@lowisluo - thank you so much for surfacing this - will flag this with our integrations team and let you know when any updates are made on our end. thank you!

**Comment by Tarislada** [comment]
Experienced same issues; came up with the same solution and worked just the same :)
