### ISSUE TITLE
[CLI]: wandb sync report error: Conflict for url: https://api.wandb.ai/graphql and very slow

### ISSUE THREAD

**Issue by wayne155** [wandb/wandb#6593]
### Describe the bug

1. wandb sync is extremely slow, it takes minutes to  sync a single run.
2. wandb sync --sync-all will report a HTTP 409 error: Conflict for url .

```python

```

```shell
❯ wandb sync --sync-all
Find logs at: /notebooks/pytorch_timeseries/wandb/debug-cli.root.log
wandb: ERROR Error while calling W&B API: run g_ai_lab/BiSTGNN/fqli6k79 was previously created and deleted; try a new run name (<Response [409]>)
wandb: ERROR Error while calling W&B API: run g_ai_lab/BiSTGNN/fqli6k79 was previously created and deleted; try a new run name (<Response [409]>)
wandb: ERROR Error while calling W&B API: run g_ai_lab/BiSTGNN/fqli6k79 was previously created and deleted; try a new run name (<Response [409]>)
wandb: ERROR Error while calling W&B API: run g_ai_lab/BiSTGNN/fqli6k79 was previously created and deleted; try a new run name (<Response [409]>)
wandb: ERROR Error while calling W&B API: run g_ai_lab/BiSTGNN/fqli6k79 was previously created and deleted; try a new run name (<Response [409]>)
wandb: ERROR Error while calling W&B API: run g_ai_lab/BiSTGNN/fqli6k79 was previously created and deleted; try a new run name (<Response [409]>)



wandb: ERROR Error while calling W&B API: run g_ai_lab/BiSTGNN/fqli6k79 was previously created and deleted; try a new run name (<Response [409]>)
wandb: ERROR Error while calling W&B API: run g_ai_lab/BiSTGNN/fqli6k79 was previously created and deleted; try a new run name (<Response [409]>)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.7/site-packages/wandb/apis/normalize.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 1478, in upsert_run
    **kwargs,
  File "/root/anaconda3/lib/python3.7/site-packages/wandb/sdk/lib/retry.py", line 113, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 213, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/root/anaconda3/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/root/anaconda3/lib/python3.7/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/root/anaconda3/lib/python3.7/site-packages/wandb/sync/sync.py", line 266, in run
    sm.send(pb)
  File "/root/anaconda3/lib/python3.7/site-packages/wandb/sdk/internal/sender.py", line 305, in send
    send_handler(record)
  File "/root/anaconda3/lib/python3.7/site-packages/wandb/sdk/internal/sender.py", line 797, in send_run
    self._init_run(run, config_value_dict)
  File "/root/anaconda3/lib/python3.7/site-packages/wandb/sdk/internal/sender.py", line 837, in _init_run
    commit=run.git.commit or None,
  File "/root/anaconda3/lib/python3.7/site-packages/wandb/apis/normalize.py", line 28, in wrapper
    raise CommError(err.response, err)
wandb.errors.CommError: <Response [409]>
```

here's some error message appears in the debug-cli.root.log file:

```
2023-11-11 05:46:26 ERROR 409 response executing GraphQL.
2023-11-11 05:46:26 ERROR {"errors":[{"message":"run g_ai_lab/BiSTGNN/fqli6k79 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-11-11 05:46:28 ERROR 409 response executing GraphQL.
2023-11-11 05:46:28 ERROR {"errors":[{"message":"run g_ai_lab/BiSTGNN/fqli6k79 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-11-11 05:46:30 ERROR 409 response executing GraphQL.
2023-11-11 05:46:30 ERROR {"errors":[{"message":"run g_ai_lab/BiSTGNN/fqli6k79 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-11-11 05:46:30 ERROR Retry attempt failed:
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.7/site-packages/wandb/sdk/lib/retry.py", line 113, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 213, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/root/anaconda3/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/root/anaconda3/lib/python3.7/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2023-11-11 05:46:35 ERROR 409 response executing GraphQL.
2023-11-11 05:46:35 ERROR {"errors":[{"message":"run g_ai_lab/BiSTGNN/fqli6k79 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-11-11 05:46:43 ERROR 409 response executing GraphQL.
2023-11-11 05:46:43 ERROR {"errors":[{"message":"run g_ai_lab/BiSTGNN/fqli6k79 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-11-11 05:47:03 ERROR 409 response executing GraphQL.
2023-11-11 05:47:03 ERROR {"errors":[{"message":"run g_ai_lab/BiSTGNN/fqli6k79 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
```

seems this issue also happens in wandb online mode training stage, I have to use offline mode to avoid this, but sync does not work because this problem.

### Environment

WandB version:
0.16.0
OS:
Linux Ubuntu 20.04
Python version:
3.8.16
Versions of relevant libraries:

**Comment by JoanaMarieL** [comment]
Hello @wayne155 ,

Apologies for experiencing the slowness. For this concern, we would like to ask some details for the following: 

-if this is an online synch or an offline one?
-snippet of the code you are using
-tell us more on the process you did for this case(screen recording might help describe it)
-attach the debug.log and debug-internal.log. These files are under your local folder wandb/run-<date>_<time>-<run-id>/logs in the same directory where you’re running your code.

Thank you.

**Comment by JoanaMarieL** [comment]
Hi @wayne155 

We are investigating options to modify this behavior and will get back to you next week after the holiday break.

**Comment by AlessioQuercia** [comment]
Any news? 

It would be nice to have a flag to decide how to handle previously deleted runs. Options could be:
- default: do nothing
- skip: skip the deleted run
- delete: delete the local copy of the deleted run
