### ISSUE TITLE
unable to set up wandb locally

### ISSUE THREAD

**Issue by roaa108** [wandb/wandb#6643]
I have installed docker and python as required and running these commands from jupyter notebook with:

Python 3.9.18
wandb, version 0.16.0
Docker version 24.0.6

but the server start command `!wandb server start` throw this error : 
Command '['docker', 'inspect', 'wandb/local', '--format', '{{json .RepoDigests}}']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "C:\Users\roaa_mohamed\AppData\Local\anaconda3\envs\GMM\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\roaa_mohamed\AppData\Local\anaconda3\envs\GMM\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\roaa_mohamed\AppData\Local\anaconda3\envs\GMM\Scripts\wandb.exe\__main__.py", line 7, in <module>
  File "C:\Users\roaa_mohamed\AppData\Local\anaconda3\envs\GMM\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\roaa_mohamed\AppData\Local\anaconda3\envs\GMM\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\roaa_mohamed\AppData\Local\anaconda3\envs\GMM\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\roaa_mohamed\AppData\Local\anaconda3\envs\GMM\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\roaa_mohamed\AppData\Local\anaconda3\envs\GMM\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\roaa_mohamed\AppData\Local\anaconda3\envs\GMM\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\roaa_mohamed\AppData\Local\anaconda3\envs\GMM\lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\roaa_mohamed\AppData\Local\anaconda3\envs\GMM\lib\site-packages\wandb\cli\cli.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\roaa_mohamed\AppData\Local\anaconda3\envs\GMM\lib\site-packages\wandb\cli\cli.py", line 1989, in start
    local_image_sha = wandb.docker.image_id("wandb/local").split("wandb/local")[-1]
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by Carlo-Argel** [comment]
Hi @roaa108 ,

Thank you for reaching out for support. I'll be happy to assist you with this. I'll look into this and get back with updates. 

Regards,
Carlo Argel

**Comment by MBakirWB** [comment]
Hi @roaa108 , happy to help. This error occurs when a user does not not have an internet connection when starting up their wandb server using `wandb server start` 

Deeper explanation
- If you notice [here](https://github.com/wandb/wandb/blob/2f0ad645f55b5edf00b249f82d5bccd773316e97/wandb/cli/cli.py#L1680), this is we are getting the local hash for the docker image.
- Then on [this line](https://github.com/wandb/wandb/blob/2f0ad645f55b5edf00b249f82d5bccd773316e97/wandb/cli/cli.py#L1681), we are trying to get the SHA for the latest docker image on docker hub
- [On this line](https://github.com/wandb/wandb/blob/2f0ad645f55b5edf00b249f82d5bccd773316e97/wandb/cli/cli.py#L1684), we check if the local image SHA and the remote image SHA are the same. It's to make sure you have the latest image. If not, it prompts you to pass the `--upgrade` flag to get the latest image.
- So when [trying to get the SHA](https://github.com/wandb/wandb/blob/2f0ad645f55b5edf00b249f82d5bccd773316e97/wandb/docker/__init__.py#L187) for the latest image on docker hub, we need and internet connectivity to obtain that SHA. Since you had no network connection it raised an exception and the function [returned](https://github.com/wandb/wandb/blob/2f0ad645f55b5edf00b249f82d5bccd773316e97/wandb/docker/__init__.py#L197) None . 

You will need an internet connection to execute wandb server start. If you already pulled the image and have it on your machine, e.g. `docker pull wandb/local:latest` then you can launch server using docker `docker run --rm -d -v wandb:/vol -p 8080:8080 --name wandb-local wandb/local:latest`
