### ISSUE TITLE
[CLI]: The entity argument passed to wandb.init is not honored

### ISSUE THREAD

**Issue by alegonz** [wandb/wandb#6651]
### Describe the bug

The documentation states:

> **Do environment variables overwrite the parameters passed to wandb.init()?**
> Arguments passed to `wandb.init` take precedence over the environment.

However, when attempting to use an artifact from a run that was created by calling `wandb.init` with an entity different to the one set in `WANDB_ENTITY` it raises a permission error. See below on how to reproduce the issue.

I believe there are two issues here:
1. The entity passed to `wandb.init` is not taking precedence over the environment variable, contrary to what the documentation states.
2. If my understanding is correct, the entity of the run calling `use_artifact` should be irrelevant anyway. If the user has permissions to the entity that owns the artifact, then the user should be able to use the artifact from a run belonging to a different entity.

Script to log an artifact:
```python
# log_artifact.py
from pathlib import Path
import wandb

run = wandb.init(entity="gon", project="test")
file = Path("foo.txt")
file.touch()
artifact = wandb.Artifact(name="foo", type="bar")
artifact.add_file(str(file))
run.log_artifact(artifact)
```

Script to use the artifact:
```python
# use_artifact.py
import wandb

run = wandb.init(entity="gon", project="test")
artifact = run.use_artifact('gon/test/foo:v0', type='bar')
```

Steps:
```shell
~$ # First log an artifact
~$ python3 use_artifact.py

# Then try to use the artifact but with the WANDB_ENTITY env var set to an entity different to the one passed to wandb.init
# The "anotherentity" entity does exist, but the result is the same regardless.
~$ WANDB_ENTITY="anotherentity" python3 use_artifact.py
```

The output of `use_artifact.py` is as shown below:

```shell
wandb: Currently logged in as: gon. Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.16.0
wandb: Run data is saved locally in **REDACTED**/wandb/run-20231201_095905-xl6wuvuo
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run exalted-cherry-68
wandb: ⭐️ View project at https://**REDACTED**/gon/test
wandb: 🚀 View run at https://**REDACTED**/gon/test/runs/xl6wuvuo
wandb: ERROR Error while calling W&B API: failed to find run test/xl6wuvuo (<Response [404]>)
wandb: ERROR Permission denied to access gon/test/xl6wuvuo
Traceback (most recent call last):
  File "**REDACTED**/venv/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "**REDACTED**/venv/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 366, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "**REDACTED**/venv/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "**REDACTED**/venv/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "**REDACTED**/venv/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "**REDACTED**/venv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://**REDACTED**/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "**REDACTED**/use_artifact.py", line 4, in <module>
    artifact = run.use_artifact('gon/test/foo:v0', type='bar')
  File "**REDACTED**/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 371, in wrapper_fn
    return func(self, *args, **kwargs)
  File "**REDACTED**/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 361, in wrapper
    return func(self, *args, **kwargs)
  File "**REDACTED**/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2790, in use_artifact
    api.use_artifact(
  File "**REDACTED**/venv/lib/python3.10/site-packages/wandb/apis/internal.py", line 156, in use_artifact
    return self.api.use_artifact(*args, **kwargs)
  File "**REDACTED**/venv/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 3241, in use_artifact
    response = self.gql(
  File "**REDACTED**/venv/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 338, in gql
    ret = self._retry_gql(
  File "**REDACTED**/venv/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "**REDACTED**/venv/lib/python3.10/site-packages/wandb/util.py", line 905, in no_retry_auth
    raise CommError(f"Permission denied to access {wandb.run.path}")
wandb.errors.CommError: Permission denied to access gon/test/xl6wuvuo
wandb: 🚀 View run exalted-cherry-68 at: https://app.wb.swp-ml.tri-ad.global/gon/test/runs/xl6wuvuo
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 1 other file(s)
wandb: Find logs at: ./wandb/run-20231201_095905-xl6wuvuo/logs
```

If `WANDB_ENTITY` matches the one passed to `wandb.init` it works as expected.
```shell
~$ WANDB_ENTITY="gon" python3 use_artifact.py
```

### Environment

WandB version: 0.16.0

OS: Ubuntu 20.04

Python version: 3.10.12

Versions of relevant libraries:

**Comment by ArtsiomWB** [comment]
Thank you for reporting it, Alejandro! I was able to repro the concern and have sent it over to our engineering team.
