### ISSUE TITLE
[CLI]: BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by Obrepal** [wandb/wandb#6657]
### Describe the bug

```python
# sweep_config = {
#     "method": "bayes",
#     "metric": {"goal": "minimize", "name": "Final score"},
#     "parameters": {
#         "n_estimators": {"values": [100, 120, 150, 200, 300, 400, 500, 600, 700]},
#         "max_depth": {"values": [10, 12, 15, 20,25,30]},
#         "min_samples_split": {"values": [2, 3, 5, 7, 10]},
#         "min_samples_leaf": {"values": [1, 2, 3, 4, 5]},
#     },
# }
with open ("configs_wandb/random_forest_config.json", 'r') as f:
    sweep_config = json.load(f)

# wandb.init(project="Seeing-beyond-the-visible")

wandb.init(settings=wandb.Settings(start_method="fork"),project="my-first-sweep_1")
sweep_id = wandb.sweep(sweep=sweep_config, project="my-first-sweep_1")

wandb.agent(sweep_id, function=train_random_forest, count=50)

def train_random_forest():

    n_estimators = wandb.config.n_estimators
    max_depth = wandb.config.max_depth
    min_samples_split = wandb.config.min_samples_split
    min_samples_leaf = wandb.config.min_samples_leaf


    model = RandomForestRegressor(
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        min_samples_leaf=min_samples_leaf,
        random_state=42,
    )

    model.fit(X_train, y_train)
    predictions = model.predict(X_test)

    mse = np.mean((y_test - predictions) ** 2, axis=0)
    scores = mse / baselines
    final_score = np.mean(scores)


    wandb.log(
            { 
               "Final score": final_score,
                "n_estimators": n_estimators,
                "max_depth": max_depth,
                "min_samples_split": min_samples_split,
                "min_samples_leaf": min_samples_leaf,
            }
        )
    wandb.finish()
    
```

```shell
wandb: WARNING Calling wandb.login() after wandb.init() has no effect.
Create sweep with ID: ofnbus1w
Sweep URL: https://wandb.ai/i-obrepal/my-first-sweep_1/sweeps/ofnbus1w
wandb: WARNING Source type is set to 'repo' but some required information is missing from the environment. A job will not be created from this run. See https://docs.wandb.ai/guides/launch/create-job
<IPython.core.display.HTML object>
<IPython.core.display.HTML object>
wandb: Agent Starting Run: q1d0g619 with config:
wandb: 	max_depth: 25
wandb: 	min_samples_leaf: 2
wandb: 	min_samples_split: 10
wandb: 	n_estimators: 120
Exception in thread Exception in thread NetStatThr:
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_sandbox/lib/python3.8/threading.py", line 932, in _bootstrap_inner
ChkStopThr:
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_sandbox/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Exception in thread IntMsgThr:
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_sandbox/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_sandbox/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_sandbox/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 286, in check_stop_status
    self._loop_check_status(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_sandbox/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 224, in _loop_check_status
    local_handle = request()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_sandbox/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 750, in deliver_stop_status
    self.run()
          File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_sandbox/lib/python3.8/threading.py", line 870, in run
return self._deliver_stop_status(status)    self.run()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_sandbox/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 468, in _deliver_stop_status
self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_sandbox/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 300, in check_internal_messages

          File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_sandbox/lib/python3.8/threading.py", line 870, in run
self._loop_check_status(return self._deliver_record(record)
      File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_sandbox/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 224, in _loop_check_status
self._target(*self._args, **self._kwargs)

      File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_sandbox/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 268, in check_network_status
local_handle = request()      File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_sandbox/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 437, in _deliver_record

self._loop_check_status(      File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_sandbox/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 766, in deliver_internal_messages

  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_sandbox/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 224, in _loop_check_status
handle = mailbox._deliver_record(record, interface=self)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_sandbox/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 455, in _deliver_record
            local_handle = request()
return self._deliver_internal_messages(internal_message)  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_sandbox/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 758, in deliver_network_status
interface._publish(record)

  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_sandbox/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 490, in _deliver_internal_messages
      File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_sandbox/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
return self._deliver_network_status(status)    
return self._deliver_record(record)      File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_sandbox/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 484, in _deliver_network_status

self._sock_client.send_record_publish(record)  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_sandbox/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 437, in _deliver_record
    
    return self._deliver_record(record)  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_sandbox/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 221, in send_record_publish
handle = mailbox._deliver_record(record, interface=self)
    
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_sandbox/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 455, in _deliver_record
self.send_server_request(server_req)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_sandbox/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)      File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_sandbox/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 437, in _deliver_record

  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_sandbox/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
interface._publish(record)
      File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_sandbox/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
    self._sendall_with_error_handle(header + data)
self._sock_client.send_record_publish(record)  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_sandbox/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle

  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_sandbox/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 221, in send_record_publish
        sent = self._sock.send(data)handle = mailbox._deliver_record(record, interface=self)    

  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_sandbox/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 455, in _deliver_record
self.send_server_request(server_req)
    BrokenPipeError: [Errno 32] Broken pipe
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_sandbox/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)interface._publish(record)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_sandbox/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    
self._sendall_with_error_handle(header + data)  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_sandbox/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish

      File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_sandbox/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    self._sock_client.send_record_publish(record)sent = self._sock.send(data)

BrokenPipeError  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_sandbox/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 221, in send_record_publish
: [Errno 32] Broken pipe
    self.send_server_request(server_req)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_sandbox/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_sandbox/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_sandbox/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

```

### Environment

WandB version: wandb, version 0.16.0

OS:  Ventura Version 13.5.1 (22G90)

Python version: Python 3.8.16

Versions of relevant libraries:

**Comment by Obrepal** [comment]
Here you can that for first case final result is NULL
![W B Chart 3 12 2023, 21 49 56](https://github.com/wandb/wandb/assets/48407260/9821c6d2-da02-449b-a52b-8238e23c8a42)

**Comment by Obrepal** [comment]
[debug-internal.log](https://github.com/wandb/wandb/files/13599938/debug-internal.log)
[debug.log](https://github.com/wandb/wandb/files/13599939/debug.log)
sure, here they are

**Comment by Obrepal** [comment]
I also attach with suggested changes applied, but Null still exists 
[debug-internal.log](https://github.com/wandb/wandb/files/13600107/debug-internal.log)
[debug.log](https://github.com/wandb/wandb/files/13600108/debug.log)

**Comment by MBakirWB** [comment]
Hi @Obrepal we appreciate your patience as we looked into this. Thank you for modifying your code per suggestions by Carlo. I reviewed your debug logs and the following caught my attention: 

In `debug-internal.log` 

> 2023-12-07 13:51:52,402 DEBUG   HandlerThread:19028 [handler.py:handle_request():146] handle_request: status_report

and `debug.log`

`2023-12-07 13:49:43,088 INFO    Thread-14 :18371 [wandb_init.py:init():841] run started, returning control to user process`

This indicates to me a run was interrupted after being started. Did you at anytime kill a run from your terminal? Specifically the last run that is showing a Null value for final score? 

Did you notice any wandb warnings or errors in your terminal?

Would you say this is happening for every sweep?

My [reproduction attempting](https://wandb.ai/mohammadbakir/my-first-sweep_1/sweeps/bzaoe4x4) using your example

**Comment by MBakirWB** [comment]
Hi @Obrepal , I wanted to follow up with you to see if you've had an opportunity to review my previous response regarding the sweeps issue you were experiencing?

**Comment by Obrepal** [comment]
Yes, I killed it. Is it the source of the problem and Nones?

**Comment by MBakirWB** [comment]
Hi @Obrepal , see new link for reproduction efforts https://wandb.ai/mohammadbakir/github-6657/sweeps/rf0rs7ks. If you were to kill the run, then yes, I would expect Nones if the run summary metrics have not fully logged to the run. Marking this resolved, but do let us know if you have any questions.

**Comment by Obrepal** [comment]
Hi, it is still a issue 
@Carlo-Argel [`wandb: WARNING Calling wandb.login() after wandb.init() has no effect.
Create sweep with ID: uk2esyb6
Sweep URL: https://wandb.ai/i-obrepal/improved_workflow_test/sweeps/uk2esyb6
<IPython.core.display.HTML object>
<IPython.core.display.HTML object>
wandb: Agent Starting Run: 8joivan8 with config:
wandb: 	max_depth: 25
wandb: 	min_samples_leaf: 5
wandb: 	min_samples_split: 3
wandb: 	n_estimators: 150
wandb: 	random_state: 42
Exception in thread Exception in thread NetStatThrException in thread ChkStopThr:
IntMsgThr:
:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/hyperview/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
  File "/opt/homebrew/Caskroom/miniforge/base/envs/hyperview/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
  File "/opt/homebrew/Caskroom/miniforge/base/envs/hyperview/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
        self.run()self.run()    

self.run()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/hyperview/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 761, in run_closure
  File "/opt/homebrew/Caskroom/miniforge/base/envs/hyperview/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 761, in run_closure
  File "/opt/homebrew/Caskroom/miniforge/base/envs/hyperview/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 761, in run_closure
            _threading_Thread_run(self)_threading_Thread_run(self)_threading_Thread_run(self)


  File "/opt/homebrew/Caskroom/miniforge/base/envs/hyperview/lib/python3.11/threading.py", line 982, in run
  File "/opt/homebrew/Caskroom/miniforge/base/envs/hyperview/lib/python3.11/threading.py", line 982, in run
  File "/opt/homebrew/Caskroom/miniforge/base/envs/hyperview/lib/python3.11/threading.py", line 982, in run
        self._target(*self._args, **self._kwargs)    self._target(*self._args, **self._kwargs)
self._target(*self._args, **self._kwargs)

  File "/opt/homebrew/Caskroom/miniforge/base/envs/hyperview/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 300, in check_internal_messages
  File "/opt/homebrew/Caskroom/miniforge/base/envs/hyperview/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 286, in check_stop_status
  File "/opt/homebrew/Caskroom/miniforge/base/envs/hyperview/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 268, in check_network_status
    self._loop_check_status(    
    self._loop_check_status(self._loop_check_status(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/hyperview/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 224, in _loop_check_status

  File "/opt/homebrew/Caskroom/miniforge/base/envs/hyperview/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 224, in _loop_check_status
  File "/opt/homebrew/Caskroom/miniforge/base/envs/hyperview/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 224, in _loop_check_status
        local_handle = request()local_handle = request()

    local_handle = request()  
                                                   ^^ ^ ^^ ^^ ^^^^^^^^^^
^^^^^  File "/opt/homebrew/Caskroom/miniforge/base/envs/hyperview/lib/python3.11/site-packages/wandb/sdk/interface/interface.py", line 803, in deliver_internal_messages
^^
^^  File "/opt/homebrew/Caskroom/miniforge/base/envs/hyperview/lib/python3.11/site-packages/wandb/sdk/interface/interface.py", line 787, in deliver_stop_status
    ^return self._deliver_internal_messages(internal_message)

  File "/opt/homebrew/Caskroom/miniforge/base/envs/hyperview/lib/python3.11/site-packages/wandb/sdk/interface/interface.py", line 795, in deliver_network_status
      return self._deliver_stop_status(status)     
return self._deliver_network_status(status) 
                    ^  ^  ^    ^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^
^  File "/opt/homebrew/Caskroom/miniforge/base/envs/hyperview/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 484, in _deliver_stop_status
^  File "/opt/homebrew/Caskroom/miniforge/base/envs/hyperview/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 500, in _deliver_network_status
^^^^^^    ^    return self._deliver_record(record)^return self._deliver_record(record)


   File "/opt/homebrew/Caskroom/miniforge/base/envs/hyperview/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 506, in _deliver_internal_messages
              return self._deliver_record(record)  
          ^  ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^  File "/opt/homebrew/Caskroom/miniforge/base/envs/hyperview/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 449, in _deliver_record
^^^
^    ^handle = mailbox._deliver_record(record, interface=self)  File "/opt/homebrew/Caskroom/miniforge/base/envs/hyperview/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 449, in _deliver_record
^
^^     ^ handle = mailbox._deliver_record(record, interface=self)
 
     File "/opt/homebrew/Caskroom/miniforge/base/envs/hyperview/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 449, in _deliver_record
            handle = mailbox._deliver_record(record, interface=self)  
      ^ ^  ^   ^  ^  ^ ^^^^ ^^^^ ^ ^^^ ^^ ^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^  File "/opt/homebrew/Caskroom/miniforge/base/envs/hyperview/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 455, in _deliver_record
^^^^^^^    ^^interface._publish(record)^^^^^^^^^
^
^^  File "/opt/homebrew/Caskroom/miniforge/base/envs/hyperview/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/hyperview/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 455, in _deliver_record
  File "/opt/homebrew/Caskroom/miniforge/base/envs/hyperview/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 455, in _deliver_record
    self._sock_client.send_record_publish(record)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/hyperview/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 221, in send_record_publish
    interface._publish(record)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/hyperview/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
    interface._publish(record)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/hyperview/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
    self._sock_client.send_record_publish(record)
      File "/opt/homebrew/Caskroom/miniforge/base/envs/hyperview/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 221, in send_record_publish
    self.send_server_request(server_req)self._sock_client.send_record_publish(record)

      File "/opt/homebrew/Caskroom/miniforge/base/envs/hyperview/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
self.send_server_request(server_req)  File "/opt/homebrew/Caskroom/miniforge/base/envs/hyperview/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 221, in send_record_publish

          File "/opt/homebrew/Caskroom/miniforge/base/envs/hyperview/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
self._send_message(msg)self.send_server_request(server_req)

    self._send_message(msg)  File "/opt/homebrew/Caskroom/miniforge/base/envs/hyperview/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message

  File "/opt/homebrew/Caskroom/miniforge/base/envs/hyperview/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
      File "/opt/homebrew/Caskroom/miniforge/base/envs/hyperview/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
self._sendall_with_error_handle(header + data)
    self._send_message(msg)    
  File "/opt/homebrew/Caskroom/miniforge/base/envs/hyperview/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
self._sendall_with_error_handle(header + data)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/hyperview/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
      File "/opt/homebrew/Caskroom/miniforge/base/envs/hyperview/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
sent = self._sock.send(data)
        self._sendall_with_error_handle(header + data) sent = self._sock.send(data)

   File "/opt/homebrew/Caskroom/miniforge/base/envs/hyperview/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
         sent = self._sock.send(data)
                ^   ^  ^^  ^^ ^^ ^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

^^BrokenPipeErrorBrokenPipeError: : ^^[Errno 32] Broken pipe^[Errno 32] Broken pipe`]
