### ISSUE TITLE
[CLI]: `mlflow` importer uses old API

### ISSUE THREAD

**Issue by dannyfriar** [wandb/wandb#6755]
### Describe the bug

```bash
~> wandb import mlflow --mlflow-tracking-uri ... --target-project test-mlflow --target-entity test-mlflow
```

```shell
Traceback (most recent call last):
  File "/home/admin/.virtualenvs/research/bin/wandb", line 8, in <module>
    sys.exit(cli())
  File "/home/admin/.virtualenvs/research/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/admin/.virtualenvs/research/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/admin/.virtualenvs/research/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/admin/.virtualenvs/research/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/admin/.virtualenvs/research/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/admin/.virtualenvs/research/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/admin/.virtualenvs/research/lib/python3.10/site-packages/wandb/cli/cli.py", line 2657, in mlflow
    importer.import_all_parallel(overrides=overrides)
AttributeError: 'MlflowImporter' object has no attribute 'import_all_parallel'
```

The docs also seem to reference this https://docs.wandb.ai/guides/track/public-api-guide#import-runs-and-reports-with-custom-logic.

I tried with the Python API and ran into various protobuf errors. After hacking around these the import of a single run appears to complete but I can't see the run in the UI.

### Environment

WandB version: 0.16.1

OS: Ubuntu 22.04

Python version: 3.10

Versions of relevant libraries: mlflow==2.9.2

**Comment by dannyfriar** [comment]
These docs also reference https://github.com/wandb/wandb/issues/6184 which seems like it was removed a few months ago.
