### ISSUE TITLE
[App]: Run running forever despite job crashing weeks ago

### ISSUE THREAD

**Issue by mova** [wandb/wandb#6779]
### Current Behavior

Hey, 
all my runs in 
https://wandb.ai/hamgen/calochallange/table?workspace=user-mscham
are still marked as 'running' despite them crashing a while ago.
Stopping them via the web interface doesn't work.
EG. 
https://wandb.ai/hamgen/calochallange/runs/4rfphfjo

loading one of these runs results in   this:

~~~
>>> import wandb
>>> wandb_run = wandb.init(
...     id="bl062a5p",
...     resume="must",
... )
Problem at: <stdin> 1 <module>    
wandb: ERROR You provided an invalid value for the `resume` argument. The value 'must' is not a valid option for resuming a run (bl062a5p) that does not exist. 
Please check your inputs and try again with a valid run ID. If you are trying to start a new run, please omit the `resume` argument or use `resume='allow'`.
Traceback (most recent call last):                                              
  File "<stdin>", line 1, in <module>
  File "/dev/shm/mscham/fgsim/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1189, in init
    raise e
  File "/dev/shm/mscham/fgsim/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/dev/shm/mscham/fgsim/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 781, in init
    raise error
wandb.errors.UsageError: You provided an invalid value for the `resume` argument. The value 'must' is not a valid option for resuming a run (bl062a5p) that does  not exist. Please check your inputs and try again with a valid run ID. If you are trying to start a new run, please omit the `resume` argument or use `resume='allow'`.
~~~

### Environment

OS:

Browsers:

Version:

**Comment by rsanandres-wandb** [comment]
Hello @mova !

I have asked our team to look into this for you and to stop your runs in our UI. I will get back to you once they have gotten back to me.

**Comment by rsanandres-wandb** [comment]
Hello @mova ! Our Infra team has stopped the runs for you and you should now be able to see that they have stopped running. Let me know if this is not the case for you.
