### ISSUE TITLE
[CLI]: .log_code error due to temp file permission

### ISSUE THREAD

**Issue by MoH-assan** [wandb/wandb#6800]
### Describe the bug

when using `.log_code` , appdirs package  attempt to write temp file to `~/.local/share/<AppName> ` [appdirs.py#L73-L74](https://github.com/ActiveState/appdirs/blob/8734277956c1df3b85385e6b308e954910533884/appdirs.py#L73-L74) I don't have writing permission to. 

I am not sure, but may be here, using `os.environ['WANDB_DIR']`  can be a better solution not sure. 
https://github.com/wandb/wandb/blob/6a211b19f02ee7c6b87b82eafd5789c4ba3739ec/wandb/env.py#L373

This also works
os.environ['XDG_DATA_HOME'] = root_path

```python
wandb_run.log_code(root=root_path)
```

```shell
Traceback (most recent call last):
File "/gpfs/fs0/scratch/c/cglee/abubakr5/AM/Codes/deep_spatiotemporal_model/training.py", line 243, in <module>
wandb_run.log_code(root=root_path)
File "/home/c/cglee/abubakr5/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 371, in wrapper_fn
return func(self, *args, **kwargs)
File "/home/c/cglee/abubakr5/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 361, in wrapper
return func(self, *args, **kwargs)
File "/home/c/cglee/abubakr5/.local/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1165, in log_code
art.add_file(file_path, name=save_name)
File "/home/c/cglee/abubakr5/.local/lib/python3.9/site-packages/wandb/sdk/artifacts/artifact.py", line 1194, in add_file
return self._add_local_file(name, local_path, digest=digest)
File "/home/c/cglee/abubakr5/.local/lib/python3.9/site-packages/wandb/sdk/artifacts/artifact.py", line 1469, in _add_local_file
with tempfile.NamedTemporaryFile(dir=get_staging_dir(), delete=False) as f:
File "/home/c/cglee/abubakr5/.conda/envs/BKRMIST39/lib/python3.9/tempfile.py", line 545, in NamedTemporaryFile
(fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
File "/home/c/cglee/abubakr5/.conda/envs/BKRMIST39/lib/python3.9/tempfile.py", line 255, in _mkstemp_inner
fd = _os.open(file, flags, 0o600)
OSError: [Errno 30] Read-only file system: '/home/c/cglee/abubakr5/.local/share/wandb/artifacts/staging/tmpnrkfdqt5'
```

I guess this is also related to this issue [#6792](https://github.com/wandb/wandb/issues/6792) but in my case, the below did not help.  

```
os.chdir(root_path)
os.environ['TMPDIR'] = root_path
os.environ['TEMP'] = root_path
os.environ['TMP'] = root_path
# os.environ['XDG_DATA_HOME'] = root_path
os.environ['DATA_DIR'] = root_path
os.environ['ARTIFACT_DIR'] = root_path
os.environ['WANDB_DIR'] = wandb_dir
os.environ['WANDB_CACHE_DIR'] = wandb_dir
os.environ['WANDB_CONFIG_DIR'] = wandb_dir
os.environ['DATA_DIR'] = wandb_dir
```

### Environment

WandB version:
 0.16.0

OS:
linux

Python version:
Python 3.8.8 (default, Apr 13 2021, 20:11:25)
[GCC 7.3.0] :: Anaconda, Inc. on linux

**Comment by kptkin** [comment]
@MoH-assan could you try using `WANDB_DATA_DIR` env variable and let us know if that solved your issue?

**Comment by MoH-assan** [comment]
@kptkin `os.environ['WANDB_DATA_DIR'] = root_path` works! 
Thanks
