### ISSUE TITLE
[CLI]: Wandb fails if git detects dubious ownership

### ISSUE THREAD

**Issue by zacps** [wandb/wandb#6877]
### Describe the bug

If git detects dubious repository ownership the wandb run will fail with the log:

```
Jan 21 10:20:47 bubbles02 pipeline.sh[695325]: Thread HandlerThread:
Jan 21 10:20:47 bubbles02 pipeline.sh[695325]: Traceback (most recent call last):
Jan 21 10:20:47 bubbles02 pipeline.sh[695325]:   File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/internal/internal_util.py", line 49, in run
Jan 21 10:20:47 bubbles02 pipeline.sh[695325]:     self._run()
Jan 21 10:20:47 bubbles02 pipeline.sh[695325]:   File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/internal/internal_util.py", line 100, in _run
Jan 21 10:20:47 bubbles02 pipeline.sh[695325]:     self._process(record)
Jan 21 10:20:47 bubbles02 pipeline.sh[695325]:   File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/internal/internal.py", line 279, in _process
Jan 21 10:20:47 bubbles02 pipeline.sh[695325]:     self._hm.handle(record)
Jan 21 10:20:47 bubbles02 pipeline.sh[695325]:   File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/internal/handler.py", line 138, in handle
Jan 21 10:20:47 bubbles02 pipeline.sh[695325]:     handler(record)
Jan 21 10:20:47 bubbles02 pipeline.sh[695325]:   File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/internal/handler.py", line 148, in handle_request
Jan 21 10:20:47 bubbles02 pipeline.sh[695325]:     handler(record)
Jan 21 10:20:47 bubbles02 pipeline.sh[695325]:   File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/internal/handler.py", line 683, in handle_request_run_start
Jan 21 10:20:47 bubbles02 pipeline.sh[695325]:     self._system_monitor.probe(publish=True)
Jan 21 10:20:47 bubbles02 pipeline.sh[695325]:   File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/internal/system/system_monitor.py", line 228, in probe
Jan 21 10:20:47 bubbles02 pipeline.sh[695325]:     self.system_info.publish(system_info)
Jan 21 10:20:47 bubbles02 pipeline.sh[695325]:   File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/internal/system/system_info.py", line 255, in publish
Jan 21 10:20:47 bubbles02 pipeline.sh[695325]:     self._save_patches()
Jan 21 10:20:47 bubbles02 pipeline.sh[695325]:   File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/internal/system/system_info.py", line 146, in _save_patches
Jan 21 10:20:47 bubbles02 pipeline.sh[695325]:     upstream_commit = self.git.get_upstream_fork_point()
Jan 21 10:20:47 bubbles02 pipeline.sh[695325]:   File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/lib/gitlib.py", line 200, in get_upstream_fork_point
Jan 21 10:20:47 bubbles02 pipeline.sh[695325]:     possible_relatives.append(tracking_branch.commit)
Jan 21 10:20:47 bubbles02 pipeline.sh[695325]:   File "/usr/local/lib/python3.8/dist-packages/git/refs/symbolic.py", line 274, in _get_commit
Jan 21 10:20:47 bubbles02 pipeline.sh[695325]:     obj = self._get_object()
Jan 21 10:20:47 bubbles02 pipeline.sh[695325]:   File "/usr/local/lib/python3.8/dist-packages/git/refs/symbolic.py", line 267, in _get_object
Jan 21 10:20:47 bubbles02 pipeline.sh[695325]:     return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
Jan 21 10:20:47 bubbles02 pipeline.sh[695325]:   File "/usr/local/lib/python3.8/dist-packages/git/objects/base.py", line 94, in new_from_sha
Jan 21 10:20:47 bubbles02 pipeline.sh[695325]:     oinfo = repo.odb.info(sha1)
Jan 21 10:20:47 bubbles02 pipeline.sh[695325]:   File "/usr/local/lib/python3.8/dist-packages/git/db.py", line 40, in info
Jan 21 10:20:47 bubbles02 pipeline.sh[695325]:     hexsha, typename, size = self._git.get_object_header(bin_to_hex(binsha))
Jan 21 10:20:47 bubbles02 pipeline.sh[695325]:   File "/usr/local/lib/python3.8/dist-packages/git/cmd.py", line 1384, in get_object_header
Jan 21 10:20:47 bubbles02 pipeline.sh[695325]:     return self.__get_object_header(cmd, ref)
Jan 21 10:20:47 bubbles02 pipeline.sh[695325]:   File "/usr/local/lib/python3.8/dist-packages/git/cmd.py", line 1370, in __get_object_header
Jan 21 10:20:47 bubbles02 pipeline.sh[695325]:     cmd.stdin.flush()
Jan 21 10:20:47 bubbles02 pipeline.sh[695325]: BrokenPipeError: [Errno 32] Broken pipe
Jan 21 10:20:47 bubbles02 pipeline.sh[695325]: wandb: ERROR Internal wandb error: file data was not synced
Jan 21 10:20:54 bubbles02 pipeline.sh[695253]: wandb: ERROR Find detailed error logs at: /opt/PROJECT/wandb/debug-cli.root.log
Jan 21 10:20:54 bubbles02 pipeline.sh[695253]: Error: transport failed
Jan 21 10:20:54 bubbles02 pipeline.sh[695253]: Problem at: /usr/local/lib/python3.8/dist-packages/wandb/sdk/artifacts/artifact.py 1694 download
Jan 21 10:20:54 bubbles02 pipeline.sh[695253]: wandb: While tearing down the service manager. The following error has occurred: [Errno 32] Broken pipe

```

Debug internal log:
```shell
2024-01-21 10:20:44,592 INFO    HandlerThread:695325 [system_monitor.py:probe():224] Finished collecting system info
2024-01-21 10:20:44,592 INFO    HandlerThread:695325 [system_monitor.py:probe():227] Publishing system info
2024-01-21 10:20:44,593 DEBUG   HandlerThread:695325 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-01-21 10:20:44,593 DEBUG   HandlerThread:695325 [system_info.py:_save_pip():68] Saving pip packages done
2024-01-21 10:20:44,593 DEBUG   HandlerThread:695325 [system_info.py:_save_code():90] Saving code
2024-01-21 10:20:44,593 WARNING HandlerThread:695325 [system_info.py:_save_code():92] unable to save code -- program entry not found
2024-01-21 10:20:44,593 DEBUG   HandlerThread:695325 [system_info.py:_save_patches():128] Saving git patches
2024-01-21 10:20:44,597 ERROR   HandlerThread:695325 [gitlib.py:root():92] git root error: Cmd('git') failed due to: exit code(128)
  cmdline: git rev-parse --show-toplevel
  stderr: 'fatal: detected dubious ownership in repository at '/opt/PROJECT'
To add an exception for this directory, call:

        git config --global --add safe.directory /opt/PROJECT'
2024-01-21 10:20:45,362 INFO    Thread-12 :695325 [dir_watcher.py:_on_file_created():271] file/dir created: /opt/PROJECT/wandb/run-20240121_102039-nn56f1rr/files/requirements.txt
2024-01-21 10:20:45,368 INFO    WriterThread:695325 [datastore.py:close():294] close: /opt/PROJECT/wandb/run-20240121_102039-nn56f1rr/run-nn56f1rr.wandb
2024-01-21 10:20:45,533 INFO    SenderThread:695325 [sender.py:finish():1548] shutting down sender
2024-01-21 10:20:45,533 INFO    SenderThread:695325 [dir_watcher.py:finish():358] shutting down directory watcher
2024-01-21 10:20:46,363 INFO    SenderThread:695325 [dir_watcher.py:finish():388] scan: /opt/PROJECT/wandb/run-20240121_102039-nn56f1rr/files
2024-01-21 10:20:46,363 INFO    SenderThread:695325 [dir_watcher.py:finish():402] scan save: /opt/PROJECT/wandb/run-20240121_102039-nn56f1rr/files/requirements.txt requirements.txt
2024-01-21 10:20:46,363 INFO    SenderThread:695325 [dir_watcher.py:finish():402] scan save: /opt/PROJECT/wandb/run-20240121_102039-nn56f1rr/files/config.yaml config.yaml
2024-01-21 10:20:46,363 INFO    SenderThread:695325 [file_pusher.py:finish():175] shutting down file pusher
2024-01-21 10:20:46,365 INFO    SenderThread:695325 [file_pusher.py:join():181] waiting for file pusher
2024-01-21 10:20:46,751 INFO    wandb-upload_1:695325 [upload_job.py:push():131] Uploaded file /opt/PROJECT/wandb/run-20240121_102039-nn56f1rr/files/config.yaml
2024-01-21 10:20:46,829 INFO    wandb-upload_0:695325 [upload_job.py:push():131] Uploaded file /opt/PROJECT/wandb/run-20240121_102039-nn56f1rr/files/requirements.txt
2024-01-21 10:20:47,367 INFO    SenderThread:695325 [file_stream.py:finish():595] file stream finish called
2024-01-21 10:20:47,450 INFO    SenderThread:695325 [file_stream.py:finish():599] file stream finish is done
2024-01-21 10:20:47,526 ERROR   StreamThr :695325 [internal.py:wandb_internal():174] Thread HandlerThread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/internal/internal_util.py", line 49, in run
    self._run()
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/internal/internal_util.py", line 100, in _run
    self._process(record)
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/internal/internal.py", line 279, in _process
    self._hm.handle(record)
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/internal/handler.py", line 138, in handle
    handler(record)
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/internal/handler.py", line 148, in handle_request
    handler(record)
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/internal/handler.py", line 683, in handle_request_run_start
    self._system_monitor.probe(publish=True)
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/internal/system/system_monitor.py", line 228, in probe
    self.system_info.publish(system_info)
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/internal/system/system_info.py", line 255, in publish
    self._save_patches()
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/internal/system/system_info.py", line 146, in _save_patches
    upstream_commit = self.git.get_upstream_fork_point()
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/lib/gitlib.py", line 200, in get_upstream_fork_point
    possible_relatives.append(tracking_branch.commit)
  File "/usr/local/lib/python3.8/dist-packages/git/refs/symbolic.py", line 274, in _get_commit
    obj = self._get_object()
  File "/usr/local/lib/python3.8/dist-packages/git/refs/symbolic.py", line 267, in _get_object
    return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
  File "/usr/local/lib/python3.8/dist-packages/git/objects/base.py", line 94, in new_from_sha
    oinfo = repo.odb.info(sha1)
  File "/usr/local/lib/python3.8/dist-packages/git/db.py", line 40, in info
    hexsha, typename, size = self._git.get_object_header(bin_to_hex(binsha))
  File "/usr/local/lib/python3.8/dist-packages/git/cmd.py", line 1384, in get_object_header
    return self.__get_object_header(cmd, ref)
  File "/usr/local/lib/python3.8/dist-packages/git/cmd.py", line 1370, in __get_object_header
    cmd.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe
```

### Environment

WandB version: 0.16.2

OS: Linux

Python version: 3.10.12

**Comment by thanos-wandb** [comment]
Hi @zacps thank you for reporting this issue. It looks like it fails during run's init, as there are some git checks in wandb.init() call and the error seems related to Git `safe.directory` configuration.

There might be two possible ways to prevent this from happening, one would be to disable wandb from probing git repo hence capturing latest commit/diff, and you could do that by exporting the following environment variable:
`WANDB_DISABLE_GIT=True`

Another way would be to add an exception to this directory, as it's suggested in the stacktrace:
`git config --global --add safe.directory /opt/PROJECT`

Would any of these options work for you?

**Comment by zacps** [comment]
Yes, these work as workarounds, but ultimately wandb should fall back to not collecting git information (or at the very least emit a more understandable error message).

**Comment by thanos-wandb** [comment]
Great, thank you for confirming these would work for you as temporary solutions. Thanks as well for the feedback, I will log it as a feature request with the team so that we can support either a fallback mechanism or output a more detailed message. We will keep you updated here.

**Comment by sephmard** [comment]
@shc443, wondering if you have had a chance to try our new Go based client: https://wandb.me/wandb-core? This update includes some stability improvements that might help with the Git ownership detection issue you encountered. You can try it out by adding wandb.require("core") to your scripts. Can you let us know if this addresses your issue?
