### ISSUE TITLE
[CLI]: "None if not a permitted value of the categorical hyperparameter in the current sweep

### ISSUE THREAD

**Issue by ahalev** [wandb/wandb#6881]
### Describe the bug

Pretty self-explanatory. I think this behavior hasn't failed before so this is might be a newly-introduced bug.

"None is not a permitted value of the categorical hyperparameter algo.train_config.loss.weight in the current sweep.",

See the sweep config below. This occurs when launching a new agent. I think this is happening server-side so I can't really debug this myself. I've attached the `debug.log` and the debug-internal.log`.

```shell
2024-01-21 22:42:05,813 - wandb.wandb_agent - INFO - Running runs: []
400 response executing GraphQL.
{"errors":[{"message":"None is not a permitted value of the categorical hyperparameter algo.train_config.loss.weight in the current sweep.","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
wandb: ERROR Error while calling W&B API: None is not a permitted value of the categorical hyperparameter algo.train_config.loss.weight in the current sweep. (<Response [400]>)
wandb: Terminating and syncing runs. Press ctrl-c to kill.
Traceback (most recent call last):
  File "/home/ahalev/miniconda3/envs/eye-image-env/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2778, in agent_heartbeat
    response = self.gql(
  File "/home/ahalev/miniconda3/envs/eye-image-env/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 338, in gql
    ret = self._retry_gql(
  File "/home/ahalev/miniconda3/envs/eye-image-env/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/ahalev/miniconda3/envs/eye-image-env/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 366, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/ahalev/miniconda3/envs/eye-image-env/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/ahalev/miniconda3/envs/eye-image-env/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/ahalev/miniconda3/envs/eye-image-env/lib/python3.8/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/ahalev/miniconda3/envs/eye-image-env/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "agent.py", line 4, in <module>
    Sweep().launch_agent()
  File "/home/ahalev/eye-image/project/rgen/sweep/sweep.py", line 69, in launch_agent
    wandb.agent(sweep_id, count=count)
  File "/home/ahalev/miniconda3/envs/eye-image-env/lib/python3.8/site-packages/wandb/wandb_agent.py", line 583, in agent
    return run_agent(
  File "/home/ahalev/miniconda3/envs/eye-image-env/lib/python3.8/site-packages/wandb/wandb_agent.py", line 528, in run_agent
    agent.run()
  File "/home/ahalev/miniconda3/envs/eye-image-env/lib/python3.8/site-packages/wandb/wandb_agent.py", line 277, in run
    commands = self._api.agent_heartbeat(agent_id, {}, run_status)
  File "/home/ahalev/miniconda3/envs/eye-image-env/lib/python3.8/site-packages/wandb/apis/internal.py", line 153, in agent_heartbeat
    return self.api.agent_heartbeat(*args, **kwargs)
  File "/home/ahalev/miniconda3/envs/eye-image-env/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2789, in agent_heartbeat
    message = ast.literal_eval(e.args[0])["message"]
  File "/home/ahalev/miniconda3/envs/eye-image-env/lib/python3.8/ast.py", line 59, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/home/ahalev/miniconda3/envs/eye-image-env/lib/python3.8/ast.py", line 47, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    400 Client Error: Bad Request for url: https://api.wandb.ai/graphql
        ^
SyntaxError: invalid syntax
```

I am receiving this (new?) error in running a bayesian sweep:

```shell
400 response executing GraphQL.                                                                          
{"errors":[{"message":"None is not a permitted value of the categorical hyperparameter algo.train_config.
loss.weight in the current sweep.","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}           
wandb: ERROR Error while calling W&B API: None is not a permitted value of the categorical hyperparameter
 algo.train_config.loss.weight in the current sweep. (<Response [400]>)  
```

As far as I can tell, this sweep has successfully launched runs with `algo.train_config.loss.weight=None` previously. I can link to them if desired.

Here is the config of the sweep:

```yaml
command:
  - /home/ahalev/miniconda3/envs/eye-image-env/bin/python
  - ${program}
  - ${args}
method: bayes
metric:
  goal: maximize
  name: Evaluate/EMA/balanced_accuracy_T-T_best
  target: 1
parameters:
  algo.model.architecture:
    distribution: categorical
    values:
      - inception_v3
      - vit_base_patch16_224
      - inception_resnet_v2
      - retfound_vit
  algo.train_config.loss.weight:
    distribution: categorical
    values:
      - null
      - reciprocal
      - reciprocal_squared
  algo.train_config.optimizer.lr:
    distribution: log_uniform_values
    max: 0.01
    min: 1e-06
  algo.train_config.optimizer.opt:
    distribution: categorical
    values:
      - sgd
      - adamw
  algo.train_config.optimizer.weight_decay:
    distribution: log_uniform_values
    max: 0.001
    min: 1e-09
  algo.train_config.scheduler.type:
    distribution: categorical
    values:
      - cosine
      - cyclic_triangular
      - cyclic_triangular2
      - cyclic_exp_range
  algo.train_config.train_layers:
    distribution: categorical
    values:
      - all
      - 2
      - 0.5
  dataset.images.train.eye:
    value: both
  dataset.images.train.side:
    value: both
  dataset.retinal_genotype.gene:
    value: arms2
  preprocess.add_gaussian_noise_sigma:
    distribution: uniform
    max: 1
    min: 0
  preprocess.gaussian_laplace_sigma:
    distribution: uniform
    max: 1
    min: 0
  preprocess.random_flip_probability.horizontal:
    distribution: categorical
    values:
      - 0
      - 0.5
  preprocess.random_flip_probability.vertical:
    distribution: categorical
    values:
      - 0
      - 0.5
  preprocess.resize_crop.ratio:
    distribution: categorical
    values:
      - - 0
      - - 0.75
        - 1.33
  preprocess.resize_crop.scale:
    distribution: categorical
    values:
      - - 0
      - - 0.6
        - 1
  project:
    value: retinal_genotype
program: ../trainer.py
project: retinal_genotype
```

Any assistance would be appreciated.

### Additional Files

[debug-internal.log](https://github.com/wandb/wandb/files/14015970/debug-internal.log)
[debug.log](https://github.com/wandb/wandb/files/14015971/debug.log)

### Environment

WandB version: 0.16.0

OS: Linux

Python version: 3.8.18

Versions of relevant libraries:

**Comment by luisbergua** [comment]
Hey @ahalev, thanks for writing in! I just tested with version `0.16.2` and the sweep runs fine with no errors so would you mind upgrading to see if the issue is gone?

**Comment by luisbergua** [comment]
Hey @ahalev, since we haven't heard back and the issue isn't reproducible in the latest version, we're going to close this request for now but please feel free to re-open if upgrading doesn't fix it.
