### ISSUE TITLE
FileNotFoundError [WinError 3] when running on Windows

### ISSUE THREAD

**Issue by dsaffie** [wandb/wandb#6896]
### Describe the bug

After creating an artifact and trying to call `log_artifact()` an exception is thrown for a file not found error.

```python
dataset_artifact = wandb.Artifact("test", "test", incremental=true)
wandb.log_artifact(dataset_artifact)
dataset_artifact = dataset_artifact.wait()
```

```shell
[2024-01-24T18:34:02.813Z] Exception in thread Thread-14 (_thread_body):
[2024-01-24T18:34:02.816Z] Traceback (most recent call last):
[2024-01-24T18:34:02.818Z]   File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
[2024-01-24T18:34:02.819Z]     self.run()
[2024-01-24T18:34:02.821Z]   File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
[2024-01-24T18:34:02.824Z]     self._target(*self._args, **self._kwargs)
[2024-01-24T18:34:02.827Z]   File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\filesync\step_checksum.py", 
line 81, in _thread_body
[2024-01-24T18:34:02.828Z]     filesystem.mkdir_exists_ok(os.path.dirname(path))
[2024-01-24T18:34:02.829Z]   File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\lib\filesystem.py", line 30, in mkdir_exists_ok
[2024-01-24T18:34:02.830Z]     os.makedirs(dir_name, exist_ok=True)
[2024-01-24T18:34:02.832Z]   File "<frozen os>", line 215, in makedirs
[2024-01-24T18:34:02.833Z]   File "<frozen os>", line 215, in makedirs
[2024-01-24T18:34:02.834Z]   File "<frozen os>", line 215, in makedirs
[2024-01-24T18:34:02.835Z]   [Previous line repeated 7 more times]
[2024-01-24T18:34:02.836Z]   File "<frozen os>", line 225, in makedirs
[2024-01-24T18:34:02.837Z] FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\me\\AppData\\Local\\Temp\\tmpcl35an_vwandb\\zhpqp9ix-../AppData'
```

### Environment

WandB version: 0.16.2

OS: Windows 10 Enterprise 

Python version: 3.11.4

Versions of relevant libraries:

**Comment by dsaffie** [comment]
> Hey @dsaffie, thanks for reporting this! Would you mind sharing if this happened after upgrading the `wandb` package or has it always been the case?

@ luisbergua the issue ended up being setting the `save_code` flag to `True` in `init()`

**Comment by luisbergua** [comment]
Thanks for confirming this @dsaffie!

**Comment by Firestorm-253** [comment]
i have the same error when starting up:

wandb: Currently logged in as: firestorm to http://192.168.21.135:8080. Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.19.7.dev1
wandb: Run data is saved locally in C:\Ungesichert\wandb\temp\wandb\run-20250227_141503-3lcjg33w
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run run_006
wandb:  View project at http://192.168.21.135:8080/firestorm/test
wandb:  View run at http://192.168.21.135:8080/firestorm/test/runs/3lcjg33w
Exception in thread Thread-14:
Traceback (most recent call last):
  File "C:\Users\****\AppData\Local\miniconda3\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\****\AppData\Local\miniconda3\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\****\AppData\Local\miniconda3\lib\site-packages\wandb\filesync\step_checksum.py", line 80, in _thread_body
    filesystem.mkdir_exists_ok(os.path.dirname(path))
  File "C:\Users\****\AppData\Local\miniconda3\lib\site-packages\wandb\sdk\lib\filesystem.py", line 30, in mkdir_exists_ok
    os.makedirs(dir_name, exist_ok=True)
  File "C:\Users\****\AppData\Local\miniconda3\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] Das System kann den angegebenen Pfad nicht finden: 'C:\\Ungesichert\\wandb\\temp\\tmpiq8thtiuwandb\\4b0a6k9j-../Ungesichert'

**Comment by Firestorm-253** [comment]
`wandb.require("legacy-service")
os.environ["WANDB_API_KEY"] = "local-6d6b62c020d7dee35669db9eaf1b2d0523c7107f"
os.environ["TEMP"] = "C:\\Ungesichert\\wandb\\temp"
os.environ['WANDB_DIR'] = "C:\\Ungesichert\\wandb\\temp"
os.makedirs(os.environ["TEMP"], exist_ok=True)


# start a new wandb run to track this script
wandb.init(
    # set the wandb project where this run will be logged
    project="test",

    # track hyperparameters and run metadata
    config={
    "learning_rate": 0.02,
    "architecture": "CNN",
    "dataset": "CIFAR-100",
    "epochs": 10,
    },
    name="run_006",
    reinit=True,
    save_code=True
)`

**Comment by Firestorm-253** [comment]
after further testing i realise that the bug seems to arrise but doesn't block the program from running up until the point of wandb.finish() where it gets stuck:

```python
print("1")
wandb.log({
    "array_chart": wandb.plot.line(table, x="step", y="value", title="my chart")
})
print("2")
wandb.finish()
print("3")
```

output:
FileNotFoundError: [WinError 3] Das System kann den angegebenen Pfad nicht finden: 'C:\\Ungesichert\\wandb\\temp\\tmpyzcekxqbwandb\\v8aqcqhx-../Ungesichert'
1
2
