### ISSUE TITLE
[Q]Network error (ReadTimeout), entering retry loop

### ISSUE THREAD

**Issue by arandinglv** [wandb/wandb#7086]
I have came across this question for a long time. Could you provide a solution? 
`wandb: Currently logged in as: arandinglv (arandinglv_). Use `wandb login --relogin` to force relogin
wandb: Network error (ReadTimeout), entering retry loop.
Problem at: /root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loggers/wandb.py 357 experiment
wandb: ERROR Run initialization has timed out after 90.0 sec. 
wandb: ERROR Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "run.py", line 483, in <module>
    typer.run(main)
  File "/root/miniconda3/lib/python3.8/site-packages/typer/main.py", line 864, in run
    app()
  File "/root/miniconda3/lib/python3.8/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/root/miniconda3/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/miniconda3/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "run.py", line 462, in main
    wandb_logger = WandbLogger()
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loggers/wandb.py", line 311, in __init__
    _ = self.experiment
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loggers/base.py", line 41, in experiment
    return get_experiment() or DummyExperiment()
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/rank_zero.py", line 32, in wrapped_fn
    return fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loggers/base.py", line 39, in get_experiment
    return fn(self)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_lightning/loggers/wandb.py", line 357, in experiment
    self._experiment = wandb.init(**self._wandb_init)
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1195, in init
    raise e
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/root/miniconda3/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process`

**Comment by fmamberti-wandb** [comment]
Hi @arandinglv, sorry to hear you are experiencing this issue.

Would you mind providing some additional information regarding your setup and the code you are running when seeing this error:

- What version of the SDK do you have installed?
- Are you seeing this error when running `wandb.init()` or `wandb.finish()`?
- Are you running your code in a Jupyter Notebook / Colab or via a script?
- Are you running your code locally on your device or in a remote environment? 

If you are seeing this while running `wandb.init()` or `wandb.finish()` especially in a Jupyter Notebook, you may be able to fix it running in a cell the following lines:

```
!for pid in $(ps -ef | grep wandb-service | grep -v grep | awk '{print $2}'); do kill -9 $pid;done # Kills any unresponsive wandb-service
wandb.teardown()
```

**Comment by fmamberti-wandb** [comment]
Hi @arandinglv, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by arandinglv** [comment]
> Hi @arandinglv, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

No, I have not solved this proble,. I have tried to offline training. After the training session, I followed the step "wandb sync /root/.../offline-run-xxx", but it generated the notice: "wandb: Network error (ReadTimeout), entering retry loop" without any response. Could you tell me how to solve this problem?

**Comment by arandinglv** [comment]
No, I have not solved this proble,. I have tried to offline training. After the training session, I followed the step "wandb sync /root/.../offline-run-xxx", but it generated the notice: "wandb: Network error (ReadTimeout), entering retry loop" without any response. Could you tell me how to solve this problem?

**Comment by fmamberti-wandb** [comment]
Hi @arandinglv, I'd be happy to help you troubleshoot this. Would you mind sharing some information that would help the investigation:

- What version of the wandb SDK do you have installed? You can find that out running `wandb --version`
- Could you share the `debug.log` and `debug-internal.log` files for the Run failing to sync? These should be in `./wandb/run-date_time-runid/logs`
- Can you try running `wandb login --relogin --cloud` to re-login with your account on the cloud instance and then try to log in a basic Run such as:

```
import wandb

wandb.init(project='test-run')

for i in range(10):
    wandb.log({"metric": i})
```

**Comment by fmamberti-wandb** [comment]
Hi @arandinglv, I wanted to check-in and see if you had the chance to test the steps mentioned in my previous message.

**Comment by fmamberti-wandb** [comment]
Hi @arandinglv, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
