### ISSUE TITLE
[CLI]: Error when running in Parellel with joblib on macOS

### ISSUE THREAD

**Issue by noahfarr** [wandb/wandb#7115]
### Describe the bug

I have to run multiple processes with Parallel from joblib but when I try to add logging with wandb it crashes. 

```python
from joblib import Parallel, delayed
import wandb


def foo(x):
    wandb.init()
    wandb.log({"val": 0})
    wandb.finish()


Parallel(n_jobs=2)(delayed(foo)(1) for i in range(2))

```

```shell
python mult.py 
Fatal Python error: init_sys_streams: can't initialize sys standard streams
Python runtime state: core initialized
OSError: [Errno 9] Bad file descriptor

Current thread 0x00000001dc095c40 (most recent call first):
  <no Python frame>
Fatal Python error: init_sys_streams: can't initialize sys standard streams
Python runtime state: core initialized
OSError: [Errno 9] Bad file descriptor

Current thread 0x00000001dc095c40 (most recent call first):
  <no Python frame>
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/noahfarr/Documents/thesis/reward-design/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py", line 463, in _process_worker
    r = call_item()
        ^^^^^^^^^^^
  File "/Users/noahfarr/Documents/thesis/reward-design/.venv/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py", line 291, in __call__
    return self.fn(*self.args, **self.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noahfarr/Documents/thesis/reward-design/.venv/lib/python3.12/site-packages/joblib/parallel.py", line 589, in __call__
    return [func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noahfarr/Documents/mult.py", line 6, in foo
    wandb.init()
  File "/Users/noahfarr/Documents/thesis/reward-design/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1195, in init
    raise e
  File "/Users/noahfarr/Documents/thesis/reward-design/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1172, in init
    wi.setup(kwargs)
  File "/Users/noahfarr/Documents/thesis/reward-design/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 189, in setup
    self._wl = wandb_setup.setup(settings=setup_settings)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noahfarr/Documents/thesis/reward-design/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_setup.py", line 327, in setup
    ret = _setup(settings=settings)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noahfarr/Documents/thesis/reward-design/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_setup.py", line 320, in _setup
    wl = _WandbSetup(settings=settings)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noahfarr/Documents/thesis/reward-design/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_setup.py", line 303, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noahfarr/Documents/thesis/reward-design/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_setup.py", line 114, in __init__
    self._setup()
  File "/Users/noahfarr/Documents/thesis/reward-design/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_setup.py", line 250, in _setup
    self._setup_manager()
  File "/Users/noahfarr/Documents/thesis/reward-design/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_setup.py", line 277, in _setup_manager
    self._manager = wandb_manager._Manager(settings=self._settings)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noahfarr/Documents/thesis/reward-design/.venv/lib/python3.12/site-packages/wandb/sdk/wandb_manager.py", line 139, in __init__
    self._service.start()
  File "/Users/noahfarr/Documents/thesis/reward-design/.venv/lib/python3.12/site-packages/wandb/sdk/service/service.py", line 250, in start
    self._launch_server()
  File "/Users/noahfarr/Documents/thesis/reward-design/.venv/lib/python3.12/site-packages/wandb/sdk/service/service.py", line 244, in _launch_server
    _sentry.reraise(e)
  File "/Users/noahfarr/Documents/thesis/reward-design/.venv/lib/python3.12/site-packages/wandb/analytics/sentry.py", line 154, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/Users/noahfarr/Documents/thesis/reward-design/.venv/lib/python3.12/site-packages/wandb/sdk/service/service.py", line 242, in _launch_server
    self._wait_for_ports(fname, proc=internal_proc)
  File "/Users/noahfarr/Documents/thesis/reward-design/.venv/lib/python3.12/site-packages/wandb/sdk/service/service.py", line 108, in _wait_for_ports
    raise ServiceStartProcessError(
wandb.sdk.service.service.ServiceStartProcessError: The wandb service process exited with 1. Ensure that `sys.executable` is a valid python interpreter. You can override it with the `_executable` setting or with the `WANDB__EXECUTABLE` environment variable.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/noahfarr/Documents/mult.py", line 11, in <module>
    Parallel(n_jobs=2)(delayed(foo)(1) for i in range(2))
  File "/Users/noahfarr/Documents/thesis/reward-design/.venv/lib/python3.12/site-packages/joblib/parallel.py", line 1952, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "/Users/noahfarr/Documents/thesis/reward-design/.venv/lib/python3.12/site-packages/joblib/parallel.py", line 1595, in _get_outputs
    yield from self._retrieve()
  File "/Users/noahfarr/Documents/thesis/reward-design/.venv/lib/python3.12/site-packages/joblib/parallel.py", line 1699, in _retrieve
    self._raise_error_fast()
  File "/Users/noahfarr/Documents/thesis/reward-design/.venv/lib/python3.12/site-packages/joblib/parallel.py", line 1734, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "/Users/noahfarr/Documents/thesis/reward-design/.venv/lib/python3.12/site-packages/joblib/parallel.py", line 736, in get_result
    return self._return_or_raise()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noahfarr/Documents/thesis/reward-design/.venv/lib/python3.12/site-packages/joblib/parallel.py", line 754, in _return_or_raise
    raise self._result
wandb.sdk.service.service.ServiceStartProcessError: The wandb service process exited with 1. Ensure that `sys.executable` is a valid python interpreter. You can override it with the `_executable` setting or with the `WANDB__EXECUTABLE` environment variable.
```

### Environment

WandB version: 0.16.4

OS: MacOS Sonoma 14.3.1

Python version: 3.11.7

Versions of relevant libraries:
joblib version: 1.3.2

### Additional Context

This is only happening for n_jobs > 1

**Comment by fmamberti-wandb** [comment]
Hi @noahfarr, thank you for surfacing this. I was able to repro on my side, I will be escalating this to our engineering team and we will keep you posted on the progress.

As a temporary workaround, I was able to have the code you provided running with python==3.10.13

**Comment by noahfarr** [comment]
Hi @fmamberti-wandb, do you have any update on this?
