### ISSUE TITLE
[App]: wandb.init fail(UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte)

### ISSUE THREAD

**Issue by feiji110** [wandb/wandb#7168]
### Current Behavior

```
Thread HandlerThread:wandb.init()...
Traceback (most recent call last):
  File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/wandb/sdk/internal/internal_util.py", line 49, in run
    self._run()
  File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/wandb/sdk/internal/internal_util.py", line 100, in _run
    self._process(record)
  File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/wandb/sdk/internal/internal.py", line 279, in _process
    self._hm.handle(record)
  File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/wandb/sdk/internal/handler.py", line 138, in handle
    handler(record)
  File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/wandb/sdk/internal/handler.py", line 148, in handle_request
    handler(record)
  File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/wandb/sdk/internal/handler.py", line 686, in handle_request_run_start
    self._system_monitor.probe(publish=True)
  File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/wandb/sdk/internal/system/system_monitor.py", line 217, in probe
    k: v for d in [asset.probe() for asset in self.assets] for k, v in d.items()
  File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/wandb/sdk/internal/system/system_monitor.py", line 217, in <listcomp>
    k: v for d in [asset.probe() for asset in self.assets] for k, v in d.items()
  File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/wandb/sdk/internal/system/assets/gpu.py", line 395, in probe
    info["gpu"] = pynvml.nvmlDeviceGetName(pynvml.nvmlDeviceGetHandleByIndex(0))  # type: ignore
  File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/wandb/vendor/pynvml/pynvml.py", line 1962, in wrapper
    return res.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte
wandb: ERROR Internal wandb error: file data was not synced
```

### Environment

OS: WSL2 Ubuntu

Browsers:

Version:

**Comment by umakrishnaswamy** [comment]
hey @feiji110 - what wandb SDK version are you using? Also, would it be possible to provide the following details? 
- environment set-up: GPU details, whether you're running this in any sort of distributed framework, etc. does this error occur when you spin up a fresh local environment and call wandb.init ?
- code snippet of your wandb.init call
- are you running this in a Jupyter notebook/python script?
- Any other details I could use to reproduce the behavior on my end - thanks!

**Comment by umakrishnaswamy** [comment]
Hi Angus, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please feel free to write back in

**Comment by Voldemort108X** [comment]
I am having the same issue. 

Python: 3.6
wandb: 0.13.10
GPU: RTX 2080 ti 
PyTorch: 0.10.0

Error message:
Thread HandlerThread:
Traceback (most recent call last):
  File "/home/xiaoranzhang/anaconda3/envs/optical_flow/lib/python3.6/site-packages/wandb/sdk/internal/internal_util.py", line 49, in run
    self._run()
  File "/home/xiaoranzhang/anaconda3/envs/optical_flow/lib/python3.6/site-packages/wandb/sdk/internal/internal_util.py", line 100, in _run
    self._process(record)
  File "/home/xiaoranzhang/anaconda3/envs/optical_flow/lib/python3.6/site-packages/wandb/sdk/internal/internal.py", line 280, in _process
    self._hm.handle(record)
  File "/home/xiaoranzhang/anaconda3/envs/optical_flow/lib/python3.6/site-packages/wandb/sdk/internal/handler.py", line 136, in handle
    handler(record)
  File "/home/xiaoranzhang/anaconda3/envs/optical_flow/lib/python3.6/site-packages/wandb/sdk/internal/handler.py", line 146, in handle_request
    handler(record)
  File "/home/xiaoranzhang/anaconda3/envs/optical_flow/lib/python3.6/site-packages/wandb/sdk/internal/handler.py", line 694, in handle_request_run_start
    self._system_monitor.probe(publish=True)
  File "/home/xiaoranzhang/anaconda3/envs/optical_flow/lib/python3.6/site-packages/wandb/sdk/internal/system/system_monitor.py", line 207, in probe
    k: v for d in [asset.probe() for asset in self.assets] for k, v in d.items()
  File "/home/xiaoranzhang/anaconda3/envs/optical_flow/lib/python3.6/site-packages/wandb/sdk/internal/system/system_monitor.py", line 207, in <listcomp>
    k: v for d in [asset.probe() for asset in self.assets] for k, v in d.items()
  File "/home/xiaoranzhang/anaconda3/envs/optical_flow/lib/python3.6/site-packages/wandb/sdk/internal/system/assets/gpu.py", line 353, in probe
    info["gpu"] = pynvml.nvmlDeviceGetName(pynvml.nvmlDeviceGetHandleByIndex(0))  # type: ignore
  File "/home/xiaoranzhang/anaconda3/envs/optical_flow/lib/python3.6/site-packages/wandb/vendor/pynvml/pynvml.py", line 1962, in wrapper
    return res.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte

**Comment by umakrishnaswamy** [comment]
hey @Voldemort108X - would it be possible to provide the following details:

- environment set-up: GPU details, whether you're running this in any sort of distributed framework, etc. does this error occur when you spin up a fresh local environment and call wandb.init ?
- code snippet of your wandb.init call
- are you running this in a Jupyter notebook/python script?
- Any other details I could use to reproduce the behavior on my end - thanks!

Additionally, do you reach this error upon upgrading wandb to the latest SDK? I noticed you are on a much older version

**Comment by Voldemort108X** [comment]
1. environment set-up: single GPU, no distributed framework
2. code snippet:
```
# wandb tracking experiments
run = wandb.init(
    # set the wandb project where this run will be logged
    project="echo_segmentation",
    
    # track hyperparameters and run metadata
    config={
    "learning_rate": args.lr,
    "architecture": "UNet",
    "dataset": args.dataset,
    "epochs": args.epochs,
    "batch_size": args.batch_size,
    "enc_nf": enc_nf,
    "dec_nf": dec_nf,
    "image-loss": args.image_loss,
    },

    # have a run name
    name = args.wandb_name
)
```
3. I am running this in a jupyter notebook but the same error can be reproduced in Python script.
4. I am also able to reproduce the same error in wandb=0.15..11.
5. The error does not seem to be related to the wandb.init snippet. I noticed that even if I just type break lines in code the same error will occur and deleting them will resolve the issue.

**Comment by Voldemort108X** [comment]
Any updates on this? @umakrishnaswamy thanks!

**Comment by Voldemort108X** [comment]
It does seem to be a compatibility issue. The following combination works out:

Python = 3.8
PyTorch = 1.12.0+cu102
cudatoolkit = 10.2
wandb = 0.16.5

The above packages can be installed using the following:
```
conda create -n myenv python=3.8
```
```
pip install torch==1.12.0+cu102 torchvision==0.13.0+cu102 torchaudio==0.12.0 --extra-index-url https://download.pytorch.org/whl/cu102
```
```
pip install wandb
```

**Comment by umakrishnaswamy** [comment]
thank you for letting us know! in general we recommend staying as up to date as possible with our latest SDK, so I am glad to hear this fixed the issue!

**Comment by 00-uno-00** [comment]
Same error presented to me aswell:

Python: 3.10.12
wandb: 0.17.0
PyTorch: 2.3.0
GPU: RTX 2060 SUPER

Error:
```
Traceback (most recent call last):
  File "/home/edo/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_util.py", line 48, in run
    self._run()
  File "/home/edo/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_util.py", line 99, in _run
    self._process(record)
  File "/home/edo/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal.py", line 278, in _process
    self._hm.handle(record)
  File "/home/edo/.local/lib/python3.10/site-packages/wandb/sdk/internal/handler.py", line 150, in handle
    handler(record)
  File "/home/edo/.local/lib/python3.10/site-packages/wandb/sdk/internal/handler.py", line 160, in handle_request
    handler(record)
  File "/home/edo/.local/lib/python3.10/site-packages/wandb/sdk/internal/handler.py", line 702, in handle_request_run_start
    self._system_monitor.probe(publish=True)
  File "/home/edo/.local/lib/python3.10/site-packages/wandb/sdk/internal/system/system_monitor.py", line 217, in probe
    k: v for d in [asset.probe() for asset in self.assets] for k, v in d.items()
  File "/home/edo/.local/lib/python3.10/site-packages/wandb/sdk/internal/system/system_monitor.py", line 217, in <listcomp>
    k: v for d in [asset.probe() for asset in self.assets] for k, v in d.items()
  File "/home/edo/.local/lib/python3.10/site-packages/wandb/sdk/internal/system/assets/gpu.py", line 395, in probe
    info["gpu"] = pynvml.nvmlDeviceGetName(pynvml.nvmlDeviceGetHandleByIndex(0))  # type: ignore
  File "/home/edo/.local/lib/python3.10/site-packages/wandb/vendor/pynvml/pynvml.py", line 1962, in wrapper
    return res.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte
```
It happened while running some experiments on [this](https://github.com/makgyver/fluke) framework, right after switching from local logging back to WanDB. The call to WanDB happens before the experiment run but after the initialization.
(note that while the framework is meant to simulate FedaratedLearning everything happens locally)

**Comment by simonusher** [comment]
Hi, I'm having the same issue
here's the trace:
```
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/home/swozniak/projects/kraina-ai/tf/.venv/lib/python3.10/site-packages/lightning/pytorch/trainer/configuration_validator.py:74: You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.
You are using a CUDA device ('NVIDIA GeForce RTX 4080') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
wandb: Currently logged in as: swozniak6 (pwr-spatial-lab). Use `wandb login --relogin` to force relogin
Thread HandlerThread:
Traceback (most recent call last):
  File "/home/swozniak/projects/kraina-ai/tf/.venv/lib/python3.10/site-packages/wandb/sdk/internal/internal_util.py", line 48, in run
    self._run()
  File "/home/swozniak/projects/kraina-ai/tf/.venv/lib/python3.10/site-packages/wandb/sdk/internal/internal_util.py", line 99, in _run
    self._process(record)
  File "/home/swozniak/projects/kraina-ai/tf/.venv/lib/python3.10/site-packages/wandb/sdk/internal/internal.py", line 278, in _process
    self._hm.handle(record)
  File "/home/swozniak/projects/kraina-ai/tf/.venv/lib/python3.10/site-packages/wandb/sdk/internal/handler.py", line 150, in handle
    handler(record)
  File "/home/swozniak/projects/kraina-ai/tf/.venv/lib/python3.10/site-packages/wandb/sdk/internal/handler.py", line 160, in handle_request
    handler(record)
  File "/home/swozniak/projects/kraina-ai/tf/.venv/lib/python3.10/site-packages/wandb/sdk/internal/handler.py", line 702, in handle_request_run_start
    self._system_monitor.probe(publish=True)
  File "/home/swozniak/projects/kraina-ai/tf/.venv/lib/python3.10/site-packages/wandb/sdk/internal/system/system_monitor.py", line 217, in probe
    k: v for d in [asset.probe() for asset in self.assets] for k, v in d.items()
  File "/home/swozniak/projects/kraina-ai/tf/.venv/lib/python3.10/site-packages/wandb/sdk/internal/system/system_monitor.py", line 217, in <listcomp>
    k: v for d in [asset.probe() for asset in self.assets] for k, v in d.items()
  File "/home/swozniak/projects/kraina-ai/tf/.venv/lib/python3.10/site-packages/wandb/sdk/internal/system/assets/gpu.py", line 395, in probe
    info["gpu"] = pynvml.nvmlDeviceGetName(pynvml.nvmlDeviceGetHandleByIndex(0))  # type: ignore
  File "/home/swozniak/projects/kraina-ai/tf/.venv/lib/python3.10/site-packages/wandb/vendor/pynvml/pynvml.py", line 1962, in wrapper
    return res.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte
wandb: ERROR Internal wandb error: file data was not synced
```
I'm running it from a jupyter notebook using the Lightning integration
```python
logger = WandbLogger(log_model="all")
trainer = Trainer(max_epochs=1, logger=logger)
trainer.fit(model, dataloader)
```
The versions:
- python 3.10.9
- wandb 0.17.0
- torch 2.3.0
- lightning 2.2.5
- GPU: RTX 4080

**Comment by ssslakter** [comment]
I also run into this issue. The error says the problem is in the `pynvml` library that is essentially python bindings to the NVIDIA Management Library, so I tried to test it without wandb, and it failed. Then I downgraded its version to 11.4.1
```sh
pip install pynvml==11.4.1
```
and tested this snippet once more.
```python
import pynvml
pynvml.nvmlInit()
pynvml.nvmlDeviceGetName(pynvml.nvmlDeviceGetHandleByIndex(0))
```
After downgrade it works fine, however in wandb it still results the same error. Also I tried to follow the stack and found that it seems that it's called in the `SystemMonitor` inside the `handle_request_run_start` method, but I didn't find any other usages of this methodapart from its definition and debugger doesn't pause on it's breakpoint as well. https://github.com/wandb/wandb/blob/9b7041a9f9d5e747c896166e3eea3891d5969d57/wandb/sdk/internal/handler.py#L695

**Comment by phucdev** [comment]
Take a look at this issue: https://github.com/wandb/wandb/issues/7683#issuecomment-2124952404
Downgrading the NVIDIA driver to 552.44 solved it for me and many people in the issue.
