### ISSUE TITLE
wandb: ERROR Error while calling W&B API: An internal error occurred. Please contact support. (<Response [500]>)

### ISSUE THREAD

**Issue by EduardDurech** [wandb/wandb#7267]
### Describe the bug

Same as #5372 but https://status.wandb.com/ does not show any problems

When running `wandb.init()` returns `wandb: ERROR Error while calling W&B API: An internal error occurred. Please contact support. (<Response [500]>)`

`debug.log` is normal
<details>
<summary>debug-internal.log shows "requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/graphql"</summary>

```
2024-03-30 17:51:31 INFO    StreamThr :33739 [internal.py:wandb_internal():86] W&B internal server running at pid: 33739, started at: 2024-03-30 17:51:31
2024-03-30 17:51:31 DEBUG   HandlerThread:33739 [handler.py:handle_request():146] handle_request: status
2024-03-30 17:51:31 INFO    WriterThread:33739 [datastore.py:open_for_write():87] open: foo/wandb/run-foo/run-foo_.wandb
2024-03-30 17:51:31 DEBUG   SenderThread:33739 [sender.py:send():379] send: header
2024-03-30 17:51:31 DEBUG   SenderThread:33739 [sender.py:send():379] send: run
2024-03-30 17:51:31 INFO    SenderThread:33739 [sender.py:_setup_resume():749] checking resume status for None/foo
2024-03-30 17:51:33 INFO    SenderThread:33739 [sender.py:_setup_resume():827] configured resuming with: ResumeState(resumed=True,step=0,history=0,events=37,output=4,runtime=foo,wandb_runtime=None,summary={},config={foo}},tags=[])
2024-03-30 17:51:34 INFO    SenderThread:33739 [dir_watcher.py:__init__():211] watching files in: foo/wandb/run-foo/files
2024-03-30 17:51:34 INFO    SenderThread:33739 [sender.py:_start_run_threads():1124] run started: foo with start time
2024-03-30 17:51:34 DEBUG   HandlerThread:33739 [handler.py:handle_request():146] handle_request: check_version
2024-03-30 17:51:34 DEBUG   SenderThread:33739 [sender.py:send_request():406] send_request: check_version
2024-03-30 17:51:34 DEBUG   HandlerThread:33739 [handler.py:handle_request():146] handle_request: run_start
2024-03-30 17:51:34 DEBUG   HandlerThread:33739 [system_info.py:__init__():26] System info init
2024-03-30 17:51:34 DEBUG   HandlerThread:33739 [system_info.py:__init__():41] System info init done
2024-03-30 17:51:34 INFO    HandlerThread:33739 [system_monitor.py:start():194] Starting system monitor
2024-03-30 17:51:34 INFO    SystemMonitor:33739 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-03-30 17:51:34 INFO    SystemMonitor:33739 [interfaces.py:start():190] Started cpu monitoring
2024-03-30 17:51:34 INFO    SystemMonitor:33739 [interfaces.py:start():190] Started disk monitoring
2024-03-30 17:51:34 INFO    SystemMonitor:33739 [interfaces.py:start():190] Started gpu monitoring
2024-03-30 17:51:34 INFO    SystemMonitor:33739 [interfaces.py:start():190] Started memory monitoring
2024-03-30 17:51:34 INFO    SystemMonitor:33739 [interfaces.py:start():190] Started network monitoring
2024-03-30 17:51:36 DEBUG   HandlerThread:33739 [handler.py:handle_request():146] handle_request: status_report
2024-03-30 17:51:38 DEBUG   HandlerThread:33739 [handler.py:handle_request():146] handle_request: python_packages
2024-03-30 17:51:38 DEBUG   HandlerThread:33739 [handler.py:handle_request():146] handle_request: stop_status
2024-03-30 17:51:38 DEBUG   SenderThread:33739 [sender.py:send_request():406] send_request: python_packages
2024-03-30 17:51:38 DEBUG   SenderThread:33739 [sender.py:send_request():406] send_request: stop_status
2024-03-30 17:51:38 DEBUG   HandlerThread:33739 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-30 17:51:38 DEBUG   HandlerThread:33739 [handler.py:handle_request():146] handle_request: log_artifact
2024-03-30 17:51:38 DEBUG   SenderThread:33739 [sender.py:send():379] send: telemetry
2024-03-30 17:51:38 DEBUG   SenderThread:33739 [sender.py:send_request():406] send_request: log_artifact
2024-03-30 17:51:38 DEBUG   HandlerThread:33739 [handler.py:handle_request():146] handle_request: pause
2024-03-30 17:51:38 INFO    HandlerThread:33739 [handler.py:handle_request_pause():708] stopping system metrics thread
2024-03-30 17:51:38 INFO    HandlerThread:33739 [system_monitor.py:finish():203] Stopping system monitor
2024-03-30 17:51:38 DEBUG   SystemMonitor:33739 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-03-30 17:51:38 INFO    HandlerThread:33739 [interfaces.py:finish():202] Joined cpu monitor
2024-03-30 17:51:38 DEBUG   SystemMonitor:33739 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-03-30 17:51:38 INFO    HandlerThread:33739 [interfaces.py:finish():202] Joined disk monitor
2024-03-30 17:51:38 DEBUG   SystemMonitor:33739 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-03-30 17:51:38 INFO    HandlerThread:33739 [interfaces.py:finish():202] Joined gpu monitor
2024-03-30 17:51:38 INFO    HandlerThread:33739 [interfaces.py:finish():202] Joined memory monitor
2024-03-30 17:51:38 INFO    HandlerThread:33739 [interfaces.py:finish():202] Joined network monitor
2024-03-30 17:51:38 ERROR   SenderThread:33739 [internal_api.py:execute():373] 500 response executing GraphQL.
2024-03-30 17:51:38 ERROR   SenderThread:33739 [internal_api.py:execute():374] {"errors":[{"message":"An internal error occurred. Please contact support.","path":["createArtifactManifest"]}],"data":{"createArtifactManifest":null}}
2024-03-30 17:51:39 INFO    Thread-12 :33739 [dir_watcher.py:_on_file_created():271] file/dir created: foo/wandb/run-foo/files/requirements.txt
2024-03-30 17:51:40 ERROR   SenderThread:33739 [internal_api.py:execute():373] 500 response executing GraphQL.
2024-03-30 17:51:40 ERROR   SenderThread:33739 [internal_api.py:execute():374] {"errors":[{"message":"An internal error occurred. Please contact support.","path":["createArtifactManifest"]}],"data":{"createArtifactManifest":null}}
2024-03-30 17:51:42 ERROR   SenderThread:33739 [internal_api.py:execute():373] 500 response executing GraphQL.
2024-03-30 17:51:42 ERROR   SenderThread:33739 [internal_api.py:execute():374] {"errors":[{"message":"An internal error occurred. Please contact support.","path":["createArtifactManifest"]}],"data":{"createArtifactManifest":null}}
2024-03-30 17:51:42 INFO    SenderThread:33739 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/graphql
2024-03-30 17:51:47 ERROR   SenderThread:33739 [internal_api.py:execute():373] 500 response executing GraphQL.
2024-03-30 17:51:47 ERROR   SenderThread:33739 [internal_api.py:execute():374] {"errors":[{"message":"An internal error occurred. Please contact support.","path":["createArtifactManifest"]}],"data":{"createArtifactManifest":null}}
2024-03-30 17:51:53 DEBUG   HandlerThread:33739 [handler.py:handle_request():146] handle_request: stop_status
2024-03-30 17:51:53 DEBUG   HandlerThread:33739 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-30 17:51:56 ERROR   SenderThread:33739 [internal_api.py:execute():373] 500 response executing GraphQL.
2024-03-30 17:51:56 ERROR   SenderThread:33739 [internal_api.py:execute():374] {"errors":[{"message":"An internal error occurred. Please contact support.","path":["createArtifactManifest"]}],"data":{"createArtifactManifest":null}}
2024-03-30 17:51:58 DEBUG   HandlerThread:33739 [handler.py:handle_request():146] handle_request: keepalive
2024-03-30 17:52:03 DEBUG   HandlerThread:33739 [handler.py:handle_request():146] handle_request: keepalive
2024-03-30 17:52:08 DEBUG   HandlerThread:33739 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-30 17:52:13 DEBUG   HandlerThread:33739 [handler.py:handle_request():146] handle_request: keepalive
2024-03-30 17:52:14 ERROR   SenderThread:33739 [internal_api.py:execute():373] 500 response executing GraphQL.
2024-03-30 17:52:14 ERROR   SenderThread:33739 [internal_api.py:execute():374] {"errors":[{"message":"An internal error occurred. Please contact support.","path":["createArtifactManifest"]}],"data":{"createArtifactManifest":null}}
```
</details>

### Environment

WandB version: 0.16.5

OS: Ubuntu 22.04.4

**Comment by liubaoryol** [comment]
I have the same problem

**Comment by ymtricks** [comment]
I also encountered internal errors, but it appears to be fine now.

**Comment by MBakirWB** [comment]
Hi @EduardDurech & @liubaoryol , thank you for flagging this. We did have a minor incident over the weekend that was contributing. Are you still seeing any errors when logging videos?

**Comment by liubaoryol** [comment]
No, it's working now. Thank you!

**Comment by kptkin** [comment]
closing as it seems to be resolved now.
