### ISSUE TITLE
ConnectionRefusedError: [Errno 111] Connection refused and wandb.sdk.wandb_manager.ManagerConnectionRefusedError: Connection to wandb service failed since the process is not available. 

### ISSUE THREAD

**Issue by DavidoF3** [wandb/wandb#7329]
### Describe the bug

I am trying to resume a wandb run on a SLURM job, by running:

```
run = wandb.init(
        entity=entity,
        project=project,
        id=<id_of_run>,
        resume="must",
    )
```
I pass my API key with `export WANDB_API_KEY=` in the sbatch script (based on other issues).

I get the errors below:

```shell
Traceback (most recent call last):
  File "/rds/project/rds-pRsZozWgfxI/user_files/doc_files/repos/octiocor-train-segmenter/venv_noapp/lib/python3.9/site-packages/wandb/sdk/wandb_manager.py", line 116, in _service_connect
    svc_iface._svc_connect(port=port)
  File "/rds/project/rds-pRsZozWgfxI/user_files/doc_files/repos/octiocor-train-segmenter/venv_noapp/lib/python3.9/site-packages/wandb/sdk/service/service_sock.py", line 30, in _svc_connect
    self._sock_client.connect(port=port)
  File "/rds/project/rds-pRsZozWgfxI/user_files/doc_files/repos/octiocor-train-segmenter/venv_noapp/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 102, in connect
    s.connect(("localhost", port))
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/rds/project/rds-pRsZozWgfxI/user_files/doc_files/repos/octiocor-train-segmenter/venv_noapp/lib/python3.9/site-packages/versiontools/wandb_utils.py", line 65, in resume_wandb_run
    run = instanciate_resume_run(
  File "/rds/project/rds-pRsZozWgfxI/user_files/doc_files/repos/octiocor-train-segmenter/venv_noapp/lib/python3.9/site-packages/versiontools/wandb_utils.py", line 48, in instanciate_resume_run
    wandb.setup(settings=dict(_executable=sys.executable))
  File "/rds/project/rds-pRsZozWgfxI/user_files/doc_files/repos/octiocor-train-segmenter/venv_noapp/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 327, in setup
    ret = _setup(settings=settings)
  File "/rds/project/rds-pRsZozWgfxI/user_files/doc_files/repos/octiocor-train-segmenter/venv_noapp/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 320, in _setup
    wl = _WandbSetup(settings=settings)
  File "/rds/project/rds-pRsZozWgfxI/user_files/doc_files/repos/octiocor-train-segmenter/venv_noapp/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 303, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/rds/project/rds-pRsZozWgfxI/user_files/doc_files/repos/octiocor-train-segmenter/venv_noapp/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 114, in __init__
    self._setup()
  File "/rds/project/rds-pRsZozWgfxI/user_files/doc_files/repos/octiocor-train-segmenter/venv_noapp/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 250, in _setup
    self._setup_manager()
  File "/rds/project/rds-pRsZozWgfxI/user_files/doc_files/repos/octiocor-train-segmenter/venv_noapp/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 277, in _setup_manager
    self._manager = wandb_manager._Manager(settings=self._settings)
  File "/rds/project/rds-pRsZozWgfxI/user_files/doc_files/repos/octiocor-train-segmenter/venv_noapp/lib/python3.9/site-packages/wandb/sdk/wandb_manager.py", line 153, in __init__
    wandb._sentry.reraise(e)
  File "/rds/project/rds-pRsZozWgfxI/user_files/doc_files/repos/octiocor-train-segmenter/venv_noapp/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 154, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/rds/project/rds-pRsZozWgfxI/user_files/doc_files/repos/octiocor-train-segmenter/venv_noapp/lib/python3.9/site-packages/wandb/sdk/wandb_manager.py", line 151, in __init__
    self._service_connect()
  File "/rds/project/rds-pRsZozWgfxI/user_files/doc_files/repos/octiocor-train-segmenter/venv_noapp/lib/python3.9/site-packages/wandb/sdk/wandb_manager.py", line 125, in _service_connect
    raise ManagerConnectionRefusedError(message)
wandb.sdk.wandb_manager.ManagerConnectionRefusedError: Connection to wandb service failed since the process is not available. 
```

### Environment

WandB version: 0.16.3

OS: Linux Rocky

Python version: 3.9.17

Versions of relevant libraries:

**Comment by thanos-wandb** [comment]
Hi @DavidoF3 thank you for reporting this issue, and apologies for the delayed response. Is this issue still occurring for you? Could you please confirm if the node where you're executing this job has internet access or if there are any firewall configurations that might be affecting connectivity? Are you able to create new online runs, or are you running offline and syncing later? Additionally, could you please share the [SDK debug logs](https://docs.wandb.ai/guides/technical-faq/admin#which-files-should-i-check-when-my-code-crashes) for further review? This will help us diagnose and resolve the issue more effectively.

**Comment by thanos-wandb** [comment]
Hi @DavidoF3 we wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by thanos-wandb** [comment]
Hi @DavidoF3 since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know, and we will be more than happy to assist you!

**Comment by ff781** [comment]
Hi I also face this problem when submitting a job to slurm, when the node just has to run a normal run (wandb.init() called) it all works fine, but when I run the agent in the slurm job I get this error as well (wandb.agent() called)
