### ISSUE TITLE
[CLI]: ChunkedEncodingError: Response ended prematurely

### ISSUE THREAD

**Issue by 2er0** [wandb/wandb#7358]
### Describe the bug

Downloading metadata to experiments via the Python API results in an error.
The table download to CSV button in the web UI only provides some of the runs but not all.

Increasing the timeout has helped in the past, but not anymore.

```python
from time import sleep
import pandas as pd
import wandb
from requests.exceptions import ChunkedEncodingError

from urllib3.exceptions import ProtocolError

values_of_interest = ['name']
additional_of_interest = ['VUS_ROC', 'AUC_ROC']


def crawl(id_list: list, config_list: list, name_list: list):
    api = wandb.Api(timeout=80)

    # Project is specified by <entity/project-name>
    runs = api.runs("<entity/project-name>", per_page=50)

    for run in runs:
        if run.id in id_list:
            continue
        id_list.append(run.id)
        if len(id_list) % 100 == 0:
            print(f"Processed {len(id_list)} runs")

        # .config contains the hyperparameters.
        c = dict(run.config)
        cs = {k: c.get(k, None) for k in values_of_interest}
        cs['id'] = run.id

        for mode in ['test']:
            c_model = c.get(mode, None)
            if c_model is None:
                continue
            for metric in additional_of_interest:
                cs[f'{mode}.{metric}'] = c_model.get(metric, None)

        config_list.append(cs)

        name_list.append(run.name)

    runs_df = pd.DataFrame({
        "id": id_list,
        "name": name_list,
        # "metadata": metadata_list,
        "config": config_list,
    })

    runs_df.to_csv("project.csv", index=False)
    return True


def repeated_crawl():
    no_update_counter = 0
    id_list, config_list, name_list = [], [], []
    id_count = 0
    while True:
        try:
            id_count = len(id_list)
            if crawl(id_list, config_list, name_list):
                print("Crawling successful")
                break
        except ChunkedEncodingError as e:
            print(e)
            print("ChunkedEncodingError")
        except ProtocolError as e:
            print(e)
            print("ProtocolError")
        finally:
            print(f"Current id count: {len(id_list)}")
            if id_count == len(id_list):
                no_update_counter += 1
            else:
                no_update_counter = 0

            if no_update_counter > 10:
                break
            sleep(5)


if __name__ == '__main__':
    repeated_crawl()
```

```shell
Traceback (most recent call last):
  File "…envs/CleanTimeFlow/lib/python3.10/site-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "…/envs/CleanTimeFlow/lib/python3.10/site-packages/urllib3/response.py", line 1040, in stream
    yield from self.read_chunked(amt, decode_content=decode_content)
  File "…/envs/CleanTimeFlow/lib/python3.10/site-packages/urllib3/response.py", line 1184, in read_chunked
    self._update_chunk_length()
  File "…/envs/CleanTimeFlow/lib/python3.10/site-packages/urllib3/response.py", line 1119, in _update_chunk_length
    raise ProtocolError("Response ended prematurely") from None
urllib3.exceptions.ProtocolError: Response ended prematurely

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "…/wandb-crawling.py", line 127, in repeated_crawl
    if crawl(id_list, config_list, name_list):
  File "wandb-crawling.py", line 71, in crawl
    for run in runs:
  File "…/envs/CleanTimeFlow/lib/python3.10/site-packages/wandb/apis/paginator.py", line 75, in __next__
    if not self._load_page():
  File "…/envs/CleanTimeFlow/lib/python3.10/site-packages/wandb/apis/paginator.py", line 59, in _load_page
    self.last_response = self.client.execute(
  File "…/envs/CleanTimeFlow/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "…/envs/CleanTimeFlow/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "…/envs/CleanTimeFlow/lib/python3.10/site-packages/wandb/apis/public/api.py", line 73, in execute
    return self._client.execute(*args, **kwargs)
  File "…/envs/CleanTimeFlow/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "…/envs/CleanTimeFlow/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "…/envs/CleanTimeFlow/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
  File "…/envs/CleanTimeFlow/lib/python3.10/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "…/envs/CleanTimeFlow/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "…/envs/CleanTimeFlow/lib/python3.10/site-packages/requests/sessions.py", line 747, in send
    r.content
  File "…/envs/CleanTimeFlow/lib/python3.10/site-packages/requests/models.py", line 899, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
  File "…/envs/CleanTimeFlow/lib/python3.10/site-packages/requests/models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: Response ended prematurely
```

### Environment

WandB version: 0.16.4

OS: MacOS Sonoma 14.4.1

Python version: 3.10

Versions of relevant libraries: -

**Comment by ArtsiomWB** [comment]
Hi @2er0! Thank you for writing in!

What particular metadata do you usually need to pull from wandb API. Could you please provide a workspace where you are seeing a behavior of the table download button as cvs not downloading all runs?

**Comment by ArtsiomWB** [comment]
Hi there, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by 2er0** [comment]
The issue still exists.
I have one workspace where it works and one where the error above occurs:
- not working: `timeflow/timeflow-mTADS-4-idun-real`
- working: `timeflow/timeflow-mTADS-2-idun`

**Comment by ArtsiomWB** [comment]
Thank you for sending over the example workspaces, that is very helpful. 

When you run your script above, does it crash right away, or after pulling some data from wandb?

**Comment by 2er0** [comment]
The script pulls ~117 runs and then gets the error seen above.

**Comment by ArtsiomWB** [comment]
Hi @2er0, apologies it took a while to get back to you, this thread got completely burried. What would you like your CSV to look like while pulling it from the API? 

Also does it always error out at run 117?

**Comment by 2er0** [comment]
I was able to collect the results in a different way. We can close this issue from my side.
I'm not pulling a CSV via the API.
