### ISSUE TITLE
[CLI]: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte

### ISSUE THREAD

**Issue by j-v-n** [wandb/wandb#7683]
### Describe the bug

My project which was working fine yesterday, all of a sudden started giving me the following error. Background: It is an MLflow + Wandb MLOps project and currently it is failing before even the first component is run. I have verified it ran end-to-end without an issue yesterday. The only other update is that I updated my gpu drivers this morning, but none of the ML components actually use the gpu

Traceback is below
```
wandb: Currently logged in as: jayanthnair. Use `wandb login --relogin` to force relogin
Thread HandlerThread:
Traceback (most recent call last):
  File "/home/jayanth/miniforge3/envs/mlflow-1241d4075b866d96a3aec6de7b419e2247f88fe6/lib/python3.12/site-packages/wandb/sdk/internal/internal_util.py", line 48, in run
    self._run()
  File "/home/jayanth/miniforge3/envs/mlflow-1241d4075b866d96a3aec6de7b419e2247f88fe6/lib/python3.12/site-packages/wandb/sdk/internal/internal_util.py", line 99, in _run
    self._process(record)
  File "/home/jayanth/miniforge3/envs/mlflow-1241d4075b866d96a3aec6de7b419e2247f88fe6/lib/python3.12/site-packages/wandb/sdk/internal/internal.py", line 278, in _process
    self._hm.handle(record)
  File "/home/jayanth/miniforge3/envs/mlflow-1241d4075b866d96a3aec6de7b419e2247f88fe6/lib/python3.12/site-packages/wandb/sdk/internal/handler.py", line 150, in handle
    handler(record)
  File "/home/jayanth/miniforge3/envs/mlflow-1241d4075b866d96a3aec6de7b419e2247f88fe6/lib/python3.12/site-packages/wandb/sdk/internal/handler.py", line 160, in handle_request
    handler(record)
  File "/home/jayanth/miniforge3/envs/mlflow-1241d4075b866d96a3aec6de7b419e2247f88fe6/lib/python3.12/site-packages/wandb/sdk/internal/handler.py", line 702, in handle_request_run_start
    self._system_monitor.probe(publish=True)
  File "/home/jayanth/miniforge3/envs/mlflow-1241d4075b866d96a3aec6de7b419e2247f88fe6/lib/python3.12/site-packages/wandb/sdk/internal/system/system_monitor.py", line 217, in probe
    k: v for d in [asset.probe() for asset in self.assets] for k, v in d.items()
                   ^^^^^^^^^^^^^
  File "/home/jayanth/miniforge3/envs/mlflow-1241d4075b866d96a3aec6de7b419e2247f88fe6/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu.py", line 395, in probe
    info["gpu"] = pynvml.nvmlDeviceGetName(pynvml.nvmlDeviceGetHandleByIndex(0))  # type: ignore
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jayanth/miniforge3/envs/mlflow-1241d4075b866d96a3aec6de7b419e2247f88fe6/lib/python3.12/site-packages/wandb/vendor/pynvml/pynvml.py", line 1962, in wrapper
    return res.decode()
           ^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte
wandb: ERROR Internal wandb error: file data was not synced
wandb: ERROR transport failed
Traceback (most recent call last):
  File "/mnt/c/Users/jynth/Documents/xxxxxxxxxx/model_inference/data_pull/run.py", line 104, in <module>
    go(args)
  File "/mnt/c/Users/jynth/Documents/xxxxxxxxxx/model_inference/data_pull/run.py", line 26, in go
    run = wandb.init(job_type="data_pull")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jayanth/miniforge3/envs/mlflow-1241d4075b866d96a3aec6de7b419e2247f88fe6/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1178, in init
    wandb._sentry.reraise(e)
  File "/home/jayanth/miniforge3/envs/mlflow-1241d4075b866d96a3aec6de7b419e2247f88fe6/lib/python3.12/site-packages/wandb/analytics/sentry.py", line 155, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/jayanth/miniforge3/envs/mlflow-1241d4075b866d96a3aec6de7b419e2247f88fe6/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
           ^^^^^^^^^
  File "/home/jayanth/miniforge3/envs/mlflow-1241d4075b866d96a3aec6de7b419e2247f88fe6/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 808, in init
    run_start_result = run_start_handle.wait(timeout=30)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jayanth/miniforge3/envs/mlflow-1241d4075b866d96a3aec6de7b419e2247f88fe6/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 281, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed
wandb: While tearing down the service manager. The following error has occurred: [Errno 32] Broken pipe
Error executing job with overrides: []
Traceback (most recent call last):
  File "/mnt/c/Users/jynth/Documents/xxxxxxxxxx/model_inference/main.py", line 135, in <module>
    go()
  File "/home/jayanth/miniforge3/envs/mlflow-bdab075c5b1921673316d0297f84520597576a1c/lib/python3.12/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/jayanth/miniforge3/envs/mlflow-bdab075c5b1921673316d0297f84520597576a1c/lib/python3.12/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/jayanth/miniforge3/envs/mlflow-bdab075c5b1921673316d0297f84520597576a1c/lib/python3.12/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/jayanth/miniforge3/envs/mlflow-bdab075c5b1921673316d0297f84520597576a1c/lib/python3.12/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/jayanth/miniforge3/envs/mlflow-bdab075c5b1921673316d0297f84520597576a1c/lib/python3.12/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
           ^^^^^^
  File "/home/jayanth/miniforge3/envs/mlflow-bdab075c5b1921673316d0297f84520597576a1c/lib/python3.12/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
            ^^^^^^^^^^
  File "/home/jayanth/miniforge3/envs/mlflow-bdab075c5b1921673316d0297f84520597576a1c/lib/python3.12/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
        ^^^^^^^^^^^^^^^^
  File "/home/jayanth/miniforge3/envs/mlflow-bdab075c5b1921673316d0297f84520597576a1c/lib/python3.12/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/jayanth/miniforge3/envs/mlflow-bdab075c5b1921673316d0297f84520597576a1c/lib/python3.12/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/jynth/Documents/xxxxxxxxxx/model_inference/main.py", line 24, in go
    _ = mlflow.run(
        ^^^^^^^^^^^
  File "/home/jayanth/miniforge3/envs/mlflow-bdab075c5b1921673316d0297f84520597576a1c/lib/python3.12/site-packages/mlflow/projects/__init__.py", line 361, in run
    _wait_for(submitted_run_obj)
  File "/home/jayanth/miniforge3/envs/mlflow-bdab075c5b1921673316d0297f84520597576a1c/lib/python3.12/site-packages/mlflow/projects/__init__.py", line 378, in _wait_for
    raise ExecutionException(f"Run (ID '{run_id}') failed")
mlflow.exceptions.ExecutionException: Run (ID 'fb63b7f74f9742c4aced4a906222ed0b') failed
2024/05/21 14:11:28 ERROR mlflow.cli: === Run (ID '610cced98a694febad77d372c1d593e2') failed ===
```

### Additional Files

[debug.log](https://github.com/wandb/wandb/files/15394585/debug.log)
[debug-internal.log](https://github.com/wandb/wandb/files/15394589/debug-internal.log)

### Environment

WandB version: 0.17.0

OS: Windows (WSL2)

Python version: 3.8.19

Versions of relevant libraries: mlflow==2.13.0, torch==1.12.0+cu102, torchvision=0.13.0+cu102, protobuf==4.25.3

**Comment by Aricept094** [comment]
I've recently started experiencing the same exact issue that I suspect is related to a recent NVIDIA driver update. Yesterday, I updated my NVIDIA driver to version 555.85, and since then, I've been encountering errors in both Ray Tune and wand.

Initially, I encountered the error in Ray Tune, but after modifying the nvidia_gpu.py file in python3.11/site-packages/ray/_private/accelerators/ to use Latin-1 encoding instead of UTF-8, I was able to get my Ray Tune project working again. The modified code is as follows:

try:
    pynvml.nvmlInit()
except pynvml.NVMLError:
    return None  # pynvml init failed
device_count = pynvml.nvmlDeviceGetCount()
cuda_device_type = None
if device_count > 0:
    handle = pynvml.nvmlDeviceGetHandleByIndex(0)
    device_name = pynvml.nvmlDeviceGetName(handle)
    if isinstance(device_name, bytes):
        device_name = device_name.decode("latin1")  # Changed from "utf-8" to "latin1"
    cuda_device_type = (
        NvidiaGPUAcceleratorManager._gpu_name_to_accelerator_type(device_name)
    )
pynvml.nvmlShutdown()
return cuda_device_type

However, I'm still experiencing issues with W&B, where I'm receiving errors and my metrics are not being monitored as intended.

**Comment by Aricept094** [comment]
same here , worked.

**Comment by rjavierch** [comment]
> Update: I fixed my issue by rolling back my Nvidia driver to 552.44 and restarting my machine.

I second this, downgraded to the Nvidia 552.44 studio driver, it and now is working again.

**Comment by j-v-n** [comment]
Has anyone tested out if it's safe to update the driver now?

**Comment by boyden** [comment]
I encounter the same issue and downgrading to the Nvidia 552.44 also works for me.

**Comment by Aricept094** [comment]
The latest nvidia driver works fine , no need to downgrade anymore.

**Comment by boyden** [comment]
Thanks. I rechecked my env and found that the driver versions 555.85, 555.99, and 556.12 do not work for me: the latest version and versions less than 552.44 all work fine.

**Comment by Aricept094** [comment]
> Thanks. I rechecked my env and found that the driver versions 555.85, 555.99, and 556.12 do not work for me: the latest version and versions less than 552.44 all work fine.

Update to this version , it should work 

https://github.com/ray-project/ray/issues/45492#issuecomment-2237850762
