### ISSUE TITLE
[Q] UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte

### ISSUE THREAD

**Issue by CYYJL** [wandb/wandb#7770]
Hi，when I run my code, I meet this strange problem, looks like there was a problem getting the gpu I have't effective method.

```
Thread HandlerThread:
Traceback (most recent call last):
  File "/home/yjl/anaconda3/envs/VMUnet/lib/python3.10/site-packages/wandb/sdk/internal/internal_util.py", line 48, in run
    self._run()
  File "/home/yjl/anaconda3/envs/VMUnet/lib/python3.10/site-packages/wandb/sdk/internal/internal_util.py", line 99, in _run
    self._process(record)
  File "/home/yjl/anaconda3/envs/VMUnet/lib/python3.10/site-packages/wandb/sdk/internal/internal.py", line 278, in _process
    self._hm.handle(record)
  File "/home/yjl/anaconda3/envs/VMUnet/lib/python3.10/site-packages/wandb/sdk/internal/handler.py", line 150, in handle
    handler(record)
  File "/home/yjl/anaconda3/envs/VMUnet/lib/python3.10/site-packages/wandb/sdk/internal/handler.py", line 160, in handle_request
    handler(record)
  File "/home/yjl/anaconda3/envs/VMUnet/lib/python3.10/site-packages/wandb/sdk/internal/handler.py", line 702, in handle_request_run_start
    self._system_monitor.probe(publish=True)
  File "/home/yjl/anaconda3/envs/VMUnet/lib/python3.10/site-packages/wandb/sdk/internal/system/system_monitor.py", line 217, in probe
    k: v for d in [asset.probe() for asset in self.assets] for k, v in d.items()
  File "/home/yjl/anaconda3/envs/VMUnet/lib/python3.10/site-packages/wandb/sdk/internal/system/system_monitor.py", line 217, in <listcomp>
    k: v for d in [asset.probe() for asset in self.assets] for k, v in d.items()
  File "/home/yjl/anaconda3/envs/VMUnet/lib/python3.10/site-packages/wandb/sdk/internal/system/assets/gpu.py", line 395, in probe
    info["gpu"] = pynvml.nvmlDeviceGetName(pynvml.nvmlDeviceGetHandleByIndex(0))  # type: ignore
  File "/home/yjl/anaconda3/envs/VMUnet/lib/python3.10/site-packages/wandb/vendor/pynvml/pynvml.py", line 1962, in wrapper
    return res.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte
wandb: ERROR Internal wandb error: file data was not synced
wandb: ERROR transport failed
Traceback (most recent call last):
  File "/mnt/d/AIPRO/VM-UNet-main/train.py", line 268, in <module>
    main(config)
  File "/mnt/d/AIPRO/VM-UNet-main/train.py", line 133, in main
    run_wandb = wandb.init(
  File "/home/yjl/anaconda3/envs/VMUnet/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1185, in init
    wandb._sentry.reraise(e)
  File "/home/yjl/anaconda3/envs/VMUnet/lib/python3.10/site-packages/wandb/analytics/sentry.py", line 155, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/yjl/anaconda3/envs/VMUnet/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1171, in init
    return wi.init()
  File "/home/yjl/anaconda3/envs/VMUnet/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 808, in init
    run_start_result = run_start_handle.wait(timeout=30)
  File "/home/yjl/anaconda3/envs/VMUnet/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 281, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed
wandb: While tearing down the service manager. The following error has occurred: [Errno 32] Broken pipe

```

**Comment by CYYJL** [comment]
Hi, I found that the issue with the initialization of wandb was due to its inability to retrieve the GPU model and CPU model during initialization. However, when I commented out that part of the code, wandb was able to initialize normally. It might be because I am using the latest version of the Nvidia driver, version 555.99, and wandb cannot get the corresponding GPU model from the driver, causing the error.

**Comment by benbowler** [comment]
I'm seeing this today after upgrading to the v555 of the NVIDIA drivers. I can confirm commenting out this block bypasses the error for now.

**Comment by zzk2021** [comment]
![image](https://github.com/wandb/wandb/assets/73774678/0773d743-0354-4c96-954d-9cd2d8987425)
same problem, how to fix it?

**Comment by Wissotsky** [comment]
Can concur the same problem occurring with driver ver 555.99

**Comment by CYYJL** [comment]
@Wissotsky @zzk2021 
Hi，My solution is to avoid using pynvml to get GPU information. The downside is that you won't be able to see GPU and CPU-related information on the wandb website. In the code, you can comment out the code I showed in the probe function of the library file wandb/sdk/internal/system/assets, and then wandb will work normally.
![image](https://github.com/wandb/wandb/assets/148782029/d5de7d55-5587-4bef-96e4-3688b442e95a)

**Comment by fmamberti-wandb** [comment]
Thank you for surfacing this. I will raise with our engineering team and we will keep you posted with the progress

**Comment by cyber-chris** [comment]
Thanks, looks like the fix worked.

In case anyone else is having this issue, make sure you upgrade to `0.17.2`

**Comment by dmitryduev** [comment]
Please upgrade to version 0.17.2 and turn on our new backend `wandb-core` with `wandb.require("core")` after importing wandb. No source code modification should be necessary.
