### ISSUE TITLE
[CLI]: Numpy 2.0 breaks login command

### ISSUE THREAD

**Issue by PadLex** [wandb/wandb#7810]
### Describe the bug

Numpy 2.0 introduces breaking changes. Downgrading to version 1.26.4 works as a work-around for now.

```shell
pip install wandb
wandb login
```

```shell
(torch_cuda_11-7) ubuntu@129-213-88-203:~/LudiiRL$ wandb login
Traceback (most recent call last):
  File "/home/ubuntu/LudiiRL/torch_cuda_11-7/bin/wandb", line 5, in <module>
    from wandb.cli.cli import cli
  File "/home/ubuntu/LudiiRL/torch_cuda_11-7/lib/python3.10/site-packages/wandb/__init__.py", line 27, in <module>
    from wandb import sdk as wandb_sdk
  File "/home/ubuntu/LudiiRL/torch_cuda_11-7/lib/python3.10/site-packages/wandb/sdk/__init__.py", line 25, in <module>
    from .artifacts.artifact import Artifact
  File "/home/ubuntu/LudiiRL/torch_cuda_11-7/lib/python3.10/site-packages/wandb/sdk/artifacts/artifact.py", line 45, in <module>
    from wandb import data_types, env, util
  File "/home/ubuntu/LudiiRL/torch_cuda_11-7/lib/python3.10/site-packages/wandb/data_types.py", line 32, in <module>
    from .sdk.data_types import _dtypes
  File "/home/ubuntu/LudiiRL/torch_cuda_11-7/lib/python3.10/site-packages/wandb/sdk/data_types/_dtypes.py", line 393, in <module>
    NumberType.types.append(np.float_)
  File "/home/ubuntu/LudiiRL/torch_cuda_11-7/lib/python3.10/site-packages/numpy/__init__.py", line 397, in __getattr__
    raise AttributeError(
AttributeError: `np.float_` was removed in the NumPy 2.0 release. Use `np.float64` instead.. Did you mean: 'float16'?
```

### Environment

WandB version: 0.17.1

OS:

Python version:

Versions of relevant libraries:

**Comment by ppardus** [comment]
You can try using "pip install numpy==1.26.4," since numpy 2.0 does not support np.float_.

**Comment by NeilGirdhar** [comment]
This appears to be fixed on main?

**Comment by dmitryduev** [comment]
This was fixed in [v0.17.2](https://github.com/wandb/wandb/releases/tag/v0.17.2).

**Comment by chelseatroy** [comment]
Hi! I'll reopen it.

Observed in wandb v0.17.3, while running `import wandb` in a metaflow flow:

```
2024-06-27 17:32:49.749 [35/train/122 (pid 45700)] [pod t-44f0fe8b-h2nlw-wzrbz]     import wandb
2024-06-27 17:32:49.749 [35/train/122 (pid 45700)] [pod t-44f0fe8b-h2nlw-wzrbz]   File "/metaflow/linux-64/5a19c9bbb1aa612/lib/python3.10/site-packages/wandb/__init__.py", line 27, in <module>
2024-06-27 17:32:49.749 [35/train/122 (pid 45700)] [pod t-44f0fe8b-h2nlw-wzrbz]     from wandb import sdk as wandb_sdk
2024-06-27 17:32:49.749 [35/train/122 (pid 45700)] [pod t-44f0fe8b-h2nlw-wzrbz]   File "/metaflow/linux-64/5a19c9bbb1aa612/lib/python3.10/site-packages/wandb/sdk/__init__.py", line 25, in <module>
2024-06-27 17:32:49.749 [35/train/122 (pid 45700)] [pod t-44f0fe8b-h2nlw-wzrbz]     from .artifacts.artifact import Artifact
2024-06-27 17:32:49.749 [35/train/122 (pid 45700)] [pod t-44f0fe8b-h2nlw-wzrbz]   File "/metaflow/linux-64/5a19c9bbb1aa612/lib/python3.10/site-packages/wandb/sdk/artifacts/artifact.py", line 45, in <module>
2024-06-27 17:32:49.749 [35/train/122 (pid 45700)] [pod t-44f0fe8b-h2nlw-wzrbz]     from wandb import data_types, env, util
2024-06-27 17:32:49.749 [35/train/122 (pid 45700)] [pod t-44f0fe8b-h2nlw-wzrbz]   File "/metaflow/linux-64/5a19c9bbb1aa612/lib/python3.10/site-packages/wandb/data_types.py", line 32, in <module>
2024-06-27 17:32:49.749 [35/train/122 (pid 45700)] [pod t-44f0fe8b-h2nlw-wzrbz]     from .sdk.data_types import _dtypes
2024-06-27 17:32:49.749 [35/train/122 (pid 45700)] [pod t-44f0fe8b-h2nlw-wzrbz]   File "/metaflow/linux-64/5a19c9bbb1aa612/lib/python3.10/site-packages/wandb/sdk/data_types/_dtypes.py", line 393, in <module>
2024-06-27 17:32:49.749 [35/train/122 (pid 45700)] [pod t-44f0fe8b-h2nlw-wzrbz]     NumberType.types.append(np.float_)
2024-06-27 17:32:49.749 [35/train/122 (pid 45700)] [pod t-44f0fe8b-h2nlw-wzrbz]   File "/metaflow/linux-64/5a19c9bbb1aa612/lib/python3.10/site-packages/numpy/__init__.py", line 397, in __getattr__
2024-06-27 17:32:49.749 [35/train/122 (pid 45700)] [pod t-44f0fe8b-h2nlw-wzrbz]     raise AttributeError(
2024-06-27 17:32:49.749 [35/train/122 (pid 45700)] [pod t-44f0fe8b-h2nlw-wzrbz] AttributeError: `np.float_` was removed in the NumPy 2.0 release. Use `np.float64` instead.
```

**Comment by dmitryduev** [comment]
@chelseatroy it must be picking up some older version of wandb installed elsewhere. You can verify that by looking at https://github.com/wandb/wandb/blob/main/wandb/sdk/data_types/_dtypes.py#L393 -- what's referenced in your stacktrace is not there in the latest release.
