### ISSUE TITLE
[Q] Cannot login to Wandb (SockClient bug??)

### ISSUE THREAD

**Issue by Yoonho-Na** [wandb/wandb#7986]
here is my full error at first when `wandb login`

```
Traceback (most recent call last):
  File "/home/yhn/.conda/envs/yh/bin/wandb", line 8, in <module>
    sys.exit(cli())
  File "/home/yhn/.conda/envs/yh/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/yhn/.conda/envs/yh/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/yhn/.conda/envs/yh/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/yhn/.conda/envs/yh/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yhn/.conda/envs/yh/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/yhn/.conda/envs/yh/lib/python3.7/site-packages/wandb/cli/cli.py", line 97, in wrapper
    return func(*args, **kwargs)
  File "/home/yhn/.conda/envs/yh/lib/python3.7/site-packages/wandb/cli/cli.py", line 236, in login
    wandb.setup(settings=login_settings)
  File "/home/yhn/.conda/envs/yh/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 312, in setup
    ret = _setup(settings=settings)
  File "/home/yhn/.conda/envs/yh/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 307, in _setup
    wl = _WandbSetup(settings=settings)
  File "/home/yhn/.conda/envs/yh/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 293, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/home/yhn/.conda/envs/yh/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 106, in __init__
    self._setup()
  File "/home/yhn/.conda/envs/yh/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 234, in _setup
    self._setup_manager()
  File "/home/yhn/.conda/envs/yh/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 266, in _setup_manager
    _use_grpc=use_grpc, settings=self._settings
  File "/home/yhn/.conda/envs/yh/lib/python3.7/site-packages/wandb/sdk/wandb_manager.py", line 128, in __init__
    svc_iface._svc_connect(port=port)
  File "/home/yhn/.conda/envs/yh/lib/python3.7/site-packages/wandb/sdk/service/service_sock.py", line 30, in _svc_connect
    self._sock_client.connect(port=port)
  File "/home/yhn/.conda/envs/yh/lib/python3.7/site-packages/wandb/sdk/lib/sock_client.py", line 102, in connect
    s.connect(("localhost", port))
socket.gaierror: [Errno -2] Name or service not known
wandb: While tearing down the service manager. The following error has occured: 'SockClient' object has no attribute '_sock'
```

I tried updating wandb with `pip install wandb -U`

and now it shows this

```
wandb: ERROR Find detailed error logs at: /tmp/debug-cli.yhn.log
Error: Connection to wandb service failed.
wandb: Encountered an error while tearing down the service manager: 'SockClient' object has no attribute '_sock'
```

and this is what I get from the debug-cli log

```
2024-07-22 02:41:40 ERROR Traceback (most recent call last):
  File "/home/yhn/.conda/envs/yh/lib/python3.7/site-packages/wandb/sdk/wandb_manager.py", line 116, in _service_connect
    svc_iface._svc_connect(port=port)
  File "/home/yhn/.conda/envs/yh/lib/python3.7/site-packages/wandb/sdk/service/service_sock.py", line 30, in _svc_connect
    self._sock_client.connect(port=port)
  File "/home/yhn/.conda/envs/yh/lib/python3.7/site-packages/wandb/sdk/lib/sock_client.py", line 102, in connect
    s.connect(("localhost", port))
socket.gaierror: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yhn/.conda/envs/yh/lib/python3.7/site-packages/wandb/cli/cli.py", line 108, in wrapper
    return func(*args, **kwargs)
  File "/home/yhn/.conda/envs/yh/lib/python3.7/site-packages/wandb/cli/cli.py", line 247, in login
    wandb.setup(settings=login_settings)
  File "/home/yhn/.conda/envs/yh/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 325, in setup
    ret = _setup(settings=settings)
  File "/home/yhn/.conda/envs/yh/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 318, in _setup
    wl = _WandbSetup(settings=settings)
  File "/home/yhn/.conda/envs/yh/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 303, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/home/yhn/.conda/envs/yh/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 114, in __init__
    self._setup()
  File "/home/yhn/.conda/envs/yh/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 250, in _setup
    self._setup_manager()
  File "/home/yhn/.conda/envs/yh/lib/python3.7/site-packages/wandb/sdk/wandb_setup.py", line 283, in _setup_manager
    self._manager = wandb_manager._Manager(settings=self._settings)
  File "/home/yhn/.conda/envs/yh/lib/python3.7/site-packages/wandb/sdk/wandb_manager.py", line 158, in __init__
    wandb._sentry.reraise(e)
  File "/home/yhn/.conda/envs/yh/lib/python3.7/site-packages/wandb/analytics/sentry.py", line 155, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/yhn/.conda/envs/yh/lib/python3.7/site-packages/wandb/sdk/wandb_manager.py", line 156, in __init__
    self._service_connect()
  File "/home/yhn/.conda/envs/yh/lib/python3.7/site-packages/wandb/sdk/wandb_manager.py", line 131, in _service_connect
    ) from e
wandb.sdk.wandb_manager.ManagerConnectionError: Connection to wandb service failed.
```

**Comment by Yoonho-Na** [comment]
```
(yh) yhn@rami-4:~/TPS/RL_Agent/PPO_LSTM_v4$ wandb login
wandb: ERROR Find detailed error logs at: /tmp/debug-cli.yhn.log
Error: Connection to wandb service failed.
wandb: Encountered an error while tearing down the service manager: 'SockClient' object has no attribute '_sock'
(yh) yhn@rami-4:~/TPS/RL_Agent/PPO_LSTM_v4$ ping localhost
ping: localhost: Name or service not known
(yh) yhn@rami-4:~/TPS/RL_Agent/PPO_LSTM_v4$ ping https://wandb.ai
ping: https://wandb.ai: Name or service not known
(yh) yhn@rami-4:~/TPS/RL_Agent/PPO_LSTM_v4$ ping google.com
PING google.com (142.250.66.110) 56(84) bytes of data.
64 bytes from hkg12s28-in-f14.1e100.net (142.250.66.110): icmp_seq=1 ttl=114 time=74.2 ms
64 bytes from hkg12s28-in-f14.1e100.net (142.250.66.110): icmp_seq=2 ttl=114 time=54.6 ms
64 bytes from hkg12s28-in-f14.1e100.net (142.250.66.110): icmp_seq=3 ttl=114 time=54.6 ms
64 bytes from hkg12s28-in-f14.1e100.net (142.250.66.110): icmp_seq=4 ttl=114 time=54.5 ms
64 bytes from hkg12s28-in-f14.1e100.net (142.250.66.110): icmp_seq=5 ttl=114 time=54.9 ms
^C
--- google.com ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4006ms
rtt min/avg/max/mdev = 54.524/58.558/74.179/7.811 ms
(yh) yhn@rami-4:~/TPS/RL_Agent/PPO_LSTM_v4$ ping wandb.ai
PING wandb.ai (34.128.185.112) 56(84) bytes of data.
64 bytes from 112.185.128.34.bc.googleusercontent.com (34.128.185.112): icmp_seq=1 ttl=109 time=8.75 ms
64 bytes from 112.185.128.34.bc.googleusercontent.com (34.128.185.112): icmp_seq=2 ttl=109 time=8.96 ms
64 bytes from 112.185.128.34.bc.googleusercontent.com (34.128.185.112): icmp_seq=3 ttl=109 time=8.93 ms
^C
--- wandb.ai ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2002ms
rtt min/avg/max/mdev = 8.752/8.878/8.958/0.090 ms
(yh) yhn@rami-4:~/TPS/RL_Agent/PPO_LSTM_v4$ export WANDB_BASE_URL=https://api.wandb.ai
(yh) yhn@rami-4:~/TPS/RL_Agent/PPO_LSTM_v4$ wandb login
wandb: ERROR Find detailed error logs at: /tmp/debug-cli.yhn.log
Error: Connection to wandb service failed.
wandb: Encountered an error while tearing down the service manager: 'SockClient' object has no attribute '_sock'
(yh) yhn@rami-4:~/TPS/RL_Agent/PPO_LSTM_v4$ rm -rf ~/.wandb
(yh) yhn@rami-4:~/TPS/RL_Agent/PPO_LSTM_v4$ wandb login
wandb: ERROR Find detailed error logs at: /tmp/debug-cli.yhn.log
Error: Connection to wandb service failed.
wandb: Encountered an error while tearing down the service manager: 'SockClient' object has no attribute '_sock'
(yh) yhn@rami-4:~/TPS/RL_Agent/PPO_LSTM_v4$ wandb --version
wandb, version 0.17.5
(yh) yhn@rami-4:~/TPS/RL_Agent/PPO_LSTM_v4$ python --version
Python 3.7.15
```
these are what I did except for uninstalling wandb.
I'm currently coding via remote development so I don't think the network is the problem.

**Comment by Yoonho-Na** [comment]
`pip uninstall wandb pip install wandb`

I don't know why but this command deleted pip itself and I had to reinstall the pip.

anyways, I installed wandb and `wandb login` still don't work.
also I tried rebooting the system.

**Comment by Yoonho-Na** [comment]
The problem was in the server hostname
closing the issue
