### ISSUE TITLE
Separate scripts fail when canceling one running wandb

### ISSUE THREAD

**Issue by elilaird** [wandb/wandb#7989]
### Describe the bug

I am running a training script that has one wandb run. When running multiple slurm jobs that run the same script, when I scancel one job all other jobs using wandb fail with the error below. I noticed this only happens when the separate jobs are running on the same node. I made sure that wandb was using separate IDS and WANDB_DIR for each slurm job, but this failed. I also made sure that wandb was being closed gracefully using signal handlers, but to no avail.

```python
...

 with wandb.init(
        project="<project-name>",
        dir=os.environ.get("WANDB_DIR"),
        name=f"{name}_tune",
        group=name,
        config=dict(config),
        tags=[
            slurm_id,
            config.dataset,
            config.model_type,
            config.layer_type,
            str(config.target_percentage),
        ],
        id=os.environ.get("WANDB_RUN_ID"),
        reinit=True,
        mode=WANDB_MODE,
    ) as wandb_run:
        # additional training code ...



```

```shell
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/psutil/_pslinux.py", line 1620, in pid_exists
  File "/opt/conda/lib/python3.10/site-packages/psutil/_common.py", line 711, in open_binary
FileNotFoundError: [Errno 2] No such file or directory: '/proc/4159629/status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
  File "/opt/conda/lib/python3.10/runpy.py", line 86, in _run_code
  File "/opt/conda/lib/python3.10/site-packages/wandb/__main__.py", line 3, in <module>
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1078, in main
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
  File "/opt/conda/lib/python3.10/site-packages/wandb/cli/cli.py", line 108, in wrapper
  File "/opt/conda/lib/python3.10/site-packages/wandb/cli/cli.py", line 292, in service
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/service/server.py", line 118, in serve
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/service/streams.py", line 423, in loop
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/service/streams.py", line 421, in loop
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/service/streams.py", line 407, in _loop
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/service/streams.py", line 403, in _check_orphaned
  File "/opt/conda/lib/python3.10/site-packages/psutil/__init__.py", line 1392, in pid_exists
  File "/opt/conda/lib/python3.10/site-packages/psutil/_pslinux.py", line 1629, in pid_exists
  File "/opt/conda/lib/python3.10/site-packages/psutil/_pslinux.py", line 1597, in pids
FileNotFoundError: [Errno 2] No such file or directory: b'/proc'
Exception in thread FileStreamThread:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
  File "/opt/conda/lib/python3.10/threading.py", line 953, in run
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/internal/file_stream.py", line 502, in _thread_except_body
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/internal/file_stream.py", line 496, in _thread_except_body
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/internal/file_stream.py", line 452, in _thread_body
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/internal/file_stream.py", line 542, in _send
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/internal/file_stream.py", line 636, in request_with_retry
  File "/opt/conda/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
  File "/opt/conda/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
  File "/opt/conda/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
  File "/opt/conda/lib/python3.10/site-packages/requests/adapters.py", line 459, in send
  File "/opt/conda/lib/python3.10/site-packages/requests/adapters.py", line 262, in cert_verify
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /opt/conda/lib/python3.10/site-packages/certifi/cacert.pem
Exception in thread StreamThr:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/psutil/_pslinux.py", line 1620, in pid_exists
  File "/opt/conda/lib/python3.10/site-packages/psutil/_common.py", line 711, in open_binary
FileNotFoundError: [Errno 2] No such file or directory: '/proc/4159629/status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/service/streams.py", line 49, in run
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/internal/internal.py", line 150, in wandb_internal
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/internal/internal.py", line 411, in is_dead
  File "/opt/conda/lib/python3.10/site-packages/psutil/__init__.py", line 1392, in pid_exists
  File "/opt/conda/lib/python3.10/site-packages/psutil/_pslinux.py", line 1629, in pid_exists
  File "/opt/conda/lib/python3.10/site-packages/psutil/_pslinux.py", line 1597, in pids
FileNotFoundError: [Errno 2] No such file or directory: b'/proc'

```

### Environment

WandB version: 0.17.5

OS: Linux

Python version: Python 3.10

Versions of relevant libraries:

**Comment by JoanaMarieL** [comment]
Hello @elilaird , thank you for writing in and happy to help. Could you also please send the `debug.log` and d`ebug-internal.log`. These files are under your local folder `wandb/run-<date>_<time>-<run-id>/logs` in the same directory where you’re running your code.

**Comment by elilaird** [comment]
[debug-internal.log](https://github.com/user-attachments/files/16350458/debug-internal.log)
[debug.log](https://github.com/user-attachments/files/16350459/debug.log)


@JoanaMarieL Here are my debug files! Thank you for the help!

**Comment by JoanaMarieL** [comment]
Hi @elilaird , thank you for providing the logs, can you please  try again if this is still the case?

**Comment by elilaird** [comment]
@JoanaMarieL Sorry for the late response. I can try again. Is there a particular branch/update I should pull to test again?

**Comment by elilaird** [comment]
[debug-internal.log](https://github.com/user-attachments/files/16512291/debug-internal.log)
[debug.log](https://github.com/user-attachments/files/16512292/debug.log)

I tested running my script again (two instances of the script on the same slurm node). Here are the logs ^. 

I'm using the 0.17.5 version as before from: wandb-0.17.5-py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl

Here is the error:

`Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/psutil/_pslinux.py", line 1620, in pid_exists
  File "/opt/conda/lib/python3.10/site-packages/psutil/_common.py", line 711, in open_binary
FileNotFoundError: [Errno 2] No such file or directory: '/proc/2870178/status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
  File "/opt/conda/lib/python3.10/runpy.py", line 86, in _run_code
  File "/opt/conda/lib/python3.10/site-packages/wandb/__main__.py", line 3, in <module>
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1078, in main
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
  File "/opt/conda/lib/python3.10/site-packages/wandb/cli/cli.py", line 108, in wrapper
  File "/opt/conda/lib/python3.10/site-packages/wandb/cli/cli.py", line 292, in service
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/service/server.py", line 118, in serve
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/service/streams.py", line 423, in loop
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/service/streams.py", line 421, in loop
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/service/streams.py", line 407, in _loop
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/service/streams.py", line 403, in _check_orphaned
  File "/opt/conda/lib/python3.10/site-packages/psutil/__init__.py", line 1392, in pid_exists
  File "/opt/conda/lib/python3.10/site-packages/psutil/_pslinux.py", line 1629, in pid_exists
  File "/opt/conda/lib/python3.10/site-packages/psutil/_pslinux.py", line 1597, in pids
FileNotFoundError: [Errno 2] No such file or directory: b'/proc'

RUN: TUNE | Epoch: 274 Loss: 0.172218  lr: 0.004147 wd: 0.008259 mm: 0.999174 Avg Time: 0.386784 s:  27%|██▋       | 274/1000 [01:50<04:57,  2.44it/s]
RUN: TUNE | Epoch: 274 Loss: 0.172218  lr: 0.004147 wd: 0.008259 mm: 0.999174 Avg Time: 0.386784 s:  28%|██▊       | 275/1000 [01:50<04:51,  2.48it/s]
RUN: TUNE | Epoch: 275 Loss: 0.172240  lr: 0.004141 wd: 0.008247 mm: 0.999175 Avg Time: 0.386242 s:  28%|██▊       | 275/1000 [01:50<04:51,  2.48it/s]
RUN: TUNE | Epoch: 275 Loss: 0.172240  lr: 0.004141 wd: 0.008247 mm: 0.999175 Avg Time: 0.386242 s:  28%|██▊       | 276/1000 [01:50<04:48,  2.51it/s]Exception in thread FileStreamThread:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
  File "/opt/conda/lib/python3.10/threading.py", line 953, in run
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/internal/file_stream.py", line 502, in _thread_except_body
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/internal/file_stream.py", line 496, in _thread_except_body
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/internal/file_stream.py", line 452, in _thread_body
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/internal/file_stream.py", line 542, in _send
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/internal/file_stream.py", line 636, in request_with_retry
  File "/opt/conda/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
  File "/opt/conda/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
  File "/opt/conda/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
  File "/opt/conda/lib/python3.10/site-packages/requests/adapters.py", line 459, in send
  File "/opt/conda/lib/python3.10/site-packages/requests/adapters.py", line 262, in cert_verify
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /opt/conda/lib/python3.10/site-packages/certifi/cacert.pem

Exception in thread StreamThr:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/psutil/_pslinux.py", line 1620, in pid_exists
  File "/opt/conda/lib/python3.10/site-packages/psutil/_common.py", line 711, in open_binary
FileNotFoundError: [Errno 2] No such file or directory: '/proc/2870178/status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/service/streams.py", line 49, in run
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/internal/internal.py", line 150, in wandb_internal
  File "/opt/conda/lib/python3.10/site-packages/wandb/sdk/internal/internal.py", line 411, in is_dead
  File "/opt/conda/lib/python3.10/site-packages/psutil/__init__.py", line 1392, in pid_exists
  File "/opt/conda/lib/python3.10/site-packages/psutil/_pslinux.py", line 1629, in pid_exists
  File "/opt/conda/lib/python3.10/site-packages/psutil/_pslinux.py", line 1597, in pids
FileNotFoundError: [Errno 2] No such file or directory: b'/proc'`

**Comment by JoanaMarieL** [comment]
Hi @elilaird , thank you for providing these. We suggest to add this line `wandb.require(“core”)` after wandb import.. and  you can see more details about wandb core here for reference: https://github.com/wandb/wandb/tree/main/core. Let us know how it goes :)

**Comment by elilaird** [comment]
@JoanaMarieL I tested again while using wandb-core and the same issue and errors are still happening. It seems that when one wandb job is canceled it shuts down some background process that both jobs are sharing.

**Comment by JoanaMarieL** [comment]
Thank you for sharing @elilaird , may we request to share with us your Slurm script so that we can try to reproduce the issue on our side as well.

**Comment by JoanaMarieL** [comment]
Hi @elilaird , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
