### ISSUE TITLE
[Bug-App]: [0.18.0]: Build fails on FreeBSD: undefined: NewGPUNvidia

### ISSUE THREAD

**Issue by yurivict** [wandb/wandb#8371]
### Describe the bug

What support for NVidia GPU is WanDB using?
CUDA isn't available on FreeBSD, but Vulkan is available.

**Comment by dmitryduev** [comment]
We use a rust wrapper around Nvidia's nvml (https://github.com/Cldfire/nvml-wrapper) to collect metrics for their gpus, so if there's no `libnvidia-ml.so` available for FreeBSD, no need to build that binary: to skip it, please set `WANDB_BUILD_SKIP_NVIDIA=true`.

**Comment by dmitryduev** [comment]
I also should have read the title of the issue lol :)
here's the fix for it: https://github.com/wandb/wandb/pull/8373

**Comment by yurivict** [comment]
@dmitryduev 

When I apply the patch from the PR https://github.com/wandb/wandb/pull/8373 to the release 0.18.0 and add the ```WANDB_BUILD_SKIP_NVIDIA=true``` environment variable the build still fails:
```
Building wandb-core Go binary...
# github.com/wandb/wandb/core/pkg/monitor
pkg/monitor/monitor.go:162:12: undefined: NewGPUAMD
pkg/monitor/monitor.go:171:17: undefined: NewTrainium
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 380, in <module>
    main()
  File "/usr/local/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 364, in main
    json_out["return_val"] = hook(**hook_input["kwargs"])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by dmitryduev** [comment]
oops, sorry about that. here: https://github.com/wandb/wandb/pull/8374

**Comment by yurivict** [comment]
@dmitryduev 

When I added https://github.com/wandb/wandb/pull/8374 on top of https://github.com/wandb/wandb/pull/8373 it now fails like this:
```
===>  Building for py311-wandb-0.18.0
* Getting build dependencies for wheel...
* Building wheel...
Failed to parse sysconfig.get_platform() (freebsd-14.1-STABLE-amd64); disabling cross-compilation.
Building wandb-core Go binary...
# github.com/wandb/wandb/core/pkg/monitor
pkg/monitor/noop_freebsd.go:114:6: GPUAMD redeclared in this block
        pkg/monitor/noop_freebsd.go:57:6: other declaration of GPUAMD
pkg/monitor/noop_freebsd.go:119:6: NewGPUAMD redeclared in this block
        pkg/monitor/noop_freebsd.go:62:6: other declaration of NewGPUAMD
pkg/monitor/noop_freebsd.go:126:18: method GPUAMD.Name already declared at pkg/monitor/noop_freebsd.go:69:18
pkg/monitor/noop_freebsd.go:128:18: method GPUAMD.Sample already declared at pkg/monitor/noop_freebsd.go:71:18
pkg/monitor/noop_freebsd.go:130:18: method GPUAMD.IsAvailable already declared at pkg/monitor/noop_freebsd.go:73:18
pkg/monitor/noop_freebsd.go:132:18: method GPUAMD.Probe already declared at pkg/monitor/noop_freebsd.go:75:18
pkg/monitor/noop_freebsd.go:137:6: Trainium redeclared in this block
        pkg/monitor/noop_freebsd.go:80:6: other declaration of Trainium
pkg/monitor/noop_freebsd.go:145:6: NewTrainium redeclared in this block
        pkg/monitor/noop_freebsd.go:88:6: other declaration of NewTrainium
pkg/monitor/noop_freebsd.go:160:20: method Trainium.Name already declared at pkg/monitor/noop_freebsd.go:103:20
pkg/monitor/noop_freebsd.go:162:20: method Trainium.Sample already declared at pkg/monitor/noop_freebsd.go:105:20
pkg/monitor/noop_freebsd.go:162:20: too many errors
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 380, in <module>
    main()
  File "/usr/local/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 364, in main
    json_out["return_val"] = hook(**hook_input["kwargs"])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 278, in build_wheel
    return _build_backend().build_wheel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hatchling/build.py", line 58, in build_wheel
    return os.path.basename(next(builder.build(directory=wheel_directory, versions=['standard'])))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hatchling/builders/plugin/interface.py", line 147, in build
    build_hook.initialize(version, build_data)
  File "/usr/ports/misc/py-wandb/work-py311/wandb-0.18.0/hatch_build.py", line 37, in initialize
    self._prepare_wheel(build_data)
  File "/usr/ports/misc/py-wandb/work-py311/wandb-0.18.0/hatch_build.py", line 43, in _prepare_wheel
    artifacts.extend(self._build_wandb_core())
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/ports/misc/py-wandb/work-py311/wandb-0.18.0/hatch_build.py", line 167, in _build_wandb_core
    hatch_core.build_wandb_core(
  File "/usr/ports/misc/py-wandb/work-py311/wandb-0.18.0/core/hatch.py", line 46, in build_wandb_core
    subprocess.check_call(
  File "/usr/local/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/ports/misc/py-wandb/work-py311/.bin/go', 'build', '-ldflags=-s -w -X main.commit=9295e1f45704eac6d89bb2e18ab3eb12565ce56c', '-o', '../wandb/bin/wandb-core', '-mod=vendor', 'cmd/wandb-core/main.go']' returned non-zero exit status 1.

ERROR Backend subprocess exited when trying to invoke build_wheel
*** Error code 1
```

**Comment by dmitryduev** [comment]
@yurivict looks like something got botched, there aren't even this many lines in this file: https://github.com/wandb/wandb/blob/main/core/pkg/monitor/noop_freebsd.go. Could you please try checking out main and trying it off it? (merged both of those prs and that will go into the release next week)
