### ISSUE TITLE
[Bug-App]: wandb.errors.WandbCoreNotAvailableError: Looks like wandb-core is not compiled for your system (macOS-10.16-x86_64-i386-64bit)

### ISSUE THREAD

**Issue by PlutoHades1** [wandb/wandb#8459]
### Describe the bug

packages/wandb/util.py", line 1934, in get_core_path
    raise WandbCoreNotAvailableError(
wandb.errors.WandbCoreNotAvailableError: Looks like wandb-core is not compiled for your system (macOS-10.16-x86_64-i386-64bit): Please contact support at support@wandb.com to request `wandb-core` support for your system.

**Comment by kptkin** [comment]
@PlutoHades1 thanks for reporting the issue... we had a slight regression in our 0.18.1 release, if you downgrade to 0.18.0 it should work and we are fixing it for 0.18.2 release. thanks for your patience.

**Comment by kptkin** [comment]
Duplicates #8455

**Comment by chenwei-zhang** [comment]
I got the same issue. 
My wandb version is the latest one: v0.18.7.

Here's the error message:
wandb.errors.errors.WandbCoreNotAvailableError: File not found: /home/cwzhang/atomic/lib/python3.11/site-packages/wandb/bin/wandb-core.Please contact support at support@wandb.com.Your platform is: Linux-5.14.0-362.24.2.el9_3.x86_64-x86_64-Intel-R-_Xeon-R-_Silver_4216_CPU_@_2.10GHz-with-glibc2.37.

**Comment by darinyu** [comment]
I got similar error
```
wandb.errors.errors.WandbCoreNotAvailableError: File not found: /Users/zyu/wandb/wandb/bin/wandb-core. Please contact support at support@wandb.com. Your platform is: macOS-13.6.9-arm64-arm-64bit.
```

my wandb version is v0.19.1

I just started trying out starting local wandb server with
```
wandb login --host=http://localhost:8080
```
then running `wandb.init()` gives me this error. I don't see this folder at all "/Users/zyu/wandb/wandb/bin/"

**Comment by timoffex** [comment]
@darinyu, how did you install `wandb`? If you used the command `pip install wandb`, then for your system, it should have selected and installed the wandb-0.19.1-py3-none-macosx_11_0_arm64.whl file listed in https://pypi.org/project/wandb/0.19.1/#files. You can try downloading that file and installing it directly using `pip install wandb-0.19.1-py3-none-macosx_11_0_arm64.whl`.

**Comment by darinyu** [comment]
Im still seeing this issue after reinstall wandb + install the file manually (same error)

```
1. pip install /Users/zyu/Downloads/wandb-0.19.1-py3-none-macosx_11_0_arm64.whl                                                                                                 

Looking in indexes: https://pypi.netflix.net/simple
Processing /Users/zyu/Downloads/wandb-0.19.1-py3-none-macosx_11_0_arm64.whl
Requirement already satisfied: click!=8.0.0,>=7.1 in /opt/homebrew/Caskroom/miniforge/base/envs/py310/lib/python3.10/site-packages (from wandb==0.19.1) (8.1.7)
Requirement already satisfied: docker-pycreds>=0.4.0 in /opt/homebrew/Caskroom/miniforge/base/envs/py310/lib/python3.10/site-packages (from wandb==0.19.1) (0.4.0)
Requirement already satisfied: gitpython!=3.1.29,>=1.0.0 in /opt/homebrew/Caskroom/miniforge/base/envs/py310/lib/python3.10/site-packages (from wandb==0.19.1) (3.1.43)
Requirement already satisfied: platformdirs in /opt/homebrew/Caskroom/miniforge/base/envs/py310/lib/python3.10/site-packages (from wandb==0.19.1) (4.2.2)
Requirement already satisfied: protobuf!=4.21.0,!=5.28.0,<6,>=3.19.0 in /opt/homebrew/Caskroom/miniforge/base/envs/py310/lib/python3.10/site-packages (from wandb==0.19.1) (5.26.1)
Requirement already satisfied: psutil>=5.0.0 in /opt/homebrew/Caskroom/miniforge/base/envs/py310/lib/python3.10/site-packages (from wandb==0.19.1) (6.1.1)
Requirement already satisfied: pydantic<3,>=2.6 in /opt/homebrew/Caskroom/miniforge/base/envs/py310/lib/python3.10/site-packages (from wandb==0.19.1) (2.9.0)
Requirement already satisfied: pyyaml in /opt/homebrew/Caskroom/miniforge/base/envs/py310/lib/python3.10/site-packages (from wandb==0.19.1) (6.0.1)
Requirement already satisfied: requests<3,>=2.0.0 in /opt/homebrew/Caskroom/miniforge/base/envs/py310/lib/python3.10/site-packages (from wandb==0.19.1) (2.31.0)
Requirement already satisfied: sentry-sdk>=2.0.0 in /opt/homebrew/Caskroom/miniforge/base/envs/py310/lib/python3.10/site-packages (from wandb==0.19.1) (2.19.2)
Requirement already satisfied: setproctitle in /opt/homebrew/Caskroom/miniforge/base/envs/py310/lib/python3.10/site-packages (from wandb==0.19.1) (1.3.3)
Requirement already satisfied: setuptools in /opt/homebrew/Caskroom/miniforge/base/envs/py310/lib/python3.10/site-packages (from wandb==0.19.1) (69.2.0)
Requirement already satisfied: typing-extensions<5,>=4.4 in /opt/homebrew/Caskroom/miniforge/base/envs/py310/lib/python3.10/site-packages (from wandb==0.19.1) (4.11.0)
Requirement already satisfied: six>=1.4.0 in /opt/homebrew/Caskroom/miniforge/base/envs/py310/lib/python3.10/site-packages (from docker-pycreds>=0.4.0->wandb==0.19.1) (1.16.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /opt/homebrew/Caskroom/miniforge/base/envs/py310/lib/python3.10/site-packages (from gitpython!=3.1.29,>=1.0.0->wandb==0.19.1) (4.0.11)
Requirement already satisfied: annotated-types>=0.4.0 in /opt/homebrew/Caskroom/miniforge/base/envs/py310/lib/python3.10/site-packages (from pydantic<3,>=2.6->wandb==0.19.1) (0.7.0)
Requirement already satisfied: pydantic-core==2.23.2 in /opt/homebrew/Caskroom/miniforge/base/envs/py310/lib/python3.10/site-packages (from pydantic<3,>=2.6->wandb==0.19.1) (2.23.2)
Requirement already satisfied: tzdata in /opt/homebrew/Caskroom/miniforge/base/envs/py310/lib/python3.10/site-packages (from pydantic<3,>=2.6->wandb==0.19.1) (2024.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/homebrew/Caskroom/miniforge/base/envs/py310/lib/python3.10/site-packages (from requests<3,>=2.0.0->wandb==0.19.1) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/homebrew/Caskroom/miniforge/base/envs/py310/lib/python3.10/site-packages (from requests<3,>=2.0.0->wandb==0.19.1) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/homebrew/Caskroom/miniforge/base/envs/py310/lib/python3.10/site-packages (from requests<3,>=2.0.0->wandb==0.19.1) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in /opt/homebrew/Caskroom/miniforge/base/envs/py310/lib/python3.10/site-packages (from requests<3,>=2.0.0->wandb==0.19.1) (2024.2.2)
Requirement already satisfied: smmap<6,>=3.0.1 in /opt/homebrew/Caskroom/miniforge/base/envs/py310/lib/python3.10/site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb==0.19.1) (5.0.1)
wandb is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.



2. python test.py    
wandb: Currently logged in as: zyu. Use `wandb login --relogin` to force relogin
Traceback (most recent call last):
  File "/Users/zyu/wandb/test.py", line 5, in <module>
    wandb.init(
  File "/Users/zyu/wandb/wandb/sdk/wandb_init.py", line 1303, in init
    wandb._sentry.reraise(e)
  File "/Users/zyu/wandb/wandb/analytics/sentry.py", line 156, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/Users/zyu/wandb/wandb/sdk/wandb_init.py", line 1289, in init
    return wi.init()
  File "/Users/zyu/wandb/wandb/sdk/wandb_init.py", line 677, in init
    service = self._wl.ensure_service()
  File "/Users/zyu/wandb/wandb/sdk/wandb_setup.py", line 280, in ensure_service
    self._connection = service_connection.connect_to_service(self._settings)
  File "/Users/zyu/wandb/wandb/sdk/lib/service_connection.py", line 40, in connect_to_service
    return _start_and_connect_service(settings)
  File "/Users/zyu/wandb/wandb/sdk/lib/service_connection.py", line 75, in _start_and_connect_service
    proc.start()
  File "/Users/zyu/wandb/wandb/sdk/service/service.py", line 232, in start
    self._launch_server()
  File "/Users/zyu/wandb/wandb/sdk/service/service.py", line 155, in _launch_server
    _sentry.reraise(e)
  File "/Users/zyu/wandb/wandb/analytics/sentry.py", line 156, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/Users/zyu/wandb/wandb/sdk/service/service.py", line 153, in _launch_server
    core_path = get_core_path()
  File "/Users/zyu/wandb/wandb/util.py", line 1948, in get_core_path
    raise WandbCoreNotAvailableError(
wandb.errors.errors.WandbCoreNotAvailableError: File not found: /Users/zyu/wandb/wandb/bin/wandb-core. Please contact support at support@wandb.com. Your platform is: macOS-13.6.9-arm64-arm-64bit.
```
