### ISSUE TITLE
[Bug]: Setting run.name='foo' fails in disabled mode

### ISSUE THREAD

**Issue by jdanbrown** [wandb/wandb#8513]
### Describe the bug

When `run.disabled == True`, trying to set `run.name = ...` fails because the attribute `run._backend` was never set:
- Maybe the deprecation warning (below) has something to do with it? But even so, is this expected to hard fail, or is that a bug that should be fixed in 0.18.x?

```py
>>> import wandb
>>> wandb.__version__
'0.18.0'

# Set disabled mode
>>> import os
>>> os.environ['WANDB_MODE'] = 'disabled'

# Make a run (in disabled mode)
>>> run = wandb.init()
wandb: WARNING Disabling the wandb service is deprecated as of version 0.18.0 and will be removed in future versions. 
>>> run.mode
'run'
>>> run.disabled
True

# Try to set run.name (which fails)
>>> run.name
'dummy-zvxpfqww'
>>> run.name = 'foo'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/pay/src/zoolander/py_universe_ml_golden_202403_ama/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 829, in __setattr__
    super().__setattr__(attr, value)
  File "/pay/src/zoolander/py_universe_ml_golden_202403_ama/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 404, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/pay/src/zoolander/py_universe_ml_golden_202403_ama/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 980, in name
    if self._backend and self._backend.interface:
AttributeError: 'Run' object has no attribute '_backend'
```

Versions:
- wandb 0.18.0
- python: 3.8.17
- OS: Linux 5.15.0-1068-aws #74~20.04.1-Ubuntu

**Comment by JoanaMarieL** [comment]
Hello @jdanbrown, it seems that our engineers fixed this issue, can you please try again? Thanks!

**Comment by JoanaMarieL** [comment]
Hi @jdanbrown , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
