### ISSUE TITLE
[Q]: ERROR failed to upsert bucket: returned error 403 Forbidden

### ISSUE THREAD

**Issue by bassfaye** [wandb/wandb#8609]
### Ask your question

Hello,
I am a new using wanb. I want to experiment tracking by using wandb and executing python commands. However I get this error.
How to solve this error?

wandb: Currently logged in as: bassfaye10. Use `wandb login --relogin` to force relogin
wandb: ERROR failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}

**Comment by JoanaMarieL** [comment]
Hi @bassfaye , happy to help. Could you please tell us more about your experiment or specific use case and if you could share the following:

-Code Snippet
-Full stack trace error
-the debug.log and debug-internal.log. These files are under your local folder wandb/run-<date>_<time>-<run-id>/logs in the same directory where you’re running your code.

**Comment by bassfaye** [comment]
Hi @JoanaMarieL, 
I want to use machine learning for tooth segmentation. So I've found an example on github on this link: https://github.com/limhoyeon/ToothGroupNetwork. I want to initiate myself on machine learning by compiling this project.
Here are informations that you need:

1. **Code Snippet:**

### train.py
_if config["wandb"]["wandb_on"]:
            wandb.init(
            entity=self.config["wandb"]["wandb_entity"],
            project=self.config["wandb"]["project"],
            notes=self.config["wandb"]["notes"],
            tags=self.config["wandb"]["tags"],
            name=self.config["wandb"]["name"],
            config=self.config,
            )_

2. **Full stack trace error:**

_wandb: ERROR failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
Traceback (most recent call last):
  File "start_train.py", line 51, in <module>
    runner(config, model)
  File "F:\ToothGroupNetwork\runner.py", line 56, in runner
    trainner = Trainer(config=config, model = model, gen_set=gen_set)
  File "F:\ToothGroupNetwork\trainer.py", line 15, in __init__
    wandb.init(
  File "C:\Users\serigne_admin\AppData\Local\Programs\Python\Python38\lib\site-packages\wandb\sdk\wandb_init.py", line 1266, in init
    wandb._sentry.reraise(e)
  File "C:\Users\serigne_admin\AppData\Local\Programs\Python\Python38\lib\site-packages\wandb\analytics\sentry.py", line 155, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "C:\Users\serigne_admin\AppData\Local\Programs\Python\Python38\lib\site-packages\wandb\sdk\wandb_init.py", line 1252, in init
    return wi.init()
  File "C:\Users\serigne_admin\AppData\Local\Programs\Python\Python38\lib\site-packages\wandb\sdk\wandb_init.py", line 844, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}_

3. **Debug.log**
_### 2024-10-14 11:16:39,633 INFO    MainThread:15652 [wandb_setup.py:_flush():79] Current SDK version is 0.18.3
2024-10-14 11:16:39,633 INFO    MainThread:15652 [wandb_setup.py:_flush():79] Configure stats pid to 15652
2024-10-14 11:16:39,633 INFO    MainThread:15652 [wandb_setup.py:_flush():79] Loading settings from C:\Users\serigne_admin\.config\wandb\settings
2024-10-14 11:16:39,633 INFO    MainThread:15652 [wandb_setup.py:_flush():79] Loading settings from F:\ToothGroupNetwork\wandb\settings
2024-10-14 11:16:39,633 INFO    MainThread:15652 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2024-10-14 11:16:39,633 INFO    MainThread:15652 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2024-10-14 11:16:39,652 INFO    MainThread:15652 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program_relpath': 'start_train.py', 'program_abspath': 'F:\\ToothGroupNetwork\\start_train.py', 'program': 'start_train.py'}
2024-10-14 11:16:39,652 INFO    MainThread:15652 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-10-14 11:16:39,652 INFO    MainThread:15652 [wandb_init.py:_log_setup():532] Logging user logs to F:\ToothGroupNetwork\wandb\run-20241014_111639-i5vb5pi5\logs\debug.log
2024-10-14 11:16:39,652 INFO    MainThread:15652 [wandb_init.py:_log_setup():533] Logging internal logs to F:\ToothGroupNetwork\wandb\run-20241014_111639-i5vb5pi5\logs\debug-internal.log
2024-10-14 11:16:39,652 INFO    MainThread:15652 [wandb_init.py:init():617] calling init triggers
2024-10-14 11:16:39,652 INFO    MainThread:15652 [wandb_init.py:init():624] wandb.init called with sweep_config: {}
config: {'wandb': {'entity': 'bassfaye10', 'wandb_on': True, 'project': '3d tooth mesh segmentation', 'tags': '3d tooth mesh segmentation', 'notes': '3d tooth mesh segmentation', 'name': 'tgnet_0620'}, 'generator': {'input_data_dir_path': 'data_preprocessed_directory', 'train_data_split_txt_path': 'base_name_train_fold.txt', 'val_data_split_txt_path': 'base_name_val_fold.txt', 'aug_obj_str': "aug.Augmentator([aug.Scaling([0.85, 1.15]), aug.Rotation([-30,30], 'fixed'), aug.Translation([-0.2, 0.2])])", 'train_batch_size': 1, 'val_batch_size': 1}, 'checkpoint_path': 'ckpts/tgnet_0620', 'tr_set': {'optimizer': {'lr': 0.1, 'NAME': 'sgd', 'momentum': 0.9, 'weight_decay': 0.0001}, 'scheduler': {'sched': 'cosine', 'warmup_epochs': 0, 'full_steps': 40, 'schedueler_step': 15000000, 'min_lr': 1e-05}, 'loss': {'cbl_loss_1': 1, 'cbl_loss_2': 1, 'tooth_class_loss_1': 1, 'tooth_class_loss_2': 1, 'offset_1_loss': 0.03, 'offset_1_dir_loss': 0.03, 'chamf_1_loss': 0.15}}, 'model_parameter': {'input_feat': 6, 'stride': [1, 4, 4, 4, 4], 'nsample': [36, 24, 24, 24, 24], 'blocks': [2, 3, 4, 6, 3], 'block_num': 5, 'planes': [32, 64, 128, 256, 512], 'crop_sample_size': 3072}}
2024-10-14 11:16:39,652 INFO    MainThread:15652 [wandb_init.py:init():667] starting backend
2024-10-14 11:16:39,652 INFO    MainThread:15652 [wandb_init.py:init():671] sending inform_init request
2024-10-14 11:16:39,652 INFO    MainThread:15652 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn, using: spawn
2024-10-14 11:16:39,656 INFO    MainThread:15652 [wandb_init.py:init():684] backend started and connected
2024-10-14 11:16:39,663 INFO    MainThread:15652 [wandb_init.py:init():779] updated telemetry
2024-10-14 11:16:39,663 INFO    MainThread:15652 [wandb_init.py:init():812] communicating run to backend with 90.0 second timeout
2024-10-14 11:16:40,077 ERROR   MainThread:15652 [wandb_init.py:init():838] encountered error: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2024-10-14 11:16:40,077 ERROR   MainThread:15652 [wandb_init.py:init():1262] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\serigne_admin\AppData\Local\Programs\Python\Python38\lib\site-packages\wandb\sdk\wandb_init.py", line 1252, in init
    return wi.init()
  File "C:\Users\serigne_admin\AppData\Local\Programs\Python\Python38\lib\site-packages\wandb\sdk\wandb_init.py", line 844, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2024-10-14 11:16:40,147 WARNING MsgRouterThr:15652 [router.py:message_loop():77] message_loop has been closed_

4. **Debug-internal.log:**

_{"time":"2024-10-14T11:16:39.6571469+02:00","level":"INFO","msg":"using version","core version":"0.18.3"}
{"time":"2024-10-14T11:16:39.6571469+02:00","level":"INFO","msg":"created symlink","path":"F:\\ToothGroupNetwork\\wandb\\run-20241014_111639-i5vb5pi5\\logs\\debug-core.log"}
{"time":"2024-10-14T11:16:39.667464+02:00","level":"ERROR","msg":"dialing: google: could not find default credentials. See https://cloud.google.com/docs/authentication/external/set-up-adc for more information"}
{"time":"2024-10-14T11:16:39.9300979+02:00","level":"INFO","msg":"created new stream","id":"i5vb5pi5"}
{"time":"2024-10-14T11:16:39.9302162+02:00","level":"INFO","msg":"stream: started","id":"i5vb5pi5"}
{"time":"2024-10-14T11:16:39.9302162+02:00","level":"INFO","msg":"writer: Do: started","stream_id":{"value":"i5vb5pi5"}}
{"time":"2024-10-14T11:16:39.9303154+02:00","level":"INFO","msg":"sender: started","stream_id":{"value":"i5vb5pi5"}}
{"time":"2024-10-14T11:16:39.9303154+02:00","level":"INFO","msg":"handler: started","stream_id":{"value":"i5vb5pi5"}}
{"time":"2024-10-14T11:16:40.0765827+02:00","level":"ERROR","msg":"HTTP error","status":403,"method":"POST","url":"https://api.wandb.ai/graphql"}
{"time":"2024-10-14T11:16:40.0765827+02:00","level":"ERROR","msg":"sender: upsertRun:","error":"failed to upsert bucket: returned error 403 Forbidden: {\"errors\":[{\"message\":\"permission denied\",\"path\":[\"upsertBucket\"],\"extensions\":{\"code\":\"PERMISSION_ERROR\"}}],\"data\":{\"upsertBucket\":null}}"}
{"time":"2024-10-14T11:16:40.1472315+02:00","level":"INFO","msg":"stream: closing","id":"i5vb5pi5"}
{"time":"2024-10-14T11:16:40.2625221+02:00","level":"ERROR","msg":"HTTP error","status":403,"method":"POST","url":"https://api.wandb.ai/graphql"}
{"time":"2024-10-14T11:16:40.2697548+02:00","level":"ERROR","msg":"sender: sendConfig:","error":"returned error 403 Forbidden: {\"errors\":[{\"message\":\"permission denied\",\"path\":[\"upsertBucket\"],\"extensions\":{\"code\":\"PERMISSION_ERROR\"}}],\"data\":{\"upsertBucket\":null}}"}
{"time":"2024-10-14T11:16:40.2711115+02:00","level":"WARN","msg":"No requirements.txt found, not creating job artifact. See https://docs.wandb.ai/guides/launch/create-job"}
{"time":"2024-10-14T11:16:40.2711115+02:00","level":"INFO","msg":"sender: sendDefer: no job artifact to save"}
{"time":"2024-10-14T11:16:40.3161557+02:00","level":"ERROR","msg":"HTTP error","status":404,"method":"POST","url":"https://api.wandb.ai/graphql"}
{"time":"2024-10-14T11:16:40.3161557+02:00","level":"ERROR","msg":"runfiles: CreateRunFiles returned error: returned error 404 Not Found: {\"errors\":[{\"message\":\"project bassfaye10/3d tooth mesh segmentation not found during createRunFiles\",\"path\":[\"createRunFiles\"]}],\"data\":{\"createRunFiles\":null}}"}
{"time":"2024-10-14T11:16:40.4470144+02:00","level":"ERROR","msg":"HTTP error","status":404,"method":"POST","url":"https://api.wandb.ai/graphql"}
{"time":"2024-10-14T11:16:40.4470144+02:00","level":"ERROR","msg":"runfiles: CreateRunFiles returned error: returned error 404 Not Found: {\"errors\":[{\"message\":\"project bassfaye10/3d tooth mesh segmentation not found during createRunFiles\",\"path\":[\"createRunFiles\"]}],\"data\":{\"createRunFiles\":null}}"}
{"time":"2024-10-14T11:16:40.4471349+02:00","level":"INFO","msg":"fileTransfer: Close: file transfer manager closed"}
{"time":"2024-10-14T11:16:40.4472412+02:00","level":"INFO","msg":"handler: closed","stream_id":{"value":"i5vb5pi5"}}
{"time":"2024-10-14T11:16:40.4472412+02:00","level":"INFO","msg":"writer: Close: closed","stream_id":{"value":"i5vb5pi5"}}
{"time":"2024-10-14T11:16:40.4472412+02:00","level":"INFO","msg":"sender: closed","stream_id":{"value":"i5vb5pi5"}}
{"time":"2024-10-14T11:16:40.4480132+02:00","level":"INFO","msg":"stream: closed","id":"i5vb5pi5"}_
Really appreciate your help,

**Comment by mattmattkim** [comment]
I struggled with this for a few hours but turns out that W&B wanted the full entity name that includes your organization.

Ex. username-your-organization-name

**Comment by noaleetz** [comment]
Hey @mattmattkim - could you share what you used as full entity name? i.e when you say W&B wanted the full entity name with organization, what did you end up passing in as the entity into wandb.init() that was successful eventually?

**Comment by JoanaMarieL** [comment]
Hi @bassfaye , 

In this part of your code, `entity=self.config["wandb"]["wandb_entity"]` could you please try to update it with the team you belong with, and not your personal entity?

Also, Thank you for sharing @mattmattkim with your experience!

**Comment by bassfaye** [comment]
Hi @JoanaMarieL , it works by updating ### entity=self.config["wandb"]["wandb_entity"] with my team organization entity not my personal entity.
Thanks you @mattmattkim!

**Comment by sia-cerebras** [comment]
For other who may hit this error. In my case it was because we are using a private deployment of W&B. So I needed to specify the `host` when I logged in, e.g. `wandb login --host=https://SUB_DOMAIN.wandb.io`

**Comment by sahilgupta88** [comment]
For me, entity Name was not organization name otherwise it throws error. Hence create a team and put that name into the entity below:

wandb.init(project=PROJECT_NAME, entity='TEAM_NAME')

or 

wandb.init(project=PROJECT_NAME, entity=TEAM_NAME, name=RUN_NAME)
