### ISSUE TITLE
[Bug]: File deletion via API gives error 'Argument "input" has invalid value {files: $files}'

### ISSUE THREAD

**Issue by tobias-kirschstein** [wandb/wandb#8753]
### Describe the bug

Trying to delete files from a finished run via the Python API like this:

```python
import wandb

entity = wandb.setup()._get_username()
api = wandb.Api()

project = ...  # some project name
run_id = ...  # some run ID
run = api.run(f"{entity}/{project}/{run_id}")
files = run.files()
files[0].delete()  # <- Error here
```

produces an error:
`wandb.errors.errors.CommError: Argument "input" has invalid value {files: $files}.`
`In field "projectId": Expected "Int!", found null.`

Full stacktrace:

```
Traceback (most recent call last):
  File "C:\Programs\Programming\miniconda\envs\topo\lib\site-packages\wandb\apis\normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "C:\Programs\Programming\miniconda\envs\topo\lib\site-packages\wandb\apis\public\files.py", line 188, in delete
    self.client.execute(mutation, variable_values={"files": [self.id]})
  File "C:\Programs\Programming\miniconda\envs\topo\lib\site-packages\wandb\sdk\lib\retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "C:\Programs\Programming\miniconda\envs\topo\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Programs\Programming\miniconda\envs\topo\lib\site-packages\wandb\apis\public\api.py", line 71, in execute
    return self._client.execute(*args, **kwargs)
  File "C:\Programs\Programming\miniconda\envs\topo\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 54, in execute
    raise Exception(str(result.errors[0]))
Exception: {'message': 'Argument "input" has invalid value {files: $files}.\nIn field "projectId": Expected "Int!", found null.', 'locations': [{'line': 2, 'column': 22}]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Programs\Programming\miniconda\envs\topo\lib\site-packages\wandb\apis\normalize.py", line 87, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "C:\Programs\Programming\miniconda\envs\topo\lib\site-packages\wandb\apis\normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "C:\Programs\Programming\miniconda\envs\topo\lib\site-packages\wandb\apis\public\files.py", line 188, in delete
    self.client.execute(mutation, variable_values={"files": [self.id]})
  File "C:\Programs\Programming\miniconda\envs\topo\lib\site-packages\wandb\sdk\lib\retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "C:\Programs\Programming\miniconda\envs\topo\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Programs\Programming\miniconda\envs\topo\lib\site-packages\wandb\apis\public\api.py", line 71, in execute
    return self._client.execute(*args, **kwargs)
  File "C:\Programs\Programming\miniconda\envs\topo\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 54, in execute
    raise Exception(str(result.errors[0]))
wandb.errors.errors.CommError: Argument "input" has invalid value {files: $files}.
In field "projectId": Expected "Int!", found null.
```

I can reproduce this issue on all my machines for all runs that I tried. It seems file deletion is not working at all at the moment. Probably some misguided change on the server side.

OS: at least in Windows 11, Ubuntu 20.04.4 LTS, and Ubuntu 20.04.5 LTS
Python: at least in 3.9.20 and 3.10.15
wandb version: Happens at least in 0.18.2, 0.18.3, and 0.18.5

**Comment by fmamberti-wandb** [comment]
Hi @tobias-kirschstein, thank you for surfacing the issue and sharing the details to reproduce. 
I will be working to repro on my end and will keep you posted with any updates.

**Comment by GuillaumeTong** [comment]
I have encountered this same issue with file deletion

**Comment by Dibz15** [comment]
Hi there. I've got the same bug, whereas we were able to use this API just a few weeks ago.

**Comment by edwardjjj** [comment]
Encountering the same issue here. Any updates so far?

**Comment by radekd91** [comment]
Also happening to me. I happen to need to delete a lot of files fast. Help would be appreciated. Thanks :-)

**Comment by fmamberti-wandb** [comment]
Hi everyone - thank you for your patience while we investigated this. We have now rolled out a fix so should be able to delete the files as expected via the API.

**Comment by radekd91** [comment]
@fmamberti-wandb , the deletion calls do not crash anymore, however, I am not sure if anything is successfully getting deleted at all. It certainly doesn't show. I've deleted many many files using the API, but it seems my used storage the website reports is not changing at all.

**Comment by radekd91** [comment]
I created a new issue #8944 for the problem I mention above.

**Comment by fdsig** [comment]
hey @radekd91 thanks for the update here and for creating a new issue regarding what is displayed in the wandb UI. 

I will mark this issue as solved (the original SDK bug that was fixed) but please don't hesitate to reach out here or directly to 'support@wandb.com'
