### ISSUE TITLE
[Q]: Network error (ConnectionError), entering retry loop while running sweep

### ISSUE THREAD

**Issue by jay20162016** [wandb/wandb#8825]
### Ask your question

I am getting `Network error (ConnectionError), entering retry loop` while running a sweep. The network is fine, I can ping `wandb.ai` and `api.wandb.ai` without issues. This issue has persisted for over a day now, restarting my computer doesn't help.

debug.log:
```
2024-11-09 00:44:56,829 INFO    Thread-6  :6116 [wandb_setup.py:_flush():79] Current SDK version is 0.18.6
2024-11-09 00:44:56,829 INFO    Thread-6  :6116 [wandb_setup.py:_flush():79] Configure stats pid to 6116
2024-11-09 00:44:56,830 INFO    Thread-6  :6116 [wandb_setup.py:_flush():79] Loading settings from C:\Users\ps\.config\wandb\settings
2024-11-09 00:44:56,830 INFO    Thread-6  :6116 [wandb_setup.py:_flush():79] Loading settings from D:\user\research\wandb\settings
2024-11-09 00:44:56,830 INFO    Thread-6  :6116 [wandb_setup.py:_flush():79] Loading settings from environment variables: {'root_dir': 'D:\\user\\research', 'sweep_id': 'go918ayd', 'project': 'lightning_logs', 'run_id': 'wr6y10n0', 'sweep_param_path': 'D:\\user\\research\\wandb\\sweep-go918ayd\\config-wr6y10n0.yaml'}
2024-11-09 00:44:56,830 INFO    Thread-6  :6116 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2024-11-09 00:44:56,830 INFO    Thread-6  :6116 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program_relpath': 'src\\sweep.py', 'program_abspath': 'D:\\user\\research\\src\\sweep.py', 'program': 'src/sweep.py'}
2024-11-09 00:44:56,831 INFO    Thread-6  :6116 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-11-09 00:44:56,831 INFO    Thread-6  :6116 [wandb_init.py:_log_setup():533] Logging user logs to D:\user\research\wandb\run-20241109_004456-wr6y10n0\logs\debug.log
2024-11-09 00:44:56,831 INFO    Thread-6  :6116 [wandb_init.py:_log_setup():534] Logging internal logs to D:\user\research\wandb\run-20241109_004456-wr6y10n0\logs\debug-internal.log
2024-11-09 00:44:56,832 INFO    Thread-6  :6116 [wandb_init.py:init():619] calling init triggers
2024-11-09 00:44:56,832 INFO    Thread-6  :6116 [wandb_init.py:init():626] wandb.init called with sweep_config: {'batchmul': 8, 'dropout': 0.2788766805876036, 'epochs': 80, 'l2_mul': 1.1128239127329125, 'learning_rate': 0.0006580454524951332, 'weight_decay': 0.009410512803122635}
config: {}
2024-11-09 00:44:56,832 INFO    Thread-6  :6116 [wandb_init.py:init():669] starting backend
2024-11-09 00:44:56,832 INFO    Thread-6  :6116 [wandb_init.py:init():673] sending inform_init request
2024-11-09 00:44:56,846 INFO    Thread-6  :6116 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn, using: spawn
2024-11-09 00:44:56,849 INFO    Thread-6  :6116 [wandb_init.py:init():686] backend started and connected
2024-11-09 00:44:56,856 INFO    Thread-6  :6116 [wandb_run.py:_config_callback():1389] config_cb None None {'batchmul': 8, 'dropout': 0.2788766805876036, 'epochs': 80, 'l2_mul': 1.1128239127329125, 'learning_rate': 0.0006580454524951332, 'weight_decay': 0.009410512803122635}
2024-11-09 00:44:56,858 INFO    Thread-6  :6116 [wandb_init.py:init():781] updated telemetry
2024-11-09 00:44:56,860 INFO    Thread-6  :6116 [wandb_init.py:init():814] communicating run to backend with 90.0 second timeout
2024-11-09 00:45:55,164 INFO    Thread-7  :6116 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\urllib3\connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\urllib3\connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x0000020F0F8DDD30>, 'Connection to api.wandb.ai timed out. (connect timeout=20)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000020F0F8DDD30>, 'Connection to api.wandb.ai timed out. (connect timeout=20)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\wandb\sdk\internal\internal_api.py", line 400, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\wandb\sdk\lib\gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\requests\sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\requests\adapters.py", line 553, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000020F0F8DDD30>, 'Connection to api.wandb.ai timed out. (connect timeout=20)'))
2024-11-09 00:45:58,259 INFO    Thread-5  :6116 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\urllib3\connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000020F0F9E2730>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020F0F9E2730>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\wandb\sdk\internal\internal_api.py", line 400, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\wandb\sdk\lib\gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\requests\sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020F0F9E2730>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
2024-11-09 00:46:27,411 ERROR   Thread-6  :6116 [wandb_init.py:init():841] encountered error: Run initialization has timed out after 90.0 sec. Please try increasing the timeout with the `init_timeout` setting: `wandb.init(settings=wandb.Settings(init_timeout=120))`.
2024-11-09 00:46:27,412 ERROR   Thread-6  :6116 [wandb_init.py:init():1266] error in wandb.init()
Traceback (most recent call last):
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\wandb\sdk\wandb_init.py", line 1256, in init
    return wi.init()
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\wandb\sdk\wandb_init.py", line 847, in init
    raise error
wandb.errors.errors.CommError: Run initialization has timed out after 90.0 sec. Please try increasing the timeout with the `init_timeout` setting: `wandb.init(settings=wandb.Settings(init_timeout=120))`.
2024-11-09 00:46:27,432 ERROR   MainThread:6116 [pyagent.py:_run_jobs_from_queue():234] Run wr6y10n0 errored:
Traceback (most recent call last):
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\wandb\agents\pyagent.py", line 306, in _run_job
    self._function()
  File "D:\user\research\src\sweep.py", line 57, in <lambda>
    wandb.agent(sweep_id, function=lambda: main({},sweep=True), project="lightning_logs")
  File "D:\user\research\src\unet_train.py", line 158, in main
    if sweep: wandb.init(project="lightning_logs")
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\wandb\sdk\wandb_init.py", line 1270, in init
    wandb._sentry.reraise(e)
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\wandb\analytics\sentry.py", line 161, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\wandb\sdk\wandb_init.py", line 1256, in init
    return wi.init()
  File "D:\Anaconda3\envs\ptl_env\lib\site-packages\wandb\sdk\wandb_init.py", line 847, in init
    raise error
wandb.errors.errors.CommError: Run initialization has timed out after 90.0 sec. Please try increasing the timeout with the `init_timeout` setting: `wandb.init(settings=wandb.Settings(init_timeout=120))`.

```

debug-internal.log:
```
{"time":"2024-11-09T00:44:56.8582218+08:00","level":"INFO","msg":"using version","core version":"0.18.6"}
{"time":"2024-11-09T00:44:56.8582218+08:00","level":"INFO","msg":"created symlink","path":"D:\\user\\research\\wandb\\run-20241109_004456-wr6y10n0\\logs\\debug-core.log"}
{"time":"2024-11-09T00:44:57.4052337+08:00","level":"INFO","msg":"created new stream","id":"wr6y10n0"}
{"time":"2024-11-09T00:44:57.4052337+08:00","level":"INFO","msg":"stream: started","id":"wr6y10n0"}
{"time":"2024-11-09T00:44:57.405788+08:00","level":"INFO","msg":"writer: Do: started","stream_id":{"value":"wr6y10n0"}}
{"time":"2024-11-09T00:44:57.406076+08:00","level":"INFO","msg":"sender: started","stream_id":"wr6y10n0"}
{"time":"2024-11-09T00:44:57.4059653+08:00","level":"INFO","msg":"handler: started","stream_id":{"value":"wr6y10n0"}}
{"time":"2024-11-09T00:45:18.4458511+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-09T00:45:41.5234369+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-09T00:46:07.1716706+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-09T00:46:36.7473307+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2024-11-09T00:47:14.1314565+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
```

**Comment by fmamberti-wandb** [comment]
Hi @jay20162016 , sorry to hear you are experiencing this issue and thank you for sharing the logs.

Would you mind sharing some additional information to help us troubleshoot this:

- Are you seeing this only happening when initiating a run via a Sweep agent? If so, could you share a URL to the sweep? 
- Have you tested increasing the timeout for the init (i.e. `wandb.init(settings=wandb.Settings(init_timeout=120))`) 
- Could you try running `wandb verify` from your Terminal and share the terminal output for it?

**Comment by jay20162016** [comment]
seems to be working now, will reopen if issue happens again

**Comment by zhoufy20** [comment]
> Hi [@jay20162016](https://github.com/jay20162016) , sorry to hear you are experiencing this issue and thank you for sharing the logs.
> 
> Would you mind sharing some additional information to help us troubleshoot this:
> 
> * Are you seeing this only happening when initiating a run via a Sweep agent? If so, could you share a URL to the sweep?
> * Have you tested increasing the timeout for the init (i.e. `wandb.init(settings=wandb.Settings(init_timeout=120))`)
> * Could you try running `wandb verify` from your Terminal and share the terminal output for it?

Hi,there! I encounter the same problem, this is output when `wandb verify`:
```
Default host selected: https://api.wandb.ai
Find detailed logs for this test at: /tmp/tmprvn017lj/wandb
❌
Cannot run wandb verify against api.wandb.ai
```

**Comment by fdsig** [comment]
Hey @zhoufy20 thanks for messaging  here 

If be able to share your `debug.log` and `debug-internal.log`

Regarding the error that you have shared `wandb verify`  which is intended for hosted wandb sever installs.

**Comment by fdsig** [comment]
Hey @zhoufy20, I am following up to see if you still need assistance and if so would you mind sharing the above -- if you'd prefer to reach out directly (now or in the future) you can do so by emailing `support@wandb.com`

**Comment by fdsig** [comment]
Hey @zhoufy20, since we have not heard back here I'll mark this as closed just now. Please do reach out to us here or directly at `suppor@wandb.com` on this or anything else WandB-related that you need assistance with in the future.
