### ISSUE TITLE
[Bug]: save_best_only=True breaks WandbModelCheckpoint

### ISSUE THREAD

**Issue by GabrielGosden** [wandb/wandb#8842]
### Describe the bug

# Description
In the [_check_filepath](https://github.com/wandb/wandb/blob/6bc2440183e02633c11fdd291550c5eb9c0b4634/wandb/integration/keras/callbacks/model_checkpoint.py#L176) it states that when using `save_best_only = True`, I must ensure that the `filepath` argument contains formatting placeholders like `{epoch:02d}` or `{batch:02d}` to ensure correct interpretation of the logged artifacts.

However, when doing this, the `WandbModelCheckpoint` callback fails if the model does not improve on the given metric. When the model does not improve, it is not saved locally, and therefore, it also fails to upload to W&B. `WandbModelCheckpoint` does not check if the file exists before trying to upload it.

To demonstrate this issue, I have generated a minimal working example:
```python
import wandb
from wandb.integration.keras import WandbModelCheckpoint
import os 
import numpy as np

import tensorflow as tf

wandb.init(project="wandb_keras_callback_bug")

# Create a simple model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, input_dim=10, activation='relu'),
    tf.keras.layers.Dense(1, activation='linear')
])

# Compile the model with a very high learning rate, makes sure model does not improve every epoch
model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=10), 
              loss='mean_squared_error')

callback = WandbModelCheckpoint(
    os.path.join("/playground/models/", wandb.run.name,"_epoch_{epoch:02d}" + "_min_val_loss.h5"),
    monitor="loss",
    verbose=1,
    mode="min",
    save_best_only=True,
    save_weights_only=False,
    )

model.fit(
    x=np.random.rand(100, 10),
    y=np.random.rand(100, 1),
    epochs=5,
    callbacks=[callback]
)
```
This code fails with the following error:
```
Epoch 1/5
1/4 [======>.......................] - ETA: 1s - loss: 2.4207
Epoch 1: loss improved from inf to 144019552.00000, saving model to /playground/models/volcanic-blaze-14/_epoch_01_min_val_loss.h5
4/4 [==============================] - 1s 95ms/step - loss: 144019552.0000
Epoch 2/5
1/4 [======>.......................] - ETA: 0s - loss: 1273042567168.0000
Epoch 2: loss did not improve from 144019552.00000
Traceback (most recent call last):
  File "mre_test.py", line 32, in <module>
    model.fit(
  File "/usr/local/lib/python3.8/dist-packages/wandb/integration/keras/keras.py", line 176, in new_v2
    return old_v2(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/wandb/integration/keras/keras.py", line 176, in new_v2
    return old_v2(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/wandb/integration/keras/keras.py", line 176, in new_v2
    return old_v2(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/wandb/integration/keras/callbacks/model_checkpoint.py", line 145, in on_epoch_end
    self._log_ckpt_as_artifact(filepath, aliases=aliases)
  File "/usr/local/lib/python3.8/dist-packages/wandb/integration/keras/callbacks/model_checkpoint.py", line 161, in _log_ckpt_as_artifact
    raise FileNotFoundError(f"No such file or directory {filepath}")
FileNotFoundError: No such file or directory /playground/models/volcanic-blaze-14/_epoch_02_min_val_loss.h5
```

# Possible duplicates issues
#6423 This feature request seems to have gone stale last year. Has this been abandoned?
#6169 Not directly related.

**Comment by paulosabile-wb** [comment]
Hey @GabrielGosden Good day and thank you for reporting this issue to us! I tried to run the script you shared and I received: 

```error
The filepath provided must end in `.keras` (Keras model format). Received: filepath=/playground/models/sandy-deluge-2/_epoch_{epoch:02d}_min_val_loss.h5
``` 

I assume this is because I am using a different environment but do you know if you have seen this similar error when you are trying it from your end? 

Additionally, may I know your current SDK version when you were building your experiment? You can get this by running `wandb --version`.

**Comment by GabrielGosden** [comment]
Hi @paulosabile-wb,

Thanks for your reply.

> ```
> The filepath provided must end in `.keras` (Keras model format). Received: filepath=/playground/models/sandy-deluge-2/_epoch_{epoch:02d}_min_val_loss.h5
> ```
> 
> I assume this is because I am using a different environment but do you know if you have seen this similar error when you are trying it from your end?

I have not seen this error before. If i remove the `{epoch:02d}"` placeholder i can use `WandbModelCheckpoint` to upload `.h5` files without issues.

> Additionally, may I know your current SDK version when you were building your experiment? You can get this by running wandb --version.

My error for not specifying the SDK version. We are using wandb==0.18.5

**Comment by Satge96** [comment]
I have the same issue. My wandb version is 19.0, and I use python 3.12.7. For me, the problem occurs for weights.h5 and .keras paths.

**Comment by GabrielGosden** [comment]
@paulosabile-wb have you been able to replicate the issue?

**Comment by aajais** [comment]
Hi @GabrielGosden @Satge96, We’ve been able to reproduce the issue and have filed a bug report for it. I’ll make sure to keep you updated on its progress.

At the moment, our team is in the process of scoping the issue. However, it’s not under active development just yet, as we’re currently prioritizing other major projects. While I don’t have a timeline to share right now, I’ll follow up with any updates from our engineering team as soon as they’re available.

Thank you for your patience and understanding. If you have any further questions or concerns, please don’t hesitate to reach out!

**Comment by mfazrinizar** [comment]
Are there any updates regarding this issue?

**Comment by aajais** [comment]
Hi @mfazrinizar, No updates just yet, but I’ll follow up internally and let you know as soon as I have anything to share. Thanks for your patience!

**Comment by Satge96** [comment]
Do you have any news?

**Comment by aajais** [comment]
Hi @Satge96, Yes, we’ve got plans to improve support for Keras 3, and those updates should address this issue. You can expect a fix soon! Thanks for your patience and for flagging this.
