### ISSUE TITLE
[Bug]: `ultralytics` reporting fails if there are no positive examples in the batch

### ISSUE THREAD

**Issue by Jamil** [wandb/wandb#8869]
### Describe the bug

- wandb version: 0.18.6
- python version: 3.11.5

When we encounter a batch with no positive labels, we get this error:
```
Generating Visualizations for batch-1/1:   0%|                                                                                                                                                                     | 0/44 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "pipeline.py", line 97, in <module>
    main()
  File "pipeline.py", line 84, in main
    output_path = train_stage(stage_config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "train_new.py", line 57, in train_stage
    results = model.train(**train_args)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "site-packages/ultralytics/engine/model.py", line 802, in train
    self.trainer.train()
  File "site-packages/ultralytics/engine/trainer.py", line 207, in train
    self._do_train(world_size)
  File "site-packages/ultralytics/engine/trainer.py", line 437, in _do_train
    self.metrics, self.fitness = self.validate()
                                 ^^^^^^^^^^^^^^^
  File "site-packages/ultralytics/engine/trainer.py", line 600, in validate
    metrics = self.validator(self)
              ^^^^^^^^^^^^^^^^^^^^
  File "site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "site-packages/ultralytics/engine/validator.py", line 202, in __call__
    self.run_callbacks("on_val_end")
  File "site-packages/ultralytics/engine/validator.py", line 271, in run_callbacks
    callback(self)
  File "site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "site-packages/wandb/integration/ultralytics/callback.py", line 362, in on_val_end
    self.validation_table = plot_detection_validation_results(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "site-packages/wandb/integration/ultralytics/bbox_utils.py", line 177, in plot_detection_validation_results
    ground_truth_data = get_ground_truth_bbox_annotations(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "site-packages/wandb/integration/ultralytics/bbox_utils.py", line 41, in get_ground_truth_bbox_annotations
    cls_labels = batch["cls"][indices].squeeze(1).tolist()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
```

This is because no labels will appear like this:
```
-> cls_labels = batch["cls"][indices].squeeze(1).tolist()
(Pdb) p batch["cls"][indices]
tensor([])
```

Rather than like this, for positive examples:
```
-> cls_labels = batch["cls"][indices].squeeze(1).tolist()
(Pdb) p batch["cls"][indices]
tensor([[3.]])
```

**Comment by ArtsiomWB** [comment]
Hi @Jamil! Thank you for writing in and reporting this. 

Would you mind sending us an example script for your workflow here so I can send it to our engineering team?

**Comment by Jamil** [comment]
Yeah, just any simple training with a wandb callback + ultralytics, where a single batch has no positive examples (if, for example, you use a dataset with no positive examples you can trivially reproduce this)

```
import wandb
from ultralytics import YOLO
from wandb.integration.ultralytics import add_wandb_callback

def train_yolo():
    wandb.init(
        project="yolo-example",
        name="training-run",
        job_type="training"
    )
    
    model = YOLO('yolov8x.pt')
    
    add_wandb_callback(model)
    
    results = model.train(
        data='coco128_negative.yaml',  # path to data config file with negatives
        epochs=3,
        batch=16,
        imgsz=640
    )
    
    wandb.finish()

if __name__ == "__main__":
    train_yolo()
```

This is with Ultralytics 8.3.30

**Comment by Jamil** [comment]
I also have a PR to fix this: https://github.com/wandb/wandb/pull/8870
