### ISSUE TITLE
[Feature]: Change the way to get `local_image_sha`

### ISSUE THREAD

**Issue by ease-zh** [wandb/wandb#8952]
### Description

When we call `wandb server start`, the `wandb.docker.image_id` function was called to get the `local_image_sha`. It works if I just pull the image from docker. But once I use docker save and docker load to deploy the wandb server (no internet avaliable that can not pull image), the `RepoDigests` field will be lost, thus the following error will be raised:
```
Traceback (most recent call last):
  File "/data_111/miniconda3/envs/insightface/bin/wandb", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/data_111/miniconda3/envs/insightface/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data_111/miniconda3/envs/insightface/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/data_111/miniconda3/envs/insightface/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data_111/miniconda3/envs/insightface/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data_111/miniconda3/envs/insightface/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data_111/miniconda3/envs/insightface/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data_111/miniconda3/envs/insightface/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data_111/miniconda3/envs/insightface/lib/python3.11/site-packages/wandb/cli/cli.py", line 104, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data_111/miniconda3/envs/insightface/lib/python3.11/site-packages/wandb/cli/cli.py", line 2206, in start
    registry_image_sha = wandb.docker.image_id_from_registry("wandb/local").split(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'

```

This is similar in #5748 and #4918. And the lost of `RepoDigests` was also discussed in https://github.com/moby/moby/issues/22011. 

I hope there be a way to solve the dependece on `RepoDigests`, so that the wandb server can be deployed use the save&load image.

**Comment by ease-zh** [comment]
Well, I just noticed that the `local_image_sha` is only used to compare with the `registry_image_sha`, and to check whether a upgrade is avaliable. Since I have no internet, so this comparation is no use, so I can just ignore these shas.
