### ISSUE TITLE
[Bug]: parameter sweep fails when run using the %run command in ipython

### ISSUE THREAD

**Issue by lrast** [wandb/wandb#8953]
### Describe the bug

The following code works fine: 
```
import pytorch_lightning as pl
import torch.nn.functional as F
import torch
from pytorch_lightning.loggers import WandbLogger
import wandb
from torch.utils.data import DataLoader,Dataset
import os

import torch
from torch.utils.data import Dataset


class MyDataset(Dataset):
    def __init__(self, data, labels):
        self.data = data
        self.labels = labels

    def __len__(self):
        return len(self.data)

    def __getitem__(self, index):
        x = self.data[index]
        y = self.labels[index]
        return x, y
    
class MyDataModule(pl.LightningDataModule):
    def __init__(self, config):
        super().__init__()
        N=10000   
        x = torch.unsqueeze(torch.linspace(-1, 1, N), dim=1)                    
        y = x.pow(2) + config.noise*torch.rand(x.size())                             
        self.my_dataset = MyDataset(x,y)
        print(config.noise)

    def train_dataloader(self):
        return DataLoader(self.my_dataset, batch_size=100,shuffle=True, num_workers=2)

    def val_dataloader(self):
        return DataLoader(self.my_dataset,batch_size=100,shuffle=False)



class Net(torch.nn.Module):
    def __init__(self, n_feature, n_hidden, n_output):
        super(Net, self).__init__()
        self.hidden = torch.nn.Linear(n_feature, n_hidden)
        self.predict = torch.nn.Linear(n_hidden, n_output)
    def forward(self, x):
        x= F.relu(self.hidden(x))
        x = self.predict(x)
        return x

class MyLightningModule(pl.LightningModule):
    def __init__(self, config): #n_hidden, lr):
        super().__init__()
        self.net = Net(n_feature=1, n_hidden=config.n_hidden, n_output=1)
        self.lr = config.lr

    def training_step(self, batch, batch_idx):
        # training_step defines the train loop.
        x, y = batch
        y_hat = self.net(x)
        loss = F.mse_loss(y_hat, x)
        self.log('training_loss',loss,on_step=True, on_epoch=True,prog_bar=True)
        return loss
    
    def validation_step(self, batch, batch_idx):
        x, y = batch
        y_hat = self.net(x)
        loss = F.mse_loss(y_hat, x)
        self.log('validation_loss',loss)
        return loss

    def configure_optimizers(self):
        optimizer = torch.optim.SGD(self.parameters(), lr=self.lr)
        return optimizer
    
def train_model():
    wandb.init(project="sweep")
    config=wandb.config
    wandb_logger = WandbLogger()
    data = MyDataModule(config)
    module = MyLightningModule(config)

    wandb_logger.watch(module.net)
    
    trainer = pl.Trainer(accelerator='gpu', devices=1, max_epochs=10, 
        default_root_dir="./lightning-example", logger=wandb_logger)
    trainer.fit(module, data)        


if __name__ == '__main__':
    sweep_config = {
        'method': 'random',
        'name': 'first_sweep',
        'metric': {
            'goal': 'minimize',
            'name': 'validation_loss'
        },
        'parameters': {
            'n_hidden': {'values': [2,3,5,10]},
            'lr': {'max': 1.0, 'min': 0.0001},
            'noise': {'max': 1.0, 'min': 0.}
        }
    }

    sweep_id=wandb.sweep(sweep_config, project="test_sweep")
    wandb.agent(sweep_id=sweep_id, function=train_model, count=5)
```

However, changing the last lines from

```
if __name__ == '__main__':
    sweep_config = {
        'method': 'random',
        'name': 'first_sweep',
        'metric': {
            'goal': 'minimize',
            'name': 'validation_loss'
        },
        'parameters': {
            'n_hidden': {'values': [2,3,5,10]},
            'lr': {'max': 1.0, 'min': 0.0001},
            'noise': {'max': 1.0, 'min': 0.}
        }
    }

    sweep_id=wandb.sweep(sweep_config, project="test_sweep")
    wandb.agent(sweep_id=sweep_id, function=train_model, count=5)
```
to 

```
sweep_config = {
    'method': 'random',
    'name': 'first_sweep',
    'metric': {
        'goal': 'minimize',
        'name': 'validation_loss'
    },
    'parameters': {
        'n_hidden': {'values': [2,3,5,10]},
        'lr': {'max': 1.0, 'min': 0.0001},
        'noise': {'max': 1.0, 'min': 0.}
    }
}

sweep_id=wandb.sweep(sweep_config, project="test_sweep")
wandb.agent(sweep_id=sweep_id, function=train_model, count=5)
```

when run in ipython with the command `%run myscript.py` results in the following error:

```
wandb: ERROR Run -------- errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File "---/lib/python3.12/site-packages/wandb/agents/pyagent.py", line 300, in _run_job
wandb: ERROR     wandb.sdk.wandb_setup._setup(_reset=True)
wandb: ERROR   File "---/lib/python3.12/site-packages/wandb/sdk/wandb_setup.py", line 323, in _setup
wandb: ERROR     teardown()
wandb: ERROR   File "---/lib/python3.12/site-packages/wandb/sdk/wandb_setup.py", line 405, in teardown
wandb: ERROR     setup_instance._teardown(exit_code=exit_code)
wandb: ERROR   File "---/lib/python3.12/site-packages/wandb/sdk/wandb_setup.py", line 276, in _teardown
wandb: ERROR     internal_exit_code = self._connection.teardown(exit_code or 0)
wandb: ERROR                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "---/lib/python3.12/site-packages/wandb/sdk/lib/service_connection.py", line 197, in teardown
wandb: ERROR     raise WandbServiceNotOwnedError(
wandb: ERROR wandb.sdk.lib.service_connection.WandbServiceNotOwnedError: Cannot tear down service started by different process
```

Of course there is the solution just mentioned, but I don't understand this behavior. Python 3.12.7, IPython 8.29.0,  wandb 0.18.7

**Comment by lrast** [comment]
I forgot to mention. This behavior requires there to be multiple worker process in the dataloader
```
    def train_dataloader(self):
        return DataLoader(self.my_dataset, batch_size=100,shuffle=True, num_workers=2)
```
with only one worker, there is no issue.

**Comment by aajais** [comment]
Hi, I wasn’t able to reproduce this behavior on my end. It seems that both sweep configs you provided are identical. Could you please share the correct modified sweep config so I can investigate this further?

**Comment by lrast** [comment]
The sweep configs _are_ identical. The only difference between the functional code and the error code  is that the code that produces the error runs `wandb.agent(...)` outside of `if __name__ == '__main__':`

This applies when the sweep script is run using the ipython command `%run myscript.py`.

### This script should produce an error when run using ipython `%run`:
```
import pytorch_lightning as pl
import torch.nn.functional as F
import torch
from pytorch_lightning.loggers import WandbLogger
import wandb
from torch.utils.data import DataLoader,Dataset
import os

import torch
from torch.utils.data import Dataset


class MyDataset(Dataset):
    def __init__(self, data, labels):
        self.data = data
        self.labels = labels

    def __len__(self):
        return len(self.data)

    def __getitem__(self, index):
        x = self.data[index]
        y = self.labels[index]
        return x, y
    
class MyDataModule(pl.LightningDataModule):
    def __init__(self, config):
        super().__init__()
        N=10000   
        x = torch.unsqueeze(torch.linspace(-1, 1, N), dim=1)                    
        y = x.pow(2) + config.noise*torch.rand(x.size())                             
        self.my_dataset = MyDataset(x,y)
        print(config.noise)

    def train_dataloader(self):
        return DataLoader(self.my_dataset, batch_size=100,shuffle=True, num_workers=2)

    def val_dataloader(self):
        return DataLoader(self.my_dataset,batch_size=100,shuffle=False)


class Net(torch.nn.Module):
    def __init__(self, n_feature, n_hidden, n_output):
        super(Net, self).__init__()
        self.hidden = torch.nn.Linear(n_feature, n_hidden)
        self.predict = torch.nn.Linear(n_hidden, n_output)
    def forward(self, x):
        x= F.relu(self.hidden(x))
        x = self.predict(x)
        return x

class MyLightningModule(pl.LightningModule):
    def __init__(self, config): #n_hidden, lr):
        super().__init__()
        self.net = Net(n_feature=1, n_hidden=config.n_hidden, n_output=1)
        self.lr = config.lr

    def training_step(self, batch, batch_idx):
        # training_step defines the train loop.
        x, y = batch
        y_hat = self.net(x)
        loss = F.mse_loss(y_hat, x)
        self.log('training_loss',loss,on_step=True, on_epoch=True,prog_bar=True)
        return loss
    
    def validation_step(self, batch, batch_idx):
        x, y = batch
        y_hat = self.net(x)
        loss = F.mse_loss(y_hat, x)
        self.log('validation_loss',loss)
        return loss

    def configure_optimizers(self):
        optimizer = torch.optim.SGD(self.parameters(), lr=self.lr)
        return optimizer


def train_model():
    wandb.init(project="sweep")
    config=wandb.config
    wandb_logger = WandbLogger()
    data = MyDataModule(config)
    module = MyLightningModule(config)

    wandb_logger.watch(module.net)
    
    trainer = pl.Trainer(accelerator='gpu', devices=1, max_epochs=10, 
        default_root_dir="./lightning-example", logger=wandb_logger)
    trainer.fit(module, data)        


sweep_config = {
    'method': 'random',
    'name': 'first_sweep',
    'metric': {
        'goal': 'minimize',
        'name': 'validation_loss'
    },
    'parameters': {
        'n_hidden': {'values': [2,3,5,10]},
        'lr': {'max': 1.0, 'min': 0.0001},
        'noise': {'max': 1.0, 'min': 0.}
    }
}

sweep_id = wandb.sweep(sweep_config, project="test_sweep")

wandb.agent(sweep_id=sweep_id, function=train_model, count=5)
```

### This script should perform a sweep without error:
```
import pytorch_lightning as pl
import torch.nn.functional as F
import torch
from pytorch_lightning.loggers import WandbLogger
import wandb
from torch.utils.data import DataLoader,Dataset
import os

import torch
from torch.utils.data import Dataset


class MyDataset(Dataset):
    def __init__(self, data, labels):
        self.data = data
        self.labels = labels

    def __len__(self):
        return len(self.data)

    def __getitem__(self, index):
        x = self.data[index]
        y = self.labels[index]
        return x, y
    
class MyDataModule(pl.LightningDataModule):
    def __init__(self, config):
        super().__init__()
        N=10000   
        x = torch.unsqueeze(torch.linspace(-1, 1, N), dim=1)                    
        y = x.pow(2) + config.noise*torch.rand(x.size())                             
        self.my_dataset = MyDataset(x,y)
        print(config.noise)

    def train_dataloader(self):
        return DataLoader(self.my_dataset, batch_size=100,shuffle=True, num_workers=2)

    def val_dataloader(self):
        return DataLoader(self.my_dataset,batch_size=100,shuffle=False)


class Net(torch.nn.Module):
    def __init__(self, n_feature, n_hidden, n_output):
        super(Net, self).__init__()
        self.hidden = torch.nn.Linear(n_feature, n_hidden)
        self.predict = torch.nn.Linear(n_hidden, n_output)
    def forward(self, x):
        x= F.relu(self.hidden(x))
        x = self.predict(x)
        return x

class MyLightningModule(pl.LightningModule):
    def __init__(self, config): #n_hidden, lr):
        super().__init__()
        self.net = Net(n_feature=1, n_hidden=config.n_hidden, n_output=1)
        self.lr = config.lr

    def training_step(self, batch, batch_idx):
        # training_step defines the train loop.
        x, y = batch
        y_hat = self.net(x)
        loss = F.mse_loss(y_hat, x)
        self.log('training_loss',loss,on_step=True, on_epoch=True,prog_bar=True)
        return loss
    
    def validation_step(self, batch, batch_idx):
        x, y = batch
        y_hat = self.net(x)
        loss = F.mse_loss(y_hat, x)
        self.log('validation_loss',loss)
        return loss

    def configure_optimizers(self):
        optimizer = torch.optim.SGD(self.parameters(), lr=self.lr)
        return optimizer


def train_model():
    wandb.init(project="sweep")
    config=wandb.config
    wandb_logger = WandbLogger()
    data = MyDataModule(config)
    module = MyLightningModule(config)

    wandb_logger.watch(module.net)
    
    trainer = pl.Trainer(accelerator='gpu', devices=1, max_epochs=10, 
        default_root_dir="./lightning-example", logger=wandb_logger)
    trainer.fit(module, data)        


sweep_config = {
    'method': 'random',
    'name': 'first_sweep',
    'metric': {
        'goal': 'minimize',
        'name': 'validation_loss'
    },
    'parameters': {
        'n_hidden': {'values': [2,3,5,10]},
        'lr': {'max': 1.0, 'min': 0.0001},
        'noise': {'max': 1.0, 'min': 0.}
    }
}

sweep_id = wandb.sweep(sweep_config, project="test_sweep")

if __name__ == '__main__':
    wandb.agent(sweep_id=sweep_id, function=train_model, count=5)
```

Note that the only difference is in the context where the sweep is run.

pip freeze output:
```
aiohappyeyeballs==2.4.4
aiohttp==3.11.10
aiosignal==1.3.1
annotated-types==0.7.0
asttokens==3.0.0
attrs==24.2.0
certifi==2024.8.30
charset-normalizer==3.4.0
click==8.1.7
decorator==5.1.1
docker-pycreds==0.4.0
executing==2.1.0
filelock==3.16.1
frozenlist==1.5.0
fsspec==2024.10.0
gitdb==4.0.11
GitPython==3.1.43
idna==3.10
ipython==8.30.0
jedi==0.19.2
Jinja2==3.1.4
lightning==2.4.0
lightning-utilities==0.11.9
MarkupSafe==3.0.2
matplotlib-inline==0.1.7
mpmath==1.3.0
multidict==6.1.0
networkx==3.4.2
numpy==2.2.0
packaging==24.2
parso==0.8.4
pexpect==4.9.0
platformdirs==4.3.6
prompt_toolkit==3.0.48
propcache==0.2.1
protobuf==5.29.1
psutil==6.1.0
ptyprocess==0.7.0
pure_eval==0.2.3
pydantic==2.10.3
pydantic_core==2.27.1
Pygments==2.18.0
pytorch-lightning==2.4.0
PyYAML==6.0.2
requests==2.32.3
sentry-sdk==2.19.2
setproctitle==1.3.4
setuptools==75.6.0
six==1.17.0
smmap==5.0.1
stack-data==0.6.3
sympy==1.13.1
torch==2.5.1
torchmetrics==1.6.0
tqdm==4.67.1
traitlets==5.14.3
typing_extensions==4.12.2
urllib3==2.2.3
wandb==0.19.0
wcwidth==0.2.13
yarl==1.18.3
```

**Comment by luisbergua** [comment]
Thanks for clarifying this @lrast! I was able to reproduce the issue now, so will raise it with our engineers. Would it work for you to use this for now?
```
if __name__ == '__main__':
    wandb.agent(sweep_id=sweep_id, function=train_model, count=5)
```

**Comment by lrast** [comment]
Thanks! For my purposes, this solution works just fine.

**Comment by luisbergua** [comment]
Hey @lrast, thanks for your patience! We investigated this, and the problem is actually due to the fact that pytorch-lightning is using the multiprocessing module, in which case you are required to add a main guard as per the multiprocessing library documentation: https://docs.python.org/3/library/multiprocessing.html#the-spawn-and-forkserver-start-methods 

Since this is expected behavior and not a bug I'll be closing this, but please feel free to re-open if you have any different thoughts!
