### ISSUE TITLE
[Bug]: wandb: Network error (ConnectTimeout), entering retry loop when using new wandb-core SDK in offline mode

### ISSUE THREAD

**Issue by theuutkarsh** [wandb/wandb#8957]
### Describe the bug

I am using wandb as a logger with Pytorch-Lightning. Recently, with the new version (0.18.7), I have been facing issues with the `log_text` function. The program is working fine when I run it in `online` mode, but it doesn't work in `offline` mode on a SLURM system. I also tried the previous backend by using `export WANDB__REQUIRE_LEGACY_SERVICE=TRUE` even then, I got the same error. 

On moving back to version 0.18.1, there is no error even on the new backend, but still, it would be good if you could provide some explanations for this problem.

Here are the versions of various software-
```
wandb - 0.18.7
python - 3.11.3
slurm - 23.11.10
linux - 5.14.0
```

This is the output I got when using version 0.18.7 with the new backend-
```
[rank: 0] Seed set to 42
[rank: 2] Seed set to 42
[rank: 3] Seed set to 42
[rank: 1] Seed set to 42
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
[rank: 2] Seed set to 42
Initializing distributed: GLOBAL_RANK: 2, MEMBER: 3/4
[W socket.cpp:663] [c10d] The client socket cannot be initialized to connect to [jrc0202i.jureca]:7010 (errno: 97 - Address family not supported by protocol).
[rank: 3] Seed set to 42
Initializing distributed: GLOBAL_RANK: 3, MEMBER: 4/4
[W socket.cpp:663] [c10d] The client socket cannot be initialized to connect to [jrc0202i.jureca]:7010 (errno: 97 - Address family not supported by protocol).
[rank: 1] Seed set to 42
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/4
[W socket.cpp:663] [c10d] The client socket cannot be initialized to connect to [jrc0202i.jureca]:7010 (errno: 97 - Address family not supported by protocol).
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Tracking run with wandb version 0.18.7
wandb: W&B syncing is set to `offline` in this directory.  
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
wandb: logging graph, to disable use `wandb.watch(log_graph=False)`
[rank: 0] Seed set to 42
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/4
[W socket.cpp:436] [c10d] The server socket cannot be initialized on [::]:7010 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:663] [c10d] The client socket cannot be initialized to connect to [jrc0202i.jureca]:7010 (errno: 97 - Address family not supported by protocol).
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 4 processes
----------------------------------------------------------------------------------------------------

You are using a CUDA device ('NVIDIA A100-SXM4-40GB') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
/p/software/jurecadc/stages/2024/software/PyTorch-Lightning/2.1.3-gcccoreflexiblas-12.3.0-3.3.1/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:639: Checkpoint directory /p/scratch/chkf6/upadhyay1/logs/lightning_logs/secstr_test/test exists and is not empty.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 2 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 3 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1,2,3]

  | Name             | Type        | Params
-------------------------------------------------
0 | encoder          | BERTEncoder | 2.2 K 
1 | downstream_model | Linear      | 45    
-------------------------------------------------
2.3 K     Trainable params
0         Non-trainable params
2.3 K     Total params
0.009     Total estimated model params size (MB)
SLURM auto-requeueing enabled. Setting signal handlers.
SLURM auto-requeueing enabled. Setting signal handlers.
SLURM auto-requeueing enabled. Setting signal handlers.
SLURM auto-requeueing enabled. Setting signal handlers.
/p/software/jurecadc/stages/2024/software/PyTorch-Lightning/2.1.3-gcccoreflexiblas-12.3.0-3.3.1/lib/python3.11/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 2. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/p/software/jurecadc/stages/2024/software/PyTorch-Lightning/2.1.3-gcccoreflexiblas-12.3.0-3.3.1/lib/python3.11/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:268: You requested to overfit but enabled train dataloader shuffling. We are turning off the train dataloader shuffling for you.
`Trainer.fit` stopped: `max_epochs=10` reached.
wandb: Network error (ConnectTimeout), entering retry loop.
```

This is the output I got when using version 0.18.7 with the old backend-
```
wandb: Tracking run with wandb version 0.18.7
wandb: W&B syncing is set to `offline` in this directory.  
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
wandb: logging graph, to disable use `wandb.watch(log_graph=False)`
[rank: 0] Seed set to 42
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/4
[W socket.cpp:436] [c10d] The server socket cannot be initialized on [::]:7010 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:663] [c10d] The client socket cannot be initialized to connect to [jrc0202i.jureca]:7010 (errno: 97 - Address family not supported by protocol).
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 4 processes
----------------------------------------------------------------------------------------------------

You are using a CUDA device ('NVIDIA A100-SXM4-40GB') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
/p/software/jurecadc/stages/2024/software/PyTorch-Lightning/2.1.3-gcccoreflexiblas-12.3.0-3.3.1/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:639: Checkpoint directory /p/scratch/chkf6/upadhyay1/logs/lightning_logs/secstr_test/test exists and is not empty.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 2 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 3 - CUDA_VISIBLE_DEVICES: [0,1,2,3]

  | Name             | Type        | Params
-------------------------------------------------
0 | encoder          | BERTEncoder | 2.2 K 
1 | downstream_model | Linear      | 45    
-------------------------------------------------
2.3 K     Trainable params
0         Non-trainable params
2.3 K     Total params
0.009     Total estimated model params size (MB)
SLURM auto-requeueing enabled. Setting signal handlers.
SLURM auto-requeueing enabled. Setting signal handlers.
SLURM auto-requeueing enabled. Setting signal handlers.
SLURM auto-requeueing enabled. Setting signal handlers.
/p/software/jurecadc/stages/2024/software/PyTorch-Lightning/2.1.3-gcccoreflexiblas-12.3.0-3.3.1/lib/python3.11/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 2. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/p/software/jurecadc/stages/2024/software/PyTorch-Lightning/2.1.3-gcccoreflexiblas-12.3.0-3.3.1/lib/python3.11/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:268: You requested to overfit but enabled train dataloader shuffling. We are turning off the train dataloader shuffling for you.
`Trainer.fit` stopped: `max_epochs=10` reached.
wandb: Network error (ConnectTimeout), entering retry loop.
```

This is the I got when using version 0.18.1 with new backend-

```
[rank: 3] Seed set to 42
[rank: 2] Seed set to 42
[rank: 0] Seed set to 42
[rank: 1] Seed set to 42
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
[rank: 2] Seed set to 42
[rank: 3] Seed set to 42
[rank: 1] Seed set to 42
Initializing distributed: GLOBAL_RANK: 2, MEMBER: 3/4
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/4
Initializing distributed: GLOBAL_RANK: 3, MEMBER: 4/4
[W socket.cpp:663] [c10d] The client socket cannot be initialized to connect to [jrc0444i.jureca]:7010 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:663] [c10d] The client socket cannot be initialized to connect to [jrc0444i.jureca]:7010 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:663] [c10d] The client socket cannot be initialized to connect to [jrc0444i.jureca]:7010 (errno: 97 - Address family not supported by protocol).
wandb: Using wandb-core as the SDK backend. Please refer to https://wandb.me/wandb-core for more information.
wandb: Tracking run with wandb version 0.18.1
wandb: W&B syncing is set to `offline` in this directory.  
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
wandb: logging graph, to disable use `wandb.watch(log_graph=False)`
[rank: 0] Seed set to 42
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/4
[W socket.cpp:436] [c10d] The server socket cannot be initialized on [::]:7010 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:663] [c10d] The client socket cannot be initialized to connect to [jrc0444i.jureca]:7010 (errno: 97 - Address family not supported by protocol).
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 4 processes
----------------------------------------------------------------------------------------------------

You are using a CUDA device ('NVIDIA A100-SXM4-40GB') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
/p/software/jurecadc/stages/2024/software/PyTorch-Lightning/2.1.3-gcccoreflexiblas-12.3.0-3.3.1/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:639: Checkpoint directory /p/scratch/chkf6/upadhyay1/logs/lightning_logs/secstr_test/test exists and is not empty.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 2 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 3 - CUDA_VISIBLE_DEVICES: [0,1,2,3]

  | Name             | Type        | Params
-------------------------------------------------
0 | encoder          | BERTEncoder | 2.2 K 
1 | downstream_model | Linear      | 45    
-------------------------------------------------
2.3 K     Trainable params
0         Non-trainable params
2.3 K     Total params
0.009     Total estimated model params size (MB)
SLURM auto-requeueing enabled. Setting signal handlers.
SLURM auto-requeueing enabled. Setting signal handlers.
SLURM auto-requeueing enabled. Setting signal handlers.
SLURM auto-requeueing enabled. Setting signal handlers.
/p/software/jurecadc/stages/2024/software/PyTorch-Lightning/2.1.3-gcccoreflexiblas-12.3.0-3.3.1/lib/python3.11/site-packages/pytorch_lightning/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 2. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
/p/software/jurecadc/stages/2024/software/PyTorch-Lightning/2.1.3-gcccoreflexiblas-12.3.0-3.3.1/lib/python3.11/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:268: You requested to overfit but enabled train dataloader shuffling. We are turning off the train dataloader shuffling for you.
`Trainer.fit` stopped: `max_epochs=10` reached.

```
I couldn't look at the details but here is the `debug.log` when the **error occurs**-
```
2024-11-27 18:26:14,613 INFO    MainThread:3149 [wandb_setup.py:_flush():79] Current SDK version is 0.18.7
2024-11-27 18:26:14,613 INFO    MainThread:3149 [wandb_setup.py:_flush():79] Configure stats pid to 3149
2024-11-27 18:26:14,613 INFO    MainThread:3149 [wandb_setup.py:_flush():79] Loading settings from /p/home/jusers/upadhyay1/jureca/.config/wandb/settings
2024-11-27 18:26:14,613 INFO    MainThread:3149 [wandb_setup.py:_flush():79] Loading settings from /p/project1/eats-rna/upadhyay1/nucleicbert/wandb/settings
2024-11-27 18:26:14,613 WARNING MainThread:3149 [wandb_setup.py:_flush():79] Unknown environment variable: WANDB_CACHE_DIR
2024-11-27 18:26:14,613 WARNING MainThread:3149 [wandb_setup.py:_flush():79] Unknown environment variable: WANDB_DATA_DIR
2024-11-27 18:26:14,613 WARNING MainThread:3149 [wandb_setup.py:_flush():79] Unknown environment variable: WANDB_CONFIG_DIR
2024-11-27 18:26:14,613 INFO    MainThread:3149 [wandb_setup.py:_flush():79] Loading settings from environment variables: {'root_dir': '/p/scratch/chkf6/upadhyay1/wandb_files/files', 'api_key': '***REDACTED***', '_require_legacy_service': 'TRUE', 'mode': 'offline'}
2024-11-27 18:26:14,613 INFO    MainThread:3149 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': 'offline', '_disable_service': None}
2024-11-27 18:26:14,613 INFO    MainThread:3149 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program_relpath': 'secstr/train.py', 'program_abspath': '/p/project1/eats-rna/upadhyay1/nucleicbert/secstr/train.py', 'program': '/p/project1/eats-rna/upadhyay1/nucleicbert/secstr/train.py'}
2024-11-27 18:26:14,613 INFO    MainThread:3149 [wandb_init.py:_log_setup():533] Logging user logs to /p/scratch/chkf6/upadhyay1/logs/wandb/offline-run-20241127_182614-7ztayk3n/logs/debug.log
2024-11-27 18:26:14,613 INFO    MainThread:3149 [wandb_init.py:_log_setup():534] Logging internal logs to /p/scratch/chkf6/upadhyay1/logs/wandb/offline-run-20241127_182614-7ztayk3n/logs/debug-internal.log
2024-11-27 18:26:14,613 INFO    MainThread:3149 [wandb_init.py:init():619] calling init triggers
2024-11-27 18:26:14,613 INFO    MainThread:3149 [wandb_init.py:init():626] wandb.init called with sweep_config: {}
config: {'config': {'logging_config': {'project': 'secstr_test', 'name': 'test', 'save_dir': '/p/scratch/chkf6/upadhyay1/logs/'}, 'model_config': {'dropout': 0.1, 'hidden_size': 2, 'max_length': 1024, 'num_attention_heads': 2, 'num_hidden_layers': 2, 'vocab_size': 25, 'position_embedding': 'learned'}, 'run_config': {'batch_size': 2, 'frozen': False, 'lr': 1e-06, 'num_workers': 24, 'pretrained_path': None, 'max_epochs': 10, 'use_scheduler': False, 'weight_decay': 0.0, 'data_split_ratio': 0.8, 'tokenizer_file': 'tokenizers/noncoding_seqs.json', 'logger_type': 'wandb', 'internal_logs_freq': 1, 'total_steps': 102317}, 'train_data_config': {'input_dir': '../data/sec_str_data/sec_str.csv', 'max_length': 1024, 'min_length': 20}, 'trainer_config': {'accelerator': 'gpu', 'devices': 4, 'num_nodes': 1, 'log_every_n_steps': 1000, 'strategy': 'ddp_find_unused_parameters_false', 'overfit_batches': 0.1, 'callbacks': [<pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint object at 0x15395b1ed650>, <pytorch_lightning.callbacks.progress.tqdm_progress.TQDMProgressBar object at 0x15395a3d38d0>, <pytorch_lightning.callbacks.model_summary.ModelSummary object at 0x15395a3d0990>]}}, 'model_config': {'dropout': 0.1, 'hidden_size': 2, 'max_length': 1024, 'num_attention_heads': 2, 'num_hidden_layers': 2, 'vocab_size': 25, 'position_embedding': 'learned'}, 'train_data_config': {'input_dir': '../data/sec_str_data/sec_str.csv', 'max_length': 1024, 'min_length': 20}, 'val_data_config': None, 'run_config': {'batch_size': 2, 'frozen': False, 'lr': 1e-06, 'num_workers': 24, 'pretrained_path': None, 'max_epochs': 10, 'use_scheduler': False, 'weight_decay': 0.0, 'data_split_ratio': 0.8, 'tokenizer_file': 'tokenizers/noncoding_seqs.json', 'logger_type': 'wandb', 'internal_logs_freq': 1, 'total_steps': 102317}, 'trainer_config': {'accelerator': 'gpu', 'devices': 4, 'num_nodes': 1, 'log_every_n_steps': 1000, 'strategy': 'ddp_find_unused_parameters_false', 'overfit_batches': 0.1, 'callbacks': [<pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint object at 0x15395b1ed650>, <pytorch_lightning.callbacks.progress.tqdm_progress.TQDMProgressBar object at 0x15395a3d38d0>, <pytorch_lightning.callbacks.model_summary.ModelSummary object at 0x15395a3d0990>]}, 'logging_config': {'project': 'secstr_test', 'name': 'test', 'save_dir': '/p/scratch/chkf6/upadhyay1/logs/'}}
2024-11-27 18:26:14,615 INFO    MainThread:3149 [wandb_init.py:init():669] starting backend
2024-11-27 18:26:14,615 INFO    MainThread:3149 [wandb_init.py:init():673] sending inform_init request
2024-11-27 18:26:14,616 INFO    MainThread:3149 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-11-27 18:26:14,617 INFO    MainThread:3149 [wandb_init.py:init():686] backend started and connected
2024-11-27 18:26:14,620 INFO    MainThread:3149 [wandb_init.py:init():781] updated telemetry
2024-11-27 18:26:14,721 INFO    MainThread:3149 [wandb_init.py:init():814] communicating run to backend with 90.0 second timeout
2024-11-27 18:26:14,725 INFO    MainThread:3149 [wandb_init.py:init():867] starting run threads in backend
2024-11-27 18:26:15,469 INFO    MainThread:3149 [wandb_run.py:_console_start():2456] atexit reg
2024-11-27 18:26:15,469 INFO    MainThread:3149 [wandb_run.py:_redirect():2305] redirect: wrap_raw
2024-11-27 18:26:15,469 INFO    MainThread:3149 [wandb_run.py:_redirect():2370] Wrapping output streams.
2024-11-27 18:26:15,469 INFO    MainThread:3149 [wandb_run.py:_redirect():2395] Redirects installed.
2024-11-27 18:26:15,472 INFO    MainThread:3149 [wandb_init.py:init():911] run started, returning control to user process
2024-11-27 18:26:15,472 INFO    MainThread:3149 [wandb_watch.py:_watch():71] Watching
2024-11-27 18:28:57,123 INFO    MainThread:3149 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/p/software/jurecadc/stages/2024/software/poetry/1.5.1-GCCcore-12.3.0/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/p/software/jurecadc/stages/2024/software/poetry/1.5.1-GCCcore-12.3.0/lib/python3.11/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/p/software/jurecadc/stages/2024/software/poetry/1.5.1-GCCcore-12.3.0/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/p/software/jurecadc/stages/2024/software/poetry/1.5.1-GCCcore-12.3.0/lib/python3.11/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/p/software/jurecadc/stages/2024/software/poetry/1.5.1-GCCcore-12.3.0/lib/python3.11/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/p/software/jurecadc/stages/2024/software/poetry/1.5.1-GCCcore-12.3.0/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/p/software/jurecadc/stages/2024/software/poetry/1.5.1-GCCcore-12.3.0/lib/python3.11/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/p/software/jurecadc/stages/2024/software/poetry/1.5.1-GCCcore-12.3.0/lib/python3.11/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x153934284f50>, 'Connection to api.wandb.ai timed out. (connect timeout=20)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/p/project1/eats-rna/upadhyay1/envs/ml_env/venv/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/p/software/jurecadc/stages/2024/software/poetry/1.5.1-GCCcore-12.3.0/lib/python3.11/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/p/software/jurecadc/stages/2024/software/poetry/1.5.1-GCCcore-12.3.0/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x153934284f50>, 'Connection to api.wandb.ai timed out. (connect timeout=20)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/p/project1/eats-rna/upadhyay1/envs/ml_env/venv/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/p/project1/eats-rna/upadhyay1/envs/ml_env/venv/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 400, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/p/project1/eats-rna/upadhyay1/envs/ml_env/venv/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/p/project1/eats-rna/upadhyay1/envs/ml_env/venv/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/p/project1/eats-rna/upadhyay1/envs/ml_env/venv/lib/python3.11/site-packages/wandb/sdk/lib/gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/p/project1/eats-rna/upadhyay1/envs/ml_env/venv/lib/python3.11/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/p/project1/eats-rna/upadhyay1/envs/ml_env/venv/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/p/project1/eats-rna/upadhyay1/envs/ml_env/venv/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/p/project1/eats-rna/upadhyay1/envs/ml_env/venv/lib/python3.11/site-packages/requests/adapters.py", line 688, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x153934284f50>, 'Connection to api.wandb.ai timed out. (connect timeout=20)'))

```

Please let me know if there is any other fix for this problem.

**Comment by paulosabile-wb** [comment]
Hi @theuutkarsh Good day and thank you for reaching out to us. Happy to help you troubleshoot this.

May I ask for a code snippet so we can see how you are executing your script that generates the errors? This can help us investigate and identify the next steps. Thank you!

**Comment by theuutkarsh** [comment]
Hi, @paulosabile-wb! I can't provide the whole code but here is the function in which I call `log_image` function of wandb.

```
    def on_train_epoch_end(self):
        if self.global_rank == 0 and (self.current_epoch+1)%self.internal_logs_freq == 0:
            self.output['Predictions'].extend(self.prediction)
            self.output['Target'].extend(self.target)
            image = self.cm_plot(self.cm, self.cm_fn)
            self.logger.log_image(key = 'Confusion Matrix', images = [image])
```

I hope it can help in some way. Let me know if more information is needed.

**Comment by creat89** [comment]
Hello @paulosabile-wb ! I have the same issue and I contacted the service client, Aayush Jaiswal, was assigned to my issue and I gave some code snippets as well as the logs.

**Comment by paulosabile-wb** [comment]
Hey @creat89 @theuutkarsh Thanks for sharing more details. Unfortunately, I am unable to reproduce the issue.

Would you mine running a short script for me so we can test offline mode without an actual training or experiment. If this script produces an issue, I would like to request for a copy of `debug-internal.log` and `debug.log` for the affected run. These files are under your local folder `wandb/run-_-/logs` in the same directory where you’re running your code. These files will help us with more details about this error. Thank you and I will be looking forward for your update!

```python
import wandb

# Initialize a run
wandb.init(project="project-name", mode="offline")
# Finish the run
wandb.finish()
```

**Comment by creat89** [comment]
Hello @paulosabile-wb !

So, yesterday (before you) I was contacted by Aayush again (and he gave me a more complex code), to test. At the beginning the code wasn't breaking, so after some trials (looking for what I was trying to log when the error raised in my code), and I found it. I was trying to log a W&B Table! And most importantly, you must be offline (without internet at all), as the screenshots show.

I send the data to Aayush, but here is the code to reproduce the error, in case some other people face something similar.

```
import time

import wandb
import random

run = wandb.init(
    project="your-project",
    entity="your-entity",
    mode="offline",
)

epochs = 10
offset = random.random() / 5
for epoch in range(1, epochs):
    acc = 1 - 2**-epoch - random.random() / epoch - offset
    loss = 2**-epoch + random.random() / epoch + offset
    time.sleep(1)

    # run.log({"loss": loss}, commit=False)
    # run.log({"acc": acc, "epoch": epoch}, commit=False)
    run.log({"table": wandb.Table()})

run.finish()

```
With Internet:
![Image](https://github.com/user-attachments/assets/2ce63f24-ac01-4b5e-93f2-58345377e918)

Without Internet:
![Image](https://github.com/user-attachments/assets/3a6a1720-adfc-4197-9a2e-032866742754)

**Comment by ArtsiomWB** [comment]
Hi @creat89! Thank you very much for updating us in here!

Aayush has escalated the concern to our SDK team who will look into why this behavior is happening. 

Thank you so much for bringing this up to our attention.  

I'll let you know as soon as this behavior gets fixed

**Comment by alvinshao0313** [comment]
I'm having the same issue, if there is a solution please let me know. Thank you very much!

**Comment by theuutkarsh** [comment]
Hi @alvinshao0313, please use old versions (like 0.18.1) of wandb. It is working for me but the new version has some issues.

**Comment by ArtsiomWB** [comment]
Hey guys! I was notified by our eng team that this behavior should be fixed in the next version of wandb.

**Comment by creat89** [comment]
I can confirm that the issue has been solved after this PR: https://github.com/wandb/wandb/pull/9267 and the release https://github.com/wandb/wandb/releases/tag/v0.19.5

@ArtsiomWB could you close the issue?

**Comment by ArtsiomWB** [comment]
Thank you for the follow up! Closing it out!
