### ISSUE TITLE
[Bug]: wandb cli fails to _resolve_org_entity_name 

### ISSUE THREAD

**Issue by AndreaCaliandro** [wandb/wandb#9002]
### Describe the bug

Issue arise when using the cli to download an artifact
```
wandb artifact get --root ./ "my-org/wandb-registry-model/my_model:latest"
```
It get the error message below.

Solution:
in `cli.py` line 2400 change 
`entity = InternalApi()._resolve_org_entity_name(`
with 
`entity = InternalApi().api._resolve_org_entity_name(`

```
#9 0.605 /usr/lib/python3/dist-packages/requests/__init__.py:87: RequestsDependencyWarning: urllib3 (2.2.3) or chardet (4.0.0) doesn't match a supported version!
#9 0.605   warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
#9 1.079 /usr/lib/python3/dist-packages/requests/__init__.py:87: RequestsDependencyWarning: urllib3 (2.2.3) or chardet (4.0.0) doesn't match a supported version!
#9 1.079   warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
#9 1.563 wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
#9 1.830 /usr/lib/python3/dist-packages/requests/__init__.py:87: RequestsDependencyWarning: urllib3 (2.2.3) or chardet (4.0.0) doesn't match a supported version!
#9 1.830   warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
#9 2.301 Traceback (most recent call last):
#9 2.301   File "/usr/local/bin/wandb", line 8, in <module>
#9 2.301     sys.exit(cli())
#9 2.301   File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
#9 2.302     return self.main(*args, **kwargs)
#9 2.302   File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
#9 2.302     rv = self.invoke(ctx)
#9 2.302   File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
#9 2.302     return _process_result(sub_ctx.command.invoke(sub_ctx))
#9 2.302   File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
#9 2.302     return _process_result(sub_ctx.command.invoke(sub_ctx))
#9 2.302   File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
#9 2.303     return ctx.invoke(self.callback, **ctx.params)
#9 2.303   File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
#9 2.303     return __callback(*args, **kwargs)
#9 2.303   File "/usr/local/lib/python3.10/dist-packages/wandb/cli/cli.py", line 104, in wrapper
#9 2.303     return func(*args, **kwargs)
#9 2.303   File "/usr/local/lib/python3.10/dist-packages/wandb/cli/cli.py", line 2400, in get
#9 2.303     entity = InternalApi()._resolve_org_entity_name(
#9 2.303 AttributeError: 'Api' object has no attribute '_resolve_org_entity_name'
```

**Comment by AndreaCaliandro** [comment]
Hi Jason,
as for your request 

1. wandb version is 0.18.7
2. Surprisingly enough, `wandb artifact get` to download a non-registry artifact does works 
3. I can not find the file `wandb/debug.log`, but the traceback is as follow
4. Finally, please note that the model registry I am using is the New W&B Registry. I am mentioning because I found out that `wandb artifact get` appllied to a Legacy W&B Model Registry actually works.


```
Traceback (most recent call last):
  File "/home/andrea/anaconda3/bin/wandb", line 8, in <module>
    sys.exit(cli())
  File "/home/andrea/anaconda3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/andrea/anaconda3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/andrea/anaconda3/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/andrea/anaconda3/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/andrea/anaconda3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/andrea/anaconda3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/andrea/anaconda3/lib/python3.9/site-packages/wandb/cli/cli.py", line 104, in wrapper
    return func(*args, **kwargs)
  File "/home/andrea/anaconda3/lib/python3.9/site-packages/wandb/cli/cli.py", line 2400, in get
    entity = InternalApi()._resolve_org_entity_name(
AttributeError: 'Api' object has no attribute '_resolve_org_entity_name'
```
