### ISSUE TITLE
[Bug]: config bug when using wandb with python-lightning

### ISSUE THREAD

**Issue by Chandery** [wandb/wandb#9091]
### Describe the bug

When using wandb with pytorch-lightning, we use "from lightning.pytorch.loggers import WandbLogger" and use "wandb_logger=WandbLogger()" to define a logger, and then use it as a parameter in object "lightning.Trainer".
It raise a bug when trying to set up a config in the logger througe "wandb_logger.experiment.config.update(conf)"
the error information is:
File "***", line 70, in <module>
    wandb_logger.experiment.config.update(conf)
AttributeError: 'function' object has no attribute 'update'

I update package lightning and wandb trying to solve the problem but failed.

the version of related packages and os are
- wandb 0.19.1
- lightning 2.4.0
- python 3.10.0
- ubuntu 22.04LTS

all the related codes are like
![Image](https://github.com/user-attachments/assets/8e034f22-3a97-403e-8905-5750198268b0)
![Image](https://github.com/user-attachments/assets/53f23a23-e07c-4700-81d1-79e2106c6f21)

**Comment by Chandery** [comment]
> Jason Davenport commented: Hi there! I'd be happy to help troubleshoot this issue with the `WandbLogger` configuration.
> 
> Could you please provide:
> 
> 1. The complete error traceback message
> 2. Your training script, particularly the part where you initialize and configure the WandbLogger
> 3. The `conf` dictionary you're trying to update
> 4. The output of running `wandb.run` right after initializing the WandbLogger
> 
> Additionally, please share your wandb output.log file and the debug.log and debug-internal.log files from the ./wandb/run-date_time-runid/ folder (located in files and logs subfolders).
> 
> This information will help us identify exactly where the configuration update is failing and provide you with the most accurate solution.
> 
> One initial observation: The error `'function' object has no attribute 'update'` suggests that `wandb_logger.experiment` might be returning a function instead of the expected wandb.Run object. This could happen if there's an issue with how the logger is initialized or if there's a timing issue with when the configuration update is attempted.
> 
> Looking forward to helping you resolve this!
> 
> Best regards Jason

[debug-internal.log](https://github.com/user-attachments/files/18154154/debug-internal.log)
[debug.log](https://github.com/user-attachments/files/18154155/debug.log)
[output.log](https://github.com/user-attachments/files/18154156/output.log)
Thank you so much for reply me, the materials have to provide are as follow:
1. the complete error traceback message is like this, is the same as the picture up(at that time I use 4 gpus, so it print 4 times)
![Image](https://github.com/user-attachments/assets/efe5fb6d-9560-4be4-8461-11233a6fdac6)
2. My training script related to WandbLogger and lightning is:
``` python
# ? Logger
    if config.wandb:
        logger = WandbLogger(
            name=config.name,
            project=config.wandb_project,
            id=config.wandb_id,
        )
        # ? Change config to a dictionary
        config_dict = dict(config)
        # ! currently this function has a bug and has raised an issue
        logger.experiment.config.update(config_dict, allow_val_change=True)
    else:
        logger = TensorBoardLogger("Tensorboard", name=config.name)

    # ? DataModule
    datamodule = DataModule(config)

    # ? Trainer
    lit_model = AutoNet(config)
    trainer = L.Trainer(
        max_epochs=config.epochs - elapsed_epochs, devices=config.gpus, logger=logger
    )
    trainer.fit(lit_model, datamodule=datamodule, ckpt_path=ckpt_path)

```
Additionally, I can absolutely be sure that the error is raised during running the sentence `trainer = L.Trainer(max_epochs=config.epochs - elapsed_epochs, devices=config.gpus, logger=logger)`, because at first when I did not add the `allow_val_change=True` in the method `logger.experiment.config.update`, it raise an error about it. This probably means that the error happen in the process of initialization or something during the method `L.Trainer` use it.

3. the config dictionary in the last comment is in the picture one of it, `conf = {"encoder":1, "decoder":2}`; That is a test script, this time I provide the real project script , the conf is a .yaml process by hydra and I make it into dictionary using method `dict()`, see the code above, it is named as "config_dict". For test,  `conf = {"encoder":1, "decoder":2}` is enough.
4. I did it but maybe my way is wrong. It got an error like below.
![Image](https://github.com/user-attachments/assets/13375b19-6a43-44db-b62d-651d18685c52)
![Image](https://github.com/user-attachments/assets/2c29414e-de57-40a8-8346-2c6731cc4961)

Plus, the required log file has been uploaded above.

Looking for your reply, I am so desired to resolve this problem!
Thank you so much again!

**Comment by Chandery** [comment]
> Jason Davenport commented:Jason Davenport 评论道： A few quick clarifications:一些快速的澄清：
> 
> 1. Are you running this with DDP (DistributedDataParallel)?您是否使用 DDP （DistributedDataParallel） 运行此程序？
> 2. Does the error persist if you try running on a single GPU?如果您尝试在单个 GPU 上运行，错误是否仍然存在？
> 3. Could you confirm if the wandb run is properly initialized by checking if a new run appears in your W&B project dashboard when you start training?您能否通过在开始训练时检查您的 W&B 项目仪表板中是否出现新运行来确认 wandb 运行是否已正确初始化？
>    These details will help us identify whether this is a timing issue with the distributed setup or a more fundamental problem with the logger initialization.这些细节将帮助我们确定这是分布式设置的 timing 问题，还是 logger 初始化的更基本问题。

1. I am not running this with DDP
2. Yes, the error persist when running on a single GPU(see the last picture in my last reply, the error info output single time can show this——if running on mutiple GPUs, the error info will output multiple times)
3. I tried it, but because of the error, it did not appear in my W&B project dashboard

**Comment by Chandery** [comment]
> > Jason Davenport commented:Jason Davenport 评论道： A few quick clarifications:
> > 
> > 1. Are you running this with DDP (DistributedDataParallel)?
> > 2. Does the error persist if you try running on a single GPU
> > 3. Could you confirm if the wandb run is properly initialized by checking if a new run appears in your W&B project dashboard when you start training?
> >    These details will help us identify whether this is a timing issue with the distributed setup or a more fundamental problem with the logger initialization.
> 
> 1. I am not running this with DDP
> 2. Yes, the error persist when running on a single GPU(see the last picture in my last reply, the error info output single time can show this——if running on mutiple GPUs, the error info will output multiple times)
> 3. I tried it, but because of the error, it did not appear in my W&B project dashboard

**Comment by ArtsiomWB** [comment]
Hi @Chandery!

I have tried reproing the behavior you are describing above with a example script you have provided, and it looks something like this:
```py
import wandb
from pytorch_lightning.loggers import WandbLogger, TensorBoardLogger
import pytorch_lightning as L
from dataclasses import dataclass
from typing import Optional
import torch
from torch.utils.data import DataLoader, TensorDataset


@dataclass
class Config:
    wandb: bool = True
    name: str = "experiment"
    wandb_project: str = "my_project"
    wandb_id: Optional[str] = None
    epochs: int = 10
    gpus: int = 1
    def turn_dict(self):
        dictionary = {
            "wandb": self.wandb,
            "name": self.name,
            "wandb_project": self.wandb_project,
            "wandb_id": self.wandb_id,
            "epochs": self.epochs,
            "gpus": self.gpus,
        }
        return dictionary


class DataModule(L.LightningDataModule):
    def __init__(self, config):
        super().__init__()
        self.config = config
        self.train_data = None
        self.val_data = None
        
    def setup(self, stage=None):
        # Creating dummy data for demonstration
        # Replace this with your actual dataset
        x = torch.randn(100, 10)  # 100 samples, 10 features
        y = torch.randn(100, 1)   # 100 samples, 1 target
        
        # Create train/val split
        train_size = int(0.8 * len(x))
        self.train_data = TensorDataset(
            x[:train_size], 
            y[:train_size]
        )
        self.val_data = TensorDataset(
            x[train_size:], 
            y[train_size:]
        )
    
    def train_dataloader(self):
        return DataLoader(
            self.train_data, 
            batch_size=32,
            shuffle=True
        )
    
    def val_dataloader(self):
        return DataLoader(
            self.val_data, 
            batch_size=32,
            shuffle=False
        )


class AutoNet(L.LightningModule):
    def __init__(self, config):
        super().__init__()
        self.config = config
        
    def training_step(self, batch, batch_idx):
        pass
    
    def configure_optimizers(self):
        pass


def train(config: Config, ckpt_path: Optional[str] = None):
    elapsed_epochs = 0  

    # ? Logger
    if config.wandb:
        logger = WandbLogger(
            name=config.name,
            project=config.wandb_project,
            id=config.wandb_id,
        )
        # ? Change config to a dictionary
        config_dict = dict(config.turn_dict())
        # ! currently this function has a bug and has raised an issue
        logger.experiment.config.update(config_dict, allow_val_change=True)
    else:
        logger = TensorBoardLogger("Tensorboard", name=config.name)

    # ? DataModule
    datamodule = DataModule(config)

    # ? Trainer
    lit_model = AutoNet(config)
    trainer = L.Trainer(
        max_epochs=config.epochs - elapsed_epochs, 
        devices=config.gpus, 
        logger=logger
    )
    trainer.fit(lit_model, datamodule=datamodule, ckpt_path=ckpt_path)


if __name__ == "__main__":
    config = Config()
    train(config)
```

The interesting part is that I am not running into any errors as you are describing above running the same ptl and wandb versions. Is your workflow looking any similar to this?

**Comment by ArtsiomWB** [comment]
Hi there, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by Chandery** [comment]
> Hi there, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.


Thank you ! I find the problem! Using this script, there is no errors raised again. I compare it with mine, and I find that the only environ-difference is the config.gpus. That is the key. Your config of gpus is an int "1", that means use 1 gpu. When I tried this way(use one gpu with the Trainer config as "devices=1" or "devices=[2]") the problem was solved. But when I config the devices with "[2,3]" or "2" ,  it raise the same error again. The situation happened the same.
Maybe you can try the code like this.

``` python
import wandb
from pytorch_lightning.loggers import WandbLogger, TensorBoardLogger
import pytorch_lightning as L
from dataclasses import dataclass
from typing import Optional
import torch
from torch.utils.data import DataLoader, TensorDataset


@dataclass
class Config:
    wandb: bool = True
    name: str = "experiment"
    wandb_project: str = "my_project"
    wandb_id: Optional[str] = None
    epochs: int = 10
    gpus: int = 1

    def turn_dict(self):
        dictionary = {
            "wandb": self.wandb,
            "name": self.name,
            "wandb_project": self.wandb_project,
            "wandb_id": self.wandb_id,
            "epochs": self.epochs,
            "gpus": self.gpus,
        }
        return dictionary


class DataModule(L.LightningDataModule):
    def __init__(self, config):
        super().__init__()
        self.config = config
        self.train_data = None
        self.val_data = None

    def setup(self, stage=None):
        # Creating dummy data for demonstration
        # Replace this with your actual dataset
        x = torch.randn(100, 10)  # 100 samples, 10 features
        y = torch.randn(100, 1)  # 100 samples, 1 target

        # Create train/val split
        train_size = int(0.8 * len(x))
        self.train_data = TensorDataset(x[:train_size], y[:train_size])
        self.val_data = TensorDataset(x[train_size:], y[train_size:])

    def train_dataloader(self):
        return DataLoader(self.train_data, batch_size=32, shuffle=True)

    def val_dataloader(self):
        return DataLoader(self.val_data, batch_size=32, shuffle=False)


class AutoNet(L.LightningModule):
    def __init__(self, config):
        super().__init__()
        self.config = config

    def training_step(self, batch, batch_idx):
        pass

    def configure_optimizers(self):
        pass


def train(config: Config, ckpt_path: Optional[str] = None):
    elapsed_epochs = 0

    # ? Logger
    if config.wandb:
        logger = WandbLogger(
            name=config.name,
            project=config.wandb_project,
            id=config.wandb_id,
        )
        # ? Change config to a dictionary
        config_dict = dict(config.turn_dict())
        # ! currently this function has a bug and has raised an issue
        logger.experiment.config.update(config_dict, allow_val_change=True)
    else:
        logger = TensorBoardLogger("Tensorboard", name=config.name)

    # ? DataModule
    datamodule = DataModule(config)

    # ? Trainer
    lit_model = AutoNet(config)
    trainer = L.Trainer(
        max_epochs=config.epochs - elapsed_epochs, devices=2, logger=logger
    )
    trainer.fit(lit_model, datamodule=datamodule, ckpt_path=ckpt_path)


if __name__ == "__main__":
    config = Config()
    train(config)
```

**Comment by ArtsiomWB** [comment]
What exact error are you seeing on your end after running the code above?

I am currently running into a:
`RuntimeError: DistributedDataParallel is not needed when a module doesn't have any parameter that requires a gradient.`

Which doesn't seem to be the same error as mentioned in above the thread.

**Comment by Chandery** [comment]
> What exact error are you seeing on your end after running the code above?
> 
> I am currently running into a: `RuntimeError: DistributedDataParallel is not needed when a module doesn't have any parameter that requires a gradient.`
> 
> Which doesn't seem to be the same error as mentioned in above the thread.

The exact error I am seeing is like 
```
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Currently logged in as: chan-der-y (chan-der-y-cv). Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.19.1
wandb: Run data is saved locally in ./wandb/run-20250103_075540-wf44mlmy
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run experiment
wandb: ⭐️ View project at https://wandb.ai/chan-der-y-cv/my_project
wandb: 🚀 View run at https://wandb.ai/chan-der-y-cv/my_project/runs/wf44mlmy
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
/home/cdy/anaconda3/envs/ddpm/lib/python3.10/site-packages/pytorch_lightning/trainer/configuration_validator.py:68: You passed in a `val_dataloader` but have no `validation_step`. Skipping val loop.
You are using a CUDA device ('NVIDIA GeForce RTX 3090') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/2
Traceback (most recent call last):
  File "/home/cdy/HerbDetection/test.py", line 98, in <module>
    train(config)
  File "/home/cdy/HerbDetection/test.py", line 81, in train
    logger.experiment.config.update(config_dict, allow_val_change=True)
AttributeError: 'function' object has no attribute 'update'
[rank: 1] Child process with PID 2347120 terminated with code 1. Forcefully terminating all other processes to avoid zombies 🧟
```

**Comment by aajais** [comment]
Hi @Chandery, Since Artsiom is out of office, I’ll be stepping in to assist for now. After reviewing your issue, I was able to pinpoint the cause. It seems that when you’re using two devices and updating the config, W&B is being initialized on both GPUs. This results in both GPUs attempting to update the config, which isn’t allowed for rank > 0.

To resolve this, you’ll need to ensure that config updates are restricted to the rank 0 device only. I’ve attached a sample code snippet that worked for me in a multi-GPU setup. Could you give it a try and let me know if it resolves the issue?

```
import wandb
from pytorch_lightning.loggers import WandbLogger, TensorBoardLogger
import pytorch_lightning as L
from dataclasses import dataclass
from typing import Optional
import torch
from torch.utils.data import DataLoader, TensorDataset
from pytorch_lightning.utilities import rank_zero_only


@dataclass
class Config:
    wandb: bool = True
    name: str = "experiment"
    wandb_project: str = "my_project"
    wandb_id: Optional[str] = None
    epochs: int = 10
    gpus: int = 1

    def turn_dict(self):
        dictionary = {
            "wandb": self.wandb,
            "name": self.name,
            "wandb_project": self.wandb_project,
            "wandb_id": self.wandb_id,
            "epochs": self.epochs,
            "gpus": self.gpus,
        }
        return dictionary


class DataModule(L.LightningDataModule):
    def __init__(self, config):
        super().__init__()
        self.config = config
        self.train_data = None
        self.val_data = None

    def setup(self, stage=None):
        # Creating dummy data for demonstration
        # Replace this with your actual dataset
        x = torch.randn(100, 10)  # 100 samples, 10 features
        y = torch.randn(100, 1)  # 100 samples, 1 target

        # Create train/val split
        train_size = int(0.8 * len(x))
        self.train_data = TensorDataset(x[:train_size], y[:train_size])
        self.val_data = TensorDataset(x[train_size:], y[train_size:])

    def train_dataloader(self):
        return DataLoader(self.train_data, batch_size=32, shuffle=True)

    def val_dataloader(self):
        return DataLoader(self.val_data, batch_size=32, shuffle=False)


class AutoNet(L.LightningModule):
    def __init__(self, config):
        super().__init__()
        self.config = config

    def training_step(self, batch, batch_idx):
        pass

    def configure_optimizers(self):
        pass


@rank_zero_only
def update_config(logger, config_dict):
    logger.experiment.config.update(config_dict, allow_val_change=True)


def train(config: Config, ckpt_path: Optional[str] = None):
    elapsed_epochs = 0

    # ? Logger
    if config.wandb:
        logger = WandbLogger(
            name=config.name,
            project=config.wandb_project,
            id=config.wandb_id,
        )
        # ? Change config to a dictionary
        update_config(logger, dict(config.turn_dict()))
    else:
        logger = TensorBoardLogger("Tensorboard", name=config.name)

    # ? DataModule
    datamodule = DataModule(config)

    # ? Trainer
    lit_model = AutoNet(config)
    trainer = L.Trainer(
        max_epochs=config.epochs - elapsed_epochs, devices='auto', logger=logger
    )
    trainer.fit(lit_model, datamodule=datamodule, ckpt_path=ckpt_path)


if __name__ == "__main__":
    config = Config()
    train(config)
```

**Comment by Chandery** [comment]
> Hi [@Chandery](https://github.com/Chandery), Since Artsiom is out of office, I’ll be stepping in to assist for now. After reviewing your issue, I was able to pinpoint the cause. It seems that when you’re using two devices and updating the config, W&B is being initialized on both GPUs. This results in both GPUs attempting to update the config, which isn’t allowed for rank > 0.
> 
> To resolve this, you’ll need to ensure that config updates are restricted to the rank 0 device only. I’ve attached a sample code snippet that worked for me in a multi-GPU setup. Could you give it a try and let me know if it resolves the issue?
> 
> ```
> import wandb
> from pytorch_lightning.loggers import WandbLogger, TensorBoardLogger
> import pytorch_lightning as L
> from dataclasses import dataclass
> from typing import Optional
> import torch
> from torch.utils.data import DataLoader, TensorDataset
> from pytorch_lightning.utilities import rank_zero_only
> 
> 
> @dataclass
> class Config:
>     wandb: bool = True
>     name: str = "experiment"
>     wandb_project: str = "my_project"
>     wandb_id: Optional[str] = None
>     epochs: int = 10
>     gpus: int = 1
> 
>     def turn_dict(self):
>         dictionary = {
>             "wandb": self.wandb,
>             "name": self.name,
>             "wandb_project": self.wandb_project,
>             "wandb_id": self.wandb_id,
>             "epochs": self.epochs,
>             "gpus": self.gpus,
>         }
>         return dictionary
> 
> 
> class DataModule(L.LightningDataModule):
>     def __init__(self, config):
>         super().__init__()
>         self.config = config
>         self.train_data = None
>         self.val_data = None
> 
>     def setup(self, stage=None):
>         # Creating dummy data for demonstration
>         # Replace this with your actual dataset
>         x = torch.randn(100, 10)  # 100 samples, 10 features
>         y = torch.randn(100, 1)  # 100 samples, 1 target
> 
>         # Create train/val split
>         train_size = int(0.8 * len(x))
>         self.train_data = TensorDataset(x[:train_size], y[:train_size])
>         self.val_data = TensorDataset(x[train_size:], y[train_size:])
> 
>     def train_dataloader(self):
>         return DataLoader(self.train_data, batch_size=32, shuffle=True)
> 
>     def val_dataloader(self):
>         return DataLoader(self.val_data, batch_size=32, shuffle=False)
> 
> 
> class AutoNet(L.LightningModule):
>     def __init__(self, config):
>         super().__init__()
>         self.config = config
> 
>     def training_step(self, batch, batch_idx):
>         pass
> 
>     def configure_optimizers(self):
>         pass
> 
> 
> @rank_zero_only
> def update_config(logger, config_dict):
>     logger.experiment.config.update(config_dict, allow_val_change=True)
> 
> 
> def train(config: Config, ckpt_path: Optional[str] = None):
>     elapsed_epochs = 0
> 
>     # ? Logger
>     if config.wandb:
>         logger = WandbLogger(
>             name=config.name,
>             project=config.wandb_project,
>             id=config.wandb_id,
>         )
>         # ? Change config to a dictionary
>         update_config(logger, dict(config.turn_dict()))
>     else:
>         logger = TensorBoardLogger("Tensorboard", name=config.name)
> 
>     # ? DataModule
>     datamodule = DataModule(config)
> 
>     # ? Trainer
>     lit_model = AutoNet(config)
>     trainer = L.Trainer(
>         max_epochs=config.epochs - elapsed_epochs, devices='auto', logger=logger
>     )
>     trainer.fit(lit_model, datamodule=datamodule, ckpt_path=ckpt_path)
> 
> 
> if __name__ == "__main__":
>     config = Config()
>     train(config)
> ```

It is resolved! Thank you so much!
